### Import Libraries

In [1]:
import re
import json
import random
import pandas as pd
from elasticsearch import Elasticsearch, helpers
import copy
from thefuzz import fuzz
from thefuzz import process as process
import sqlalchemy as sa
from sqlalchemy import create_engine
from snowflake.sqlalchemy import URL
import os
from dotenv import load_dotenv
load_dotenv()
import time

### Read the unique values

In [2]:
# data_version = "28_11_24"
data_version = "27_01_25"

In [3]:
with open(f"unique_values_{data_version}.json", "r") as fp:
    unique_values = json.load(fp) # data not cleaned in certification

# only for certification refer his version
with open("unique_values_21_10_24.json", "r") as fp:
    unique_values_cert = json.load(fp)

with open(file="./unique_values_22_02_24.json") as f:
    OLD_UNIQUE_VALUES = json.load(f)

with open(f"all_brands_{data_version}.json", "r") as fp:
    all_brands = json.load(fp)
    
with open(f"all_cgrades_{data_version}.json", "r") as fp:
    all_cgrades = json.load(fp)
all_cgrades = [item.lower() for item in all_cgrades]  

with open(f"all_grades_{data_version}.json", "r") as fp:
    all_gradenames = json.load(fp)
all_gradenames = [str(item).lower() for item in all_gradenames]  

with open(file=f"./outOfScopeData_{data_version}.json") as f:
    OOS_Data = json.load(f)

# Application and its respective Industry are reviewed by the Business Team
app_industry_df = pd.read_excel("applications_industry_mapping_gd_reviewed.xlsx") # Index Data
app_industry_df2 = pd.read_excel("applications_industry_mapping_sq_21_11_24.xlsx") # Survey Data


am_region_df = pd.read_excel("Region_data_04_09_24.xlsx", sheet_name='americas')
emea_region_df = pd.read_excel("Region_data_04_09_24.xlsx", sheet_name='europe middle east africa')
ap_region_df = pd.read_excel("Region_data_04_09_24.xlsx", sheet_name='asia pacific')

with open(file="./ul_list_name_value.json") as f:
    ul_list_name_value = json.load(f)

random.shuffle(all_brands)
random.shuffle(all_cgrades)
random.shuffle(all_gradenames)

In [4]:
am_region_df = am_region_df[['Country', 'State', 'City', 'Continent']]
emea_region_df = emea_region_df[['Country', 'State', 'City', 'Continent']]
ap_region_df = ap_region_df[['Country', 'State', 'City', 'Continent']]

In [5]:
unique_values.keys()

dict_keys(['Property', 'Feature', 'UL', 'Certification', 'Auto_Approval', 'Brand', 'Polymer', 'Filler', 'Market', 'Industry_Group'])

In [6]:
len(OOS_Data['grades']), len(all_gradenames)

(13980, 4228)

### Validating ul_list_name_value

In [7]:
ul_list_name_value

{'arc resistance': {'synonyms': ['arc resistance',
   'hvar',
   'arc resistivity',
   'arc resist',
   'arc resistance',
   'high voltage arc resist to ignition',
   'high voltage arc resistant to ignition',
   'high voltage arc resistance to ignition',
   'high voltage arc resistivity to ignition',
   'high voltage arc resist ignition',
   'high voltage arc resistant ignition',
   'high voltage arc resistance ignition',
   'high voltage arc resistivity ignition',
   'high voltage arc',
   'arc resistant',
   'ar',
   'arc r',
   'arcres',
   'arc res'],
  'values': ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  'has_thickness': False,
  'value_priority': False},
 'ball pressure test': {'synonyms': ['ball pressure test',
   'resist to heat',
   'resis to heat',
   'ball pressure',
   'resistance to heat',
   'resistant to heat',
   'bpt',
   'ball test'],
  'values': [],
  'has_thickness': False,
  'value_priority': False},
 'Charpy Unnotched Impact Strength': {'synonyms': ['charpy unnotched impact strength',
   'charpy impact strength unnotched',
   'unnotched charpy impact strength',
   'charpy unnotched imp str',
   'charpy imp str unnotched',
   'unnotched charpy imp str',
   'charpy unnotched imp strength',
   'charpy imp strength unnotched',
   'unnotched charpy imp strength',
   'charpy unnotched impact str',
   'charpy impact str unnotched',
   'unnotched charpy impact str'],
  'values': [],
  'has_thickness': False,
  'value_priority': False},
 'comparative tracking index (cti)': {'synonyms': ['comparative tracking',
   'comparative tracking index',
   'cti',
   'comparative tracking rating',
   'comparative tracking index rating',
   'comp tracking'],
  'values': ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  'has_thickness': False,
  'value_priority': True},
 'dielectric strength': {'synonyms': ['dielectric strength',
   'di strength',
   'dielectric str',
   'di str',
   'diele str',
   'dielec str',
   'dielectrical strength',
   'dc dielectric strength',
   'dielectric strength',
   'di-electric str'],
  'values': [],
  'has_thickness': False,
  'value_priority': False},
 'dimensional change': {'synonyms': ['dimensional change',
   'dim change',
   'dimens change',
   'dimensional chg',
   'di-mensional change'],
  'values': [],
  'has_thickness': False,
  'value_priority': False},
 'flame rating': {'synonyms': ['flame rating',
   'fr',
   'flame rated',
   'flame rate',
   'flame',
   'flamerating',
   'flamerated',
   'flamerate',
   'flammability rating',
   'flammability class rating',
   'flammability rating class',
   'flame rating class',
   'flame class rating'],
  'values': ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  'has_thickness': True,
  'value_priority': True},
 'flammability classification': {'synonyms': ['flame class',
   'flame classification',
   'flameclassification',
   'flammability class'],
  'values': ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  'has_thickness': True,
  'value_priority': False},
 'flexural stress': {'synonyms': ['flexural stress',
   'fs',
   'flex stress',
   'flexstress'],
  'values': [],
  'has_thickness': False,
  'value_priority': False},
 'glow wire flammability index': {'synonyms': ['glow wire flammability index',
   'glow-wire flammability',
   'gwfi',
   'glow wire flammability',
   'glow-wire flammability index',
   'gwf index',
   'glow wire flame index'],
  'values': [],
  'has_thickness': True,
  'value_priority': False},
 'glow wire ignition temperature': {'synonyms': ['glow wire ignition',
   'gwit',
   'glow wire temperature',
   'glow wire temp',
   'glow-wire ignition temperature',
   'gwi temp',
   'gwi temperature'],
  'values': [],
  'has_thickness': True,
  'value_priority': False},
 'glow wire': {'synonyms': ['glow wire', 'glow wire test'],
  'values': [],
  'has_thickness': True,
  'value_priority': False},
 'has linked tds': {'synonyms': ['linked tds', 'tds'],
  'values': ['yes'],
  'has_thickness': False,
  'value_priority': False},
 'high voltage arc tracking rate (hvtr)': {'synonyms': ['high voltage arc tracking rate',
   'hvtr',
   'high voltage arc tracking rate',
   'high vol arc tracking rate',
   'high voltage tracking rate',
   'high voltage arc tracking',
   'voltage arc tracking rate',
   'high voltage rate'],
  'values': ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  'has_thickness': False,
  'value_priority': False},
 'high-current arc ignition (hai)': {'synonyms': ['high-current arc ignition',
   'high current arc ignition',
   'high amp arc ignition',
   'high ampere arc ignition',
   'high amperage arc ignition category',
   'hai',
   'high current arc',
   'high current arc ignition',
   'high arc ignition',
   'arc ignition',
   'hcai',
   'high-current ignition',
   'current ignition',
   'high amp'],
  'values': ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  'has_thickness': True,
  'value_priority': False},
 'hot wire ignition (hwi)': {'synonyms': ['hot wire ignition',
   'hwi',
   'hot-wire ignition',
   'hw ignition',
   'hot wire'],
  'values': ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  'has_thickness': True,
  'value_priority': False},
 'inclined-plane tracking': {'synonyms': ['inclined-plane',
   'ip tracking',
   'ipt',
   'inclined plane',
   'plane tracking',
   'inc-plane track',
   'inc-plane tracking'],
  'values': [],
  'has_thickness': False,
  'value_priority': False},
 'mechanically recycled content': {'synonyms': ['mechanically recycled',
   'mechanical recycled',
   'mech recycled',
   'mechanically rc',
   'mechanical rc',
   'recycled mechanically',
   'recycled content mechanically',
   'recycled content mech',
   'mrc'],
  'values': ['yes'],
  'has_thickness': False,
  'value_priority': False},
 'non-halogenated material': {'synonyms': ['non-halogenated material',
   'nhm',
   'non halo material'],
  'values': ['compliant'],
  'has_thickness': False,
  'value_priority': False},
 'outdoor suitability': {'synonyms': ['outdoor suitability',
   'outdoor durability',
   'out door durability',
   'durability',
   'suitability',
   'out door suitability',
   'os'],
  'values': ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  'has_thickness': False,
  'value_priority': False},
 'detergent resistance': {'synonyms': ['detergent resistance',
   'detergent resistant',
   'detergent resist',
   'detergent resistivity',
   'detergent resis',
   'detergent res',
   'deterres',
   'dr',
   'dres'],
  'values': ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  'has_thickness': False,
  'value_priority': False},
 'relative thermal index - electrical (rti elec) (°c)': {'synonyms': ['relative thermal index electrical',
   'relative thermal index ele',
   'rti-e',
   'rti elec',
   'rti ele',
   'rti electrical',
   'rtie'],
  'values': [],
  'has_thickness': True,
  'value_priority': False},
 'relative thermal index - mechanical impact (rti imp) (°c)': {'synonyms': ['relative thermal index mechanical impact',
   'relative thermal index impact',
   'rti-i',
   'rti imp',
   'rti impact',
   'rtii'],
  'values': [],
  'has_thickness': True,
  'value_priority': False},
 'relative thermal index - mechanical strength (rti str) (°c)': {'synonyms': ['relative thermal index mechanical strength',
   'relative thermal index strength',
   'rti-s',
   'rti str',
   'rti strength',
   'relative thermal index mechanical',
   'rti ms'],
  'values': [],
  'has_thickness': True,
  'value_priority': False},
 'relative thermal index': {'synonyms': ['relative thermal index', 'rti'],
  'values': [],
  'has_thickness': True,
  'value_priority': False},
 'rohs 2011/65/eu material': {'synonyms': ['rohs',
   'rohs and eu',
   'rohs & eu',
   'rohs 2011/65/eu material',
   'rohs material',
   '2011/65/eu material',
   '2011/65/eu',
   'rohs 2011/65/eu mat',
   'rohs mat',
   '2011/65/eu mat'],
  'values': ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  'has_thickness': False,
  'value_priority': False},
 'surface resistivity': {'synonyms': ['surface resistivity',
   'surface resistance',
   'surf res',
   'sur res',
   'resistivity of surface'],
  'values': [],
  'has_thickness': False,
  'value_priority': False},
 'tensile impact strength': {'synonyms': ['tensile impact strength',
   'ten imp str',
   'tensile imp',
   'tensile imp str',
   'ti strength',
   'ti str',
   'tis'],
  'values': [],
  'has_thickness': False,
  'value_priority': False}}

In [8]:
ul_list_name_value['ball pressure test']['synonyms']

['ball pressure test',
 'resist to heat',
 'resis to heat',
 'ball pressure',
 'resistance to heat',
 'resistant to heat',
 'bpt',
 'ball test']

In [9]:
ul_list_name_value['ball pressure test']['synonyms'] = [i for i in ul_list_name_value['ball pressure test']['synonyms'] if i not in ['resis to heat', 'resist to heat', 'resistant to heat', 'resistance to heat']]

In [10]:
ul_list_name_value['ball pressure test']['synonyms']

['ball pressure test', 'ball pressure', 'bpt', 'ball test']

In [11]:
list(ul_list_name_value)

['arc resistance',
 'ball pressure test',
 'Charpy Unnotched Impact Strength',
 'comparative tracking index (cti)',
 'dielectric strength',
 'dimensional change',
 'flame rating',
 'flammability classification',
 'flexural stress',
 'glow wire flammability index',
 'glow wire ignition temperature',
 'glow wire',
 'has linked tds',
 'high voltage arc tracking rate (hvtr)',
 'high-current arc ignition (hai)',
 'hot wire ignition (hwi)',
 'inclined-plane tracking',
 'mechanically recycled content',
 'non-halogenated material',
 'outdoor suitability',
 'detergent resistance',
 'relative thermal index - electrical (rti elec) (°c)',
 'relative thermal index - mechanical impact (rti imp) (°c)',
 'relative thermal index - mechanical strength (rti str) (°c)',
 'relative thermal index',
 'rohs 2011/65/eu material',
 'surface resistivity',
 'tensile impact strength']

In [12]:
del ul_list_name_value['Charpy Unnotched Impact Strength']
del ul_list_name_value['flexural stress']
del ul_list_name_value['surface resistivity']
del ul_list_name_value['mechanically recycled content']
del ul_list_name_value['has linked tds']

### Connect to Database

In [13]:
connection_string = eval(os.getenv('connection_string'))
snowflake_connection_string = connection_string['ml-gst-dev-usscc-01']

parts = snowflake_connection_string.split("//")[1].split("/")  
account = ".".join(parts[0].split('.')[:2]) 
user = parts[1].split('user=')[1].split('&')[0] 
password = parts[1].split('password=')[1].split('&')[0] 
database = parts[1].split('db=')[1].split('&')[0]
warehouse = parts[1].split('warehouse=')[1].split('&')[0]  
role = parts[1].split('role=')[1]

# connect to dev for latest version of the data
engine = create_engine(URL(
    account = account,
    user = user,
    password = password,
    database = 'ANALYTICS_DEV', #database, 
    schema = 'gst_curated',
    warehouse = warehouse,
    role = role
))
cur = engine.connect()



def read_data_from_snowflake_table(cur,query):
    df = pd.read_sql(query, cur)
    return df

### Synonym Data

#### Reading the Data

In [14]:
synonym_df = read_data_from_snowflake_table(cur,"""select * from SYNONYM""")
synonym_df.columns = [x.upper() if x.islower() else x for x in synonym_df.columns]
synonym_df = synonym_df.apply(lambda x: x.str.lower())

synonym_df2 = copy.deepcopy(synonym_df) 
synonym_df2["SYNONYMS"] = synonym_df["SYNONYMS"].str.split(";")
synonym_df2 = synonym_df2.explode("SYNONYMS")
synonym_df2['SYNONYMS'] = synonym_df2['SYNONYMS'].apply(lambda x: re.sub("(\s+)", " ", x.strip().lower()) if x else x)
synonym_df2['DEFINED_NAME'] = synonym_df2['DEFINED_NAME'].apply(lambda x: re.sub("(\s+)", " ", x.strip().lower()) if x else x)
synonym_df2 = synonym_df2.reset_index(drop=True)
synonym_df2 = synonym_df2[~synonym_df2.duplicated()]
synonym_df2

,TYPE,DEFINED_NAME,SYNONYMS
0,auto cert,mercedes-benz,mercedes-benz
1,auto cert,mercedes-benz,daimler
2,auto cert,mercedes-benz,daimler-benz
3,auto cert,mercedes-benz,daimler mercedes
4,auto cert,mercedes-benz,daimler mercedes-benz
...,...,...,...
1551,ul property,relative thermal index - mechanical strength (...,relative thermal index - mechanical strength
1552,ul property,relative thermal index - mechanical strength (...,rti str
1553,ul property,rohs 2011/65/eu material,rohs 2011/65/eu material
1554,ul property,surface resistivity,None
1555,ul property,volume resistivity,None

#### Remove Synonyms

- Incorrect
- Confusing/Ambiguity

In [15]:
remove_syns = []

# remove grades from the synonyms
for g in all_gradenames:
    for s in list(synonym_df2['SYNONYMS']):
        if s and g.lower() == s.lower():
            if s not in remove_syns:
                remove_syns.append(s)

In [16]:
remove_syns

['hhr', 'eco-b', 'htr', 'eco-r']

In [17]:
set(synonym_df2[synonym_df2['SYNONYMS'].duplicated()]['SYNONYMS'])

{'',
 None,
 'heat resistant',
 'im',
 'injection mouldable',
 'thermal conductivity',
 'tm'}

In [18]:
remove_syns += [
    '',
    None,
    'im',
    'eco',
    'injection mouldable',
    'mold shrinkage (md/td)',
    'thermal conductivity',
    'tm',
    'lt',
    'min',
    # 'steel fiber',
    'sf',
    # 'stainless steel fiber',
    # 'ss fiber',
    # 'stainless steel',
    'ss',
    'sr',
    'tp',
    'at',
    'chemical resistance', # appearing in others
    'mi', # 'apprearing in property'
    'heat resistant', # appearing in property
    'impa', # mapped to wrong meaning in the table # ignore
    'impact strength', # it can multiple properties
    'polyester', # it is a poylmer family not 'pbt'
    'htr', # it is a grade
    'hygroscopic', # it is opposite of water resistant
    'ny', # it is a region
    # 'max service temperature',
    # 'min service temperature',
    'metalx', # partial grade name

    'charpy', # charpy not charpy impact strength
    'flammability', 
    'impact', 
    'notched impact', 
    'shore', 
    'shore hardness', 
    'strain at break', 
    'strength', 
    'stress at 100% elongation', 
    'stress at break', 
    'temperature', 
    'tensile', 
    'tensile strength', 
    'tensile stress at 100% elongation', 
    'tensile stress at break', 
    'viscosity',
    'izod',
    'hr',
    'reduce carbon capture, reduced carbon footprint',
    'carbon footprint', 
    'iso 14067', 
    'carbon capture and utilization',
    'ccu',
    'solar resistant',
    'solar resistance',

]
remove_syns

['hhr',
 'eco-b',
 'htr',
 'eco-r',
 '',
 None,
 'im',
 'eco',
 'injection mouldable',
 'mold shrinkage (md/td)',
 'thermal conductivity',
 'tm',
 'lt',
 'min',
 'sf',
 'ss',
 'sr',
 'tp',
 'at',
 'chemical resistance',
 'mi',
 'heat resistant',
 'impa',
 'impact strength',
 'polyester',
 'htr',
 'hygroscopic',
 'ny',
 'metalx',
 'charpy',
 'flammability',
 'impact',
 'notched impact',
 'shore',
 'shore hardness',
 'strain at break',
 'strength',
 'stress at 100% elongation',
 'stress at break',
 'temperature',
 'tensile',
 'tensile strength',
 'tensile stress at 100% elongation',
 'tensile stress at break',
 'viscosity',
 'izod',
 'hr',
 'reduce carbon capture, reduced carbon footprint',
 'carbon footprint',
 'iso 14067',
 'carbon capture and utilization',
 'ccu',
 'solar resistant',
 'solar resistance']

In [19]:
synonym_df2 = synonym_df2[~synonym_df2['SYNONYMS'].isin(remove_syns)]

#### Correct Synonyms

In [20]:
correct_syns = [
    ['property', 'molding shrinkage', 'mold shrinkage (md/td)'],
    ['processing', 'injection molding', 'injection mouldable'],
    ['feature', 'heat stabilized', 'heat resistant'],
    ['feature', 'impact modified', 'im'],
    ['feature', 'chemical resistant', 'chemical resistance'],
    ['property', 'melt mass-flow rate iso 1133 (g/10min)', 'mi'],
    ['feature', 'low wear / low friction', 'friction'],
    ['processing', 'fiber spinning / gel spinning', 'gel extrusion'],
    ['feature', 'laser weldable', 'lt'],
    ['property', 'surface resistivity iec 62631-3-2 (ohm)', 'sr'],
    ['delivery form', 'tape', 'tp'],
    ['polymer', 'pa6t', 'pa6t'],
    ['filler', 'metal', 'sf'],
    ['filler', 'metal', 'ss'],
    ['feature', 'sustainable', 'eco'],
    ['auto cert', 'mercedes-benz', 'mercedes-benz group (daimier)'],
    ['filler', 'cfr-gf', 'cfr gf'],    
    ['filler', 'cfr-cf', 'cfr cf'], 
    ['filler', 'cfr-gf', 'cfr/gf'],    
    ['filler', 'cfr-cf', 'cfr/cf'], 
    ['delivery form', 'micropowder', 'micro powder'],  
    ['delivery form', 'micropowder', 'micro-powder'],
    ['feature', 'hr', 'hr'],
    ['feature', 'low wear / low friction', 'tf'],
    ['polymer', 'polyether', 'polyether'],
    ['filler', 'carbon', 'carbon'], 
    ['feature', 'carbon capture', 'carbon footprint'],
    ['feature', 'carbon capture', 'iso 14067'],
    ['feature', 'carbon capture', 'carbon capture and utilization'],
    ['feature', 'carbon capture', 'ccu'],
    ['feature', 'carbon capture', 'reduce carbon capture'],
    ['feature', 'carbon capture', 'reduced carbon footprint'],
    ['feature', 'u.v. stabilized or stable to weather', 'solar resistance'],

]

synonym_df2 = pd.concat([synonym_df2, pd.DataFrame(correct_syns, columns=synonym_df2.columns)], ignore_index=True)

In [21]:
synonym_df2[synonym_df2['SYNONYMS'].duplicated()]

         TYPE             DEFINED_NAME                  SYNONYMS
1507  feature  low wear / low friction                        tf
1508  polymer                polyether                 polyether
1514  feature           carbon capture     reduce carbon capture
1515  feature           carbon capture  reduced carbon footprint

In [22]:
synonym_df2[synonym_df2['TYPE']=='property'][['DEFINED_NAME', 'SYNONYMS']]

,DEFINED_NAME,SYNONYMS
881,average molecular weight margolies' equation (...,average molecular weight
882,average molecular weight margolies' equation (...,average molar mass
883,average molecular weight margolies' equation (...,average molecular mass
884,average molecular weight margolies' equation (...,avermw
885,average molecular weight margolies' equation (...,molecular weight
...,...,...
1432,water absorption sim. to iso 62 2mm (%),moisture absorption equilibrium 23°c/50% r.h.
1433,wear by sandslurry method (based on gur 4120=100),wear by sandslurry method
1484,molding shrinkage,mold shrinkage (md/td)
1489,melt mass-flow rate iso 1133 (g/10min),mi
1493,surface resistivity iec 62631-3-2 (ohm),sr

### Ignore Terms

Add these terms to the query but not to the output

In [23]:
ignore_terms = [
    'pb',
    'non sustainable',
    'barnacle resistance',
    'crystallinity between 10% and 20%',
    'medical & pharma - drug delivery devices',
    'low ion elution',
    'insect resistant',
    'sardine flavor',
    'steam sterilization',
    'oxidation',
    'heat aging',
    'low ion elution',
    'asa',
    'epdm',
    'pvdf',
    'pvc',
    'robotic extrusion',
    # 'overmolding',
    'pellet size of 40 pellets/g',
    'stress-strain curve',
    'shear of 453.9/mpa',
    'crush test > 20 henhouses-furlong/fortnight',
    'stress-strain curve',
    'additive',
    'additives',
    'adhesion',
    'compressive / bending',
    'crosslinked',
    'food',
    'food contact',
    'molding conditions',
    'nanotube',
    'nanotubes',
    'silicone replacement',
    'stabilisation for copper contact',
    'amorphous',
    'compatibility',
    'long term heat aging',
    'fda',
    'cfr 21',
    'drug master file',
    'device master file',
    'usp',
    'iso 10993',
    'food grade',
    # 'carbon footprint',
    # 'iso 14067',
    # 'carbon capture and utilization',
    # 'carbon capture',
    # 'carbon utilization',
    # 'ccu',
    'bonding',
    'bondable',
    'ltha',
    'dmf',
    'maf',
    'qmtt2 rated',
    'qmtt2 rating',
    'qmtt2 listing',
    'qmtt2 listed',
    'qmtt2',

    # from actual data
    'crush test',
    'stress-strain',
    'pellet size',
    'shear',
    'fmvss',
    
    # model error
    'food contact compliant',
    'fda compliant',

    # prod queries
    'process guide',
    'E140692',
    'CONCENTRATE BLEND DOWN',
    'damping behavior',

    # weightage
    'non sustainable',
    'non sustainable',
    'non sustainable',
]

In [24]:
ignore_terms = [x.strip().lower() for x in ignore_terms]

In [25]:
temp = list(synonym_df2[synonym_df2['TYPE']=='others']['DEFINED_NAME']) + list(synonym_df2[synonym_df2['TYPE']=='others']['SYNONYMS'])
ignore_terms += [x for x in list(set(temp)) if x not in ignore_terms]
ignore_terms = [x for x in ignore_terms if x not in ['toyota']]
ignore_terms

['pb',
 'non sustainable',
 'barnacle resistance',
 'crystallinity between 10% and 20%',
 'medical & pharma - drug delivery devices',
 'low ion elution',
 'insect resistant',
 'sardine flavor',
 'steam sterilization',
 'oxidation',
 'heat aging',
 'low ion elution',
 'asa',
 'epdm',
 'pvdf',
 'pvc',
 'robotic extrusion',
 'pellet size of 40 pellets/g',
 'stress-strain curve',
 'shear of 453.9/mpa',
 'crush test > 20 henhouses-furlong/fortnight',
 'stress-strain curve',
 'additive',
 'additives',
 'adhesion',
 'compressive / bending',
 'crosslinked',
 'food',
 'food contact',
 'molding conditions',
 'nanotube',
 'nanotubes',
 'silicone replacement',
 'stabilisation for copper contact',
 'amorphous',
 'compatibility',
 'long term heat aging',
 'fda',
 'cfr 21',
 'drug master file',
 'device master file',
 'usp',
 'iso 10993',
 'food grade',
 'bonding',
 'bondable',
 'ltha',
 'dmf',
 'maf',
 'qmtt2 rated',
 'qmtt2 rating',
 'qmtt2 listing',
 'qmtt2 listed',
 'qmtt2',
 'crush test',
 'stress-strain',
 'pellet size',
 'shear',
 'fmvss',
 'food contact compliant',
 'fda compliant',
 'process guide',
 'e140692',
 'concentrate blend down',
 'damping behavior',
 'non sustainable',
 'non sustainable',
 'non sustainable',
 'usp 23',
 'cross-linked',
 'usp 88',
 'cross-linking',
 'crosslink',
 'cross-link',
 'crosslinking']

### Check the Defined Names (Synonym mapped to)

In [26]:
set(synonym_df2[synonym_df2['TYPE']=='feature']['DEFINED_NAME'])

{'anti-static',
 'bio-content',
 'carbon capture',
 'chemical resistant',
 'flame retardant',
 'heat stabilized',
 'high flow',
 'high gloss',
 'high viscosity',
 'hr',
 'hydrolysis resistant',
 'hydrophilic',
 'impact modified',
 'improved creep',
 'improved weld line',
 'increased electrical conductivity',
 'increased thermal conductivity',
 'laser direct structurable',
 'laser markable',
 'laser weldable',
 'lead-free soldering resistant',
 'light stabilized',
 'light weight',
 'low emissions',
 'low halide content',
 'low warpage',
 'low wear / low friction',
 'lubricants',
 'medical/healthcare',
 'non-halogenated/red phosphorous free flame retardant',
 'nucleated',
 'plasticizer',
 'platable',
 'recycled content',
 'reduced gloss',
 'release agent',
 'specialty appearance',
 'static dissipative',
 'sustainable',
 'thermal shock resistant',
 'u.v. stabilized',
 'u.v. stabilized or stable to weather',
 'ultrasonic weldable'}

In [27]:
set(synonym_df2[synonym_df2['TYPE']=='filler']['DEFINED_NAME'])

{'aramide fiber',
 'carbon',
 'carbon fiber',
 'carbon powder',
 'cfr-cf',
 'cfr-gf',
 'continuous carbon fiber',
 'continuous glass fiber',
 'glass beads',
 'glass fiber',
 'glass flake',
 'long aramide fiber',
 'long carbon fiber',
 'long glass fiber',
 'long metal fiber',
 'metal',
 'mineral',
 'unfilled',
 'whisker'}

In [28]:
for i in set(synonym_df2[synonym_df2['TYPE']=='auto cert']['DEFINED_NAME']):
    if i not in unique_values['Auto_Approval']:
        print(i)

vw group
mercedes-benz

### Filler

In [29]:
unique_values['Filler'] = [x.lower() for x in unique_values['Filler']]
unique_values['Filler']

['total load',
 'glass fiber',
 'glass beads',
 'unfilled',
 'mineral',
 'carbon fiber',
 'metal',
 'long glass fiber',
 'long carbon fiber',
 'long aramid fiber',
 'long metal fiber',
 'carbon powder',
 'aramid fiber']

In [30]:
filler_syns = synonym_df2[synonym_df2['TYPE']=='filler'][['DEFINED_NAME', 'SYNONYMS']].groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
filler_syns

{'aramide fiber': ['aramide fiber',
  'aramide fibre',
  'aramid fiber',
  'aramid fibre',
  'af',
  'aramide reinforced',
  'aramid reinforced'],
 'carbon': ['carbon'],
 'carbon fiber': ['carbon fiber',
  'carbon fibre',
  'cf',
  'carbon filled',
  'carbon reinforced'],
 'carbon powder': ['carbon powder', 'cd'],
 'cfr-cf': ['cfr cf', 'cfr/cf'],
 'cfr-gf': ['cfr gf', 'cfr/gf'],
 'continuous carbon fiber': ['continuous carbon fiber', 'cfr-cf'],
 'continuous glass fiber': ['continuous glass fiber', 'cfr-gf', 'e-glass'],
 'glass beads': ['glass beads', 'gb', 'glass sphere', 'glass balls'],
 'glass fiber': ['glass fiber',
  'glass',
  'glass filled',
  'fiber',
  'fibre',
  'gf',
  'glass reinforced',
  'reinforced',
  'gr',
  'glas fiber',
  'glass fibre',
  'glas fibre',
  'short fiber',
  'short fibre',
  'g',
  'glass reinforcement',
  'glass content',
  'fiberglass',
  'fibreglass',
  'fiber glass',
  'fibre glass'],
 'glass flake': ['glass flake', 'flake', 'gs'],
 'long aramide fiber': ['long aramide fiber',
  'laf',
  'long aramide fibre',
  'long aramid fiber',
  'long aramid fibre'],
 'long carbon fiber': ['long carbon fiber', 'lcf', 'long carbon fibre'],
 'long glass fiber': ['long glass fiber',
  'lgf',
  'long fiber',
  'continuous fiber',
  'cft',
  'long glass fibre',
  'long fibre',
  'long fiberglass',
  'long fibreglass',
  'long fiber glass',
  'long fibre glass'],
 'long metal fiber': ['long metal fiber',
  'long steel',
  'long steel fiber',
  'long stainless steel',
  'long stainless steel fiber',
  'long ss fiber',
  'long ss',
  'long metal fibre'],
 'metal': ['metal',
  'conductive filler',
  'stainless steel fiber',
  'ss fiber',
  'stainless steel',
  'steel fiber',
  'sf',
  'ss'],
 'mineral': ['mineral', 'talc', 'td', 'md', 'mf'],
 'unfilled': ['unfilled',
  'unreinforced',
  'without glass fiber',
  'without glass',
  'without filler',
  'without glass fibre',
  'no filler',
  'un filled',
  'un-filled',
  'not filled',
  'non-filler',
  'non filler',
  'no fill',
  'without fill',
  'without filled',
  'no load'],
 'whisker': ['whisker', 'glass whisker']}

In [31]:
for f in filler_syns:
    abbs = []
    for abb in filler_syns[f]:
        if len(abb)<4:
            print(abb, "-", f)
            abbs.append(abb)
    filler_syns[f].extend(abbs+abbs+abbs) # adding weightage to the abrreviations


filler_syns

af - aramide fiber
cf - carbon fiber
cd - carbon powder
gb - glass beads
gf - glass fiber
gr - glass fiber
g - glass fiber
gs - glass flake
laf - long aramide fiber
lcf - long carbon fiber
lgf - long glass fiber
cft - long glass fiber
sf - metal
ss - metal
td - mineral
md - mineral
mf - mineral

{'aramide fiber': ['aramide fiber',
  'aramide fibre',
  'aramid fiber',
  'aramid fibre',
  'af',
  'aramide reinforced',
  'aramid reinforced',
  'af',
  'af',
  'af'],
 'carbon': ['carbon'],
 'carbon fiber': ['carbon fiber',
  'carbon fibre',
  'cf',
  'carbon filled',
  'carbon reinforced',
  'cf',
  'cf',
  'cf'],
 'carbon powder': ['carbon powder', 'cd', 'cd', 'cd', 'cd'],
 'cfr-cf': ['cfr cf', 'cfr/cf'],
 'cfr-gf': ['cfr gf', 'cfr/gf'],
 'continuous carbon fiber': ['continuous carbon fiber', 'cfr-cf'],
 'continuous glass fiber': ['continuous glass fiber', 'cfr-gf', 'e-glass'],
 'glass beads': ['glass beads',
  'gb',
  'glass sphere',
  'glass balls',
  'gb',
  'gb',
  'gb'],
 'glass fiber': ['glass fiber',
  'glass',
  'glass filled',
  'fiber',
  'fibre',
  'gf',
  'glass reinforced',
  'reinforced',
  'gr',
  'glas fiber',
  'glass fibre',
  'glas fibre',
  'short fiber',
  'short fibre',
  'g',
  'glass reinforcement',
  'glass content',
  'fiberglass',
  'fibreglass',
  'fiber glass',
  'fibre glass',
  'gf',
  'gr',
  'g',
  'gf',
  'gr',
  'g',
  'gf',
  'gr',
  'g'],
 'glass flake': ['glass flake', 'flake', 'gs', 'gs', 'gs', 'gs'],
 'long aramide fiber': ['long aramide fiber',
  'laf',
  'long aramide fibre',
  'long aramid fiber',
  'long aramid fibre',
  'laf',
  'laf',
  'laf'],
 'long carbon fiber': ['long carbon fiber',
  'lcf',
  'long carbon fibre',
  'lcf',
  'lcf',
  'lcf'],
 'long glass fiber': ['long glass fiber',
  'lgf',
  'long fiber',
  'continuous fiber',
  'cft',
  'long glass fibre',
  'long fibre',
  'long fiberglass',
  'long fibreglass',
  'long fiber glass',
  'long fibre glass',
  'lgf',
  'cft',
  'lgf',
  'cft',
  'lgf',
  'cft'],
 'long metal fiber': ['long metal fiber',
  'long steel',
  'long steel fiber',
  'long stainless steel',
  'long stainless steel fiber',
  'long ss fiber',
  'long ss',
  'long metal fibre'],
 'metal': ['metal',
  'conductive filler',
  'stainless steel fiber',
  'ss fiber',
  'stainless steel',
  'steel fiber',
  'sf',
  'ss',
  'sf',
  'ss',
  'sf',
  'ss',
  'sf',
  'ss'],
 'mineral': ['mineral',
  'talc',
  'td',
  'md',
  'mf',
  'td',
  'md',
  'mf',
  'td',
  'md',
  'mf',
  'td',
  'md',
  'mf'],
 'unfilled': ['unfilled',
  'unreinforced',
  'without glass fiber',
  'without glass',
  'without filler',
  'without glass fibre',
  'no filler',
  'un filled',
  'un-filled',
  'not filled',
  'non-filler',
  'non filler',
  'no fill',
  'without fill',
  'without filled',
  'no load'],
 'whisker': ['whisker', 'glass whisker']}

In [32]:
OOS_Data['fillers']

['whisker', 'natural organic fiber']

In [33]:
if 'glass flake' not in filler_syns:
    filler_syns['glass flake'] = ['glass flake', 'flake', 'gs']
    
filler_syns['natural organic fiber'] = ['natural organic fiber', 'organic fiber', 'natural fiber']

In [34]:
def get_fp_range():
    diff = random.randint(5, 30)
    fp = random.randint(30, 70)    
    return fp, diff, fp-diff, fp+diff

In [35]:
get_fp_range()

(69, 18, 51, 87)

In [36]:
unfilled_syns = [
    "un filled", "un-filled", "unfilled", "not filled", "no filler", "non-filler", "non filler",
    "non filled", "no fill", "without fill", "without filler", "without filled", "no load"
]
for syn in filler_syns['unfilled']:
    if syn not in unfilled_syns:
       unfilled_syns.append(syn)

unfilled_syns

['un filled',
 'un-filled',
 'unfilled',
 'not filled',
 'no filler',
 'non-filler',
 'non filler',
 'non filled',
 'no fill',
 'without fill',
 'without filler',
 'without filled',
 'no load',
 'unreinforced',
 'without glass fiber',
 'without glass',
 'without glass fibre']

In [37]:
del filler_syns['unfilled']

In [38]:
filler_syn_mapping = {}
for f_meaning, f_syns in filler_syns.items():
    for syn in f_syns:
        if len(syn) > 1:
            filler_syn_mapping[syn] = f_meaning
        else:
            print(f"Add examples manually for {f_meaning} synonym '{syn}'", "\n\n")

filler_syn_mapping

Add examples manually for glass fiber synonym 'g'


Add examples manually for glass fiber synonym 'g'


Add examples manually for glass fiber synonym 'g'


Add examples manually for glass fiber synonym 'g'

{'aramide fiber': 'aramide fiber',
 'aramide fibre': 'aramide fiber',
 'aramid fiber': 'aramide fiber',
 'aramid fibre': 'aramide fiber',
 'af': 'aramide fiber',
 'aramide reinforced': 'aramide fiber',
 'aramid reinforced': 'aramide fiber',
 'carbon': 'carbon',
 'carbon fiber': 'carbon fiber',
 'carbon fibre': 'carbon fiber',
 'cf': 'carbon fiber',
 'carbon filled': 'carbon fiber',
 'carbon reinforced': 'carbon fiber',
 'carbon powder': 'carbon powder',
 'cd': 'carbon powder',
 'cfr cf': 'cfr-cf',
 'cfr/cf': 'cfr-cf',
 'cfr gf': 'cfr-gf',
 'cfr/gf': 'cfr-gf',
 'continuous carbon fiber': 'continuous carbon fiber',
 'cfr-cf': 'continuous carbon fiber',
 'continuous glass fiber': 'continuous glass fiber',
 'cfr-gf': 'continuous glass fiber',
 'e-glass': 'continuous glass fiber',
 'glass beads': 'glass beads',
 'gb': 'glass beads',
 'glass sphere': 'glass beads',
 'glass balls': 'glass beads',
 'glass fiber': 'glass fiber',
 'glass': 'glass fiber',
 'glass filled': 'glass fiber',
 'fiber': 'glass fiber',
 'fibre': 'glass fiber',
 'gf': 'glass fiber',
 'glass reinforced': 'glass fiber',
 'reinforced': 'glass fiber',
 'gr': 'glass fiber',
 'glas fiber': 'glass fiber',
 'glass fibre': 'glass fiber',
 'glas fibre': 'glass fiber',
 'short fiber': 'glass fiber',
 'short fibre': 'glass fiber',
 'glass reinforcement': 'glass fiber',
 'glass content': 'glass fiber',
 'fiberglass': 'glass fiber',
 'fibreglass': 'glass fiber',
 'fiber glass': 'glass fiber',
 'fibre glass': 'glass fiber',
 'glass flake': 'glass flake',
 'flake': 'glass flake',
 'gs': 'glass flake',
 'long aramide fiber': 'long aramide fiber',
 'laf': 'long aramide fiber',
 'long aramide fibre': 'long aramide fiber',
 'long aramid fiber': 'long aramide fiber',
 'long aramid fibre': 'long aramide fiber',
 'long carbon fiber': 'long carbon fiber',
 'lcf': 'long carbon fiber',
 'long carbon fibre': 'long carbon fiber',
 'long glass fiber': 'long glass fiber',
 'lgf': 'long glass fiber',
 'long fiber': 'long glass fiber',
 'continuous fiber': 'long glass fiber',
 'cft': 'long glass fiber',
 'long glass fibre': 'long glass fiber',
 'long fibre': 'long glass fiber',
 'long fiberglass': 'long glass fiber',
 'long fibreglass': 'long glass fiber',
 'long fiber glass': 'long glass fiber',
 'long fibre glass': 'long glass fiber',
 'long metal fiber': 'long metal fiber',
 'long steel': 'long metal fiber',
 'long steel fiber': 'long metal fiber',
 'long stainless steel': 'long metal fiber',
 'long stainless steel fiber': 'long metal fiber',
 'long ss fiber': 'long metal fiber',
 'long ss': 'long metal fiber',
 'long metal fibre': 'long metal fiber',
 'metal': 'metal',
 'conductive filler': 'metal',
 'stainless steel fiber': 'metal',
 'ss fiber': 'metal',
 'stainless steel': 'metal',
 'steel fiber': 'metal',
 'sf': 'metal',
 'ss': 'metal',
 'mineral': 'mineral',
 'talc': 'mineral',
 'td': 'mineral',
 'md': 'mineral',
 'mf': 'mineral',
 'whisker': 'whisker',
 'glass whisker': 'whisker',
 'natural organic fiber': 'natural organic fiber',
 'organic fiber': 'natural organic fiber',
 'natural fiber': 'natural organic fiber'}

In [39]:
filler_abbr = []
for i in list(filler_syn_mapping) + unique_values['Filler'] + OOS_Data['fillers']:
    if len(i) < 4 and i!='min':
        filler_abbr.append(i)

filler_abbr

['af',
 'cf',
 'cd',
 'gb',
 'gf',
 'gr',
 'gs',
 'laf',
 'lcf',
 'lgf',
 'cft',
 'sf',
 'ss',
 'td',
 'md',
 'mf']

In [40]:
len(list(filler_syn_mapping) + unique_values['Filler'] + OOS_Data['fillers'] + filler_abbr*5)

191

In [41]:
def get_random_filler():
    is_filler_range = False
    fp1 = random.randint(5, 50)
    fp2 = random.randint(5, 50)
    fp = fp1 + fp2

    all_fillers = unique_values['Filler'] + OOS_Data['fillers']
    fillers = [x.lower() for x in all_fillers if x not in ['Total load', 'total load']]
    filler_syns_list = list(filler_syn_mapping)

    filler_name = random.choice(fillers + filler_syns_list + filler_abbr*5 + ['unfilled']*19 + ['carbon']*4)
    if filler_name == 'unfilled':
        # print("unfilled")
        filler_details =  [{'filler_name': [filler_name]}, {'total_load': {'value': None, 'min': None, 'max': None}}]
        query = unfilled_syns 
    else:       
        filler_name2 = random.choice(fillers)
        
        if filler_name in filler_syns_list:
            syn_meaning1 = filler_syn_mapping[filler_name]
        else:
            syn_meaning1 = filler_name
                    
        if filler_name2 in filler_syns_list:
            syn_meaning2 = filler_syn_mapping[filler_name2]
        else:
            syn_meaning2 = filler_name2

        while (filler_name2 == 'unfilled') or (filler_name == filler_name2) or (syn_meaning1 == syn_meaning2) or (syn_meaning1 in syn_meaning2) or (syn_meaning2 in syn_meaning1):
            filler_name2 = random.choice(fillers)
            if filler_name2 in filler_syns_list:
                syn_meaning2 = filler_syn_mapping[filler_name2]
            else:
                syn_meaning2 = filler_name2

        fp_new, diff, fp_min, fp_max = get_fp_range()
        if len(filler_name) < 4 or len(filler_name2) < 4:
            # print("Abbreviations Scenario")
            pass

        filler_details_templates = [
            [{'filler_name': ['all']}, {'total_load': {'value': fp, 'min': fp-5, 'max': fp+5}}],
            
            [{'filler_name': [syn_meaning1]}, {'total_load': {'value': fp, 'min': fp-5, 'max': fp+5}}],
            [{'filler_name': [syn_meaning1]}, {'total_load': {'value': None, 'min': None, 'max': None}}],
            
            [{'filler_name': [syn_meaning1, syn_meaning2]}, {'total_load': {'value': fp, 'min': fp-5, 'max': fp+5}}],
            [{'filler_name': [syn_meaning1, syn_meaning2]}, {'total_load': {'value': None, 'min': None, 'max': None}}],

            [{'filler_name': ['all']}, {'total_load': {'value': fp, 'min': fp, 'max': None}}],
            [{'filler_name': ['all']}, {'total_load': {'value': fp, 'min': None, 'max': fp}}],
            [{'filler_name': [syn_meaning1]}, {'total_load': {'value': fp, 'min': fp, 'max': None}}],
            [{'filler_name': [syn_meaning1]}, {'total_load': {'value': fp, 'min': None, 'max': fp}}],
            
            [{'filler_name': [syn_meaning1, syn_meaning2]}, {'total_load': {'value': fp, 'min': fp, 'max': None}}],
            [{'filler_name': [syn_meaning1, syn_meaning2]}, {'total_load': {'value': fp, 'min': None, 'max': fp}}],

            [{'filler_name': ['all']}, {'total_load': {'value': fp_new, 'min': fp_min, 'max': fp_max}, "range": True}],
            [{'filler_name': [syn_meaning1]}, {'total_load': {'value': fp_new, 'min': fp_min, 'max': fp_max}, "range": True}],
            [{'filler_name': [syn_meaning1, syn_meaning2]}, {'total_load': {'value': fp_new, 'min': fp_min, 'max': fp_max}, "range": True}],


            # weightage - repeat template
            [{'filler_name': [syn_meaning1]}, {'total_load': {'value': None, 'min': None, 'max': None}}],
            [{'filler_name': [syn_meaning1, syn_meaning2]}, {'total_load': {'value': fp, 'min': fp-5, 'max': fp+5}}],
            [{'filler_name': [syn_meaning1, syn_meaning2]}, {'total_load': {'value': None, 'min': None, 'max': None}}],
        ]
        
        filler_details = random.choice(filler_details_templates)
                
    if filler_name != 'unfilled':
        tl = random.choice(["total load", "combined load", "full load", "total fill", "combined fill", "total filler load", "total content", "load", "filler load"])
        filler_name = random.choice([filler_name, filler_name, filler_name, filler_name, filler_name, filler_name, filler_name.replace(" ", "")])
        if filler_details[0]['filler_name'] == ['all']:
            if "range" in filler_details[1]:
                del filler_details[1]["range"]
                is_filler_range = True
                query_range_without_value = [              
                    f"{tl} of {fp_min} - {fp_max}",
                    f"{tl} {fp_min} - {fp_max}%",
                    f"{tl} of {fp_min}% - {fp_max}%",
                    f"{tl} {fp_min}% to {fp_max}%",
                    f"{tl} ranging between {fp_min}% - {fp_max}%",
                    f"{tl} in the range of {fp_min} - {fp_max}%",
                    f"{tl} range {fp_min} to {fp_max}%",

                    # weightage
                    f"{tl} of {fp_min} - {fp_max}",
                    f"{tl} {fp_min} - {fp_max}",
                    f"{tl} {fp_min} to {fp_max}",
                    f"{tl} ranging between {fp_min} - {fp_max}",
                    f"{tl} in the range of {fp_min} - {fp_max}",
                    f"{tl} range {fp_min} to {fp_max}",
                ]
                query = [
                    f"{tl} {fp_new} with range {diff}%",
                    f"{tl} of {fp_new} with range {diff}%",
                    f"{tl} {fp_new} with {diff}% range",
                    f"{tl} of {fp_new} with {diff}% range",

                    f"{tl} of {fp_new} with +/-{diff}% range",
                    f"{tl} of {fp_new} with range +/-{diff}%",
                    f"{tl} of {fp_new} with +/-{diff}",
                    f"{tl} of {fp_new} with +/-{diff}%",
                    
                    f"{tl} {fp_new} with range {diff}",
                    f"{tl} of {fp_new} with range {diff}",
                    f"{tl} {fp_new} with {diff} range",
                    f"{tl} of {fp_new} with {diff} range",

                    f"{tl} of {fp_new} with +/-{diff} range",
                    f"{tl} of {fp_new} with range +/-{diff}",
                    f"{tl} of {fp_new} with +/-{diff}",
                ]
            else:
                if not filler_details[1]['total_load']['min']:
                    query = [
                        f"{tl} max {fp}",
                        f"{tl} upto {fp}",
                        f"{tl} max {fp}%",
                        f"{tl} upto {fp}%",
                        f"{tl} less than {fp}",
                        f"{tl} less than {fp}%",
                        f"{tl} <{fp}",
                        f"{tl} <{fp}%",
                        
                        # weightage  
                        f"{tl} max {fp}",
                        f"{tl} upto {fp}",
                        f"{tl} less than {fp}",
                        f"{tl} <{fp}",
                    ]
                elif not filler_details[1]['total_load']['max']:
                    query = [
                        f"{tl} min {fp}",
                        f"{tl} at least {fp}",
                        f"{tl} min {fp}%",
                        f"{tl} at least {fp}%",
                        f"{tl} greater than {fp}",
                        f"{tl} greater than {fp}%",
                        f"{tl} >{fp}",
                        f"{tl} >{fp}%",
                        
                        # weightage 
                        f"{tl} min {fp}",
                        f"{tl} at least {fp}",
                        f"{tl} greater than {fp}",
                        f"{tl} >{fp}",
                    ]
                else:
                    query = [
                        f"{tl} {fp}",
                        f"{tl} {fp}%",
                        f"{fp} {tl}",
                        f"{fp}% {tl}",
                        f"{tl} of {fp}%",
                        f"{tl} of {fp}",

                        # weightage
                        f"{tl} {fp}",
                        f"{fp} {tl}",
                        f"{tl} of {fp}",
                    ]
                        
        elif len(filler_details[0]['filler_name']) == 2:
            filler_name2 = random.choice([filler_name2, filler_name2, filler_name2, filler_name2, filler_name2, filler_name2, filler_name2.replace(" ", "")])
            if "range" in filler_details[1]:
                del filler_details[1]["range"]
                is_filler_range = True
                query_range_without_value = [
                    f"{filler_name} {filler_name2} {fp_min} - {fp_max}",
                    f"{filler_name} {filler_name2} {fp_min} - {fp_max}%",
                    f"{filler_name} {filler_name2} {fp_min}% - {fp_max}%",
                    f"{filler_name} {filler_name2} {fp_min}% to {fp_max}%",
                    f"{filler_name} {filler_name2} ranging between {fp_min}% - {fp_max}%",
                    f"{filler_name} {filler_name2} with range of {fp_min} - {fp_max}%",
                    f"{filler_name} {filler_name2} range {fp_min} to {fp_max}%",

                    f"{filler_name} and {filler_name2} {fp_min} - {fp_max}",
                    f"{filler_name} and {filler_name2} {fp_min} - {fp_max}%",
                    f"{filler_name} and {filler_name2} {fp_min}% - {fp_max}%",
                    f"{filler_name} and {filler_name2} {fp_min}% to {fp_max}%",
                    f"{filler_name} and {filler_name2} ranging between {fp_min}% - {fp_max}%",
                    f"{filler_name} and {filler_name2} with range of {fp_min} - {fp_max}%",
                    f"{filler_name} and {filler_name2} range {fp_min} to {fp_max}%",

                    f"{filler_name} {filler_name2} {tl} of {fp_min} - {fp_max}",
                    f"{filler_name} {filler_name2} {tl} {fp_min} - {fp_max}%",
                    f"{filler_name} {filler_name2} {tl} of {fp_min}% - {fp_max}%",
                    f"{filler_name} {filler_name2} {tl} {fp_min}% to {fp_max}%",
                    f"{filler_name} {filler_name2} {tl} ranging between {fp_min}% - {fp_max}%",
                    f"{filler_name} {filler_name2} {tl} with range of {fp_min} - {fp_max}%",
                    f"{filler_name} {filler_name2} {tl} range {fp_min} to {fp_max}%",

                    f"{filler_name} and {filler_name2} {tl} of {fp_min} - {fp_max}",
                    f"{filler_name} and {filler_name2} {tl} {fp_min} - {fp_max}%",
                    f"{filler_name} and {filler_name2} {tl} of {fp_min}% - {fp_max}%",
                    f"{filler_name} and {filler_name2} {tl} {fp_min}% to {fp_max}%",
                    f"{filler_name} and {filler_name2} {tl} ranging between {fp_min}% - {fp_max}%",
                    f"{filler_name} and {filler_name2} {tl} with range of {fp_min} - {fp_max}%",
                    f"{filler_name} and {filler_name2} {tl} range {fp_min} to {fp_max}%",    

                    # weightage
                    f"{filler_name} {filler_name2} {fp_min} - {fp_max}",
                    f"{filler_name} {filler_name2} {fp_min} to {fp_max}",
                    f"{filler_name} {filler_name2} ranging between {fp_min} - {fp_max}",
                    f"{filler_name} {filler_name2} with range of {fp_min} - {fp_max}",
                    f"{filler_name} {filler_name2} range {fp_min} to {fp_max}",

                    f"{filler_name} and {filler_name2} {fp_min} - {fp_max}",
                    f"{filler_name} and {filler_name2} {fp_min} to {fp_max}",
                    f"{filler_name} and {filler_name2} ranging between {fp_min} - {fp_max}",
                    f"{filler_name} and {filler_name2} with range of {fp_min} - {fp_max}",
                    f"{filler_name} and {filler_name2} range {fp_min} to {fp_max}",

                    f"{filler_name} {filler_name2} {tl} of {fp_min} - {fp_max}",
                    f"{filler_name} {filler_name2} {tl} {fp_min} - {fp_max}",
                    f"{filler_name} {filler_name2} {tl} {fp_min} to {fp_max}",
                    f"{filler_name} {filler_name2} {tl} ranging between {fp_min} - {fp_max}",
                    f"{filler_name} {filler_name2} {tl} with range of {fp_min} - {fp_max}",
                    f"{filler_name} {filler_name2} {tl} range {fp_min} to {fp_max}",

                    f"{filler_name} and {filler_name2} {tl} of {fp_min} - {fp_max}",
                    f"{filler_name} and {filler_name2} {tl} {fp_min} - {fp_max}",
                    f"{filler_name} and {filler_name2} {tl} {fp_min} to {fp_max}",
                    f"{filler_name} and {filler_name2} {tl} ranging between {fp_min} - {fp_max}",
                    f"{filler_name} and {filler_name2} {tl} with range of {fp_min} - {fp_max}",
                    f"{filler_name} and {filler_name2} {tl} range {fp_min} to {fp_max}",
                ]
                
                query = [
                    f"{filler_name} {filler_name2} {fp_new} with {diff}% range",
                    f"{filler_name} {filler_name2} {fp_new} with range {diff}%",
                    f"{filler_name} and {filler_name2} {fp_new} with {diff}% range",
                    f"{filler_name} and {filler_name2} {fp_new} with range {diff}%",
                    f"{filler_name} {filler_name2} {fp_new}% with {diff}% range",
                    f"{filler_name} {filler_name2} {fp_new}% with range {diff}%",
                    f"{filler_name} and {filler_name2} {fp_new}% with {diff}% range",
                    f"{filler_name} and {filler_name2} {fp_new}% with range {diff}%",

                    f"{filler_name} {filler_name2} {fp_new} with +/-{diff}%",
                    f"{filler_name} {filler_name2} {fp_new} with +/-{diff}% range",
                    f"{filler_name} and {filler_name2} {fp_new} with +/-{diff}%",
                    f"{filler_name} and {filler_name2} {fp_new} with +/-{diff}% range",
                    f"{filler_name} {filler_name2} {fp_new}% with +/-{diff}%",
                    f"{filler_name} {filler_name2} {fp_new}% with +/-{diff}% range",
                    f"{filler_name} and {filler_name2} {fp_new}% with +/-{diff}%",
                    f"{filler_name} and {filler_name2} {fp_new}% with +/-{diff}% range",
                    
                    f"{filler_name} {filler_name2} {tl} of {fp_new} with {diff}% range",
                    f"{filler_name} {filler_name2} {tl} of {fp_new} with range {diff}%",
                    f"{filler_name} and {filler_name2} {tl} of {fp_new} with {diff}% range",
                    f"{filler_name} and {filler_name2} {tl} of {fp_new} with range {diff}%",

                    f"{filler_name} {filler_name2} {tl} of {fp_new} with +/-{diff}%",
                    f"{filler_name} {filler_name2} {tl} of {fp_new} with +/-{diff}% range",
                    f"{filler_name} and {filler_name2} {tl} of {fp_new} with +/-{diff}%",
                    f"{filler_name} and {filler_name2} {tl} of {fp_new} with +/-{diff}% range",

                    f"{filler_name} {filler_name2} {fp_new} with {diff} range",
                    f"{filler_name} {filler_name2} {fp_new} with range {diff}",
                    f"{filler_name} and {filler_name2} {fp_new} with {diff} range",
                    f"{filler_name} and {filler_name2} {fp_new} with range {diff}",

                    f"{filler_name} {filler_name2} {fp_new} with +/-{diff}",
                    f"{filler_name} {filler_name2} {fp_new} with +/-{diff} range",
                    f"{filler_name} and {filler_name2} {fp_new} with +/-{diff}",
                    f"{filler_name} and {filler_name2} {fp_new} with +/-{diff} range",
                    
                    f"{filler_name} {filler_name2} {tl} of {fp_new} with {diff} range",
                    f"{filler_name} {filler_name2} {tl} of {fp_new} with range {diff}",
                    f"{filler_name} and {filler_name2} {tl} of {fp_new} with {diff} range",
                    f"{filler_name} and {filler_name2} {tl} of {fp_new} with range {diff}",

                    f"{filler_name} {filler_name2} {tl} of {fp_new} with +/-{diff}",
                    f"{filler_name} {filler_name2} {tl} of {fp_new} with +/-{diff} range",
                    f"{filler_name} and {filler_name2} {tl} of {fp_new} with +/-{diff}",
                    f"{filler_name} and {filler_name2} {tl} of {fp_new} with +/-{diff} range",
                ]
                
            elif filler_details[1]['total_load']['value']:
                if not filler_details[1]['total_load']['min']:
                    query = [
                        f"{filler_name} {filler_name2} max {fp}",
                        f"{filler_name} {filler_name2} upto {fp}",
                        f"{filler_name} {filler_name2} max {fp}%",
                        f"{filler_name} {filler_name2} upto {fp}%",
                        f"{filler_name} {filler_name2} less than {fp}",
                        f"{filler_name} {filler_name2} less than {fp}%",
                        f"{filler_name} {filler_name2} <{fp}",
                        f"{filler_name} {filler_name2} <{fp}%",

                        f"{filler_name} {filler_name2} {tl} max {fp}",
                        f"{filler_name} {filler_name2} {tl} upto {fp}",
                        f"{filler_name} {filler_name2} {tl} max {fp}%",
                        f"{filler_name} {filler_name2} {tl} upto {fp}%",
                        f"{filler_name} {filler_name2} {tl} less than {fp}",
                        f"{filler_name} {filler_name2} {tl} less than {fp}%",
                        f"{filler_name} {filler_name2} {tl} <{fp}",
                        f"{filler_name} {filler_name2} {tl} <{fp}%",

                        f"{tl} max {fp} {filler_name} {filler_name2}",
                        f"{tl} upto {fp} {filler_name} {filler_name2}",
                        f"{tl} max {fp}% {filler_name} {filler_name2}",
                        f"{tl} upto {fp}% {filler_name} {filler_name2}",
                        f"{tl} less than {fp} {filler_name} {filler_name2}",
                        f"{tl} less than {fp}% {filler_name} {filler_name2}",
                        f"{tl} <{fp} {filler_name} {filler_name2}",
                        f"{tl} <{fp}% {filler_name} {filler_name2}",

                        # weightage
                        f"{filler_name} {filler_name2} max {fp}",
                        f"{filler_name} {filler_name2} upto {fp}",

                        f"{filler_name} {filler_name2} less than {fp}",
                        f"{filler_name} {filler_name2} <{fp}",

                        f"{filler_name} {filler_name2} {tl} max {fp}",
                        f"{filler_name} {filler_name2} {tl} upto {fp}",

                        f"{filler_name} {filler_name2} {tl} less than {fp}",
                        f"{filler_name} {filler_name2} {tl} <{fp}",

                        f"{tl} max {fp} {filler_name} {filler_name2}",
                        f"{tl} upto {fp} {filler_name} {filler_name2}",

                        f"{tl} less than {fp} {filler_name} {filler_name2}",
                        f"{tl} <{fp} {filler_name} {filler_name2}",
                    ]
                elif not filler_details[1]['total_load']['max']:
                    query = [
                        f"{filler_name} {filler_name2} min {fp}",
                        f"{filler_name} {filler_name2} at least {fp}",
                        f"{filler_name} {filler_name2} min {fp}%",
                        f"{filler_name} {filler_name2} at least {fp}%",
                        f"{filler_name} {filler_name2} greater than {fp}",
                        f"{filler_name} {filler_name2} greater than {fp}%",
                        f"{filler_name} {filler_name2} >{fp}",
                        f"{filler_name} {filler_name2} >{fp}%",

                        f"{filler_name} {filler_name2} {tl} min {fp}",
                        f"{filler_name} {filler_name2} {tl} at least {fp}",
                        f"{filler_name} {filler_name2} {tl} min {fp}%",
                        f"{filler_name} {filler_name2} {tl} at least {fp}%",
                        f"{filler_name} {filler_name2} {tl} greater than {fp}",
                        f"{filler_name} {filler_name2} {tl} greater than {fp}%",
                        f"{filler_name} {filler_name2} {tl} >{fp}",
                        f"{filler_name} {filler_name2} {tl} >{fp}%",

                        f"{tl} min {fp} {filler_name} {filler_name2}",
                        f"{tl} at least {fp} {filler_name} {filler_name2}",
                        f"{tl} min {fp}% {filler_name} {filler_name2}",
                        f"{tl} at least {fp}% {filler_name} {filler_name2}",
                        f"{tl} greater than {fp} {filler_name} {filler_name2}",
                        f"{tl} greater than {fp}% {filler_name} {filler_name2}",
                        f"{tl} >{fp} {filler_name} {filler_name2}",
                        f"{tl} >{fp}% {filler_name} {filler_name2}",

                        # weightage
                        f"{filler_name} {filler_name2} min {fp}",
                        f"{filler_name} {filler_name2} at least {fp}",

                        f"{filler_name} {filler_name2} greater than {fp}",
                        f"{filler_name} {filler_name2} >{fp}",

                        f"{filler_name} {filler_name2} {tl} min {fp}",
                        f"{filler_name} {filler_name2} {tl} at least {fp}",

                        f"{filler_name} {filler_name2} {tl} greater than {fp}",
                        f"{filler_name} {filler_name2} {tl} >{fp}",

                        f"{tl} min {fp} {filler_name} {filler_name2}",
                        f"{tl} at least {fp} {filler_name} {filler_name2}",

                        f"{tl} greater than {fp} {filler_name} {filler_name2}",
                        f"{tl} >{fp} {filler_name} {filler_name2}",
                    ]
                else:
                    query = [
                        f"{filler_name} {filler_name2}{fp}",
                        f"{filler_name} {filler_name2}{fp}%",
                        f"{filler_name}{fp} {filler_name2}",
                        f"{filler_name}{fp}% {filler_name2}", 
                        f"{filler_name} {filler_name2}{fp}",
                        f"{filler_name} {filler_name2}{fp}%",
                        f"{filler_name}{fp} {filler_name2}",
                        f"{filler_name}{fp}% {filler_name2}",
                        
                        f"{filler_name} {fp}{filler_name2}",
                        f"{filler_name} {fp}%{filler_name2}",
                        f"{fp}{filler_name} {filler_name2}",
                        f"{fp}%{filler_name} {filler_name2}", 
                        f"{filler_name} {fp}{filler_name2}",
                        f"{filler_name} {fp}%{filler_name2}",
                        f"{fp}{filler_name} {filler_name2}",
                        f"{fp}%{filler_name} {filler_name2}",
                        
                        f"{filler_name} {filler_name2} {fp}",
                        f"{filler_name} {filler_name2} {fp}%",
                        f"{filler_name}, {filler_name2} {fp}",
                        f"{filler_name}, {filler_name2} {fp}%",
                        f"{filler_name} and {filler_name2} {fp}",
                        f"{filler_name} and {filler_name2} {fp}%",
                        f"{filler_name} {filler_name2} with {fp} {tl}",
                        f"{filler_name} {filler_name2} with {fp}% {tl}",
                        f"{filler_name} and {filler_name2} with {fp} {tl}",
                        f"{filler_name} and {filler_name2} with {fp}% {tl}",
                        f"{filler_name}, {filler_name2} with {fp} {tl}",
                        f"{filler_name}, {filler_name2} with {fp}% {tl}",
                        f"{filler_name} {filler_name2} with {tl} {fp}",
                        f"{filler_name} {filler_name2} with {tl} {fp}%",
                        f"{filler_name}, {filler_name2} with {tl} {fp}",
                        f"{filler_name}, {filler_name2} with {tl} {fp}%",
                        f"{filler_name} and {filler_name2} with {tl} {fp}",
                        f"{filler_name} and {filler_name2} with {tl} {fp}%",
                        f"{tl} of {fp}% with {filler_name} and {filler_name2}",
                        f"{tl} of {fp} with {filler_name} and {filler_name2}",
                        
                        f"{filler_name} {fp1} {filler_name2} {fp2}",
                        f"{filler_name} {fp1} {filler_name2} {fp2}%",
                        f"{filler_name} {fp1}% {filler_name2} {fp2}%",
                        f"{filler_name} {fp1}, {filler_name2} {fp2}",
                        f"{filler_name} {fp1}, {filler_name2} {fp2}%",
                        f"{filler_name} {fp1}%, {filler_name2} {fp2}%",
                        f"{filler_name} {fp1} and {filler_name2} {fp2}",
                        f"{filler_name} {fp1} and {filler_name2} {fp2}%",
                        f"{filler_name} {fp1}% and {filler_name2} {fp2}%",

                        f"{fp1} {filler_name} {fp2} {filler_name2}",
                        f"{fp1} {filler_name} {fp2}% {filler_name2}",
                        f"{fp1}% {filler_name} {fp2}% {filler_name2}",
                        f"{fp1} {filler_name}, {fp2} {filler_name2}",
                        f"{fp1} {filler_name}, {fp2}% {filler_name2}",
                        f"{fp1}% {filler_name}, {fp2}% {filler_name2}",
                        f"{fp1} {filler_name} and {fp2} {filler_name2}",
                        f"{fp1} {filler_name} and {fp2}% {filler_name2}",
                        f"{fp1}% {filler_name} and {fp2}% {filler_name2}",  

                        f"{fp1}% {filler_name} + {fp2}% {filler_name2}",
                        f"{filler_name} {fp1}% + {filler_name2} {fp2}%",
                        f"{fp1} {filler_name} + {fp2} {filler_name2}",
                        f"{filler_name} {fp1} + {filler_name2} {fp2}",

                        f"{fp1}% {filler_name} / {fp2}% {filler_name2}",
                        f"{filler_name} {fp1}% / {filler_name2} {fp2}%",
                        f"{fp1} {filler_name} / {fp2} {filler_name2}",
                        f"{filler_name} {fp1} / {filler_name2} {fp2}",

                        #weightage
                        f"{filler_name} {filler_name2} {fp}",
                        f"{filler_name}, {filler_name2} {fp}",
                        f"{filler_name} and {filler_name2} {fp}",
                        f"{filler_name} {filler_name2} with {fp} {tl}",

                        f"{filler_name} and {filler_name2} with {fp} {tl}",
                        f"{filler_name}, {filler_name2} with {fp} {tl}",

                        f"{filler_name} {filler_name2} with {tl} {fp}",
                        f"{filler_name}, {filler_name2} with {tl} {fp}",
                        f"{filler_name} and {filler_name2} with {tl} {fp}",
                        f"{tl} of {fp} with {filler_name} and {filler_name2}",
                        
                        f"{filler_name} {fp1} {filler_name2} {fp2}",
                        f"{filler_name} {fp1}, {filler_name2} {fp2}",
                        f"{filler_name} {fp1} and {filler_name2} {fp2}",

                        f"{fp1} {filler_name} {fp2} {filler_name2}",
                        f"{fp1} {filler_name}, {fp2} {filler_name2}",
                        f"{fp1} {filler_name} and {fp2} {filler_name2}",

                        f"{fp1} {filler_name} + {fp2} {filler_name2}",
                        f"{filler_name} {fp1} + {filler_name2} {fp2}",

                        f"{fp1} {filler_name} / {fp2} {filler_name2}",
                        f"{filler_name} {fp1} / {filler_name2} {fp2}",


                        f"{filler_name} {fp1} {filler_name2} {fp2}",
                        f"{filler_name} {fp1} {filler_name2} {fp2}%",
                        f"{filler_name} {fp1}% {filler_name2} {fp2}%",
                        f"{filler_name} {fp1}, {filler_name2} {fp2}",
                        f"{filler_name} {fp1}, {filler_name2} {fp2}%",
                        f"{filler_name} {fp1}%, {filler_name2} {fp2}%",
                        f"{filler_name} {fp1} and {filler_name2} {fp2}",
                        f"{filler_name} {fp1} and {filler_name2} {fp2}%",
                        f"{filler_name} {fp1}% and {filler_name2} {fp2}%",

                        f"{fp1} {filler_name} {fp2} {filler_name2}",
                        f"{fp1} {filler_name} {fp2}% {filler_name2}",
                        f"{fp1}% {filler_name} {fp2}% {filler_name2}",
                        f"{fp1} {filler_name}, {fp2} {filler_name2}",
                        f"{fp1} {filler_name}, {fp2}% {filler_name2}",
                        f"{fp1}% {filler_name}, {fp2}% {filler_name2}",
                        f"{fp1} {filler_name} and {fp2} {filler_name2}",
                        f"{fp1} {filler_name} and {fp2}% {filler_name2}",
                        f"{fp1}% {filler_name} and {fp2}% {filler_name2}",

                        f"{fp1}% {filler_name} + {fp2}% {filler_name2}",
                        f"{filler_name} {fp1}% + {filler_name2} {fp2}%",
                        f"{fp1} {filler_name} + {fp2} {filler_name2}",
                        f"{filler_name} {fp1} + {filler_name2} {fp2}",

                        f"{fp1}% {filler_name} / {fp2}% {filler_name2}",
                        f"{filler_name} {fp1}% / {filler_name2} {fp2}%",
                        f"{fp1} {filler_name} / {fp2} {filler_name2}",
                        f"{filler_name} {fp1} / {filler_name2} {fp2}",
                    ]

                    if len(filler_name) <5 and len(filler_name2) <5:
                        # duplicated for more weightage
                        additional = [
                            f"{filler_name}{fp1} {filler_name2}{fp2}",
                            f"{filler_name}{fp1} {filler_name2}{fp2}%",
                            f"{filler_name}{fp1}% {filler_name2}{fp2}",
                            f"{filler_name}{fp1}% {filler_name2}{fp2}%",
                            f"{filler_name}{fp1} and {filler_name2}{fp2}",
                            f"{filler_name}{fp1}% and {filler_name2}{fp2}%",
                            f"{filler_name}{fp1}%, {filler_name2}{fp2}%",
                            f"{filler_name}{fp1}, {filler_name2}{fp2}",
                        
                            f"{fp1}{filler_name} {fp2}{filler_name2}",
                            f"{fp1}{filler_name} {fp2}%{filler_name2}",
                            f"{fp1}%{filler_name} {fp2}{filler_name2}",
                            f"{fp1}%{filler_name} {fp2}%{filler_name2}",
                            f"{fp1}{filler_name} and {fp2}{filler_name2}",
                            f"{fp1}%{filler_name} and {fp2}%{filler_name2}",
                            f"{fp1}{filler_name}, {fp2}{filler_name2}",
                            f"{fp1}%{filler_name}, {fp2}%{filler_name2}",
                            
                            f"{fp1}{filler_name}+{fp2}{filler_name2}",
                            f"{filler_name}{fp1}+{filler_name2}{fp2}",
                            f"{filler_name}{fp1}%+{filler_name2}{fp2}%",
                            
                            f"{fp1}{filler_name}/{fp2}{filler_name2}",
                            f"{filler_name}{fp1}/{filler_name2}{fp2}",
                            f"{filler_name}{fp1}%/{filler_name2}{fp2}%",

                            # weightage
                            f"{filler_name}{fp1} {filler_name2}{fp2}",
                            f"{filler_name}{fp1} {filler_name2}{fp2}",
                            f"{filler_name}{fp1} and {filler_name2}{fp2}",
                            f"{filler_name}{fp1}, {filler_name2}{fp2}",
                        
                            f"{fp1}{filler_name} {fp2}{filler_name2}",
                            f"{fp1}{filler_name} {fp2}{filler_name2}",

                            f"{fp1}{filler_name} and {fp2}{filler_name2}",
                            f"{fp1}{filler_name}, {fp2}{filler_name2}",

                            f"{fp1}{filler_name}+{fp2}{filler_name2}",
                            f"{filler_name}{fp1}+{filler_name2}{fp2}",

                            f"{fp1}{filler_name}/{fp2}{filler_name2}",
                            f"{filler_name}{fp1}/{filler_name2}{fp2}",

                            f"{filler_name}{fp1} {filler_name2}{fp2}",
                            f"{filler_name}{fp1} {filler_name2}{fp2}%",
                            f"{filler_name}{fp1}% {filler_name2}{fp2}",
                            f"{filler_name}{fp1}% {filler_name2}{fp2}%",
                            f"{filler_name}{fp1} and {filler_name2}{fp2}",
                            f"{filler_name}{fp1}% and {filler_name2}{fp2}%",
                            f"{filler_name}{fp1}%, {filler_name2}{fp2}%",
                            f"{filler_name}{fp1}, {filler_name2}{fp2}",
                        
                            f"{fp1}{filler_name} {fp2}{filler_name2}",
                            f"{fp1}{filler_name} {fp2}%{filler_name2}",
                            f"{fp1}%{filler_name} {fp2}{filler_name2}",
                            f"{fp1}%{filler_name} {fp2}%{filler_name2}",
                            f"{fp1}{filler_name} and {fp2}{filler_name2}",
                            f"{fp1}%{filler_name} and {fp2}%{filler_name2}",
                            f"{fp1}{filler_name}, {fp2}{filler_name2}",
                            f"{fp1}%{filler_name}, {fp2}%{filler_name2}",

                            f"{fp1}{filler_name}+{fp2}{filler_name2}",
                            f"{filler_name}{fp1}+{filler_name2}{fp2}",
                            f"{filler_name}{fp1}%+{filler_name2}{fp2}%",
                        
                            f"{fp1}{filler_name}/{fp2}{filler_name2}",
                            f"{filler_name}{fp1}/{filler_name2}{fp2}",
                            f"{filler_name}{fp1}%/{filler_name2}{fp2}%",
                            
                        ]
                        query.extend(additional)
            else:
                query = [
                    f"{filler_name} {filler_name2}",
                    f"{filler_name}, {filler_name2}",
                    f"{filler_name} and {filler_name2}",
                    f"{filler_name} or {filler_name2}",
                    f"{filler_name} / {filler_name2}",
                    f"{filler_name} + {filler_name2}",
                ]

                if len(filler_name) <5 and len(filler_name2) <5:
                    additional = [
                        f"{filler_name}+{filler_name2}",
                        f"{filler_name}+{filler_name2}",
                        f"{filler_name}/{filler_name2}",
                        f"{filler_name}/{filler_name2}",
                    ]
                    query.extend(additional)
        elif filler_details[1]['total_load']['value']:
            if "range" in filler_details[1]:
                del filler_details[1]["range"]
                is_filler_range = True

                query_range_without_value = [
                    f"{filler_name} {fp_min} - {fp_max}",
                    f"{filler_name} {fp_min} - {fp_max}%",
                    f"{filler_name} {fp_min}% - {fp_max}%",
                    f"{filler_name} {fp_min}% to {fp_max}%",
                    f"{filler_name} ranging between {fp_min}% - {fp_max}%",
                    f"{filler_name} in the range of {fp_min} - {fp_max}%",
                    f"{filler_name} range {fp_min} to {fp_max}%",

                    f"{filler_name} {tl} of {fp_min} - {fp_max}",
                    f"{filler_name} {tl} {fp_min} - {fp_max}%",
                    f"{filler_name} {tl} of {fp_min}% - {fp_max}%",
                    f"{filler_name} {tl} {fp_min}% to {fp_max}%",
                    f"{filler_name} {tl} ranging between {fp_min}% - {fp_max}%",
                    f"{filler_name} {tl} in the range of {fp_min} - {fp_max}%",
                    f"{filler_name} {tl} range {fp_min} to {fp_max}%",

                    # weightage
                    f"{filler_name} {fp_min} - {fp_max}",
                    f"{filler_name} {fp_min} to {fp_max}",
                    f"{filler_name} ranging between {fp_min} - {fp_max}",
                    f"{filler_name} in the range of {fp_min} - {fp_max}",
                    f"{filler_name} range {fp_min} to {fp_max}",

                    f"{filler_name} {tl} of {fp_min} - {fp_max}",
                    f"{filler_name} {tl} {fp_min} - {fp_max}",
                    f"{filler_name} {tl} {fp_min} to {fp_max}",
                    f"{filler_name} {tl} ranging between {fp_min} - {fp_max}",
                    f"{filler_name} {tl} in the range of {fp_min} - {fp_max}",
                    f"{filler_name} {tl} range {fp_min} to {fp_max}",
                ]

                query = [
                    f"{filler_name} {fp_new} with range {diff}%",
                    f"{filler_name} {fp_new}% with range {diff}%",
                    f"{filler_name} {fp_new} with {diff}% range",
                    f"{filler_name} {fp_new}% with {diff}% range",
                
                    f"{filler_name} {fp_new} with +/-{diff}% range",
                    f"{filler_name} {fp_new} with range +/-{diff}%",
                    f"{filler_name} {fp_new} with +/-{diff}",
                    f"{filler_name} {fp_new}% with +/-{diff}% range",
                    f"{filler_name} {fp_new}% with range +/-{diff}%",
                    f"{filler_name} {fp_new}% with +/-{diff}%",
                    
                    f"{filler_name} {tl} {fp_new} with range {diff}%",
                    f"{filler_name} {tl} of {fp_new} with range {diff}%",
                    f"{filler_name} {tl} {fp_new} with {diff}% range",
                    f"{filler_name} {tl} of {fp_new} with {diff}% range",

                    f"{filler_name} {tl} of {fp_new} with +/-{diff}% range",
                    f"{filler_name} {tl} of {fp_new} with range +/-{diff}%",
                    f"{filler_name} {tl} of {fp_new} with +/-{diff}",
                    f"{filler_name} {tl} of {fp_new} with +/-{diff}%",

                    f"{filler_name} {fp_new} with range {diff}",
                    f"{filler_name} {fp_new} with {diff} range",
                
                    f"{filler_name} {fp_new} with +/-{diff} range",
                    f"{filler_name} {fp_new} with range +/-{diff}",
                    f"{filler_name} {fp_new} with +/-{diff}",
                    
                    f"{filler_name} {tl} {fp_new} with range {diff}",
                    f"{filler_name} {tl} of {fp_new} with range {diff}",
                    f"{filler_name} {tl} {fp_new} with {diff} range",
                    f"{filler_name} {tl} of {fp_new} with {diff} range",

                    f"{filler_name} {tl} of {fp_new} with +/-{diff} range",
                    f"{filler_name} {tl} of {fp_new} with range +/-{diff}",
                    f"{filler_name} {tl} of {fp_new} with +/-{diff}",
                ]
            else:
                if not filler_details[1]['total_load']['min']:
                    query = [
                        f"{filler_name} max {fp}",
                        f"{filler_name} upto {fp}",
                        f"{filler_name} max {fp}%",
                        f"{filler_name} upto {fp}%",
                        f"{filler_name} less than {fp}",
                        f"{filler_name} less than {fp}%",
                        f"{filler_name} <{fp}",
                        f"{filler_name} <{fp}%",

                        f"{filler_name} {tl} max {fp}",
                        f"{filler_name} {tl} upto {fp}",
                        f"{filler_name} {tl} max {fp}%",
                        f"{filler_name} {tl} upto {fp}%",
                        f"{filler_name} {tl} less than {fp}",
                        f"{filler_name} {tl} less than {fp}%",
                        f"{filler_name} {tl} <{fp}",
                        f"{filler_name} {tl} <{fp}%",

                        f"{tl} max {fp} {filler_name}",
                        f"{tl} upto {fp} {filler_name}",
                        f"{tl} max {fp}% {filler_name}",
                        f"{tl} upto {fp}% {filler_name}",
                        f"{tl} less than {fp} {filler_name}",
                        f"{tl} less than {fp}% {filler_name}",
                        f"{tl} <{fp} {filler_name}",
                        f"{tl} <{fp}% {filler_name}",

                        # weightage
                        f"{filler_name} max {fp}",
                        f"{filler_name} upto {fp}",

                        f"{filler_name} less than {fp}",
                        f"{filler_name} <{fp}",

                        f"{filler_name} {tl} max {fp}",
                        f"{filler_name} {tl} upto {fp}",

                        f"{filler_name} {tl} less than {fp}",
                        f"{filler_name} {tl} <{fp}",

                        f"{tl} max {fp} {filler_name}",
                        f"{tl} upto {fp} {filler_name}",

                        f"{tl} less than {fp} {filler_name}",
                        f"{tl} <{fp} {filler_name}",
                    ]
                elif not filler_details[1]['total_load']['max']:
                    query = [
                        f"{filler_name} min {fp}",
                        f"{filler_name} at least {fp}",
                        f"{filler_name} min {fp}%",
                        f"{filler_name} at least {fp}%",
                        f"{filler_name} greater than {fp}",
                        f"{filler_name} greater than {fp}%",
                        f"{filler_name} >{fp}",
                        f"{filler_name} >{fp}%",

                        f"{filler_name} {tl} min {fp}",
                        f"{filler_name} {tl} at least {fp}",
                        f"{filler_name} {tl} min {fp}%",
                        f"{filler_name} {tl} at least {fp}%",
                        f"{filler_name} {tl} greater than {fp}",
                        f"{filler_name} {tl} greater than {fp}%",
                        f"{filler_name} {tl} >{fp}",
                        f"{filler_name} {tl} >{fp}%",

                        f"{tl} min {fp} {filler_name}",
                        f"{tl} at least {fp} {filler_name}",
                        f"{tl} min {fp}% {filler_name}",
                        f"{tl} at least {fp}% {filler_name}",
                        f"{tl} greater than {fp} {filler_name}",
                        f"{tl} greater than {fp}% {filler_name}",
                        f"{tl} >{fp} {filler_name}",
                        f"{tl} >{fp}% {filler_name}",

                        # weightage
                        f"{filler_name} min {fp}",
                        f"{filler_name} at least {fp}",
                        f"{filler_name} greater than {fp}",
                        f"{filler_name} >{fp}",

                        f"{filler_name} {tl} min {fp}",
                        f"{filler_name} {tl} at least {fp}",
                        f"{filler_name} {tl} greater than {fp}",
                        f"{filler_name} {tl} >{fp}",

                        f"{tl} min {fp} {filler_name}",
                        f"{tl} at least {fp} {filler_name}",
                        f"{tl} greater than {fp} {filler_name}",
                        f"{tl} >{fp} {filler_name}",
                    ]
                else:
                    query = [
                        f"{filler_name} {fp}",
                        f"{filler_name}, {fp}",
                        f"{filler_name} {fp}%",
                        f"{filler_name}, {fp}%",
                        f"{filler_name} - {fp}",
                        f"{filler_name} - {fp}%",
                        f"{filler_name} of {fp}",
                        f"{filler_name} of {fp}%",
                        f"{filler_name} with {tl} {fp}",
                        f"{filler_name} with {tl} {fp}%",
                        f"{tl} of {fp}% with {filler_name}",
                        f"{tl} of {fp} with {filler_name}",
                        f"{fp} {tl} with {filler_name}",
                        f"{fp}% {tl} with {filler_name}",

                        # weightage
                        f"{filler_name} {fp}",
                        f"{filler_name}, {fp}",

                        f"{filler_name} - {fp}",
                        f"{filler_name} of {fp}",

                        f"{filler_name} with {tl} {fp}",
                        f"{tl} of {fp} with {filler_name}",
                        f"{fp} {tl} with {filler_name}",
                    ]
                    if len(filler_name) <5:
                        # duplicated for more weightage
                        additional = [
                            f"{filler_name}{fp}",
                            f"{filler_name}{fp}%",
                            f"{fp}{filler_name}",
                            f"{fp}%{filler_name}",
                            f"{filler_name}{fp}",
                            f"{filler_name}{fp}%",
                            f"{fp}{filler_name}",
                            f"{fp}%{filler_name}",
                            f"{filler_name}{fp}",
                            f"{filler_name}{fp}%",
                            f"{fp}{filler_name}",
                            f"{fp}%{filler_name}",

                            # weightage
                            f"{filler_name}{fp}",
                            f"{fp}{filler_name}",

                            f"{fp}{filler_name}",
                            f"{filler_name}{fp}",
                        ]
                        query.extend(additional)
                
        elif not filler_details[1]['total_load']['value']:
             query = [filler_name]


    if is_filler_range:
        is_without_value = random.choice([False, False, True, True, True])
        if is_without_value:
            filler_details[1]['total_load']['value'] = filler_details[1]['total_load']['min']
            query = random.choice(query_range_without_value)
        else:
            query = random.choice(query)
    else:
        query = random.choice(query)
        
    remove_all = {'filler_name': ['all']}
    filler_details = [i for i in filler_details if i != remove_all]       
    return filler_details, query

In [42]:
for i in range(1, 100):
    print(get_random_filler(), "\n")

([{'filler_name': ['glass fiber']}, {'total_load': {'value': 73, 'min': 68, 'max': 78}}], 'gf 73%')

([{'total_load': {'value': 88, 'min': 88, 'max': None}}], 'load >88%')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'without fill')

([{'filler_name': ['carbon powder', 'long carbon fiber']}, {'total_load': {'value': 55, 'min': 50, 'max': 60}}], 'carbon powder 55%long carbon fiber')

([{'filler_name': ['natural organic fiber']}, {'total_load': {'value': 45, 'min': None, 'max': 45}}], 'natural organic fiber max 45%')

([{'filler_name': ['continuous carbon fiber']}, {'total_load': {'value': 56, 'min': None, 'max': 56}}], 'continuous carbon fiber filler load <56')

([{'filler_name': ['carbon']}, {'total_load': {'value': 46, 'min': 46, 'max': None}}], 'carbon load >46')

([{'total_load': {'value': 71, 'min': None, 'max': 71}}], 'load max 71%')

([{'filler_name': ['mineral']}, {'total_load': {'value': 77, 'min': None, 'max': 77}}], 'td full load less than 77%')

([{'filler_name': ['continuous glass fiber', 'whisker']}, {'total_load': {'value': 26, 'min': 21, 'max': 31}}], '15 cfr-gf, 11 whisker')

([{'total_load': {'value': 35, 'min': None, 'max': 35}}], 'total filler load less than 35%')

([{'filler_name': ['metal', 'whisker']}, {'total_load': {'value': 30, 'min': 30, 'max': 52}}], 'sf and whisker with range of 30 - 52%')

([{'filler_name': ['carbon fiber']}, {'total_load': {'value': 63, 'min': 58, 'max': 68}}], 'carbon reinforced with filler load 63')

([{'filler_name': ['mineral']}, {'total_load': {'value': 41, 'min': 41, 'max': 67}}], 'md total filler load of 41% - 67%')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'un-filled')

([{'total_load': {'value': 53, 'min': 53, 'max': None}}], 'combined fill >53')

([{'filler_name': ['glass fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'gr')

([{'filler_name': ['metal']}, {'total_load': {'value': 55, 'min': 50, 'max': 60}}], 'ss55')

([{'total_load': {'value': 28, 'min': 28, 'max': None}}], 'filler load >28')

([{'filler_name': ['metal']}, {'total_load': {'value': 29, 'min': 29, 'max': None}}], 'sf total fill >29')

([{'filler_name': ['long aramide fiber', 'mineral']}, {'total_load': {'value': 32, 'min': None, 'max': 32}}], 'laf mineral combined load max 32%')

([{'filler_name': ['aramide fiber', 'carbon powder']}, {'total_load': {'value': 64, 'min': 59, 'max': 69}}], 'aramidfibre 38% and carbonpowder 26%')

([{'total_load': {'value': 51, 'min': 51, 'max': 71}}], 'total content of 51% - 71%')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'not filled')

([{'total_load': {'value': 51, 'min': 26, 'max': 76}}], 'total fill of 51 with 25% range')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'without filled')

([{'filler_name': ['long glass fiber', 'long metal fiber']}, {'total_load': {'value': 53, 'min': 48, 'max': 58}}], '33 long fibre glass / 20 long metal fiber')

([{'total_load': {'value': 61, 'min': 61, 'max': None}}], 'total filler load >61%')

([{'filler_name': ['mineral', 'glass beads']}, {'total_load': {'value': 62, 'min': 57, 'max': 67}}], 'mineral 50 glass beads 12%')

([{'filler_name': ['glass beads']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'glass beads')

([{'filler_name': ['glass flake', 'carbon powder']}, {'total_load': {'value': 55, 'min': 50, 'max': 60}}], 'glass flake 28, carbon powder 27%')

([{'filler_name': ['glass fiber', 'mineral']}, {'total_load': {'value': 25, 'min': None, 'max': 25}}], 'fibre mineral upto 25%')

([{'filler_name': ['carbon fiber', 'mineral']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'cf, mineral')

([{'filler_name': ['glass fiber', 'aramide fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'glas fibre or aramid fiber')

([{'total_load': {'value': 42, 'min': 37, 'max': 47}}], 'load of 42%')

([{'filler_name': ['long metal fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'long steel')

([{'filler_name': ['cfr-gf']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'cfr/gf')

([{'filler_name': ['aramide fiber', 'whisker']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'aramide fiber whisker')

([{'filler_name': ['carbon powder']}, {'total_load': {'value': 51, 'min': 46, 'max': 56}}], 'cd, 51%')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'not filled')

([{'filler_name': ['long aramide fiber', 'glass beads']}, {'total_load': {'value': 70, 'min': 65, 'max': 75}}], '70%laf glass beads')

([{'total_load': {'value': 43, 'min': 43, 'max': None}}], 'load min 43%')

([{'filler_name': ['glass fiber', 'natural organic fiber']}, {'total_load': {'value': 30, 'min': 25, 'max': 35}}], 'fibre and natural organic fiber with 30 total filler load')

([{'filler_name': ['metal']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'sf')

([{'filler_name': ['long aramide fiber']}, {'total_load': {'value': 36, 'min': 31, 'max': 41}}], 'laf 36 with +/-5')

([{'filler_name': ['metal']}, {'total_load': {'value': 89, 'min': 89, 'max': None}}], 'combined fill at least 89 sf')

([{'total_load': {'value': 62, 'min': 62, 'max': None}}], 'full load greater than 62%')

([{'filler_name': ['aramide fiber']}, {'total_load': {'value': 30, 'min': 30, 'max': 52}}], 'af 30 - 52')

([{'filler_name': ['glass fiber']}, {'total_load': {'value': 48, 'min': None, 'max': 48}}], 'short fibre total load <48')

([{'filler_name': ['metal', 'natural organic fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'ss + natural organic fiber')

([{'total_load': {'value': 34, 'min': 34, 'max': 72}}], 'total filler load of 34 - 72')

([{'filler_name': ['long glass fiber', 'long carbon fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'long fibreglass long carbon fiber')

([{'total_load': {'value': 21, 'min': None, 'max': 21}}], 'combined fill less than 21%')

([{'filler_name': ['whisker']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'whisker')

([{'total_load': {'value': 29, 'min': 29, 'max': 63}}], 'load of 29 - 63')

([{'filler_name': ['carbon powder']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'carbon powder')

([{'filler_name': ['metal', 'natural organic fiber']}, {'total_load': {'value': 51, 'min': 51, 'max': None}}], 'filler load >51% stainless steel natural organic fiber')

([{'filler_name': ['metal', 'carbon fiber']}, {'total_load': {'value': 71, 'min': None, 'max': 71}}], 'ss carbon fiber upto 71%')

([{'total_load': {'value': 47, 'min': 47, 'max': 79}}], 'full load 47 to 79')

([{'total_load': {'value': 43, 'min': 43, 'max': None}}], 'full load >43%')

([{'filler_name': ['long metal fiber', 'carbon powder']}, {'total_load': {'value': 66, 'min': None, 'max': 66}}], 'total load less than 66 long metal fibre carbon powder')

([{'total_load': {'value': 42, 'min': 37, 'max': 47}}], 'full load of 42')

([{'total_load': {'value': 66, 'min': 61, 'max': 71}}], '66% full load')

([{'filler_name': ['long glass fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'cft')

([{'total_load': {'value': 41, 'min': 17, 'max': 65}}], 'combined load of 41 with +/-24')

([{'filler_name': ['long metal fiber', 'carbon powder']}, {'total_load': {'value': 43, 'min': None, 'max': 43}}], 'long metal fibre carbonpowder total fill less than 43')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'without filler')

([{'filler_name': ['glass fiber']}, {'total_load': {'value': 20, 'min': 20, 'max': None}}], 'glass content filler load at least 20%')

([{'total_load': {'value': 55, 'min': 50, 'max': 60}}], 'total load of 55')

([{'filler_name': ['long metal fiber', 'carbon fiber']}, {'total_load': {'value': 24, 'min': None, 'max': 24}}], 'long stainless steel carbon fiber <24')

([{'filler_name': ['natural organic fiber', 'glass fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'natural organic fiber and glass fiber')

([{'filler_name': ['glass fiber', 'aramide fiber']}, {'total_load': {'value': 46, 'min': 38, 'max': 54}}], 'fibreglass aramid fiber 46 with 8 range')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'without filler')

([{'total_load': {'value': 53, 'min': 53, 'max': None}}], 'combined fill >53%')

([{'filler_name': ['metal', 'aramide fiber']}, {'total_load': {'value': 63, 'min': None, 'max': 63}}], 'sf aramid fiber upto 63%')

([{'filler_name': ['glass beads', 'long aramide fiber']}, {'total_load': {'value': 19, 'min': 19, 'max': 57}}], 'gb long aramid fiber with range of 19 - 57')

([{'filler_name': ['long glass fiber', 'long aramide fiber']}, {'total_load': {'value': 3, 'min': 3, 'max': 63}}], 'long fiber glass and long aramid fiber combined load of 3 - 63')

([{'filler_name': ['continuous carbon fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'cfr-cf')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'non filler')

([{'filler_name': ['metal']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'metal')

([{'total_load': {'value': 91, 'min': 91, 'max': None}}], 'total content >91')

([{'filler_name': ['glass fiber', 'long carbon fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'gf or long carbon fiber')

([{'total_load': {'value': 42, 'min': None, 'max': 42}}], 'total load less than 42')

([{'filler_name': ['long glass fiber']}, {'total_load': {'value': 40, 'min': None, 'max': 40}}], 'long fiber less than 40')

([{'filler_name': ['aramide fiber', 'long glass fiber']}, {'total_load': {'value': 66, 'min': 61, 'max': 71}}], 'af and longglassfiber 66 with range 5')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'no fill')

([{'total_load': {'value': 28, 'min': 28, 'max': None}}], 'total load at least 28')

([{'total_load': {'value': 57, 'min': 52, 'max': 62}}], '57% filler load')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'without glass')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'without glass')

([{'filler_name': ['mineral', 'long glass fiber']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'mf longglassfiber')

([{'filler_name': ['long metal fiber']}, {'total_load': {'value': 43, 'min': 43, 'max': None}}], 'total filler load >43% long ss')

([{'filler_name': ['long glass fiber', 'long metal fiber']}, {'total_load': {'value': 39, 'min': 34, 'max': 44}}], 'lgf long metal fiber with 39% combined fill')

([{'filler_name': ['unfilled']}, {'total_load': {'value': None, 'min': None, 'max': None}}], 'no load')

([{'filler_name': ['mineral', 'long carbon fiber']}, {'total_load': {'value': 39, 'min': 39, 'max': 79}}], 'mf long carbon fiber 39 - 79%')

([{'total_load': {'value': 61, 'min': 56, 'max': 66}}], '61% combined fill')

([{'filler_name': ['continuous glass fiber']}, {'total_load': {'value': 57, 'min': 52, 'max': 62}}], 'continuous glass fiber, 57')

([{'filler_name': ['glass beads', 'metal']}, {'total_load': {'value': 61, 'min': 61, 'max': 77}}], 'glass balls metal total fill of 61 - 77')

([{'total_load': {'value': 68, 'min': 68, 'max': None}}], 'combined fill greater than 68')

### Brands

In [43]:
all_brands

['ecomid',
 'pip',
 'mcm',
 'ge',
 'tc',
 'ol',
 'tx',
 'lft',
 'celstran lft',
 'zenite',
 'thermx',
 'ze',
 'fri',
 'sp',
 've',
 'hyt',
 'cnl',
 'fortron',
 'santoprene',
 'fo',
 'opp',
 'mid',
 'pf',
 'lp',
 'oc',
 'cl',
 'fa',
 'frianyl',
 'zyt',
 'celstran',
 'celanex',
 'cs',
 'hostaform',
 'celcon',
 'po',
 'ff',
 'ot',
 'kepital',
 'pultrusion',
 'hf',
 'va',
 'cp',
 'im',
 'cn',
 'coolpoly',
 'rynite',
 'cra',
 'vectra',
 'crastin',
 'bf',
 'hytrel',
 'lfrt',
 'vamc',
 'celanyl',
 'blue ridge',
 'kep',
 'neo',
 'lftr',
 'pb',
 'htr',
 'fp',
 'zytel',
 'br',
 'am',
 'gur',
 'cs lft',
 'stp',
 'ta',
 'ryn',
 'cx']

In [44]:
for b in OOS_Data['brands']:
    if b not in all_brands:
        all_brands.append(b)
        
all_brands = [x for x in all_brands if x not in ['at', 'lt', 'min', 'sf', 'sr', 'tp', 'im', 'ny', 'htr']]
all_brands

['ecomid',
 'pip',
 'mcm',
 'ge',
 'tc',
 'ol',
 'tx',
 'lft',
 'celstran lft',
 'zenite',
 'thermx',
 'ze',
 'fri',
 'sp',
 've',
 'hyt',
 'cnl',
 'fortron',
 'santoprene',
 'fo',
 'opp',
 'mid',
 'pf',
 'lp',
 'oc',
 'cl',
 'fa',
 'frianyl',
 'zyt',
 'celstran',
 'celanex',
 'cs',
 'hostaform',
 'celcon',
 'po',
 'ff',
 'ot',
 'kepital',
 'pultrusion',
 'hf',
 'va',
 'cp',
 'cn',
 'coolpoly',
 'rynite',
 'cra',
 'vectra',
 'crastin',
 'bf',
 'hytrel',
 'lfrt',
 'vamc',
 'celanyl',
 'blue ridge',
 'kep',
 'neo',
 'lftr',
 'pb',
 'fp',
 'zytel',
 'br',
 'am',
 'gur',
 'cs lft',
 'stp',
 'ta',
 'ryn',
 'cx',
 'forflex',
 'kepamid',
 'abistir',
 'impet',
 'blueridge',
 'blendfor',
 'omnilon',
 'nylfor',
 'ateva',
 'selar',
 'factor',
 'tecnoprene',
 'neolast',
 'omnicarb',
 'sofpur',
 'micromax',
 'tarnoform',
 'nilamid',
 'celapex',
 'omnitech',
 'pibifor',
 'vamac',
 'kepex',
 'pipelon',
 'vitaldose',
 'forprene',
 'cecopoly',
 'clarifoil',
 'compel',
 'talcoprene',
 'litepol',
 'sikamid',
 'laprene',
 'elvamide',
 'keploy',
 'vandar',
 'stirofor',
 'amcel',
 'polifor',
 'omnipro',
 'sofprene',
 'maximid',
 'minlon',
 'pibiter']

In [45]:
brand_syns = synonym_df2[synonym_df2['TYPE']=='brand'][['DEFINED_NAME', 'SYNONYMS']].groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
brand_syns

{'abistir': ['abistir'],
 'amcel': ['amcel', 'am'],
 'ateva': ['ateva'],
 'bexloy': ['bexloy'],
 'blendfor': ['blendfor', 'bf'],
 'blueridge': ['blueridge', 'br', 'blue ridge'],
 'cecopoly': ['cecopoly'],
 'celanex': ['celanex', 'cx'],
 'celanyl': ['celanyl', 'cnl'],
 'celapex': ['celapex', 'cl'],
 'celcon': ['celcon', 'cn'],
 'celstran': ['celstran',
  'cs',
  'lft',
  'lfrt',
  'cs lft',
  'celstran lft',
  'pultrusion',
  'lftr'],
 'clarifoil': ['clarifoil'],
 'compel': ['compel'],
 'coolpoly': ['coolpoly', 'cp'],
 'crastin': ['crastin', 'cra'],
 'ecomid': ['ecomid'],
 'elvamide': ['elvamide', 'mid'],
 'factor': ['factor', 'fa'],
 'forflex': ['forflex', 'ff'],
 'forprene': ['forprene', 'fp'],
 'fortron': ['fortron', 'fo'],
 'frianyl': ['frianyl', 'fri'],
 'geolast': ['geolast', 'ge'],
 'gur': ['gur'],
 'hostaform': ['hostaform', 'hf'],
 'hytrel': ['hytrel', 'hyt'],
 'impet': ['impet'],
 'kepamid': ['kepamid'],
 'kepex': ['kepex'],
 'kepital': ['kepital', 'kep'],
 'keploy': ['keploy'],
 'laprene': ['laprene', 'lp'],
 'litepol': ['litepol'],
 'maximid': ['maximid'],
 'micromax': ['micromax', 'mcm'],
 'minlon': ['minlon'],
 'neolast': ['neolast', 'neo'],
 'nilamid': ['nilamid'],
 'nylfor': ['nylfor'],
 'omnicarb': ['omnicarb', 'oc'],
 'omnilon': ['omnilon', 'ol'],
 'omnipro': ['omnipro', 'opp'],
 'omnitech': ['omnitech', 'ot'],
 'pibifor': ['pibifor', 'po'],
 'pibiter': ['pibiter', 'pb'],
 'pipelon': ['pipelon', 'pip'],
 'polifor': ['polifor', 'pf'],
 'rynite': ['rynite', 'ryn'],
 'santoprene': ['santoprene', 'stp'],
 'sikamid': ['sikamid'],
 'sofprene': ['sofprene', 'sp'],
 'sofpur': ['sofpur'],
 'stirofor': ['stirofor'],
 'talcoprene': ['talcoprene'],
 'tarnoform': ['tarnoform', 'ta'],
 'tecnoprene': ['tecnoprene', 'tc'],
 'thermx': ['thermx', 'tx'],
 'vamac': ['vamac', 'vamc'],
 'vandar': ['vandar', 'va'],
 'vectra': ['vectra', 've'],
 'vitaldose': ['vitaldose'],
 'zenite': ['zenite', 'ze'],
 'zytel': ['zytel', 'zyt']}

In [46]:
for i in all_brands:
    skip = True
    for j in brand_syns:
        if i in brand_syns[j]:
            skip = False
    if skip:
        print(i)
        brand_syns[i] = [i]

selar

In [47]:
brand_syn_mapping = {}
for b_meaning, b_syns in brand_syns.items():
    for syn in b_syns:
        brand_syn_mapping[syn] = b_meaning

brand_syn_mapping

{'abistir': 'abistir',
 'amcel': 'amcel',
 'am': 'amcel',
 'ateva': 'ateva',
 'bexloy': 'bexloy',
 'blendfor': 'blendfor',
 'bf': 'blendfor',
 'blueridge': 'blueridge',
 'br': 'blueridge',
 'blue ridge': 'blueridge',
 'cecopoly': 'cecopoly',
 'celanex': 'celanex',
 'cx': 'celanex',
 'celanyl': 'celanyl',
 'cnl': 'celanyl',
 'celapex': 'celapex',
 'cl': 'celapex',
 'celcon': 'celcon',
 'cn': 'celcon',
 'celstran': 'celstran',
 'cs': 'celstran',
 'lft': 'celstran',
 'lfrt': 'celstran',
 'cs lft': 'celstran',
 'celstran lft': 'celstran',
 'pultrusion': 'celstran',
 'lftr': 'celstran',
 'clarifoil': 'clarifoil',
 'compel': 'compel',
 'coolpoly': 'coolpoly',
 'cp': 'coolpoly',
 'crastin': 'crastin',
 'cra': 'crastin',
 'ecomid': 'ecomid',
 'elvamide': 'elvamide',
 'mid': 'elvamide',
 'factor': 'factor',
 'fa': 'factor',
 'forflex': 'forflex',
 'ff': 'forflex',
 'forprene': 'forprene',
 'fp': 'forprene',
 'fortron': 'fortron',
 'fo': 'fortron',
 'frianyl': 'frianyl',
 'fri': 'frianyl',
 'geolast': 'geolast',
 'ge': 'geolast',
 'gur': 'gur',
 'hostaform': 'hostaform',
 'hf': 'hostaform',
 'hytrel': 'hytrel',
 'hyt': 'hytrel',
 'impet': 'impet',
 'kepamid': 'kepamid',
 'kepex': 'kepex',
 'kepital': 'kepital',
 'kep': 'kepital',
 'keploy': 'keploy',
 'laprene': 'laprene',
 'lp': 'laprene',
 'litepol': 'litepol',
 'maximid': 'maximid',
 'micromax': 'micromax',
 'mcm': 'micromax',
 'minlon': 'minlon',
 'neolast': 'neolast',
 'neo': 'neolast',
 'nilamid': 'nilamid',
 'nylfor': 'nylfor',
 'omnicarb': 'omnicarb',
 'oc': 'omnicarb',
 'omnilon': 'omnilon',
 'ol': 'omnilon',
 'omnipro': 'omnipro',
 'opp': 'omnipro',
 'omnitech': 'omnitech',
 'ot': 'omnitech',
 'pibifor': 'pibifor',
 'po': 'pibifor',
 'pibiter': 'pibiter',
 'pb': 'pibiter',
 'pipelon': 'pipelon',
 'pip': 'pipelon',
 'polifor': 'polifor',
 'pf': 'polifor',
 'rynite': 'rynite',
 'ryn': 'rynite',
 'santoprene': 'santoprene',
 'stp': 'santoprene',
 'sikamid': 'sikamid',
 'sofprene': 'sofprene',
 'sp': 'sofprene',
 'sofpur': 'sofpur',
 'stirofor': 'stirofor',
 'talcoprene': 'talcoprene',
 'tarnoform': 'tarnoform',
 'ta': 'tarnoform',
 'tecnoprene': 'tecnoprene',
 'tc': 'tecnoprene',
 'thermx': 'thermx',
 'tx': 'thermx',
 'vamac': 'vamac',
 'vamc': 'vamac',
 'vandar': 'vandar',
 'va': 'vandar',
 'vectra': 'vectra',
 've': 'vectra',
 'vitaldose': 'vitaldose',
 'zenite': 'zenite',
 'ze': 'zenite',
 'zytel': 'zytel',
 'zyt': 'zytel',
 'selar': 'selar'}

In [48]:
for i in brand_syn_mapping:
    if i not in all_brands:
        print(i)
        print(f"add the brand {i} to all_brands list")

bexloy
add the brand bexloy to all_brands list
geolast
add the brand geolast to all_brands list

In [49]:
all_brands_without_syns = []
for i in all_brands:
    if i in brand_syn_mapping and brand_syn_mapping[i]==i:
        all_brands_without_syns.append(i)
    elif i not in brand_syn_mapping:
        all_brands_without_syns.append(i)

all_brands_without_syns

['ecomid',
 'zenite',
 'thermx',
 'fortron',
 'santoprene',
 'frianyl',
 'celstran',
 'celanex',
 'hostaform',
 'celcon',
 'kepital',
 'coolpoly',
 'rynite',
 'vectra',
 'crastin',
 'hytrel',
 'celanyl',
 'zytel',
 'gur',
 'forflex',
 'kepamid',
 'abistir',
 'impet',
 'blueridge',
 'blendfor',
 'omnilon',
 'nylfor',
 'ateva',
 'selar',
 'factor',
 'tecnoprene',
 'neolast',
 'omnicarb',
 'sofpur',
 'micromax',
 'tarnoform',
 'nilamid',
 'celapex',
 'omnitech',
 'pibifor',
 'vamac',
 'kepex',
 'pipelon',
 'vitaldose',
 'forprene',
 'cecopoly',
 'clarifoil',
 'compel',
 'talcoprene',
 'litepol',
 'sikamid',
 'laprene',
 'elvamide',
 'keploy',
 'vandar',
 'stirofor',
 'amcel',
 'polifor',
 'omnipro',
 'sofprene',
 'maximid',
 'minlon',
 'pibiter']

### Grades

In [50]:
len(all_gradenames)

4228

In [51]:
for g in OOS_Data['grades']:
    if g not in all_gradenames:
        all_gradenames.append(g)

len(all_gradenames)

18148

### Polymers

In [52]:
all_polymers = [item.lower() for item in unique_values['Polymer']]

In [53]:
print(len(all_polymers))
for p in OOS_Data['polymers']:
    if p not in all_polymers:
        all_polymers.append(p)

print(len(all_polymers))

24
42

In [54]:
polymer_syns = synonym_df2[synonym_df2['TYPE']=='polymer'][['DEFINED_NAME', 'SYNONYMS']].groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
polymer_syns

{'abs': ['abs', 'acrylonitrile-butadiene-styrene'],
 'aem': ['aem', 'ethylene methylacrylate'],
 'asa': ['asa'],
 'evac': ['evac', 'ethylene-vinyl-acetate', 'eva'],
 'lcp': ['lcp', 'liquid crystal polymer', 'liquid - crystalline polymer'],
 'lcpa': ['lcpa', 'long chain nylon', 'long chain pa'],
 'pa*': ['pa*', 'polyamide', 'pa', 'nylon'],
 'pa1010': ['pa1010',
  'polyamide 1010',
  'nylon 1010',
  'pa 1010',
  'polyamide 10/10',
  'nylon 10/10',
  'pa10/10',
  'pa 10/10',
  'polyamide 10,10',
  'nylon 10,10',
  'pa 10,10',
  'pa10,10',
  'polyamide 10-10',
  'nylon 10-10',
  'pa 10-10',
  'pa10-10'],
 'pa12': ['pa12', 'polyamide 12', 'nylon 12', 'pa 12'],
 'pa6': ['pa6', 'nylon 6', 'pa 6', 'polyamide 6'],
 'pa610': ['pa610',
  'polyamide 610',
  'nylon 610',
  'pa 610',
  'nylon 6-10',
  'polyamide 6-10',
  'pa 6-10',
  'pa6-10',
  'nylon 6/10',
  'polyamide 6/10',
  'pa 6/10',
  'pa6/10',
  'nylon 6,10',
  'polyamide 6,10',
  'pa 6,10',
  'pa6,10'],
 'pa612': ['pa612',
  'polyamide 612',
  'nylon 612',
  'pa 612',
  'nylon 6-12',
  'polyamide 6-12',
  'pa 6-12',
  'pa6-12',
  'nylon 6/12',
  'polyamide 6/12',
  'pa 6/12',
  'pa6/12',
  'nylon 6,12',
  'polyamide 6,12',
  'pa 6,12',
  'pa6,12'],
 'pa66': ['pa66',
  'polyamide 66',
  'nylon 66',
  'pa 66',
  'nylon 6-6',
  'polyamide 6-6',
  'pa 6-6',
  'pa6-6',
  'nylon 6/6',
  'polyamide 6/6',
  'pa 6/6',
  'pa6/6',
  'nylon 6,6',
  'polyamide 6,6',
  'pa 6,6',
  'pa6,6'],
 'pa66/6t': ['pa66/6t',
  'pa66,6t',
  'pa66-6t',
  'pa 66,6t',
  'pa 66/6t',
  'pa 66-6t',
  'nylon 66,6t',
  'nylon 66/6t',
  'nylon 66-6t'],
 'pa666': ['pa666',
  'polyamide 666',
  'nylon 666',
  'pa 666',
  'nylon 66-6',
  'polyamide 66-6',
  'pa 66-6',
  'pa66-6',
  'nylon 66/6',
  'polyamide 66/6',
  'pa 66/6',
  'pa66/6',
  'nylon 66,6',
  'polyamide 66,6',
  'pa 66,6',
  'pa66,6'],
 'pa6t': ['pa6t'],
 'pa6t/66': ['pa6t/66',
  'pa6t,66',
  'pa6t-66',
  'pa 6t,66',
  'pa 6t/66',
  'pa 6t-66',
  'nylon 6t,66',
  'nylon 6t/66',
  'nylon 6t-66'],
 'pa6t/6i': ['pa6t/6i',
  '6t6i',
  'pa6t,6i',
  'pa6t-6i',
  'pa 6t,6i',
  'pa 6t/6i',
  'pa 6t-6i',
  'nylon 6t,6i',
  'nylon 6t/6i',
  'nylon 6t-6i'],
 'pa6t/xt': ['pa6t/xt',
  '6txt',
  'pa6t,xt',
  'pa6t-xt',
  'pa 6t,xt',
  'pa 6t/xt',
  'pa 6t-xt',
  'nylon 6t,xt',
  'nylon 6t/xt',
  'nylon 6t-xt'],
 'pamxd6': ['pamxd6', 'poly-m-xylylenadipamid'],
 'paste': ['paste'],
 'pbt': ['pbt', 'polybutylene terephthalate'],
 'pc': ['pc', 'polycarbonate'],
 'pct': ['pct', 'polycyclohexylenedimethylene terephthalate'],
 'pe-hd': ['pe-hd', 'hdpe', 'high density polyethylene', 'pehd', 'hd-pe'],
 'pe-hmw': ['pe-hmw', 'hmwpe', 'high molecular weight polyethylene', 'hmw-pe'],
 'pe-ld': ['pe-ld', 'peld', 'ldpe', 'low density polyethylene', 'ld-pe'],
 'pe-uhmw': ['pe-uhmw',
  'uhmwpe',
  'ultra high molecular weight polyethylene',
  'uhmw-pe',
  'uhmw',
  'umpe'],
 'peek': ['peek',
  'polyetheretherketone',
  'polyether ether ketone',
  'polyether'],
 'pet': ['pet', 'polyethylene terephthalate'],
 'polyether': ['polyether'],
 'pom': ['pom',
  'polyoxymethylene (acetal)',
  'polyoxymethylene',
  'acetal copolymer',
  'polyformaldehyde',
  'copolymer',
  'acetal',
  'polyacetal'],
 'pp': ['pp', 'polypropylene'],
 'ppa': ['ppa',
  'polyphthalamide',
  'semi aromatic polyamide',
  'semi aromatic pa'],
 'pps': ['pps', 'polyphenylene sulfide', 'polyphenylene sulphide'],
 'ps': ['ps', 'polystyrene'],
 'ptfe': ['ptfe', 'polytetrafluoroethylene', 'teflon'],
 'ptt': ['ptt', 'polytrimethylene terephthalate'],
 'pvdf': ['pvdf', 'poly(vinylidene fluoride)'],
 'sbs': ['sbs', 'styrene-butadiene-styrene'],
 'sebs': ['sebs', 'styrene-ethylene-butadiene-styrene'],
 'smah': ['smah', 'styrene-maleic anhydride'],
 'tpc': ['tpc',
  'copolyester thermoplastic elastomer',
  'thermoplastic copolyester',
  'copolyester elastomer',
  'tpc-et',
  'cope',
  'copolyester'],
 'tpe': ['tpe', 'thermoplastic elastomer'],
 'tpo': ['tpo', 'olefinic thermoplastic elastomer'],
 'tpu': ['tpu', 'thermoplastic polyurethane'],
 'tpv': ['tpv',
  'thermoplastic vulcanizate',
  'thermoplastic vulcanizates',
  'thermoplastic rubber vulcanisate',
  'ethylene propylene thermoplastic rubber',
  'eptr',
  'pp-epdm',
  'ppepdm',
  'pp epdm']}

In [55]:
polymer_syn_mapping = {}
for poly_meaning, poly_syns in polymer_syns.items():
    for syn in poly_syns:
        polymer_syn_mapping[syn] = poly_meaning

polymer_syn_mapping

{'abs': 'abs',
 'acrylonitrile-butadiene-styrene': 'abs',
 'aem': 'aem',
 'ethylene methylacrylate': 'aem',
 'asa': 'asa',
 'evac': 'evac',
 'ethylene-vinyl-acetate': 'evac',
 'eva': 'evac',
 'lcp': 'lcp',
 'liquid crystal polymer': 'lcp',
 'liquid - crystalline polymer': 'lcp',
 'lcpa': 'lcpa',
 'long chain nylon': 'lcpa',
 'long chain pa': 'lcpa',
 'pa*': 'pa*',
 'polyamide': 'pa*',
 'pa': 'pa*',
 'nylon': 'pa*',
 'pa1010': 'pa1010',
 'polyamide 1010': 'pa1010',
 'nylon 1010': 'pa1010',
 'pa 1010': 'pa1010',
 'polyamide 10/10': 'pa1010',
 'nylon 10/10': 'pa1010',
 'pa10/10': 'pa1010',
 'pa 10/10': 'pa1010',
 'polyamide 10,10': 'pa1010',
 'nylon 10,10': 'pa1010',
 'pa 10,10': 'pa1010',
 'pa10,10': 'pa1010',
 'polyamide 10-10': 'pa1010',
 'nylon 10-10': 'pa1010',
 'pa 10-10': 'pa1010',
 'pa10-10': 'pa1010',
 'pa12': 'pa12',
 'polyamide 12': 'pa12',
 'nylon 12': 'pa12',
 'pa 12': 'pa12',
 'pa6': 'pa6',
 'nylon 6': 'pa6',
 'pa 6': 'pa6',
 'polyamide 6': 'pa6',
 'pa610': 'pa610',
 'polyamide 610': 'pa610',
 'nylon 610': 'pa610',
 'pa 610': 'pa610',
 'nylon 6-10': 'pa610',
 'polyamide 6-10': 'pa610',
 'pa 6-10': 'pa610',
 'pa6-10': 'pa610',
 'nylon 6/10': 'pa610',
 'polyamide 6/10': 'pa610',
 'pa 6/10': 'pa610',
 'pa6/10': 'pa610',
 'nylon 6,10': 'pa610',
 'polyamide 6,10': 'pa610',
 'pa 6,10': 'pa610',
 'pa6,10': 'pa610',
 'pa612': 'pa612',
 'polyamide 612': 'pa612',
 'nylon 612': 'pa612',
 'pa 612': 'pa612',
 'nylon 6-12': 'pa612',
 'polyamide 6-12': 'pa612',
 'pa 6-12': 'pa612',
 'pa6-12': 'pa612',
 'nylon 6/12': 'pa612',
 'polyamide 6/12': 'pa612',
 'pa 6/12': 'pa612',
 'pa6/12': 'pa612',
 'nylon 6,12': 'pa612',
 'polyamide 6,12': 'pa612',
 'pa 6,12': 'pa612',
 'pa6,12': 'pa612',
 'pa66': 'pa66',
 'polyamide 66': 'pa66',
 'nylon 66': 'pa66',
 'pa 66': 'pa66',
 'nylon 6-6': 'pa66',
 'polyamide 6-6': 'pa66',
 'pa 6-6': 'pa66',
 'pa6-6': 'pa66',
 'nylon 6/6': 'pa66',
 'polyamide 6/6': 'pa66',
 'pa 6/6': 'pa66',
 'pa6/6': 'pa66',
 'nylon 6,6': 'pa66',
 'polyamide 6,6': 'pa66',
 'pa 6,6': 'pa66',
 'pa6,6': 'pa66',
 'pa66/6t': 'pa66/6t',
 'pa66,6t': 'pa66/6t',
 'pa66-6t': 'pa66/6t',
 'pa 66,6t': 'pa66/6t',
 'pa 66/6t': 'pa66/6t',
 'pa 66-6t': 'pa66/6t',
 'nylon 66,6t': 'pa66/6t',
 'nylon 66/6t': 'pa66/6t',
 'nylon 66-6t': 'pa66/6t',
 'pa666': 'pa666',
 'polyamide 666': 'pa666',
 'nylon 666': 'pa666',
 'pa 666': 'pa666',
 'nylon 66-6': 'pa666',
 'polyamide 66-6': 'pa666',
 'pa 66-6': 'pa666',
 'pa66-6': 'pa666',
 'nylon 66/6': 'pa666',
 'polyamide 66/6': 'pa666',
 'pa 66/6': 'pa666',
 'pa66/6': 'pa666',
 'nylon 66,6': 'pa666',
 'polyamide 66,6': 'pa666',
 'pa 66,6': 'pa666',
 'pa66,6': 'pa666',
 'pa6t': 'pa6t',
 'pa6t/66': 'pa6t/66',
 'pa6t,66': 'pa6t/66',
 'pa6t-66': 'pa6t/66',
 'pa 6t,66': 'pa6t/66',
 'pa 6t/66': 'pa6t/66',
 'pa 6t-66': 'pa6t/66',
 'nylon 6t,66': 'pa6t/66',
 'nylon 6t/66': 'pa6t/66',
 'nylon 6t-66': 'pa6t/66',
 'pa6t/6i': 'pa6t/6i',
 '6t6i': 'pa6t/6i',
 'pa6t,6i': 'pa6t/6i',
 'pa6t-6i': 'pa6t/6i',
 'pa 6t,6i': 'pa6t/6i',
 'pa 6t/6i': 'pa6t/6i',
 'pa 6t-6i': 'pa6t/6i',
 'nylon 6t,6i': 'pa6t/6i',
 'nylon 6t/6i': 'pa6t/6i',
 'nylon 6t-6i': 'pa6t/6i',
 'pa6t/xt': 'pa6t/xt',
 '6txt': 'pa6t/xt',
 'pa6t,xt': 'pa6t/xt',
 'pa6t-xt': 'pa6t/xt',
 'pa 6t,xt': 'pa6t/xt',
 'pa 6t/xt': 'pa6t/xt',
 'pa 6t-xt': 'pa6t/xt',
 'nylon 6t,xt': 'pa6t/xt',
 'nylon 6t/xt': 'pa6t/xt',
 'nylon 6t-xt': 'pa6t/xt',
 'pamxd6': 'pamxd6',
 'poly-m-xylylenadipamid': 'pamxd6',
 'paste': 'paste',
 'pbt': 'pbt',
 'polybutylene terephthalate': 'pbt',
 'pc': 'pc',
 'polycarbonate': 'pc',
 'pct': 'pct',
 'polycyclohexylenedimethylene terephthalate': 'pct',
 'pe-hd': 'pe-hd',
 'hdpe': 'pe-hd',
 'high density polyethylene': 'pe-hd',
 'pehd': 'pe-hd',
 'hd-pe': 'pe-hd',
 'pe-hmw': 'pe-hmw',
 'hmwpe': 'pe-hmw',
 'high molecular weight polyethylene': 'pe-hmw',
 'hmw-pe': 'pe-hmw',
 'pe-ld': 'pe-ld',
 'peld': 'pe-ld',
 'ldpe': 'pe-ld',
 'low density polyethylene': 'pe-ld',
 'ld-pe': 'pe-ld',
 'pe-uhmw': 'pe-uhmw',
 'uhmwpe': 'pe-uhmw',
 'ultra high molecular weight polyethylene': 'pe-uhmw',
 'uhmw-pe': 'pe-uhmw',
 'uhmw': 'pe-uhmw',
 'umpe': 'pe-uhmw',
 'peek': 'peek',
 'polyetheretherketone': 'peek',
 'polyether ether ketone': 'peek',
 'polyether': 'polyether',
 'pet': 'pet',
 'polyethylene terephthalate': 'pet',
 'pom': 'pom',
 'polyoxymethylene (acetal)': 'pom',
 'polyoxymethylene': 'pom',
 'acetal copolymer': 'pom',
 'polyformaldehyde': 'pom',
 'copolymer': 'pom',
 'acetal': 'pom',
 'polyacetal': 'pom',
 'pp': 'pp',
 'polypropylene': 'pp',
 'ppa': 'ppa',
 'polyphthalamide': 'ppa',
 'semi aromatic polyamide': 'ppa',
 'semi aromatic pa': 'ppa',
 'pps': 'pps',
 'polyphenylene sulfide': 'pps',
 'polyphenylene sulphide': 'pps',
 'ps': 'ps',
 'polystyrene': 'ps',
 'ptfe': 'ptfe',
 'polytetrafluoroethylene': 'ptfe',
 'teflon': 'ptfe',
 'ptt': 'ptt',
 'polytrimethylene terephthalate': 'ptt',
 'pvdf': 'pvdf',
 'poly(vinylidene fluoride)': 'pvdf',
 'sbs': 'sbs',
 'styrene-butadiene-styrene': 'sbs',
 'sebs': 'sebs',
 'styrene-ethylene-butadiene-styrene': 'sebs',
 'smah': 'smah',
 'styrene-maleic anhydride': 'smah',
 'tpc': 'tpc',
 'copolyester thermoplastic elastomer': 'tpc',
 'thermoplastic copolyester': 'tpc',
 'copolyester elastomer': 'tpc',
 'tpc-et': 'tpc',
 'cope': 'tpc',
 'copolyester': 'tpc',
 'tpe': 'tpe',
 'thermoplastic elastomer': 'tpe',
 'tpo': 'tpo',
 'olefinic thermoplastic elastomer': 'tpo',
 'tpu': 'tpu',
 'thermoplastic polyurethane': 'tpu',
 'tpv': 'tpv',
 'thermoplastic vulcanizate': 'tpv',
 'thermoplastic vulcanizates': 'tpv',
 'thermoplastic rubber vulcanisate': 'tpv',
 'ethylene propylene thermoplastic rubber': 'tpv',
 'eptr': 'tpv',
 'pp-epdm': 'tpv',
 'ppepdm': 'tpv',
 'pp epdm': 'tpv'}

In [56]:
for p in polymer_syn_mapping:
    if p not in all_polymers:
        all_polymers.append(p)

In [57]:
for i in polymer_syn_mapping:
    if i not in all_polymers:
        print(f"add polymer '{i}' to all_polymers")

In [58]:
all_polymers_without_syns = []
for i in all_polymers:
    if i in polymer_syn_mapping and polymer_syn_mapping[i]==i:
        all_polymers_without_syns.append(i)
    elif i not in polymer_syn_mapping:
        all_polymers_without_syns.append(i)

all_polymers_without_syns

['pbt',
 'pet',
 'pa66',
 'pa6',
 'pa*',
 'pom',
 'pa666',
 'pe-hd',
 'pp',
 'pps',
 'tpu',
 'pc',
 'abs',
 'lcp',
 'pe-uhmw',
 'pe-hmw',
 'tpc',
 'tpv',
 'pct',
 'pa612',
 'pa6t/xt',
 'pa6t/66',
 'pa66/6t',
 'pa610',
 'evac',
 'pvdf',
 'smah',
 'pa6t/6i',
 'ps',
 'pa12',
 'paste',
 'ptt',
 'pe-ld',
 'pa1010',
 'sebs',
 'peek',
 'pamxd6',
 'asa',
 'sbs',
 'tpo',
 'aem',
 'lcpa',
 'pa6t',
 'polyether',
 'ppa',
 'ptfe',
 'tpe']

### Clean: Processing, Feature, and Delivery Form

In [59]:
processing_types = []
product_functions = []
delivery_forms = []
for item in unique_values['Feature']:
    if item['Feature Type']=='Processing':
        processing_types.append(item['FEATURE'].lower().replace("mould", "mold"))
    if item['Feature Type']=='Product Categories' and item['FEATURE'].lower() not in ['auto spec approved']:
        product_functions.append(item['FEATURE'].lower())
    if item['Feature Type']=='Delivery Form':
        delivery_forms.append(item['FEATURE'].lower())

In [60]:
print([i for i in OLD_UNIQUE_VALUES["FEATURE"] if len(i)<5])

['bd', 'bio', 'bm', 'cast', 'ebm', 'emi', 'esd', 'fda', 'film', 'fr', 'heat', 'hhr', 'hr', 'ibm', 'im', 'lds', 'lm', 'lt', 'lw', 'mmm', 'mt', 'nh', 'nhfr', 'pcr', 'pir', 'rec', 'rm', 'tape', 'uv']

### Processing

In [61]:
processing_syns = synonym_df2[synonym_df2['TYPE']=='processing'][['DEFINED_NAME', 'SYNONYMS']].groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
processing_syns

{'blow molding': ['blow molding',
  'blowmolding',
  'bm',
  'blow moulding',
  'blow moldable',
  'blow molded'],
 'calendering': ['calendering',
  'calandering',
  'calendered',
  'calendr',
  'calenderable'],
 'casting': ['casting', 'castable'],
 'coatable': ['coatable', 'coating', 'polymeric coating', 'spin coating'],
 'coextrusion': ['coextrusion'],
 'compression molding': ['compression molding',
  'compression moulding',
  'matched-die moulding',
  'matched-die molding',
  'matched die molding',
  'matched die moulding',
  'cold compression',
  'hot compression',
  'compmold',
  'compression moldable',
  'compression mouldable'],
 'extrusion - hose': ['extrusion - hose', 'hose extrusion'],
 'extrusion - ram': ['extrusion - ram', 'ram extrusion'],
 'extrusion - small tubing': ['extrusion - small tubing'],
 'extrusion - wire and cable': ['extrusion - wire and cable',
  'cable extrusion',
  'wire extrusion',
  'extrusion wire coating',
  'extrusion cable coating',
  'wire coating',
  'cable coating'],
 'extrusion blow molding': ['extrusion blow molding',
  'extrusion blow moulding',
  'extrusion blow moldable',
  'extrusion blow mouldable',
  'extrusion - blow molding'],
 'fiber spinning / gel spinning': ['fiber spinning / gel spinning',
  'fibre spinning / gel spinning',
  'fibre spinning / gel extrusion',
  'fiber spinning / gel extrusion',
  'fiber spinning',
  'fibre spinning',
  'semi melt spinning',
  'gel-electrospinning',
  'gel electrospinning',
  'gel spinning',
  'extrusion - gel',
  'gel extrusion'],
 'film extrusion': ['film extrusion',
  'cast film extrusion',
  'extrusion - film'],
 'foam processing': ['foam processing',
  'foam extrusion',
  'foamable',
  'bead foam extrusion',
  'physical foaming',
  'foaming',
  'mucell'],
 'injection blow molding': ['injection blow molding',
  'injection blow moulding',
  'injection blow moldable',
  'ibm'],
 'injection molding': ['injection molding',
  'injection moldable',
  'injection moulding',
  'injmold',
  'injmould',
  'injection',
  'injection mouldable'],
 'melt blowing / nonwovens': ['melt blowing / nonwovens', 'melt blown'],
 'multi injection molding': ['multi injection molding',
  'multi injection moulding',
  'multi-material injection molding',
  'multi material injection molding',
  'multi-material injection moulding',
  'multi material injection moulding',
  'mmm',
  'multi injection moldable',
  'multi injection mouldable',
  '2k injection molding',
  '2k injection moulding',
  'double shot molding',
  'double shot moulding'],
 'other extrusion': ['other extrusion', 'otherex', 'extrusion - other'],
 'powder coating / sintering': ['power coating / sintering',
  'poweder coating',
  'porous sintering',
  'sintering'],
 'profile extrusion': ['profile extrusion',
  'profex',
  'profilextrusion',
  'extrusion - profile'],
 'rotational molding': ['rotational molding',
  'rotomolding',
  'rotomoulding',
  'rotomoldable',
  'rotomouldable',
  'rm',
  'rotational moulding',
  'rotational moldable',
  'rotational mouldable'],
 'selective reinforcement': ['selective reinforcement'],
 'sheet extrusion': ['sheet extrusion',
  'sheet',
  'sheetex',
  'extrusion - sheet'],
 'thermoforming': ['thermoforming', 'thermo forming', 'thermo'],
 'transfer molding': ['transfer molding',
  'transfer moulding',
  'xfermol',
  'transfer moldable',
  'transfer mouldable']}

In [62]:
processing_syn_mapping = {}
for p_meaning, p_syns in processing_syns.items():
    for syn in p_syns:
        processing_syn_mapping[syn] = p_meaning

processing_syn_mapping

{'blow molding': 'blow molding',
 'blowmolding': 'blow molding',
 'bm': 'blow molding',
 'blow moulding': 'blow molding',
 'blow moldable': 'blow molding',
 'blow molded': 'blow molding',
 'calendering': 'calendering',
 'calandering': 'calendering',
 'calendered': 'calendering',
 'calendr': 'calendering',
 'calenderable': 'calendering',
 'casting': 'casting',
 'castable': 'casting',
 'coatable': 'coatable',
 'coating': 'coatable',
 'polymeric coating': 'coatable',
 'spin coating': 'coatable',
 'coextrusion': 'coextrusion',
 'compression molding': 'compression molding',
 'compression moulding': 'compression molding',
 'matched-die moulding': 'compression molding',
 'matched-die molding': 'compression molding',
 'matched die molding': 'compression molding',
 'matched die moulding': 'compression molding',
 'cold compression': 'compression molding',
 'hot compression': 'compression molding',
 'compmold': 'compression molding',
 'compression moldable': 'compression molding',
 'compression mouldable': 'compression molding',
 'extrusion - hose': 'extrusion - hose',
 'hose extrusion': 'extrusion - hose',
 'extrusion - ram': 'extrusion - ram',
 'ram extrusion': 'extrusion - ram',
 'extrusion - small tubing': 'extrusion - small tubing',
 'extrusion - wire and cable': 'extrusion - wire and cable',
 'cable extrusion': 'extrusion - wire and cable',
 'wire extrusion': 'extrusion - wire and cable',
 'extrusion wire coating': 'extrusion - wire and cable',
 'extrusion cable coating': 'extrusion - wire and cable',
 'wire coating': 'extrusion - wire and cable',
 'cable coating': 'extrusion - wire and cable',
 'extrusion blow molding': 'extrusion blow molding',
 'extrusion blow moulding': 'extrusion blow molding',
 'extrusion blow moldable': 'extrusion blow molding',
 'extrusion blow mouldable': 'extrusion blow molding',
 'extrusion - blow molding': 'extrusion blow molding',
 'fiber spinning / gel spinning': 'fiber spinning / gel spinning',
 'fibre spinning / gel spinning': 'fiber spinning / gel spinning',
 'fibre spinning / gel extrusion': 'fiber spinning / gel spinning',
 'fiber spinning / gel extrusion': 'fiber spinning / gel spinning',
 'fiber spinning': 'fiber spinning / gel spinning',
 'fibre spinning': 'fiber spinning / gel spinning',
 'semi melt spinning': 'fiber spinning / gel spinning',
 'gel-electrospinning': 'fiber spinning / gel spinning',
 'gel electrospinning': 'fiber spinning / gel spinning',
 'gel spinning': 'fiber spinning / gel spinning',
 'extrusion - gel': 'fiber spinning / gel spinning',
 'gel extrusion': 'fiber spinning / gel spinning',
 'film extrusion': 'film extrusion',
 'cast film extrusion': 'film extrusion',
 'extrusion - film': 'film extrusion',
 'foam processing': 'foam processing',
 'foam extrusion': 'foam processing',
 'foamable': 'foam processing',
 'bead foam extrusion': 'foam processing',
 'physical foaming': 'foam processing',
 'foaming': 'foam processing',
 'mucell': 'foam processing',
 'injection blow molding': 'injection blow molding',
 'injection blow moulding': 'injection blow molding',
 'injection blow moldable': 'injection blow molding',
 'ibm': 'injection blow molding',
 'injection molding': 'injection molding',
 'injection moldable': 'injection molding',
 'injection moulding': 'injection molding',
 'injmold': 'injection molding',
 'injmould': 'injection molding',
 'injection': 'injection molding',
 'injection mouldable': 'injection molding',
 'melt blowing / nonwovens': 'melt blowing / nonwovens',
 'melt blown': 'melt blowing / nonwovens',
 'multi injection molding': 'multi injection molding',
 'multi injection moulding': 'multi injection molding',
 'multi-material injection molding': 'multi injection molding',
 'multi material injection molding': 'multi injection molding',
 'multi-material injection moulding': 'multi injection molding',
 'multi material injection moulding': 'multi injection molding',
 'mmm': 'multi injection molding',
 'multi injection moldable': 'multi injection molding',
 'multi injection mouldable': 'multi injection molding',
 '2k injection molding': 'multi injection molding',
 '2k injection moulding': 'multi injection molding',
 'double shot molding': 'multi injection molding',
 'double shot moulding': 'multi injection molding',
 'other extrusion': 'other extrusion',
 'otherex': 'other extrusion',
 'extrusion - other': 'other extrusion',
 'power coating / sintering': 'powder coating / sintering',
 'poweder coating': 'powder coating / sintering',
 'porous sintering': 'powder coating / sintering',
 'sintering': 'powder coating / sintering',
 'profile extrusion': 'profile extrusion',
 'profex': 'profile extrusion',
 'profilextrusion': 'profile extrusion',
 'extrusion - profile': 'profile extrusion',
 'rotational molding': 'rotational molding',
 'rotomolding': 'rotational molding',
 'rotomoulding': 'rotational molding',
 'rotomoldable': 'rotational molding',
 'rotomouldable': 'rotational molding',
 'rm': 'rotational molding',
 'rotational moulding': 'rotational molding',
 'rotational moldable': 'rotational molding',
 'rotational mouldable': 'rotational molding',
 'selective reinforcement': 'selective reinforcement',
 'sheet extrusion': 'sheet extrusion',
 'sheet': 'sheet extrusion',
 'sheetex': 'sheet extrusion',
 'extrusion - sheet': 'sheet extrusion',
 'thermoforming': 'thermoforming',
 'thermo forming': 'thermoforming',
 'thermo': 'thermoforming',
 'transfer molding': 'transfer molding',
 'transfer moulding': 'transfer molding',
 'xfermol': 'transfer molding',
 'transfer moldable': 'transfer molding',
 'transfer mouldable': 'transfer molding'}

In [63]:
print(len(processing_types))
for i in processing_syn_mapping:
    if i not in processing_types:
        processing_types.append(i)

print(len(processing_types))

26
127

In [64]:
all_processing_without_syns = []
for i in processing_types:
    if i in processing_syn_mapping and processing_syn_mapping[i]==i:
        all_processing_without_syns.append(i)
    elif i not in processing_syn_mapping:
        all_processing_without_syns.append(i)

all_processing_without_syns

['injection molding',
 'other extrusion',
 'film extrusion',
 'profile extrusion',
 'sheet extrusion',
 'multi injection molding',
 'coextrusion',
 'compression molding',
 'blow molding',
 'calendering',
 'selective reinforcement',
 'thermoforming',
 'transfer molding',
 'coatable',
 'casting',
 'fiber spinning / gel spinning',
 'extrusion blow molding',
 'rotational molding',
 'foam processing',
 'extrusion - wire and cable',
 'extrusion - small tubing',
 'injection blow molding',
 'extrusion - hose',
 'extrusion - ram',
 'melt blowing / nonwovens']

### Delivery Form

In [65]:
delivery_forms

['pellets', 'granules', 'tape', 'powder', 'micropowder']

In [66]:
delivery_form_syns = synonym_df2[synonym_df2['TYPE']=='delivery form'][['DEFINED_NAME', 'SYNONYMS']].groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
delivery_form_syns

{'granules': ['granules'],
 'micropowder': ['micro powder', 'micro-powder'],
 'pellets': ['pellets', 'pelets', 'pellet'],
 'powder': ['powder'],
 'tape': ['tape', 'cfr', 'tp']}

In [67]:
delivery_syn_mapping = {}
for d_meaning, d_syns in delivery_form_syns.items():
    for syn in d_syns:
        delivery_syn_mapping[syn] = d_meaning

delivery_syn_mapping

{'granules': 'granules',
 'micro powder': 'micropowder',
 'micro-powder': 'micropowder',
 'pellets': 'pellets',
 'pelets': 'pellets',
 'pellet': 'pellets',
 'powder': 'powder',
 'tape': 'tape',
 'cfr': 'tape',
 'tp': 'tape'}

In [68]:
print(len(delivery_forms))
for i in delivery_syn_mapping:
    if i not in delivery_forms:
        delivery_forms.append(i)

print(len(delivery_forms))

5
11

In [69]:
all_delivery_without_syns = []
for i in delivery_forms:
    if i in delivery_syn_mapping and delivery_syn_mapping[i]==i:
        all_delivery_without_syns.append(i)
    elif i not in delivery_syn_mapping:
        all_delivery_without_syns.append(i)

all_delivery_without_syns

['pellets', 'granules', 'tape', 'powder', 'micropowder']

### Feature

In [70]:
feature_syn_meaning_mapped = {
    'impact modified': 'high impact or impact modified',
    'u.v. stabilized': 'u.v. stabilized or stable to weather',
    'heat stabilized': 'heat stabilized or stable to heat',
    'light stabilized': 'light stabilized or stable to light',
}

In [71]:
feature_df = synonym_df2[synonym_df2['TYPE']=='feature'][['DEFINED_NAME', 'SYNONYMS']]
feature_df['DEFINED_NAME'] = feature_df['DEFINED_NAME'].replace(to_replace=feature_syn_meaning_mapped)
feature_syns = feature_df.groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
feature_syns

{'anti-static': ['anti-static',
  'static resistant',
  'static',
  'static resistance',
  'antistatic',
  'avoid static',
  'avoid static build',
  'avoid static build up'],
 'bio-content': ['bio-content', 'bio-based', 'bio', 'biobased'],
 'carbon capture': ['carbon capture',
  'reduce carbon capture',
  'reduced carbon footprint',
  'eco-c',
  'carbon footprint',
  'iso 14067',
  'carbon capture and utilization',
  'ccu',
  'reduce carbon capture',
  'reduced carbon footprint'],
 'chemical resistant': ['chemical resistant',
  'acid resistant',
  'acid resistance',
  'chem resistance',
  'chem resistant',
  'anti chemical',
  'anti acid',
  'anti-chemical',
  'anti-acid',
  'chemical resistance'],
 'flame retardant': ['flame retardant',
  'flameretardent',
  'fr',
  'flame retarding agent',
  'flamret',
  'flamretag',
  'flame resistant',
  'flame resistance',
  'halogenated fr',
  'halogenated',
  'halogenated flame retardant'],
 'heat stabilized or stable to heat': ['heat stabilized or stable to heat',
  'stable to heat',
  'heat resistance',
  'heat tolerant',
  'high heat performance',
  'high heat',
  'heat stabilized',
  'heat stabilised',
  'heat',
  'heat stable',
  'high heat conditions',
  'resistant to heat',
  'thermal resistance',
  'thermal resistant',
  'anti heat',
  'anti-heat',
  'heat resistant'],
 'high flow': ['high flow',
  'high mv',
  'high flowability',
  'low viscosity',
  'easy flow',
  'thin wall',
  'low wall'],
 'high gloss': ['high gloss', 'enhanced gloss', 'highgloss'],
 'high impact or impact modified': ['impact modified',
  'high impact or impact modified',
  'toughened',
  'impact resistance',
  'impact resistant',
  'anti impact',
  'anti-impact',
  'impact grade',
  'impact modification',
  'improved toughness',
  'tough',
  'im'],
 'high viscosity': ['high viscosity', 'low mv', 'low flow', 'highvisc'],
 'hr': ['hr'],
 'hydrolysis resistant': ['hydrolysis resistant',
  'hydrolysis',
  'water resistant',
  'anti hydrolysis',
  'hydrolysis resistance',
  'water resistance',
  'anti-hydrolysis',
  'anti-water',
  'hydrostable',
  'not hygroscopic'],
 'hydrophilic': ['hydrophilic',
  'hydrophile',
  'absorbent',
  'water affinity',
  'hydrophilicity'],
 'improved creep': ['improved creep',
  'creep resistance',
  'creep resistant',
  'anti creep',
  'anti-creep'],
 'improved weld line': ['improved weld line',
  'weld line improved',
  'weld line strength'],
 'increased electrical conductivity': ['increased electrical conductivity',
  'electro conductive',
  'electrical conductivity'],
 'increased thermal conductivity': ['increased thermal conductivity',
  'heat dissipation'],
 'laser direct structurable': ['laser direct structurable',
  'lds',
  'laser direct structuring',
  'laser direct structuring (lds)'],
 'laser markable': ['laser markable',
  'lm',
  'lasermarkable',
  'laser marking',
  'lasermark'],
 'laser weldable': ['laser weldable',
  'laser transparent',
  'lasertr',
  'lasertransparent',
  'laser weld',
  'laser transmission',
  'lt'],
 'lead-free soldering resistant': ['lead-free soldering resistant',
  'surface mount solderable',
  'smd solderable',
  'lead-free reflow solderable',
  'lead-free solderability',
  'lead-free soldering resistance',
  'pb free solder reflow',
  'anti lead free soldering'],
 'light stabilized or stable to light': ['light stabilized or stable to light',
  'light stabilised or stable to light',
  'light stabilised',
  'light stabilized',
  'stable to light'],
 'light weight': ['light weight',
  'light weighting',
  'replacement for aluminum',
  'metal replacement'],
 'low emissions': ['low emissions',
  'low emission',
  'reduced emission',
  'low-e',
  'lowemiss',
  'emissions',
  'low formaldehyde',
  'low voc'],
 'low halide content': ['low halide content'],
 'low warpage': ['low warpage',
  'low warp',
  'warp resistant',
  'lowwarp',
  'high flatness',
  'warp resistance',
  'anti warp',
  'anti-warp'],
 'low wear / low friction': ['low wear / low friction',
  'low wear',
  'low friction',
  'tribo',
  'tribological',
  'low wear and friction',
  'tribological modified',
  'tribology',
  'good sliding',
  'lw',
  'abrasion resistance',
  'abrasion resistant',
  'silicone modified',
  'ptfe modified',
  'silicon oil concentrate',
  'silicone',
  'silicone concentrate',
  'tf',
  'friction',
  'tf'],
 'lubricants': ['lubricants', 'lubricated', 'lubric'],
 'medical/healthcare': ['medical/healthcare',
  'medical',
  'medical grade',
  'medgrade',
  'medhc',
  'medical grades',
  'healthcare',
  'medical grade technology',
  'mt',
  'med'],
 'non-halogenated/red phosphorous free flame retardant': ['non-halogenated/red phosphorous free flame retardant',
  'halogen free',
  'haogen free',
  'nhfr',
  'hffr',
  'halogen free flame retardant',
  'non-halogenated',
  'non-halogenated fr'],
 'nucleated': ['nucleated',
  'high crystallinity',
  'highly crystalline',
  'highest cristalline'],
 'plasticizer': ['plasticizer', 'plasticiser', 'plasti'],
 'platable': ['platable', 'plateable', 'plating grade'],
 'recycled content': ['recycled content',
  'contains recycle',
  'recycle',
  'recycled',
  'post consumer recycle',
  'post-consumer recycle',
  'pcr',
  'pir',
  'post industrial recycle',
  'post-industrial recycle'],
 'reduced gloss': ['reduced gloss', 'low gloss', 'redugloss'],
 'release agent': ['release agent', 'release'],
 'specialty appearance': ['specialty appearance',
  'lx',
  'appearance',
  'aesthetical',
  'good aesthetics',
  'visual fx'],
 'static dissipative': ['static dissipative',
  'esd',
  'esd modified',
  'elecdiss',
  'elec diss',
  'electdiss',
  'elect diss',
  'electrostatic dissipation',
  'electrostatic dissipative'],
 'sustainable': ['sustainable',
  'green',
  'circular economy',
  'environmentally friendly',
  'sustainability',
  'eco'],
 'thermal shock resistant': ['thermal shock resistant',
  'thermal shock resistance',
  'thermal shock',
  'shock resistance',
  'shock resistant',
  'anti thermal shock',
  'anti-thermal shock'],
 'u.v. stabilized or stable to weather': ['u.v. stabilized',
  'u.v. stabilised',
  'u.v. stabilized or stable to weather',
  'u.v. stabilised or stable to weather',
  'uv resistant',
  'uv',
  'anti uv',
  'anti-uv',
  'uv-stabilized',
  'exposure to outdoor sunlight',
  'uv resistent',
  'uvres',
  'uv stabilise',
  'uv stability',
  'weather resistance',
  'weather resistant',
  'uv resistance',
  'weatherable',
  'stable to weather',
  'weather',
  'solar resistance'],
 'ultrasonic weldable': ['ultrasonic weldable']}

In [72]:
feature_syn_mapping = {}
for f_meaning, f_syns in feature_syns.items():
    for syn in f_syns:
        feature_syn_mapping[syn] = f_meaning

feature_syn_mapping

{'anti-static': 'anti-static',
 'static resistant': 'anti-static',
 'static': 'anti-static',
 'static resistance': 'anti-static',
 'antistatic': 'anti-static',
 'avoid static': 'anti-static',
 'avoid static build': 'anti-static',
 'avoid static build up': 'anti-static',
 'bio-content': 'bio-content',
 'bio-based': 'bio-content',
 'bio': 'bio-content',
 'biobased': 'bio-content',
 'carbon capture': 'carbon capture',
 'reduce carbon capture': 'carbon capture',
 'reduced carbon footprint': 'carbon capture',
 'eco-c': 'carbon capture',
 'carbon footprint': 'carbon capture',
 'iso 14067': 'carbon capture',
 'carbon capture and utilization': 'carbon capture',
 'ccu': 'carbon capture',
 'chemical resistant': 'chemical resistant',
 'acid resistant': 'chemical resistant',
 'acid resistance': 'chemical resistant',
 'chem resistance': 'chemical resistant',
 'chem resistant': 'chemical resistant',
 'anti chemical': 'chemical resistant',
 'anti acid': 'chemical resistant',
 'anti-chemical': 'chemical resistant',
 'anti-acid': 'chemical resistant',
 'chemical resistance': 'chemical resistant',
 'flame retardant': 'flame retardant',
 'flameretardent': 'flame retardant',
 'fr': 'flame retardant',
 'flame retarding agent': 'flame retardant',
 'flamret': 'flame retardant',
 'flamretag': 'flame retardant',
 'flame resistant': 'flame retardant',
 'flame resistance': 'flame retardant',
 'halogenated fr': 'flame retardant',
 'halogenated': 'flame retardant',
 'halogenated flame retardant': 'flame retardant',
 'heat stabilized or stable to heat': 'heat stabilized or stable to heat',
 'stable to heat': 'heat stabilized or stable to heat',
 'heat resistance': 'heat stabilized or stable to heat',
 'heat tolerant': 'heat stabilized or stable to heat',
 'high heat performance': 'heat stabilized or stable to heat',
 'high heat': 'heat stabilized or stable to heat',
 'heat stabilized': 'heat stabilized or stable to heat',
 'heat stabilised': 'heat stabilized or stable to heat',
 'heat': 'heat stabilized or stable to heat',
 'heat stable': 'heat stabilized or stable to heat',
 'high heat conditions': 'heat stabilized or stable to heat',
 'resistant to heat': 'heat stabilized or stable to heat',
 'thermal resistance': 'heat stabilized or stable to heat',
 'thermal resistant': 'heat stabilized or stable to heat',
 'anti heat': 'heat stabilized or stable to heat',
 'anti-heat': 'heat stabilized or stable to heat',
 'heat resistant': 'heat stabilized or stable to heat',
 'high flow': 'high flow',
 'high mv': 'high flow',
 'high flowability': 'high flow',
 'low viscosity': 'high flow',
 'easy flow': 'high flow',
 'thin wall': 'high flow',
 'low wall': 'high flow',
 'high gloss': 'high gloss',
 'enhanced gloss': 'high gloss',
 'highgloss': 'high gloss',
 'impact modified': 'high impact or impact modified',
 'high impact or impact modified': 'high impact or impact modified',
 'toughened': 'high impact or impact modified',
 'impact resistance': 'high impact or impact modified',
 'impact resistant': 'high impact or impact modified',
 'anti impact': 'high impact or impact modified',
 'anti-impact': 'high impact or impact modified',
 'impact grade': 'high impact or impact modified',
 'impact modification': 'high impact or impact modified',
 'improved toughness': 'high impact or impact modified',
 'tough': 'high impact or impact modified',
 'im': 'high impact or impact modified',
 'high viscosity': 'high viscosity',
 'low mv': 'high viscosity',
 'low flow': 'high viscosity',
 'highvisc': 'high viscosity',
 'hr': 'hr',
 'hydrolysis resistant': 'hydrolysis resistant',
 'hydrolysis': 'hydrolysis resistant',
 'water resistant': 'hydrolysis resistant',
 'anti hydrolysis': 'hydrolysis resistant',
 'hydrolysis resistance': 'hydrolysis resistant',
 'water resistance': 'hydrolysis resistant',
 'anti-hydrolysis': 'hydrolysis resistant',
 'anti-water': 'hydrolysis resistant',
 'hydrostable': 'hydrolysis resistant',
 'not hygroscopic': 'hydrolysis resistant',
 'hydrophilic': 'hydrophilic',
 'hydrophile': 'hydrophilic',
 'absorbent': 'hydrophilic',
 'water affinity': 'hydrophilic',
 'hydrophilicity': 'hydrophilic',
 'improved creep': 'improved creep',
 'creep resistance': 'improved creep',
 'creep resistant': 'improved creep',
 'anti creep': 'improved creep',
 'anti-creep': 'improved creep',
 'improved weld line': 'improved weld line',
 'weld line improved': 'improved weld line',
 'weld line strength': 'improved weld line',
 'increased electrical conductivity': 'increased electrical conductivity',
 'electro conductive': 'increased electrical conductivity',
 'electrical conductivity': 'increased electrical conductivity',
 'increased thermal conductivity': 'increased thermal conductivity',
 'heat dissipation': 'increased thermal conductivity',
 'laser direct structurable': 'laser direct structurable',
 'lds': 'laser direct structurable',
 'laser direct structuring': 'laser direct structurable',
 'laser direct structuring (lds)': 'laser direct structurable',
 'laser markable': 'laser markable',
 'lm': 'laser markable',
 'lasermarkable': 'laser markable',
 'laser marking': 'laser markable',
 'lasermark': 'laser markable',
 'laser weldable': 'laser weldable',
 'laser transparent': 'laser weldable',
 'lasertr': 'laser weldable',
 'lasertransparent': 'laser weldable',
 'laser weld': 'laser weldable',
 'laser transmission': 'laser weldable',
 'lt': 'laser weldable',
 'lead-free soldering resistant': 'lead-free soldering resistant',
 'surface mount solderable': 'lead-free soldering resistant',
 'smd solderable': 'lead-free soldering resistant',
 'lead-free reflow solderable': 'lead-free soldering resistant',
 'lead-free solderability': 'lead-free soldering resistant',
 'lead-free soldering resistance': 'lead-free soldering resistant',
 'pb free solder reflow': 'lead-free soldering resistant',
 'anti lead free soldering': 'lead-free soldering resistant',
 'light stabilized or stable to light': 'light stabilized or stable to light',
 'light stabilised or stable to light': 'light stabilized or stable to light',
 'light stabilised': 'light stabilized or stable to light',
 'light stabilized': 'light stabilized or stable to light',
 'stable to light': 'light stabilized or stable to light',
 'light weight': 'light weight',
 'light weighting': 'light weight',
 'replacement for aluminum': 'light weight',
 'metal replacement': 'light weight',
 'low emissions': 'low emissions',
 'low emission': 'low emissions',
 'reduced emission': 'low emissions',
 'low-e': 'low emissions',
 'lowemiss': 'low emissions',
 'emissions': 'low emissions',
 'low formaldehyde': 'low emissions',
 'low voc': 'low emissions',
 'low halide content': 'low halide content',
 'low warpage': 'low warpage',
 'low warp': 'low warpage',
 'warp resistant': 'low warpage',
 'lowwarp': 'low warpage',
 'high flatness': 'low warpage',
 'warp resistance': 'low warpage',
 'anti warp': 'low warpage',
 'anti-warp': 'low warpage',
 'low wear / low friction': 'low wear / low friction',
 'low wear': 'low wear / low friction',
 'low friction': 'low wear / low friction',
 'tribo': 'low wear / low friction',
 'tribological': 'low wear / low friction',
 'low wear and friction': 'low wear / low friction',
 'tribological modified': 'low wear / low friction',
 'tribology': 'low wear / low friction',
 'good sliding': 'low wear / low friction',
 'lw': 'low wear / low friction',
 'abrasion resistance': 'low wear / low friction',
 'abrasion resistant': 'low wear / low friction',
 'silicone modified': 'low wear / low friction',
 'ptfe modified': 'low wear / low friction',
 'silicon oil concentrate': 'low wear / low friction',
 'silicone': 'low wear / low friction',
 'silicone concentrate': 'low wear / low friction',
 'tf': 'low wear / low friction',
 'friction': 'low wear / low friction',
 'lubricants': 'lubricants',
 'lubricated': 'lubricants',
 'lubric': 'lubricants',
 'medical/healthcare': 'medical/healthcare',
 'medical': 'medical/healthcare',
 'medical grade': 'medical/healthcare',
 'medgrade': 'medical/healthcare',
 'medhc': 'medical/healthcare',
 'medical grades': 'medical/healthcare',
 'healthcare': 'medical/healthcare',
 'medical grade technology': 'medical/healthcare',
 'mt': 'medical/healthcare',
 'med': 'medical/healthcare',
 'non-halogenated/red phosphorous free flame retardant': 'non-halogenated/red phosphorous free flame retardant',
 'halogen free': 'non-halogenated/red phosphorous free flame retardant',
 'haogen free': 'non-halogenated/red phosphorous free flame retardant',
 'nhfr': 'non-halogenated/red phosphorous free flame retardant',
 'hffr': 'non-halogenated/red phosphorous free flame retardant',
 'halogen free flame retardant': 'non-halogenated/red phosphorous free flame retardant',
 'non-halogenated': 'non-halogenated/red phosphorous free flame retardant',
 'non-halogenated fr': 'non-halogenated/red phosphorous free flame retardant',
 'nucleated': 'nucleated',
 'high crystallinity': 'nucleated',
 'highly crystalline': 'nucleated',
 'highest cristalline': 'nucleated',
 'plasticizer': 'plasticizer',
 'plasticiser': 'plasticizer',
 'plasti': 'plasticizer',
 'platable': 'platable',
 'plateable': 'platable',
 'plating grade': 'platable',
 'recycled content': 'recycled content',
 'contains recycle': 'recycled content',
 'recycle': 'recycled content',
 'recycled': 'recycled content',
 'post consumer recycle': 'recycled content',
 'post-consumer recycle': 'recycled content',
 'pcr': 'recycled content',
 'pir': 'recycled content',
 'post industrial recycle': 'recycled content',
 'post-industrial recycle': 'recycled content',
 'reduced gloss': 'reduced gloss',
 'low gloss': 'reduced gloss',
 'redugloss': 'reduced gloss',
 'release agent': 'release agent',
 'release': 'release agent',
 'specialty appearance': 'specialty appearance',
 'lx': 'specialty appearance',
 'appearance': 'specialty appearance',
 'aesthetical': 'specialty appearance',
 'good aesthetics': 'specialty appearance',
 'visual fx': 'specialty appearance',
 'static dissipative': 'static dissipative',
 'esd': 'static dissipative',
 'esd modified': 'static dissipative',
 'elecdiss': 'static dissipative',
 'elec diss': 'static dissipative',
 'electdiss': 'static dissipative',
 'elect diss': 'static dissipative',
 'electrostatic dissipation': 'static dissipative',
 'electrostatic dissipative': 'static dissipative',
 'sustainable': 'sustainable',
 'green': 'sustainable',
 'circular economy': 'sustainable',
 'environmentally friendly': 'sustainable',
 'sustainability': 'sustainable',
 'eco': 'sustainable',
 'thermal shock resistant': 'thermal shock resistant',
 'thermal shock resistance': 'thermal shock resistant',
 'thermal shock': 'thermal shock resistant',
 'shock resistance': 'thermal shock resistant',
 'shock resistant': 'thermal shock resistant',
 'anti thermal shock': 'thermal shock resistant',
 'anti-thermal shock': 'thermal shock resistant',
 'u.v. stabilized': 'u.v. stabilized or stable to weather',
 'u.v. stabilised': 'u.v. stabilized or stable to weather',
 'u.v. stabilized or stable to weather': 'u.v. stabilized or stable to weather',
 'u.v. stabilised or stable to weather': 'u.v. stabilized or stable to weather',
 'uv resistant': 'u.v. stabilized or stable to weather',
 'uv': 'u.v. stabilized or stable to weather',
 'anti uv': 'u.v. stabilized or stable to weather',
 'anti-uv': 'u.v. stabilized or stable to weather',
 'uv-stabilized': 'u.v. stabilized or stable to weather',
 'exposure to outdoor sunlight': 'u.v. stabilized or stable to weather',
 'uv resistent': 'u.v. stabilized or stable to weather',
 'uvres': 'u.v. stabilized or stable to weather',
 'uv stabilise': 'u.v. stabilized or stable to weather',
 'uv stability': 'u.v. stabilized or stable to weather',
 'weather resistance': 'u.v. stabilized or stable to weather',
 'weather resistant': 'u.v. stabilized or stable to weather',
 'uv resistance': 'u.v. stabilized or stable to weather',
 'weatherable': 'u.v. stabilized or stable to weather',
 'stable to weather': 'u.v. stabilized or stable to weather',
 'weather': 'u.v. stabilized or stable to weather',
 'solar resistance': 'u.v. stabilized or stable to weather',
 'ultrasonic weldable': 'ultrasonic weldable'}

In [73]:
print(len(product_functions))
for i in feature_syn_mapping:
    if i not in product_functions:
        product_functions.append(i)

print(len(product_functions))

41
278

In [74]:
all_features_without_syns = []
for i in product_functions:
    if i in feature_syn_mapping and feature_syn_mapping[i]==i:
        all_features_without_syns.append(i)
    elif i not in feature_syn_mapping:
        all_features_without_syns.append(i)

all_features_without_syns

['high viscosity',
 'lubricants',
 'release agent',
 'high flow',
 'hydrolysis resistant',
 'low wear / low friction',
 'high impact or impact modified',
 'flame retardant',
 'u.v. stabilized or stable to weather',
 'heat stabilized or stable to heat',
 'high gloss',
 'recycled content',
 'sustainable',
 'medical/healthcare',
 'bio-content',
 'nucleated',
 'laser markable',
 'specialty appearance',
 'low warpage',
 'non-halogenated/red phosphorous free flame retardant',
 'static dissipative',
 'anti-static',
 'increased electrical conductivity',
 'chemical resistant',
 'low halide content',
 'increased thermal conductivity',
 'light stabilized or stable to light',
 'improved creep',
 'reduced gloss',
 'carbon capture',
 'low emissions',
 'light weight',
 'lead-free soldering resistant',
 'laser weldable',
 'thermal shock resistant',
 'platable',
 'hydrophilic',
 'improved weld line',
 'ultrasonic weldable',
 'laser direct structurable',
 'plasticizer',
 'hr']

In [75]:
for i in processing_types:
    if i not in processing_syn_mapping:
        print(1, i)


for i in delivery_forms:
    if i not in delivery_syn_mapping:
        print(2, i)

# medical & pharma - drug delivery devices: no synonyms
for i in product_functions:
    if i not in feature_syn_mapping:
        print(3, i)

2 micropowder

### Properties

In [76]:
prop_df = synonym_df2[synonym_df2['TYPE']=='property'][['DEFINED_NAME', 'SYNONYMS']]
prop_df['DEFINED_NAME'] = prop_df['DEFINED_NAME'].apply(lambda x: x.replace(" -  (-)", "").replace(" (-)", "").rstrip(" -") if x else x)
prop_df

,DEFINED_NAME,SYNONYMS
881,average molecular weight margolies' equation (...,average molecular weight
882,average molecular weight margolies' equation (...,average molar mass
883,average molecular weight margolies' equation (...,average molecular mass
884,average molecular weight margolies' equation (...,avermw
885,average molecular weight margolies' equation (...,molecular weight
...,...,...
1432,water absorption sim. to iso 62 2mm (%),moisture absorption equilibrium 23°c/50% r.h.
1433,wear by sandslurry method (based on gur 4120=100),wear by sandslurry method
1484,molding shrinkage,mold shrinkage (md/td)
1489,melt mass-flow rate iso 1133 (g/10min),mi
1493,surface resistivity iec 62631-3-2 (ohm),sr

In [77]:
print(prop_df[prop_df['DEFINED_NAME']=='fiber areal weight (g/m²)'])

prop_df['DEFINED_NAME'] = prop_df['DEFINED_NAME'].replace('fiber areal weight - (g/m²)', 'fiber areal weight (g/m²)')
prop_df['DEFINED_NAME'] = prop_df['DEFINED_NAME'].replace('tape areal weight - (g/m²)', 'tape areal weight (g/m²)')

print(prop_df[prop_df['DEFINED_NAME']=='fiber areal weight (g/m²)'])

                   DEFINED_NAME            SYNONYMS
1045  fiber areal weight (g/m²)  fiber areal weight
                   DEFINED_NAME            SYNONYMS
1045  fiber areal weight (g/m²)  fiber areal weight

In [78]:
property_syns = prop_df.groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
property_syns

{"average molecular weight margolies' equation (g/mol)": ['average molecular weight',
  'average molar mass',
  'average molecular mass',
  'avermw',
  'molecular weight',
  'mw'],
 'average particle size laser scattering d50 (µm)': ['average particle size laser scattering d50 (µm)',
  'average particle size',
  'avg. particle size',
  'avpartsize',
  'particle size',
  'particle size d50'],
 'ball indentation hardness iso 2039-1 h 358/30 (mpa)': ['ball indentation hardness',
  'ball indention hardness'],
 'ball pressure test iec 60695-10-2 (°c)': ['ball pressure test'],
 'bulk density iso 60 (kg/m³)': ['bulk density',
  'apparent (bulk) density',
  'apparent density',
  'bulkdens'],
 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)': ['charpy double notched impact strength',
  'charpy impact strength (double notched)',
  'charpy impact strength (double notch)',
  'double notch charpy impact strength',
  'double notched charpy impact strength',
  'double notch charpy',
  'double notched charpy',
  'double notch impact',
  'double notched impact',
  'charpy double notch',
  'charpy double notched'],
 'charpy impact strength': ['charpy impact strength',
  'charpy impact',
  'impact charpy',
  'charpy unnotched',
  'charpy unnotch',
  'unnotched charpy',
  'unnotch charpy',
  'charpy unnotched impact',
  'charpy unnotch impact',
  'unnotched charpy impact',
  'unnotch charpy impact',
  'charpy impact strength unnotched',
  'charpy impact strength unnotch',
  'charpy impact strength (unnotched)',
  'charpy impact strength (unnotch)',
  'charpy impact unnotched',
  'charpy impact unnotch',
  'charpy impact (unnotched)',
  'charpy impact (unnotch)'],
 'charpy notched impact strength': ['charpy notched impact strength',
  'charpy notched',
  'charpy notch',
  'notched charpy',
  'notch charpy',
  'charpy notched impact',
  'charpy notch impact',
  'notched charpy impact',
  'notch charpy impact',
  'charpy impact strength notched',
  'charpy impact strength notch',
  'charpy impact strength (notched)',
  'charpy impact strength (notch)',
  'charpy impact notched',
  'charpy impact notch',
  'charpy impact (notched)',
  'charpy impact (notch)'],
 'coefficient of linear thermal expansion (clte)': ['coefficient of linear thermal expansion (clte)',
  'coefficient of linear thermal expansion',
  'clte',
  'linear expansion factor',
  'thermal expansion',
  'linear thermal expansion',
  'coef. of lin. therm expansion'],
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)': ['linear expansion factor (normal)',
  'normal thermal expansion',
  'normal linear thermal expansion',
  'coef. of lin. therm expansion normal',
  'clte (transverse direction)'],
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)': ['linear expansion factor (parallel)',
  'parallel thermal expansion',
  'parallel linear thermal expansion',
  'coef. of lin. therm expansion parallel',
  'clte (flow direction)'],
 'compression set': ['compression set'],
 'compression set iso 815 23°c (%)': ['compression set at 23c'],
 'compression set iso 815 23°c, 24h (%)': ['compression set at 23c, 24h'],
 'compressive modulus iso 604 (mpa)': ['compressive modulus',
  'compressive module',
  'comp mod'],
 'compressive strength iso 604 (mpa)': ['compressive strength',
  'compressive stress'],
 'compressive stress at 1% strain iso 604 (mpa)': ['compressive stress at 1% strain',
  'compressive strength at 1% strain',
  'compressive stress 1% deformation',
  'compressive strength at 1% deformation'],
 'continuous service temperature iec 60216-1 (°c)': ['continuous service temperature',
  'continuous use temperature',
  'continuous allowable service temperature in air',
  'max service temperature',
  'min service temperature',
  'service temperature long term',
  'service temperature short term',
  'cut',
  'temperature resistance',
  'minimum operating temperature',
  'continuous utilization temperature'],
 'density iso 1183 (kg/m³)': ['density',
  'dense',
  'heavy',
  'heavy weight',
  'specific gravity'],
 'dissipation factor': ['dissipation factor',
  'tangent delta',
  'tan delta',
  'df',
  'dielectric dissipation factor',
  'dielectric dissipation',
  'loss angle',
  'loss tangent'],
 'dissipation factor iec 62631-2-1 100hz (e-4)': ['dissipation factor 100hz',
  'tangent delta at 100hz',
  'tangent delta, 100hz',
  'tan delta 100hz',
  'tan delta at 100hz',
  'df 100hz',
  '100hz df',
  'dielectric dissipation factor at 100hz',
  'dielectric dissipation factor, 100hz',
  'dielectric dissipation 100hz',
  'dielectric dissipation at 100hz',
  'loss angle at 100hz',
  'loss angle 100hz',
  'loss tangent 100hz',
  'loss tangent at 100hz'],
 'dissipation factor iec 62631-2-1 1mhz (e-4)': ['dissipation factor 1mhz',
  'tangent delta at 1mhz',
  'tangent delta, 1mhz',
  'tan delta 1mhz',
  'tan delta at 1mhz',
  'df 1mhz',
  '1mhz df',
  'dielectric dissipation factor at 1mhz',
  'dielectric dissipation factor, 1mhz',
  'dielectric dissipation 1mhz',
  'dielectric dissipation at 1mhz',
  'loss angle at 1mhz',
  'loss angle 1mhz',
  'loss tangent 1mhz',
  'loss tangent at 1mhz'],
 'effective thermal diffusivity': ['effective thermal diffusivity'],
 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)': ['effective thermal diffusivity, crossflow direction'],
 'effective thermal diffusivity iso 22007-4 flow (m²/s)': ['effective thermal diffusity, flow direction',
  'in plane thermal diffusivity'],
 'effective thermal diffusivity iso 22007-4 through plane (m²/s)': ['effective thermal diffusivity, through plane direction',
  'through plane thermal diffusivity',
  'cross plane thermal diffusivity'],
 'electric strength iec 60243-1 (kv/mm)': ['electric strength',
  'ac electristrength',
  'ac dielectric strength',
  'ac'],
 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)': ['elongation at break, perpendicular',
  'perpendicular elongation at break',
  'perpendicular break strain'],
 'elongational stress f iso 21304-2 150/10 (mpa)': ['elongational stress f'],
 'fiber areal weight (g/m²)': ['fiber areal weight'],
 'fiber volume content iso 11667 (%)': ['fiber volume content'],
 'flexural modulus': ['flexural modulus',
  'flex modulus',
  'flex mod',
  'flexural modulus of elasticity',
  'flexural performance',
  'rigid',
  'rigidity',
  'bend strength',
  'flexibility',
  'flexible',
  'flex'],
 'flexural modulus astm d 790 tape 0° (mpa)': ['tape flexural modulus',
  'tape flex modulus',
  'tape flex mod'],
 'flexural strain at failure': ['flexural strain at failure',
  'flexural elongation at break',
  'failure flex strain'],
 'flexural strain at failure astm d 790 tape 0° (%)': ['flexural strain at failure, tape',
  'tape flex strain failure'],
 'flexural strength': ['flexural strength', 'flex str', 'flex stress'],
 'flexural strength astm d 790 tape 0° (mpa)': ['tape flexural strength',
  'tape flex strength',
  'tape flex str',
  'tape flex stress'],
 'flexural stress at 3.5% iso 178 (mpa)': ['flexural stress at 3.5%',
  'flex stress at 3.5% elongation',
  'flex str at 3.5% strain'],
 'glass transition temperature iso 11357-1/-3 10°c/min (°c)': ['glass transition temperature',
  'glass transition',
  'tg'],
 'hardness, rockwell': ['hardness, rockwell', 'rockwell hardness'],
 'hardness, rockwell iso 2039-2 m-scale': ['hardness, rockwell m-scale',
  'rockwell hardness m-scale',
  'rockwell, m',
  'hardness rockwell m'],
 'hardness, rockwell iso 2039-2 r-scale': ['hardness, rockwell r-scale',
  'rockwell hardness r-scale',
  'rockwell, r',
  'hardness rockwell r'],
 'humidity absorption sim. to iso 62 2mm (%)': ['humidity absorption',
  'humid',
  'humidity'],
 'intrinsic viscosity iso 307, 1628': ['intrinsic viscosity', 'η', 'intrvisc'],
 'izod impact strength': ['izod impact strength',
  'izod impact',
  'impact izod',
  'izod unnotched',
  'izod unnotch',
  'unnotched izod',
  'unnotch izod',
  'izod unnotched impact',
  'izod unnotch impact',
  'unnotched izod impact',
  'unnotch izod impact',
  'izod impact strength unnotched',
  'izod impact strength unnotch',
  'izod impact strength (unnotched)',
  'izod impact strength (unnotch)',
  'izod impact unnotched',
  'izod impact unnotch',
  'izod impact (unnotched)',
  'izod impact (unnotch)'],
 'izod notched impact strength': ['izod notched impact strength',
  'izod notched',
  'izod notch',
  'notched izod',
  'notch izod',
  'izod notched impact',
  'izod notch impact',
  'notched izod impact',
  'notch izod impact',
  'izod impact strength notched',
  'izod impact strength notch',
  'izod impact strength (notched)',
  'izod impact strength (notch)',
  'izod impact notched',
  'izod impact notch',
  'izod impact (notched)',
  'izod impact (notch)'],
 'melt mass-flow rate iso 1133 (g/10min)': ['melt mass-flow rate',
  'melt mass flow rate',
  'melt flow rate',
  'mfr',
  'flow rate',
  'melt index',
  'melt flow index',
  'mfi',
  'flow',
  'mi'],
 'melt volume-flow rate iso 1133 (cm³/10min)': ['melt volume-flow rate',
  'melt volume flow rate',
  'melt volume rate',
  'mvr',
  'melt volume',
  'mv'],
 'melting temperature iso 11357-1/-3 10°c/min (°c)': ['melting temperature',
  'melt temp',
  'dsc melting temp',
  'mp'],
 'molding shrinkage': ['molding shrinkage',
  'moulding shrinkage',
  'mold shrinkage',
  'mold-shrinkage',
  'mould shrinkage',
  'dimensional, precise',
  'dimensional precision',
  'mold shrinkage (md/td)'],
 'molding shrinkage iso 294-4, 2577 normal (%)': ['molding shrinkage, normal',
  'mold shrinkage (x-flow)',
  'mold shrinkage (td)',
  'mold shrinkage normal',
  'mold shrinkage(transverse direction)',
  'mold-shrinkage, normal',
  'mould shrinkage normal',
  'mould-shrinkage',
  'mould-shrinkage, normal'],
 'molding shrinkage iso 294-4, 2577 parallel (%)': ['molding shrinkage, parallel',
  'mold shrinkage (flow)',
  'mold shrinkage (md)',
  'mold shrinkage flow',
  'mold shrinkage machine direction',
  'mold shrinkage md',
  'mold shrinkage parallel',
  'mold-shrinkage, parallel',
  'mould shrinkage parallel',
  'mould-shrinkage, parallel'],
 'nominal strain at break iso 527-1/-2 (%)': ['nominal strain at break',
  'nominal elongation at break',
  'nominal break strain',
  'nominal break elongation',
  'nominal strain, break',
  'nominal elongation',
  'break'],
 'oxygen index iso 4589-1/-2 (%)': ['oxygen index', 'loi', 'limiting oxygen'],
 "poisson's ratio": ["poisson's ratio", 'poissons ratio'],
 'puncture - maximum force iso 6603-2 23°c (n)': ['puncture - maximum force',
  'puncture maximum force',
  'maximum puncture force'],
 'puncture energy': ['puncture energy'],
 'relative permittivity': ['relative permittivity',
  'dk',
  'dielectric factor',
  'dielectric loss'],
 'relative permittivity iec 62631-2-1 100hz': ['relative permittivity at 100hz',
  'dk at 100hz',
  'dielectric factor at 100hz',
  'dielectric loss at 100hz',
  '100hz dk',
  'relative permittivity 100hz',
  'dk 100hz',
  'dielectric factor 100hz',
  'dielectric loss 100hz'],
 'relative permittivity iec 62631-2-1 1mhz': ['relative permittivity at 1mhz',
  'dk at 1mhz',
  'dielectric factor at 1mhz',
  'dielectric loss at 1mhz',
  '1mhz dk',
  'relative permittivity 1mhz',
  'dk 1mhz',
  'dielectric factor 1mhz',
  'dielectric loss 1mhz'],
 'relative permittivity iec 62631-2-1 60hz': ['relative permittivity at 60hz',
  'dk at 60hz',
  'dielectric factor at 60hz',
  'dielectric loss at 60hz',
  '60hz dk',
  'relative permittivity 60hz',
  'dk 60hz',
  'dielectric factor 60hz',
  'dielectric loss 60hz'],
 'shore a hardness iso 48-4 / iso 868 15s': ['shore a hardness',
  'shore a',
  'sh a',
  'durometer hardness (a)',
  'durometer hardness (shore a)',
  'a',
  'soft',
  'hardness, shore a iso 48-4 / iso 868 15s'],
 'shore d hardness iso 48-4 / iso 868 15s': ['shore d hardness',
  'shore d',
  'sh d',
  'durometer hardness (d)',
  'durometer hardness (shore d)',
  'd',
  'hardness, shore d iso 48-4 / iso 868 15s'],
 'shore hardness': ['durometer hardness'],
 'specific heat capacity of melt iso 22007-4 (j/(kg k))': ['specific heat capacity of melt'],
 'surface resistivity iec 62631-3-2 (ohm)': ['surface resistivity',
  'surf_res',
  'sr'],
 'tape areal weight (g/m²)': ['tape areal weight'],
 'tape thickness iso 16012 (mm)': ['tape thickness'],
 'tape width iso 16012 (mm)': ['tape width'],
 'tear strength iso 34-1 normal (kn/m)': ['tear strength',
  'tear stress',
  'burst strength'],
 'temperature of deflection under load': ['temperature of deflection under load',
  'temp. of deflection under load',
  'dtul',
  'hdt',
  'deflection temperature'],
 'temperature of deflection under load iso 75-1/-2 0.45 mpa (°c)': ['temperature of deflection under load 0.45 mpa',
  'temp. of deflection under load 0.45 mpa',
  'deflection temperature 0.45mpa',
  'deflection temperature 66psi',
  'hdt 0.45mpa',
  'temp. of deflection under load 65 psi annealed',
  'dtul 0.45mpa'],
 'temperature of deflection under load iso 75-1/-2 1.8 mpa (°c)': ['temperature of deflection under load 1.80 mpa',
  'temp. of deflection under load 1.80 mpa',
  'deflection temperature 1.8mpa',
  'deflection temperature 264psi',
  'hdt 1.8mpa',
  'temp. of deflection under load 260 psi annealed',
  'dtul 1.8mpa'],
 'temperature of deflection under load iso 75-1/-2 8 mpa (°c)': ['temperature of deflection under load 8.0 mpa',
  'temp. of deflection under load 8.0 mpa',
  'deflection temperature 8.0mpa',
  'hdt 8.0mpa',
  'dtul 8.0mpa'],
 'tensile creep modulus': ['tensile creep modulus'],
 'tensile creep modulus iso 899-1 1000h (mpa)': ['tensile creep modulus at 1000h'],
 'tensile creep modulus iso 899-1 1h (mpa)': ['tensile creep modulus at 1h'],
 'tensile modulus': ['tensile modulus',
  'young modulus',
  "young's modulus",
  'stiff',
  'ten mod',
  'e-modulus',
  'e modulus',
  'modulus of elasticity',
  'tensile mod',
  "tensile young's modulus",
  'youngs e modulus',
  'youngs modulus',
  'emod',
  'e-mod',
  'tensile module',
  'stiffness',
  'mechanical strength',
  'mechanical behavior',
  'mechanical resistance',
  'mechanical properties',
  'deformation',
  'deformation stability',
  'mechanical performance',
  'elastic modulus',
  'strength modulus'],
 'tensile modulus astm d 3039 m tape 0° (mpa)': ['tape tens mod',
  'tape tensile modulus',
  'tape tensile mod',
  'tape modulus of elasticity',
  'tape e modulus'],
 'tensile notched impact strength iso 8256/1 23°c (kj/m²)': ['tensile notched impact strength',
  'tensile impact notched',
  'n tenile impact'],
 'tensile strain at break': ['tensile strain at break',
  'break strain, break elongation',
  'elongation at break',
  'elongation break'],
 'tensile strain at break iso 527-1/-2 50mm/min (%)': ['tensile strain at break 50mm/min',
  'strain at break 50mm/min',
  'strain at break 50 mm/min',
  'strain break 50mm/min',
  'strain break 50 mm/min',
  'break strain 50mm/min',
  'break strain 50 mm/min',
  'elongation at break 50mm/min',
  'elongation at break 50 mm/min',
  'elongation break 50mm/min',
  'elongation break 50 mm/min',
  'break elongation 50mm/min',
  'break elongation 50 mm/min'],
 'tensile strain at break iso 527-1/-2 5mm/min (%)': ['tensile strain at break 5mm/min',
  'strain at break 5mm/min',
  'strain at break 5 mm/min',
  'strain break 5mm/min',
  'strain break 5 mm/min',
  'break strain 5mm/min',
  'break strain 5 mm/min',
  'elongation at break 5mm/min',
  'elongation at break 5 mm/min',
  'elongation break 5mm/min',
  'elongation break 5 mm/min',
  'break elongation 5mm/min',
  'break elongation 5 mm/min'],
 'tensile strain at failure astm d 3039 m tape 0° (%)': ['tensile strain at failure'],
 'tensile strain at yield iso 527-1/-2 50mm/min (%)': ['tensile strain at yield',
  'tensile strain at yield 50mm/min',
  'strain at yield 50mm/min',
  'strain at yield 50 mm/min',
  'strain yield 50mm/min',
  'strain yield 50 mm/min',
  'yield strain 50mm/min',
  'yield strain 50 mm/min',
  'yield strain',
  'strain at yield',
  'elongation at yield 50mm/min',
  'elongation at yield 50 mm/min',
  'elongation yield 50mm/min',
  'elongation yield 50 mm/min',
  'yield elongation 50mm/min',
  'yield elongation 50 mm/min',
  'yield elongation',
  'elongation at yield',
  'strain yield'],
 'tensile strength astm d 3039 m tape 0° (mpa)': ['tensile strength tape',
  'tape tensile strength'],
 'tensile stress at 100% elongation iso 37 perpendicular (mpa)': ['tensile stress at 100% elongation, perpendicular',
  'tensile stress at 100% strain, perpendicular',
  'tensile stress at 100% deformation, perpendicular',
  'perpendicular tensile stress at 100% elongation',
  'perpendicular tensile stress at 100% strain',
  'perpendicular tensile stress at 100% deformation'],
 'tensile stress at 100% strain iso 527-1/-2 (mpa)': ['tensile stress at 100% strain',
  'stress at 100% deformation'],
 'tensile stress at 50% strain iso 527-1/-2 (mpa)': ['tensile stress at 50% strain',
  'stress at 50% elongation',
  'stress at 50% deformation'],
 'tensile stress at break': ['strebr',
  'tensile strength at break',
  'tensile stress (break)',
  'break stress',
  'ten stress brk'],
 'tensile stress at break iso 527-1/-2 50mm/min (mpa)': ['tensile stress at break at 50mm/min',
  'strebr at 50mm/min',
  'tensile strength at break at 50mm/min',
  'tensile stress (break) at 50mm/min',
  'break stress at 50mm/min',
  'ten stress brk at 50mm/min'],
 'tensile stress at break iso 527-1/-2 5mm/min (mpa)': ['tensile stress at break at 5mm/min',
  'strebr at 5mm/min',
  'tensile strength at break at 5mm/min',
  'tensile stress (break) at 5mm/min',
  'break stress at 5mm/min',
  'ten stress brk at 5mm/min'],
 'tensile stress at break iso 527-1/-2 or iso 37 perpendicular (mpa)': ['tensile stress at break perpendicular',
  'perpendicular stress at break',
  'perpendicular break stress'],
 'tensile stress at yield iso 527-1/-2 50mm/min (mpa)': ['tensile stress at yield',
  'tensile stress at yield 50mm/min',
  'tensile strength (yield)',
  'tensile strength at yield',
  'tensile stress (yield)',
  'yield stress'],
 'thermal conductivity': ['thermal conductive', 'heat transfer'],
 'thermal conductivity iso 22007-2 crossflow (w/(m k))': ['thermal conductivity crossflow direction',
  'cross plane thermal conductivity'],
 'thermal conductivity iso 22007-2 flow (w/(m k))': ['thermal conductivity flow direction',
  'in plane thermal conductivity'],
 'thermal conductivity iso 22007-2 through plane (w/(m k))': ['thermal conductivity through plane',
  'thermal conductivity thruplane direction',
  'thruplane thermal conductivity'],
 'thermal conductivity of melt iso 22007-2 (w/(m k))': ['thermal conductivity of melt'],
 'vicat softening temperature': ['vicat softening temperature',
  'vicat',
  'vicat softening point',
  'vicat softing temp'],
 'vicat softening temperature iso 306 50°c/h 10n (°c)': ['vicat softening temperature at 50°c/h 10n',
  'vicat at 50°c/h 10n',
  'vicat softening point at 50°c/h 10n',
  'vicat softing temp at 50°c/h 10n'],
 'vicat softening temperature iso 306 50°c/h 50n (°c)': ['vicat softening temperature at 50°c/h 50n',
  'vicat at 50°c/h 50n',
  'vicat softening point at 50°c/h 50n',
  'vicat softing temp at 50°c/h 50n'],
 'viscosity number iso 307, 1628 (cm³/g)': ['viscosity number',
  'h2so4',
  'viscosity number (0.5% in 96 % h2so4)',
  'vn at 0.5% in sulfuric acid nominal',
  'viscosity h2so4'],
 'volume resistivity iec 62631-3-1 (ohm.m)': ['volume resistivity',
  'volres',
  'vr'],
 'water absorption sim. to iso 62 2mm (%)': ['water absorption',
  'h20 absorption',
  'water',
  'moisture uptake',
  'moisture absorption',
  'moisture absorption equilibrium 23°c/50% r.h.'],
 'wear by sandslurry method (based on gur 4120=100)': ['wear by sandslurry method']}

In [79]:
list(property_syns)

["average molecular weight margolies' equation (g/mol)",
 'average particle size laser scattering d50 (µm)',
 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'ball pressure test iec 60695-10-2 (°c)',
 'bulk density iso 60 (kg/m³)',
 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy impact strength',
 'charpy notched impact strength',
 'coefficient of linear thermal expansion (clte)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'compression set',
 'compression set iso 815 23°c (%)',
 'compression set iso 815 23°c, 24h (%)',
 'compressive modulus iso 604 (mpa)',
 'compressive strength iso 604 (mpa)',
 'compressive stress at 1% strain iso 604 (mpa)',
 'continuous service temperature iec 60216-1 (°c)',
 'density iso 1183 (kg/m³)',
 'dissipation factor',
 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'effective thermal diffusivity',
 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)',
 'effective thermal diffusivity iso 22007-4 flow (m²/s)',
 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'electric strength iec 60243-1 (kv/mm)',
 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'elongational stress f iso 21304-2 150/10 (mpa)',
 'fiber areal weight (g/m²)',
 'fiber volume content iso 11667 (%)',
 'flexural modulus',
 'flexural modulus astm d 790 tape 0° (mpa)',
 'flexural strain at failure',
 'flexural strain at failure astm d 790 tape 0° (%)',
 'flexural strength',
 'flexural strength astm d 790 tape 0° (mpa)',
 'flexural stress at 3.5% iso 178 (mpa)',
 'glass transition temperature iso 11357-1/-3 10°c/min (°c)',
 'hardness, rockwell',
 'hardness, rockwell iso 2039-2 m-scale',
 'hardness, rockwell iso 2039-2 r-scale',
 'humidity absorption sim. to iso 62 2mm (%)',
 'intrinsic viscosity iso 307, 1628',
 'izod impact strength',
 'izod notched impact strength',
 'melt mass-flow rate iso 1133 (g/10min)',
 'melt volume-flow rate iso 1133 (cm³/10min)',
 'melting temperature iso 11357-1/-3 10°c/min (°c)',
 'molding shrinkage',
 'molding shrinkage iso 294-4, 2577 normal (%)',
 'molding shrinkage iso 294-4, 2577 parallel (%)',
 'nominal strain at break iso 527-1/-2 (%)',
 'oxygen index iso 4589-1/-2 (%)',
 "poisson's ratio",
 'puncture - maximum force iso 6603-2 23°c (n)',
 'puncture energy',
 'relative permittivity',
 'relative permittivity iec 62631-2-1 100hz',
 'relative permittivity iec 62631-2-1 1mhz',
 'relative permittivity iec 62631-2-1 60hz',
 'shore a hardness iso 48-4 / iso 868 15s',
 'shore d hardness iso 48-4 / iso 868 15s',
 'shore hardness',
 'specific heat capacity of melt iso 22007-4 (j/(kg k))',
 'surface resistivity iec 62631-3-2 (ohm)',
 'tape areal weight (g/m²)',
 'tape thickness iso 16012 (mm)',
 'tape width iso 16012 (mm)',
 'tear strength iso 34-1 normal (kn/m)',
 'temperature of deflection under load',
 'temperature of deflection under load iso 75-1/-2 0.45 mpa (°c)',
 'temperature of deflection under load iso 75-1/-2 1.8 mpa (°c)',
 'temperature of deflection under load iso 75-1/-2 8 mpa (°c)',
 'tensile creep modulus',
 'tensile creep modulus iso 899-1 1000h (mpa)',
 'tensile creep modulus iso 899-1 1h (mpa)',
 'tensile modulus',
 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tensile notched impact strength iso 8256/1 23°c (kj/m²)',
 'tensile strain at break',
 'tensile strain at break iso 527-1/-2 50mm/min (%)',
 'tensile strain at break iso 527-1/-2 5mm/min (%)',
 'tensile strain at failure astm d 3039 m tape 0° (%)',
 'tensile strain at yield iso 527-1/-2 50mm/min (%)',
 'tensile strength astm d 3039 m tape 0° (mpa)',
 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
 'tensile stress at 100% strain iso 527-1/-2 (mpa)',
 'tensile stress at 50% strain iso 527-1/-2 (mpa)',
 'tensile stress at break',
 'tensile stress at break iso 527-1/-2 50mm/min (mpa)',
 'tensile stress at break iso 527-1/-2 5mm/min (mpa)',
 'tensile stress at break iso 527-1/-2 or iso 37 perpendicular (mpa)',
 'tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
 'thermal conductivity',
 'thermal conductivity iso 22007-2 crossflow (w/(m k))',
 'thermal conductivity iso 22007-2 flow (w/(m k))',
 'thermal conductivity iso 22007-2 through plane (w/(m k))',
 'thermal conductivity of melt iso 22007-2 (w/(m k))',
 'vicat softening temperature',
 'vicat softening temperature iso 306 50°c/h 10n (°c)',
 'vicat softening temperature iso 306 50°c/h 50n (°c)',
 'viscosity number iso 307, 1628 (cm³/g)',
 'volume resistivity iec 62631-3-1 (ohm.m)',
 'water absorption sim. to iso 62 2mm (%)',
 'wear by sandslurry method (based on gur 4120=100)']

In [80]:
all_property_names = []
for i in unique_values['Property']:
    all_property_names.append(i['PROPERTY_NAME_UI'].lower())

all_property_names2 = []
for i in unique_values['Property']:
    all_property_names2.append(i['PROPERTY_NAME'].lower())
    
for i in list(property_syns):
    if i not in all_property_names:
        # print(i)
        if i not in all_property_names2:
            print(i)
            # pass

shore hardness
thermal conductivity of melt iso 22007-2 (w/(m k))

In [81]:
prop_not_mapped = [
    'shore hardness',
    'thermal conductivity of melt iso 22007-2 (w/(m k))',
]

In [82]:
prop_syn_meaning_mapped = {
    'shore hardness': 'shore hardness',
    'thermal conductivity of melt iso 22007-2 (w/(m k))': 'thermal conductivity iso 22007-2 flow (w/(m k))',
    'tensile stress at 100% elongation iso 527-1/-2 or iso 37 perpendicular (mpa)': 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
}

In [83]:
prop_df['DEFINED_NAME'] = prop_df['DEFINED_NAME'].replace(to_replace=prop_syn_meaning_mapped)
property_syns = prop_df.groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
property_syns

{"average molecular weight margolies' equation (g/mol)": ['average molecular weight',
  'average molar mass',
  'average molecular mass',
  'avermw',
  'molecular weight',
  'mw'],
 'average particle size laser scattering d50 (µm)': ['average particle size laser scattering d50 (µm)',
  'average particle size',
  'avg. particle size',
  'avpartsize',
  'particle size',
  'particle size d50'],
 'ball indentation hardness iso 2039-1 h 358/30 (mpa)': ['ball indentation hardness',
  'ball indention hardness'],
 'ball pressure test iec 60695-10-2 (°c)': ['ball pressure test'],
 'bulk density iso 60 (kg/m³)': ['bulk density',
  'apparent (bulk) density',
  'apparent density',
  'bulkdens'],
 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)': ['charpy double notched impact strength',
  'charpy impact strength (double notched)',
  'charpy impact strength (double notch)',
  'double notch charpy impact strength',
  'double notched charpy impact strength',
  'double notch charpy',
  'double notched charpy',
  'double notch impact',
  'double notched impact',
  'charpy double notch',
  'charpy double notched'],
 'charpy impact strength': ['charpy impact strength',
  'charpy impact',
  'impact charpy',
  'charpy unnotched',
  'charpy unnotch',
  'unnotched charpy',
  'unnotch charpy',
  'charpy unnotched impact',
  'charpy unnotch impact',
  'unnotched charpy impact',
  'unnotch charpy impact',
  'charpy impact strength unnotched',
  'charpy impact strength unnotch',
  'charpy impact strength (unnotched)',
  'charpy impact strength (unnotch)',
  'charpy impact unnotched',
  'charpy impact unnotch',
  'charpy impact (unnotched)',
  'charpy impact (unnotch)'],
 'charpy notched impact strength': ['charpy notched impact strength',
  'charpy notched',
  'charpy notch',
  'notched charpy',
  'notch charpy',
  'charpy notched impact',
  'charpy notch impact',
  'notched charpy impact',
  'notch charpy impact',
  'charpy impact strength notched',
  'charpy impact strength notch',
  'charpy impact strength (notched)',
  'charpy impact strength (notch)',
  'charpy impact notched',
  'charpy impact notch',
  'charpy impact (notched)',
  'charpy impact (notch)'],
 'coefficient of linear thermal expansion (clte)': ['coefficient of linear thermal expansion (clte)',
  'coefficient of linear thermal expansion',
  'clte',
  'linear expansion factor',
  'thermal expansion',
  'linear thermal expansion',
  'coef. of lin. therm expansion'],
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)': ['linear expansion factor (normal)',
  'normal thermal expansion',
  'normal linear thermal expansion',
  'coef. of lin. therm expansion normal',
  'clte (transverse direction)'],
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)': ['linear expansion factor (parallel)',
  'parallel thermal expansion',
  'parallel linear thermal expansion',
  'coef. of lin. therm expansion parallel',
  'clte (flow direction)'],
 'compression set': ['compression set'],
 'compression set iso 815 23°c (%)': ['compression set at 23c'],
 'compression set iso 815 23°c, 24h (%)': ['compression set at 23c, 24h'],
 'compressive modulus iso 604 (mpa)': ['compressive modulus',
  'compressive module',
  'comp mod'],
 'compressive strength iso 604 (mpa)': ['compressive strength',
  'compressive stress'],
 'compressive stress at 1% strain iso 604 (mpa)': ['compressive stress at 1% strain',
  'compressive strength at 1% strain',
  'compressive stress 1% deformation',
  'compressive strength at 1% deformation'],
 'continuous service temperature iec 60216-1 (°c)': ['continuous service temperature',
  'continuous use temperature',
  'continuous allowable service temperature in air',
  'max service temperature',
  'min service temperature',
  'service temperature long term',
  'service temperature short term',
  'cut',
  'temperature resistance',
  'minimum operating temperature',
  'continuous utilization temperature'],
 'density iso 1183 (kg/m³)': ['density',
  'dense',
  'heavy',
  'heavy weight',
  'specific gravity'],
 'dissipation factor': ['dissipation factor',
  'tangent delta',
  'tan delta',
  'df',
  'dielectric dissipation factor',
  'dielectric dissipation',
  'loss angle',
  'loss tangent'],
 'dissipation factor iec 62631-2-1 100hz (e-4)': ['dissipation factor 100hz',
  'tangent delta at 100hz',
  'tangent delta, 100hz',
  'tan delta 100hz',
  'tan delta at 100hz',
  'df 100hz',
  '100hz df',
  'dielectric dissipation factor at 100hz',
  'dielectric dissipation factor, 100hz',
  'dielectric dissipation 100hz',
  'dielectric dissipation at 100hz',
  'loss angle at 100hz',
  'loss angle 100hz',
  'loss tangent 100hz',
  'loss tangent at 100hz'],
 'dissipation factor iec 62631-2-1 1mhz (e-4)': ['dissipation factor 1mhz',
  'tangent delta at 1mhz',
  'tangent delta, 1mhz',
  'tan delta 1mhz',
  'tan delta at 1mhz',
  'df 1mhz',
  '1mhz df',
  'dielectric dissipation factor at 1mhz',
  'dielectric dissipation factor, 1mhz',
  'dielectric dissipation 1mhz',
  'dielectric dissipation at 1mhz',
  'loss angle at 1mhz',
  'loss angle 1mhz',
  'loss tangent 1mhz',
  'loss tangent at 1mhz'],
 'effective thermal diffusivity': ['effective thermal diffusivity'],
 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)': ['effective thermal diffusivity, crossflow direction'],
 'effective thermal diffusivity iso 22007-4 flow (m²/s)': ['effective thermal diffusity, flow direction',
  'in plane thermal diffusivity'],
 'effective thermal diffusivity iso 22007-4 through plane (m²/s)': ['effective thermal diffusivity, through plane direction',
  'through plane thermal diffusivity',
  'cross plane thermal diffusivity'],
 'electric strength iec 60243-1 (kv/mm)': ['electric strength',
  'ac electristrength',
  'ac dielectric strength',
  'ac'],
 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)': ['elongation at break, perpendicular',
  'perpendicular elongation at break',
  'perpendicular break strain'],
 'elongational stress f iso 21304-2 150/10 (mpa)': ['elongational stress f'],
 'fiber areal weight (g/m²)': ['fiber areal weight'],
 'fiber volume content iso 11667 (%)': ['fiber volume content'],
 'flexural modulus': ['flexural modulus',
  'flex modulus',
  'flex mod',
  'flexural modulus of elasticity',
  'flexural performance',
  'rigid',
  'rigidity',
  'bend strength',
  'flexibility',
  'flexible',
  'flex'],
 'flexural modulus astm d 790 tape 0° (mpa)': ['tape flexural modulus',
  'tape flex modulus',
  'tape flex mod'],
 'flexural strain at failure': ['flexural strain at failure',
  'flexural elongation at break',
  'failure flex strain'],
 'flexural strain at failure astm d 790 tape 0° (%)': ['flexural strain at failure, tape',
  'tape flex strain failure'],
 'flexural strength': ['flexural strength', 'flex str', 'flex stress'],
 'flexural strength astm d 790 tape 0° (mpa)': ['tape flexural strength',
  'tape flex strength',
  'tape flex str',
  'tape flex stress'],
 'flexural stress at 3.5% iso 178 (mpa)': ['flexural stress at 3.5%',
  'flex stress at 3.5% elongation',
  'flex str at 3.5% strain'],
 'glass transition temperature iso 11357-1/-3 10°c/min (°c)': ['glass transition temperature',
  'glass transition',
  'tg'],
 'hardness, rockwell': ['hardness, rockwell', 'rockwell hardness'],
 'hardness, rockwell iso 2039-2 m-scale': ['hardness, rockwell m-scale',
  'rockwell hardness m-scale',
  'rockwell, m',
  'hardness rockwell m'],
 'hardness, rockwell iso 2039-2 r-scale': ['hardness, rockwell r-scale',
  'rockwell hardness r-scale',
  'rockwell, r',
  'hardness rockwell r'],
 'humidity absorption sim. to iso 62 2mm (%)': ['humidity absorption',
  'humid',
  'humidity'],
 'intrinsic viscosity iso 307, 1628': ['intrinsic viscosity', 'η', 'intrvisc'],
 'izod impact strength': ['izod impact strength',
  'izod impact',
  'impact izod',
  'izod unnotched',
  'izod unnotch',
  'unnotched izod',
  'unnotch izod',
  'izod unnotched impact',
  'izod unnotch impact',
  'unnotched izod impact',
  'unnotch izod impact',
  'izod impact strength unnotched',
  'izod impact strength unnotch',
  'izod impact strength (unnotched)',
  'izod impact strength (unnotch)',
  'izod impact unnotched',
  'izod impact unnotch',
  'izod impact (unnotched)',
  'izod impact (unnotch)'],
 'izod notched impact strength': ['izod notched impact strength',
  'izod notched',
  'izod notch',
  'notched izod',
  'notch izod',
  'izod notched impact',
  'izod notch impact',
  'notched izod impact',
  'notch izod impact',
  'izod impact strength notched',
  'izod impact strength notch',
  'izod impact strength (notched)',
  'izod impact strength (notch)',
  'izod impact notched',
  'izod impact notch',
  'izod impact (notched)',
  'izod impact (notch)'],
 'melt mass-flow rate iso 1133 (g/10min)': ['melt mass-flow rate',
  'melt mass flow rate',
  'melt flow rate',
  'mfr',
  'flow rate',
  'melt index',
  'melt flow index',
  'mfi',
  'flow',
  'mi'],
 'melt volume-flow rate iso 1133 (cm³/10min)': ['melt volume-flow rate',
  'melt volume flow rate',
  'melt volume rate',
  'mvr',
  'melt volume',
  'mv'],
 'melting temperature iso 11357-1/-3 10°c/min (°c)': ['melting temperature',
  'melt temp',
  'dsc melting temp',
  'mp'],
 'molding shrinkage': ['molding shrinkage',
  'moulding shrinkage',
  'mold shrinkage',
  'mold-shrinkage',
  'mould shrinkage',
  'dimensional, precise',
  'dimensional precision',
  'mold shrinkage (md/td)'],
 'molding shrinkage iso 294-4, 2577 normal (%)': ['molding shrinkage, normal',
  'mold shrinkage (x-flow)',
  'mold shrinkage (td)',
  'mold shrinkage normal',
  'mold shrinkage(transverse direction)',
  'mold-shrinkage, normal',
  'mould shrinkage normal',
  'mould-shrinkage',
  'mould-shrinkage, normal'],
 'molding shrinkage iso 294-4, 2577 parallel (%)': ['molding shrinkage, parallel',
  'mold shrinkage (flow)',
  'mold shrinkage (md)',
  'mold shrinkage flow',
  'mold shrinkage machine direction',
  'mold shrinkage md',
  'mold shrinkage parallel',
  'mold-shrinkage, parallel',
  'mould shrinkage parallel',
  'mould-shrinkage, parallel'],
 'nominal strain at break iso 527-1/-2 (%)': ['nominal strain at break',
  'nominal elongation at break',
  'nominal break strain',
  'nominal break elongation',
  'nominal strain, break',
  'nominal elongation',
  'break'],
 'oxygen index iso 4589-1/-2 (%)': ['oxygen index', 'loi', 'limiting oxygen'],
 "poisson's ratio": ["poisson's ratio", 'poissons ratio'],
 'puncture - maximum force iso 6603-2 23°c (n)': ['puncture - maximum force',
  'puncture maximum force',
  'maximum puncture force'],
 'puncture energy': ['puncture energy'],
 'relative permittivity': ['relative permittivity',
  'dk',
  'dielectric factor',
  'dielectric loss'],
 'relative permittivity iec 62631-2-1 100hz': ['relative permittivity at 100hz',
  'dk at 100hz',
  'dielectric factor at 100hz',
  'dielectric loss at 100hz',
  '100hz dk',
  'relative permittivity 100hz',
  'dk 100hz',
  'dielectric factor 100hz',
  'dielectric loss 100hz'],
 'relative permittivity iec 62631-2-1 1mhz': ['relative permittivity at 1mhz',
  'dk at 1mhz',
  'dielectric factor at 1mhz',
  'dielectric loss at 1mhz',
  '1mhz dk',
  'relative permittivity 1mhz',
  'dk 1mhz',
  'dielectric factor 1mhz',
  'dielectric loss 1mhz'],
 'relative permittivity iec 62631-2-1 60hz': ['relative permittivity at 60hz',
  'dk at 60hz',
  'dielectric factor at 60hz',
  'dielectric loss at 60hz',
  '60hz dk',
  'relative permittivity 60hz',
  'dk 60hz',
  'dielectric factor 60hz',
  'dielectric loss 60hz'],
 'shore a hardness iso 48-4 / iso 868 15s': ['shore a hardness',
  'shore a',
  'sh a',
  'durometer hardness (a)',
  'durometer hardness (shore a)',
  'a',
  'soft',
  'hardness, shore a iso 48-4 / iso 868 15s'],
 'shore d hardness iso 48-4 / iso 868 15s': ['shore d hardness',
  'shore d',
  'sh d',
  'durometer hardness (d)',
  'durometer hardness (shore d)',
  'd',
  'hardness, shore d iso 48-4 / iso 868 15s'],
 'shore hardness': ['durometer hardness'],
 'specific heat capacity of melt iso 22007-4 (j/(kg k))': ['specific heat capacity of melt'],
 'surface resistivity iec 62631-3-2 (ohm)': ['surface resistivity',
  'surf_res',
  'sr'],
 'tape areal weight (g/m²)': ['tape areal weight'],
 'tape thickness iso 16012 (mm)': ['tape thickness'],
 'tape width iso 16012 (mm)': ['tape width'],
 'tear strength iso 34-1 normal (kn/m)': ['tear strength',
  'tear stress',
  'burst strength'],
 'temperature of deflection under load': ['temperature of deflection under load',
  'temp. of deflection under load',
  'dtul',
  'hdt',
  'deflection temperature'],
 'temperature of deflection under load iso 75-1/-2 0.45 mpa (°c)': ['temperature of deflection under load 0.45 mpa',
  'temp. of deflection under load 0.45 mpa',
  'deflection temperature 0.45mpa',
  'deflection temperature 66psi',
  'hdt 0.45mpa',
  'temp. of deflection under load 65 psi annealed',
  'dtul 0.45mpa'],
 'temperature of deflection under load iso 75-1/-2 1.8 mpa (°c)': ['temperature of deflection under load 1.80 mpa',
  'temp. of deflection under load 1.80 mpa',
  'deflection temperature 1.8mpa',
  'deflection temperature 264psi',
  'hdt 1.8mpa',
  'temp. of deflection under load 260 psi annealed',
  'dtul 1.8mpa'],
 'temperature of deflection under load iso 75-1/-2 8 mpa (°c)': ['temperature of deflection under load 8.0 mpa',
  'temp. of deflection under load 8.0 mpa',
  'deflection temperature 8.0mpa',
  'hdt 8.0mpa',
  'dtul 8.0mpa'],
 'tensile creep modulus': ['tensile creep modulus'],
 'tensile creep modulus iso 899-1 1000h (mpa)': ['tensile creep modulus at 1000h'],
 'tensile creep modulus iso 899-1 1h (mpa)': ['tensile creep modulus at 1h'],
 'tensile modulus': ['tensile modulus',
  'young modulus',
  "young's modulus",
  'stiff',
  'ten mod',
  'e-modulus',
  'e modulus',
  'modulus of elasticity',
  'tensile mod',
  "tensile young's modulus",
  'youngs e modulus',
  'youngs modulus',
  'emod',
  'e-mod',
  'tensile module',
  'stiffness',
  'mechanical strength',
  'mechanical behavior',
  'mechanical resistance',
  'mechanical properties',
  'deformation',
  'deformation stability',
  'mechanical performance',
  'elastic modulus',
  'strength modulus'],
 'tensile modulus astm d 3039 m tape 0° (mpa)': ['tape tens mod',
  'tape tensile modulus',
  'tape tensile mod',
  'tape modulus of elasticity',
  'tape e modulus'],
 'tensile notched impact strength iso 8256/1 23°c (kj/m²)': ['tensile notched impact strength',
  'tensile impact notched',
  'n tenile impact'],
 'tensile strain at break': ['tensile strain at break',
  'break strain, break elongation',
  'elongation at break',
  'elongation break'],
 'tensile strain at break iso 527-1/-2 50mm/min (%)': ['tensile strain at break 50mm/min',
  'strain at break 50mm/min',
  'strain at break 50 mm/min',
  'strain break 50mm/min',
  'strain break 50 mm/min',
  'break strain 50mm/min',
  'break strain 50 mm/min',
  'elongation at break 50mm/min',
  'elongation at break 50 mm/min',
  'elongation break 50mm/min',
  'elongation break 50 mm/min',
  'break elongation 50mm/min',
  'break elongation 50 mm/min'],
 'tensile strain at break iso 527-1/-2 5mm/min (%)': ['tensile strain at break 5mm/min',
  'strain at break 5mm/min',
  'strain at break 5 mm/min',
  'strain break 5mm/min',
  'strain break 5 mm/min',
  'break strain 5mm/min',
  'break strain 5 mm/min',
  'elongation at break 5mm/min',
  'elongation at break 5 mm/min',
  'elongation break 5mm/min',
  'elongation break 5 mm/min',
  'break elongation 5mm/min',
  'break elongation 5 mm/min'],
 'tensile strain at failure astm d 3039 m tape 0° (%)': ['tensile strain at failure'],
 'tensile strain at yield iso 527-1/-2 50mm/min (%)': ['tensile strain at yield',
  'tensile strain at yield 50mm/min',
  'strain at yield 50mm/min',
  'strain at yield 50 mm/min',
  'strain yield 50mm/min',
  'strain yield 50 mm/min',
  'yield strain 50mm/min',
  'yield strain 50 mm/min',
  'yield strain',
  'strain at yield',
  'elongation at yield 50mm/min',
  'elongation at yield 50 mm/min',
  'elongation yield 50mm/min',
  'elongation yield 50 mm/min',
  'yield elongation 50mm/min',
  'yield elongation 50 mm/min',
  'yield elongation',
  'elongation at yield',
  'strain yield'],
 'tensile strength astm d 3039 m tape 0° (mpa)': ['tensile strength tape',
  'tape tensile strength'],
 'tensile stress at 100% elongation iso 37 perpendicular (mpa)': ['tensile stress at 100% elongation, perpendicular',
  'tensile stress at 100% strain, perpendicular',
  'tensile stress at 100% deformation, perpendicular',
  'perpendicular tensile stress at 100% elongation',
  'perpendicular tensile stress at 100% strain',
  'perpendicular tensile stress at 100% deformation'],
 'tensile stress at 100% strain iso 527-1/-2 (mpa)': ['tensile stress at 100% strain',
  'stress at 100% deformation'],
 'tensile stress at 50% strain iso 527-1/-2 (mpa)': ['tensile stress at 50% strain',
  'stress at 50% elongation',
  'stress at 50% deformation'],
 'tensile stress at break': ['strebr',
  'tensile strength at break',
  'tensile stress (break)',
  'break stress',
  'ten stress brk'],
 'tensile stress at break iso 527-1/-2 50mm/min (mpa)': ['tensile stress at break at 50mm/min',
  'strebr at 50mm/min',
  'tensile strength at break at 50mm/min',
  'tensile stress (break) at 50mm/min',
  'break stress at 50mm/min',
  'ten stress brk at 50mm/min'],
 'tensile stress at break iso 527-1/-2 5mm/min (mpa)': ['tensile stress at break at 5mm/min',
  'strebr at 5mm/min',
  'tensile strength at break at 5mm/min',
  'tensile stress (break) at 5mm/min',
  'break stress at 5mm/min',
  'ten stress brk at 5mm/min'],
 'tensile stress at break iso 527-1/-2 or iso 37 perpendicular (mpa)': ['tensile stress at break perpendicular',
  'perpendicular stress at break',
  'perpendicular break stress'],
 'tensile stress at yield iso 527-1/-2 50mm/min (mpa)': ['tensile stress at yield',
  'tensile stress at yield 50mm/min',
  'tensile strength (yield)',
  'tensile strength at yield',
  'tensile stress (yield)',
  'yield stress'],
 'thermal conductivity': ['thermal conductive', 'heat transfer'],
 'thermal conductivity iso 22007-2 crossflow (w/(m k))': ['thermal conductivity crossflow direction',
  'cross plane thermal conductivity'],
 'thermal conductivity iso 22007-2 flow (w/(m k))': ['thermal conductivity flow direction',
  'in plane thermal conductivity',
  'thermal conductivity of melt'],
 'thermal conductivity iso 22007-2 through plane (w/(m k))': ['thermal conductivity through plane',
  'thermal conductivity thruplane direction',
  'thruplane thermal conductivity'],
 'vicat softening temperature': ['vicat softening temperature',
  'vicat',
  'vicat softening point',
  'vicat softing temp'],
 'vicat softening temperature iso 306 50°c/h 10n (°c)': ['vicat softening temperature at 50°c/h 10n',
  'vicat at 50°c/h 10n',
  'vicat softening point at 50°c/h 10n',
  'vicat softing temp at 50°c/h 10n'],
 'vicat softening temperature iso 306 50°c/h 50n (°c)': ['vicat softening temperature at 50°c/h 50n',
  'vicat at 50°c/h 50n',
  'vicat softening point at 50°c/h 50n',
  'vicat softing temp at 50°c/h 50n'],
 'viscosity number iso 307, 1628 (cm³/g)': ['viscosity number',
  'h2so4',
  'viscosity number (0.5% in 96 % h2so4)',
  'vn at 0.5% in sulfuric acid nominal',
  'viscosity h2so4'],
 'volume resistivity iec 62631-3-1 (ohm.m)': ['volume resistivity',
  'volres',
  'vr'],
 'water absorption sim. to iso 62 2mm (%)': ['water absorption',
  'h20 absorption',
  'water',
  'moisture uptake',
  'moisture absorption',
  'moisture absorption equilibrium 23°c/50% r.h.'],
 'wear by sandslurry method (based on gur 4120=100)': ['wear by sandslurry method']}

In [84]:
all_property_names = []
for i in unique_values['Property']:
    all_property_names.append(i['PROPERTY_NAME_UI'].lower())

all_property_names2 = []
for i in unique_values['Property']:
    all_property_names2.append(i['PROPERTY_NAME'].lower())
    
for i in list(property_syns):
    if i not in all_property_names:
        # print(i)
        if i not in all_property_names2:
            print(i)

shore hardness

In [85]:
property_syn_meaning = sorted(list(property_syns), key=len, reverse=True)

# property name mapped to meaning column in synonym table
prop_mapping = {}
for item in unique_values['Property']:
    match_found = False

    if not match_found:
        for i in property_syn_meaning:
            if item['PROPERTY_NAME'].lower() == i or item['PROPERTY_NAME_UI'].lower() == i:
                match_found = True
                meaning = i
                # print(meaning)
    
            if match_found:
                break
                
    if not match_found:          
        for i in property_syn_meaning:
            if i.startswith(item['PROPERTY_NAME'].lower()):
                match_found = True
                meaning = i
                # print(i, item['PROPERTY_NAME'].lower())
        
            if match_found:
                break
        
    if match_found:
        # print(meaning)
        prop_mapping[item['PROPERTY_NAME'].lower()] = meaning.replace(" -  (-)", "").replace(" (-)", "").replace(" -", "")
    else:
        print("no match for:", item['PROPERTY_NAME'].lower())
        prop_mapping[item['PROPERTY_NAME'].lower()] = item['PROPERTY_NAME_UI'].lower()

prop_mapping

no match for: stress at break
no match for: stress at 10% elongation

{'shore a hardness': 'shore a hardness iso 48-4 / iso 868 15s',
 'electric strength': 'electric strength iec 60243-1 (kv/mm)',
 'intrinsic viscosity': 'intrinsic viscosity iso 307, 1628',
 'vicat softening temperature': 'vicat softening temperature iso 306 50°c/h 10n (°c)',
 'relative permittivity': 'relative permittivity iec 62631-2-1 60hz',
 'tensile strain at failure': 'tensile strain at failure astm d 3039 m tape 0° (%)',
 'wear by sandslurry method (based on gur 4120=100)': 'wear by sandslurry method (based on gur 4120=100)',
 'tensile stress at 100% elongation': 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
 'izod notched impact strength': 'izod notched impact strength',
 'stress at break': 'stress at break iso 527-1/-2 (mpa)',
 'tensile strain at break': 'tensile strain at break iso 527-1/-2 50mm/min (%)',
 'puncture energy': 'puncture energy',
 'tensile creep modulus': 'tensile creep modulus iso 899-1 1000h (mpa)',
 'fiber volume content': 'fiber volume content iso 11667 (%)',
 'izod impact strength': 'izod impact strength',
 'oxygen index': 'oxygen index iso 4589-1/-2 (%)',
 'shore d hardness': 'shore d hardness iso 48-4 / iso 868 15s',
 'effective thermal diffusivity': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'surface resistivity': 'surface resistivity iec 62631-3-2 (ohm)',
 'tensile strain at yield': 'tensile strain at yield iso 527-1/-2 50mm/min (%)',
 'flexural strength': 'flexural strength astm d 790 tape 0° (mpa)',
 'ball indentation hardness': 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'flexural modulus': 'flexural modulus',
 'tensile stress at yield': 'tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
 'tape thickness': 'tape thickness iso 16012 (mm)',
 'density': 'density iso 1183 (kg/m³)',
 'dissipation factor': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'tensile stress at 50% strain': 'tensile stress at 50% strain iso 527-1/-2 (mpa)',
 'tensile stress at 100% strain': 'tensile stress at 100% strain iso 527-1/-2 (mpa)',
 'average molecular weight': "average molecular weight margolies' equation (g/mol)",
 'stress at 10% elongation': 'stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
 'continuous service temperature': 'continuous service temperature iec 60216-1 (°c)',
 'tensile notched impact strength': 'tensile notched impact strength iso 8256/1 23°c (kj/m²)',
 'tensile stress at break': 'tensile stress at break iso 527-1/-2 5mm/min (mpa)',
 'water absorption': 'water absorption sim. to iso 62 2mm (%)',
 'compression set': 'compression set iso 815 23°c, 24h (%)',
 'fiber areal weight': 'fiber areal weight (g/m²)',
 'charpy impact strength': 'charpy impact strength',
 'molding shrinkage': 'molding shrinkage iso 294-4, 2577 parallel (%)',
 'temperature of deflection under load': 'temperature of deflection under load iso 75-1/-2 1.8 mpa (°c)',
 'charpy double notched impact strength': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'melt volume-flow rate': 'melt volume-flow rate iso 1133 (cm³/10min)',
 'elongational stress f': 'elongational stress f iso 21304-2 150/10 (mpa)',
 'thermal conductivity': 'thermal conductivity iso 22007-2 through plane (w/(m k))',
 'hardness, rockwell': 'hardness, rockwell iso 2039-2 m-scale',
 'compressive strength': 'compressive strength iso 604 (mpa)',
 'tensile strength': 'tensile strength astm d 3039 m tape 0° (mpa)',
 'puncture - maximum force': 'puncture maximum force iso 6603-2 23°c (n)',
 'volume resistivity': 'volume resistivity iec 62631-3-1 (ohm.m)',
 'charpy notched impact strength': 'charpy notched impact strength',
 'specific heat capacity of melt': 'specific heat capacity of melt iso 22007-4 (j/(kg k))',
 "poisson's ratio": "poisson's ratio",
 'flexural stress at 3.5%': 'flexural stress at 3.5% iso 178 (mpa)',
 'viscosity number': 'viscosity number iso 307, 1628 (cm³/g)',
 'flexural strain at failure': 'flexural strain at failure astm d 790 tape 0° (%)',
 'glass transition temperature': 'glass transition temperature iso 11357-1/-3 10°c/min (°c)',
 'nominal strain at break': 'nominal strain at break iso 527-1/-2 (%)',
 'tensile modulus': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'average particle size': 'average particle size laser scattering d50 (µm)',
 'ball pressure test': 'ball pressure test iec 60695-10-2 (°c)',
 'compressive modulus': 'compressive modulus iso 604 (mpa)',
 'melt mass-flow rate': 'melt mass-flow rate iso 1133 (g/10min)',
 'elongation at break': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'melting temperature': 'melting temperature iso 11357-1/-3 10°c/min (°c)',
 'tear strength': 'tear strength iso 34-1 normal (kn/m)',
 'coefficient of linear thermal expansion (clte)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'tape areal weight': 'tape areal weight (g/m²)',
 'humidity absorption': 'humidity absorption sim. to iso 62 2mm (%)',
 'bulk density': 'bulk density iso 60 (kg/m³)',
 'tape width': 'tape width iso 16012 (mm)',
 'compressive stress at 1% strain': 'compressive stress at 1% strain iso 604 (mpa)'}

In [86]:
prop_mapping['thermal conductivity'] = 'thermal conductivity'
prop_mapping['coefficient of linear thermal expansion (clte)'] = 'coefficient of linear thermal expansion (clte)'
prop_mapping['tensile strain at break'] = 'tensile strain at break'
prop_mapping['tensile creep modulus'] = 'tensile creep modulus'
prop_mapping['dissipation factor'] = 'dissipation factor'
prop_mapping['tensile stress at break'] = 'tensile stress at break'
prop_mapping['molding shrinkage'] = 'molding shrinkage'
prop_mapping['effective thermal diffusivity'] = 'effective thermal diffusivity'
prop_mapping['temperature of deflection under load'] = 'temperature of deflection under load'
prop_mapping['flexural modulus'] = 'flexural modulus'
prop_mapping['hardness, rockwell'] = 'hardness, rockwell'
prop_mapping['relative permittivity'] = 'relative permittivity'
prop_mapping['vicat softening temperature'] = 'vicat softening temperature'

prop_mapping

{'shore a hardness': 'shore a hardness iso 48-4 / iso 868 15s',
 'electric strength': 'electric strength iec 60243-1 (kv/mm)',
 'intrinsic viscosity': 'intrinsic viscosity iso 307, 1628',
 'vicat softening temperature': 'vicat softening temperature',
 'relative permittivity': 'relative permittivity',
 'tensile strain at failure': 'tensile strain at failure astm d 3039 m tape 0° (%)',
 'wear by sandslurry method (based on gur 4120=100)': 'wear by sandslurry method (based on gur 4120=100)',
 'tensile stress at 100% elongation': 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
 'izod notched impact strength': 'izod notched impact strength',
 'stress at break': 'stress at break iso 527-1/-2 (mpa)',
 'tensile strain at break': 'tensile strain at break',
 'puncture energy': 'puncture energy',
 'tensile creep modulus': 'tensile creep modulus',
 'fiber volume content': 'fiber volume content iso 11667 (%)',
 'izod impact strength': 'izod impact strength',
 'oxygen index': 'oxygen index iso 4589-1/-2 (%)',
 'shore d hardness': 'shore d hardness iso 48-4 / iso 868 15s',
 'effective thermal diffusivity': 'effective thermal diffusivity',
 'surface resistivity': 'surface resistivity iec 62631-3-2 (ohm)',
 'tensile strain at yield': 'tensile strain at yield iso 527-1/-2 50mm/min (%)',
 'flexural strength': 'flexural strength astm d 790 tape 0° (mpa)',
 'ball indentation hardness': 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'flexural modulus': 'flexural modulus',
 'tensile stress at yield': 'tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
 'tape thickness': 'tape thickness iso 16012 (mm)',
 'density': 'density iso 1183 (kg/m³)',
 'dissipation factor': 'dissipation factor',
 'tensile stress at 50% strain': 'tensile stress at 50% strain iso 527-1/-2 (mpa)',
 'tensile stress at 100% strain': 'tensile stress at 100% strain iso 527-1/-2 (mpa)',
 'average molecular weight': "average molecular weight margolies' equation (g/mol)",
 'stress at 10% elongation': 'stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
 'continuous service temperature': 'continuous service temperature iec 60216-1 (°c)',
 'tensile notched impact strength': 'tensile notched impact strength iso 8256/1 23°c (kj/m²)',
 'tensile stress at break': 'tensile stress at break',
 'water absorption': 'water absorption sim. to iso 62 2mm (%)',
 'compression set': 'compression set iso 815 23°c, 24h (%)',
 'fiber areal weight': 'fiber areal weight (g/m²)',
 'charpy impact strength': 'charpy impact strength',
 'molding shrinkage': 'molding shrinkage',
 'temperature of deflection under load': 'temperature of deflection under load',
 'charpy double notched impact strength': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'melt volume-flow rate': 'melt volume-flow rate iso 1133 (cm³/10min)',
 'elongational stress f': 'elongational stress f iso 21304-2 150/10 (mpa)',
 'thermal conductivity': 'thermal conductivity',
 'hardness, rockwell': 'hardness, rockwell',
 'compressive strength': 'compressive strength iso 604 (mpa)',
 'tensile strength': 'tensile strength astm d 3039 m tape 0° (mpa)',
 'puncture - maximum force': 'puncture maximum force iso 6603-2 23°c (n)',
 'volume resistivity': 'volume resistivity iec 62631-3-1 (ohm.m)',
 'charpy notched impact strength': 'charpy notched impact strength',
 'specific heat capacity of melt': 'specific heat capacity of melt iso 22007-4 (j/(kg k))',
 "poisson's ratio": "poisson's ratio",
 'flexural stress at 3.5%': 'flexural stress at 3.5% iso 178 (mpa)',
 'viscosity number': 'viscosity number iso 307, 1628 (cm³/g)',
 'flexural strain at failure': 'flexural strain at failure astm d 790 tape 0° (%)',
 'glass transition temperature': 'glass transition temperature iso 11357-1/-3 10°c/min (°c)',
 'nominal strain at break': 'nominal strain at break iso 527-1/-2 (%)',
 'tensile modulus': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'average particle size': 'average particle size laser scattering d50 (µm)',
 'ball pressure test': 'ball pressure test iec 60695-10-2 (°c)',
 'compressive modulus': 'compressive modulus iso 604 (mpa)',
 'melt mass-flow rate': 'melt mass-flow rate iso 1133 (g/10min)',
 'elongation at break': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'melting temperature': 'melting temperature iso 11357-1/-3 10°c/min (°c)',
 'tear strength': 'tear strength iso 34-1 normal (kn/m)',
 'coefficient of linear thermal expansion (clte)': 'coefficient of linear thermal expansion (clte)',
 'tape areal weight': 'tape areal weight (g/m²)',
 'humidity absorption': 'humidity absorption sim. to iso 62 2mm (%)',
 'bulk density': 'bulk density iso 60 (kg/m³)',
 'tape width': 'tape width iso 16012 (mm)',
 'compressive stress at 1% strain': 'compressive stress at 1% strain iso 604 (mpa)'}

In [87]:
property_and_values =[]
for item in unique_values['Property']:
    if item['UNIT_OF_MEAS_SI']:
        property_and_values.append((prop_mapping[item['PROPERTY_NAME'].lower()], item['Min_Value'], item['Max_Value'], item['UNIT_OF_MEAS_SI'].lower().strip(), item['PROPERTY_NAME'].lower()))
    else: 
        property_and_values.append((prop_mapping[item['PROPERTY_NAME'].lower()], item['Min_Value'], item['Max_Value'], "", item['PROPERTY_NAME'].lower()))

In [88]:
# ('wear by sandslurry method (based on gur 4120=100)', 80, 380, ''), >>>> ???

In [89]:
property_and_values

[('shore a hardness iso 48-4 / iso 868 15s', 91, 91, '', 'shore a hardness'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kv/mm',
  'electric strength'),
 ('intrinsic viscosity iso 307, 1628', 0.63, 3400, '', 'intrinsic viscosity'),
 ('vicat softening temperature', 60, 290, '°c', 'vicat softening temperature'),
 ('relative permittivity', 2.7, 32, '', 'relative permittivity'),
 ('shore a hardness iso 48-4 / iso 868 15s', 28, 98, '', 'shore a hardness'),
 ('tensile strain at failure astm d 3039 m tape 0° (%)',
  1.76,
  3,
  '%',
  'tensile strain at failure'),
 ('wear by sandslurry method (based on gur 4120=100)',
  80,
  380,
  '',
  'wear by sandslurry method (based on gur 4120=100)'),
 ('tensile stress at 100% elongation iso 37 perpendicular (mpa)',
  0.7,
  9.9,
  'mpa',
  'tensile stress at 100% elongation'),
 ('izod notched impact strength',
  2,
  64,
  'kj/m²',
  'izod notched impact strength'),
 ('stress at break iso 527-1/-2 (mpa)', 9, 50, 'mpa', 'stress at break'),
 ('tensile strain at break', 0.35, 50, '%', 'tensile strain at break'),
 ('puncture energy', 13, 43, 'j', 'puncture energy'),
 ('tensile creep modulus', 50, 19600, 'mpa', 'tensile creep modulus'),
 ('fiber volume content iso 11667 (%)', 35, 53, '%', 'fiber volume content'),
 ('izod impact strength', 6, 300, 'kj/m²', 'izod impact strength'),
 ('oxygen index iso 4589-1/-2 (%)', 14.9, 53, '%', 'oxygen index'),
 ('shore d hardness iso 48-4 / iso 868 15s', 21, 85, '', 'shore d hardness'),
 ('effective thermal diffusivity',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('surface resistivity iec 62631-3-2 (ohm)',
  10,
  100000000000000000,
  'ohm',
  'surface resistivity'),
 ('relative permittivity', 2.7, 30, '', 'relative permittivity'),
 ('vicat softening temperature', 47, 270, '°c', 'vicat softening temperature'),
 ('tensile strain at yield iso 527-1/-2 50mm/min (%)',
  2.1,
  40,
  '%',
  'tensile strain at yield'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  29,
  470,
  'mpa',
  'flexural strength'),
 ('izod notched impact strength',
  2,
  96,
  'kj/m²',
  'izod notched impact strength'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'mpa',
  'ball indentation hardness'),
 ('flexural modulus', 26900, 105000, 'mpa', 'flexural modulus'),
 ('tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
  18,
  240,
  'mpa',
  'tensile stress at yield'),
 ('tape thickness iso 16012 (mm)', 0.13, 0.3, 'mm', 'tape thickness'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'density'),
 ('dissipation factor', 4, 654, 'e-4', 'dissipation factor'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  3.2,
  28,
  'mpa',
  'tensile stress at 50% strain'),
 ('tensile stress at 100% strain iso 527-1/-2 (mpa)',
  3,
  26,
  'mpa',
  'tensile stress at 100% strain'),
 ('relative permittivity', 2.3, 2.7, '', 'relative permittivity'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular weight'),
 ('tensile strain at break', 1.5, 370, '%', 'tensile strain at break'),
 ('stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
  3,
  10,
  'mpa',
  'stress at 10% elongation'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°c',
  'continuous service temperature'),
 ('tensile notched impact strength iso 8256/1 23°c (kj/m²)',
  57,
  410,
  'kj/m²',
  'tensile notched impact strength'),
 ('effective thermal diffusivity',
  2.2e-07,
  1.08e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength'),
 ('tensile stress at break', 2.6, 20.7, 'mpa', 'tensile stress at break'),
 ('water absorption sim. to iso 62 2mm (%)',
  0.005,
  12,
  '%',
  'water absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 70, '%', 'compression set'),
 ('flexural modulus', 25, 41000, 'mpa', 'flexural modulus'),
 ('fiber areal weight (g/m²)', 117, 308, 'g/m²', 'fiber areal weight'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact strength'),
 ('molding shrinkage', 0.3, 2.75, '%', 'molding shrinkage'),
 ('temperature of deflection under load',
  46,
  305,
  '°c',
  'temperature of deflection under load'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kj/m²',
  'charpy double notched impact strength'),
 ('melt volume-flow rate iso 1133 (cm³/10min)',
  0.6,
  210,
  'cm³/10min',
  'melt volume-flow rate'),
 ('elongational stress f iso 21304-2 150/10 (mpa)',
  0.01,
  0.68,
  'mpa',
  'elongational stress f'),
 ('dissipation factor', 0, 1500, 'e-4', 'dissipation factor'),
 ('temperature of deflection under load',
  56,
  271,
  '°c',
  'temperature of deflection under load'),
 ('thermal conductivity', 0.21, 34, 'w/(m k)', 'thermal conductivity'),
 ('hardness, rockwell', 95, 125, '', 'hardness, rockwell'),
 ('compressive strength iso 604 (mpa)',
  71,
  293,
  'mpa',
  'compressive strength'),
 ('tensile strength astm d 3039 m tape 0° (mpa)',
  679,
  2030,
  'mpa',
  'tensile strength'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  2100,
  3700,
  'n',
  'puncture - maximum force'),
 ('volume resistivity iec 62631-3-1 (ohm.m)',
  0.001,
  25000000000000000,
  'ohm.m',
  'volume resistivity'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact strength'),
 ('specific heat capacity of melt iso 22007-4 (j/(kg k))',
  1.11,
  2900,
  'j/(kg k)',
  'specific heat capacity of melt'),
 ("poisson's ratio", 0.23, 0.5, '', "poisson's ratio"),
 ('molding shrinkage', 0, 2.75, '%', 'molding shrinkage'),
 ('flexural stress at 3.5% iso 178 (mpa)',
  5.7,
  270,
  'mpa',
  'flexural stress at 3.5%'),
 ('viscosity number iso 307, 1628 (cm³/g)',
  55,
  4200,
  'cm³/g',
  'viscosity number'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.1,
  5.8,
  '%',
  'flexural strain at failure'),
 ('izod impact strength', 9, 300, 'kj/m²', 'izod impact strength'),
 ('charpy impact strength', 2.9, 400, 'kj/m²', 'charpy impact strength'),
 ('glass transition temperature iso 11357-1/-3 10°c/min (°c)',
  -110,
  140,
  '°c',
  'glass transition temperature'),
 ('compression set iso 815 23°c, 24h (%)', 30.3, 76, '%', 'compression set'),
 ('charpy notched impact strength',
  1.9,
  160,
  'kj/m²',
  'charpy notched impact strength'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.08,
  3.32,
  '%',
  'flexural strain at failure'),
 ('nominal strain at break iso 527-1/-2 (%)',
  1.2,
  900,
  '%',
  'nominal strain at break'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  22,
  37300,
  'mpa',
  'tensile modulus'),
 ('tensile stress at break', 10, 180, 'mpa', 'tensile stress at break'),
 ('puncture energy', 3, 85, 'j', 'puncture energy'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°c',
  'ball pressure test'),
 ('izod notched impact strength',
  2,
  115,
  'kj/m²',
  'izod notched impact strength'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'mpa',
  'compressive modulus'),
 ('hardness, rockwell', 39, 119, '', 'hardness, rockwell'),
 ('melt mass-flow rate iso 1133 (g/10min)',
  0.1,
  250,
  'g/10min',
  'melt mass-flow rate'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'elongation at break'),
 ('tensile stress at break', 15.4, 320, 'mpa', 'tensile stress at break'),
 ('charpy notched impact strength',
  0.9,
  130,
  'kj/m²',
  'charpy notched impact strength'),
 ('thermal conductivity', 0.41, 24, 'w/(m k)', 'thermal conductivity'),
 ('effective thermal diffusivity',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'effective thermal diffusivity'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  970,
  5500,
  'n',
  'puncture - maximum force'),
 ('melting temperature iso 11357-1/-3 10°c/min (°c)',
  127,
  355,
  '°c',
  'melting temperature'),
 ('tear strength iso 34-1 normal (kn/m)', 10, 260, 'kn/m', 'tear strength'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25700,
  101000,
  'mpa',
  'tensile modulus'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('tape areal weight (g/m²)', 194, 510, 'g/m²', 'tape areal weight'),
 ('tensile creep modulus', 18, 15800, 'mpa', 'tensile creep modulus'),
 ('humidity absorption sim. to iso 62 2mm (%)',
  0.002,
  4,
  '%',
  'humidity absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 48, '%', 'compression set'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  16,
  49,
  'mpa',
  'tensile stress at 50% strain'),
 ('thermal conductivity', 0.13, 4.5, 'w/(m k)', 'thermal conductivity'),
 ('compression set iso 815 23°c, 24h (%)', 10, 38, '%', 'compression set'),
 ('coefficient of linear thermal expansion (clte)',
  -2.4,
  250,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulk density'),
 ('temperature of deflection under load',
  35,
  340,
  '°c',
  'temperature of deflection under load'),
 ('tape width iso 16012 (mm)', 263, 330, 'mm', 'tape width'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'mpa',
  'compressive stress at 1% strain')]

In [90]:
property_and_values += [
    ('tensile modulus astm d 3039 m tape 0° (mpa)', 25.7, 101, 'gpa', 'tape tens mod'), 
    ('tensile modulus astm d 3039 m tape 0° (mpa)', 25.7, 101, 'gpa', 'tensile mod tape'), 
    ('tensile modulus astm d 3039 m tape 0° (mpa)', 25.7, 101, 'gpa', 'tape tensile modulus'), 
    ('tensile modulus astm d 3039 m tape 0° (mpa)', 25.7, 101, 'gpa', 'tensile modulus tape'), 
    ('tensile modulus astm d 3039 m tape 0° (mpa)', 25.7, 101, 'gpa', 'tensile tape'), 
    
    ('flexural modulus astm d 790 tape 0° (mpa)', 26.9, 105, 'gpa', 'tape flex mod'), 
    ('flexural modulus astm d 790 tape 0° (mpa)', 26.9, 105, 'gpa', 'flex mod tape'), 
    ('flexural modulus astm d 790 tape 0° (mpa)', 26.9, 105, 'gpa', 'tape flexural modulus'), 
    ('flexural modulus astm d 790 tape 0° (mpa)', 26.9, 105, 'gpa', 'flexural modulus tape'), 
    
    ('flexural strength astm d 790 tape 0° (mpa)', 465, 1220, 'mpa', 'tape flex strength'), 
    ('flexural strength astm d 790 tape 0° (mpa)', 465, 1220, 'mpa', 'flex strength tape'), 
    ('flexural strength astm d 790 tape 0° (mpa)', 465, 1220, 'mpa', 'tape flexural strength'), 
    ('flexural strength astm d 790 tape 0° (mpa)', 465, 1220, 'mpa', 'flexural strength tape')]
property_and_values

[('shore a hardness iso 48-4 / iso 868 15s', 91, 91, '', 'shore a hardness'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kv/mm',
  'electric strength'),
 ('intrinsic viscosity iso 307, 1628', 0.63, 3400, '', 'intrinsic viscosity'),
 ('vicat softening temperature', 60, 290, '°c', 'vicat softening temperature'),
 ('relative permittivity', 2.7, 32, '', 'relative permittivity'),
 ('shore a hardness iso 48-4 / iso 868 15s', 28, 98, '', 'shore a hardness'),
 ('tensile strain at failure astm d 3039 m tape 0° (%)',
  1.76,
  3,
  '%',
  'tensile strain at failure'),
 ('wear by sandslurry method (based on gur 4120=100)',
  80,
  380,
  '',
  'wear by sandslurry method (based on gur 4120=100)'),
 ('tensile stress at 100% elongation iso 37 perpendicular (mpa)',
  0.7,
  9.9,
  'mpa',
  'tensile stress at 100% elongation'),
 ('izod notched impact strength',
  2,
  64,
  'kj/m²',
  'izod notched impact strength'),
 ('stress at break iso 527-1/-2 (mpa)', 9, 50, 'mpa', 'stress at break'),
 ('tensile strain at break', 0.35, 50, '%', 'tensile strain at break'),
 ('puncture energy', 13, 43, 'j', 'puncture energy'),
 ('tensile creep modulus', 50, 19600, 'mpa', 'tensile creep modulus'),
 ('fiber volume content iso 11667 (%)', 35, 53, '%', 'fiber volume content'),
 ('izod impact strength', 6, 300, 'kj/m²', 'izod impact strength'),
 ('oxygen index iso 4589-1/-2 (%)', 14.9, 53, '%', 'oxygen index'),
 ('shore d hardness iso 48-4 / iso 868 15s', 21, 85, '', 'shore d hardness'),
 ('effective thermal diffusivity',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('surface resistivity iec 62631-3-2 (ohm)',
  10,
  100000000000000000,
  'ohm',
  'surface resistivity'),
 ('relative permittivity', 2.7, 30, '', 'relative permittivity'),
 ('vicat softening temperature', 47, 270, '°c', 'vicat softening temperature'),
 ('tensile strain at yield iso 527-1/-2 50mm/min (%)',
  2.1,
  40,
  '%',
  'tensile strain at yield'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  29,
  470,
  'mpa',
  'flexural strength'),
 ('izod notched impact strength',
  2,
  96,
  'kj/m²',
  'izod notched impact strength'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'mpa',
  'ball indentation hardness'),
 ('flexural modulus', 26900, 105000, 'mpa', 'flexural modulus'),
 ('tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
  18,
  240,
  'mpa',
  'tensile stress at yield'),
 ('tape thickness iso 16012 (mm)', 0.13, 0.3, 'mm', 'tape thickness'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'density'),
 ('dissipation factor', 4, 654, 'e-4', 'dissipation factor'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  3.2,
  28,
  'mpa',
  'tensile stress at 50% strain'),
 ('tensile stress at 100% strain iso 527-1/-2 (mpa)',
  3,
  26,
  'mpa',
  'tensile stress at 100% strain'),
 ('relative permittivity', 2.3, 2.7, '', 'relative permittivity'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular weight'),
 ('tensile strain at break', 1.5, 370, '%', 'tensile strain at break'),
 ('stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
  3,
  10,
  'mpa',
  'stress at 10% elongation'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°c',
  'continuous service temperature'),
 ('tensile notched impact strength iso 8256/1 23°c (kj/m²)',
  57,
  410,
  'kj/m²',
  'tensile notched impact strength'),
 ('effective thermal diffusivity',
  2.2e-07,
  1.08e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength'),
 ('tensile stress at break', 2.6, 20.7, 'mpa', 'tensile stress at break'),
 ('water absorption sim. to iso 62 2mm (%)',
  0.005,
  12,
  '%',
  'water absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 70, '%', 'compression set'),
 ('flexural modulus', 25, 41000, 'mpa', 'flexural modulus'),
 ('fiber areal weight (g/m²)', 117, 308, 'g/m²', 'fiber areal weight'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact strength'),
 ('molding shrinkage', 0.3, 2.75, '%', 'molding shrinkage'),
 ('temperature of deflection under load',
  46,
  305,
  '°c',
  'temperature of deflection under load'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kj/m²',
  'charpy double notched impact strength'),
 ('melt volume-flow rate iso 1133 (cm³/10min)',
  0.6,
  210,
  'cm³/10min',
  'melt volume-flow rate'),
 ('elongational stress f iso 21304-2 150/10 (mpa)',
  0.01,
  0.68,
  'mpa',
  'elongational stress f'),
 ('dissipation factor', 0, 1500, 'e-4', 'dissipation factor'),
 ('temperature of deflection under load',
  56,
  271,
  '°c',
  'temperature of deflection under load'),
 ('thermal conductivity', 0.21, 34, 'w/(m k)', 'thermal conductivity'),
 ('hardness, rockwell', 95, 125, '', 'hardness, rockwell'),
 ('compressive strength iso 604 (mpa)',
  71,
  293,
  'mpa',
  'compressive strength'),
 ('tensile strength astm d 3039 m tape 0° (mpa)',
  679,
  2030,
  'mpa',
  'tensile strength'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  2100,
  3700,
  'n',
  'puncture - maximum force'),
 ('volume resistivity iec 62631-3-1 (ohm.m)',
  0.001,
  25000000000000000,
  'ohm.m',
  'volume resistivity'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact strength'),
 ('specific heat capacity of melt iso 22007-4 (j/(kg k))',
  1.11,
  2900,
  'j/(kg k)',
  'specific heat capacity of melt'),
 ("poisson's ratio", 0.23, 0.5, '', "poisson's ratio"),
 ('molding shrinkage', 0, 2.75, '%', 'molding shrinkage'),
 ('flexural stress at 3.5% iso 178 (mpa)',
  5.7,
  270,
  'mpa',
  'flexural stress at 3.5%'),
 ('viscosity number iso 307, 1628 (cm³/g)',
  55,
  4200,
  'cm³/g',
  'viscosity number'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.1,
  5.8,
  '%',
  'flexural strain at failure'),
 ('izod impact strength', 9, 300, 'kj/m²', 'izod impact strength'),
 ('charpy impact strength', 2.9, 400, 'kj/m²', 'charpy impact strength'),
 ('glass transition temperature iso 11357-1/-3 10°c/min (°c)',
  -110,
  140,
  '°c',
  'glass transition temperature'),
 ('compression set iso 815 23°c, 24h (%)', 30.3, 76, '%', 'compression set'),
 ('charpy notched impact strength',
  1.9,
  160,
  'kj/m²',
  'charpy notched impact strength'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.08,
  3.32,
  '%',
  'flexural strain at failure'),
 ('nominal strain at break iso 527-1/-2 (%)',
  1.2,
  900,
  '%',
  'nominal strain at break'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  22,
  37300,
  'mpa',
  'tensile modulus'),
 ('tensile stress at break', 10, 180, 'mpa', 'tensile stress at break'),
 ('puncture energy', 3, 85, 'j', 'puncture energy'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°c',
  'ball pressure test'),
 ('izod notched impact strength',
  2,
  115,
  'kj/m²',
  'izod notched impact strength'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'mpa',
  'compressive modulus'),
 ('hardness, rockwell', 39, 119, '', 'hardness, rockwell'),
 ('melt mass-flow rate iso 1133 (g/10min)',
  0.1,
  250,
  'g/10min',
  'melt mass-flow rate'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'elongation at break'),
 ('tensile stress at break', 15.4, 320, 'mpa', 'tensile stress at break'),
 ('charpy notched impact strength',
  0.9,
  130,
  'kj/m²',
  'charpy notched impact strength'),
 ('thermal conductivity', 0.41, 24, 'w/(m k)', 'thermal conductivity'),
 ('effective thermal diffusivity',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'effective thermal diffusivity'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  970,
  5500,
  'n',
  'puncture - maximum force'),
 ('melting temperature iso 11357-1/-3 10°c/min (°c)',
  127,
  355,
  '°c',
  'melting temperature'),
 ('tear strength iso 34-1 normal (kn/m)', 10, 260, 'kn/m', 'tear strength'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25700,
  101000,
  'mpa',
  'tensile modulus'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('tape areal weight (g/m²)', 194, 510, 'g/m²', 'tape areal weight'),
 ('tensile creep modulus', 18, 15800, 'mpa', 'tensile creep modulus'),
 ('humidity absorption sim. to iso 62 2mm (%)',
  0.002,
  4,
  '%',
  'humidity absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 48, '%', 'compression set'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  16,
  49,
  'mpa',
  'tensile stress at 50% strain'),
 ('thermal conductivity', 0.13, 4.5, 'w/(m k)', 'thermal conductivity'),
 ('compression set iso 815 23°c, 24h (%)', 10, 38, '%', 'compression set'),
 ('coefficient of linear thermal expansion (clte)',
  -2.4,
  250,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulk density'),
 ('temperature of deflection under load',
  35,
  340,
  '°c',
  'temperature of deflection under load'),
 ('tape width iso 16012 (mm)', 263, 330, 'mm', 'tape width'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'mpa',
  'compressive stress at 1% strain'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tens mod'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile mod tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tensile modulus'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile modulus tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flex mod'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flex mod tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flexural modulus'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flexural modulus tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flex strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flex strength tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flexural strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength tape')]

In [91]:
RANGE_MODIFIERS = [
    
    # 'excellent', 'superior', 'exceptional', 'best', 'outstanding', 'very good', 'maximum', 'very high', 'great', 'high', 'highest', 'higher', 
    # 'less', 'least', 'weak', 'lower', 'lowest', 'inferior', 'limited', 'low', 'typical', 
    # 'good', 'fair', 'medium', 'moderate', 'normal', 'ordinary', 'average', 'standard'

    'high', 'highest', 'excellent', 'strong',
    'lowest', 'low', 'weak',
    'medium', 'moderate', 'average', 'standard', 'good',
]
RANGE_MODIFIERS

['high',
 'highest',
 'excellent',
 'strong',
 'lowest',
 'low',
 'weak',
 'medium',
 'moderate',
 'average',
 'standard',
 'good']

In [92]:
set(synonym_df2['TYPE'])

{'auto cert',
 'brand',
 'delivery form',
 'feature',
 'filler',
 'others',
 'polymer',
 'processing',
 'property',
 'ul property'}

In [93]:
list(property_syns)

["average molecular weight margolies' equation (g/mol)",
 'average particle size laser scattering d50 (µm)',
 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'ball pressure test iec 60695-10-2 (°c)',
 'bulk density iso 60 (kg/m³)',
 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy impact strength',
 'charpy notched impact strength',
 'coefficient of linear thermal expansion (clte)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'compression set',
 'compression set iso 815 23°c (%)',
 'compression set iso 815 23°c, 24h (%)',
 'compressive modulus iso 604 (mpa)',
 'compressive strength iso 604 (mpa)',
 'compressive stress at 1% strain iso 604 (mpa)',
 'continuous service temperature iec 60216-1 (°c)',
 'density iso 1183 (kg/m³)',
 'dissipation factor',
 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'effective thermal diffusivity',
 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)',
 'effective thermal diffusivity iso 22007-4 flow (m²/s)',
 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'electric strength iec 60243-1 (kv/mm)',
 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'elongational stress f iso 21304-2 150/10 (mpa)',
 'fiber areal weight (g/m²)',
 'fiber volume content iso 11667 (%)',
 'flexural modulus',
 'flexural modulus astm d 790 tape 0° (mpa)',
 'flexural strain at failure',
 'flexural strain at failure astm d 790 tape 0° (%)',
 'flexural strength',
 'flexural strength astm d 790 tape 0° (mpa)',
 'flexural stress at 3.5% iso 178 (mpa)',
 'glass transition temperature iso 11357-1/-3 10°c/min (°c)',
 'hardness, rockwell',
 'hardness, rockwell iso 2039-2 m-scale',
 'hardness, rockwell iso 2039-2 r-scale',
 'humidity absorption sim. to iso 62 2mm (%)',
 'intrinsic viscosity iso 307, 1628',
 'izod impact strength',
 'izod notched impact strength',
 'melt mass-flow rate iso 1133 (g/10min)',
 'melt volume-flow rate iso 1133 (cm³/10min)',
 'melting temperature iso 11357-1/-3 10°c/min (°c)',
 'molding shrinkage',
 'molding shrinkage iso 294-4, 2577 normal (%)',
 'molding shrinkage iso 294-4, 2577 parallel (%)',
 'nominal strain at break iso 527-1/-2 (%)',
 'oxygen index iso 4589-1/-2 (%)',
 "poisson's ratio",
 'puncture - maximum force iso 6603-2 23°c (n)',
 'puncture energy',
 'relative permittivity',
 'relative permittivity iec 62631-2-1 100hz',
 'relative permittivity iec 62631-2-1 1mhz',
 'relative permittivity iec 62631-2-1 60hz',
 'shore a hardness iso 48-4 / iso 868 15s',
 'shore d hardness iso 48-4 / iso 868 15s',
 'shore hardness',
 'specific heat capacity of melt iso 22007-4 (j/(kg k))',
 'surface resistivity iec 62631-3-2 (ohm)',
 'tape areal weight (g/m²)',
 'tape thickness iso 16012 (mm)',
 'tape width iso 16012 (mm)',
 'tear strength iso 34-1 normal (kn/m)',
 'temperature of deflection under load',
 'temperature of deflection under load iso 75-1/-2 0.45 mpa (°c)',
 'temperature of deflection under load iso 75-1/-2 1.8 mpa (°c)',
 'temperature of deflection under load iso 75-1/-2 8 mpa (°c)',
 'tensile creep modulus',
 'tensile creep modulus iso 899-1 1000h (mpa)',
 'tensile creep modulus iso 899-1 1h (mpa)',
 'tensile modulus',
 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tensile notched impact strength iso 8256/1 23°c (kj/m²)',
 'tensile strain at break',
 'tensile strain at break iso 527-1/-2 50mm/min (%)',
 'tensile strain at break iso 527-1/-2 5mm/min (%)',
 'tensile strain at failure astm d 3039 m tape 0° (%)',
 'tensile strain at yield iso 527-1/-2 50mm/min (%)',
 'tensile strength astm d 3039 m tape 0° (mpa)',
 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
 'tensile stress at 100% strain iso 527-1/-2 (mpa)',
 'tensile stress at 50% strain iso 527-1/-2 (mpa)',
 'tensile stress at break',
 'tensile stress at break iso 527-1/-2 50mm/min (mpa)',
 'tensile stress at break iso 527-1/-2 5mm/min (mpa)',
 'tensile stress at break iso 527-1/-2 or iso 37 perpendicular (mpa)',
 'tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
 'thermal conductivity',
 'thermal conductivity iso 22007-2 crossflow (w/(m k))',
 'thermal conductivity iso 22007-2 flow (w/(m k))',
 'thermal conductivity iso 22007-2 through plane (w/(m k))',
 'vicat softening temperature',
 'vicat softening temperature iso 306 50°c/h 10n (°c)',
 'vicat softening temperature iso 306 50°c/h 50n (°c)',
 'viscosity number iso 307, 1628 (cm³/g)',
 'volume resistivity iec 62631-3-1 (ohm.m)',
 'water absorption sim. to iso 62 2mm (%)',
 'wear by sandslurry method (based on gur 4120=100)']

In [94]:
syn_property_and_values = []
for i in list(property_syns):       
    matched = False
    for j in unique_values['Property']:
        if i==j['PROPERTY_NAME_UI'].lower() and not matched:
            matched = True
            # print(1, i, " | ", j['PROPERTY_NAME_UI'])
            # print(1, (j['PROPERTY_NAME_UI'].lower(), j['Min_Value'], j['Max_Value'], j['UNIT_OF_MEAS_SI'], j['PROPERTY_NAME_UI'].lower()))
            if j['UNIT_OF_MEAS_SI']:
                syn_property_and_values.append((j['PROPERTY_NAME_UI'].lower(), j['Min_Value'], j['Max_Value'], j['UNIT_OF_MEAS_SI'], j['PROPERTY_NAME_UI'].lower()))
            else:
                syn_property_and_values.append((j['PROPERTY_NAME_UI'].lower(), j['Min_Value'], j['Max_Value'], "", j['PROPERTY_NAME_UI'].lower()))
            
            for p_syn in property_syns[i]:
                if p_syn:
                    if j['UNIT_OF_MEAS_SI']:
                        syn_property_and_values.append((j['PROPERTY_NAME_UI'].lower(), j['Min_Value'], j['Max_Value'], j['UNIT_OF_MEAS_SI'], p_syn))
                    else:
                        syn_property_and_values.append((j['PROPERTY_NAME_UI'].lower(), j['Min_Value'], j['Max_Value'], "", p_syn))

            break
            

    if matched:
        # print(i)
        pass
    else:
        # print(i)
        matched_prop = process.extract(i, all_property_names2)[0][0]
        matched2 = False
        for j in property_and_values:
            if matched_prop==j[0] and not matched2:
                matched2 = True
                # print(2, i, " | ", j[0])
                # print(2, (i, j[1], j[2], j[3], i))
                syn_property_and_values.append((i, j[1], j[2], j[3], i))               
                for p_syn in property_syns[i]:
                    if p_syn:
                        # print((i, j[1], j[2], j[3], p_syn))
                        syn_property_and_values.append((i, j[1], j[2], j[3], p_syn))

                break

        if not matched2:
            matched_prop = process.extract(i, all_property_names2)[0][0]
            for j in property_and_values:
                if matched_prop in j[0] and not matched2:
                    matched2 = True
                    # print(3, i, " | ", j[0])
                    # print(2, (i, j[1], j[2], j[3], i))
                    syn_property_and_values.append((i, j[1], j[2], j[3], i))               
                    for p_syn in property_syns[i]:
                        if p_syn:
                            # print((i, j[1], j[2], j[3], p_syn))
                            syn_property_and_values.append((i, j[1], j[2], j[3], p_syn))
    
                    break
        
        if not matched2:
            print(i)
            pass
            
syn_property_and_values

[("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  "average molecular weight margolies' equation (g/mol)"),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular weight'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molar mass'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular mass'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'avermw'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'molecular weight'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'mw'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size laser scattering d50 (µm)'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size laser scattering d50 (µm)'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'avg. particle size'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'avpartsize'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'particle size'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'particle size d50'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indentation hardness iso 2039-1 h 358/30 (mpa)'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indentation hardness'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indention hardness'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°C',
  'ball pressure test iec 60695-10-2 (°c)'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°C',
  'ball pressure test'),
 ('bulk density iso 60 (kg/m³)',
  220,
  1100,
  'kg/m³',
  'bulk density iso 60 (kg/m³)'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulk density'),
 ('bulk density iso 60 (kg/m³)',
  220,
  1100,
  'kg/m³',
  'apparent (bulk) density'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'apparent density'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulkdens'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched impact strength iso 21304-2 23°c (kj/m²)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy impact strength (double notched)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy impact strength (double notch)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch charpy impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched charpy impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch charpy'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched charpy'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch impact'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched impact'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notch'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact strength'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact strength'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'impact charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotch'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotched charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotch charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotched impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotch impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotched charpy impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotch charpy impact'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength unnotched'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength unnotch'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength (unnotched)'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength (unnotch)'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact unnotched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact unnotch'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact (unnotched)'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact (unnotch)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact strength'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact strength'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notched'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notch'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notched charpy'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notch charpy'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notch impact'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'notched charpy impact'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notch charpy impact'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength notched'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength notch'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength (notched)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength (notch)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact notched'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy impact notch'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact (notched)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact (notch)'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte)', 6, 329, 'e-6/k', 'clte'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'linear expansion factor'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'thermal expansion'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coef. of lin. therm expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'linear expansion factor (normal)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'normal thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'normal linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'coef. of lin. therm expansion normal'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'clte (transverse direction)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'linear expansion factor (parallel)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'parallel thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'parallel linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'coef. of lin. therm expansion parallel'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'clte (flow direction)'),
 ('compression set', 18, 70, '%', 'compression set'),
 ('compression set', 18, 70, '%', 'compression set'),
 ('compression set iso 815 23°c (%)',
  18,
  48,
  '%',
  'compression set iso 815 23°c (%)'),
 ('compression set iso 815 23°c (%)', 18, 48, '%', 'compression set at 23c'),
 ('compression set iso 815 23°c, 24h (%)',
  10,
  38,
  '%',
  'compression set iso 815 23°c, 24h (%)'),
 ('compression set iso 815 23°c, 24h (%)',
  10,
  38,
  '%',
  'compression set at 23c, 24h'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'MPa',
  'compressive modulus iso 604 (mpa)'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'MPa',
  'compressive modulus'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'MPa',
  'compressive module'),
 ('compressive modulus iso 604 (mpa)', 2000, 33000, 'MPa', 'comp mod'),
 ('compressive strength iso 604 (mpa)',
  71,
  293,
  'MPa',
  'compressive strength iso 604 (mpa)'),
 ('compressive strength iso 604 (mpa)',
  71,
  293,
  'MPa',
  'compressive strength'),
 ('compressive strength iso 604 (mpa)', 71, 293, 'MPa', 'compressive stress'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'MPa',
  'compressive stress at 1% strain iso 604 (mpa)'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'MPa',
  'compressive stress at 1% strain'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'MPa',
  'compressive strength at 1% strain'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'MPa',
  'compressive stress 1% deformation'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'MPa',
  'compressive strength at 1% deformation'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'continuous service temperature iec 60216-1 (°c)'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'continuous service temperature'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'continuous use temperature'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'continuous allowable service temperature in air'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'max service temperature'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'min service temperature'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'service temperature long term'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'service temperature short term'),
 ('continuous service temperature iec 60216-1 (°c)', 85, 140, '°C', 'cut'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'temperature resistance'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'minimum operating temperature'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°C',
  'continuous utilization temperature'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'density iso 1183 (kg/m³)'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'density'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'dense'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'heavy'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'heavy weight'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'specific gravity'),
 ('dissipation factor', 4, 654, 'e-4', 'dissipation factor'),
 ('dissipation factor', 4, 654, 'e-4', 'dissipation factor'),
 ('dissipation factor', 4, 654, 'e-4', 'tangent delta'),
 ('dissipation factor', 4, 654, 'e-4', 'tan delta'),
 ('dissipation factor', 4, 654, 'e-4', 'df'),
 ('dissipation factor', 4, 654, 'e-4', 'dielectric dissipation factor'),
 ('dissipation factor', 4, 654, 'e-4', 'dielectric dissipation'),
 ('dissipation factor', 4, 654, 'e-4', 'loss angle'),
 ('dissipation factor', 4, 654, 'e-4', 'loss tangent'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'dissipation factor iec 62631-2-1 100hz (e-4)'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'dissipation factor 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'tangent delta at 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'tangent delta, 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'tan delta 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'tan delta at 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)', 4, 654, 'E-4', 'df 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)', 4, 654, 'E-4', '100hz df'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'dielectric dissipation factor at 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'dielectric dissipation factor, 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'dielectric dissipation 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'dielectric dissipation at 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'loss angle at 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'loss angle 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'loss tangent 100hz'),
 ('dissipation factor iec 62631-2-1 100hz (e-4)',
  4,
  654,
  'E-4',
  'loss tangent at 100hz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'dissipation factor iec 62631-2-1 1mhz (e-4)'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'dissipation factor 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'tangent delta at 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'tangent delta, 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'tan delta 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'tan delta at 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)', 0, 1500, 'E-4', 'df 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)', 0, 1500, 'E-4', '1mhz df'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'dielectric dissipation factor at 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'dielectric dissipation factor, 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'dielectric dissipation 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'dielectric dissipation at 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'loss angle at 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'loss angle 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'loss tangent 1mhz'),
 ('dissipation factor iec 62631-2-1 1mhz (e-4)',
  0,
  1500,
  'E-4',
  'loss tangent at 1mhz'),
 ('effective thermal diffusivity',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('effective thermal diffusivity',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('effective thermal diffusivity iso 22007-4 crossflow (m²/s)',
  2.2e-07,
  1.08e-06,
  'm²/s',
  'effective thermal diffusivity iso 22007-4 crossflow (m²/s)'),
 ('effective thermal diffusivity iso 22007-4 crossflow (m²/s)',
  2.2e-07,
  1.08e-06,
  'm²/s',
  'effective thermal diffusivity, crossflow direction'),
 ('effective thermal diffusivity iso 22007-4 flow (m²/s)',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusivity iso 22007-4 flow (m²/s)'),
 ('effective thermal diffusivity iso 22007-4 flow (m²/s)',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusity, flow direction'),
 ('effective thermal diffusivity iso 22007-4 flow (m²/s)',
  2e-11,
  1.79e-06,
  'm²/s',
  'in plane thermal diffusivity'),
 ('effective thermal diffusivity iso 22007-4 through plane (m²/s)',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'effective thermal diffusivity iso 22007-4 through plane (m²/s)'),
 ('effective thermal diffusivity iso 22007-4 through plane (m²/s)',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'effective thermal diffusivity, through plane direction'),
 ('effective thermal diffusivity iso 22007-4 through plane (m²/s)',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'through plane thermal diffusivity'),
 ('effective thermal diffusivity iso 22007-4 through plane (m²/s)',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'cross plane thermal diffusivity'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kV/mm',
  'electric strength iec 60243-1 (kv/mm)'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kV/mm',
  'electric strength'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kV/mm',
  'ac electristrength'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kV/mm',
  'ac dielectric strength'),
 ('electric strength iec 60243-1 (kv/mm)', 2.4, 59, 'kV/mm', 'ac'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'elongation at break, perpendicular'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'perpendicular elongation at break'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'perpendicular break strain'),
 ('elongational stress f iso 21304-2 150/10 (mpa)',
  0.01,
  0.68,
  'MPa',
  'elongational stress f iso 21304-2 150/10 (mpa)'),
 ('elongational stress f iso 21304-2 150/10 (mpa)',
  0.01,
  0.68,
  'MPa',
  'elongational stress f'),
 ('fiber areal weight (g/m²)', 117, 308, 'g/m²', 'fiber areal weight (g/m²)'),
 ('fiber areal weight (g/m²)', 117, 308, 'g/m²', 'fiber areal weight'),
 ('fiber volume content iso 11667 (%)',
  35,
  53,
  '%',
  'fiber volume content iso 11667 (%)'),

In [95]:
property_and_values

[('shore a hardness iso 48-4 / iso 868 15s', 91, 91, '', 'shore a hardness'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kv/mm',
  'electric strength'),
 ('intrinsic viscosity iso 307, 1628', 0.63, 3400, '', 'intrinsic viscosity'),
 ('vicat softening temperature', 60, 290, '°c', 'vicat softening temperature'),
 ('relative permittivity', 2.7, 32, '', 'relative permittivity'),
 ('shore a hardness iso 48-4 / iso 868 15s', 28, 98, '', 'shore a hardness'),
 ('tensile strain at failure astm d 3039 m tape 0° (%)',
  1.76,
  3,
  '%',
  'tensile strain at failure'),
 ('wear by sandslurry method (based on gur 4120=100)',
  80,
  380,
  '',
  'wear by sandslurry method (based on gur 4120=100)'),
 ('tensile stress at 100% elongation iso 37 perpendicular (mpa)',
  0.7,
  9.9,
  'mpa',
  'tensile stress at 100% elongation'),
 ('izod notched impact strength',
  2,
  64,
  'kj/m²',
  'izod notched impact strength'),
 ('stress at break iso 527-1/-2 (mpa)', 9, 50, 'mpa', 'stress at break'),
 ('tensile strain at break', 0.35, 50, '%', 'tensile strain at break'),
 ('puncture energy', 13, 43, 'j', 'puncture energy'),
 ('tensile creep modulus', 50, 19600, 'mpa', 'tensile creep modulus'),
 ('fiber volume content iso 11667 (%)', 35, 53, '%', 'fiber volume content'),
 ('izod impact strength', 6, 300, 'kj/m²', 'izod impact strength'),
 ('oxygen index iso 4589-1/-2 (%)', 14.9, 53, '%', 'oxygen index'),
 ('shore d hardness iso 48-4 / iso 868 15s', 21, 85, '', 'shore d hardness'),
 ('effective thermal diffusivity',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('surface resistivity iec 62631-3-2 (ohm)',
  10,
  100000000000000000,
  'ohm',
  'surface resistivity'),
 ('relative permittivity', 2.7, 30, '', 'relative permittivity'),
 ('vicat softening temperature', 47, 270, '°c', 'vicat softening temperature'),
 ('tensile strain at yield iso 527-1/-2 50mm/min (%)',
  2.1,
  40,
  '%',
  'tensile strain at yield'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  29,
  470,
  'mpa',
  'flexural strength'),
 ('izod notched impact strength',
  2,
  96,
  'kj/m²',
  'izod notched impact strength'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'mpa',
  'ball indentation hardness'),
 ('flexural modulus', 26900, 105000, 'mpa', 'flexural modulus'),
 ('tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
  18,
  240,
  'mpa',
  'tensile stress at yield'),
 ('tape thickness iso 16012 (mm)', 0.13, 0.3, 'mm', 'tape thickness'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'density'),
 ('dissipation factor', 4, 654, 'e-4', 'dissipation factor'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  3.2,
  28,
  'mpa',
  'tensile stress at 50% strain'),
 ('tensile stress at 100% strain iso 527-1/-2 (mpa)',
  3,
  26,
  'mpa',
  'tensile stress at 100% strain'),
 ('relative permittivity', 2.3, 2.7, '', 'relative permittivity'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular weight'),
 ('tensile strain at break', 1.5, 370, '%', 'tensile strain at break'),
 ('stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
  3,
  10,
  'mpa',
  'stress at 10% elongation'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°c',
  'continuous service temperature'),
 ('tensile notched impact strength iso 8256/1 23°c (kj/m²)',
  57,
  410,
  'kj/m²',
  'tensile notched impact strength'),
 ('effective thermal diffusivity',
  2.2e-07,
  1.08e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength'),
 ('tensile stress at break', 2.6, 20.7, 'mpa', 'tensile stress at break'),
 ('water absorption sim. to iso 62 2mm (%)',
  0.005,
  12,
  '%',
  'water absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 70, '%', 'compression set'),
 ('flexural modulus', 25, 41000, 'mpa', 'flexural modulus'),
 ('fiber areal weight (g/m²)', 117, 308, 'g/m²', 'fiber areal weight'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact strength'),
 ('molding shrinkage', 0.3, 2.75, '%', 'molding shrinkage'),
 ('temperature of deflection under load',
  46,
  305,
  '°c',
  'temperature of deflection under load'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kj/m²',
  'charpy double notched impact strength'),
 ('melt volume-flow rate iso 1133 (cm³/10min)',
  0.6,
  210,
  'cm³/10min',
  'melt volume-flow rate'),
 ('elongational stress f iso 21304-2 150/10 (mpa)',
  0.01,
  0.68,
  'mpa',
  'elongational stress f'),
 ('dissipation factor', 0, 1500, 'e-4', 'dissipation factor'),
 ('temperature of deflection under load',
  56,
  271,
  '°c',
  'temperature of deflection under load'),
 ('thermal conductivity', 0.21, 34, 'w/(m k)', 'thermal conductivity'),
 ('hardness, rockwell', 95, 125, '', 'hardness, rockwell'),
 ('compressive strength iso 604 (mpa)',
  71,
  293,
  'mpa',
  'compressive strength'),
 ('tensile strength astm d 3039 m tape 0° (mpa)',
  679,
  2030,
  'mpa',
  'tensile strength'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  2100,
  3700,
  'n',
  'puncture - maximum force'),
 ('volume resistivity iec 62631-3-1 (ohm.m)',
  0.001,
  25000000000000000,
  'ohm.m',
  'volume resistivity'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact strength'),
 ('specific heat capacity of melt iso 22007-4 (j/(kg k))',
  1.11,
  2900,
  'j/(kg k)',
  'specific heat capacity of melt'),
 ("poisson's ratio", 0.23, 0.5, '', "poisson's ratio"),
 ('molding shrinkage', 0, 2.75, '%', 'molding shrinkage'),
 ('flexural stress at 3.5% iso 178 (mpa)',
  5.7,
  270,
  'mpa',
  'flexural stress at 3.5%'),
 ('viscosity number iso 307, 1628 (cm³/g)',
  55,
  4200,
  'cm³/g',
  'viscosity number'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.1,
  5.8,
  '%',
  'flexural strain at failure'),
 ('izod impact strength', 9, 300, 'kj/m²', 'izod impact strength'),
 ('charpy impact strength', 2.9, 400, 'kj/m²', 'charpy impact strength'),
 ('glass transition temperature iso 11357-1/-3 10°c/min (°c)',
  -110,
  140,
  '°c',
  'glass transition temperature'),
 ('compression set iso 815 23°c, 24h (%)', 30.3, 76, '%', 'compression set'),
 ('charpy notched impact strength',
  1.9,
  160,
  'kj/m²',
  'charpy notched impact strength'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.08,
  3.32,
  '%',
  'flexural strain at failure'),
 ('nominal strain at break iso 527-1/-2 (%)',
  1.2,
  900,
  '%',
  'nominal strain at break'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  22,
  37300,
  'mpa',
  'tensile modulus'),
 ('tensile stress at break', 10, 180, 'mpa', 'tensile stress at break'),
 ('puncture energy', 3, 85, 'j', 'puncture energy'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°c',
  'ball pressure test'),
 ('izod notched impact strength',
  2,
  115,
  'kj/m²',
  'izod notched impact strength'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'mpa',
  'compressive modulus'),
 ('hardness, rockwell', 39, 119, '', 'hardness, rockwell'),
 ('melt mass-flow rate iso 1133 (g/10min)',
  0.1,
  250,
  'g/10min',
  'melt mass-flow rate'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'elongation at break'),
 ('tensile stress at break', 15.4, 320, 'mpa', 'tensile stress at break'),
 ('charpy notched impact strength',
  0.9,
  130,
  'kj/m²',
  'charpy notched impact strength'),
 ('thermal conductivity', 0.41, 24, 'w/(m k)', 'thermal conductivity'),
 ('effective thermal diffusivity',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'effective thermal diffusivity'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  970,
  5500,
  'n',
  'puncture - maximum force'),
 ('melting temperature iso 11357-1/-3 10°c/min (°c)',
  127,
  355,
  '°c',
  'melting temperature'),
 ('tear strength iso 34-1 normal (kn/m)', 10, 260, 'kn/m', 'tear strength'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25700,
  101000,
  'mpa',
  'tensile modulus'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('tape areal weight (g/m²)', 194, 510, 'g/m²', 'tape areal weight'),
 ('tensile creep modulus', 18, 15800, 'mpa', 'tensile creep modulus'),
 ('humidity absorption sim. to iso 62 2mm (%)',
  0.002,
  4,
  '%',
  'humidity absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 48, '%', 'compression set'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  16,
  49,
  'mpa',
  'tensile stress at 50% strain'),
 ('thermal conductivity', 0.13, 4.5, 'w/(m k)', 'thermal conductivity'),
 ('compression set iso 815 23°c, 24h (%)', 10, 38, '%', 'compression set'),
 ('coefficient of linear thermal expansion (clte)',
  -2.4,
  250,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulk density'),
 ('temperature of deflection under load',
  35,
  340,
  '°c',
  'temperature of deflection under load'),
 ('tape width iso 16012 (mm)', 263, 330, 'mm', 'tape width'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'mpa',
  'compressive stress at 1% strain'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tens mod'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile mod tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tensile modulus'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile modulus tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flex mod'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flex mod tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flexural modulus'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flexural modulus tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flex strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flex strength tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flexural strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength tape')]

In [96]:
print(len(property_and_values))
for i in syn_property_and_values:
    if i not in property_and_values:
        property_and_values.append(i)

print(len(property_and_values))

property_and_values

118
716

[('shore a hardness iso 48-4 / iso 868 15s', 91, 91, '', 'shore a hardness'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kv/mm',
  'electric strength'),
 ('intrinsic viscosity iso 307, 1628', 0.63, 3400, '', 'intrinsic viscosity'),
 ('vicat softening temperature', 60, 290, '°c', 'vicat softening temperature'),
 ('relative permittivity', 2.7, 32, '', 'relative permittivity'),
 ('shore a hardness iso 48-4 / iso 868 15s', 28, 98, '', 'shore a hardness'),
 ('tensile strain at failure astm d 3039 m tape 0° (%)',
  1.76,
  3,
  '%',
  'tensile strain at failure'),
 ('wear by sandslurry method (based on gur 4120=100)',
  80,
  380,
  '',
  'wear by sandslurry method (based on gur 4120=100)'),
 ('tensile stress at 100% elongation iso 37 perpendicular (mpa)',
  0.7,
  9.9,
  'mpa',
  'tensile stress at 100% elongation'),
 ('izod notched impact strength',
  2,
  64,
  'kj/m²',
  'izod notched impact strength'),
 ('stress at break iso 527-1/-2 (mpa)', 9, 50, 'mpa', 'stress at break'),
 ('tensile strain at break', 0.35, 50, '%', 'tensile strain at break'),
 ('puncture energy', 13, 43, 'j', 'puncture energy'),
 ('tensile creep modulus', 50, 19600, 'mpa', 'tensile creep modulus'),
 ('fiber volume content iso 11667 (%)', 35, 53, '%', 'fiber volume content'),
 ('izod impact strength', 6, 300, 'kj/m²', 'izod impact strength'),
 ('oxygen index iso 4589-1/-2 (%)', 14.9, 53, '%', 'oxygen index'),
 ('shore d hardness iso 48-4 / iso 868 15s', 21, 85, '', 'shore d hardness'),
 ('effective thermal diffusivity',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('surface resistivity iec 62631-3-2 (ohm)',
  10,
  100000000000000000,
  'ohm',
  'surface resistivity'),
 ('relative permittivity', 2.7, 30, '', 'relative permittivity'),
 ('vicat softening temperature', 47, 270, '°c', 'vicat softening temperature'),
 ('tensile strain at yield iso 527-1/-2 50mm/min (%)',
  2.1,
  40,
  '%',
  'tensile strain at yield'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  29,
  470,
  'mpa',
  'flexural strength'),
 ('izod notched impact strength',
  2,
  96,
  'kj/m²',
  'izod notched impact strength'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'mpa',
  'ball indentation hardness'),
 ('flexural modulus', 26900, 105000, 'mpa', 'flexural modulus'),
 ('tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
  18,
  240,
  'mpa',
  'tensile stress at yield'),
 ('tape thickness iso 16012 (mm)', 0.13, 0.3, 'mm', 'tape thickness'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'density'),
 ('dissipation factor', 4, 654, 'e-4', 'dissipation factor'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  3.2,
  28,
  'mpa',
  'tensile stress at 50% strain'),
 ('tensile stress at 100% strain iso 527-1/-2 (mpa)',
  3,
  26,
  'mpa',
  'tensile stress at 100% strain'),
 ('relative permittivity', 2.3, 2.7, '', 'relative permittivity'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular weight'),
 ('tensile strain at break', 1.5, 370, '%', 'tensile strain at break'),
 ('stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
  3,
  10,
  'mpa',
  'stress at 10% elongation'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°c',
  'continuous service temperature'),
 ('tensile notched impact strength iso 8256/1 23°c (kj/m²)',
  57,
  410,
  'kj/m²',
  'tensile notched impact strength'),
 ('effective thermal diffusivity',
  2.2e-07,
  1.08e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength'),
 ('tensile stress at break', 2.6, 20.7, 'mpa', 'tensile stress at break'),
 ('water absorption sim. to iso 62 2mm (%)',
  0.005,
  12,
  '%',
  'water absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 70, '%', 'compression set'),
 ('flexural modulus', 25, 41000, 'mpa', 'flexural modulus'),
 ('fiber areal weight (g/m²)', 117, 308, 'g/m²', 'fiber areal weight'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact strength'),
 ('molding shrinkage', 0.3, 2.75, '%', 'molding shrinkage'),
 ('temperature of deflection under load',
  46,
  305,
  '°c',
  'temperature of deflection under load'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kj/m²',
  'charpy double notched impact strength'),
 ('melt volume-flow rate iso 1133 (cm³/10min)',
  0.6,
  210,
  'cm³/10min',
  'melt volume-flow rate'),
 ('elongational stress f iso 21304-2 150/10 (mpa)',
  0.01,
  0.68,
  'mpa',
  'elongational stress f'),
 ('dissipation factor', 0, 1500, 'e-4', 'dissipation factor'),
 ('temperature of deflection under load',
  56,
  271,
  '°c',
  'temperature of deflection under load'),
 ('thermal conductivity', 0.21, 34, 'w/(m k)', 'thermal conductivity'),
 ('hardness, rockwell', 95, 125, '', 'hardness, rockwell'),
 ('compressive strength iso 604 (mpa)',
  71,
  293,
  'mpa',
  'compressive strength'),
 ('tensile strength astm d 3039 m tape 0° (mpa)',
  679,
  2030,
  'mpa',
  'tensile strength'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  2100,
  3700,
  'n',
  'puncture - maximum force'),
 ('volume resistivity iec 62631-3-1 (ohm.m)',
  0.001,
  25000000000000000,
  'ohm.m',
  'volume resistivity'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact strength'),
 ('specific heat capacity of melt iso 22007-4 (j/(kg k))',
  1.11,
  2900,
  'j/(kg k)',
  'specific heat capacity of melt'),
 ("poisson's ratio", 0.23, 0.5, '', "poisson's ratio"),
 ('molding shrinkage', 0, 2.75, '%', 'molding shrinkage'),
 ('flexural stress at 3.5% iso 178 (mpa)',
  5.7,
  270,
  'mpa',
  'flexural stress at 3.5%'),
 ('viscosity number iso 307, 1628 (cm³/g)',
  55,
  4200,
  'cm³/g',
  'viscosity number'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.1,
  5.8,
  '%',
  'flexural strain at failure'),
 ('izod impact strength', 9, 300, 'kj/m²', 'izod impact strength'),
 ('charpy impact strength', 2.9, 400, 'kj/m²', 'charpy impact strength'),
 ('glass transition temperature iso 11357-1/-3 10°c/min (°c)',
  -110,
  140,
  '°c',
  'glass transition temperature'),
 ('compression set iso 815 23°c, 24h (%)', 30.3, 76, '%', 'compression set'),
 ('charpy notched impact strength',
  1.9,
  160,
  'kj/m²',
  'charpy notched impact strength'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.08,
  3.32,
  '%',
  'flexural strain at failure'),
 ('nominal strain at break iso 527-1/-2 (%)',
  1.2,
  900,
  '%',
  'nominal strain at break'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  22,
  37300,
  'mpa',
  'tensile modulus'),
 ('tensile stress at break', 10, 180, 'mpa', 'tensile stress at break'),
 ('puncture energy', 3, 85, 'j', 'puncture energy'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°c',
  'ball pressure test'),
 ('izod notched impact strength',
  2,
  115,
  'kj/m²',
  'izod notched impact strength'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'mpa',
  'compressive modulus'),
 ('hardness, rockwell', 39, 119, '', 'hardness, rockwell'),
 ('melt mass-flow rate iso 1133 (g/10min)',
  0.1,
  250,
  'g/10min',
  'melt mass-flow rate'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'elongation at break'),
 ('tensile stress at break', 15.4, 320, 'mpa', 'tensile stress at break'),
 ('charpy notched impact strength',
  0.9,
  130,
  'kj/m²',
  'charpy notched impact strength'),
 ('thermal conductivity', 0.41, 24, 'w/(m k)', 'thermal conductivity'),
 ('effective thermal diffusivity',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'effective thermal diffusivity'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  970,
  5500,
  'n',
  'puncture - maximum force'),
 ('melting temperature iso 11357-1/-3 10°c/min (°c)',
  127,
  355,
  '°c',
  'melting temperature'),
 ('tear strength iso 34-1 normal (kn/m)', 10, 260, 'kn/m', 'tear strength'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25700,
  101000,
  'mpa',
  'tensile modulus'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('tape areal weight (g/m²)', 194, 510, 'g/m²', 'tape areal weight'),
 ('tensile creep modulus', 18, 15800, 'mpa', 'tensile creep modulus'),
 ('humidity absorption sim. to iso 62 2mm (%)',
  0.002,
  4,
  '%',
  'humidity absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 48, '%', 'compression set'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  16,
  49,
  'mpa',
  'tensile stress at 50% strain'),
 ('thermal conductivity', 0.13, 4.5, 'w/(m k)', 'thermal conductivity'),
 ('compression set iso 815 23°c, 24h (%)', 10, 38, '%', 'compression set'),
 ('coefficient of linear thermal expansion (clte)',
  -2.4,
  250,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulk density'),
 ('temperature of deflection under load',
  35,
  340,
  '°c',
  'temperature of deflection under load'),
 ('tape width iso 16012 (mm)', 263, 330, 'mm', 'tape width'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'mpa',
  'compressive stress at 1% strain'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tens mod'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile mod tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tensile modulus'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile modulus tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flex mod'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flex mod tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flexural modulus'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flexural modulus tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flex strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flex strength tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flexural strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength tape'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  "average molecular weight margolies' equation (g/mol)"),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molar mass'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular mass'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'avermw'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'molecular weight'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'mw'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size laser scattering d50 (µm)'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'avg. particle size'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'avpartsize'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'particle size'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'particle size d50'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indentation hardness iso 2039-1 h 358/30 (mpa)'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indentation hardness'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indention hardness'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°C',
  'ball pressure test iec 60695-10-2 (°c)'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°C',
  'ball pressure test'),
 ('bulk density iso 60 (kg/m³)',
  220,
  1100,
  'kg/m³',
  'bulk density iso 60 (kg/m³)'),
 ('bulk density iso 60 (kg/m³)',
  220,
  1100,
  'kg/m³',
  'apparent (bulk) density'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'apparent density'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulkdens'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched impact strength iso 21304-2 23°c (kj/m²)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy impact strength (double notched)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy impact strength (double notch)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch charpy impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched charpy impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch charpy'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched charpy'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch impact'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched impact'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notch'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'impact charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotch'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotched charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotch charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotched impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotch impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotched charpy impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotch charpy impact'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength unnotched'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength unnotch'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength (unnotched)'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength (unnotch)'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact unnotched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact unnotch'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact (unnotched)'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact (unnotch)'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notched'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notch'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notched charpy'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notch charpy'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notch impact'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'notched charpy impact'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notch charpy impact'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength notched'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength notch'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength (notched)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength (notch)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact notched'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy impact notch'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact (notched)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact (notch)'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte)', 6, 329, 'e-6/k', 'clte'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'linear expansion factor'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'thermal expansion'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coef. of lin. therm expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'linear expansion factor (normal)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'normal thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'normal linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'coef. of lin. therm expansion normal'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'clte (transverse direction)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'linear expansion factor (parallel)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'parallel thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'parallel linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'coef. of lin. therm expansion parallel'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'clte (flow direction)'),
 ('compression set', 18, 70, '%', 'compression set'),
 ('compression set iso 815 23°c (%)',
  18,
  48,
  '%',
  'compression set iso 815 23°c (%)'),
 ('compression set iso 815 23°c (%)', 18, 48, '%', 'compression set at 23c'),
 ('compression set iso 815 23°c, 24h (%)',
  10,
  38,
  '%',
  'compression set iso 815 23°c, 24h (%)'),
 ('compression set iso 815 23°c, 24h (%)',
  10,
  38,
  '%',
  'compression set at 23c, 24h'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'MPa',
  'compressive modulus iso 604 (mpa)'),

In [97]:
property_and_values

[('shore a hardness iso 48-4 / iso 868 15s', 91, 91, '', 'shore a hardness'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kv/mm',
  'electric strength'),
 ('intrinsic viscosity iso 307, 1628', 0.63, 3400, '', 'intrinsic viscosity'),
 ('vicat softening temperature', 60, 290, '°c', 'vicat softening temperature'),
 ('relative permittivity', 2.7, 32, '', 'relative permittivity'),
 ('shore a hardness iso 48-4 / iso 868 15s', 28, 98, '', 'shore a hardness'),
 ('tensile strain at failure astm d 3039 m tape 0° (%)',
  1.76,
  3,
  '%',
  'tensile strain at failure'),
 ('wear by sandslurry method (based on gur 4120=100)',
  80,
  380,
  '',
  'wear by sandslurry method (based on gur 4120=100)'),
 ('tensile stress at 100% elongation iso 37 perpendicular (mpa)',
  0.7,
  9.9,
  'mpa',
  'tensile stress at 100% elongation'),
 ('izod notched impact strength',
  2,
  64,
  'kj/m²',
  'izod notched impact strength'),
 ('stress at break iso 527-1/-2 (mpa)', 9, 50, 'mpa', 'stress at break'),
 ('tensile strain at break', 0.35, 50, '%', 'tensile strain at break'),
 ('puncture energy', 13, 43, 'j', 'puncture energy'),
 ('tensile creep modulus', 50, 19600, 'mpa', 'tensile creep modulus'),
 ('fiber volume content iso 11667 (%)', 35, 53, '%', 'fiber volume content'),
 ('izod impact strength', 6, 300, 'kj/m²', 'izod impact strength'),
 ('oxygen index iso 4589-1/-2 (%)', 14.9, 53, '%', 'oxygen index'),
 ('shore d hardness iso 48-4 / iso 868 15s', 21, 85, '', 'shore d hardness'),
 ('effective thermal diffusivity',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('surface resistivity iec 62631-3-2 (ohm)',
  10,
  100000000000000000,
  'ohm',
  'surface resistivity'),
 ('relative permittivity', 2.7, 30, '', 'relative permittivity'),
 ('vicat softening temperature', 47, 270, '°c', 'vicat softening temperature'),
 ('tensile strain at yield iso 527-1/-2 50mm/min (%)',
  2.1,
  40,
  '%',
  'tensile strain at yield'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  29,
  470,
  'mpa',
  'flexural strength'),
 ('izod notched impact strength',
  2,
  96,
  'kj/m²',
  'izod notched impact strength'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'mpa',
  'ball indentation hardness'),
 ('flexural modulus', 26900, 105000, 'mpa', 'flexural modulus'),
 ('tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
  18,
  240,
  'mpa',
  'tensile stress at yield'),
 ('tape thickness iso 16012 (mm)', 0.13, 0.3, 'mm', 'tape thickness'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'density'),
 ('dissipation factor', 4, 654, 'e-4', 'dissipation factor'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  3.2,
  28,
  'mpa',
  'tensile stress at 50% strain'),
 ('tensile stress at 100% strain iso 527-1/-2 (mpa)',
  3,
  26,
  'mpa',
  'tensile stress at 100% strain'),
 ('relative permittivity', 2.3, 2.7, '', 'relative permittivity'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular weight'),
 ('tensile strain at break', 1.5, 370, '%', 'tensile strain at break'),
 ('stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
  3,
  10,
  'mpa',
  'stress at 10% elongation'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°c',
  'continuous service temperature'),
 ('tensile notched impact strength iso 8256/1 23°c (kj/m²)',
  57,
  410,
  'kj/m²',
  'tensile notched impact strength'),
 ('effective thermal diffusivity',
  2.2e-07,
  1.08e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength'),
 ('tensile stress at break', 2.6, 20.7, 'mpa', 'tensile stress at break'),
 ('water absorption sim. to iso 62 2mm (%)',
  0.005,
  12,
  '%',
  'water absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 70, '%', 'compression set'),
 ('flexural modulus', 25, 41000, 'mpa', 'flexural modulus'),
 ('fiber areal weight (g/m²)', 117, 308, 'g/m²', 'fiber areal weight'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact strength'),
 ('molding shrinkage', 0.3, 2.75, '%', 'molding shrinkage'),
 ('temperature of deflection under load',
  46,
  305,
  '°c',
  'temperature of deflection under load'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kj/m²',
  'charpy double notched impact strength'),
 ('melt volume-flow rate iso 1133 (cm³/10min)',
  0.6,
  210,
  'cm³/10min',
  'melt volume-flow rate'),
 ('elongational stress f iso 21304-2 150/10 (mpa)',
  0.01,
  0.68,
  'mpa',
  'elongational stress f'),
 ('dissipation factor', 0, 1500, 'e-4', 'dissipation factor'),
 ('temperature of deflection under load',
  56,
  271,
  '°c',
  'temperature of deflection under load'),
 ('thermal conductivity', 0.21, 34, 'w/(m k)', 'thermal conductivity'),
 ('hardness, rockwell', 95, 125, '', 'hardness, rockwell'),
 ('compressive strength iso 604 (mpa)',
  71,
  293,
  'mpa',
  'compressive strength'),
 ('tensile strength astm d 3039 m tape 0° (mpa)',
  679,
  2030,
  'mpa',
  'tensile strength'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  2100,
  3700,
  'n',
  'puncture - maximum force'),
 ('volume resistivity iec 62631-3-1 (ohm.m)',
  0.001,
  25000000000000000,
  'ohm.m',
  'volume resistivity'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact strength'),
 ('specific heat capacity of melt iso 22007-4 (j/(kg k))',
  1.11,
  2900,
  'j/(kg k)',
  'specific heat capacity of melt'),
 ("poisson's ratio", 0.23, 0.5, '', "poisson's ratio"),
 ('molding shrinkage', 0, 2.75, '%', 'molding shrinkage'),
 ('flexural stress at 3.5% iso 178 (mpa)',
  5.7,
  270,
  'mpa',
  'flexural stress at 3.5%'),
 ('viscosity number iso 307, 1628 (cm³/g)',
  55,
  4200,
  'cm³/g',
  'viscosity number'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.1,
  5.8,
  '%',
  'flexural strain at failure'),
 ('izod impact strength', 9, 300, 'kj/m²', 'izod impact strength'),
 ('charpy impact strength', 2.9, 400, 'kj/m²', 'charpy impact strength'),
 ('glass transition temperature iso 11357-1/-3 10°c/min (°c)',
  -110,
  140,
  '°c',
  'glass transition temperature'),
 ('compression set iso 815 23°c, 24h (%)', 30.3, 76, '%', 'compression set'),
 ('charpy notched impact strength',
  1.9,
  160,
  'kj/m²',
  'charpy notched impact strength'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.08,
  3.32,
  '%',
  'flexural strain at failure'),
 ('nominal strain at break iso 527-1/-2 (%)',
  1.2,
  900,
  '%',
  'nominal strain at break'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  22,
  37300,
  'mpa',
  'tensile modulus'),
 ('tensile stress at break', 10, 180, 'mpa', 'tensile stress at break'),
 ('puncture energy', 3, 85, 'j', 'puncture energy'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°c',
  'ball pressure test'),
 ('izod notched impact strength',
  2,
  115,
  'kj/m²',
  'izod notched impact strength'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'mpa',
  'compressive modulus'),
 ('hardness, rockwell', 39, 119, '', 'hardness, rockwell'),
 ('melt mass-flow rate iso 1133 (g/10min)',
  0.1,
  250,
  'g/10min',
  'melt mass-flow rate'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'elongation at break'),
 ('tensile stress at break', 15.4, 320, 'mpa', 'tensile stress at break'),
 ('charpy notched impact strength',
  0.9,
  130,
  'kj/m²',
  'charpy notched impact strength'),
 ('thermal conductivity', 0.41, 24, 'w/(m k)', 'thermal conductivity'),
 ('effective thermal diffusivity',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'effective thermal diffusivity'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  970,
  5500,
  'n',
  'puncture - maximum force'),
 ('melting temperature iso 11357-1/-3 10°c/min (°c)',
  127,
  355,
  '°c',
  'melting temperature'),
 ('tear strength iso 34-1 normal (kn/m)', 10, 260, 'kn/m', 'tear strength'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25700,
  101000,
  'mpa',
  'tensile modulus'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('tape areal weight (g/m²)', 194, 510, 'g/m²', 'tape areal weight'),
 ('tensile creep modulus', 18, 15800, 'mpa', 'tensile creep modulus'),
 ('humidity absorption sim. to iso 62 2mm (%)',
  0.002,
  4,
  '%',
  'humidity absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 48, '%', 'compression set'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  16,
  49,
  'mpa',
  'tensile stress at 50% strain'),
 ('thermal conductivity', 0.13, 4.5, 'w/(m k)', 'thermal conductivity'),
 ('compression set iso 815 23°c, 24h (%)', 10, 38, '%', 'compression set'),
 ('coefficient of linear thermal expansion (clte)',
  -2.4,
  250,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulk density'),
 ('temperature of deflection under load',
  35,
  340,
  '°c',
  'temperature of deflection under load'),
 ('tape width iso 16012 (mm)', 263, 330, 'mm', 'tape width'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'mpa',
  'compressive stress at 1% strain'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tens mod'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile mod tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tensile modulus'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile modulus tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flex mod'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flex mod tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flexural modulus'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flexural modulus tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flex strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flex strength tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flexural strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength tape'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  "average molecular weight margolies' equation (g/mol)"),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molar mass'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular mass'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'avermw'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'molecular weight'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'mw'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size laser scattering d50 (µm)'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'avg. particle size'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'avpartsize'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'particle size'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'particle size d50'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indentation hardness iso 2039-1 h 358/30 (mpa)'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indentation hardness'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indention hardness'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°C',
  'ball pressure test iec 60695-10-2 (°c)'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°C',
  'ball pressure test'),
 ('bulk density iso 60 (kg/m³)',
  220,
  1100,
  'kg/m³',
  'bulk density iso 60 (kg/m³)'),
 ('bulk density iso 60 (kg/m³)',
  220,
  1100,
  'kg/m³',
  'apparent (bulk) density'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'apparent density'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulkdens'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched impact strength iso 21304-2 23°c (kj/m²)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy impact strength (double notched)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy impact strength (double notch)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch charpy impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched charpy impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch charpy'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched charpy'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch impact'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched impact'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notch'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'impact charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotch'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotched charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotch charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotched impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotch impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotched charpy impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotch charpy impact'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength unnotched'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength unnotch'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength (unnotched)'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength (unnotch)'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact unnotched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact unnotch'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact (unnotched)'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact (unnotch)'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notched'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notch'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notched charpy'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notch charpy'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notch impact'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'notched charpy impact'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notch charpy impact'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength notched'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength notch'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength (notched)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength (notch)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact notched'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy impact notch'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact (notched)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact (notch)'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte)', 6, 329, 'e-6/k', 'clte'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'linear expansion factor'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'thermal expansion'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coef. of lin. therm expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'linear expansion factor (normal)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'normal thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'normal linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'coef. of lin. therm expansion normal'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'clte (transverse direction)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'linear expansion factor (parallel)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'parallel thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'parallel linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'coef. of lin. therm expansion parallel'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'clte (flow direction)'),
 ('compression set', 18, 70, '%', 'compression set'),
 ('compression set iso 815 23°c (%)',
  18,
  48,
  '%',
  'compression set iso 815 23°c (%)'),
 ('compression set iso 815 23°c (%)', 18, 48, '%', 'compression set at 23c'),
 ('compression set iso 815 23°c, 24h (%)',
  10,
  38,
  '%',
  'compression set iso 815 23°c, 24h (%)'),
 ('compression set iso 815 23°c, 24h (%)',
  10,
  38,
  '%',
  'compression set at 23c, 24h'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'MPa',
  'compressive modulus iso 604 (mpa)'),

In [98]:
all_property_names3 = []
prop_abrv = []
for i in property_and_values:
    all_property_names3.append(i[-1])
    if len(i[-1]) <= 4:
        prop_abrv.append(i[-1])

set(all_property_names3)

{'100hz df',
 '100hz dk',
 '1mhz df',
 '1mhz dk',
 '60hz dk',
 'a',
 'ac',
 'ac dielectric strength',
 'ac electristrength',
 'apparent (bulk) density',
 'apparent density',
 'average molar mass',
 'average molecular mass',
 'average molecular weight',
 "average molecular weight margolies' equation (g/mol)",
 'average particle size',
 'average particle size laser scattering d50 (µm)',
 'avermw',
 'avg. particle size',
 'avpartsize',
 'ball indentation hardness',
 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'ball indention hardness',
 'ball pressure test',
 'ball pressure test iec 60695-10-2 (°c)',
 'bend strength',
 'break',
 'break elongation 5 mm/min',
 'break elongation 50 mm/min',
 'break elongation 50mm/min',
 'break elongation 5mm/min',
 'break strain 5 mm/min',
 'break strain 50 mm/min',
 'break strain 50mm/min',
 'break strain 5mm/min',
 'break strain, break elongation',
 'break stress',
 'break stress at 50mm/min',
 'break stress at 5mm/min',
 'bulk density',
 'bulk density iso 60 (kg/m³)',
 'bulkdens',
 'burst strength',
 'charpy double notch',
 'charpy double notched',
 'charpy double notched impact strength',
 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy impact',
 'charpy impact (notch)',
 'charpy impact (notched)',
 'charpy impact (unnotch)',
 'charpy impact (unnotched)',
 'charpy impact notch',
 'charpy impact notched',
 'charpy impact strength',
 'charpy impact strength (double notch)',
 'charpy impact strength (double notched)',
 'charpy impact strength (notch)',
 'charpy impact strength (notched)',
 'charpy impact strength (unnotch)',
 'charpy impact strength (unnotched)',
 'charpy impact strength notch',
 'charpy impact strength notched',
 'charpy impact strength unnotch',
 'charpy impact strength unnotched',
 'charpy impact unnotch',
 'charpy impact unnotched',
 'charpy notch',
 'charpy notch impact',
 'charpy notched',
 'charpy notched impact',
 'charpy notched impact strength',
 'charpy unnotch',
 'charpy unnotch impact',
 'charpy unnotched',
 'charpy unnotched impact',
 'clte',
 'clte (flow direction)',
 'clte (transverse direction)',
 'coef. of lin. therm expansion',
 'coef. of lin. therm expansion normal',
 'coef. of lin. therm expansion parallel',
 'coefficient of linear thermal expansion',
 'coefficient of linear thermal expansion (clte)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'comp mod',
 'compression set',
 'compression set at 23c',
 'compression set at 23c, 24h',
 'compression set iso 815 23°c (%)',
 'compression set iso 815 23°c, 24h (%)',
 'compressive module',
 'compressive modulus',
 'compressive modulus iso 604 (mpa)',
 'compressive strength',
 'compressive strength at 1% deformation',
 'compressive strength at 1% strain',
 'compressive strength iso 604 (mpa)',
 'compressive stress',
 'compressive stress 1% deformation',
 'compressive stress at 1% strain',
 'compressive stress at 1% strain iso 604 (mpa)',
 'continuous allowable service temperature in air',
 'continuous service temperature',
 'continuous service temperature iec 60216-1 (°c)',
 'continuous use temperature',
 'continuous utilization temperature',
 'cross plane thermal conductivity',
 'cross plane thermal diffusivity',
 'cut',
 'd',
 'deflection temperature',
 'deflection temperature 0.45mpa',
 'deflection temperature 1.8mpa',
 'deflection temperature 264psi',
 'deflection temperature 66psi',
 'deflection temperature 8.0mpa',
 'deformation',
 'deformation stability',
 'dense',
 'density',
 'density iso 1183 (kg/m³)',
 'df',
 'df 100hz',
 'df 1mhz',
 'dielectric dissipation',
 'dielectric dissipation 100hz',
 'dielectric dissipation 1mhz',
 'dielectric dissipation at 100hz',
 'dielectric dissipation at 1mhz',
 'dielectric dissipation factor',
 'dielectric dissipation factor at 100hz',
 'dielectric dissipation factor at 1mhz',
 'dielectric dissipation factor, 100hz',
 'dielectric dissipation factor, 1mhz',
 'dielectric factor',
 'dielectric factor 100hz',
 'dielectric factor 1mhz',
 'dielectric factor 60hz',
 'dielectric factor at 100hz',
 'dielectric factor at 1mhz',
 'dielectric factor at 60hz',
 'dielectric loss',
 'dielectric loss 100hz',
 'dielectric loss 1mhz',
 'dielectric loss 60hz',
 'dielectric loss at 100hz',
 'dielectric loss at 1mhz',
 'dielectric loss at 60hz',
 'dimensional precision',
 'dimensional, precise',
 'dissipation factor',
 'dissipation factor 100hz',
 'dissipation factor 1mhz',
 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dk',
 'dk 100hz',
 'dk 1mhz',
 'dk 60hz',
 'dk at 100hz',
 'dk at 1mhz',
 'dk at 60hz',
 'double notch charpy',
 'double notch charpy impact strength',
 'double notch impact',
 'double notched charpy',
 'double notched charpy impact strength',
 'double notched impact',
 'dsc melting temp',
 'dtul',
 'dtul 0.45mpa',
 'dtul 1.8mpa',
 'dtul 8.0mpa',
 'durometer hardness',
 'durometer hardness (a)',
 'durometer hardness (d)',
 'durometer hardness (shore a)',
 'durometer hardness (shore d)',
 'e modulus',
 'e-mod',
 'e-modulus',
 'effective thermal diffusity, flow direction',
 'effective thermal diffusivity',
 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)',
 'effective thermal diffusivity iso 22007-4 flow (m²/s)',
 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'effective thermal diffusivity, crossflow direction',
 'effective thermal diffusivity, through plane direction',
 'elastic modulus',
 'electric strength',
 'electric strength iec 60243-1 (kv/mm)',
 'elongation at break',
 'elongation at break 5 mm/min',
 'elongation at break 50 mm/min',
 'elongation at break 50mm/min',
 'elongation at break 5mm/min',
 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'elongation at break, perpendicular',
 'elongation at yield',
 'elongation at yield 50 mm/min',
 'elongation at yield 50mm/min',
 'elongation break',
 'elongation break 5 mm/min',
 'elongation break 50 mm/min',
 'elongation break 50mm/min',
 'elongation break 5mm/min',
 'elongation yield 50 mm/min',
 'elongation yield 50mm/min',
 'elongational stress f',
 'elongational stress f iso 21304-2 150/10 (mpa)',
 'emod',
 'failure flex strain',
 'fiber areal weight',
 'fiber areal weight (g/m²)',
 'fiber volume content',
 'fiber volume content iso 11667 (%)',
 'flex',
 'flex mod',
 'flex mod tape',
 'flex modulus',
 'flex str',
 'flex str at 3.5% strain',
 'flex strength tape',
 'flex stress',
 'flex stress at 3.5% elongation',
 'flexibility',
 'flexible',
 'flexural elongation at break',
 'flexural modulus',
 'flexural modulus astm d 790 tape 0° (mpa)',
 'flexural modulus of elasticity',
 'flexural modulus tape',
 'flexural performance',
 'flexural strain at failure',
 'flexural strain at failure astm d 790 tape 0° (%)',
 'flexural strain at failure, tape',
 'flexural strength',
 'flexural strength astm d 790 tape 0° (mpa)',
 'flexural strength tape',
 'flexural stress at 3.5%',
 'flexural stress at 3.5% iso 178 (mpa)',
 'flow',
 'flow rate',
 'glass transition',
 'glass transition temperature',
 'glass transition temperature iso 11357-1/-3 10°c/min (°c)',
 'h20 absorption',
 'h2so4',
 'hardness rockwell m',
 'hardness rockwell r',
 'hardness, rockwell',
 'hardness, rockwell iso 2039-2 m-scale',
 'hardness, rockwell iso 2039-2 r-scale',
 'hardness, rockwell m-scale',
 'hardness, rockwell r-scale',
 'hardness, shore a iso 48-4 / iso 868 15s',
 'hardness, shore d iso 48-4 / iso 868 15s',
 'hdt',
 'hdt 0.45mpa',
 'hdt 1.8mpa',
 'hdt 8.0mpa',
 'heat transfer',
 'heavy',
 'heavy weight',
 'humid',
 'humidity',
 'humidity absorption',
 'humidity absorption sim. to iso 62 2mm (%)',
 'impact charpy',
 'impact izod',
 'in plane thermal conductivity',
 'in plane thermal diffusivity',
 'intrinsic viscosity',
 'intrinsic viscosity iso 307, 1628',
 'intrvisc',
 'izod impact',
 'izod impact (notch)',
 'izod impact (notched)',
 'izod impact (unnotch)',
 'izod impact (unnotched)',
 'izod impact notch',
 'izod impact notched',
 'izod impact strength',
 'izod impact strength (notch)',
 'izod impact strength (notched)',
 'izod impact strength (unnotch)',
 'izod impact strength (unnotched)',
 'izod impact strength notch',
 'izod impact strength notched',
 'izod impact strength unnotch',
 'izod impact strength unnotched',
 'izod impact unnotch',
 'izod impact unnotched',
 'izod notch',
 'izod notch impact',
 'izod notched',
 'izod notched impact',
 'izod notched impact strength',
 'izod unnotch',
 'izod unnotch impact',
 'izod unnotched',
 'izod unnotched impact',
 'limiting oxygen',
 'linear expansion factor',
 'linear expansion factor (normal)',
 'linear expansion factor (parallel)',
 'linear thermal expansion',
 'loi',
 'loss angle',
 'loss angle 100hz',
 'loss angle 1mhz',
 'loss angle at 100hz',
 'loss angle at 1mhz',
 'loss tangent',
 'loss tangent 100hz',
 'loss tangent 1mhz',
 'loss tangent at 100hz',
 'loss tangent at 1mhz',
 'max service temperature',
 'maximum puncture force',
 'mechanical behavior',
 'mechanical performance',
 'mechanical properties',
 'mechanical resistance',
 'mechanical strength',
 'melt flow index',
 'melt flow rate',
 'melt index',
 'melt mass flow rate',
 'melt mass-flow rate',
 'melt mass-flow rate iso 1133 (g/10min)',
 'melt temp',
 'melt volume',
 'melt volume flow rate',
 'melt volume rate',
 'melt volume-flow rate',
 'melt volume-flow rate iso 1133 (cm³/10min)',
 'melting temperature',
 'melting temperature iso 11357-1/-3 10°c/min (°c)',
 'mfi',
 'mfr',
 'mi',
 'min service temperature',
 'minimum operating temperature',
 'modulus of elasticity',
 'moisture absorption',
 'moisture absorption equilibrium 23°c/50% r.h.',
 'moisture uptake',
 'mold shrinkage',
 'mold shrinkage (flow)',
 'mold shrinkage (md)',
 'mold shrinkage (md/td)',
 'mold shrinkage (td)',
 'mold shrinkage (x-flow)',
 'mold shrinkage flow',
 'mold shrinkage machine direction',
 'mold shrinkage md',
 'mold shrinkage normal',
 'mold shrinkage parallel',
 'mold shrinkage(transverse direction)',
 'mold-shrinkage',
 'mold-shrinkage, normal',
 'mold-shrinkage, parallel',
 'molding shrinkage',
 'molding shrinkage iso 294-4, 2577 normal (%)',
 'molding shrinkage iso 294-4, 2577 parallel (%)',
 'molding shrinkage, normal',
 'molding shrinkage, parallel',
 'molecular weight',
 'mould shrinkage',
 'mould shrinkage normal',
 'mould shrinkage parallel',
 'mould-shrinkage',
 'mould-shrinkage, normal',
 'mould-shrinkage, parallel',
 'moulding shrinkage',
 'mp',
 'mv',
 'mvr',
 'mw',
 'n tenile impact',
 'nominal break elongation',
 'nominal break strain',
 'nominal elongation',
 'nominal elongation at break',
 'nominal strain at break',
 'nominal strain at break iso 527-1/-2 (%)',
 'nominal strain, break',
 'normal linear thermal expansion',
 'normal thermal expansion',
 'notch charpy',
 'notch charpy impact',
 'notch izod',
 'notch izod impact',
 'notched charpy',
 'notched charpy impact',
 'notched izod',
 'notched izod impact',
 'oxygen index',
 'oxygen index iso 4589-1/-2 (%)',
 'parallel linear thermal expansion',
 'parallel thermal expansion',
 'particle size',
 'particle size d50',
 'perpendicular break strain',
 'perpendicular break stress',
 'perpendicular elongation at break',
 'perpendicular stress at break',
 'perpendicular tensile stress at 100% deformation',
 'perpendicular tensile stress at 100% elongation',
 'perpendicular tensile stress at 100% strain',
 "poisson's ratio",
 'poissons ratio',
 'puncture - maximum force',
 'puncture - maximum force iso 6603-2 23°c (n)',
 'puncture energy',
 'puncture maximum force',
 'relative permittivity',
 'relative permittivity 100hz',
 'relative permittivity 1mhz',
 'relative permittivity 60hz',
 'relative permittivity at 100hz',
 'relative permittivity at 1mhz',
 'relative permittivity at 60hz',
 'relative permittivity iec 62631-2-1 100hz',
 'relative permittivity iec 62631-2-1 1mhz',
 'relative permittivity iec 62631-2-1 60hz',
 'rigid',
 'rigidity',
 'rockwell hardness',
 'rockwell hardness m-scale',
 'rockwell hardness r-scale',
 'rockwell, m',
 'rockwell, r',
 'service temperature long term',
 'service temperature short term',
 'sh a',
 'sh d',
 'shore a',
 'shore a hardness',
 'shore a hardness iso 48-4 / iso 868 15s',
 'shore d',
 'shore d hardness',
 'shore d hardness iso 48-4 / iso 868 15s',
 'shore hardness',
 'soft',
 'specific gravity',
 'specific heat capacity of melt',
 'specific heat capacity of melt iso 22007-4 (j/(kg k))',
 'sr',
 'stiff',
 'stiffness',
 'strain at break 5 mm/min',
 'strain at break 50 mm/min',
 'strain at break 50mm/min',
 'strain at break 5mm/min',
 'strain at yield',
 'strain at yield 50 mm/min',
 'strain at yield 50mm/min',
 'strain break 5 mm/min',
 'strain break 50 mm/min',
 'strain break 50mm/min',
 'strain break 5mm/min',
 'strain yield',
 'strain yield 50 mm/min',
 'strain yield 50mm/min',
 'strebr',
 'strebr at 50mm/min',
 'strebr at 5mm/min',
 'strength modulus',
 'stress at 10% elongation',
 'stress at 100% deformation',
 'stress at 50% deformation',
 'stress at 50% elongation',
 'stress at break',
 'surf_res',
 'surface resistivity',
 'surface resistivity iec 62631-3-2 (ohm)',
 'tan delta',
 'tan delta 100hz',
 'tan delta 1mhz',
 'tan delta at 100hz',
 'tan delta at 1mhz',
 'tangent delta',
 'tangent delta at 100hz',
 'tangent delta at 1mhz',
 'tangent delta, 100hz',
 'tangent delta, 1mhz',
 'tape areal weight',
 'tape areal weight (g/m²)',
 'tape e modulus',
 'tape flex mod',
 'tape flex modulus',
 'tape flex str',
 'tape flex strain failure',
 'tape flex strength',
 'tape flex stress',
 'tape flexural modulus',
 'tape flexural strength',
 'tape modulus of elasticity',
 'tape tens mod',
 'tape tensile mod',
 'tape tensile modulus',
 'tape tensile strength',
 'tape thickness',
 'tape thickness iso 16012 (mm)',
 'tape width',
 'tape width iso 16012 (mm)',
 'tear strength',
 'tear strength iso 34-1 normal (kn/m)',
 'tear stress',
 'temp. of deflection under load',
 'temp. of deflection under load 0.45 mpa',
 'temp. of deflection under load 1.80 mpa',
 'temp. of deflection under load 260 psi annealed',
 'temp. of deflection under load 65 psi annealed',
 'temp. of deflection under load 8.0 mpa',
 'temperature of deflection under load',
 'temperature of deflection under load 0.45 mpa',
 'temperature of deflection under load 1.80 mpa',
 'temperature of deflection under load 8.0 mpa',
 'temperature of deflection under load iso 75-1/-2 0.45 mpa (°c)',
 'temperature of deflection under load iso 75-1/-2 1.8 mpa (°c)',
 'temperature of deflection under load iso 75-1/-2 8 mpa (°c)',
 'temperature resistance',
 'ten mod',
 'ten stress brk',
 'ten stress brk at 50mm/min',
 'ten stress brk at 5mm/min',
 'tensile creep modulus',
 'tensile creep modulus at 1000h',
 'tensile creep modulus at 1h',
 'tensile creep modulus iso 899-1 1000h (mpa)',
 'tensile creep modulus iso 899-1 1h (mpa)',
 'tensile impact notched',
 'tensile mod',
 'tensile mod tape',
 'tensile module',
 'tensile modulus',
 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tensile modulus tape',
 'tensile notched impact strength',
 'tensile notched impact strength iso 8256/1 23°c (kj/m²)',
 'tensile strain at break',
 'tensile strain at break 50mm/min',
 'tensile strain at break 5mm/min',
 'tensile strain at break iso 527-1/-2 50mm/min (%)',
 'tensile strain at break iso 527-1/-2 5mm/min (%)',
 'tensile strain at failure',
 'tensile strain at failure astm d 3039 m tape 0° (%)',
 'tensile strain at yield',
 'tensile strain at yield 50mm/min',
 'tensile strain at yield iso 527-1/-2 50mm/min (%)',
 'tensile strength',
 'tensile strength (yield)',
 'tensile strength astm d 3039 m tape 0° (mpa)',
 'tensile strength at break',
 'tensile strength at break at 50mm/min',
 'tensile strength at break at 5mm/min',
 'tensile strength at yield',
 'tensile strength tape',
 'tensile stress (break)',
 'tensile stress (break) at 50mm/min',
 'tensile stress (break) at 5mm/min',
 'tensile stress (yield)',
 'tensile stress at 100% deformation, perpendicular',
 'tensile stress at 100% elongation',
 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
 'tensile stress at 100% elongation, perpendicular',
 'tensile stress at 100% strain',
 'tensile stress at 100% strain iso 527-1/-2 (mpa)',
 'tensile stress at 100% strain, perpendicular',
 'tensile stress at 50% strain',
 'tensile stress at 50% strain iso 527-1/-2 (mpa)',
 'tensile stress at break',
 'tensile stress at break at 50mm/min',
 'tensile stress at break at 5mm/min',
 'tensile stress at break iso 527-1/-2 50mm/min (mpa)',
 'tensile stress at break iso 527-1/-2 5mm/min (mpa)',
 'tensile stress at break iso 527-1/-2 or iso 37 perpendicular (mpa)',
 'tensile stress at break perpendicular',
 'tensile stress at yield',
 'tensile stress at yield 50mm/min',
 'tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
 'tensile tape',
 "tensile young's modulus",
 'tg',
 'thermal conductive',
 'thermal conductivity',
 'thermal conductivity crossflow direction',
 'thermal conductivity flow direction',
 'thermal conductivity iso 22007-2 crossflow (w/(m k))',
 'thermal conductivity iso 22007-2 flow (w/(m k))',
 'thermal conductivity iso 22007-2 through plane (w/(m k))',
 'thermal conductivity of melt',
 'thermal conductivity through plane',
 'thermal conductivity thruplane direction',
 'thermal expansion',
 'through plane thermal diffusivity',
 'thruplane thermal conductivity',
 'unnotch charpy',
 'unnotch charpy impact',
 'unnotch izod',
 'unnotch izod impact',
 'unnotched charpy',
 'unnotched charpy impact',
 'unnotched izod',
 'unnotched izod impact',
 'vicat',
 'vicat at 50°c/h 10n',
 'vicat at 50°c/h 50n',
 'vicat softening point',
 'vicat softening point at 50°c/h 10n',
 'vicat softening point at 50°c/h 50n',
 'vicat softening temperature',
 'vicat softening temperature at 50°c/h 10n',
 'vicat softening temperature at 50°c/h 50n',
 'vicat softening temperature iso 306 50°c/h 10n (°c)',
 'vicat softening temperature iso 306 50°c/h 50n (°c)',
 'vicat softing temp',
 'vicat softing temp at 50°c/h 10n',
 'vicat softing temp at 50°c/h 50n',
 'viscosity h2so4',
 'viscosity number',
 'viscosity number (0.5% in 96 % h2so4)',
 'viscosity number iso 307, 1628 (cm³/g)',
 'vn at 0.5% in sulfuric acid nominal',
 'volres',
 'volume resistivity',
 'volume resistivity iec 62631-3-1 (ohm.m)',
 'vr',
 'water',
 'water absorption',
 'water absorption sim. to iso 62 2mm (%)',
 'wear by sandslurry method',
 'wear by sandslurry method (based on gur 4120=100)',
 'yield elongation',
 'yield elongation 50 mm/min',
 'yield elongation 50mm/min',
 'yield strain',
 'yield strain 50 mm/min',
 'yield strain 50mm/min',
 'yield stress',
 'young modulus',
 "young's modulus",
 'youngs e modulus',
 'youngs modulus',
 'η'}

In [99]:
print(prop_abrv)

['mw', 'clte', 'cut', 'df', 'ac', 'flex', 'tg', 'η', 'mfr', 'mfi', 'flow', 'mi', 'mvr', 'mv', 'mp', 'loi', 'dk', 'sh a', 'a', 'soft', 'sh d', 'd', 'sr', 'dtul', 'hdt', 'emod', 'vr']

In [100]:
all_filler_syns = []
for i in filler_syns:
    all_filler_syns.extend(filler_syns[i])

# prop_abrv = [
#     'bpt', 'bsa', 'bsb', 'bse', 'bsl', 'bspa', 'clte', 'cte', 'dc', 'df', 'dk', 'dr', 'dres', 'ds', 'dtul', 'emod', 'eoc', 'eov',
#     'flow', 'fs', 'hdt', 'izod', 'loi', 'lsa', 'lsb', 'lse', 'lsl', 'mfi', 'mfr', 'mrc', 'mv', 'mvr', 
#     'mw', 'sg', 'sr', 'tg', 'wsa', 'wsb', 'wse', 'wsl', 'wvtr', 'fm', 'fs', 'ts', 'sha'
# ]


print(len(prop_abrv))

# prop_abrv = [i for i in prop_abrv if i not in all_ulp_syns]
prop_abrv = [i for i in prop_abrv if i not in all_brands]
prop_abrv = [i for i in prop_abrv if i not in all_filler_syns]

print(len(prop_abrv))

prop_abrv_mapping = {}
for i in prop_df[prop_df['SYNONYMS'].isin(prop_abrv)][['DEFINED_NAME', 'SYNONYMS']].to_dict('split')['data']:
    matched_prop = process.extract(i[0], all_property_names3)[0][0]
    # print(i[1], i[0], matched_prop)
    prop_abrv_mapping[i[1]] = matched_prop
    
prop_abrv_mapping

27
27

{'mw': "average molecular weight margolies' equation (g/mol)",
 'clte': 'coefficient of linear thermal expansion (clte)',
 'cut': 'continuous service temperature iec 60216-1 (°c)',
 'df': 'dissipation factor',
 'ac': 'electric strength iec 60243-1 (kv/mm)',
 'flex': 'flexural modulus',
 'tg': 'glass transition temperature iso 11357-1/-3 10°c/min (°c)',
 'η': 'intrinsic viscosity iso 307, 1628',
 'mfr': 'melt mass-flow rate iso 1133 (g/10min)',
 'mfi': 'melt mass-flow rate iso 1133 (g/10min)',
 'flow': 'melt mass-flow rate iso 1133 (g/10min)',
 'mvr': 'melt volume-flow rate iso 1133 (cm³/10min)',
 'mv': 'melt volume-flow rate iso 1133 (cm³/10min)',
 'mp': 'melting temperature iso 11357-1/-3 10°c/min (°c)',
 'loi': 'oxygen index iso 4589-1/-2 (%)',
 'dk': 'relative permittivity',
 'sh a': 'shore a hardness iso 48-4 / iso 868 15s',
 'a': 'shore a hardness iso 48-4 / iso 868 15s',
 'soft': 'shore a hardness iso 48-4 / iso 868 15s',
 'sh d': 'shore d hardness iso 48-4 / iso 868 15s',
 'd': 'shore d hardness iso 48-4 / iso 868 15s',
 'dtul': 'temperature of deflection under load',
 'hdt': 'temperature of deflection under load',
 'emod': 'tensile modulus',
 'vr': 'volume resistivity iec 62631-3-1 (ohm.m)',
 'mi': 'melt mass-flow rate iso 1133 (g/10min)',
 'sr': 'surface resistivity iec 62631-3-2 (ohm)'}

In [101]:
a = list(feature_syn_mapping) + list(brand_syn_mapping) + list(polymer_syn_mapping) + list(processing_syn_mapping) + list(delivery_syn_mapping)
for i in all_property_names3:
    if i in a:
        print(i)


# all_property_names3

In [102]:
# for i in ['mw', 'cut', 'ac', 'tg', 'η', 'mfr', 'mfi', 'flow', 'mvr', 'mv', 'mp', 'loi', 'sh a', 'a', 'soft', 'sh a', 'a', 'soft', 'sh d', 'd', 'hard', 'sr', 'dtul', 'hdt', 'dtul', 'hdt', 'dtul', 'hdt', 'vr']:
#     if i not in list(prop_abrv_mapping):
#         print(i)

# print(len(set(prop_abrv)), len(prop_abrv_mapping))

In [103]:
prop_abrv_mapping

{'mw': "average molecular weight margolies' equation (g/mol)",
 'clte': 'coefficient of linear thermal expansion (clte)',
 'cut': 'continuous service temperature iec 60216-1 (°c)',
 'df': 'dissipation factor',
 'ac': 'electric strength iec 60243-1 (kv/mm)',
 'flex': 'flexural modulus',
 'tg': 'glass transition temperature iso 11357-1/-3 10°c/min (°c)',
 'η': 'intrinsic viscosity iso 307, 1628',
 'mfr': 'melt mass-flow rate iso 1133 (g/10min)',
 'mfi': 'melt mass-flow rate iso 1133 (g/10min)',
 'flow': 'melt mass-flow rate iso 1133 (g/10min)',
 'mvr': 'melt volume-flow rate iso 1133 (cm³/10min)',
 'mv': 'melt volume-flow rate iso 1133 (cm³/10min)',
 'mp': 'melting temperature iso 11357-1/-3 10°c/min (°c)',
 'loi': 'oxygen index iso 4589-1/-2 (%)',
 'dk': 'relative permittivity',
 'sh a': 'shore a hardness iso 48-4 / iso 868 15s',
 'a': 'shore a hardness iso 48-4 / iso 868 15s',
 'soft': 'shore a hardness iso 48-4 / iso 868 15s',
 'sh d': 'shore d hardness iso 48-4 / iso 868 15s',
 'd': 'shore d hardness iso 48-4 / iso 868 15s',
 'dtul': 'temperature of deflection under load',
 'hdt': 'temperature of deflection under load',
 'emod': 'tensile modulus',
 'vr': 'volume resistivity iec 62631-3-1 (ohm.m)',
 'mi': 'melt mass-flow rate iso 1133 (g/10min)',
 'sr': 'surface resistivity iec 62631-3-2 (ohm)'}

In [104]:
property_and_values

[('shore a hardness iso 48-4 / iso 868 15s', 91, 91, '', 'shore a hardness'),
 ('electric strength iec 60243-1 (kv/mm)',
  2.4,
  59,
  'kv/mm',
  'electric strength'),
 ('intrinsic viscosity iso 307, 1628', 0.63, 3400, '', 'intrinsic viscosity'),
 ('vicat softening temperature', 60, 290, '°c', 'vicat softening temperature'),
 ('relative permittivity', 2.7, 32, '', 'relative permittivity'),
 ('shore a hardness iso 48-4 / iso 868 15s', 28, 98, '', 'shore a hardness'),
 ('tensile strain at failure astm d 3039 m tape 0° (%)',
  1.76,
  3,
  '%',
  'tensile strain at failure'),
 ('wear by sandslurry method (based on gur 4120=100)',
  80,
  380,
  '',
  'wear by sandslurry method (based on gur 4120=100)'),
 ('tensile stress at 100% elongation iso 37 perpendicular (mpa)',
  0.7,
  9.9,
  'mpa',
  'tensile stress at 100% elongation'),
 ('izod notched impact strength',
  2,
  64,
  'kj/m²',
  'izod notched impact strength'),
 ('stress at break iso 527-1/-2 (mpa)', 9, 50, 'mpa', 'stress at break'),
 ('tensile strain at break', 0.35, 50, '%', 'tensile strain at break'),
 ('puncture energy', 13, 43, 'j', 'puncture energy'),
 ('tensile creep modulus', 50, 19600, 'mpa', 'tensile creep modulus'),
 ('fiber volume content iso 11667 (%)', 35, 53, '%', 'fiber volume content'),
 ('izod impact strength', 6, 300, 'kj/m²', 'izod impact strength'),
 ('oxygen index iso 4589-1/-2 (%)', 14.9, 53, '%', 'oxygen index'),
 ('shore d hardness iso 48-4 / iso 868 15s', 21, 85, '', 'shore d hardness'),
 ('effective thermal diffusivity',
  2e-11,
  1.79e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('surface resistivity iec 62631-3-2 (ohm)',
  10,
  100000000000000000,
  'ohm',
  'surface resistivity'),
 ('relative permittivity', 2.7, 30, '', 'relative permittivity'),
 ('vicat softening temperature', 47, 270, '°c', 'vicat softening temperature'),
 ('tensile strain at yield iso 527-1/-2 50mm/min (%)',
  2.1,
  40,
  '%',
  'tensile strain at yield'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  29,
  470,
  'mpa',
  'flexural strength'),
 ('izod notched impact strength',
  2,
  96,
  'kj/m²',
  'izod notched impact strength'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'mpa',
  'ball indentation hardness'),
 ('flexural modulus', 26900, 105000, 'mpa', 'flexural modulus'),
 ('tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
  18,
  240,
  'mpa',
  'tensile stress at yield'),
 ('tape thickness iso 16012 (mm)', 0.13, 0.3, 'mm', 'tape thickness'),
 ('density iso 1183 (kg/m³)', 890, 2290, 'kg/m³', 'density'),
 ('dissipation factor', 4, 654, 'e-4', 'dissipation factor'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  3.2,
  28,
  'mpa',
  'tensile stress at 50% strain'),
 ('tensile stress at 100% strain iso 527-1/-2 (mpa)',
  3,
  26,
  'mpa',
  'tensile stress at 100% strain'),
 ('relative permittivity', 2.3, 2.7, '', 'relative permittivity'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular weight'),
 ('tensile strain at break', 1.5, 370, '%', 'tensile strain at break'),
 ('stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
  3,
  10,
  'mpa',
  'stress at 10% elongation'),
 ('continuous service temperature iec 60216-1 (°c)',
  85,
  140,
  '°c',
  'continuous service temperature'),
 ('tensile notched impact strength iso 8256/1 23°c (kj/m²)',
  57,
  410,
  'kj/m²',
  'tensile notched impact strength'),
 ('effective thermal diffusivity',
  2.2e-07,
  1.08e-06,
  'm²/s',
  'effective thermal diffusivity'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength'),
 ('tensile stress at break', 2.6, 20.7, 'mpa', 'tensile stress at break'),
 ('water absorption sim. to iso 62 2mm (%)',
  0.005,
  12,
  '%',
  'water absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 70, '%', 'compression set'),
 ('flexural modulus', 25, 41000, 'mpa', 'flexural modulus'),
 ('fiber areal weight (g/m²)', 117, 308, 'g/m²', 'fiber areal weight'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact strength'),
 ('molding shrinkage', 0.3, 2.75, '%', 'molding shrinkage'),
 ('temperature of deflection under load',
  46,
  305,
  '°c',
  'temperature of deflection under load'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kj/m²',
  'charpy double notched impact strength'),
 ('melt volume-flow rate iso 1133 (cm³/10min)',
  0.6,
  210,
  'cm³/10min',
  'melt volume-flow rate'),
 ('elongational stress f iso 21304-2 150/10 (mpa)',
  0.01,
  0.68,
  'mpa',
  'elongational stress f'),
 ('dissipation factor', 0, 1500, 'e-4', 'dissipation factor'),
 ('temperature of deflection under load',
  56,
  271,
  '°c',
  'temperature of deflection under load'),
 ('thermal conductivity', 0.21, 34, 'w/(m k)', 'thermal conductivity'),
 ('hardness, rockwell', 95, 125, '', 'hardness, rockwell'),
 ('compressive strength iso 604 (mpa)',
  71,
  293,
  'mpa',
  'compressive strength'),
 ('tensile strength astm d 3039 m tape 0° (mpa)',
  679,
  2030,
  'mpa',
  'tensile strength'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  2100,
  3700,
  'n',
  'puncture - maximum force'),
 ('volume resistivity iec 62631-3-1 (ohm.m)',
  0.001,
  25000000000000000,
  'ohm.m',
  'volume resistivity'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact strength'),
 ('specific heat capacity of melt iso 22007-4 (j/(kg k))',
  1.11,
  2900,
  'j/(kg k)',
  'specific heat capacity of melt'),
 ("poisson's ratio", 0.23, 0.5, '', "poisson's ratio"),
 ('molding shrinkage', 0, 2.75, '%', 'molding shrinkage'),
 ('flexural stress at 3.5% iso 178 (mpa)',
  5.7,
  270,
  'mpa',
  'flexural stress at 3.5%'),
 ('viscosity number iso 307, 1628 (cm³/g)',
  55,
  4200,
  'cm³/g',
  'viscosity number'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.1,
  5.8,
  '%',
  'flexural strain at failure'),
 ('izod impact strength', 9, 300, 'kj/m²', 'izod impact strength'),
 ('charpy impact strength', 2.9, 400, 'kj/m²', 'charpy impact strength'),
 ('glass transition temperature iso 11357-1/-3 10°c/min (°c)',
  -110,
  140,
  '°c',
  'glass transition temperature'),
 ('compression set iso 815 23°c, 24h (%)', 30.3, 76, '%', 'compression set'),
 ('charpy notched impact strength',
  1.9,
  160,
  'kj/m²',
  'charpy notched impact strength'),
 ('flexural strain at failure astm d 790 tape 0° (%)',
  1.08,
  3.32,
  '%',
  'flexural strain at failure'),
 ('nominal strain at break iso 527-1/-2 (%)',
  1.2,
  900,
  '%',
  'nominal strain at break'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  22,
  37300,
  'mpa',
  'tensile modulus'),
 ('tensile stress at break', 10, 180, 'mpa', 'tensile stress at break'),
 ('puncture energy', 3, 85, 'j', 'puncture energy'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°c',
  'ball pressure test'),
 ('izod notched impact strength',
  2,
  115,
  'kj/m²',
  'izod notched impact strength'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'mpa',
  'compressive modulus'),
 ('hardness, rockwell', 39, 119, '', 'hardness, rockwell'),
 ('melt mass-flow rate iso 1133 (g/10min)',
  0.1,
  250,
  'g/10min',
  'melt mass-flow rate'),
 ('elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
  300,
  830,
  '%',
  'elongation at break'),
 ('tensile stress at break', 15.4, 320, 'mpa', 'tensile stress at break'),
 ('charpy notched impact strength',
  0.9,
  130,
  'kj/m²',
  'charpy notched impact strength'),
 ('thermal conductivity', 0.41, 24, 'w/(m k)', 'thermal conductivity'),
 ('effective thermal diffusivity',
  1.3e-07,
  3.8e-07,
  'm²/s',
  'effective thermal diffusivity'),
 ('puncture maximum force iso 6603-2 23°c (n)',
  970,
  5500,
  'n',
  'puncture - maximum force'),
 ('melting temperature iso 11357-1/-3 10°c/min (°c)',
  127,
  355,
  '°c',
  'melting temperature'),
 ('tear strength iso 34-1 normal (kn/m)', 10, 260, 'kn/m', 'tear strength'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25700,
  101000,
  'mpa',
  'tensile modulus'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('tape areal weight (g/m²)', 194, 510, 'g/m²', 'tape areal weight'),
 ('tensile creep modulus', 18, 15800, 'mpa', 'tensile creep modulus'),
 ('humidity absorption sim. to iso 62 2mm (%)',
  0.002,
  4,
  '%',
  'humidity absorption'),
 ('compression set iso 815 23°c, 24h (%)', 18, 48, '%', 'compression set'),
 ('tensile stress at 50% strain iso 527-1/-2 (mpa)',
  16,
  49,
  'mpa',
  'tensile stress at 50% strain'),
 ('thermal conductivity', 0.13, 4.5, 'w/(m k)', 'thermal conductivity'),
 ('compression set iso 815 23°c, 24h (%)', 10, 38, '%', 'compression set'),
 ('coefficient of linear thermal expansion (clte)',
  -2.4,
  250,
  'e-6/k',
  'coefficient of linear thermal expansion (clte)'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulk density'),
 ('temperature of deflection under load',
  35,
  340,
  '°c',
  'temperature of deflection under load'),
 ('tape width iso 16012 (mm)', 263, 330, 'mm', 'tape width'),
 ('compressive stress at 1% strain iso 604 (mpa)',
  21,
  238,
  'mpa',
  'compressive stress at 1% strain'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tens mod'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile mod tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tape tensile modulus'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile modulus tape'),
 ('tensile modulus astm d 3039 m tape 0° (mpa)',
  25.7,
  101,
  'gpa',
  'tensile tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flex mod'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flex mod tape'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'tape flexural modulus'),
 ('flexural modulus astm d 790 tape 0° (mpa)',
  26.9,
  105,
  'gpa',
  'flexural modulus tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flex strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flex strength tape'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'tape flexural strength'),
 ('flexural strength astm d 790 tape 0° (mpa)',
  465,
  1220,
  'mpa',
  'flexural strength tape'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  "average molecular weight margolies' equation (g/mol)"),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molar mass'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'average molecular mass'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'avermw'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'molecular weight'),
 ("average molecular weight margolies' equation (g/mol)",
  240000,
  10200000,
  'g/mol',
  'mw'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'average particle size laser scattering d50 (µm)'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'avg. particle size'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'avpartsize'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'particle size'),
 ('average particle size laser scattering d50 (µm)',
  20,
  450,
  'µm',
  'particle size d50'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indentation hardness iso 2039-1 h 358/30 (mpa)'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indentation hardness'),
 ('ball indentation hardness iso 2039-1 h 358/30 (mpa)',
  90,
  200,
  'MPa',
  'ball indention hardness'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°C',
  'ball pressure test iec 60695-10-2 (°c)'),
 ('ball pressure test iec 60695-10-2 (°c)',
  150,
  290,
  '°C',
  'ball pressure test'),
 ('bulk density iso 60 (kg/m³)',
  220,
  1100,
  'kg/m³',
  'bulk density iso 60 (kg/m³)'),
 ('bulk density iso 60 (kg/m³)',
  220,
  1100,
  'kg/m³',
  'apparent (bulk) density'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'apparent density'),
 ('bulk density iso 60 (kg/m³)', 220, 1100, 'kg/m³', 'bulkdens'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched impact strength iso 21304-2 23°c (kj/m²)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy impact strength (double notched)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy impact strength (double notch)'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch charpy impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched charpy impact strength'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch charpy'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched charpy'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notch impact'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'double notched impact'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notch'),
 ('charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
  15,
  240,
  'kJ/m²',
  'charpy double notched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'impact charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotch'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotched charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotch charpy'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotched impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy unnotch impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotched charpy impact'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'unnotch charpy impact'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength unnotched'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength unnotch'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength (unnotched)'),
 ('charpy impact strength',
  3.4,
  300,
  'kj/m²',
  'charpy impact strength (unnotch)'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact unnotched'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact unnotch'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact (unnotched)'),
 ('charpy impact strength', 3.4, 300, 'kj/m²', 'charpy impact (unnotch)'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notched'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notch'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notched charpy'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notch charpy'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy notched impact'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy notch impact'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'notched charpy impact'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'notch charpy impact'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength notched'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength notch'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength (notched)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact strength (notch)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact notched'),
 ('charpy notched impact strength', 2.5, 150, 'kj/m²', 'charpy impact notch'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact (notched)'),
 ('charpy notched impact strength',
  2.5,
  150,
  'kj/m²',
  'charpy impact (notch)'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coefficient of linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte)', 6, 329, 'e-6/k', 'clte'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'linear expansion factor'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'thermal expansion'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte)',
  6,
  329,
  'e-6/k',
  'coef. of lin. therm expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'linear expansion factor (normal)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'normal thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'normal linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'coef. of lin. therm expansion normal'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
  6,
  329,
  'E-6/K',
  'clte (transverse direction)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'linear expansion factor (parallel)'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'parallel thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'parallel linear thermal expansion'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'coef. of lin. therm expansion parallel'),
 ('coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
  -2.4,
  250,
  'E-6/K',
  'clte (flow direction)'),
 ('compression set', 18, 70, '%', 'compression set'),
 ('compression set iso 815 23°c (%)',
  18,
  48,
  '%',
  'compression set iso 815 23°c (%)'),
 ('compression set iso 815 23°c (%)', 18, 48, '%', 'compression set at 23c'),
 ('compression set iso 815 23°c, 24h (%)',
  10,
  38,
  '%',
  'compression set iso 815 23°c, 24h (%)'),
 ('compression set iso 815 23°c, 24h (%)',
  10,
  38,
  '%',
  'compression set at 23c, 24h'),
 ('compressive modulus iso 604 (mpa)',
  2000,
  33000,
  'MPa',
  'compressive modulus iso 604 (mpa)'),

In [105]:
all_units = []
for i in property_and_values:
    if i[3].lower() not in all_units:
        all_units.append(i[3].lower())
        
all_units

['',
 'kv/mm',
 '°c',
 '%',
 'mpa',
 'kj/m²',
 'j',
 'm²/s',
 'ohm',
 'mm',
 'kg/m³',
 'e-4',
 'g/mol',
 'g/m²',
 'cm³/10min',
 'w/(m k)',
 'n',
 'ohm.m',
 'j/(kg k)',
 'cm³/g',
 'µm',
 'g/10min',
 'kn/m',
 'e-6/k',
 'gpa']

In [106]:
unit_syns = {
    'mpa':  ['megapascal', 'kilopascal', 'kpa', 'pascal'], 
    '%': ['percent', 'percentage'], 
    'kj/m²': ['kj/m2', 'kilojoule per square meter', 'joule per square meter', 'j/m²', 'j/m2'], 
    '°c': ['degrees celsius', 'celsius', 'c', 'centigrade', 'fahrenheit', '°f', 'f', 'kelvin', 'k'], 
    'kv/mm': ['kilovolts per millimeter', 'volts per mil', 'v/mm'], 
    'gpa': ['gigapascal', 'gpa'], 
    'kg/m³': ['kilograms per cubic meter', 'grams per cubic centimeter', 'g/cm³'], 
}

for k in unit_syns:
    unit_syns[k] = [x.lower().strip() for x in unit_syns[k]]
    
for i in unit_syns:
    found = False
    if i not in all_units:
        for j in unit_syns[i]:
            if j in all_units:
                found = True
    else:
        found = True
    
    if not found:
        print(i)

In [107]:
def get_random_percent(v):
    range_percent = random.choice([5, 10, 15, 20, 25, 30])
    min_value = v*(1+ (-range_percent/100))
    max_value = v*(1+ (range_percent/100))
    return range_percent, min_value, max_value

get_random_percent(random.randint(10, 1000))

(5, 438.9, 485.1)

In [108]:
def get_random_range(value):
    # Generate random min and max
    start = float(value*0.5)
    end = float(value*1.5)
    min_value = round(random.uniform(start, value*0.9), 2)
    max_value = round(random.uniform(value*1.1, end), 2)
    if not -10 < min_value < 10:
        min_value = int(min_value)
        max_value = int(max_value)
        
    return min_value, max_value

In [109]:
temp = []
for i in property_and_values:
    if not i[-1].replace(" ", "") in temp:
        temp.append(i[-1].replace(" ", ""))
		
temp

['shoreahardness',
 'electricstrength',
 'intrinsicviscosity',
 'vicatsofteningtemperature',
 'relativepermittivity',
 'tensilestrainatfailure',
 'wearbysandslurrymethod(basedongur4120=100)',
 'tensilestressat100%elongation',
 'izodnotchedimpactstrength',
 'stressatbreak',
 'tensilestrainatbreak',
 'punctureenergy',
 'tensilecreepmodulus',
 'fibervolumecontent',
 'izodimpactstrength',
 'oxygenindex',
 'shoredhardness',
 'effectivethermaldiffusivity',
 'surfaceresistivity',
 'tensilestrainatyield',
 'flexuralstrength',
 'ballindentationhardness',
 'flexuralmodulus',
 'tensilestressatyield',
 'tapethickness',
 'density',
 'dissipationfactor',
 'tensilestressat50%strain',
 'tensilestressat100%strain',
 'averagemolecularweight',
 'stressat10%elongation',
 'continuousservicetemperature',
 'tensilenotchedimpactstrength',
 'tensilestressatbreak',
 'waterabsorption',
 'compressionset',
 'fiberarealweight',
 'charpyimpactstrength',
 'moldingshrinkage',
 'temperatureofdeflectionunderload',
 'charpydoublenotchedimpactstrength',
 'meltvolume-flowrate',
 'elongationalstressf',
 'thermalconductivity',
 'hardness,rockwell',
 'compressivestrength',
 'tensilestrength',
 'puncture-maximumforce',
 'volumeresistivity',
 'charpynotchedimpactstrength',
 'specificheatcapacityofmelt',
 "poisson'sratio",
 'flexuralstressat3.5%',
 'viscositynumber',
 'flexuralstrainatfailure',
 'glasstransitiontemperature',
 'nominalstrainatbreak',
 'tensilemodulus',
 'averageparticlesize',
 'ballpressuretest',
 'compressivemodulus',
 'meltmass-flowrate',
 'elongationatbreak',
 'meltingtemperature',
 'tearstrength',
 'coefficientoflinearthermalexpansion(clte)',
 'tapearealweight',
 'humidityabsorption',
 'bulkdensity',
 'tapewidth',
 'compressivestressat1%strain',
 'tapetensmod',
 'tensilemodtape',
 'tapetensilemodulus',
 'tensilemodulustape',
 'tensiletape',
 'tapeflexmod',
 'flexmodtape',
 'tapeflexuralmodulus',
 'flexuralmodulustape',
 'tapeflexstrength',
 'flexstrengthtape',
 'tapeflexuralstrength',
 'flexuralstrengthtape',
 "averagemolecularweightmargolies'equation(g/mol)",
 'averagemolarmass',
 'averagemolecularmass',
 'avermw',
 'molecularweight',
 'mw',
 'averageparticlesizelaserscatteringd50(µm)',
 'avg.particlesize',
 'avpartsize',
 'particlesize',
 'particlesized50',
 'ballindentationhardnessiso2039-1h358/30(mpa)',
 'ballindentionhardness',
 'ballpressuretestiec60695-10-2(°c)',
 'bulkdensityiso60(kg/m³)',
 'apparent(bulk)density',
 'apparentdensity',
 'bulkdens',
 'charpydoublenotchedimpactstrengthiso21304-223°c(kj/m²)',
 'charpyimpactstrength(doublenotched)',
 'charpyimpactstrength(doublenotch)',
 'doublenotchcharpyimpactstrength',
 'doublenotchedcharpyimpactstrength',
 'doublenotchcharpy',
 'doublenotchedcharpy',
 'doublenotchimpact',
 'doublenotchedimpact',
 'charpydoublenotch',
 'charpydoublenotched',
 'charpyimpact',
 'impactcharpy',
 'charpyunnotched',
 'charpyunnotch',
 'unnotchedcharpy',
 'unnotchcharpy',
 'charpyunnotchedimpact',
 'charpyunnotchimpact',
 'unnotchedcharpyimpact',
 'unnotchcharpyimpact',
 'charpyimpactstrengthunnotched',
 'charpyimpactstrengthunnotch',
 'charpyimpactstrength(unnotched)',
 'charpyimpactstrength(unnotch)',
 'charpyimpactunnotched',
 'charpyimpactunnotch',
 'charpyimpact(unnotched)',
 'charpyimpact(unnotch)',
 'charpynotched',
 'charpynotch',
 'notchedcharpy',
 'notchcharpy',
 'charpynotchedimpact',
 'charpynotchimpact',
 'notchedcharpyimpact',
 'notchcharpyimpact',
 'charpyimpactstrengthnotched',
 'charpyimpactstrengthnotch',
 'charpyimpactstrength(notched)',
 'charpyimpactstrength(notch)',
 'charpyimpactnotched',
 'charpyimpactnotch',
 'charpyimpact(notched)',
 'charpyimpact(notch)',
 'coefficientoflinearthermalexpansion',
 'clte',
 'linearexpansionfactor',
 'thermalexpansion',
 'linearthermalexpansion',
 'coef.oflin.thermexpansion',
 'coefficientoflinearthermalexpansion(clte)iso11359-1/-2normal(e-6/k)',
 'linearexpansionfactor(normal)',
 'normalthermalexpansion',
 'normallinearthermalexpansion',
 'coef.oflin.thermexpansionnormal',
 'clte(transversedirection)',
 'coefficientoflinearthermalexpansion(clte)iso11359-1/-2parallel(e-6/k)',
 'linearexpansionfactor(parallel)',
 'parallelthermalexpansion',
 'parallellinearthermalexpansion',
 'coef.oflin.thermexpansionparallel',
 'clte(flowdirection)',
 'compressionsetiso81523°c(%)',
 'compressionsetat23c',
 'compressionsetiso81523°c,24h(%)',
 'compressionsetat23c,24h',
 'compressivemodulusiso604(mpa)',
 'compressivemodule',
 'compmod',
 'compressivestrengthiso604(mpa)',
 'compressivestress',
 'compressivestressat1%strainiso604(mpa)',
 'compressivestrengthat1%strain',
 'compressivestress1%deformation',
 'compressivestrengthat1%deformation',
 'continuousservicetemperatureiec60216-1(°c)',
 'continuoususetemperature',
 'continuousallowableservicetemperatureinair',
 'maxservicetemperature',
 'minservicetemperature',
 'servicetemperaturelongterm',
 'servicetemperatureshortterm',
 'cut',
 'temperatureresistance',
 'minimumoperatingtemperature',
 'continuousutilizationtemperature',
 'densityiso1183(kg/m³)',
 'dense',
 'heavy',
 'heavyweight',
 'specificgravity',
 'tangentdelta',
 'tandelta',
 'df',
 'dielectricdissipationfactor',
 'dielectricdissipation',
 'lossangle',
 'losstangent',
 'dissipationfactoriec62631-2-1100hz(e-4)',
 'dissipationfactor100hz',
 'tangentdeltaat100hz',
 'tangentdelta,100hz',
 'tandelta100hz',
 'tandeltaat100hz',
 'df100hz',
 '100hzdf',
 'dielectricdissipationfactorat100hz',
 'dielectricdissipationfactor,100hz',
 'dielectricdissipation100hz',
 'dielectricdissipationat100hz',
 'lossangleat100hz',
 'lossangle100hz',
 'losstangent100hz',
 'losstangentat100hz',
 'dissipationfactoriec62631-2-11mhz(e-4)',
 'dissipationfactor1mhz',
 'tangentdeltaat1mhz',
 'tangentdelta,1mhz',
 'tandelta1mhz',
 'tandeltaat1mhz',
 'df1mhz',
 '1mhzdf',
 'dielectricdissipationfactorat1mhz',
 'dielectricdissipationfactor,1mhz',
 'dielectricdissipation1mhz',
 'dielectricdissipationat1mhz',
 'lossangleat1mhz',
 'lossangle1mhz',
 'losstangent1mhz',
 'losstangentat1mhz',
 'effectivethermaldiffusivityiso22007-4crossflow(m²/s)',
 'effectivethermaldiffusivity,crossflowdirection',
 'effectivethermaldiffusivityiso22007-4flow(m²/s)',
 'effectivethermaldiffusity,flowdirection',
 'inplanethermaldiffusivity',
 'effectivethermaldiffusivityiso22007-4throughplane(m²/s)',
 'effectivethermaldiffusivity,throughplanedirection',
 'throughplanethermaldiffusivity',
 'crossplanethermaldiffusivity',
 'electricstrengthiec60243-1(kv/mm)',
 'acelectristrength',
 'acdielectricstrength',
 'ac',
 'elongationatbreakiso527-1/-2oriso37perpendicular(%)',
 'elongationatbreak,perpendicular',
 'perpendicularelongationatbreak',
 'perpendicularbreakstrain',
 'elongationalstressfiso21304-2150/10(mpa)',
 'fiberarealweight(g/m²)',
 'fibervolumecontentiso11667(%)',
 'flexmodulus',
 'flexmod',
 'flexuralmodulusofelasticity',
 'flexuralperformance',
 'rigid',
 'rigidity',
 'bendstrength',
 'flexibility',
 'flexible',
 'flex',
 'flexuralmodulusastmd790tape0°(mpa)',
 'tapeflexmodulus',
 'flexuralelongationatbreak',
 'failureflexstrain',
 'flexuralstrainatfailureastmd790tape0°(%)',
 'flexuralstrainatfailure,tape',
 'tapeflexstrainfailure',
 'flexstr',
 'flexstress',
 'flexuralstrengthastmd790tape0°(mpa)',
 'tapeflexstr',
 'tapeflexstress',
 'flexuralstressat3.5%iso178(mpa)',
 'flexstressat3.5%elongation',
 'flexstrat3.5%strain',
 'glasstransitiontemperatureiso11357-1/-310°c/min(°c)',
 'glasstransition',
 'tg',
 'rockwellhardness',
 'hardness,rockwelliso2039-2m-scale',
 'hardness,rockwellm-scale',
 'rockwellhardnessm-scale',
 'rockwell,m',
 'hardnessrockwellm',
 'hardness,rockwelliso2039-2r-scale',
 'hardness,rockwellr-scale',
 'rockwellhardnessr-scale',
 'rockwell,r',
 'hardnessrockwellr',
 'humidityabsorptionsim.toiso622mm(%)',
 'humid',
 'humidity',
 'intrinsicviscosityiso307,1628',
 'η',
 'intrvisc',
 'izodimpact',
 'impactizod',
 'izodunnotched',
 'izodunnotch',
 'unnotchedizod',
 'unnotchizod',
 'izodunnotchedimpact',
 'izodunnotchimpact',
 'unnotchedizodimpact',
 'unnotchizodimpact',
 'izodimpactstrengthunnotched',
 'izodimpactstrengthunnotch',
 'izodimpactstrength(unnotched)',
 'izodimpactstrength(unnotch)',
 'izodimpactunnotched',
 'izodimpactunnotch',
 'izodimpact(unnotched)',
 'izodimpact(unnotch)',
 'izodnotched',
 'izodnotch',
 'notchedizod',
 'notchizod',
 'izodnotchedimpact',
 'izodnotchimpact',
 'notchedizodimpact',
 'notchizodimpact',
 'izodimpactstrengthnotched',
 'izodimpactstrengthnotch',
 'izodimpactstrength(notched)',
 'izodimpactstrength(notch)',
 'izodimpactnotched',
 'izodimpactnotch',
 'izodimpact(notched)',
 'izodimpact(notch)',
 'meltmass-flowrateiso1133(g/10min)',
 'meltmassflowrate',
 'meltflowrate',
 'mfr',
 'flowrate',
 'meltindex',
 'meltflowindex',
 'mfi',
 'flow',
 'mi',
 'meltvolume-flowrateiso1133(cm³/10min)',
 'meltvolumeflowrate',
 'meltvolumerate',
 'mvr',
 'meltvolume',
 'mv',
 'meltingtemperatureiso11357-1/-310°c/min(°c)',
 'melttemp',
 'dscmeltingtemp',
 'mp',
 'mouldingshrinkage',
 'moldshrinkage',
 'mold-shrinkage',
 'mouldshrinkage',
 'dimensional,precise',
 'dimensionalprecision',
 'moldshrinkage(md/td)',
 'moldingshrinkageiso294-4,2577normal(%)',
 'moldingshrinkage,normal',
 'moldshrinkage(x-flow)',
 'moldshrinkage(td)',
 'moldshrinkagenormal',
 'moldshrinkage(transversedirection)',
 'mold-shrinkage,normal',
 'mouldshrinkagenormal',
 'mould-shrinkage',
 'mould-shrinkage,normal',
 'moldingshrinkageiso294-4,2577parallel(%)',
 'moldingshrinkage,parallel',
 'moldshrinkage(flow)',
 'moldshrinkage(md)',
 'moldshrinkageflow',
 'moldshrinkagemachinedirection',
 'moldshrinkagemd',
 'moldshrinkageparallel',
 'mold-shrinkage,parallel',
 'mouldshrinkageparallel',
 'mould-shrinkage,parallel',
 'nominalstrainatbreakiso527-1/-2(%)',
 'nominalelongationatbreak',
 'nominalbreakstrain',
 'nominalbreakelongation',
 'nominalstrain,break',
 'nominalelongation',
 'break',
 'oxygenindexiso4589-1/-2(%)',
 'loi',
 'limitingoxygen',
 'poissonsratio',
 'puncture-maximumforceiso6603-223°c(n)',
 'puncturemaximumforce',
 'maximumpunctureforce',
 'dk',
 'dielectricfactor',
 'dielectricloss',
 'relativepermittivityiec62631-2-1100hz',
 'relativepermittivityat100hz',
 'dkat100hz',
 'dielectricfactorat100hz',
 'dielectriclossat100hz',
 '100hzdk',
 'relativepermittivity100hz',
 'dk100hz',
 'dielectricfactor100hz',
 'dielectricloss100hz',
 'relativepermittivityiec62631-2-11mhz',
 'relativepermittivityat1mhz',
 'dkat1mhz',
 'dielectricfactorat1mhz',
 'dielectriclossat1mhz',
 '1mhzdk',
 'relativepermittivity1mhz',
 'dk1mhz',
 'dielectricfactor1mhz',
 'dielectricloss1mhz',
 'relativepermittivityiec62631-2-160hz',
 'relativepermittivityat60hz',
 'dkat60hz',
 'dielectricfactorat60hz',
 'dielectriclossat60hz',
 '60hzdk',
 'relativepermittivity60hz',
 'dk60hz',
 'dielectricfactor60hz',
 'dielectricloss60hz',
 'shoreahardnessiso48-4/iso86815s',
 'shorea',
 'sha',
 'durometerhardness(a)',
 'durometerhardness(shorea)',
 'a',
 'soft',
 'hardness,shoreaiso48-4/iso86815s',
 'shoredhardnessiso48-4/iso86815s',
 'shored',
 'shd',
 'durometerhardness(d)',
 'durometerhardness(shored)',
 'd',
 'hardness,shorediso48-4/iso86815s',
 'shorehardness',
 'durometerhardness',
 'specificheatcapacityofmeltiso22007-4(j/(kgk))',
 'surfaceresistivityiec62631-3-2(ohm)',
 'surf_res',
 'sr',
 'tapearealweight(g/m²)',
 'tapethicknessiso16012(mm)',
 'tapewidthiso16012(mm)',
 'tearstrengthiso34-1normal(kn/m)',
 'tearstress',
 'burststrength',
 'temp.ofdeflectionunderload',
 'dtul',
 'hdt',
 'deflectiontemperature',
 'temperatureofdeflectionunderloadiso75-1/-20.45mpa(°c)',
 'temperatureofdeflectionunderload0.45mpa',
 'temp.ofdeflectionunderload0.45mpa',
 'deflectiontemperature0.45mpa',
 'deflectiontemperature66psi',
 'hdt0.45mpa',
 'temp.ofdeflectionunderload65psiannealed',
 'dtul0.45mpa',
 'temperatureofdeflectionunderloadiso75-1/-21.8mpa(°c)',
 'temperatureofdeflectionunderload1.80mpa',
 'temp.ofdeflectionunderload1.80mpa',
 'deflectiontemperature1.8mpa',
 'deflectiontemperature264psi',
 'hdt1.8mpa',
 'temp.ofdeflectionunderload260psiannealed',
 'dtul1.8mpa',
 'temperatureofdeflectionunderloadiso75-1/-28mpa(°c)',
 'temperatureofdeflectionunderload8.0mpa',
 'temp.ofdeflectionunderload8.0mpa',
 'deflectiontemperature8.0mpa',
 'hdt8.0mpa',
 'dtul8.0mpa',
 'tensilecreepmodulusiso899-11000h(mpa)',
 'tensilecreepmodulusat1000h',
 'tensilecreepmodulusiso899-11h(mpa)',
 'tensilecreepmodulusat1h',
 'youngmodulus',
 "young'smodulus",
 'stiff',
 'tenmod',
 'e-modulus',
 'emodulus',
 'modulusofelasticity',
 'tensilemod',
 "tensileyoung'smodulus",
 'youngsemodulus',
 'youngsmodulus',
 'emod',
 'e-mod',
 'tensilemodule',
 'stiffness',
 'mechanicalstrength',
 'mechanicalbehavior',
 'mechanicalresistance',
 'mechanicalproperties',
 'deformation',
 'deformationstability',
 'mechanicalperformance',
 'elasticmodulus',
 'strengthmodulus',
 'tensilemodulusastmd3039mtape0°(mpa)',
 'tapetensilemod',
 'tapemodulusofelasticity',
 'tapeemodulus',
 'tensilenotchedimpactstrengthiso8256/123°c(kj/m²)',
 'tensileimpactnotched',
 'ntenileimpact',
 'breakstrain,breakelongation',
 'elongationbreak',
 'tensilestrainatbreakiso527-1/-250mm/min(%)',
 'tensilestrainatbreak50mm/min',
 'strainatbreak50mm/min',
 'strainbreak50mm/min',
 'breakstrain50mm/min',
 'elongationatbreak50mm/min',
 'elongationbreak50mm/min',
 'breakelongation50mm/min',
 'tensilestrainatbreakiso527-1/-25mm/min(%)',
 'tensilestrainatbreak5mm/min',
 'strainatbreak5mm/min',
 'strainbreak5mm/min',
 'breakstrain5mm/min',
 'elongationatbreak5mm/min',
 'elongationbreak5mm/min',
 'breakelongation5mm/min',
 'tensilestrainatfailureastmd3039mtape0°(%)',
 'tensilestrainatyieldiso527-1/-250mm/min(%)',
 'tensilestrainatyield50mm/min',
 'strainatyield50mm/min',
 'strainyield50mm/min',
 'yieldstrain50mm/min',
 'yieldstrain',
 'strainatyield',
 'elongationatyield50mm/min',
 'elongationyield50mm/min',
 'yieldelongation50mm/min',
 'yieldelongation',
 'elongationatyield',
 'strainyield',
 'tensilestrengthastmd3039mtape0°(mpa)',
 'tensilestrengthtape',
 'tapetensilestrength',
 'tensilestressat100%elongationiso37perpendicular(mpa)',
 'tensilestressat100%elongation,perpendicular',
 'tensilestressat100%strain,perpendicular',
 'tensilestressat100%deformation,perpendicular',
 'perpendiculartensilestressat100%elongation',
 'perpendiculartensilestressat100%strain',
 'perpendiculartensilestressat100%deformation',
 'tensilestressat100%strainiso527-1/-2(mpa)',
 'stressat100%deformation',
 'tensilestressat50%strainiso527-1/-2(mpa)',
 'stressat50%elongation',
 'stressat50%deformation',
 'strebr',
 'tensilestrengthatbreak',
 'tensilestress(break)',
 'breakstress',
 'tenstressbrk',
 'tensilestressatbreakiso527-1/-250mm/min(mpa)',
 'tensilestressatbreakat50mm/min',
 'strebrat50mm/min',
 'tensilestrengthatbreakat50mm/min',
 'tensilestress(break)at50mm/min',
 'breakstressat50mm/min',
 'tenstressbrkat50mm/min',
 'tensilestressatbreakiso527-1/-25mm/min(mpa)',
 'tensilestressatbreakat5mm/min',
 'strebrat5mm/min',
 'tensilestrengthatbreakat5mm/min',
 'tensilestress(break)at5mm/min',
 'breakstressat5mm/min',
 'tenstressbrkat5mm/min',
 'tensilestressatbreakiso527-1/-2oriso37perpendicular(mpa)',
 'tensilestressatbreakperpendicular',
 'perpendicularstressatbreak',
 'perpendicularbreakstress',
 'tensilestressatyieldiso527-1/-250mm/min(mpa)',
 'tensilestressatyield50mm/min',
 'tensilestrength(yield)',
 'tensilestrengthatyield',
 'tensilestress(yield)',
 'yieldstress',
 'thermalconductive',
 'heattransfer',
 'thermalconductivityiso22007-2crossflow(w/(mk))',
 'thermalconductivitycrossflowdirection',
 'crossplanethermalconductivity',
 'thermalconductivityiso22007-2flow(w/(mk))',
 'thermalconductivityflowdirection',
 'inplanethermalconductivity',
 'thermalconductivityofmelt',
 'thermalconductivityiso22007-2throughplane(w/(mk))',
 'thermalconductivitythroughplane',
 'thermalconductivitythruplanedirection',
 'thruplanethermalconductivity',
 'vicat',
 'vicatsofteningpoint',
 'vicatsoftingtemp',
 'vicatsofteningtemperatureiso30650°c/h10n(°c)',
 'vicatsofteningtemperatureat50°c/h10n',
 'vicatat50°c/h10n',
 'vicatsofteningpointat50°c/h10n',
 'vicatsoftingtempat50°c/h10n',
 'vicatsofteningtemperatureiso30650°c/h50n(°c)',
 'vicatsofteningtemperatureat50°c/h50n',
 'vicatat50°c/h50n',
 'vicatsofteningpointat50°c/h50n',
 'vicatsoftingtempat50°c/h50n',
 'viscositynumberiso307,1628(cm³/g)',
 'h2so4',
 'viscositynumber(0.5%in96%h2so4)',
 'vnat0.5%insulfuricacidnominal',
 'viscosityh2so4',
 'volumeresistivityiec62631-3-1(ohm.m)',
 'volres',
 'vr',
 'waterabsorptionsim.toiso622mm(%)',
 'h20absorption',
 'water',
 'moistureuptake',
 'moistureabsorption',
 'moistureabsorptionequilibrium23°c/50%r.h.',
 'wearbysandslurrymethod']

#### For Abbreviations

In [110]:
def get_property_abb():
    abrv = random.choice(list(prop_abrv_mapping))
    abrv_meaning = prop_abrv_mapping[abrv]
    value = None
    unit = ""
    exponential = ''
    for i in property_and_values:
        if abrv_meaning == i[0] or abrv_meaning == i[-1]:
            try:    
                value = random.randrange(i[1],i[2])
            except: 
                value = round(random.uniform(i[1], i[2]),2)

            if value > 89999999:
                # print("*"*20, "{:.2e}".format(value))
                float_value = value
                value = "{:.2e}".format(value)
                exponential = 'positive'

            while value==0.0:
                value = round(random.uniform(i[1], i[2]),9)
                # print("$"*20, f"value was 0.0, picking another random number {i[1]} to {i[2]}", value)
                # print("#"*20, "{:.8f}".format(value))
                if -0.99 < value < 0.99:
                    float_value = value
                    value = "{:.2e}".format(value)
                    # value = "{:.8f}".format(value)
                    exponential = 'negative'
                else:
                    value = round(value, 2)
                    
            unit = random.choice([i[3],f" {i[3]}", ""])
            if not unit.strip():
                unit=""
        
            break
            
    if not value:
        # print(f"could not find the value for {abrv_meaning}: {abrv}")
        value = random.randint(20, 200)

    queries = [       
        f"{abrv} of {value}{unit}",
        f"{abrv} {value}{unit}",
        f"{abrv} ({value}{unit})",
        f"{abrv} ={value}{unit}",
        f"{abrv} = {value}{unit}",
        f"{abrv} - {value}{unit}",
        f"{abrv}: {value}{unit}",
        f"{value}{unit} {abrv}",
    ]

    query = random.choice(queries)
    
    if not " " in abrv and not exponential:
        query2 = random.choice([
            f"{abrv}{value}",
            f"{abrv}-{value}",
            f"{value}{abrv}",
            f"{abrv}={value}",
        ])
        is_unit = random.choice([True, True, True, False, False])
        if not is_unit:
            query = query2
            unit = ''
        
    if exponential == 'positive':
        # print("#"*25, 'positive')
        if float_value < 0:
            property_details = {'property_name': abrv_meaning, 'modifier': {'value': "{:.2e}".format(round(float_value, 2)), 'min': "{:.2e}".format(round(float_value*1.1, 2)), 'max': "{:.2e}".format(round(float_value*0.9, 2)), 'unit': unit.strip()}, 'property_type': 'property'}
        else:
            property_details = {'property_name': abrv_meaning, 'modifier': {'value': "{:.2e}".format(round(float_value, 2)), 'min': "{:.2e}".format(round(float_value*0.9, 2)), 'max': "{:.2e}".format(round(float_value*1.1, 2)), 'unit': unit.strip()}, 'property_type': 'property'}
    elif exponential == 'negative':
        print("*"*25, 'negative exponential')
        if float_value < 0:
            property_details = {'property_name': abrv_meaning, 'modifier': {'value': "{:.2e}".format(round(float_value, 9)), 'min': "{:.2e}".format(round(float_value*1.1, 9)), 'max': "{:.2e}".format(round(float_value*0.9, 9)), 'unit': unit.strip()}, 'property_type': 'property'}
        else:
            property_details = {'property_name': abrv_meaning, 'modifier': {'value': "{:.2e}".format(round(float_value, 9)), 'min': "{:.2e}".format(round(float_value*0.9, 9)), 'max': "{:.2e}".format(round(float_value*1.1, 9)), 'unit': unit.strip()}, 'property_type': 'property'}
        print(property_details, query)
    else:
        if value < 0:
            property_details = {'property_name': abrv_meaning, 'modifier': {'value': str(round(value, 2)), 'min': str(round(value*1.1, 2)), 'max': str(round(value*0.9, 2)), 'unit': unit.strip()}, 'property_type': 'property'}
        else:
            property_details = {'property_name': abrv_meaning, 'modifier': {'value': str(round(value, 2)), 'min': str(round(value*0.9, 2)), 'max': str(round(value*1.1, 2)), 'unit': unit.strip()}, 'property_type': 'property'}
    return property_details, query

In [111]:
for i in range(20):
    print(get_property_abb(), "\n")

({'property_name': 'melt mass-flow rate iso 1133 (g/10min)', 'modifier': {'value': '118.77', 'min': '106.89', 'max': '130.65', 'unit': ''}, 'property_type': 'property'}, 'flow 118.77')

({'property_name': 'shore a hardness iso 48-4 / iso 868 15s', 'modifier': {'value': '91.0', 'min': '81.9', 'max': '100.1', 'unit': ''}, 'property_type': 'property'}, 'soft-91.0')

({'property_name': 'melt volume-flow rate iso 1133 (cm³/10min)', 'modifier': {'value': '9.54', 'min': '8.59', 'max': '10.49', 'unit': ''}, 'property_type': 'property'}, 'mv 9.54')

({'property_name': 'glass transition temperature iso 11357-1/-3 10°c/min (°c)', 'modifier': {'value': '-53', 'min': '-58.3', 'max': '-47.7', 'unit': ''}, 'property_type': 'property'}, 'tg--53')

({'property_name': 'melt mass-flow rate iso 1133 (g/10min)', 'modifier': {'value': '195.14', 'min': '175.63', 'max': '214.65', 'unit': ''}, 'property_type': 'property'}, 'flow195.14')

({'property_name': 'intrinsic viscosity iso 307, 1628', 'modifier': {'value': '1355.82', 'min': '1220.24', 'max': '1491.4', 'unit': ''}, 'property_type': 'property'}, 'η = 1355.82')

({'property_name': 'intrinsic viscosity iso 307, 1628', 'modifier': {'value': '1290.22', 'min': '1161.2', 'max': '1419.24', 'unit': ''}, 'property_type': 'property'}, 'η-1290.22')

({'property_name': 'dissipation factor', 'modifier': {'value': '425', 'min': '382.5', 'max': '467.5', 'unit': ''}, 'property_type': 'property'}, 'df 425')

({'property_name': 'surface resistivity iec 62631-3-2 (ohm)', 'modifier': {'value': '1.24e+15', 'min': '1.12e+15', 'max': '1.37e+15', 'unit': 'ohm'}, 'property_type': 'property'}, '1.24e+15ohm sr')

({'property_name': 'melt volume-flow rate iso 1133 (cm³/10min)', 'modifier': {'value': '11.24', 'min': '10.12', 'max': '12.36', 'unit': 'cm³/10min'}, 'property_type': 'property'}, 'mv of 11.24 cm³/10min')

({'property_name': "average molecular weight margolies' equation (g/mol)", 'modifier': {'value': '8691296', 'min': '7822166.4', 'max': '9560425.6', 'unit': 'g/mol'}, 'property_type': 'property'}, '8691296g/mol mw')

({'property_name': 'surface resistivity iec 62631-3-2 (ohm)', 'modifier': {'value': '6.07e+16', 'min': '5.46e+16', 'max': '6.68e+16', 'unit': 'ohm'}, 'property_type': 'property'}, '6.07e+16 ohm sr')

({'property_name': 'coefficient of linear thermal expansion (clte)', 'modifier': {'value': '57', 'min': '51.3', 'max': '62.7', 'unit': 'e-6/k'}, 'property_type': 'property'}, '57 e-6/k clte')

({'property_name': 'volume resistivity iec 62631-3-1 (ohm.m)', 'modifier': {'value': '1.96e+16', 'min': '1.76e+16', 'max': '2.15e+16', 'unit': 'ohm.m'}, 'property_type': 'property'}, 'vr - 1.96e+16 ohm.m')

({'property_name': 'shore d hardness iso 48-4 / iso 868 15s', 'modifier': {'value': '68', 'min': '61.2', 'max': '74.8', 'unit': ''}, 'property_type': 'property'}, 'sh d - 68')

({'property_name': 'shore a hardness iso 48-4 / iso 868 15s', 'modifier': {'value': '91.0', 'min': '81.9', 'max': '100.1', 'unit': ''}, 'property_type': 'property'}, 'a = 91.0')

({'property_name': 'volume resistivity iec 62631-3-1 (ohm.m)', 'modifier': {'value': '1.83e+16', 'min': '1.65e+16', 'max': '2.01e+16', 'unit': ''}, 'property_type': 'property'}, '1.83e+16 vr')

({'property_name': 'shore d hardness iso 48-4 / iso 868 15s', 'modifier': {'value': '33', 'min': '29.7', 'max': '36.3', 'unit': ''}, 'property_type': 'property'}, 'sh d: 33')

({'property_name': 'intrinsic viscosity iso 307, 1628', 'modifier': {'value': '763.8', 'min': '687.42', 'max': '840.18', 'unit': ''}, 'property_type': 'property'}, 'η of 763.8')

({'property_name': 'electric strength iec 60243-1 (kv/mm)', 'modifier': {'value': '11.53', 'min': '10.38', 'max': '12.68', 'unit': ''}, 'property_type': 'property'}, 'ac11.53')

C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_6740\1632742568.py:10: DeprecationWarning: randrange() will raise TypeError in the future
  value = random.randrange(i[1],i[2])

In [112]:
prop_syn_mapping = {}
for i in property_and_values:
    prop_syn_mapping[i[-1]] = i[0]

prop_syn_mapping

{'shore a hardness': 'shore a hardness iso 48-4 / iso 868 15s',
 'electric strength': 'electric strength iec 60243-1 (kv/mm)',
 'intrinsic viscosity': 'intrinsic viscosity iso 307, 1628',
 'vicat softening temperature': 'vicat softening temperature',
 'relative permittivity': 'relative permittivity',
 'tensile strain at failure': 'tensile strain at failure astm d 3039 m tape 0° (%)',
 'wear by sandslurry method (based on gur 4120=100)': 'wear by sandslurry method (based on gur 4120=100)',
 'tensile stress at 100% elongation': 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
 'izod notched impact strength': 'izod notched impact strength',
 'stress at break': 'stress at break iso 527-1/-2 (mpa)',
 'tensile strain at break': 'tensile strain at break',
 'puncture energy': 'puncture energy',
 'tensile creep modulus': 'tensile creep modulus',
 'fiber volume content': 'fiber volume content iso 11667 (%)',
 'izod impact strength': 'izod impact strength',
 'oxygen index': 'oxygen index iso 4589-1/-2 (%)',
 'shore d hardness': 'shore d hardness iso 48-4 / iso 868 15s',
 'effective thermal diffusivity': 'effective thermal diffusivity',
 'surface resistivity': 'surface resistivity iec 62631-3-2 (ohm)',
 'tensile strain at yield': 'tensile strain at yield iso 527-1/-2 50mm/min (%)',
 'flexural strength': 'flexural strength',
 'ball indentation hardness': 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'flexural modulus': 'flexural modulus',
 'tensile stress at yield': 'tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
 'tape thickness': 'tape thickness iso 16012 (mm)',
 'density': 'density iso 1183 (kg/m³)',
 'dissipation factor': 'dissipation factor',
 'tensile stress at 50% strain': 'tensile stress at 50% strain iso 527-1/-2 (mpa)',
 'tensile stress at 100% strain': 'tensile stress at 100% strain iso 527-1/-2 (mpa)',
 'average molecular weight': "average molecular weight margolies' equation (g/mol)",
 'stress at 10% elongation': 'stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
 'continuous service temperature': 'continuous service temperature iec 60216-1 (°c)',
 'tensile notched impact strength': 'tensile notched impact strength iso 8256/1 23°c (kj/m²)',
 'tensile stress at break': 'tensile stress at break',
 'water absorption': 'water absorption sim. to iso 62 2mm (%)',
 'compression set': 'compression set',
 'fiber areal weight': 'fiber areal weight (g/m²)',
 'charpy impact strength': 'charpy impact strength',
 'molding shrinkage': 'molding shrinkage',
 'temperature of deflection under load': 'temperature of deflection under load',
 'charpy double notched impact strength': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'melt volume-flow rate': 'melt volume-flow rate iso 1133 (cm³/10min)',
 'elongational stress f': 'elongational stress f iso 21304-2 150/10 (mpa)',
 'thermal conductivity': 'thermal conductivity',
 'hardness, rockwell': 'hardness, rockwell',
 'compressive strength': 'compressive strength iso 604 (mpa)',
 'tensile strength': 'tensile strength astm d 3039 m tape 0° (mpa)',
 'puncture - maximum force': 'puncture - maximum force iso 6603-2 23°c (n)',
 'volume resistivity': 'volume resistivity iec 62631-3-1 (ohm.m)',
 'charpy notched impact strength': 'charpy notched impact strength',
 'specific heat capacity of melt': 'specific heat capacity of melt iso 22007-4 (j/(kg k))',
 "poisson's ratio": "poisson's ratio",
 'flexural stress at 3.5%': 'flexural stress at 3.5% iso 178 (mpa)',
 'viscosity number': 'viscosity number iso 307, 1628 (cm³/g)',
 'flexural strain at failure': 'flexural strain at failure',
 'glass transition temperature': 'glass transition temperature iso 11357-1/-3 10°c/min (°c)',
 'nominal strain at break': 'nominal strain at break iso 527-1/-2 (%)',
 'tensile modulus': 'tensile modulus',
 'average particle size': 'average particle size laser scattering d50 (µm)',
 'ball pressure test': 'ball pressure test iec 60695-10-2 (°c)',
 'compressive modulus': 'compressive modulus iso 604 (mpa)',
 'melt mass-flow rate': 'melt mass-flow rate iso 1133 (g/10min)',
 'elongation at break': 'tensile strain at break',
 'melting temperature': 'melting temperature iso 11357-1/-3 10°c/min (°c)',
 'tear strength': 'tear strength iso 34-1 normal (kn/m)',
 'coefficient of linear thermal expansion (clte)': 'coefficient of linear thermal expansion (clte)',
 'tape areal weight': 'tape areal weight (g/m²)',
 'humidity absorption': 'humidity absorption sim. to iso 62 2mm (%)',
 'bulk density': 'bulk density iso 60 (kg/m³)',
 'tape width': 'tape width iso 16012 (mm)',
 'compressive stress at 1% strain': 'compressive stress at 1% strain iso 604 (mpa)',
 'tape tens mod': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tensile mod tape': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tape tensile modulus': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tensile modulus tape': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tensile tape': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tape flex mod': 'flexural modulus astm d 790 tape 0° (mpa)',
 'flex mod tape': 'flexural modulus astm d 790 tape 0° (mpa)',
 'tape flexural modulus': 'flexural modulus astm d 790 tape 0° (mpa)',
 'flexural modulus tape': 'flexural modulus astm d 790 tape 0° (mpa)',
 'tape flex strength': 'flexural strength astm d 790 tape 0° (mpa)',
 'flex strength tape': 'flexural strength astm d 790 tape 0° (mpa)',
 'tape flexural strength': 'flexural strength astm d 790 tape 0° (mpa)',
 'flexural strength tape': 'flexural strength astm d 790 tape 0° (mpa)',
 "average molecular weight margolies' equation (g/mol)": "average molecular weight margolies' equation (g/mol)",
 'average molar mass': "average molecular weight margolies' equation (g/mol)",
 'average molecular mass': "average molecular weight margolies' equation (g/mol)",
 'avermw': "average molecular weight margolies' equation (g/mol)",
 'molecular weight': "average molecular weight margolies' equation (g/mol)",
 'mw': "average molecular weight margolies' equation (g/mol)",
 'average particle size laser scattering d50 (µm)': 'average particle size laser scattering d50 (µm)',
 'avg. particle size': 'average particle size laser scattering d50 (µm)',
 'avpartsize': 'average particle size laser scattering d50 (µm)',
 'particle size': 'average particle size laser scattering d50 (µm)',
 'particle size d50': 'average particle size laser scattering d50 (µm)',
 'ball indentation hardness iso 2039-1 h 358/30 (mpa)': 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'ball indention hardness': 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'ball pressure test iec 60695-10-2 (°c)': 'ball pressure test iec 60695-10-2 (°c)',
 'bulk density iso 60 (kg/m³)': 'bulk density iso 60 (kg/m³)',
 'apparent (bulk) density': 'bulk density iso 60 (kg/m³)',
 'apparent density': 'bulk density iso 60 (kg/m³)',
 'bulkdens': 'bulk density iso 60 (kg/m³)',
 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy impact strength (double notched)': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy impact strength (double notch)': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notch charpy impact strength': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notched charpy impact strength': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notch charpy': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notched charpy': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notch impact': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notched impact': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy double notch': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy double notched': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy impact': 'charpy impact strength',
 'impact charpy': 'charpy impact strength',
 'charpy unnotched': 'charpy impact strength',
 'charpy unnotch': 'charpy impact strength',
 'unnotched charpy': 'charpy impact strength',
 'unnotch charpy': 'charpy impact strength',
 'charpy unnotched impact': 'charpy impact strength',
 'charpy unnotch impact': 'charpy impact strength',
 'unnotched charpy impact': 'charpy impact strength',
 'unnotch charpy impact': 'charpy impact strength',
 'charpy impact strength unnotched': 'charpy impact strength',
 'charpy impact strength unnotch': 'charpy impact strength',
 'charpy impact strength (unnotched)': 'charpy impact strength',
 'charpy impact strength (unnotch)': 'charpy impact strength',
 'charpy impact unnotched': 'charpy impact strength',
 'charpy impact unnotch': 'charpy impact strength',
 'charpy impact (unnotched)': 'charpy impact strength',
 'charpy impact (unnotch)': 'charpy impact strength',
 'charpy notched': 'charpy notched impact strength',
 'charpy notch': 'charpy notched impact strength',
 'notched charpy': 'charpy notched impact strength',
 'notch charpy': 'charpy notched impact strength',
 'charpy notched impact': 'charpy notched impact strength',
 'charpy notch impact': 'charpy notched impact strength',
 'notched charpy impact': 'charpy notched impact strength',
 'notch charpy impact': 'charpy notched impact strength',
 'charpy impact strength notched': 'charpy notched impact strength',
 'charpy impact strength notch': 'charpy notched impact strength',
 'charpy impact strength (notched)': 'charpy notched impact strength',
 'charpy impact strength (notch)': 'charpy notched impact strength',
 'charpy impact notched': 'charpy notched impact strength',
 'charpy impact notch': 'charpy notched impact strength',
 'charpy impact (notched)': 'charpy notched impact strength',
 'charpy impact (notch)': 'charpy notched impact strength',
 'coefficient of linear thermal expansion': 'coefficient of linear thermal expansion (clte)',
 'clte': 'coefficient of linear thermal expansion (clte)',
 'linear expansion factor': 'coefficient of linear thermal expansion (clte)',
 'thermal expansion': 'coefficient of linear thermal expansion (clte)',
 'linear thermal expansion': 'coefficient of linear thermal expansion (clte)',
 'coef. of lin. therm expansion': 'coefficient of linear thermal expansion (clte)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'linear expansion factor (normal)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'normal thermal expansion': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'normal linear thermal expansion': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'coef. of lin. therm expansion normal': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'clte (transverse direction)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'linear expansion factor (parallel)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'parallel thermal expansion': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'parallel linear thermal expansion': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'coef. of lin. therm expansion parallel': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'clte (flow direction)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'compression set iso 815 23°c (%)': 'compression set iso 815 23°c (%)',
 'compression set at 23c': 'compression set iso 815 23°c (%)',
 'compression set iso 815 23°c, 24h (%)': 'compression set iso 815 23°c, 24h (%)',
 'compression set at 23c, 24h': 'compression set iso 815 23°c, 24h (%)',
 'compressive modulus iso 604 (mpa)': 'compressive modulus iso 604 (mpa)',
 'compressive module': 'compressive modulus iso 604 (mpa)',
 'comp mod': 'compressive modulus iso 604 (mpa)',
 'compressive strength iso 604 (mpa)': 'compressive strength iso 604 (mpa)',
 'compressive stress': 'compressive strength iso 604 (mpa)',
 'compressive stress at 1% strain iso 604 (mpa)': 'compressive stress at 1% strain iso 604 (mpa)',
 'compressive strength at 1% strain': 'compressive stress at 1% strain iso 604 (mpa)',
 'compressive stress 1% deformation': 'compressive stress at 1% strain iso 604 (mpa)',
 'compressive strength at 1% deformation': 'compressive stress at 1% strain iso 604 (mpa)',
 'continuous service temperature iec 60216-1 (°c)': 'continuous service temperature iec 60216-1 (°c)',
 'continuous use temperature': 'continuous service temperature iec 60216-1 (°c)',
 'continuous allowable service temperature in air': 'continuous service temperature iec 60216-1 (°c)',
 'max service temperature': 'continuous service temperature iec 60216-1 (°c)',
 'min service temperature': 'continuous service temperature iec 60216-1 (°c)',
 'service temperature long term': 'continuous service temperature iec 60216-1 (°c)',
 'service temperature short term': 'continuous service temperature iec 60216-1 (°c)',
 'cut': 'continuous service temperature iec 60216-1 (°c)',
 'temperature resistance': 'continuous service temperature iec 60216-1 (°c)',
 'minimum operating temperature': 'continuous service temperature iec 60216-1 (°c)',
 'continuous utilization temperature': 'continuous service temperature iec 60216-1 (°c)',
 'density iso 1183 (kg/m³)': 'density iso 1183 (kg/m³)',
 'dense': 'density iso 1183 (kg/m³)',
 'heavy': 'density iso 1183 (kg/m³)',
 'heavy weight': 'density iso 1183 (kg/m³)',
 'specific gravity': 'density iso 1183 (kg/m³)',
 'tangent delta': 'dissipation factor',
 'tan delta': 'dissipation factor',
 'df': 'dissipation factor',
 'dielectric dissipation factor': 'dissipation factor',
 'dielectric dissipation': 'dissipation factor',
 'loss angle': 'dissipation factor',
 'loss tangent': 'dissipation factor',
 'dissipation factor iec 62631-2-1 100hz (e-4)': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dissipation factor 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'tangent delta at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'tangent delta, 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'tan delta 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'tan delta at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'df 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 '100hz df': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dielectric dissipation factor at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dielectric dissipation factor, 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dielectric dissipation 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dielectric dissipation at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'loss angle at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'loss angle 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'loss tangent 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'loss tangent at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dissipation factor iec 62631-2-1 1mhz (e-4)': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dissipation factor 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'tangent delta at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'tangent delta, 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'tan delta 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'tan delta at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'df 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 '1mhz df': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dielectric dissipation factor at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dielectric dissipation factor, 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dielectric dissipation 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dielectric dissipation at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'loss angle at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'loss angle 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'loss tangent 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'loss tangent at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)': 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)',
 'effective thermal diffusivity, crossflow direction': 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)',
 'effective thermal diffusivity iso 22007-4 flow (m²/s)': 'effective thermal diffusivity iso 22007-4 flow (m²/s)',
 'effective thermal diffusity, flow direction': 'effective thermal diffusivity iso 22007-4 flow (m²/s)',
 'in plane thermal diffusivity': 'effective thermal diffusivity iso 22007-4 flow (m²/s)',
 'effective thermal diffusivity iso 22007-4 through plane (m²/s)': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'effective thermal diffusivity, through plane direction': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'through plane thermal diffusivity': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'cross plane thermal diffusivity': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'electric strength iec 60243-1 (kv/mm)': 'electric strength iec 60243-1 (kv/mm)',
 'ac electristrength': 'electric strength iec 60243-1 (kv/mm)',
 'ac dielectric strength': 'electric strength iec 60243-1 (kv/mm)',
 'ac': 'electric strength iec 60243-1 (kv/mm)',
 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'elongation at break, perpendicular': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'perpendicular elongation at break': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'perpendicular break strain': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'elongational stress f iso 21304-2 150/10 (mpa)': 'elongational stress f iso 21304-2 150/10 (mpa)',
 'fiber areal weight (g/m²)': 'fiber areal weight (g/m²)',
 'fiber volume content iso 11667 (%)': 'fiber volume content iso 11667 (%)',
 'flex modulus': 'flexural modulus',
 'flex mod': 'flexural modulus',
 'flexural modulus of elasticity': 'flexural modulus',
 'flexural performance': 'flexural modulus',
 'rigid': 'flexural modulus',
 'rigidity': 'flexural modulus',
 'bend strength': 'flexural modulus',
 'flexibility': 'flexural modulus',
 'flexible': 'flexural modulus',
 'flex': 'flexural modulus',
 'flexural modulus astm d 790 tape 0° (mpa)': 'flexural modulus astm d 790 tape 0° (mpa)',
 'tape flex modulus': 'flexural modulus astm d 790 tape 0° (mpa)',
 'flexural elongation at break': 'flexural strain at failure',
 'failure flex strain': 'flexural strain at failure',
 'flexural strain at failure astm d 790 tape 0° (%)': 'flexural strain at failure astm d 790 tape 0° (%)',
 'flexural strain at failure, tape': 'flexural strain at failure astm d 790 tape 0° (%)',
 'tape flex strain failure': 'flexural strain at failure astm d 790 tape 0° (%)',
 'flex str': 'flexural strength',
 'flex stress': 'flexural strength',
 'flexural strength astm d 790 tape 0° (mpa)': 'flexural strength astm d 790 tape 0° (mpa)',
 'tape flex str': 'flexural strength astm d 790 tape 0° (mpa)',
 'tape flex stress': 'flexural strength astm d 790 tape 0° (mpa)',
 'flexural stress at 3.5% iso 178 (mpa)': 'flexural stress at 3.5% iso 178 (mpa)',

In [113]:
prop_abrv_mapping
for k, v in prop_abrv_mapping.items():
    prop_syn_mapping[k] = v
    print(k, ":", v)

mw : average molecular weight margolies' equation (g/mol)
clte : coefficient of linear thermal expansion (clte)
cut : continuous service temperature iec 60216-1 (°c)
df : dissipation factor
ac : electric strength iec 60243-1 (kv/mm)
flex : flexural modulus
tg : glass transition temperature iso 11357-1/-3 10°c/min (°c)
η : intrinsic viscosity iso 307, 1628
mfr : melt mass-flow rate iso 1133 (g/10min)
mfi : melt mass-flow rate iso 1133 (g/10min)
flow : melt mass-flow rate iso 1133 (g/10min)
mvr : melt volume-flow rate iso 1133 (cm³/10min)
mv : melt volume-flow rate iso 1133 (cm³/10min)
mp : melting temperature iso 11357-1/-3 10°c/min (°c)
loi : oxygen index iso 4589-1/-2 (%)
dk : relative permittivity
sh a : shore a hardness iso 48-4 / iso 868 15s
a : shore a hardness iso 48-4 / iso 868 15s
soft : shore a hardness iso 48-4 / iso 868 15s
sh d : shore d hardness iso 48-4 / iso 868 15s
d : shore d hardness iso 48-4 / iso 868 15s
dtul : temperature of deflection under load
hdt : temperature of deflection under load
emod : tensile modulus
vr : volume resistivity iec 62631-3-1 (ohm.m)
mi : melt mass-flow rate iso 1133 (g/10min)
sr : surface resistivity iec 62631-3-2 (ohm)

In [114]:
prop_syn_mapping

{'shore a hardness': 'shore a hardness iso 48-4 / iso 868 15s',
 'electric strength': 'electric strength iec 60243-1 (kv/mm)',
 'intrinsic viscosity': 'intrinsic viscosity iso 307, 1628',
 'vicat softening temperature': 'vicat softening temperature',
 'relative permittivity': 'relative permittivity',
 'tensile strain at failure': 'tensile strain at failure astm d 3039 m tape 0° (%)',
 'wear by sandslurry method (based on gur 4120=100)': 'wear by sandslurry method (based on gur 4120=100)',
 'tensile stress at 100% elongation': 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
 'izod notched impact strength': 'izod notched impact strength',
 'stress at break': 'stress at break iso 527-1/-2 (mpa)',
 'tensile strain at break': 'tensile strain at break',
 'puncture energy': 'puncture energy',
 'tensile creep modulus': 'tensile creep modulus',
 'fiber volume content': 'fiber volume content iso 11667 (%)',
 'izod impact strength': 'izod impact strength',
 'oxygen index': 'oxygen index iso 4589-1/-2 (%)',
 'shore d hardness': 'shore d hardness iso 48-4 / iso 868 15s',
 'effective thermal diffusivity': 'effective thermal diffusivity',
 'surface resistivity': 'surface resistivity iec 62631-3-2 (ohm)',
 'tensile strain at yield': 'tensile strain at yield iso 527-1/-2 50mm/min (%)',
 'flexural strength': 'flexural strength',
 'ball indentation hardness': 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'flexural modulus': 'flexural modulus',
 'tensile stress at yield': 'tensile stress at yield iso 527-1/-2 50mm/min (mpa)',
 'tape thickness': 'tape thickness iso 16012 (mm)',
 'density': 'density iso 1183 (kg/m³)',
 'dissipation factor': 'dissipation factor',
 'tensile stress at 50% strain': 'tensile stress at 50% strain iso 527-1/-2 (mpa)',
 'tensile stress at 100% strain': 'tensile stress at 100% strain iso 527-1/-2 (mpa)',
 'average molecular weight': "average molecular weight margolies' equation (g/mol)",
 'stress at 10% elongation': 'stress at 10% elongation iso 527-1/-2 or iso 37 (mpa)',
 'continuous service temperature': 'continuous service temperature iec 60216-1 (°c)',
 'tensile notched impact strength': 'tensile notched impact strength iso 8256/1 23°c (kj/m²)',
 'tensile stress at break': 'tensile stress at break',
 'water absorption': 'water absorption sim. to iso 62 2mm (%)',
 'compression set': 'compression set',
 'fiber areal weight': 'fiber areal weight (g/m²)',
 'charpy impact strength': 'charpy impact strength',
 'molding shrinkage': 'molding shrinkage',
 'temperature of deflection under load': 'temperature of deflection under load',
 'charpy double notched impact strength': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'melt volume-flow rate': 'melt volume-flow rate iso 1133 (cm³/10min)',
 'elongational stress f': 'elongational stress f iso 21304-2 150/10 (mpa)',
 'thermal conductivity': 'thermal conductivity',
 'hardness, rockwell': 'hardness, rockwell',
 'compressive strength': 'compressive strength iso 604 (mpa)',
 'tensile strength': 'tensile strength astm d 3039 m tape 0° (mpa)',
 'puncture - maximum force': 'puncture - maximum force iso 6603-2 23°c (n)',
 'volume resistivity': 'volume resistivity iec 62631-3-1 (ohm.m)',
 'charpy notched impact strength': 'charpy notched impact strength',
 'specific heat capacity of melt': 'specific heat capacity of melt iso 22007-4 (j/(kg k))',
 "poisson's ratio": "poisson's ratio",
 'flexural stress at 3.5%': 'flexural stress at 3.5% iso 178 (mpa)',
 'viscosity number': 'viscosity number iso 307, 1628 (cm³/g)',
 'flexural strain at failure': 'flexural strain at failure',
 'glass transition temperature': 'glass transition temperature iso 11357-1/-3 10°c/min (°c)',
 'nominal strain at break': 'nominal strain at break iso 527-1/-2 (%)',
 'tensile modulus': 'tensile modulus',
 'average particle size': 'average particle size laser scattering d50 (µm)',
 'ball pressure test': 'ball pressure test iec 60695-10-2 (°c)',
 'compressive modulus': 'compressive modulus iso 604 (mpa)',
 'melt mass-flow rate': 'melt mass-flow rate iso 1133 (g/10min)',
 'elongation at break': 'tensile strain at break',
 'melting temperature': 'melting temperature iso 11357-1/-3 10°c/min (°c)',
 'tear strength': 'tear strength iso 34-1 normal (kn/m)',
 'coefficient of linear thermal expansion (clte)': 'coefficient of linear thermal expansion (clte)',
 'tape areal weight': 'tape areal weight (g/m²)',
 'humidity absorption': 'humidity absorption sim. to iso 62 2mm (%)',
 'bulk density': 'bulk density iso 60 (kg/m³)',
 'tape width': 'tape width iso 16012 (mm)',
 'compressive stress at 1% strain': 'compressive stress at 1% strain iso 604 (mpa)',
 'tape tens mod': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tensile mod tape': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tape tensile modulus': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tensile modulus tape': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tensile tape': 'tensile modulus astm d 3039 m tape 0° (mpa)',
 'tape flex mod': 'flexural modulus astm d 790 tape 0° (mpa)',
 'flex mod tape': 'flexural modulus astm d 790 tape 0° (mpa)',
 'tape flexural modulus': 'flexural modulus astm d 790 tape 0° (mpa)',
 'flexural modulus tape': 'flexural modulus astm d 790 tape 0° (mpa)',
 'tape flex strength': 'flexural strength astm d 790 tape 0° (mpa)',
 'flex strength tape': 'flexural strength astm d 790 tape 0° (mpa)',
 'tape flexural strength': 'flexural strength astm d 790 tape 0° (mpa)',
 'flexural strength tape': 'flexural strength astm d 790 tape 0° (mpa)',
 "average molecular weight margolies' equation (g/mol)": "average molecular weight margolies' equation (g/mol)",
 'average molar mass': "average molecular weight margolies' equation (g/mol)",
 'average molecular mass': "average molecular weight margolies' equation (g/mol)",
 'avermw': "average molecular weight margolies' equation (g/mol)",
 'molecular weight': "average molecular weight margolies' equation (g/mol)",
 'mw': "average molecular weight margolies' equation (g/mol)",
 'average particle size laser scattering d50 (µm)': 'average particle size laser scattering d50 (µm)',
 'avg. particle size': 'average particle size laser scattering d50 (µm)',
 'avpartsize': 'average particle size laser scattering d50 (µm)',
 'particle size': 'average particle size laser scattering d50 (µm)',
 'particle size d50': 'average particle size laser scattering d50 (µm)',
 'ball indentation hardness iso 2039-1 h 358/30 (mpa)': 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'ball indention hardness': 'ball indentation hardness iso 2039-1 h 358/30 (mpa)',
 'ball pressure test iec 60695-10-2 (°c)': 'ball pressure test iec 60695-10-2 (°c)',
 'bulk density iso 60 (kg/m³)': 'bulk density iso 60 (kg/m³)',
 'apparent (bulk) density': 'bulk density iso 60 (kg/m³)',
 'apparent density': 'bulk density iso 60 (kg/m³)',
 'bulkdens': 'bulk density iso 60 (kg/m³)',
 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy impact strength (double notched)': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy impact strength (double notch)': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notch charpy impact strength': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notched charpy impact strength': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notch charpy': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notched charpy': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notch impact': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'double notched impact': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy double notch': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy double notched': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)',
 'charpy impact': 'charpy impact strength',
 'impact charpy': 'charpy impact strength',
 'charpy unnotched': 'charpy impact strength',
 'charpy unnotch': 'charpy impact strength',
 'unnotched charpy': 'charpy impact strength',
 'unnotch charpy': 'charpy impact strength',
 'charpy unnotched impact': 'charpy impact strength',
 'charpy unnotch impact': 'charpy impact strength',
 'unnotched charpy impact': 'charpy impact strength',
 'unnotch charpy impact': 'charpy impact strength',
 'charpy impact strength unnotched': 'charpy impact strength',
 'charpy impact strength unnotch': 'charpy impact strength',
 'charpy impact strength (unnotched)': 'charpy impact strength',
 'charpy impact strength (unnotch)': 'charpy impact strength',
 'charpy impact unnotched': 'charpy impact strength',
 'charpy impact unnotch': 'charpy impact strength',
 'charpy impact (unnotched)': 'charpy impact strength',
 'charpy impact (unnotch)': 'charpy impact strength',
 'charpy notched': 'charpy notched impact strength',
 'charpy notch': 'charpy notched impact strength',
 'notched charpy': 'charpy notched impact strength',
 'notch charpy': 'charpy notched impact strength',
 'charpy notched impact': 'charpy notched impact strength',
 'charpy notch impact': 'charpy notched impact strength',
 'notched charpy impact': 'charpy notched impact strength',
 'notch charpy impact': 'charpy notched impact strength',
 'charpy impact strength notched': 'charpy notched impact strength',
 'charpy impact strength notch': 'charpy notched impact strength',
 'charpy impact strength (notched)': 'charpy notched impact strength',
 'charpy impact strength (notch)': 'charpy notched impact strength',
 'charpy impact notched': 'charpy notched impact strength',
 'charpy impact notch': 'charpy notched impact strength',
 'charpy impact (notched)': 'charpy notched impact strength',
 'charpy impact (notch)': 'charpy notched impact strength',
 'coefficient of linear thermal expansion': 'coefficient of linear thermal expansion (clte)',
 'clte': 'coefficient of linear thermal expansion (clte)',
 'linear expansion factor': 'coefficient of linear thermal expansion (clte)',
 'thermal expansion': 'coefficient of linear thermal expansion (clte)',
 'linear thermal expansion': 'coefficient of linear thermal expansion (clte)',
 'coef. of lin. therm expansion': 'coefficient of linear thermal expansion (clte)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'linear expansion factor (normal)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'normal thermal expansion': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'normal linear thermal expansion': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'coef. of lin. therm expansion normal': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'clte (transverse direction)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 normal (e-6/k)',
 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'linear expansion factor (parallel)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'parallel thermal expansion': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'parallel linear thermal expansion': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'coef. of lin. therm expansion parallel': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'clte (flow direction)': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)',
 'compression set iso 815 23°c (%)': 'compression set iso 815 23°c (%)',
 'compression set at 23c': 'compression set iso 815 23°c (%)',
 'compression set iso 815 23°c, 24h (%)': 'compression set iso 815 23°c, 24h (%)',
 'compression set at 23c, 24h': 'compression set iso 815 23°c, 24h (%)',
 'compressive modulus iso 604 (mpa)': 'compressive modulus iso 604 (mpa)',
 'compressive module': 'compressive modulus iso 604 (mpa)',
 'comp mod': 'compressive modulus iso 604 (mpa)',
 'compressive strength iso 604 (mpa)': 'compressive strength iso 604 (mpa)',
 'compressive stress': 'compressive strength iso 604 (mpa)',
 'compressive stress at 1% strain iso 604 (mpa)': 'compressive stress at 1% strain iso 604 (mpa)',
 'compressive strength at 1% strain': 'compressive stress at 1% strain iso 604 (mpa)',
 'compressive stress 1% deformation': 'compressive stress at 1% strain iso 604 (mpa)',
 'compressive strength at 1% deformation': 'compressive stress at 1% strain iso 604 (mpa)',
 'continuous service temperature iec 60216-1 (°c)': 'continuous service temperature iec 60216-1 (°c)',
 'continuous use temperature': 'continuous service temperature iec 60216-1 (°c)',
 'continuous allowable service temperature in air': 'continuous service temperature iec 60216-1 (°c)',
 'max service temperature': 'continuous service temperature iec 60216-1 (°c)',
 'min service temperature': 'continuous service temperature iec 60216-1 (°c)',
 'service temperature long term': 'continuous service temperature iec 60216-1 (°c)',
 'service temperature short term': 'continuous service temperature iec 60216-1 (°c)',
 'cut': 'continuous service temperature iec 60216-1 (°c)',
 'temperature resistance': 'continuous service temperature iec 60216-1 (°c)',
 'minimum operating temperature': 'continuous service temperature iec 60216-1 (°c)',
 'continuous utilization temperature': 'continuous service temperature iec 60216-1 (°c)',
 'density iso 1183 (kg/m³)': 'density iso 1183 (kg/m³)',
 'dense': 'density iso 1183 (kg/m³)',
 'heavy': 'density iso 1183 (kg/m³)',
 'heavy weight': 'density iso 1183 (kg/m³)',
 'specific gravity': 'density iso 1183 (kg/m³)',
 'tangent delta': 'dissipation factor',
 'tan delta': 'dissipation factor',
 'df': 'dissipation factor',
 'dielectric dissipation factor': 'dissipation factor',
 'dielectric dissipation': 'dissipation factor',
 'loss angle': 'dissipation factor',
 'loss tangent': 'dissipation factor',
 'dissipation factor iec 62631-2-1 100hz (e-4)': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dissipation factor 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'tangent delta at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'tangent delta, 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'tan delta 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'tan delta at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'df 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 '100hz df': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dielectric dissipation factor at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dielectric dissipation factor, 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dielectric dissipation 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dielectric dissipation at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'loss angle at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'loss angle 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'loss tangent 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'loss tangent at 100hz': 'dissipation factor iec 62631-2-1 100hz (e-4)',
 'dissipation factor iec 62631-2-1 1mhz (e-4)': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dissipation factor 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'tangent delta at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'tangent delta, 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'tan delta 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'tan delta at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'df 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 '1mhz df': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dielectric dissipation factor at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dielectric dissipation factor, 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dielectric dissipation 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'dielectric dissipation at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'loss angle at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'loss angle 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'loss tangent 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'loss tangent at 1mhz': 'dissipation factor iec 62631-2-1 1mhz (e-4)',
 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)': 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)',
 'effective thermal diffusivity, crossflow direction': 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)',
 'effective thermal diffusivity iso 22007-4 flow (m²/s)': 'effective thermal diffusivity iso 22007-4 flow (m²/s)',
 'effective thermal diffusity, flow direction': 'effective thermal diffusivity iso 22007-4 flow (m²/s)',
 'in plane thermal diffusivity': 'effective thermal diffusivity iso 22007-4 flow (m²/s)',
 'effective thermal diffusivity iso 22007-4 through plane (m²/s)': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'effective thermal diffusivity, through plane direction': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'through plane thermal diffusivity': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'cross plane thermal diffusivity': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)',
 'electric strength iec 60243-1 (kv/mm)': 'electric strength iec 60243-1 (kv/mm)',
 'ac electristrength': 'electric strength iec 60243-1 (kv/mm)',
 'ac dielectric strength': 'electric strength iec 60243-1 (kv/mm)',
 'ac': 'electric strength iec 60243-1 (kv/mm)',
 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'elongation at break, perpendicular': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'perpendicular elongation at break': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'perpendicular break strain': 'elongation at break iso 527-1/-2 or iso 37 perpendicular (%)',
 'elongational stress f iso 21304-2 150/10 (mpa)': 'elongational stress f iso 21304-2 150/10 (mpa)',
 'fiber areal weight (g/m²)': 'fiber areal weight (g/m²)',
 'fiber volume content iso 11667 (%)': 'fiber volume content iso 11667 (%)',
 'flex modulus': 'flexural modulus',
 'flex mod': 'flexural modulus',
 'flexural modulus of elasticity': 'flexural modulus',
 'flexural performance': 'flexural modulus',
 'rigid': 'flexural modulus',
 'rigidity': 'flexural modulus',
 'bend strength': 'flexural modulus',
 'flexibility': 'flexural modulus',
 'flexible': 'flexural modulus',
 'flex': 'flexural modulus',
 'flexural modulus astm d 790 tape 0° (mpa)': 'flexural modulus astm d 790 tape 0° (mpa)',
 'tape flex modulus': 'flexural modulus astm d 790 tape 0° (mpa)',
 'flexural elongation at break': 'flexural strain at failure',
 'failure flex strain': 'flexural strain at failure',
 'flexural strain at failure astm d 790 tape 0° (%)': 'flexural strain at failure astm d 790 tape 0° (%)',
 'flexural strain at failure, tape': 'flexural strain at failure astm d 790 tape 0° (%)',
 'tape flex strain failure': 'flexural strain at failure astm d 790 tape 0° (%)',
 'flex str': 'flexural strength',
 'flex stress': 'flexural strength',
 'flexural strength astm d 790 tape 0° (mpa)': 'flexural strength astm d 790 tape 0° (mpa)',
 'tape flex str': 'flexural strength astm d 790 tape 0° (mpa)',
 'tape flex stress': 'flexural strength astm d 790 tape 0° (mpa)',
 'flexural stress at 3.5% iso 178 (mpa)': 'flexural stress at 3.5% iso 178 (mpa)',

#### For Property

In [115]:
def get_property():
    min_value = None
    max_value = None
    unit = ''
    exponential = ''
    p_metadata = random.choice(property_and_values)
    property_name = p_metadata[-1].lower()
    property_name_meaning = p_metadata[0].lower()
    range_type = random.choice(['value', 'value', 'value', 'min_value', 'max_value', 'value_range', 'range_without_value', 'range_percent'])
    property_details = {'property_name': None, 'modifier': {'value': None, 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}
    single_space_pattern = '(\s+)'
    try:    
        value = random.randrange(p_metadata[1],p_metadata[2])
    except: 
        value = round(random.uniform(p_metadata[1], p_metadata[2]),2)
        
    if p_metadata[3] != '°c':
        value = random.choice([value, value, value, value, value, value, value, value, value, value, value, value, value, value, random.randrange(100000, 1000000000)])

    if value > 899999:
        # print("*"*20, "{:.2e}".format(value))
        float_value = value
        value = "{:.2e}".format(value)
        exponential = 'positive'

    while value==0.0:
        value = round(random.uniform(p_metadata[1], p_metadata[2]), 9)
        print("$"*20, f"value was 0.0 for property range {p_metadata[1]} to {p_metadata[2]}, picking another random number: {value}")
        # print("#"*20, "{:.8f}".format(value))
        if -0.99999999999 < value < 0.99999999999:
            float_value = value
            value = "{:.2e}".format(value)
            # value = "{:.8f}".format(value)
            exponential = 'negative'
        else:
            value = round(value, 2)
            
    unit = random.choice([p_metadata[3],f" {p_metadata[3]}", ""])
    if not unit.strip():
        unit=''
            
    if not value:
        # print(f"could not find the value for {property_name_meaning}: {property_name}")
        value = random.randint(20, 200)
        
    is_unit_syn = random.choice([False, False, True])
    if unit and is_unit_syn and unit in unit_syns :
        # print("unit synonym")
        unit = random.choice(unit_syns[unit])
        
    if range_type=='min_value':
        try:
            if value < 0:
                max_value, min_value = get_random_range(float(value))
            else:
                min_value, max_value = get_random_range(float(value))
        except:
            min_value, max_value = get_random_range(random.randint(20, 2000))
            
        value = None
        max_value = None
        queries = [
            f"{property_name} of min {min_value}{unit}",
            f"{property_name} of minimum {min_value}{unit}",
            f"minimum of {property_name} {min_value}{unit}",
            f"{property_name} min {min_value}{unit}",
            f"{property_name} minimum {min_value}{unit}",           
            f"minimum {property_name} {min_value}{unit}",
            
            f"{property_name} more than {min_value}{unit}",
            f"{property_name} greater than {min_value}{unit}",
            f"{property_name} greater than {min_value}{unit}",
            f"{property_name} more than or eaual to {min_value}{unit}",
            f"{property_name} greater than or equal to {min_value}{unit}",
            f"{property_name} greater than or equal to {min_value}{unit}",
            f"{property_name} >{min_value}{unit}",
            f"{property_name} > {min_value}{unit}",
            f"{property_name} >={min_value}{unit}",
            f"{property_name} >= {min_value}{unit}",
        ]
        query = random.choice(queries)
    elif range_type=='max_value':
        try:
            if value < 0:
                max_value, min_value = get_random_range(float(value))
            else:
                min_value, max_value = get_random_range(float(value))
        except:
            min_value, max_value = get_random_range(random.randint(20, 2000))
            
        value = None
        min_value = None
        queries = [
            f"{property_name} of max {max_value}{unit}",
            f"{property_name} of maximum {max_value}{unit}",
            f"maximum of {property_name} {max_value}{unit}",
            f"{property_name} max {max_value}{unit}",
            f"{property_name} maximum {max_value}{unit}",
            f"maximum {property_name} {max_value}{unit}",
            
            f"{property_name} lesser than {max_value}{unit}",
            f"{property_name} less than {max_value}{unit}",
            f"{property_name} lesser than or equal to {max_value}{unit}",
            f"{property_name} less than or equal to {max_value}{unit}",
            f"{property_name} <{max_value}{unit}",
            f"{property_name} < {max_value}{unit}",
            f"{property_name} <={max_value}{unit}",
            f"{property_name} <= {max_value}{unit}",
        ]
        query = random.choice(queries)   
    else:
        queries = [
            f"{property_name} {value}{unit}",
            f"{property_name} {value}{unit}",

            f"{property_name} of {value}{unit}",
            f"{property_name} = {value}{unit}",
            f"{property_name} - {value}{unit}",
            f"{property_name}: {value}{unit}",
            f"{property_name} ({value}{unit})",
            f"{value}{unit} {property_name}",

            f"{property_name} {value}{unit}",
            f"{property_name} {value}{unit}",

            f"{property_name} of {value}{unit}",
            f"{property_name} = {value}{unit}",
            f"{property_name} - {value}{unit}",
            f"{property_name}: {value}{unit}",
            f"{property_name} ({value}{unit})",
            f"{value}{unit} {property_name}",

            f"{re.sub(single_space_pattern, ' ', re.sub('[^A-Za-z0-9]+', ' ', property_name).strip())} = {value}{unit}",
            f"{re.sub(single_space_pattern, ' ', re.sub('[^A-Za-z0-9]+', ' ', property_name).strip())} ={value}{unit}",

        ]

        if range_type == 'value':
            queries += [
                f"{property_name} of approximately {value}{unit}",
                f"{property_name} of approx {value}{unit}",
                f"{property_name} close to {value}{unit}",
                f"{property_name} around {value}{unit}",
            ]

        query = random.choice(queries)
        if random.choice(range(0, 10)) == 1 and property_name:
            query = f"{property_name.replace(' ', '')}={value}{unit}"
    #         print(f"cant remove space for {property_name}")

        if not " " in property_name and not exponential and value > 0:
            query2 = random.choice([
                f"{property_name}{value}",
                f"{property_name}-{value}",
                f"{value}{property_name}",
                f"{property_name}={value}",
            ])
            is_unit = random.choice([True, True, True, False, False])
            if not is_unit:
                query = query2
                unit = ''

        if not exponential and range_type != 'value' and value > 0:
            min_value, max_value = get_random_range(float(value))
            query3 = random.choice([       
                f"{property_name} of {value}{unit}",
                f"{property_name} {value}{unit}",
                f"{property_name} ({value}{unit})",
                f"{property_name} ={value}{unit}",
                f"{property_name} = {value}{unit}",
                f"{property_name} - {value}{unit}",
                f"{property_name}: {value}{unit}",
            ])

            if range_type == 'value_range': 
                range_query = random.choice([
                    f" from {min_value} to {max_value}",
                    f" from {min_value} - {max_value}",
                    f" from {min_value}-{max_value}",
                    f" between {min_value} to {max_value}",
                    f" between {min_value} - {max_value}",
                    f" between {min_value}-{max_value}",
                    f" between {min_value} and {max_value}",
                    f" in the range of {min_value} to {max_value}",
                    f" in the range of {min_value} - {max_value}",
                    f" in the range of {min_value}-{max_value}",
                ])
                query = query3 + range_query
            elif range_type == 'range_without_value':
                range_query = random.choice([
                    f" from {min_value} to {max_value}",
                    f" from {min_value} - {max_value}",
                    f" from {min_value}-{max_value}",
                    f" {min_value}-{max_value}",
                    f" {min_value} - {max_value}",
                    f" {min_value} to {max_value}",
                    f" between {min_value} to {max_value}",
                    f" between {min_value} - {max_value}",
                    f" between {min_value}-{max_value}",
                    f" between {min_value} and {max_value}",
                    f" in the range of {min_value} to {max_value}",
                    f" in the range of {min_value} - {max_value}",
                    f" in the range of {min_value}-{max_value}",
                ])
                query = f"{property_name}" + range_query + f"{unit}"

            elif range_type == 'range_percent':
                percent, min_value, max_value = get_random_percent(value)
                range_percent_query = random.choice([
                    f" with {percent}% range",
                    f" with +/-{percent}% range",
                    f" of +/-{percent}% range",
                    f" of -/+{percent}% range",
                    f" around {percent}% variation",
                    f" around {percent}% range",
                    f" around {percent}% margin",
    #                 f" close to a {percent}% variation",
    #                 f" close to a {percent}% range",
    #                 f" close to a {percent}% margin",
                    f" in the vicinity of {percent}%",
                    f" in the range of {percent}%",
                    f" within a range of {percent}%",
                    f" within {percent}% range",
                    f" within {percent}% margin",
                    ])

                query = query3 + range_percent_query
            else:
                print("@"*40, range_type)
        else:
            range_type = 'value'
        
    property_details['property_name'] = property_name_meaning
  
    property_details['modifier']['unit'] = unit.strip().lower()
    if not property_details['modifier']['unit']:
        property_details['modifier']['unit'] = None

    # no range queries for exponential queries
    if range_type == 'min_value':
        property_details['modifier']['min'] =  str(round(min_value, 2))
        property_details['modifier']['max'] =  None
        property_details['modifier']['value'] = property_details['modifier']['min']

    elif range_type == 'max_value':
        property_details['modifier']['max'] = str(round(max_value, 2))
        property_details['modifier']['min'] =  None
        property_details['modifier']['value'] = property_details['modifier']['max']

    elif range_type in ['value_range', 'range_percent']:
        property_details['modifier']['value'] = str(round(value, 2))
        property_details['modifier']['min'] = str(round(min_value, 2))
        property_details['modifier']['max'] = str(round(max_value, 2))
        
    elif range_type == 'range_without_value':
        property_details['modifier']['min'] = str(round(min_value, 2))
        property_details['modifier']['max'] = str(round(max_value, 2))
        property_details['modifier']['value'] = property_details['modifier']['min'] 
    else:
        if value:
            if exponential == 'positive':
                # print("#"*25, 'positive')
                if float_value < 0:
                    property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 2))
                    property_details['modifier']['max'] = "{:.2e}".format(round(float_value*0.9, 2))
                    property_details['modifier']['min'] = "{:.2e}".format(round(float_value*1.1, 2))
                else:
                    property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 2))
                    property_details['modifier']['min'] = "{:.2e}".format(round(float_value*0.9, 2))
                    property_details['modifier']['max'] = "{:.2e}".format(round(float_value*1.1, 2))
                    
            elif exponential == 'negative':
                print("*"*25, 'negative exponential')
                if float_value < 0:
                    property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 9))
                    property_details['modifier']['max'] = "{:.2e}".format(round(float_value*0.9, 9))
                    property_details['modifier']['min'] = "{:.2e}".format(round(float_value*1.1, 9))
                else:
                    property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 9))
                    property_details['modifier']['min'] = "{:.2e}".format(round(float_value*0.9, 9))
                    property_details['modifier']['max'] = "{:.2e}".format(round(float_value*1.1, 9))
                print(property_details)
                
            else:
                if value < 0:
                    property_details['modifier']['value'] = str(round(value, 2))
                    property_details['modifier']['max'] = str(round(value*0.9, 2))
                    property_details['modifier']['min'] = str(round(value*1.1, 2))
                else:
                    property_details['modifier']['value'] = str(round(value, 2))
                    property_details['modifier']['min'] = str(round(value*0.9, 2))
                    property_details['modifier']['max'] = str(round(value*1.1, 2))
        else:
            property_details['modifier']['value'] = None
        
    query = re.sub("(\s+)", " ", query.strip().lower())

    return property_details, query.replace("young s", "young's")

In [116]:
for i in range(1, 20):
    print(get_property(), "\n")

({'property_name': 'melt volume-flow rate iso 1133 (cm³/10min)', 'modifier': {'value': '97', 'min': '97', 'max': '227', 'unit': None}, 'property_type': 'property'}, 'mv in the range of 97 to 227')

({'property_name': 'melt volume-flow rate iso 1133 (cm³/10min)', 'modifier': {'value': '135', 'min': '135', 'max': None, 'unit': 'cm³/10min'}, 'property_type': 'property'}, 'melt volume rate greater than 135cm³/10min')

({'property_name': 'melting temperature iso 11357-1/-3 10°c/min (°c)', 'modifier': {'value': '319', 'min': '287.1', 'max': '350.9', 'unit': None}, 'property_type': 'property'}, 'dsc melting temp 319')

({'property_name': 'tensile strain at break iso 527-1/-2 50mm/min (%)', 'modifier': {'value': '85.05', 'min': '68.04', 'max': '102.06', 'unit': None}, 'property_type': 'property'}, 'elongation break 50 mm/min - 85.05 within 20% margin')

({'property_name': 'dissipation factor iec 62631-2-1 1mhz (e-4)', 'modifier': {'value': '1332', 'min': '1087', 'max': '1587', 'unit': None}, 'property_type': 'property'}, 'dielectric dissipation at 1mhz = 1332 between 1087 to 1587')

({'property_name': 'compressive strength iso 604 (mpa)', 'modifier': {'value': '147', 'min': '147', 'max': '330', 'unit': None}, 'property_type': 'property'}, 'compressive strength from 147 - 330')

({'property_name': 'tensile strain at yield iso 527-1/-2 50mm/min (%)', 'modifier': {'value': '38.03', 'min': '34.23', 'max': '41.83', 'unit': '%'}, 'property_type': 'property'}, '38.03 % yield strain 50mm/min')

({'property_name': 'charpy double notched impact strength iso 21304-2 23°c (kj/m²)', 'modifier': {'value': '237', 'min': '213.3', 'max': '260.7', 'unit': 'kj/m²'}, 'property_type': 'property'}, 'double notched charpy impact strength - 237 kj/m²')

({'property_name': 'tensile modulus', 'modifier': {'value': '1764', 'min': '1764', 'max': '3344', 'unit': 'mpa'}, 'property_type': 'property'}, 'tensile mod 1764 - 3344mpa')

({'property_name': 'tensile modulus', 'modifier': {'value': '6580', 'min': '4606.0', 'max': '8554.0', 'unit': 'mpa'}, 'property_type': 'property'}, 'tensile module 6580mpa within 30% margin')

({'property_name': 'izod notched impact strength', 'modifier': {'value': '8.19', 'min': '8.19', 'max': '18.1', 'unit': 'kj/m²'}, 'property_type': 'property'}, 'izod impact notch between 8.19 and 18.1 kj/m²')

({'property_name': 'flexural strain at failure astm d 790 tape 0° (%)', 'modifier': {'value': '5.53', 'min': '4.98', 'max': '6.08', 'unit': '%'}, 'property_type': 'property'}, 'flexural strain at failure: 5.53 %')

({'property_name': 'compressive stress at 1% strain iso 604 (mpa)', 'modifier': {'value': '159', 'min': '143.1', 'max': '174.9', 'unit': 'mpa'}, 'property_type': 'property'}, 'compressive stress at 1% strain =159mpa with 10% range')

({'property_name': 'tensile strain at yield iso 527-1/-2 50mm/min (%)', 'modifier': {'value': '10.58', 'min': '7.96', 'max': '13.87', 'unit': '%'}, 'property_type': 'property'}, 'elongation at yield 50 mm/min 10.58 % from 7.96 to 13.87')

({'property_name': 'tensile strain at yield iso 527-1/-2 50mm/min (%)', 'modifier': {'value': '37.1', 'min': '33.39', 'max': '40.81', 'unit': '%'}, 'property_type': 'property'}, 'strain at yield 50mm/min 37.1 %')

({'property_name': 'hardness, rockwell', 'modifier': {'value': '118', 'min': '106.2', 'max': '129.8', 'unit': None}, 'property_type': 'property'}, 'hardness, rockwell 118')

({'property_name': 'tensile stress at break iso 527-1/-2 50mm/min (mpa)', 'modifier': {'value': '155', 'min': None, 'max': '155', 'unit': 'mpa'}, 'property_type': 'property'}, 'tensile strength at break at 50mm/min < 155 mpa')

({'property_name': 'intrinsic viscosity iso 307, 1628', 'modifier': {'value': '2953', 'min': None, 'max': '2953', 'unit': None}, 'property_type': 'property'}, 'maximum of η 2953')

({'property_name': 'relative permittivity iec 62631-2-1 100hz', 'modifier': {'value': '5.37', 'min': '5.37', 'max': None, 'unit': None}, 'property_type': 'property'}, 'relative permittivity 100hz >= 5.37')

C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_6740\164086352.py:13: DeprecationWarning: randrange() will raise TypeError in the future
  value = random.randrange(p_metadata[1],p_metadata[2])

#### For Range Modifiers

In [117]:
def get_property_range_modifier(cm=False):
    property_details = []
    range_modifier = random.choice(RANGE_MODIFIERS)
    single_space_pattern = '(\s+)'
    is_abrv = random.choice([False, False, False, False, True])
    
    p_metadata = random.choice(property_and_values)
    while p_metadata[-1] in prop_abrv_mapping:
        p_metadata = random.choice(property_and_values)
        
    property_name = p_metadata[-1].lower()
    property_name_meaning = p_metadata[0].lower()

    p_metadata2 = random.choice(property_and_values)
    property_name2 = p_metadata2[-1].lower()
    property_name_meaning2 = p_metadata2[0].lower()
    
    while p_metadata2[-1] in prop_abrv_mapping:
        p_metadata2 = random.choice(property_and_values)
        property_name2 = p_metadata2[-1].lower()
        property_name_meaning2 = p_metadata2[0].lower()
        
    if is_abrv:
        abrv = random.choice(list(prop_abrv_mapping))
        while len(abrv)<2:
            abrv = random.choice(list(prop_abrv_mapping))
            
        property_name_meaning = prop_abrv_mapping[abrv]

        abrv2 = random.choice(list(prop_abrv_mapping))
        property_name_meaning2 = prop_abrv_mapping[abrv2]

        while property_name_meaning2 == property_name_meaning:
            abrv2 = random.choice(list(prop_abrv_mapping))
            property_name_meaning2 = prop_abrv_mapping[abrv2]
    
    if cm:
    
        property_details.extend([
            {"property_name": property_name_meaning, "modifier": {"value": str(range_modifier), "min": None, "max": None, "unit": ""}, "property_type": "property"},
            {"property_name": property_name_meaning2, "modifier": {"value": str(range_modifier), "min": None, "max": None, "unit": ""}, "property_type": "property"},
        ])
                
        if is_abrv:
            query = random.choice([
                f"{range_modifier} {abrv} and {abrv2}",
                f"{range_modifier} {abrv} and {abrv2}",
                f"{range_modifier} {abrv} or {abrv2}",    
            ])
        else:
            query = random.choice([
                f"{range_modifier} {property_name} and {property_name2}",
                f"{range_modifier} {property_name} and {property_name2}",
                f"{range_modifier} {property_name} or {property_name2}",    
            ])

    else:
        property_details.extend([
            {"property_name": property_name_meaning, "modifier": {"value": str(range_modifier), "min": None, "max": None, "unit": ""}, "property_type": "property"},
        ])
        
        if is_abrv:
            query = random.choice([
                f"{abrv} {range_modifier}",
                f"{abrv}: {range_modifier}",
                f"{abrv} - {range_modifier}",
                f"{abrv} = {range_modifier}",
                f"{abrv} ({range_modifier})",
        
                f"{range_modifier} {abrv}",
                f"{range_modifier} - {abrv}",    
            ])
        else:
            query = random.choice([
                f"{property_name} {range_modifier}",
                f"{property_name}: {range_modifier}",
                f"{property_name} - {range_modifier}",
                f"{property_name} = {range_modifier}",
                f"{property_name} ({range_modifier})",
        
                f"{range_modifier} {property_name}",
                f"{range_modifier} - {property_name}",
                
                f"{re.sub(single_space_pattern, ' ', re.sub('[^A-Za-z0-9]+', ' ', property_name).strip())} = {range_modifier}",
                f"{re.sub(single_space_pattern, ' ', re.sub('[^A-Za-z0-9]+', ' ', property_name).strip())} ={range_modifier}",
    
            ])
            
            if random.choice(range(0, 12)) == 1:
                query = f"{property_name.replace(' ', '')}={range_modifier}"

    ignore_prop_range_mod = [
        {'property_name': 'impact', 'modifier': {'value': 'high', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'},
        {'property_name': 'impact', 'modifier': {'value': 'highest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'},
    ]
    
    for i in property_details:
        if i in ignore_prop_range_mod:
            return get_property_range_modifier(cm)
                    
    return property_details, query.replace("young s", "young's")

In [118]:
get_property_range_modifier(True)

([{'property_name': 'melting temperature iso 11357-1/-3 10°c/min (°c)',
   'modifier': {'value': 'low', 'min': None, 'max': None, 'unit': ''},
   'property_type': 'property'},
  {'property_name': 'shore a hardness iso 48-4 / iso 868 15s',
   'modifier': {'value': 'low', 'min': None, 'max': None, 'unit': ''},
   'property_type': 'property'}],
 'low mp and soft')

In [119]:
get_property_range_modifier()

([{'property_name': 'dissipation factor iec 62631-2-1 100hz (e-4)',
   'modifier': {'value': 'high', 'min': None, 'max': None, 'unit': ''},
   'property_type': 'property'}],
 'tangent delta, 100hz - high')

In [120]:
for i in range(1, 20):
    print(get_property_range_modifier(True), "\n")
    
for i in range(1, 20):
    print(get_property_range_modifier(), "\n")

([{'property_name': 'average particle size laser scattering d50 (µm)', 'modifier': {'value': 'moderate', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'charpy impact strength', 'modifier': {'value': 'moderate', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'moderate average particle size and charpy unnotched impact')

([{'property_name': "average molecular weight margolies' equation (g/mol)", 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'melt mass-flow rate iso 1133 (g/10min)', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'lowest mw and mi')

([{'property_name': 'temperature of deflection under load', 'modifier': {'value': 'medium', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'shore d hardness iso 48-4 / iso 868 15s', 'modifier': {'value': 'medium', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'medium dtul and sh d')

([{'property_name': 'relative permittivity', 'modifier': {'value': 'low', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'flexural modulus', 'modifier': {'value': 'low', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'low relative permittivity and flex mod')

([{'property_name': 'tensile stress at break', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'lowest tensile stress at break and coefficient of linear thermal expansion (clte) iso 11359-1/-2 parallel (e-6/k)')

([{'property_name': 'electric strength iec 60243-1 (kv/mm)', 'modifier': {'value': 'high', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'izod impact strength', 'modifier': {'value': 'high', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'high ac dielectric strength and izod unnotched impact')

([{'property_name': 'tensile creep modulus iso 899-1 1h (mpa)', 'modifier': {'value': 'good', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'hardness, rockwell iso 2039-2 m-scale', 'modifier': {'value': 'good', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'good tensile creep modulus iso 899-1 1h (mpa) or rockwell, m')

([{'property_name': 'stress at break iso 527-1/-2 (mpa)', 'modifier': {'value': 'average', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'shore d hardness iso 48-4 / iso 868 15s', 'modifier': {'value': 'average', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'average stress at break or durometer hardness (shore d)')

([{'property_name': 'fiber areal weight (g/m²)', 'modifier': {'value': 'high', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'tensile notched impact strength iso 8256/1 23°c (kj/m²)', 'modifier': {'value': 'high', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'high fiber areal weight (g/m²) and n tenile impact')

([{'property_name': 'tensile strength astm d 3039 m tape 0° (mpa)', 'modifier': {'value': 'high', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'compression set iso 815 23°c (%)', 'modifier': {'value': 'high', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'high tensile strength tape or compression set at 23c')

([{'property_name': 'nominal strain at break iso 527-1/-2 (%)', 'modifier': {'value': 'excellent', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'flexural modulus astm d 790 tape 0° (mpa)', 'modifier': {'value': 'excellent', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'excellent break or tape flexural modulus')

([{'property_name': 'relative permittivity', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'viscosity number iso 307, 1628 (cm³/g)', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'lowest dielectric loss or viscosity number')

([{'property_name': 'charpy impact strength', 'modifier': {'value': 'highest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'tensile stress at 100% strain iso 527-1/-2 (mpa)', 'modifier': {'value': 'highest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'highest charpy impact unnotched or tensile stress at 100% strain')

([{'property_name': 'tensile strain at yield iso 527-1/-2 50mm/min (%)', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'izod impact strength', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'lowest yield strain 50mm/min and izod impact strength unnotch')

([{'property_name': 'tear strength iso 34-1 normal (kn/m)', 'modifier': {'value': 'moderate', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'vicat softening temperature iso 306 50°c/h 50n (°c)', 'modifier': {'value': 'moderate', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'moderate burst strength and vicat softening point at 50°c/h 50n')

([{'property_name': 'tensile modulus', 'modifier': {'value': 'good', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'dissipation factor iec 62631-2-1 1mhz (e-4)', 'modifier': {'value': 'good', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'good deformation or tangent delta at 1mhz')

([{'property_name': 'oxygen index iso 4589-1/-2 (%)', 'modifier': {'value': 'strong', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'thermal conductivity iso 22007-2 flow (w/(m k))', 'modifier': {'value': 'strong', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'strong oxygen index iso 4589-1/-2 (%) or in plane thermal conductivity')

([{'property_name': 'shore a hardness iso 48-4 / iso 868 15s', 'modifier': {'value': 'excellent', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'temperature of deflection under load', 'modifier': {'value': 'excellent', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'excellent soft and hdt')

([{'property_name': 'compression set iso 815 23°c, 24h (%)', 'modifier': {'value': 'low', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}, {'property_name': 'temperature of deflection under load iso 75-1/-2 1.8 mpa (°c)', 'modifier': {'value': 'low', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'low compression set and deflection temperature 264psi')

([{'property_name': 'relative permittivity', 'modifier': {'value': 'medium', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'dielectricloss=medium')

([{'property_name': 'charpy impact strength', 'modifier': {'value': 'moderate', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'charpy impact strength unnotch =moderate')

([{'property_name': 'oxygen index iso 4589-1/-2 (%)', 'modifier': {'value': 'average', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'oxygen index iso 4589 1 2 =average')

([{'property_name': 'bulk density iso 60 (kg/m³)', 'modifier': {'value': 'highest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'apparent density highest')

([{'property_name': 'melt mass-flow rate iso 1133 (g/10min)', 'modifier': {'value': 'strong', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'mi (strong)')

([{'property_name': 'tensile stress at break iso 527-1/-2 50mm/min (mpa)', 'modifier': {'value': 'highest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'ten stress brk at 50mm min = highest')

([{'property_name': 'vicat softening temperature', 'modifier': {'value': 'low', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'vicatsoftingtemp=low')

([{'property_name': 'shore d hardness iso 48-4 / iso 868 15s', 'modifier': {'value': 'excellent', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'hardness shore d iso 48 4 iso 868 15s =excellent')

([{'property_name': 'tensile modulus', 'modifier': {'value': 'good', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'emod: good')

([{'property_name': 'charpy notched impact strength', 'modifier': {'value': 'standard', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'standard notch charpy')

([{'property_name': 'fiber areal weight (g/m²)', 'modifier': {'value': 'standard', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'fiberarealweight(g/m²)=standard')

([{'property_name': 'tensile strain at break', 'modifier': {'value': 'low', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'break strain, break elongation: low')

([{'property_name': 'molding shrinkage iso 294-4, 2577 parallel (%)', 'modifier': {'value': 'strong', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'molding shrinkage iso 294-4, 2577 parallel (%) (strong)')

([{'property_name': 'tensile creep modulus', 'modifier': {'value': 'average', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'tensile creep modulus: average')

([{'property_name': 'tensile notched impact strength iso 8256/1 23°c (kj/m²)', 'modifier': {'value': 'excellent', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'tensile notched impact strength (excellent)')

([{'property_name': 'average particle size laser scattering d50 (µm)', 'modifier': {'value': 'good', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'avpartsize - good')

([{'property_name': 'tensile stress at break iso 527-1/-2 5mm/min (mpa)', 'modifier': {'value': 'highest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'tensile strength at break at 5mm/min (highest)')

([{'property_name': 'temperature of deflection under load iso 75-1/-2 1.8 mpa (°c)', 'modifier': {'value': 'strong', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'temperature of deflection under load 1 80 mpa = strong')

([{'property_name': 'molding shrinkage', 'modifier': {'value': 'standard', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'mold shrinkage (md/td): standard')

In [121]:
for i in range(1, 20):
    print(get_property(), "\n")

for i in range(1, 20):
    print(get_property_range_modifier(), "\n")

({'property_name': 'flexural stress at 3.5% iso 178 (mpa)', 'modifier': {'value': '180.34', 'min': '162.31', 'max': '198.37', 'unit': None}, 'property_type': 'property'}, 'flexural stress at 3.5% iso 178 (mpa) close to 180.34')

({'property_name': 'izod impact strength', 'modifier': {'value': '267', 'min': '240.3', 'max': '293.7', 'unit': None}, 'property_type': 'property'}, 'izod unnotch impact 267')

({'property_name': 'shore d hardness iso 48-4 / iso 868 15s', 'modifier': {'value': '14', 'min': '14', 'max': None, 'unit': None}, 'property_type': 'property'}, 'd greater than 14')

({'property_name': 'vicat softening temperature', 'modifier': {'value': '144', 'min': '144', 'max': None, 'unit': None}, 'property_type': 'property'}, 'vicat softing temp of minimum 144')

({'property_name': 'tensile stress at 100% strain iso 527-1/-2 (mpa)', 'modifier': {'value': '5', 'min': '4.5', 'max': '5.5', 'unit': 'mpa'}, 'property_type': 'property'}, 'tensile stress at 100% strain = 5mpa')

({'property_name': 'vicat softening temperature iso 306 50°c/h 50n (°c)', 'modifier': {'value': '262', 'min': '183.4', 'max': '340.6', 'unit': '°c'}, 'property_type': 'property'}, 'vicat softing temp at 50°c/h 50n - 262 °c in the vicinity of 30%')

({'property_name': 'dissipation factor iec 62631-2-1 1mhz (e-4)', 'modifier': {'value': '976', 'min': '878.4', 'max': '1073.6', 'unit': None}, 'property_type': 'property'}, 'tan delta 1mhz - 976')

({'property_name': 'shore hardness', 'modifier': {'value': '91.0', 'min': '81.9', 'max': '100.1', 'unit': None}, 'property_type': 'property'}, 'durometer hardness 91.0')

({'property_name': 'tensile modulus', 'modifier': {'value': '14157', 'min': '14157', 'max': '18100', 'unit': 'mpa'}, 'property_type': 'property'}, 'mechanical resistance between 14157 and 18100mpa')

({'property_name': 'tensile stress at break iso 527-1/-2 5mm/min (mpa)', 'modifier': {'value': '83', 'min': None, 'max': '83', 'unit': 'mpa'}, 'property_type': 'property'}, 'strebr at 5mm/min maximum 83 mpa')

({'property_name': 'charpy impact strength', 'modifier': {'value': '281.72', 'min': '253.55', 'max': '309.89', 'unit': 'kj/m²'}, 'property_type': 'property'}, 'unnotch charpy - 281.72 kj/m²')

({'property_name': 'average particle size laser scattering d50 (µm)', 'modifier': {'value': '267', 'min': '267', 'max': None, 'unit': None}, 'property_type': 'property'}, 'avg. particle size min 267')

({'property_name': 'tensile strain at break iso 527-1/-2 5mm/min (%)', 'modifier': {'value': '1.15e+08', 'min': '1.04e+08', 'max': '1.27e+08', 'unit': None}, 'property_type': 'property'}, 'tensilestrainatbreakiso527-1/-25mm/min(%)=1.15e+08')

({'property_name': 'density iso 1183 (kg/m³)', 'modifier': {'value': '1888', 'min': '1699.2', 'max': '2076.8', 'unit': None}, 'property_type': 'property'}, 'dense of approximately 1888')

({'property_name': 'intrinsic viscosity iso 307, 1628', 'modifier': {'value': '2046', 'min': None, 'max': '2046', 'unit': None}, 'property_type': 'property'}, 'η max 2046')

({'property_name': 'charpy notched impact strength', 'modifier': {'value': '4.0', 'min': None, 'max': '4.0', 'unit': 'kj/m²'}, 'property_type': 'property'}, 'charpy impact notch less than 4.0 kj/m²')

({'property_name': 'tensile strain at yield iso 527-1/-2 50mm/min (%)', 'modifier': {'value': '5.32', 'min': '5.32', 'max': None, 'unit': '%'}, 'property_type': 'property'}, 'elongation yield 50 mm/min >5.32%')

({'property_name': 'flexural modulus astm d 790 tape 0° (mpa)', 'modifier': {'value': '47', 'min': '47', 'max': None, 'unit': 'gpa'}, 'property_type': 'property'}, 'minimum flexural modulus tape 47 gpa')

({'property_name': "average molecular weight margolies' equation (g/mol)", 'modifier': {'value': '3.75e+06', 'min': '3.37e+06', 'max': '4.12e+06', 'unit': None}, 'property_type': 'property'}, 'average molar mass = 3.75e+06')

([{'property_name': 'surface resistivity iec 62631-3-2 (ohm)', 'modifier': {'value': 'excellent', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'sr - excellent')

([{'property_name': 'tensile strain at yield iso 527-1/-2 50mm/min (%)', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'strain at yield (lowest)')

([{'property_name': 'average particle size laser scattering d50 (µm)', 'modifier': {'value': 'moderate', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'average particle size =moderate')

([{'property_name': 'tensile stress at 50% strain iso 527-1/-2 (mpa)', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'tensile stress at 50% strain iso 527-1/-2 (mpa) - lowest')

([{'property_name': 'tensile strain at break', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'lowest break strain, break elongation')

([{'property_name': 'continuous service temperature iec 60216-1 (°c)', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'lowest continuous utilization temperature')

([{'property_name': 'dissipation factor', 'modifier': {'value': 'medium', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'df medium')

([{'property_name': 'flexural strain at failure astm d 790 tape 0° (%)', 'modifier': {'value': 'excellent', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'flexural strain at failure astm d 790 tape 0° (%) - excellent')

([{'property_name': 'tensile strain at yield iso 527-1/-2 50mm/min (%)', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'yield strain 50 mm/min = lowest')

([{'property_name': 'tensile stress at break', 'modifier': {'value': 'lowest', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'lowest break stress')

([{'property_name': 'flexural modulus', 'modifier': {'value': 'medium', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'flex mod (medium)')

([{'property_name': 'tensile strain at yield iso 527-1/-2 50mm/min (%)', 'modifier': {'value': 'medium', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'strain yield 50 mm/min = medium')

([{'property_name': 'density iso 1183 (kg/m³)', 'modifier': {'value': 'moderate', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'moderate heavy')

([{'property_name': 'relative permittivity', 'modifier': {'value': 'moderate', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'dielectric loss =moderate')

([{'property_name': 'vicat softening temperature iso 306 50°c/h 10n (°c)', 'modifier': {'value': 'strong', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'strong - vicat at 50°c/h 10n')

([{'property_name': 'tensile strain at yield iso 527-1/-2 50mm/min (%)', 'modifier': {'value': 'weak', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'elongation at yield - weak')

([{'property_name': 'temperature of deflection under load', 'modifier': {'value': 'strong', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'dtul = strong')

([{'property_name': 'flexural strength astm d 790 tape 0° (mpa)', 'modifier': {'value': 'average', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'tape flexural strength: average')

([{'property_name': 'tensile stress at break iso 527-1/-2 50mm/min (mpa)', 'modifier': {'value': 'standard', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'tensilestressatbreakat50mm/min=standard')

C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_6740\164086352.py:13: DeprecationWarning: randrange() will raise TypeError in the future
  value = random.randrange(p_metadata[1],p_metadata[2])

### UL Properties

In [122]:
ul_cert = unique_values["UL"]

In [123]:
ul_properties = []
for item in ul_cert:
    if item['UL_PROPERTY']!="Minimum Thickness (mm)":
#         print(item)
#         print("\n")
        # if item["UNIT_OF_MEAS_SI"]:
        #     ul_properties.append((item["UL_PROPERTY"].lower(), item["Min_Value"], item["Max_Value"], item["Categorical_Values"], item["UNIT_OF_MEAS_SI"].lower(), item["UL_PROPERTY"].lower()))
        # else:
        #     ul_properties.append((item["UL_PROPERTY"].lower(), item["Min_Value"], item["Max_Value"], item["Categorical_Values"], "", item["UL_PROPERTY"].lower()))    
        if item["UNIT_OF_MEAS_SI"] and item["Categorical_Values"]:
            ul_properties.append((item["UL_PROPERTY"].lower(), item["Min_Value"], item["Max_Value"], [x.lower() for x in item["Categorical_Values"]], item["UNIT_OF_MEAS_SI"].lower(), item["UL_PROPERTY"].lower()))
        elif item["Categorical_Values"] and not item["UNIT_OF_MEAS_SI"]:
            ul_properties.append((item["UL_PROPERTY"].lower(), item["Min_Value"], item["Max_Value"], [x.lower() for x in item["Categorical_Values"]], "", item["UL_PROPERTY"].lower()))    
        elif item["UNIT_OF_MEAS_SI"] and not item["Categorical_Values"]:
            ul_properties.append((item["UL_PROPERTY"].lower(), item["Min_Value"], item["Max_Value"], None, item["UNIT_OF_MEAS_SI"].lower(), item["UL_PROPERTY"].lower()))    
        else:
            ul_properties.append((item["UL_PROPERTY"].lower(), item["Min_Value"], item["Max_Value"], None, "", item["UL_PROPERTY"].lower()))

In [124]:
ul_properties

[('flexural stress', 74, 157, None, 'mpa', 'flexural stress'),
 ('tensile impact strength',
  761,
  761,
  None,
  'kj/m²',
  'tensile impact strength'),
 ('comparative tracking index (cti)',
  125,
  600,
  None,
  'v',
  'comparative tracking index (cti)'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric strength'),
 ('surface resistivity',
  10000000000,
  100000000000,
  None,
  'ohms',
  'surface resistivity'),
 ('volume resistivity', 1, 1e+22, None, 'ohms·cm', 'volume resistivity'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure test'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional change'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0 (0 - 10 mm/min.)',
   'plc 1 (10.1 - 25.4 mm/min.)',
   'plc 2 (25.5 - 80 mm/min.)',
   'plc 3 (80.1 - 150 mm/min.)',
   'plc 4 (greater than 150 mm/min.)'],
  '',
  'high voltage arc tracking rate (hvtr)'),
 ('arc resistance',
  None,
  None,
  ['plc 0 (420 seconds or longer)',
   'plc 1 (360 - 419 seconds)',
   'plc 2 (300 - 359 seconds)',
   'plc 3 (240 - 299 seconds)',
   'plc 4 (180 - 239 seconds)',
   'plc 5 (120 - 179 seconds)',
   'plc 6 (60 - 119 seconds)',
   'plc 7 (less than 60 seconds)'],
  '',
  'arc resistance'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0 (600 v and greater)',
   'plc 1 (400 v - 599 v)',
   'plc 2 (250 v - 399 v)',
   'plc 3 (175 v - 249 v)',
   'plc 4 (100 v - 174 v)',
   'plc 5 (less than 100 v)'],
  '',
  'comparative tracking index (cti)'),
 ('outdoor suitability',
  None,
  None,
  ['f1 (suitable for ultraviolet light, water, and immersion exposure',
   'f2 (suitable for ultraviolet light, water, or immersion exposure)'],
  '',
  'outdoor suitability'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant'],
  '',
  'rohs 2011/65/eu material'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non-halogenated material'),
 ('non-chlorine & non-bromine material',
  None,
  None,
  ['compliant'],
  '',
  'non-chlorine & non-bromine material'),
 ('detergent resistance', None, None, ['f3'], '', 'detergent resistance'),
 ('detergent resistance', None, None, ['f4'], '', 'detergent resistance')]

In [125]:
remove_ulp = []
for i in ul_properties:
    if 'comparative tracking index' in i[0].lower() and 'v'==i[4].lower():
        remove_ulp.append(i)
    elif i[0].lower() in ['outdoor suitability', 'detergent resistance', 'flexural stress', 'volume resistivity', 'surface resistivity']:
        remove_ulp.append(i)
        
ul_properties.append(('detergent resistance', None, None, ['f3','f4'], '', 'detergent resistance'))
ul_properties.append(('outdoor suitability', None, None, ['f1','f2'], '', 'outdoor suitability'))

ul_properties = [i for i in ul_properties if i not in remove_ulp]
ul_properties

[('tensile impact strength',
  761,
  761,
  None,
  'kj/m²',
  'tensile impact strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric strength'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure test'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional change'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0 (0 - 10 mm/min.)',
   'plc 1 (10.1 - 25.4 mm/min.)',
   'plc 2 (25.5 - 80 mm/min.)',
   'plc 3 (80.1 - 150 mm/min.)',
   'plc 4 (greater than 150 mm/min.)'],
  '',
  'high voltage arc tracking rate (hvtr)'),
 ('arc resistance',
  None,
  None,
  ['plc 0 (420 seconds or longer)',
   'plc 1 (360 - 419 seconds)',
   'plc 2 (300 - 359 seconds)',
   'plc 3 (240 - 299 seconds)',
   'plc 4 (180 - 239 seconds)',
   'plc 5 (120 - 179 seconds)',
   'plc 6 (60 - 119 seconds)',
   'plc 7 (less than 60 seconds)'],
  '',
  'arc resistance'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0 (600 v and greater)',
   'plc 1 (400 v - 599 v)',
   'plc 2 (250 v - 399 v)',
   'plc 3 (175 v - 249 v)',
   'plc 4 (100 v - 174 v)',
   'plc 5 (less than 100 v)'],
  '',
  'comparative tracking index (cti)'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant'],
  '',
  'rohs 2011/65/eu material'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non-halogenated material'),
 ('non-chlorine & non-bromine material',
  None,
  None,
  ['compliant'],
  '',
  'non-chlorine & non-bromine material'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4'],
  '',
  'detergent resistance'),
 ('outdoor suitability', None, None, ['f1', 'f2'], '', 'outdoor suitability')]

In [126]:
ul_properties

[('tensile impact strength',
  761,
  761,
  None,
  'kj/m²',
  'tensile impact strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric strength'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure test'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional change'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0 (0 - 10 mm/min.)',
   'plc 1 (10.1 - 25.4 mm/min.)',
   'plc 2 (25.5 - 80 mm/min.)',
   'plc 3 (80.1 - 150 mm/min.)',
   'plc 4 (greater than 150 mm/min.)'],
  '',
  'high voltage arc tracking rate (hvtr)'),
 ('arc resistance',
  None,
  None,
  ['plc 0 (420 seconds or longer)',
   'plc 1 (360 - 419 seconds)',
   'plc 2 (300 - 359 seconds)',
   'plc 3 (240 - 299 seconds)',
   'plc 4 (180 - 239 seconds)',
   'plc 5 (120 - 179 seconds)',
   'plc 6 (60 - 119 seconds)',
   'plc 7 (less than 60 seconds)'],
  '',
  'arc resistance'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0 (600 v and greater)',
   'plc 1 (400 v - 599 v)',
   'plc 2 (250 v - 399 v)',
   'plc 3 (175 v - 249 v)',
   'plc 4 (100 v - 174 v)',
   'plc 5 (less than 100 v)'],
  '',
  'comparative tracking index (cti)'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant'],
  '',
  'rohs 2011/65/eu material'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non-halogenated material'),
 ('non-chlorine & non-bromine material',
  None,
  None,
  ['compliant'],
  '',
  'non-chlorine & non-bromine material'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4'],
  '',
  'detergent resistance'),
 ('outdoor suitability', None, None, ['f1', 'f2'], '', 'outdoor suitability')]

In [127]:
for ul in ul_properties:
    if ul[3]:
        values = []
        for v in ul[3]:
            values.append(v.split(" (")[0])
        values = [i for i in values if i not in ul[3]]
        if values:
            ul[3].extend(values)

ul_properties

[('tensile impact strength',
  761,
  761,
  None,
  'kj/m²',
  'tensile impact strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric strength'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure test'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional change'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0 (0 - 10 mm/min.)',
   'plc 1 (10.1 - 25.4 mm/min.)',
   'plc 2 (25.5 - 80 mm/min.)',
   'plc 3 (80.1 - 150 mm/min.)',
   'plc 4 (greater than 150 mm/min.)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4'],
  '',
  'high voltage arc tracking rate (hvtr)'),
 ('arc resistance',
  None,
  None,
  ['plc 0 (420 seconds or longer)',
   'plc 1 (360 - 419 seconds)',
   'plc 2 (300 - 359 seconds)',
   'plc 3 (240 - 299 seconds)',
   'plc 4 (180 - 239 seconds)',
   'plc 5 (120 - 179 seconds)',
   'plc 6 (60 - 119 seconds)',
   'plc 7 (less than 60 seconds)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7'],
  '',
  'arc resistance'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0 (600 v and greater)',
   'plc 1 (400 v - 599 v)',
   'plc 2 (250 v - 399 v)',
   'plc 3 (175 v - 249 v)',
   'plc 4 (100 v - 174 v)',
   'plc 5 (less than 100 v)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5'],
  '',
  'comparative tracking index (cti)'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant'],
  '',
  'rohs 2011/65/eu material'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non-halogenated material'),
 ('non-chlorine & non-bromine material',
  None,
  None,
  ['compliant'],
  '',
  'non-chlorine & non-bromine material'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4'],
  '',
  'detergent resistance'),
 ('outdoor suitability', None, None, ['f1', 'f2'], '', 'outdoor suitability')]

In [128]:
ul_prop_names = []
for ul in ul_properties:
    ul_prop_names.append(ul[0].lower())

ul_prop_names

['tensile impact strength',
 'dielectric strength',
 'ball pressure test',
 'dimensional change',
 'inclined-plane tracking',
 'high voltage arc tracking rate (hvtr)',
 'arc resistance',
 'comparative tracking index (cti)',
 'rohs 2011/65/eu material',
 'non-halogenated material',
 'non-chlorine & non-bromine material',
 'detergent resistance',
 'outdoor suitability']

In [129]:
extra_uls = []
for ulp in ul_list_name_value:
    if not ul_list_name_value[ulp]['has_thickness']:
        if ul_list_name_value[ulp]['values']:
            for syn in ul_list_name_value[ulp]['synonyms']:
                extra_uls.append((ulp, None, None, ul_list_name_value[ulp]['values'], '', syn))
        elif ulp.lower() in ul_prop_names:
            for ul in ul_properties:
                if ul[0] == ulp:
                    for syn in ul_list_name_value[ulp]['synonyms']:
                        extra_uls.append((ulp, ul[1], ul[2], ul[3], ul[4], syn)) 
        else:
            print("\n", ulp, False, "currently not adding")


extra_uls.extend(
    [
    ('comparative tracking index (cti)', 100, 650, None, 'v', 'comparative tracking index (cti)'),
    ('comparative tracking index (cti)', 100, 650, None, 'v', 'comparative tracking'),
    ('comparative tracking index (cti)', 100, 650, None, 'v', 'comparative tracking index'),
    ('comparative tracking index (cti)', 100, 650, None, 'v', 'cti'),
    ('comparative tracking index (cti)', 100, 650, None, 'v', 'comparative tracking rating'),
    ('comparative tracking index (cti)', 100, 650, None, 'v', 'comparative tracking index rating'),
    ('comparative tracking index (cti)', 100, 650, None, 'v', 'comp tracking'),
]
)

for i in extra_uls:
    if i not in ul_properties:
        ul_properties.append(i)
        
ul_properties

[('tensile impact strength',
  761,
  761,
  None,
  'kj/m²',
  'tensile impact strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric strength'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure test'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional change'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0 (0 - 10 mm/min.)',
   'plc 1 (10.1 - 25.4 mm/min.)',
   'plc 2 (25.5 - 80 mm/min.)',
   'plc 3 (80.1 - 150 mm/min.)',
   'plc 4 (greater than 150 mm/min.)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4'],
  '',
  'high voltage arc tracking rate (hvtr)'),
 ('arc resistance',
  None,
  None,
  ['plc 0 (420 seconds or longer)',
   'plc 1 (360 - 419 seconds)',
   'plc 2 (300 - 359 seconds)',
   'plc 3 (240 - 299 seconds)',
   'plc 4 (180 - 239 seconds)',
   'plc 5 (120 - 179 seconds)',
   'plc 6 (60 - 119 seconds)',
   'plc 7 (less than 60 seconds)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7'],
  '',
  'arc resistance'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0 (600 v and greater)',
   'plc 1 (400 v - 599 v)',
   'plc 2 (250 v - 399 v)',
   'plc 3 (175 v - 249 v)',
   'plc 4 (100 v - 174 v)',
   'plc 5 (less than 100 v)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5'],
  '',
  'comparative tracking index (cti)'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant'],
  '',
  'rohs 2011/65/eu material'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non-halogenated material'),
 ('non-chlorine & non-bromine material',
  None,
  None,
  ['compliant'],
  '',
  'non-chlorine & non-bromine material'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4'],
  '',
  'detergent resistance'),
 ('outdoor suitability', None, None, ['f1', 'f2'], '', 'outdoor suitability'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resistance'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'hvar'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resistivity'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resist'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resist to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistant to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistance to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistivity to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resist ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistant ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistance ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistivity ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resistant'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'ar'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc r'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arcres'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc res'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure'),
 ('ball pressure test', 125, 245, None, '', 'bpt'),
 ('ball pressure test', 125, 245, None, '', 'ball test'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking index'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'cti'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking rating'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking index rating'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comp tracking'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'di strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'di str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'diele str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielec str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectrical strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dc dielectric strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'di-electric str'),
 ('dimensional change', 0, 1.8, None, '%', 'dim change'),
 ('dimensional change', 0, 1.8, None, '%', 'dimens change'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional chg'),
 ('dimensional change', 0, 1.8, None, '%', 'di-mensional change'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage arc tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'hvtr'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high vol arc tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage arc tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'voltage arc tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage rate'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'ip tracking'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'ipt'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined plane'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'plane tracking'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inc-plane track'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inc-plane tracking'),
 ('non-halogenated material', None, None, ['compliant'], '', 'nhm'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non halo material'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'outdoor suitability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'outdoor durability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'out door durability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'durability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'suitability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'out door suitability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'os'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resistance'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resistant'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resist'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resistivity'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resis'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent res'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'deterres'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'dr'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'dres'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs and eu'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs & eu'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs 2011/65/eu material'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs material'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  '2011/65/eu material'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  '2011/65/eu'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs 2011/65/eu mat'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs mat'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  '2011/65/eu mat'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'ten imp str'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'tensile imp'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'tensile imp str'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'ti strength'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'ti str'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'tis'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking index (cti)'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking index'),
 ('comparative tracking index (cti)', 100, 650, None, 'v', 'cti'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking rating'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking index rating'),
 ('comparative tracking index (cti)', 100, 650, None, 'v', 'comp tracking')]

In [130]:
for i in ul_properties:
    if not i[0] or not i[-1]:
        print(i, "\n")

In [131]:
ul_property_syns = synonym_df2[synonym_df2['TYPE']=='ul property'][['DEFINED_NAME', 'SYNONYMS']].groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
ul_property_syns

{'arc resistance': ['arc resistance'],
 'comparative tracking index (cti)': ['comparative tracking index (cti)',
  'comparative tracking index',
  'cti',
  'iec tracking index',
  'tracking index'],
 'detergent resistance': ['detergent resistance', 'detergence resistance'],
 'dielectric strength': ['dielectric strength',
  'electrically insulative',
  'electrical insulation',
  'dielectric breakdown strength'],
 'dimensional change': ['dimensional change'],
 'flame rating': ['flame rating', 'ul listed', 'flame class rating'],
 'flammability classification': ['flammability classification',
  'flame classification',
  'flameclassification',
  'flame class'],
 'glow wire flammability index': ['glow wire flammability index',
  'gwfi',
  'glow wire flammability',
  'glow wire flame',
  'glow wire flame index'],
 'glow wire ignition temperature': ['flow wire ignition temperature', 'gwit'],
 'high voltage arc tracking rate (hvtr)': ['high voltage arc tracking rate (hvtr)',
  'high voltage arc tracking rate',
  'hvtr'],
 'high-current arc ignition (hai)': ['high current arc ignition (hai)',
  'high current arc ignition',
  'hai'],
 'hot wire ignition (hwi)': ['hot wire ignition (hwi)',
  'hot wire ignition',
  'hwi'],
 'inclined-plane tracking': ['inclined plane tracking'],
 'outdoor suitability': ['outdoor suitability'],
 'relative thermal index': ['relative thermal index', 'rti'],
 'relative thermal index - electrical (rti elec) (°c)': ['relative thermal index - electrical (rti elec)',
  'relative thermal index - electrical',
  'rti elec'],
 'relative thermal index - mechanical impact (rti imp) (°c)': ['relative thermal index - mechanical impact (rti imp)',
  'relative thermal index - mechanical impact',
  'rti imp'],
 'relative thermal index - mechanical strength (rti str) (°c)': ['relative thermal index - mechanical strength (rti str)',
  'relative thermal index - mechanical strength',
  'rti str'],
 'rohs 2011/65/eu material': ['rohs 2011/65/eu material']}

In [132]:
for i in list(ul_property_syns):
    match_ul_prop = process.extract(i, list(ul_list_name_value))
    if match_ul_prop[0][1] < 88:
        print("Not adding: ", i, match_ul_prop[0], "\n")
    else:
        # print(i, match_ul_prop[0], "\n")
        if ul_property_syns[i] != [None]:
            ul_list_name_value[match_ul_prop[0][0]]['synonyms'].extend(ul_property_syns[i])
            ul_list_name_value[match_ul_prop[0][0]]['synonyms'] = list(set(ul_list_name_value[match_ul_prop[0][0]]['synonyms']))
        else:
            print(ul_property_syns[i])

In [133]:
for i in list(ul_property_syns):
    if i not in list(ul_list_name_value):
        print(1, i, "\n")
        
    
# for j in list(ul_list_name_value):
#     if j not in list(ul_property_syns):
#         print(2, j, "\n")

In [134]:
list(ul_list_name_value)

['arc resistance',
 'ball pressure test',
 'comparative tracking index (cti)',
 'dielectric strength',
 'dimensional change',
 'flame rating',
 'flammability classification',
 'glow wire flammability index',
 'glow wire ignition temperature',
 'glow wire',
 'high voltage arc tracking rate (hvtr)',
 'high-current arc ignition (hai)',
 'hot wire ignition (hwi)',
 'inclined-plane tracking',
 'non-halogenated material',
 'outdoor suitability',
 'detergent resistance',
 'relative thermal index - electrical (rti elec) (°c)',
 'relative thermal index - mechanical impact (rti imp) (°c)',
 'relative thermal index - mechanical strength (rti str) (°c)',
 'relative thermal index',
 'rohs 2011/65/eu material',
 'tensile impact strength']

In [135]:
ul_prop_syn_mapping = {}
ul_sub_prop_syn_mapping = {}

for ulp in ul_list_name_value:
    if ul_list_name_value[ulp]['has_thickness']:
        for syn in ul_list_name_value[ulp]['synonyms']:
            ul_sub_prop_syn_mapping[syn] = ulp
    else:
        for syn in ul_list_name_value[ulp]['synonyms']:
            ul_prop_syn_mapping[syn] = ulp

In [136]:
ul_prop_syn_mapping

{'high voltage arc': 'arc resistance',
 'high voltage arc resist ignition': 'arc resistance',
 'arcres': 'arc resistance',
 'high voltage arc resistant to ignition': 'arc resistance',
 'high voltage arc resistance to ignition': 'arc resistance',
 'ar': 'arc resistance',
 'arc r': 'arc resistance',
 'high voltage arc resistant ignition': 'arc resistance',
 'hvar': 'arc resistance',
 'arc resist': 'arc resistance',
 'high voltage arc resistivity to ignition': 'arc resistance',
 'arc res': 'arc resistance',
 'arc resistant': 'arc resistance',
 'arc resistance': 'arc resistance',
 'high voltage arc resistivity ignition': 'arc resistance',
 'high voltage arc resistance ignition': 'arc resistance',
 'high voltage arc resist to ignition': 'arc resistance',
 'arc resistivity': 'arc resistance',
 'ball pressure test': 'ball pressure test',
 'ball pressure': 'ball pressure test',
 'bpt': 'ball pressure test',
 'ball test': 'ball pressure test',
 'comparative tracking index rating': 'comparative tracking index (cti)',
 'comparative tracking index (cti)': 'comparative tracking index (cti)',
 'tracking index': 'comparative tracking index (cti)',
 'comparative tracking': 'comparative tracking index (cti)',
 'comp tracking': 'comparative tracking index (cti)',
 'cti': 'comparative tracking index (cti)',
 'comparative tracking index': 'comparative tracking index (cti)',
 'iec tracking index': 'comparative tracking index (cti)',
 'comparative tracking rating': 'comparative tracking index (cti)',
 'dielectrical strength': 'dielectric strength',
 'diele str': 'dielectric strength',
 'dielectric str': 'dielectric strength',
 'di strength': 'dielectric strength',
 'dielec str': 'dielectric strength',
 'electrical insulation': 'dielectric strength',
 'dielectric breakdown strength': 'dielectric strength',
 'dielectric strength': 'dielectric strength',
 'di-electric str': 'dielectric strength',
 'dc dielectric strength': 'dielectric strength',
 'electrically insulative': 'dielectric strength',
 'di str': 'dielectric strength',
 'dimensional change': 'dimensional change',
 'dimens change': 'dimensional change',
 'di-mensional change': 'dimensional change',
 'dim change': 'dimensional change',
 'dimensional chg': 'dimensional change',
 'voltage arc tracking rate': 'high voltage arc tracking rate (hvtr)',
 'high voltage arc tracking rate (hvtr)': 'high voltage arc tracking rate (hvtr)',
 'hvtr': 'high voltage arc tracking rate (hvtr)',
 'high voltage rate': 'high voltage arc tracking rate (hvtr)',
 'high vol arc tracking rate': 'high voltage arc tracking rate (hvtr)',
 'high voltage arc tracking rate': 'high voltage arc tracking rate (hvtr)',
 'high voltage arc tracking': 'high voltage arc tracking rate (hvtr)',
 'high voltage tracking rate': 'high voltage arc tracking rate (hvtr)',
 'ip tracking': 'inclined-plane tracking',
 'plane tracking': 'inclined-plane tracking',
 'inc-plane tracking': 'inclined-plane tracking',
 'ipt': 'inclined-plane tracking',
 'inclined plane tracking': 'inclined-plane tracking',
 'inclined plane': 'inclined-plane tracking',
 'inc-plane track': 'inclined-plane tracking',
 'inclined-plane': 'inclined-plane tracking',
 'non-halogenated material': 'non-halogenated material',
 'nhm': 'non-halogenated material',
 'non halo material': 'non-halogenated material',
 'outdoor suitability': 'outdoor suitability',
 'durability': 'outdoor suitability',
 'os': 'outdoor suitability',
 'suitability': 'outdoor suitability',
 'out door suitability': 'outdoor suitability',
 'out door durability': 'outdoor suitability',
 'outdoor durability': 'outdoor suitability',
 'detergent resistance': 'detergent resistance',
 'dres': 'detergent resistance',
 'detergent resistant': 'detergent resistance',
 'detergent resist': 'detergent resistance',
 'detergent resistivity': 'detergent resistance',
 'detergent res': 'detergent resistance',
 'deterres': 'detergent resistance',
 'detergence resistance': 'detergent resistance',
 'detergent resis': 'detergent resistance',
 'dr': 'detergent resistance',
 '2011/65/eu': 'rohs 2011/65/eu material',
 '2011/65/eu mat': 'rohs 2011/65/eu material',
 'rohs & eu': 'rohs 2011/65/eu material',
 'rohs 2011/65/eu mat': 'rohs 2011/65/eu material',
 '2011/65/eu material': 'rohs 2011/65/eu material',
 'rohs and eu': 'rohs 2011/65/eu material',
 'rohs mat': 'rohs 2011/65/eu material',
 'rohs': 'rohs 2011/65/eu material',
 'rohs material': 'rohs 2011/65/eu material',
 'rohs 2011/65/eu material': 'rohs 2011/65/eu material',
 'tensile impact strength': 'tensile impact strength',
 'ten imp str': 'tensile impact strength',
 'tensile imp': 'tensile impact strength',
 'tensile imp str': 'tensile impact strength',
 'ti strength': 'tensile impact strength',
 'ti str': 'tensile impact strength',
 'tis': 'tensile impact strength'}

In [137]:
list(ul_list_name_value)

['arc resistance',
 'ball pressure test',
 'comparative tracking index (cti)',
 'dielectric strength',
 'dimensional change',
 'flame rating',
 'flammability classification',
 'glow wire flammability index',
 'glow wire ignition temperature',
 'glow wire',
 'high voltage arc tracking rate (hvtr)',
 'high-current arc ignition (hai)',
 'hot wire ignition (hwi)',
 'inclined-plane tracking',
 'non-halogenated material',
 'outdoor suitability',
 'detergent resistance',
 'relative thermal index - electrical (rti elec) (°c)',
 'relative thermal index - mechanical impact (rti imp) (°c)',
 'relative thermal index - mechanical strength (rti str) (°c)',
 'relative thermal index',
 'rohs 2011/65/eu material',
 'tensile impact strength']

In [138]:
a = []
for i in ul_properties:
    a.append(i[0])

a = list(set(a))

for i in a:
    if not i in list(set(ul_prop_syn_mapping.values())):
        print(i)

non-chlorine & non-bromine material

In [139]:
ul_properties

[('tensile impact strength',
  761,
  761,
  None,
  'kj/m²',
  'tensile impact strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric strength'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure test'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional change'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0 (0 - 10 mm/min.)',
   'plc 1 (10.1 - 25.4 mm/min.)',
   'plc 2 (25.5 - 80 mm/min.)',
   'plc 3 (80.1 - 150 mm/min.)',
   'plc 4 (greater than 150 mm/min.)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4'],
  '',
  'high voltage arc tracking rate (hvtr)'),
 ('arc resistance',
  None,
  None,
  ['plc 0 (420 seconds or longer)',
   'plc 1 (360 - 419 seconds)',
   'plc 2 (300 - 359 seconds)',
   'plc 3 (240 - 299 seconds)',
   'plc 4 (180 - 239 seconds)',
   'plc 5 (120 - 179 seconds)',
   'plc 6 (60 - 119 seconds)',
   'plc 7 (less than 60 seconds)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7'],
  '',
  'arc resistance'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0 (600 v and greater)',
   'plc 1 (400 v - 599 v)',
   'plc 2 (250 v - 399 v)',
   'plc 3 (175 v - 249 v)',
   'plc 4 (100 v - 174 v)',
   'plc 5 (less than 100 v)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5'],
  '',
  'comparative tracking index (cti)'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant'],
  '',
  'rohs 2011/65/eu material'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non-halogenated material'),
 ('non-chlorine & non-bromine material',
  None,
  None,
  ['compliant'],
  '',
  'non-chlorine & non-bromine material'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4'],
  '',
  'detergent resistance'),
 ('outdoor suitability', None, None, ['f1', 'f2'], '', 'outdoor suitability'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resistance'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'hvar'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resistivity'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resist'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resist to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistant to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistance to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistivity to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resist ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistant ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistance ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistivity ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resistant'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'ar'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc r'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arcres'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc res'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure'),
 ('ball pressure test', 125, 245, None, '', 'bpt'),
 ('ball pressure test', 125, 245, None, '', 'ball test'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking index'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'cti'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking rating'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking index rating'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comp tracking'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'di strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'di str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'diele str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielec str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectrical strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dc dielectric strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'di-electric str'),
 ('dimensional change', 0, 1.8, None, '%', 'dim change'),
 ('dimensional change', 0, 1.8, None, '%', 'dimens change'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional chg'),
 ('dimensional change', 0, 1.8, None, '%', 'di-mensional change'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage arc tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'hvtr'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high vol arc tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage arc tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'voltage arc tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage rate'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'ip tracking'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'ipt'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined plane'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'plane tracking'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inc-plane track'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inc-plane tracking'),
 ('non-halogenated material', None, None, ['compliant'], '', 'nhm'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non halo material'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'outdoor suitability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'outdoor durability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'out door durability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'durability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'suitability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'out door suitability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'os'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resistance'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resistant'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resist'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resistivity'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resis'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent res'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'deterres'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'dr'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'dres'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs and eu'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs & eu'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs 2011/65/eu material'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs material'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  '2011/65/eu material'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  '2011/65/eu'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs 2011/65/eu mat'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs mat'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  '2011/65/eu mat'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'ten imp str'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'tensile imp'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'tensile imp str'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'ti strength'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'ti str'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'tis'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking index (cti)'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking index'),
 ('comparative tracking index (cti)', 100, 650, None, 'v', 'cti'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking rating'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking index rating'),
 ('comparative tracking index (cti)', 100, 650, None, 'v', 'comp tracking')]

In [140]:
ul_properties_merge_values = {}
for i in ul_properties:
    if i[3]:
        if i[0] in ul_properties_merge_values:
            ul_properties_merge_values[i[0]] += [x for x in i[3] if x not in ul_properties_merge_values[i[0]]]
        else:
            ul_properties_merge_values[i[0]] = i[3]
            
        # print(i)

ul_properties_merge_values

{'high voltage arc tracking rate (hvtr)': ['plc 0 (0 - 10 mm/min.)',
  'plc 1 (10.1 - 25.4 mm/min.)',
  'plc 2 (25.5 - 80 mm/min.)',
  'plc 3 (80.1 - 150 mm/min.)',
  'plc 4 (greater than 150 mm/min.)',
  'plc 0',
  'plc 1',
  'plc 2',
  'plc 3',
  'plc 4',
  'plc0',
  'plc1',
  'plc2',
  'plc3',
  'plc4',
  'plc-0',
  'plc-1',
  'plc-2',
  'plc-3',
  'plc-4'],
 'arc resistance': ['plc 0 (420 seconds or longer)',
  'plc 1 (360 - 419 seconds)',
  'plc 2 (300 - 359 seconds)',
  'plc 3 (240 - 299 seconds)',
  'plc 4 (180 - 239 seconds)',
  'plc 5 (120 - 179 seconds)',
  'plc 6 (60 - 119 seconds)',
  'plc 7 (less than 60 seconds)',
  'plc 0',
  'plc 1',
  'plc 2',
  'plc 3',
  'plc 4',
  'plc 5',
  'plc 6',
  'plc 7',
  'plc0',
  'plc1',
  'plc2',
  'plc3',
  'plc4',
  'plc5',
  'plc6',
  'plc7',
  'plc-0',
  'plc-1',
  'plc-2',
  'plc-3',
  'plc-4',
  'plc-5',
  'plc-6',
  'plc-7'],
 'comparative tracking index (cti)': ['plc 0 (600 v and greater)',
  'plc 1 (400 v - 599 v)',
  'plc 2 (250 v - 399 v)',
  'plc 3 (175 v - 249 v)',
  'plc 4 (100 v - 174 v)',
  'plc 5 (less than 100 v)',
  'plc 0',
  'plc 1',
  'plc 2',
  'plc 3',
  'plc 4',
  'plc 5',
  'plc0',
  'plc1',
  'plc2',
  'plc3',
  'plc4',
  'plc5',
  'plc-0',
  'plc-1',
  'plc-2',
  'plc-3',
  'plc-4',
  'plc-5'],
 'rohs 2011/65/eu material': ['+863 compliant',
  '863 compliant',
  '863',
  '+863-compliant',
  '863-compliant'],
 'non-halogenated material': ['compliant'],
 'non-chlorine & non-bromine material': ['compliant'],
 'detergent resistance': ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
 'outdoor suitability': ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2']}

In [141]:
len(ul_properties[0])

6

In [142]:
ul_properties2 = []
temp = []
for i in ul_properties:
    if i[0] in ul_properties_merge_values and i[0]==i[-1] and i[0] not in temp:
        temp.append(i[0])
        ul_properties2.append((i[0], i[1], i[2], ul_properties_merge_values[i[0]], i[4], i[5]))
    if i[0] in ul_properties_merge_values and i[0]==i[-1] and i[0] in temp:
        pass
    else:
        if i not in ul_properties2:
             ul_properties2.append(i)

ul_properties2

[('tensile impact strength',
  761,
  761,
  None,
  'kj/m²',
  'tensile impact strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric strength'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure test'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional change'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0 (0 - 10 mm/min.)',
   'plc 1 (10.1 - 25.4 mm/min.)',
   'plc 2 (25.5 - 80 mm/min.)',
   'plc 3 (80.1 - 150 mm/min.)',
   'plc 4 (greater than 150 mm/min.)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage arc tracking rate (hvtr)'),
 ('arc resistance',
  None,
  None,
  ['plc 0 (420 seconds or longer)',
   'plc 1 (360 - 419 seconds)',
   'plc 2 (300 - 359 seconds)',
   'plc 3 (240 - 299 seconds)',
   'plc 4 (180 - 239 seconds)',
   'plc 5 (120 - 179 seconds)',
   'plc 6 (60 - 119 seconds)',
   'plc 7 (less than 60 seconds)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resistance'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0 (600 v and greater)',
   'plc 1 (400 v - 599 v)',
   'plc 2 (250 v - 399 v)',
   'plc 3 (175 v - 249 v)',
   'plc 4 (100 v - 174 v)',
   'plc 5 (less than 100 v)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking index (cti)'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs 2011/65/eu material'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non-halogenated material'),
 ('non-chlorine & non-bromine material',
  None,
  None,
  ['compliant'],
  '',
  'non-chlorine & non-bromine material'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resistance'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'outdoor suitability'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'hvar'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resistivity'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resist'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resist to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistant to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistance to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistivity to ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resist ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistant ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistance ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc resistivity ignition'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'high voltage arc'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc resistant'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'ar'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc r'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arcres'),
 ('arc resistance',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc 6',
   'plc 7',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc6',
   'plc7',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5',
   'plc-6',
   'plc-7'],
  '',
  'arc res'),
 ('ball pressure test', 125, 245, None, '', 'ball pressure'),
 ('ball pressure test', 125, 245, None, '', 'bpt'),
 ('ball pressure test', 125, 245, None, '', 'ball test'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking index'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'cti'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking rating'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comparative tracking index rating'),
 ('comparative tracking index (cti)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  '',
  'comp tracking'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'di strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectric str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'di str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'diele str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielec str'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dielectrical strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'dc dielectric strength'),
 ('dielectric strength', 8, 55, None, 'kv/mm', 'di-electric str'),
 ('dimensional change', 0, 1.8, None, '%', 'dim change'),
 ('dimensional change', 0, 1.8, None, '%', 'dimens change'),
 ('dimensional change', 0, 1.8, None, '%', 'dimensional chg'),
 ('dimensional change', 0, 1.8, None, '%', 'di-mensional change'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage arc tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'hvtr'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high vol arc tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage arc tracking'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'voltage arc tracking rate'),
 ('high voltage arc tracking rate (hvtr)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  '',
  'high voltage rate'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined-plane'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'ip tracking'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'ipt'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inclined plane'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'plane tracking'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inc-plane track'),
 ('inclined-plane tracking', 1, 2.5, None, 'kv', 'inc-plane tracking'),
 ('non-halogenated material', None, None, ['compliant'], '', 'nhm'),
 ('non-halogenated material',
  None,
  None,
  ['compliant'],
  '',
  'non halo material'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'outdoor durability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'out door durability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'durability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'suitability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'out door suitability'),
 ('outdoor suitability',
  None,
  None,
  ['f1', 'f2', 'f 1', 'f 2', 'f-1', 'f-2'],
  '',
  'os'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resistant'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resist'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resistivity'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent resis'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'detergent res'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'deterres'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'dr'),
 ('detergent resistance',
  None,
  None,
  ['f3', 'f4', 'f 3', 'f 4', 'f-3', 'f-4'],
  '',
  'dres'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs and eu'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs & eu'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs material'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  '2011/65/eu material'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  '2011/65/eu'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs 2011/65/eu mat'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  'rohs mat'),
 ('rohs 2011/65/eu material',
  None,
  None,
  ['+863 compliant',
   '863 compliant',
   '863',
   '+863-compliant',
   '863-compliant'],
  '',
  '2011/65/eu mat'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'ten imp str'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'tensile imp'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'tensile imp str'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'ti strength'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'ti str'),
 ('tensile impact strength', 761, 761, None, 'kj/m²', 'tis'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking index'),
 ('comparative tracking index (cti)', 100, 650, None, 'v', 'cti'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking rating'),
 ('comparative tracking index (cti)',
  100,
  650,
  None,
  'v',
  'comparative tracking index rating'),
 ('comparative tracking index (cti)', 100, 650, None, 'v', 'comp tracking')]

In [143]:
len(ul_properties), len(ul_properties2)

(107, 102)

In [144]:
temp = []
duplicates = []
for i in ul_properties2:
    if i[-1] not in temp:
        temp.append(i[-1])
    else:
        duplicates.append(i[-1])
        print(i[-1])

comparative tracking
comparative tracking index
cti
comparative tracking rating
comparative tracking index rating
comp tracking

In [145]:
ul_properties3 = []
for i in ul_properties2:
    if i not in ul_properties3:
        ul_properties3.append(i)
        if i[-1] in duplicates:
            print(i)
    else:
        print(i)

print(len(ul_properties2), len(ul_properties3))

('comparative tracking index (cti)', None, None, ['plc 0', 'plc 1', 'plc 2', 'plc 3', 'plc 4', 'plc 5', 'plc0', 'plc1', 'plc2', 'plc3', 'plc4', 'plc5', 'plc-0', 'plc-1', 'plc-2', 'plc-3', 'plc-4', 'plc-5'], '', 'comparative tracking')
('comparative tracking index (cti)', None, None, ['plc 0', 'plc 1', 'plc 2', 'plc 3', 'plc 4', 'plc 5', 'plc0', 'plc1', 'plc2', 'plc3', 'plc4', 'plc5', 'plc-0', 'plc-1', 'plc-2', 'plc-3', 'plc-4', 'plc-5'], '', 'comparative tracking index')
('comparative tracking index (cti)', None, None, ['plc 0', 'plc 1', 'plc 2', 'plc 3', 'plc 4', 'plc 5', 'plc0', 'plc1', 'plc2', 'plc3', 'plc4', 'plc5', 'plc-0', 'plc-1', 'plc-2', 'plc-3', 'plc-4', 'plc-5'], '', 'cti')
('comparative tracking index (cti)', None, None, ['plc 0', 'plc 1', 'plc 2', 'plc 3', 'plc 4', 'plc 5', 'plc0', 'plc1', 'plc2', 'plc3', 'plc4', 'plc5', 'plc-0', 'plc-1', 'plc-2', 'plc-3', 'plc-4', 'plc-5'], '', 'comparative tracking rating')
('comparative tracking index (cti)', None, None, ['plc 0', 'plc 1', 'plc 2', 'plc 3', 'plc 4', 'plc 5', 'plc0', 'plc1', 'plc2', 'plc3', 'plc4', 'plc5', 'plc-0', 'plc-1', 'plc-2', 'plc-3', 'plc-4', 'plc-5'], '', 'comparative tracking index rating')
('comparative tracking index (cti)', None, None, ['plc 0', 'plc 1', 'plc 2', 'plc 3', 'plc 4', 'plc 5', 'plc0', 'plc1', 'plc2', 'plc3', 'plc4', 'plc5', 'plc-0', 'plc-1', 'plc-2', 'plc-3', 'plc-4', 'plc-5'], '', 'comp tracking')
('comparative tracking index (cti)', 100, 650, None, 'v', 'comparative tracking')
('comparative tracking index (cti)', 100, 650, None, 'v', 'comparative tracking index')
('comparative tracking index (cti)', 100, 650, None, 'v', 'cti')
('comparative tracking index (cti)', 100, 650, None, 'v', 'comparative tracking rating')
('comparative tracking index (cti)', 100, 650, None, 'v', 'comparative tracking index rating')
('comparative tracking index (cti)', 100, 650, None, 'v', 'comp tracking')
102 102

In [146]:
ul_properties = [x for x in ul_properties2]

In [147]:
def get_ul_property():
    p_metadata = random.choice(ul_properties)
    property_name = p_metadata[-1].lower()

    if property_name in ul_prop_syn_mapping:
        property_name_meaning = ul_prop_syn_mapping[property_name]
    else:
        property_name_meaning = property_name
    
    try:
        min_value = None
        max_value = None
        unit = ''
        exponential = ''
        
        range_type = random.choice(['value', 'value', 'value', 'min_value', 'max_value', 'value_range', 'range_without_value', 'range_percent'])

        property_details = {'property_name': None, 'modifier': {'value': None, 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}
        single_space_pattern = '(\s+)'
        try:    
            value = random.randrange(p_metadata[1],p_metadata[2])
        except: 
            value = round(random.uniform(p_metadata[1], p_metadata[2]),2)
            
        if p_metadata[4] != '°c':
            value = random.choice([value, value, value, value, value, value, value, value, value, value, value, value, value, value, random.randrange(100000, 1000000000)])

        if value > 899999:
            # print("*"*20, "{:.2e}".format(value))
            float_value = value
            value = "{:.2e}".format(value)
            exponential = 'positive'

        while value==0.0:
            value = round(random.uniform(p_metadata[1], p_metadata[2]), 9)
            print("$"*20, f"value was 0.0 for property range {p_metadata[1]} to {p_metadata[2]}, picking another random number: {value}")
            # print("#"*20, "{:.8f}".format(value))
            if -0.99999999999 < value < 0.99999999999:
                float_value = value
                value = "{:.2e}".format(value)
                # value = "{:.8f}".format(value)
                exponential = 'negative'
            else:
                value = round(value, 2)
                
        unit = random.choice([p_metadata[4],f" {p_metadata[4]}", ""])
        if not unit.strip():
            unit=''
                
        if not value:
            # print(f"could not find the value for {property_name_meaning}: {property_name}")
            value = random.randint(20, 200)
            
        is_unit_syn = random.choice([False, False, True])
        if unit and is_unit_syn and unit in unit_syns :
            # print("unit synonym")
            unit = random.choice(unit_syns[unit])
            
        if range_type=='min_value':
            try:
                if value < 0:
                    max_value, min_value = get_random_range(float(value))
                else:
                    min_value, max_value = get_random_range(float(value))
            except:
                min_value, max_value = get_random_range(random.randint(20, 2000))
                
            value = None
            max_value = None
            queries = [
                f"{property_name} of min {min_value}{unit}",
                f"{property_name} of minimum {min_value}{unit}",
                f"minimum of {property_name} {min_value}{unit}",
                f"{property_name} min {min_value}{unit}",
                f"{property_name} minimum {min_value}{unit}",           
                f"minimum {property_name} {min_value}{unit}",
                
                f"{property_name} more than {min_value}{unit}",
                f"{property_name} greater than {min_value}{unit}",
                f"{property_name} greater than {min_value}{unit}",
                f"{property_name} more than or eaual to {min_value}{unit}",
                f"{property_name} greater than or equal to {min_value}{unit}",
                f"{property_name} greater than or equal to {min_value}{unit}",
                f"{property_name} >{min_value}{unit}",
                f"{property_name} > {min_value}{unit}",
                f"{property_name} >={min_value}{unit}",
                f"{property_name} >= {min_value}{unit}",
            ]
            query = random.choice(queries)
        elif range_type=='max_value':
            try:
                if value < 0:
                    max_value, min_value = get_random_range(float(value))
                else:
                    min_value, max_value = get_random_range(float(value))
            except:
                min_value, max_value = get_random_range(random.randint(20, 2000))
                
            value = None
            min_value = None
            queries = [
                f"{property_name} of max {max_value}{unit}",
                f"{property_name} of maximum {max_value}{unit}",
                f"maximum of {property_name} {max_value}{unit}",
                f"{property_name} max {max_value}{unit}",
                f"{property_name} maximum {max_value}{unit}",
                f"maximum {property_name} {max_value}{unit}",
                
                f"{property_name} lesser than {max_value}{unit}",
                f"{property_name} less than {max_value}{unit}",
                f"{property_name} lesser than or equal to {max_value}{unit}",
                f"{property_name} less than or equal to {max_value}{unit}",
                f"{property_name} <{max_value}{unit}",
                f"{property_name} < {max_value}{unit}",
                f"{property_name} <={max_value}{unit}",
                f"{property_name} <= {max_value}{unit}",
            ]
            query = random.choice(queries)   
        else:
            queries = [
                f"{property_name} {value}{unit}",
                f"{property_name} {value}{unit}",

                f"{property_name} of {value}{unit}",
                f"{property_name} = {value}{unit}",
                f"{property_name} - {value}{unit}",
                f"{property_name}: {value}{unit}",
                f"{property_name} ({value}{unit})",
                f"{value}{unit} {property_name}",

                f"{property_name} {value}{unit}",
                f"{property_name} {value}{unit}",

                f"{property_name} of {value}{unit}",
                f"{property_name} = {value}{unit}",
                f"{property_name} - {value}{unit}",
                f"{property_name}: {value}{unit}",
                f"{property_name} ({value}{unit})",
                f"{value}{unit} {property_name}",

                f"{re.sub(single_space_pattern, ' ', re.sub('[^A-Za-z0-9]+', ' ', property_name).strip())} = {value}{unit}",
                f"{re.sub(single_space_pattern, ' ', re.sub('[^A-Za-z0-9]+', ' ', property_name).strip())} ={value}{unit}",

            ]

            if range_type == 'value':
                queries += [
                    f"{property_name} of approximately {value}{unit}",
                    f"{property_name} of approx {value}{unit}",
                    f"{property_name} close to {value}{unit}",
                    f"{property_name} around {value}{unit}",
                ]

            query = random.choice(queries)
            if random.choice(range(0, 10)) == 1 and property_name:
                query = f"{property_name.replace(' ', '')}={value}{unit}"
        #         print(f"cant remove space for {property_name}")

            if not " " in property_name and not exponential and value > 0:
                query2 = random.choice([
                    f"{property_name}{value}",
                    f"{property_name}-{value}",
                    f"{value}{property_name}",
                    f"{property_name}={value}",
                ])
                is_unit = random.choice([True, True, True, False, False])
                if not is_unit:
                    query = query2
                    unit = ''

            if not exponential and range_type != 'value' and value > 0:
                min_value, max_value = get_random_range(float(value))
                query3 = random.choice([       
                    f"{property_name} of {value}{unit}",
                    f"{property_name} {value}{unit}",
                    f"{property_name} ({value}{unit})",
                    f"{property_name} ={value}{unit}",
                    f"{property_name} = {value}{unit}",
                    f"{property_name} - {value}{unit}",
                    f"{property_name}: {value}{unit}",
                ])

                if range_type == 'value_range': 
                    range_query = random.choice([
                        f" from {min_value} to {max_value}",
                        f" from {min_value} - {max_value}",
                        f" from {min_value}-{max_value}",
                        f" between {min_value} to {max_value}",
                        f" between {min_value} - {max_value}",
                        f" between {min_value}-{max_value}",
                        f" between {min_value} and {max_value}",
                        f" in the range of {min_value} to {max_value}",
                        f" in the range of {min_value} - {max_value}",
                        f" in the range of {min_value}-{max_value}",
                    ])
                    query = query3 + range_query
                elif range_type == 'range_without_value':
                    range_query = random.choice([
                        f" from {min_value} to {max_value}",
                        f" from {min_value} - {max_value}",
                        f" from {min_value}-{max_value}",
                        f" {min_value}-{max_value}",
                        f" {min_value} - {max_value}",
                        f" {min_value} to {max_value}",
                        f" between {min_value} to {max_value}",
                        f" between {min_value} - {max_value}",
                        f" between {min_value}-{max_value}",
                        f" between {min_value} and {max_value}",
                        f" in the range of {min_value} to {max_value}",
                        f" in the range of {min_value} - {max_value}",
                        f" in the range of {min_value}-{max_value}",
                    ])
                    query = f"{property_name}" + range_query + f"{unit}"

                elif range_type == 'range_percent':
                    percent, min_value, max_value = get_random_percent(value)
                    range_percent_query = random.choice([
                        f" with {percent}% range",
                        f" with +/-{percent}% range",
                        f" of +/-{percent}% range",
                        f" of -/+{percent}% range",
                        f" around {percent}% variation",
                        f" around {percent}% range",
                        f" around {percent}% margin",
        #                 f" close to a {percent}% variation",
        #                 f" close to a {percent}% range",
        #                 f" close to a {percent}% margin",
                        f" in the vicinity of {percent}%",
                        f" in the range of {percent}%",
                        f" within a range of {percent}%",
                        f" within {percent}% range",
                        f" within {percent}% margin",
                        ])

                    query = query3 + range_percent_query
                else:
                    print("@"*40, range_type)
            else:
                range_type = 'value'
            
        property_details['property_name'] = property_name_meaning
    
        property_details['modifier']['unit'] = unit.strip().lower()
        if not property_details['modifier']['unit']:
            property_details['modifier']['unit'] = None

        # no range queries for exponential queries
        if range_type == 'min_value':
            property_details['modifier']['min'] =  str(round(min_value, 2))
            property_details['modifier']['max'] =  None
            property_details['modifier']['value'] = property_details['modifier']['min']

        elif range_type == 'max_value':
            property_details['modifier']['max'] = str(round(max_value, 2))
            property_details['modifier']['min'] =  None
            property_details['modifier']['value'] = property_details['modifier']['max']

        elif range_type in ['value_range', 'range_percent']:
            property_details['modifier']['value'] = str(round(value, 2))
            property_details['modifier']['min'] = str(round(min_value, 2))
            property_details['modifier']['max'] = str(round(max_value, 2))
            
        elif range_type == 'range_without_value':
            property_details['modifier']['min'] = str(round(min_value, 2))
            property_details['modifier']['max'] = str(round(max_value, 2))
            property_details['modifier']['value'] = property_details['modifier']['min'] 
        else:
            if value:
                if exponential == 'positive':
                    # print("#"*25, 'positive')
                    if float_value < 0:
                        property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 2))
                        property_details['modifier']['max'] = "{:.2e}".format(round(float_value*0.9, 2))
                        property_details['modifier']['min'] = "{:.2e}".format(round(float_value*1.1, 2))
                    else:
                        property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 2))
                        property_details['modifier']['min'] = "{:.2e}".format(round(float_value*0.9, 2))
                        property_details['modifier']['max'] = "{:.2e}".format(round(float_value*1.1, 2))
                        
                elif exponential == 'negative':
                    print("*"*25, 'negative exponential')
                    if float_value < 0:
                        property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 9))
                        property_details['modifier']['max'] = "{:.2e}".format(round(float_value*0.9, 9))
                        property_details['modifier']['min'] = "{:.2e}".format(round(float_value*1.1, 9))
                    else:
                        property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 9))
                        property_details['modifier']['min'] = "{:.2e}".format(round(float_value*0.9, 9))
                        property_details['modifier']['max'] = "{:.2e}".format(round(float_value*1.1, 9))
                    print(property_details)
                    
                else:
                    if value < 0:
                        property_details['modifier']['value'] = str(round(value, 2))
                        property_details['modifier']['max'] = str(round(value*0.9, 2))
                        property_details['modifier']['min'] = str(round(value*1.1, 2))
                    else:
                        property_details['modifier']['value'] = str(round(value, 2))
                        property_details['modifier']['min'] = str(round(value*0.9, 2))
                        property_details['modifier']['max'] = str(round(value*1.1, 2))
            else:
                property_details['modifier']['value'] = None
    except:
        values = p_metadata[3]
        unit = "" 
        if type(values)==list:
            value = random.choice(values)
            queries = [
                f"{property_name}-{value}{unit}",
                
                ####
                f"{property_name} {value}{unit}",
                f"{property_name} {value}{unit}",
                
                f"{property_name} of {value}{unit}",
                f"{property_name} = {value}{unit}",
                f"{property_name}={value}{unit}",
                f"{property_name} - {value}{unit}",
                
                f"{property_name}: {value}{unit}",
                f"{property_name} ({value}{unit})",
                f"{value}{unit} {property_name}",

                f"{property_name.replace(' ', '')} {value}{unit}",
                f"{property_name.replace(' ', '')} of {value}{unit}",

                ####
                f"{property_name} {value}{unit}",
                f"{property_name} {value}{unit}",
                
                f"{property_name} of {value}{unit}",
                f"{property_name} = {value}{unit}",
                f"{property_name}={value}{unit}",
                f"{property_name} - {value}{unit}",
                
                f"{property_name}: {value}{unit}",
                f"{property_name} ({value}{unit})",
                f"{value}{unit} {property_name}",

                f"{property_name.replace(' ', '')} {value}{unit}",
                f"{property_name.replace(' ', '')} of {value}{unit}",
            ]
            query = random.choice(queries)
            property_details = {"property_name": property_name_meaning, "modifier": {"value": value, "min": None, "max": None, "unit": unit.strip()}, "property_type": "ul_property"}

        
    query = re.sub("(\s+)", " ", query.strip().lower())

    return property_details, query

In [148]:
for i in range(1, 25):
    print(get_ul_property(), "\n")

({'property_name': 'ball pressure test', 'modifier': {'value': '1.96e+08', 'min': '1.76e+08', 'max': '2.15e+08', 'unit': None}, 'property_type': 'ul_property'}, 'ball pressure test around 1.96e+08')

({'property_name': 'outdoor suitability', 'modifier': {'value': 'f-2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'suitability = f-2')

({'property_name': 'detergent resistance', 'modifier': {'value': 'f4', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'detergent resis f4')

({'property_name': 'outdoor suitability', 'modifier': {'value': 'f-2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'outdoor suitability - f-2')

({'property_name': 'arc resistance', 'modifier': {'value': 'plc 4', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'arc resistant of plc 4')

({'property_name': 'dielectric strength', 'modifier': {'value': '28', 'min': '28', 'max': '50', 'unit': 'kilovolts per millimeter'}, 'property_type': 'ul_property'}, 'dielectrical strength from 28-50kilovolts per millimeter')

({'property_name': 'comparative tracking index (cti)', 'modifier': {'value': '115', 'min': '115', 'max': None, 'unit': None}, 'property_type': 'ul_property'}, 'comparative tracking index of minimum 115')

({'property_name': 'detergent resistance', 'modifier': {'value': 'f-3', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'f-3 dr')

({'property_name': 'high voltage arc tracking rate (hvtr)', 'modifier': {'value': 'plc-2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'high voltage arc tracking rate = plc-2')

({'property_name': 'comparative tracking index (cti)', 'modifier': {'value': '575', 'min': None, 'max': '575', 'unit': 'v'}, 'property_type': 'ul_property'}, 'comparative tracking index rating max 575 v')

({'property_name': 'dielectric strength', 'modifier': {'value': '43', 'min': '38.7', 'max': '47.3', 'unit': 'v/mm'}, 'property_type': 'ul_property'}, 'dielec str (43v/mm)')

({'property_name': 'high voltage arc tracking rate (hvtr)', 'modifier': {'value': 'plc3', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'high voltage rate of plc3')

({'property_name': 'comparative tracking index (cti)', 'modifier': {'value': 'plc1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'cti (plc1)')

({'property_name': 'inclined-plane tracking', 'modifier': {'value': '1.91', 'min': '1.91', 'max': None, 'unit': None}, 'property_type': 'ul_property'}, 'minimum of ipt 1.91')

({'property_name': 'dielectric strength', 'modifier': {'value': '39', 'min': '35.1', 'max': '42.9', 'unit': 'kv/mm'}, 'property_type': 'ul_property'}, 'di-electric str: 39 kv/mm around 10% margin')

({'property_name': 'non-halogenated material', 'modifier': {'value': 'compliant', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'nhm compliant')

({'property_name': 'arc resistance', 'modifier': {'value': 'plc2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'plc2 high voltage arc')

({'property_name': 'high voltage arc tracking rate (hvtr)', 'modifier': {'value': 'plc 2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'high vol arc tracking rate=plc 2')

({'property_name': 'detergent resistance', 'modifier': {'value': 'f3', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, 'detergent resis = f3')

({'property_name': 'inclined-plane tracking', 'modifier': {'value': '1.43', 'min': '1.12', 'max': '2.01', 'unit': 'kv'}, 'property_type': 'ul_property'}, 'ipt =1.43kv in the range of 1.12 - 2.01')

({'property_name': 'rohs 2011/65/eu material', 'modifier': {'value': '863-compliant', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_property'}, '2011/65/eu mat (863-compliant)')

({'property_name': 'inclined-plane tracking', 'modifier': {'value': '2.31', 'min': '2.08', 'max': '2.54', 'unit': None}, 'property_type': 'ul_property'}, 'inclined-plane=2.31')

({'property_name': 'dielectric strength', 'modifier': {'value': '23', 'min': '20.7', 'max': '25.3', 'unit': None}, 'property_type': 'ul_property'}, 'di strength close to 23')

({'property_name': 'dielectric strength', 'modifier': {'value': '12', 'min': '12', 'max': None, 'unit': None}, 'property_type': 'ul_property'}, 'dielectric strength >=12')

C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_6740\2640670372.py:21: DeprecationWarning: randrange() will raise TypeError in the future
  value = random.randrange(p_metadata[1],p_metadata[2])

### UL Sub-Property

In [149]:
ul_sub_properties = []
for item in ul_cert:
    if item['UL_PROPERTY']=="Minimum Thickness (mm)":
        sub_items = item['SUB_PROPERTIES']
        for sub_item in sub_items:
            if "Categorical_Values" in  sub_item.keys():
                ul_sub_properties.append((sub_item["UL_SUB_PROPERTY"].lower().replace("–", "-"),None,None,[x.lower() for x in sub_item["Categorical_Values"] if x],None,sub_item["UL_SUB_PROPERTY"].lower().replace("–", "-")))
            else:
                if sub_item["UNIT_OF_MEAS_SI"]:
                    ul_sub_properties.append((sub_item["UL_SUB_PROPERTY"].lower().replace("–", "-"), sub_item["Min_Value"], sub_item["Max_Value"], None, sub_item["UNIT_OF_MEAS_SI"].lower(),sub_item["UL_SUB_PROPERTY"].lower().replace("–", "-")))
                else:
                    ul_sub_properties.append((sub_item["UL_SUB_PROPERTY"].lower().replace("–", "-"), sub_item["Min_Value"], sub_item["Max_Value"], None, '',sub_item["UL_SUB_PROPERTY"].lower().replace("–", "-")))

In [150]:
ul_sub_properties

[('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - mechanical strength (rti str) (°c)'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index - mechanical impact (rti imp) (°c)'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - electrical (rti elec) (°c)'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow wire ignition temperature'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flammability index'),
 ('flame rating',
  None,
  None,
  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb'],
  None,
  'flame rating'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0 (120 seconds and longer)',
   'plc 1 (60 through 119 seconds)',
   'plc 2 (30 through 59 seconds)',
   'plc 3 (15 through 29 seconds)',
   'plc 4 (7 through 14 seconds)',
   'plc 5 (less than 7 seconds)'],
  None,
  'hot wire ignition (hwi)'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0 (120 and greater)',
   'plc 1 (60 - 119)',
   'plc 2 (30 - 59)',
   'plc 3 (15 - 29)',
   'plc 4 (less than 15)'],
  None,
  'high-current arc ignition (hai)'),
 ('flammability classification',
  None,
  None,
  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb', 'hb40', 'hb75'],
  None,
  'flammability classification')]

In [151]:
for ul_sub in ul_sub_properties:
    if ul_sub[3]:
        values = []
        for v in ul_sub[3]:
            values.append(v.split(" (")[0])
        values = [i for i in values if i not in ul_sub[3]]
        if values:
            ul_sub[3].extend(values)

ul_sub_properties

[('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - mechanical strength (rti str) (°c)'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index - mechanical impact (rti imp) (°c)'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - electrical (rti elec) (°c)'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow wire ignition temperature'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flammability index'),
 ('flame rating',
  None,
  None,
  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb'],
  None,
  'flame rating'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0 (120 seconds and longer)',
   'plc 1 (60 through 119 seconds)',
   'plc 2 (30 through 59 seconds)',
   'plc 3 (15 through 29 seconds)',
   'plc 4 (7 through 14 seconds)',
   'plc 5 (less than 7 seconds)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5'],
  None,
  'hot wire ignition (hwi)'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0 (120 and greater)',
   'plc 1 (60 - 119)',
   'plc 2 (30 - 59)',
   'plc 3 (15 - 29)',
   'plc 4 (less than 15)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4'],
  None,
  'high-current arc ignition (hai)'),
 ('flammability classification',
  None,
  None,
  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb', 'hb40', 'hb75'],
  None,
  'flammability classification')]

In [152]:
ul_sub_prop_names = []
for ul_sub in ul_sub_properties:
    ul_sub_prop_names.append(ul_sub[0].lower())

ul_sub_prop_names

['relative thermal index - mechanical strength (rti str) (°c)',
 'relative thermal index - mechanical impact (rti imp) (°c)',
 'relative thermal index - electrical (rti elec) (°c)',
 'glow wire ignition temperature',
 'glow wire flammability index',
 'flame rating',
 'hot wire ignition (hwi)',
 'high-current arc ignition (hai)',
 'flammability classification']

In [153]:
ul_sub_properties

[('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - mechanical strength (rti str) (°c)'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index - mechanical impact (rti imp) (°c)'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - electrical (rti elec) (°c)'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow wire ignition temperature'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flammability index'),
 ('flame rating',
  None,
  None,
  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb'],
  None,
  'flame rating'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0 (120 seconds and longer)',
   'plc 1 (60 through 119 seconds)',
   'plc 2 (30 through 59 seconds)',
   'plc 3 (15 through 29 seconds)',
   'plc 4 (7 through 14 seconds)',
   'plc 5 (less than 7 seconds)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5'],
  None,
  'hot wire ignition (hwi)'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0 (120 and greater)',
   'plc 1 (60 - 119)',
   'plc 2 (30 - 59)',
   'plc 3 (15 - 29)',
   'plc 4 (less than 15)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4'],
  None,
  'high-current arc ignition (hai)'),
 ('flammability classification',
  None,
  None,
  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb', 'hb40', 'hb75'],
  None,
  'flammability classification')]

In [154]:
ul_list_name_value.keys()

dict_keys(['arc resistance', 'ball pressure test', 'comparative tracking index (cti)', 'dielectric strength', 'dimensional change', 'flame rating', 'flammability classification', 'glow wire flammability index', 'glow wire ignition temperature', 'glow wire', 'high voltage arc tracking rate (hvtr)', 'high-current arc ignition (hai)', 'hot wire ignition (hwi)', 'inclined-plane tracking', 'non-halogenated material', 'outdoor suitability', 'detergent resistance', 'relative thermal index - electrical (rti elec) (°c)', 'relative thermal index - mechanical impact (rti imp) (°c)', 'relative thermal index - mechanical strength (rti str) (°c)', 'relative thermal index', 'rohs 2011/65/eu material', 'tensile impact strength'])

In [155]:
for i in ul_sub_properties:
    if i[0] == i[-1]:
        print(i[0], " | ", i[3], " | ", i[-1])

relative thermal index - mechanical strength (rti str) (°c)  |  None  |  relative thermal index - mechanical strength (rti str) (°c)
relative thermal index - mechanical impact (rti imp) (°c)  |  None  |  relative thermal index - mechanical impact (rti imp) (°c)
relative thermal index - electrical (rti elec) (°c)  |  None  |  relative thermal index - electrical (rti elec) (°c)
glow wire ignition temperature  |  None  |  glow wire ignition temperature
glow wire flammability index  |  None  |  glow wire flammability index
flame rating  |  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb']  |  flame rating
hot wire ignition (hwi)  |  ['plc 0 (120 seconds and longer)', 'plc 1 (60 through 119 seconds)', 'plc 2 (30 through 59 seconds)', 'plc 3 (15 through 29 seconds)', 'plc 4 (7 through 14 seconds)', 'plc 5 (less than 7 seconds)', 'plc 0', 'plc 1', 'plc 2', 'plc 3', 'plc 4', 'plc 5']  |  hot wire ignition (hwi)
high-current arc ignition (hai)  |  ['plc 0 (120 and greater)', 'plc 1 (60 - 119)', 'plc 2 (30 - 59)', 'plc 3 (15 - 29)', 'plc 4 (less than 15)', 'plc 0', 'plc 1', 'plc 2', 'plc 3', 'plc 4']  |  high-current arc ignition (hai)
flammability classification  |  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb', 'hb40', 'hb75']  |  flammability classification

In [156]:
extra_ul_subs = []
for ulp in ul_list_name_value:
    if ul_list_name_value[ulp]['has_thickness']:
        if ul_list_name_value[ulp]['values']:
            for syn in ul_list_name_value[ulp]['synonyms']:
                extra_ul_subs.append((ulp, None, None, ul_list_name_value[ulp]['values'], None, syn))
        elif ulp.lower() in ul_sub_prop_names:
            for ul_sub in ul_sub_properties:
                if ul_sub[0] == ulp:
                    for syn in ul_list_name_value[ulp]['synonyms']:
                        extra_ul_subs.append((ulp, ul_sub[1], ul_sub[2], ul_sub[3], ul_sub[4], syn))
        else:
            print("\n", ulp, False, "should we add?")

extra_ul_subs.extend([
    ('relative thermal index', 50, 240, None, '°c', 'relative thermal index'), 
    ('glow wire', 600, 100, None, '°c', 'glow wire')
]
)

ul_sub_properties.extend(extra_ul_subs)
ul_sub_properties

 glow wire False should we add?

 relative thermal index False should we add?

[('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - mechanical strength (rti str) (°c)'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index - mechanical impact (rti imp) (°c)'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - electrical (rti elec) (°c)'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow wire ignition temperature'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flammability index'),
 ('flame rating',
  None,
  None,
  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb'],
  None,
  'flame rating'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0 (120 seconds and longer)',
   'plc 1 (60 through 119 seconds)',
   'plc 2 (30 through 59 seconds)',
   'plc 3 (15 through 29 seconds)',
   'plc 4 (7 through 14 seconds)',
   'plc 5 (less than 7 seconds)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5'],
  None,
  'hot wire ignition (hwi)'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0 (120 and greater)',
   'plc 1 (60 - 119)',
   'plc 2 (30 - 59)',
   'plc 3 (15 - 29)',
   'plc 4 (less than 15)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4'],
  None,
  'high-current arc ignition (hai)'),
 ('flammability classification',
  None,
  None,
  ['5va', '5vb', 'v-0', 'v-1', 'v-2', 'hb', 'hb40', 'hb75'],
  None,
  'flammability classification'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame class rating'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'ul listed'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flammability class rating'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame rating'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame rated'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame rate'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flamerated'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flammability rating class'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame rating class'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flamerate'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flamerating'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'fr'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flammability rating'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  None,
  'flammability classification'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  None,
  'flammability class'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  None,
  'flame classification'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  None,
  'flame class'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  None,
  'flameclassification'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flammability index'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow-wire flammability'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flammability'),
 ('glow wire flammability index', 650, 960, None, '°c', 'gwf index'),
 ('glow wire flammability index', 650, 960, None, '°c', 'glow wire flame'),
 ('glow wire flammability index', 650, 960, None, '°c', 'gwfi'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flame index'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow-wire flammability index'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow wire ignition'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow-wire ignition temperature'),
 ('glow wire ignition temperature', 625, 985, None, '°c', 'gwit'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow wire temperature'),
 ('glow wire ignition temperature', 625, 985, None, '°c', 'gwi temp'),
 ('glow wire ignition temperature', 625, 985, None, '°c', 'glow wire temp'),
 ('glow wire ignition temperature', 625, 985, None, '°c', 'gwi temperature'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'flow wire ignition temperature'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high-current arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high-current ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'hai'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high current arc ignition (hai)'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'hcai'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'current ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high amp arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high amp'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high current arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high current arc'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high amperage arc ignition category'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high ampere arc ignition'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hot wire'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hot wire ignition'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hw ignition'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hot-wire ignition'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hwi'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hot wire ignition (hwi)'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - electrical (rti elec)'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - electrical'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index electrical'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rti electrical'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rtie'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index ele'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rti ele'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rti elec'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rti-e'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index - mechanical impact'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index - mechanical impact (rti imp)'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'rtii'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index mechanical impact'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'rti impact'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index impact'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'rti imp'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'rti-i'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index strength'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index mechanical strength'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index mechanical'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'rti-s'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'rti ms'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'rti strength'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - mechanical strength (rti str)'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'rti str'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - mechanical strength'),
 ('relative thermal index', 50, 240, None, '°c', 'relative thermal index'),
 ('glow wire', 600, 100, None, '°c', 'glow wire')]

In [157]:
ul_sub_properties_merge_values = {}
for i in ul_sub_properties:
    if i[3]:
        if i[0] in ul_sub_properties_merge_values:
            ul_sub_properties_merge_values[i[0]] += [x for x in i[3] if x not in ul_sub_properties_merge_values[i[0]]]
        else:
            ul_sub_properties_merge_values[i[0]] = i[3]
            
        # print(i)

ul_sub_properties_merge_values

{'flame rating': ['5va',
  '5vb',
  'v-0',
  'v-1',
  'v-2',
  'hb',
  'vo',
  'v0',
  'v1',
  'v2',
  '5 va',
  '5 vb',
  'v 0',
  'v 1',
  'v 2',
  'v-o',
  '5-va',
  '5-vb'],
 'hot wire ignition (hwi)': ['plc 0 (120 seconds and longer)',
  'plc 1 (60 through 119 seconds)',
  'plc 2 (30 through 59 seconds)',
  'plc 3 (15 through 29 seconds)',
  'plc 4 (7 through 14 seconds)',
  'plc 5 (less than 7 seconds)',
  'plc 0',
  'plc 1',
  'plc 2',
  'plc 3',
  'plc 4',
  'plc 5',
  'plc0',
  'plc1',
  'plc2',
  'plc3',
  'plc4',
  'plc5',
  'plc-0',
  'plc-1',
  'plc-2',
  'plc-3',
  'plc-4',
  'plc-5'],
 'high-current arc ignition (hai)': ['plc 0 (120 and greater)',
  'plc 1 (60 - 119)',
  'plc 2 (30 - 59)',
  'plc 3 (15 - 29)',
  'plc 4 (less than 15)',
  'plc 0',
  'plc 1',
  'plc 2',
  'plc 3',
  'plc 4',
  'plc0',
  'plc1',
  'plc2',
  'plc3',
  'plc4',
  'plc-0',
  'plc-1',
  'plc-2',
  'plc-3',
  'plc-4'],
 'flammability classification': ['5va',
  '5vb',
  'v-0',
  'v-1',
  'v-2',
  'hb',
  'hb40',
  'hb75',
  'vo',
  'v0',
  'v1',
  'v2',
  '5 va',
  '5 vb',
  'v 0',
  'v 1',
  'v 2',
  'hb 40',
  'hb 75',
  'vo',
  '5-va',
  '5-vb',
  'hb-40',
  'hb-75']}

In [158]:
len(ul_sub_properties[0])

6

In [159]:
ul_sub_properties2 = []
temp = []
for i in ul_sub_properties:
    if i[0] in ul_sub_properties_merge_values and i[0]==i[-1] and i[0] not in temp:
        temp.append(i[0])
        ul_sub_properties2.append((i[0], i[1], i[2], ul_sub_properties_merge_values[i[0]], i[4], i[5]))
    if i[0] in ul_sub_properties_merge_values and i[0]==i[-1] and i[0] in temp:
        pass
    else:
        if i not in ul_sub_properties2: 
             ul_sub_properties2.append(i)
ul_sub_properties2

[('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - mechanical strength (rti str) (°c)'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index - mechanical impact (rti imp) (°c)'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - electrical (rti elec) (°c)'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow wire ignition temperature'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flammability index'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'v-0',
   'v-1',
   'v-2',
   'hb',
   'vo',
   'v0',
   'v1',
   'v2',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb'],
  None,
  'flame rating'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0 (120 seconds and longer)',
   'plc 1 (60 through 119 seconds)',
   'plc 2 (30 through 59 seconds)',
   'plc 3 (15 through 29 seconds)',
   'plc 4 (7 through 14 seconds)',
   'plc 5 (less than 7 seconds)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hot wire ignition (hwi)'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0 (120 and greater)',
   'plc 1 (60 - 119)',
   'plc 2 (30 - 59)',
   'plc 3 (15 - 29)',
   'plc 4 (less than 15)',
   'plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high-current arc ignition (hai)'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'v-0',
   'v-1',
   'v-2',
   'hb',
   'hb40',
   'hb75',
   'vo',
   'v0',
   'v1',
   'v2',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'hb-40',
   'hb-75'],
  None,
  'flammability classification'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame class rating'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'ul listed'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flammability class rating'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame rated'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame rate'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flamerated'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flammability rating class'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flame rating class'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flamerate'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flamerating'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'fr'),
 ('flame rating',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'v-o',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2'],
  None,
  'flammability rating'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  None,
  'flammability class'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  None,
  'flame classification'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  None,
  'flame class'),
 ('flammability classification',
  None,
  None,
  ['5va',
   '5vb',
   'vo',
   'v0',
   'v1',
   'v2',
   'hb',
   'hb40',
   'hb75',
   '5 va',
   '5 vb',
   'v 0',
   'v 1',
   'v 2',
   'hb 40',
   'hb 75',
   'vo',
   '5-va',
   '5-vb',
   'v-0',
   'v-1',
   'v-2',
   'hb-40',
   'hb-75'],
  None,
  'flameclassification'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow-wire flammability'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flammability'),
 ('glow wire flammability index', 650, 960, None, '°c', 'gwf index'),
 ('glow wire flammability index', 650, 960, None, '°c', 'glow wire flame'),
 ('glow wire flammability index', 650, 960, None, '°c', 'gwfi'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow wire flame index'),
 ('glow wire flammability index',
  650,
  960,
  None,
  '°c',
  'glow-wire flammability index'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow wire ignition'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow-wire ignition temperature'),
 ('glow wire ignition temperature', 625, 985, None, '°c', 'gwit'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'glow wire temperature'),
 ('glow wire ignition temperature', 625, 985, None, '°c', 'gwi temp'),
 ('glow wire ignition temperature', 625, 985, None, '°c', 'glow wire temp'),
 ('glow wire ignition temperature', 625, 985, None, '°c', 'gwi temperature'),
 ('glow wire ignition temperature',
  625,
  985,
  None,
  '°c',
  'flow wire ignition temperature'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high-current arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high-current ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'hai'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high current arc ignition (hai)'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'hcai'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'current ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high amp arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high amp'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high current arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high current arc'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'arc ignition'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high amperage arc ignition category'),
 ('high-current arc ignition (hai)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4'],
  None,
  'high ampere arc ignition'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hot wire'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hot wire ignition'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hw ignition'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hot-wire ignition'),
 ('hot wire ignition (hwi)',
  None,
  None,
  ['plc 0',
   'plc 1',
   'plc 2',
   'plc 3',
   'plc 4',
   'plc 5',
   'plc0',
   'plc1',
   'plc2',
   'plc3',
   'plc4',
   'plc5',
   'plc-0',
   'plc-1',
   'plc-2',
   'plc-3',
   'plc-4',
   'plc-5'],
  None,
  'hwi'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - electrical (rti elec)'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - electrical'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index electrical'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rti electrical'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rtie'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index ele'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rti ele'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rti elec'),
 ('relative thermal index - electrical (rti elec) (°c)',
  50,
  240,
  None,
  '°c',
  'rti-e'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index - mechanical impact'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index - mechanical impact (rti imp)'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'rtii'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index mechanical impact'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'rti impact'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'relative thermal index impact'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'rti imp'),
 ('relative thermal index - mechanical impact (rti imp) (°c)',
  50,
  220,
  None,
  '°c',
  'rti-i'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index strength'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index mechanical strength'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index mechanical'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'rti-s'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'rti ms'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'rti strength'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - mechanical strength (rti str)'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'rti str'),
 ('relative thermal index - mechanical strength (rti str) (°c)',
  50,
  240,
  None,
  '°c',
  'relative thermal index - mechanical strength'),
 ('relative thermal index', 50, 240, None, '°c', 'relative thermal index'),
 ('glow wire', 600, 100, None, '°c', 'glow wire')]

In [160]:
len(ul_sub_properties), len(ul_sub_properties2)

(92, 88)

In [161]:
temp = []
duplicates = []
for i in ul_sub_properties2:
    if i[-1] not in temp:
        temp.append(i[-1])
    else:
        duplicates.append(i[-1])
        print(i[-1])

In [162]:
ul_sub_properties3 = []
for i in ul_sub_properties2:
    if i not in ul_sub_properties3:
        ul_sub_properties3.append(i)
        if i[-1] in duplicates:
            print(i)
    else:
        print(i)

print(len(ul_sub_properties2), len(ul_sub_properties3))

88 88

In [163]:
ul_sub_prop_syn_mapping

{'flame class rating': 'flame rating',
 'ul listed': 'flame rating',
 'flammability class rating': 'flame rating',
 'flame rating': 'flame rating',
 'flame rated': 'flame rating',
 'flame rate': 'flame rating',
 'flamerated': 'flame rating',
 'flame': 'flame rating',
 'flammability rating class': 'flame rating',
 'flame rating class': 'flame rating',
 'flamerate': 'flame rating',
 'flamerating': 'flame rating',
 'fr': 'flame rating',
 'flammability rating': 'flame rating',
 'flammability classification': 'flammability classification',
 'flammability class': 'flammability classification',
 'flame classification': 'flammability classification',
 'flame class': 'flammability classification',
 'flameclassification': 'flammability classification',
 'glow wire flammability index': 'glow wire flammability index',
 'glow-wire flammability': 'glow wire flammability index',
 'glow wire flammability': 'glow wire flammability index',
 'gwf index': 'glow wire flammability index',
 'glow wire flame': 'glow wire flammability index',
 'gwfi': 'glow wire flammability index',
 'glow wire flame index': 'glow wire flammability index',
 'glow-wire flammability index': 'glow wire flammability index',
 'glow wire ignition': 'glow wire ignition temperature',
 'glow-wire ignition temperature': 'glow wire ignition temperature',
 'gwit': 'glow wire ignition temperature',
 'glow wire temperature': 'glow wire ignition temperature',
 'gwi temp': 'glow wire ignition temperature',
 'glow wire temp': 'glow wire ignition temperature',
 'gwi temperature': 'glow wire ignition temperature',
 'flow wire ignition temperature': 'glow wire ignition temperature',
 'glow wire': 'glow wire',
 'glow wire test': 'glow wire',
 'high-current arc ignition': 'high-current arc ignition (hai)',
 'high-current ignition': 'high-current arc ignition (hai)',
 'hai': 'high-current arc ignition (hai)',
 'high arc ignition': 'high-current arc ignition (hai)',
 'high current arc ignition (hai)': 'high-current arc ignition (hai)',
 'hcai': 'high-current arc ignition (hai)',
 'current ignition': 'high-current arc ignition (hai)',
 'high amp arc ignition': 'high-current arc ignition (hai)',
 'high amp': 'high-current arc ignition (hai)',
 'high current arc ignition': 'high-current arc ignition (hai)',
 'high current arc': 'high-current arc ignition (hai)',
 'arc ignition': 'high-current arc ignition (hai)',
 'high amperage arc ignition category': 'high-current arc ignition (hai)',
 'high ampere arc ignition': 'high-current arc ignition (hai)',
 'hot wire': 'hot wire ignition (hwi)',
 'hot wire ignition': 'hot wire ignition (hwi)',
 'hw ignition': 'hot wire ignition (hwi)',
 'hot-wire ignition': 'hot wire ignition (hwi)',
 'hwi': 'hot wire ignition (hwi)',
 'hot wire ignition (hwi)': 'hot wire ignition (hwi)',
 'relative thermal index - electrical (rti elec)': 'relative thermal index - electrical (rti elec) (°c)',
 'relative thermal index - electrical': 'relative thermal index - electrical (rti elec) (°c)',
 'relative thermal index electrical': 'relative thermal index - electrical (rti elec) (°c)',
 'rti electrical': 'relative thermal index - electrical (rti elec) (°c)',
 'rtie': 'relative thermal index - electrical (rti elec) (°c)',
 'relative thermal index ele': 'relative thermal index - electrical (rti elec) (°c)',
 'rti ele': 'relative thermal index - electrical (rti elec) (°c)',
 'rti elec': 'relative thermal index - electrical (rti elec) (°c)',
 'rti-e': 'relative thermal index - electrical (rti elec) (°c)',
 'relative thermal index - mechanical impact': 'relative thermal index - mechanical impact (rti imp) (°c)',
 'relative thermal index - mechanical impact (rti imp)': 'relative thermal index - mechanical impact (rti imp) (°c)',
 'rtii': 'relative thermal index - mechanical impact (rti imp) (°c)',
 'relative thermal index mechanical impact': 'relative thermal index - mechanical impact (rti imp) (°c)',
 'rti impact': 'relative thermal index - mechanical impact (rti imp) (°c)',
 'relative thermal index impact': 'relative thermal index - mechanical impact (rti imp) (°c)',
 'rti imp': 'relative thermal index - mechanical impact (rti imp) (°c)',
 'rti-i': 'relative thermal index - mechanical impact (rti imp) (°c)',
 'relative thermal index strength': 'relative thermal index - mechanical strength (rti str) (°c)',
 'relative thermal index mechanical strength': 'relative thermal index - mechanical strength (rti str) (°c)',
 'relative thermal index mechanical': 'relative thermal index - mechanical strength (rti str) (°c)',
 'rti-s': 'relative thermal index - mechanical strength (rti str) (°c)',
 'rti ms': 'relative thermal index - mechanical strength (rti str) (°c)',
 'rti strength': 'relative thermal index - mechanical strength (rti str) (°c)',
 'relative thermal index - mechanical strength (rti str)': 'relative thermal index - mechanical strength (rti str) (°c)',
 'rti str': 'relative thermal index - mechanical strength (rti str) (°c)',
 'relative thermal index - mechanical strength': 'relative thermal index - mechanical strength (rti str) (°c)',
 'rti': 'relative thermal index',
 'relative thermal index': 'relative thermal index'}

In [164]:
def get_ul_sub_property(default=None):
    if default==None:
        default = random.choice([True, False])
        
    p_metadata = random.choice(ul_sub_properties)
    property_name = p_metadata[-1].lower()
    if property_name in ul_sub_prop_syn_mapping:
        property_name_meaning = ul_sub_prop_syn_mapping[property_name]
    else:
        property_name_meaning = property_name

    value_only_prop = {
        'flammability classification': ['hb-40', 'hb-75'], 
        'flame rating': ['5va', '5vb', 'hb', '5 va', '5 vb', '5-va', '5-vb', '5va', '5vb', 'hb', '5 va', '5 vb', '5-va', '5-vb', 'v-1', 'v-2', 'v1', 'v2', 'v 1', 'v 2',]
    }
    if property_name_meaning in value_only_prop:
        only_value = random.choice([True, False, False])
    else:
        only_value = False

    if default:
        try:    
            min_value = None
            max_value = None
            unit = ''
            exponential = ''
            
            range_type = random.choice(['value', 'value', 'value', 'min_value', 'max_value', 'value_range', 'range_without_value', 'range_percent'])
            
            sub_property_details = {'property_name': None, 'modifier': {'value': None, 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}
            single_space_pattern = '(\s+)'
            try:    
                value = random.randrange(p_metadata[1],p_metadata[2])
            except: 
                value = round(random.uniform(p_metadata[1], p_metadata[2]),2)
                
            if p_metadata[4] != '°c':
                value = random.choice([value, value, value, value, value, value, value, value, value, value, value, value, value, value, random.randrange(100000, 1000000000)])
            
            if value > 899999:
                # print("*"*20, "{:.2e}".format(value))
                float_value = value
                value = "{:.2e}".format(value)
                exponential = 'positive'
            
            while value==0.0:
                value = round(random.uniform(p_metadata[1], p_metadata[2]), 9)
                print("$"*20, f"value was 0.0 for property range {p_metadata[1]} to {p_metadata[2]}, picking another random number: {value}")
                # print("#"*20, "{:.8f}".format(value))
                if -0.99999999999 < value < 0.99999999999:
                    float_value = value
                    value = "{:.2e}".format(value)
                    # value = "{:.8f}".format(value)
                    exponential = 'negative'
                else:
                    value = round(value, 2)
                    
            unit = random.choice([p_metadata[4],f" {p_metadata[4]}", ""])
            if not unit.strip():
                unit=''
                    
            if not value:
                # print(f"could not find the value for {property_name_meaning}: {property_name}")
                value = random.randint(20, 200)
                
            is_unit_syn = random.choice([False, False, True])
            if unit and is_unit_syn and unit in unit_syns :
                # print("unit synonym")
                unit = random.choice(unit_syns[unit])
                
            if range_type=='min_value':
                try:
                    if value < 0:
                        max_value, min_value = get_random_range(float(value))
                    else:
                        min_value, max_value = get_random_range(float(value))
                except:
                    min_value, max_value = get_random_range(random.randint(20, 2000))
                    
                value = None
                max_value = None
                queries = [
                    f"{property_name} of min {min_value}{unit}",
                    f"{property_name} of minimum {min_value}{unit}",
                    f"minimum of {property_name} {min_value}{unit}",
                    f"{property_name} min {min_value}{unit}",
                    f"{property_name} minimum {min_value}{unit}",           
                    f"minimum {property_name} {min_value}{unit}",
                    
                    f"{property_name} more than {min_value}{unit}",
                    f"{property_name} greater than {min_value}{unit}",
                    f"{property_name} greater than {min_value}{unit}",
                    f"{property_name} more than or eaual to {min_value}{unit}",
                    f"{property_name} greater than or equal to {min_value}{unit}",
                    f"{property_name} greater than or equal to {min_value}{unit}",
                    f"{property_name} >{min_value}{unit}",
                    f"{property_name} > {min_value}{unit}",
                    f"{property_name} >={min_value}{unit}",
                    f"{property_name} >= {min_value}{unit}",
                ]
                query = random.choice(queries)
            elif range_type=='max_value':
                try:
                    if value < 0:
                        max_value, min_value = get_random_range(float(value))
                    else:
                        min_value, max_value = get_random_range(float(value))
                except:
                    min_value, max_value = get_random_range(random.randint(20, 2000))
                    
                value = None
                min_value = None
                queries = [
                    f"{property_name} of max {max_value}{unit}",
                    f"{property_name} of maximum {max_value}{unit}",
                    f"maximum of {property_name} {max_value}{unit}",
                    f"{property_name} max {max_value}{unit}",
                    f"{property_name} maximum {max_value}{unit}",
                    f"maximum {property_name} {max_value}{unit}",
                    
                    f"{property_name} lesser than {max_value}{unit}",
                    f"{property_name} less than {max_value}{unit}",
                    f"{property_name} lesser than or equal to {max_value}{unit}",
                    f"{property_name} less than or equal to {max_value}{unit}",
                    f"{property_name} <{max_value}{unit}",
                    f"{property_name} < {max_value}{unit}",
                    f"{property_name} <={max_value}{unit}",
                    f"{property_name} <= {max_value}{unit}",
                ]
                query = random.choice(queries)   
            else:
                queries = [
                    f"{property_name} {value}{unit}",
                    f"{property_name} {value}{unit}",
            
                    f"{property_name} of {value}{unit}",
                    f"{property_name} = {value}{unit}",
                    f"{property_name} - {value}{unit}",
                    f"{property_name}: {value}{unit}",
                    f"{property_name} ({value}{unit})",
                    f"{value}{unit} {property_name}",
            
                    f"{property_name} {value}{unit}",
                    f"{property_name} {value}{unit}",
            
                    f"{property_name} of {value}{unit}",
                    f"{property_name} = {value}{unit}",
                    f"{property_name} - {value}{unit}",
                    f"{property_name}: {value}{unit}",
                    f"{property_name} ({value}{unit})",
                    f"{value}{unit} {property_name}",
            
                    f"{re.sub(single_space_pattern, ' ', re.sub('[^A-Za-z0-9]+', ' ', property_name).strip())} = {value}{unit}",
                    f"{re.sub(single_space_pattern, ' ', re.sub('[^A-Za-z0-9]+', ' ', property_name).strip())} ={value}{unit}",
            
                ]
            
                if range_type == 'value':
                    queries += [
                        f"{property_name} of approximately {value}{unit}",
                        f"{property_name} of approx {value}{unit}",
                        f"{property_name} close to {value}{unit}",
                        f"{property_name} around {value}{unit}",
                    ]
            
                query = random.choice(queries)
                if random.choice(range(0, 10)) == 1 and property_name:
                    query = f"{property_name.replace(' ', '')}={value}{unit}"
            #         print(f"cant remove space for {property_name}")
            
                if not " " in property_name and not exponential and value > 0:
                    query2 = random.choice([
                        f"{property_name}{value}",
                        f"{property_name}-{value}",
                        f"{value}{property_name}",
                        f"{property_name}={value}",
                    ])
                    is_unit = random.choice([True, True, True, False, False])
                    if not is_unit:
                        query = query2
                        unit = ''
            
                if not exponential and range_type != 'value' and value > 0:
                    min_value, max_value = get_random_range(float(value))
                    query3 = random.choice([       
                        f"{property_name} of {value}{unit}",
                        f"{property_name} {value}{unit}",
                        f"{property_name} ({value}{unit})",
                        f"{property_name} ={value}{unit}",
                        f"{property_name} = {value}{unit}",
                        f"{property_name} - {value}{unit}",
                        f"{property_name}: {value}{unit}",
                    ])
            
                    if range_type == 'value_range': 
                        range_query = random.choice([
                            f" from {min_value} to {max_value}",
                            f" from {min_value} - {max_value}",
                            f" from {min_value}-{max_value}",
                            f" between {min_value} to {max_value}",
                            f" between {min_value} - {max_value}",
                            f" between {min_value}-{max_value}",
                            f" between {min_value} and {max_value}",
                            f" in the range of {min_value} to {max_value}",
                            f" in the range of {min_value} - {max_value}",
                            f" in the range of {min_value}-{max_value}",
                        ])
                        query = query3 + range_query
                    elif range_type == 'range_without_value':
                        range_query = random.choice([
                            f" from {min_value} to {max_value}",
                            f" from {min_value} - {max_value}",
                            f" from {min_value}-{max_value}",
                            f" {min_value}-{max_value}",
                            f" {min_value} - {max_value}",
                            f" {min_value} to {max_value}",
                            f" between {min_value} to {max_value}",
                            f" between {min_value} - {max_value}",
                            f" between {min_value}-{max_value}",
                            f" between {min_value} and {max_value}",
                            f" in the range of {min_value} to {max_value}",
                            f" in the range of {min_value} - {max_value}",
                            f" in the range of {min_value}-{max_value}",
                        ])
                        query = f"{property_name}" + range_query + f"{unit}"
            
                    elif range_type == 'range_percent':
                        percent, min_value, max_value = get_random_percent(value)
                        range_percent_query = random.choice([
                            f" with {percent}% range",
                            f" with +/-{percent}% range",
                            f" of +/-{percent}% range",
                            f" of -/+{percent}% range",
                            f" around {percent}% variation",
                            f" around {percent}% range",
                            f" around {percent}% margin",
            #                 f" close to a {percent}% variation",
            #                 f" close to a {percent}% range",
            #                 f" close to a {percent}% margin",
                            f" in the vicinity of {percent}%",
                            f" in the range of {percent}%",
                            f" within a range of {percent}%",
                            f" within {percent}% range",
                            f" within {percent}% margin",
                            ])
            
                        query = query3 + range_percent_query
                    else:
                        print("@"*40, range_type)
                else:
                    range_type = 'value'
                
            sub_property_details['property_name'] = property_name_meaning
            
            sub_property_details['modifier']['unit'] = unit.strip().lower()
            if not sub_property_details['modifier']['unit']:
                sub_property_details['modifier']['unit'] = None
            
            # no range queries for exponential queries
            if range_type == 'min_value':
                sub_property_details['modifier']['min'] =  str(round(min_value, 2))
                sub_property_details['modifier']['max'] =  None
                sub_property_details['modifier']['value'] = sub_property_details['modifier']['min']
            
            elif range_type == 'max_value':
                sub_property_details['modifier']['max'] = str(round(max_value, 2))
                sub_property_details['modifier']['min'] =  None
                sub_property_details['modifier']['value'] = sub_property_details['modifier']['max']
            
            elif range_type in ['value_range', 'range_percent']:
                sub_property_details['modifier']['value'] = str(round(value, 2))
                sub_property_details['modifier']['min'] = str(round(min_value, 2))
                sub_property_details['modifier']['max'] = str(round(max_value, 2))
                
            elif range_type == 'range_without_value':
                sub_property_details['modifier']['min'] = str(round(min_value, 2))
                sub_property_details['modifier']['max'] = str(round(max_value, 2))
                sub_property_details['modifier']['value'] = sub_property_details['modifier']['min'] 
            else:
                if value:
                    if exponential == 'positive':
                        # print("#"*25, 'positive')
                        if float_value < 0:
                            sub_property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 2))
                            sub_property_details['modifier']['max'] = "{:.2e}".format(round(float_value*0.9, 2))
                            sub_property_details['modifier']['min'] = "{:.2e}".format(round(float_value*1.1, 2))
                        else:
                            sub_property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 2))
                            sub_property_details['modifier']['min'] = "{:.2e}".format(round(float_value*0.9, 2))
                            sub_property_details['modifier']['max'] = "{:.2e}".format(round(float_value*1.1, 2))
                            
                    elif exponential == 'negative':
                        print("*"*25, 'negative exponential')
                        if float_value < 0:
                            sub_property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 9))
                            sub_property_details['modifier']['max'] = "{:.2e}".format(round(float_value*0.9, 9))
                            sub_property_details['modifier']['min'] = "{:.2e}".format(round(float_value*1.1, 9))
                        else:
                            sub_property_details['modifier']['value'] = "{:.2e}".format(round(float_value, 9))
                            sub_property_details['modifier']['min'] = "{:.2e}".format(round(float_value*0.9, 9))
                            sub_property_details['modifier']['max'] = "{:.2e}".format(round(float_value*1.1, 9))
                        print(sub_property_details)
                        
                    else:
                        if value < 0:
                            sub_property_details['modifier']['value'] = str(round(value, 2))
                            sub_property_details['modifier']['max'] = str(round(value*0.9, 2))
                            sub_property_details['modifier']['min'] = str(round(value*1.1, 2))
                        else:
                            sub_property_details['modifier']['value'] = str(round(value, 2))
                            sub_property_details['modifier']['min'] = str(round(value*0.9, 2))
                            sub_property_details['modifier']['max'] = str(round(value*1.1, 2))
                else:
                    sub_property_details['modifier']['value'] = None
    

            property_details = [sub_property_details, {"property_name": "minimum thickness (mm)", "modifier": {"value": '0.4', "min": None, "max": None, "unit": 'mm'}, "property_type": "ul_property"}]
        except:
            values = p_metadata[3]
            unit = "" 
            if type(values)==list:
                value = random.choice(values)
                if only_value and property_name_meaning in value_only_prop:
                    # print(f"adding only value for ul sub property {property_name_meaning}")
                    value = random.choice(value_only_prop[property_name_meaning])
                    query = str(value)
                    if value == 'vo':
                        value = 'v0'
                    elif value =='v-o':
                        value = 'v-0'
                    property_details = [{"property_name": property_name_meaning, "modifier": {"value": value, "min": None, "max": None, "unit": unit.strip()}, "property_type": "ul_sub_property"}, {"property_name": "minimum thickness (mm)", "modifier": {"value": '0.4', "min": None, "max": None, "unit": 'mm'}, "property_type": "ul_property"}]
                else:
                    queries = [
                        f"{property_name}-{value}{unit}",
                        
                        ####
                        f"{property_name} {value}{unit}",
                        f"{property_name} {value}{unit}",
                        
                        f"{property_name} of {value}{unit}",
                        f"{property_name} = {value}{unit}",
                        f"{property_name}={value}{unit}",
                        f"{property_name} - {value}{unit}",
                        
                        f"{property_name}: {value}{unit}",
                        f"{property_name} ({value}{unit})",
                        f"{value}{unit} {property_name}",
        
                        f"{property_name.replace(' ', '')} {value}{unit}",
                        f"{property_name.replace(' ', '')} of {value}{unit}",
        
                        ####
                        f"{property_name} {value}{unit}",
                        f"{property_name} {value}{unit}",
                        
                        f"{property_name} of {value}{unit}",
                        f"{property_name} = {value}{unit}",
                        f"{property_name}={value}{unit}",
                        f"{property_name} - {value}{unit}",
                        
                        f"{property_name}: {value}{unit}",
                        f"{property_name} ({value}{unit})",
                        f"{value}{unit} {property_name}",
        
                        f"{property_name.replace(' ', '')} {value}{unit}",
                        f"{property_name.replace(' ', '')} of {value}{unit}",
                    ]
                    query = random.choice(queries)
                    if value == 'vo':
                        value = 'v0'
                    elif value =='v-o':
                        value = 'v-0'
                    property_details = [{"property_name": property_name_meaning, "modifier": {"value": value, "min": None, "max": None, "unit": unit.strip()}, "property_type": "ul_sub_property"}, {"property_name": "minimum thickness (mm)", "modifier": {"value": '0.4', "min": None, "max": None, "unit": 'mm'}, "property_type": "ul_property"}]

    
    else:
        thickness_values = [0.1,0.3,0.5,0.6,0.7,0.8,0.9,1,1.2,1.3,1.5,1.6,2,2.2,3,3.1,3.5,3,5,6]
    
        try:
            try:    value = random.randrange(p_metadata[1],p_metadata[2])
            except: value = round(random.uniform(p_metadata[1], p_metadata[2]),2)
            unit = random.choice([p_metadata[4],f" {p_metadata[4]}","",""])
            if not unit:
                unit=""
            thickness = random.choice(thickness_values)
            queries = [
                f"{property_name} {value}{unit} at {thickness}mm",
                f"{property_name} at {thickness}mm {value}{unit}",
                f"{property_name} at {thickness}mm of {value}{unit}",
                f"{property_name} at {thickness} {value}{unit}",
                f"{property_name} at {thickness} of {value}{unit}",

                f"{property_name} @ {thickness} {value}{unit}",
                f"{property_name} @ {thickness} of {value}{unit}",
                
                f"{property_name} {thickness}mm of {value}{unit}",
                f"{property_name} {value}{unit}, {thickness}mm thickness",
                f"{property_name} {value}{unit} {thickness}mm thick.",
                f"min thickness {thickness}, {value}{unit} {property_name}",
                f"{value}{unit} {property_name} @ {thickness}mm",

                f"{property_name.replace(' ', '')} {value}{unit} at {thickness}mm",
                f"{value}{unit} {property_name.replace(' ', '')} @ {thickness}mm",
            ]
            query = random.choice(queries)
            property_details = [{"property_name": property_name_meaning, "modifier": {"value": value, "min": round(value-value*10/100,2), "max": round(value+value*10/100,2), "unit": unit.strip()}, "property_type": "ul_sub_property"}, {"property_name": "minimum thickness (mm)", "modifier": {"value": str(thickness), "min": None, "max": None, "unit": 'mm'}, "property_type": "ul_property"}]
        except:
            values = p_metadata[3]
            unit = "" 
            if type(values)==list:
                value = random.choice(values)
                thickness = random.choice(thickness_values)
                if only_value and property_name_meaning in value_only_prop:
                    # print(f"adding only value for ul sub property {property_name_meaning}")
                    value = random.choice(value_only_prop[property_name_meaning])
                    queries = [
                        f"{value}{unit} at {thickness}mm",
                        f"{thickness}mm {value}{unit}",
                        f"{thickness}mm {value}{unit}",
                        f"{thickness} {value}{unit}",
                        
                        f"{value}{unit}, {thickness}mm thickness",
                        f"{value}{unit} {thickness}mm thickness",
                        f"{value}{unit} {thickness}mm thick.",
                        f"min thickness {thickness}, {value}{unit}",
                        f"min thickness {thickness} {value}{unit}",
                        f"{value}{unit} @ {thickness}mm",
                    ]
                    query = random.choice(queries)
                    if value == 'vo':
                        value = 'v0'
                    elif value =='v-o':
                        value = 'v-0'
                    property_details = [{"property_name": property_name_meaning, "modifier": {"value": value, "min": None, "max": None, "unit": ''}, "property_type": "ul_sub_property"}, {"property_name": "minimum thickness (mm)", "modifier": {"value": str(thickness), "min": None, "max": None, "unit": 'mm'}, "property_type": "ul_property"}]
                else:
                    queries = [
                        f"{property_name} {value}{unit} at {thickness}mm",
                        f"{property_name} at {thickness}mm {value}{unit}",
                        f"{property_name} at {thickness}mm of {value}{unit}",
                        f"{property_name} at {thickness} {value}{unit}",
                        f"{property_name} at {thickness} of {value}{unit}",
        
                        f"{property_name} @ {thickness} {value}{unit}",
                        f"{property_name} @ {thickness} of {value}{unit}",
                        
                        f"{property_name} {thickness}mm of {value}{unit}",
                        f"{property_name} {value}{unit}, {thickness}mm thickness",
                        f"{property_name} {value}{unit} {thickness}mm thick.",
                        f"min thickness {thickness}, {value}{unit} {property_name}",
                        f"{value}{unit} {property_name} @ {thickness}mm",
                        
                        f"{property_name.replace(' ', '')} {value}{unit} at {thickness}mm",
                        f"{value}{unit} {property_name.replace(' ', '')} @ {thickness}mm",
                    ]
                    query = random.choice(queries)
                    if value == 'vo':
                        value = 'v0'
                    elif value =='v-o':
                        value = 'v-0'
                        
                    property_details = [{"property_name": property_name_meaning, "modifier": {"value": value, "min": None, "max": None, "unit": unit.strip()}, "property_type": "ul_sub_property"}, {"property_name": "minimum thickness (mm)", "modifier": {"value": str(thickness), "min": None, "max": None, "unit": 'mm'}, "property_type": "ul_property"}]

    
    return property_details, query

In [165]:
for i in range(1, 100):
    print(get_ul_sub_property(), "\n")

([{'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': 216, 'min': 194.4, 'max': 237.6, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.7', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], '216 relative thermal index impact @ 0.7mm')

([{'property_name': 'glow wire flammability index', 'modifier': {'value': 658, 'min': 592.2, 'max': 723.8, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.8', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'gwfindex 658 at 0.8mm')

([{'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': '116', 'min': '86', 'max': '147', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index - electrical: 116 from 86-147')

([{'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': '69', 'min': '69', 'max': None, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'minimum of relative thermal index ele 69 °c')

([{'property_name': 'flame rating', 'modifier': {'value': '5 va', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], '5 va')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc 1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'hai: plc 1')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': 152, 'min': 136.8, 'max': 167.2, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '3', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], '152 relative thermal index mechanical strength @ 3mm')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc-2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.8', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'high arc ignition 0.8mm of plc-2')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc-3', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.1', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'high current arc ignition plc-3 at 0.1mm')

([{'property_name': 'flame rating', 'modifier': {'value': 'v0', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.1', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'flame rating class v0 at 0.1mm')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc4', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.1', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'arc ignition @ 0.1 plc4')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc 4', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'highamparcignition of plc 4')

([{'property_name': 'flame rating', 'modifier': {'value': '5vb', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.5', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'flamerated at 0.5 of 5vb')

([{'property_name': 'glow wire flammability index', 'modifier': {'value': 897, 'min': 807.3, 'max': 986.7, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '2.2', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow wire flame index 897, 2.2mm thickness')

([{'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': 185, 'min': 166.5, 'max': 203.5, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '6', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'rti elec @ 6 of 185 °c')

([{'property_name': 'hot wire ignition (hwi)', 'modifier': {'value': 'plc5', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.6', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'hot wire ignition at 0.6 of plc5')

([{'property_name': 'flame rating', 'modifier': {'value': 'v1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'flame class rating v1')

([{'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': '178', 'min': '160.2', 'max': '195.8', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'rti ele 178 °c')

([{'property_name': 'flame rating', 'modifier': {'value': '5 vb', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], '5 vb')

([{'property_name': 'glow wire flammability index', 'modifier': {'value': 807, 'min': 726.3, 'max': 887.7, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '1.5', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow-wire flammability index at 1.5mm of 807')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'high amperage arc ignition category plc1')

([{'property_name': 'flame rating', 'modifier': {'value': 'v-2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.6', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'flamerated at 0.6 of v-2')

([{'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': '99', 'min': '99', 'max': None, 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'rtii >99')

([{'property_name': 'glow wire flammability index', 'modifier': {'value': '738', 'min': '664.2', 'max': '811.8', 'unit': '°f'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow wire flammability index of 738°f')

([{'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': 199, 'min': 179.1, 'max': 218.9, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '1.2', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index - mechanical impact (rti imp) 199 1.2mm thick.')

([{'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': 204, 'min': 183.6, 'max': 224.4, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '3', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'rti-e 3mm of 204 °c')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '139', 'min': '97.3', 'max': '180.7', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'rti-s (139 °c) with +/-30% range')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': 66, 'min': 59.4, 'max': 72.6, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '2.2', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relativethermalindex-mechanicalstrength 66 at 2.2mm')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '102', 'min': '91.8', 'max': '112.2', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index - mechanical strength (rti str) (°c) - 102')

([{'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': '109', 'min': '71', 'max': '148', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index - mechanical impact (rti imp): 109 between 71-148')

([{'property_name': 'glow wire flammability index', 'modifier': {'value': '594', 'min': '594', 'max': '832', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow-wire flammability index between 594 and 832°c')

([{'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': '131', 'min': '131', 'max': '268', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index - electrical in the range of 131 to 268')

([{'property_name': 'flammability classification', 'modifier': {'value': 'v1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '6', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'flammability class @ 6 of v1')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '94', 'min': '94', 'max': None, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'rti strength greater than or equal to 94 °c')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc 0', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'high ampere arc ignition=plc 0')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc0', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'plc0 high-current arc ignition (hai)')

([{'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': '127', 'min': '114.3', 'max': '139.7', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index electrical rti elec =127°c')

([{'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': 126, 'min': 113.4, 'max': 138.6, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '3.1', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index - mechanical impact at 3.1 of 126')

([{'property_name': 'hot wire ignition (hwi)', 'modifier': {'value': 'plc-0', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'hw ignition plc-0')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '207', 'min': '186.3', 'max': '227.7', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'rti ms 207°c')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '3.1', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'min thickness 3.1, plc2 high amp')

([{'property_name': 'flame rating', 'modifier': {'value': 'v1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '1', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'v1 @ 1mm')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc-1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'arc ignition plc-1')

([{'property_name': 'flame rating', 'modifier': {'value': '5 vb', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'ullisted of 5 vb')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.5', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'plc2 highamparcignition @ 0.5mm')

([{'property_name': 'glow wire flammability index', 'modifier': {'value': 697, 'min': 627.3, 'max': 766.7, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '1.6', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow wire flammability 697, 1.6mm thickness')

([{'property_name': 'relative thermal index', 'modifier': {'value': 68, 'min': 61.2, 'max': 74.8, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.5', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], '68 relative thermal index @ 0.5mm')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '193', 'min': '173.7', 'max': '212.3', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index - mechanical strength around 193')

([{'property_name': 'flame rating', 'modifier': {'value': '5-vb', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '2.2', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'flammability rating 2.2mm of 5-vb')

([{'property_name': 'glow wire flammability index', 'modifier': {'value': '810', 'min': '729.0', 'max': '891.0', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'gwf index = 810 °c in the vicinity of 10%')

([{'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': '103', 'min': '92.7', 'max': '113.3', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'rti impact =103°c')

([{'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': 104, 'min': 93.6, 'max': 114.4, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '1.6', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relativethermalindexmechanicalimpact 104 at 1.6mm')

([{'property_name': 'flame rating', 'modifier': {'value': 'v-1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'flameclassrating v-1')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '71', 'min': '63.9', 'max': '78.1', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.4', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index strength 71')

([{'property_name': 'hot wire ignition (hwi)', 'modifier': {'value': 'plc5', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.9', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'hot wire at 0.9 of plc5')

([{'property_name': 'flame rating', 'modifier': {'value': 'v 2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.6', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'v 2 flame @ 0.6mm')


#### Multi UL Sub-Properties

In [166]:
def get_ul_sub_properties():
    pdetails, q = [], ''
    pd1, q1 = get_ul_sub_property(True)
    pd2, q2 = get_ul_sub_property(False)
    
    pdetails = []
    if pd2[0]['property_name'] != pd1[0]['property_name'] == pd1[0]['property_name']!= 'minimum thickness (mm)':
        num = random.choice([1, 1, 2])
        if num==1:
            q = random.choice([
                f"{q1} {q2}",
                f"{q1}, {q2}",
                f"{q1} and {q2}",
            ])
            pdetails.append(pd1[0]) 
            pdetails.append(pd2[0]) 
        else:
            q = random.choice([
                f"{q2} {q1}",
                f"{q2}, {q1}",
                f"{q2} and {q1}",
            ])
            pdetails.append(pd2[0]) 
            pdetails.append(pd1[0]) 
            
        pdetails.append(pd2[1])
    else:
        print("got same properties")
        pdetails, q = get_ul_sub_properties()
        
    return pdetails, q

In [167]:
for i in range(1, 20):
    print(get_ul_sub_properties(), "\n")

([{'property_name': 'hot wire ignition (hwi)', 'modifier': {'value': 'plc-3', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'glow wire flammability index', 'modifier': {'value': '896', 'min': None, 'max': '896', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.9', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'hot-wire ignition at 0.9mm of plc-3, glow wire flammability index lesser than or equal to 896')

([{'property_name': 'flame rating', 'modifier': {'value': 'v1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc 4', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '2.2', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'v1, current ignition at 2.2 plc 4')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '121', 'min': '81', 'max': '160', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'flame rating', 'modifier': {'value': '5 vb', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '2.2', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index - mechanical strength of 121°c from 81 to 160 and 5 vb flammabilityclassrating @ 2.2mm')

([{'property_name': 'glow wire ignition temperature', 'modifier': {'value': '671', 'min': '603.9', 'max': '738.1', 'unit': 'fahrenheit'}, 'property_type': 'ul_sub_property'}, {'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': 70, 'min': 63.0, 'max': 77.0, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.7', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow wire ignition temperature of 671fahrenheit, rti-e at 0.7mm 70 °c')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc-0', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '124', 'min': '111.6', 'max': '136.4', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '3', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'high amperage arc ignition category at 3 plc-0 rti-s (124°c)')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc3', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': '143', 'min': None, 'max': '143', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '1.6', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'high current arc ignition @ 1.6 of plc3, rti electrical of max 143')

([{'property_name': 'glow wire', 'modifier': {'value': '554.18', 'min': '415.63', 'max': '692.72', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc 1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.3', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow wire (554.18) in the range of 25%, high-current arc ignition 0.3mm of plc 1')

([{'property_name': 'flame rating', 'modifier': {'value': 'v-0', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': '113', 'min': None, 'max': '113', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '2.2', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'flameclassrating v-o at 2.2mm relative thermal index impact <= 113 °c')

got same properties
got same properties
([{'property_name': 'flame rating', 'modifier': {'value': 'v-1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'hot wire ignition (hwi)', 'modifier': {'value': 'plc0', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.1', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'v-1 @ 0.1mm and hot-wire ignition=plc0')

([{'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': '137', 'min': '137', 'max': None, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'hot wire ignition (hwi)', 'modifier': {'value': 'plc2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '3.1', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'rti-i greater than or equal to 137 °c and plc2 hot wire @ 3.1mm')

([{'property_name': 'glow wire', 'modifier': {'value': '346', 'min': '346', 'max': None, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'glow wire flammability index', 'modifier': {'value': 716, 'min': 644.4, 'max': 787.6, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '1.3', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow wire more than or eaual to 346 °c and gwf index at 1.3 of 716')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc4', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'glow wire ignition temperature', 'modifier': {'value': 945, 'min': 850.5, 'max': 1039.5, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.9', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'highcurrentarcignition of plc4 gwi temperature at 0.9mm 945')

([{'property_name': 'glow wire', 'modifier': {'value': '364', 'min': '364', 'max': '755', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'hot wire ignition (hwi)', 'modifier': {'value': 'plc 1', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '1.3', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow wire between 364 and 755, hot wire ignition (hwi) @ 1.3 of plc 1')

([{'property_name': 'glow wire ignition temperature', 'modifier': {'value': '676', 'min': '473.2', 'max': '878.8', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc0', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '3.1', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'glow wire ignition temperature - 676 within 30% margin high current arc at 3.1mm of plc0')

([{'property_name': 'glow wire ignition temperature', 'modifier': {'value': 880, 'min': 792.0, 'max': 968.0, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '108', 'min': '75.6', 'max': '140.4', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '0.7', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'flow wire ignition temperature 0.7mm of 880°c relative thermal index - mechanical strength 108 °c in the vicinity of 30%')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '123', 'min': '103', 'max': '153', 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'relative thermal index - electrical (rti elec) (°c)', 'modifier': {'value': 166, 'min': 149.4, 'max': 182.6, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '6', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index - mechanical strength (rti str) (123 °c) in the range of 103 to 153 and rti electrical at 6 of 166 °c')

([{'property_name': 'flammability classification', 'modifier': {'value': 'hb-40', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'flame rating', 'modifier': {'value': 'v-2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '3', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'hb-40 flame rated v-2, 3mm thickness')

([{'property_name': 'high-current arc ignition (hai)', 'modifier': {'value': 'plc-3', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'relative thermal index - mechanical impact (rti imp) (°c)', 'modifier': {'value': 131, 'min': 117.9, 'max': 144.1, 'unit': '°c'}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '2.2', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'high current arc plc-3 relative thermal index impact at 2.2mm of 131°c')

([{'property_name': 'relative thermal index - mechanical strength (rti str) (°c)', 'modifier': {'value': '59', 'min': '59', 'max': '111', 'unit': None}, 'property_type': 'ul_sub_property'}, {'property_name': 'flame rating', 'modifier': {'value': 'v 2', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'ul_sub_property'}, {'property_name': 'minimum thickness (mm)', 'modifier': {'value': '3', 'min': None, 'max': None, 'unit': 'mm'}, 'property_type': 'ul_property'}], 'relative thermal index mechanical strength 59-111 flamerating v 2, 3mm thickness')

### Certifications (excluding Auto Certification)

In [168]:
for item in unique_values['Certification']:
    if item['CERTIFICATION_TYPE']=='NSF':
        nsf_certifications = item['CERTIFICATIONS']
    if item['CERTIFICATION_TYPE']=='RAILWAY SPECIFICATION':
        railway_certifications = item['CERTIFICATIONS']
    if item['CERTIFICATION_TYPE']=='WATER APPROVAL':
        water_certifications = item['CERTIFICATIONS']

water_certifications_combinations = [
    ['NSF 61 at 23°C', 'NSF 61', '23'],
    ['NSF 61 at 82°C','NSF 61', '82'],
    ['NSF 61 at 60°C','NSF 61', '60'],
    ['WRAS 23°C','WRAS','23'],
    ['WRAS 60°C','WRAS','60'],
    ['KTW BWGL at 23°C','KTW BWGL', '23'],
    ['KTW BWGL at 60°C','KTW BWGL', '60'],
    ['WRAS 85°C','WRAS','85'],
    ['EN16421','EN16421','ALL'],
    ['ACS 23°C','ACS','23'],
    ['KTW BWGL at 85°C','KTW BWGL', '85'],
    ['ACS 85°C','ACS','85'],
    ['ACS 60°C','ACS','60'],
    ['NSF 61 at 23°C', 'NSF 61', '23'],
    ['NSF 61 at 82°C','NSF 61', '82'],
    ['NSF 61 at 60°C','NSF 61', '60'],
    ['WRAS 23°C','WRAS','23'],
    ['WRAS 60°C','WRAS','60'],
    ['KTW BWGL at 23°C','KTW BWGL', '23'],
    ['KTW BWGL at 60°C','KTW BWGL', '60'],
    ['WRAS 85°C','WRAS','85'],
    ['EN16421','EN16421','ALL'],
    ['ACS 23°C','ACS','23'],
    ['KTW BWGL at 85°C','KTW BWGL', '85'],
    ['ACS 85°C','ACS','85'],
    ['ACS 60°C','ACS','60'],
    ['NSF 61 at 23°C', 'NSF 61', '23'],
    ['NSF 61 at 82°C','NSF 61', '82'],
    ['NSF 61 at 60°C','NSF 61', '60'],
    ['WRAS 23°C','WRAS','23'],
    ['WRAS 60°C','WRAS','60'],
    ['KTW BWGL at 23°C','KTW BWGL', '23'],
    ['KTW BWGL at 60°C','KTW BWGL', '60'],
    ['WRAS 85°C','WRAS','85'],
    ['EN16421','EN16421','ALL'],
    ['ACS 23°C','ACS','23'],
    ['KTW BWGL at 85°C','KTW BWGL', '85'],
    ['ACS 85°C','ACS','85'],
    ['ACS 60°C','ACS','60'],    

    ['NSF 61 at 23 degrees', 'NSF 61', '23'],
    ['NSF 61 at 82 degrees','NSF 61', '82'],
    ['NSF 61 at 60 degrees','NSF 61', '60'],
    ['WRAS 23 degrees', 'WRAS', '23'],
    ['WRAS 60 degrees', 'WRAS', '60'],
    ['KTW BWGL at 23 degrees','KTW BWGL', '23'],
    ['KTW BWGL at 60 degrees','KTW BWGL', '60'],
    ['WRAS 85 degrees','WRAS','85'],
    ['EN16421','EN16421','ALL'],
    ['ACS 23 degrees','ACS','23'],
    ['KTW BWGL at 85 degrees','KTW BWGL', '85'],
    ['ACS 85 degrees','ACS','85'],
    ['ACS 60 degrees','ACS','60'],
    ['NSF 61 at 23 degree celsius', 'NSF 61', '23'],
    ['NSF 61 at 82 degree celsius','NSF 61', '82'],
    ['NSF 61 at 60 degree celsius','NSF 61', '60'],
    ['WRAS 23 degree celsius','WRAS','23'],
    ['WRAS 60 degree celsius','WRAS','60'],
    ['KTW BWGL at 23 degree celsius','KTW BWGL', '23'],
    ['KTW BWGL at 60 degree celsius','KTW BWGL', '60'],
    ['WRAS 85 degree celsius','WRAS','85'],
    ['EN16421','EN16421','ALL'],
    ['ACS 23 degree celsius','ACS','23'],
    ['KTW BWGL at 85 degree celsius','KTW BWGL', '85'],
    ['ACS 85 degree celsius','ACS','85'],
    ['ACS 60 degree celsius','ACS','60'],
    ['NSF 61 at 23 celsius', 'NSF 61', '23'],
    ['NSF 61 at 82 celsius','NSF 61', '82'],
    ['NSF 61 at 60 celsius','NSF 61', '60'],
    ['WRAS 23 celsius','WRAS','23'],
    ['WRAS 60 celsius','WRAS','60'],
    ['KTW BWGL at 23 celsius','KTW BWGL', '23'],
    ['KTW BWGL at 60 celsius','KTW BWGL', '60'],
    ['WRAS 85 celsius','WRAS','85'],
    ['EN16421','EN16421','ALL'],
    ['ACS 23 celsius','ACS','23'],
    ['KTW BWGL at 85 celsius','KTW BWGL', '85'],
    ['ACS 85 celsius','ACS','85'],
    ['ACS 60 celsius','ACS','60'],   
    ['NSF 61 at 23 deg celsius', 'NSF 61', '23'],
    ['NSF 61 at 82 deg celsius','NSF 61', '82'],
    ['NSF 61 at 60 deg celsius','NSF 61', '60'],
    ['WRAS 23 deg celsius','WRAS','23'],
    ['WRAS 60 deg celsius','WRAS','60'],
    ['KTW BWGL at 23 deg celsius','KTW BWGL', '23'],
    ['KTW BWGL at 60 deg celsius','KTW BWGL', '60'],
    ['WRAS 85 deg celsius','WRAS','85'],
    ['EN16421','EN16421','ALL'],
    ['ACS 23 deg celsius','ACS','23'],
    ['KTW BWGL at 85 deg celsius','KTW BWGL', '85'],
    ['ACS 85 deg celsius','ACS','85'],
    ['ACS 60 deg celsius','ACS','60'],
    ['NSF 61 at 23c', 'NSF 61', '23'],
    ['NSF 61 at 82c','NSF 61', '82'],
    ['NSF 61 at 60c','NSF 61', '60'],
    ['WRAS 23c','WRAS','23'],
    ['WRAS 60c','WRAS','60'],
    ['KTW BWGL at 23c','KTW BWGL', '23'],
    ['KTW BWGL at 60c','KTW BWGL', '60'],
    ['WRAS 85c','WRAS','85'],
    ['EN16421','EN16421','ALL'],
    ['ACS 23c','ACS','23'],
    ['KTW BWGL at 85c','KTW BWGL', '85'],
    ['ACS 85c','ACS','85'],
    ['ACS 60c','ACS','60'],
    ['NSF 61 at 23 deg c', 'NSF 61', '23'],
    ['NSF 61 at 82 deg c','NSF 61', '82'],
    ['NSF 61 at 60 deg c','NSF 61', '60'],
    ['WRAS 23 deg c','WRAS','23'],
    ['WRAS 60 deg c','WRAS','60'],
    ['KTW BWGL at 23 deg c','KTW BWGL', '23'],
    ['KTW BWGL at 60 deg c','KTW BWGL', '60'],
    ['WRAS 85 deg c','WRAS','85'],
    ['EN16421','EN16421','ALL'],
    ['ACS 23 deg c','ACS','23'],
    ['KTW BWGL at 85 deg c','KTW BWGL', '85'],
    ['ACS 85 deg c','ACS','85'],
    ['ACS 60 deg c','ACS','60'],

    ['WRAS', 'WRAS', 'ALL'],
    ['WRAS', 'WRAS', 'ALL'],
    ['ACS', 'ACS', 'ALL'],
    ['ACS', 'ACS', 'ALL'],
    ['KTW', 'KTW BWGL', 'ALL'],
    ['KTW', 'KTW BWGL', 'ALL'],
    ['KTW BWGL', 'KTW BWGL', 'ALL'],
    ['KTW BWGL', 'KTW BWGL', 'ALL'],
    ['BWGL', 'KTW BWGL', 'ALL'],
    ['BWGL', 'KTW BWGL', 'ALL'],

    ['hot water', 'all', 'hot'],
    ['hot-water', 'all', 'hot'],

    ['commerical-hot water', 'all', 'c-hot'],
    ['commerical-hot', 'all', 'c-hot'],
    ['c-hot water', 'all', 'c-hot'],
    ['c-hot', 'all', 'c-hot'], 
    
    ['domestic-hot water', 'all', 'd-hot'],
    ['domestic-hot', 'all', 'd-hot'],
    ['d-hot water', 'all', 'd-hot'],
    ['d-hot', 'all', 'd-hot'],

    ['cold water', 'all', 'cold'],
    ['c-water', 'all', 'cold'],
    

]
railway_certifications_combinations = [(i, i.split(" - ")[0], i.split(" - ")[1].split(" (")[0],"EN 45545-2") for i in railway_certifications]

In [169]:
railway_certifications_combinations

[('R23 - HL3 (EN 45545-2)', 'R23', 'HL3', 'EN 45545-2'),
 ('R24 - HL3 (EN 45545-2)', 'R24', 'HL3', 'EN 45545-2'),
 ('R22 - HL2 (EN 45545-2)', 'R22', 'HL2', 'EN 45545-2'),
 ('R26 - V0 (EN 45545-2)', 'R26', 'V0', 'EN 45545-2'),
 ('R22 - HL3 (EN 45545-2)', 'R22', 'HL3', 'EN 45545-2'),
 ('R24 - HL2 (EN 45545-2)', 'R24', 'HL2', 'EN 45545-2'),
 ('R23 - HL2 (EN 45545-2)', 'R23', 'HL2', 'EN 45545-2'),
 ('R22 - HL1 (EN 45545-2)', 'R22', 'HL1', 'EN 45545-2')]

In [170]:
nsf_certifications

['NSF 61', 'NSF 51', 'NSF 42', 'NSF 372']

### Auto Approvals

In [171]:
auto_certs = {}
# for cert_details in unique_values['Auto_Approval']:
for cert_details in unique_values_cert['Auto_Approval']: 
    if cert_details['OEM_Name'].lower() not in auto_certs:
        auto_certs[cert_details['OEM_Name'].lower()] = [x.lower() for x in cert_details['CERTIFICATIONS']]
    else:
        auto_certs[cert_details['OEM_Name'].lower()] += [x.lower() for x in cert_details['CERTIFICATIONS']]

auto_certs

{'baic': ['q-bjev 01.59', 'q-bjev 01.33', 'bas-491', 'bas-492'],
 'bmw': ['gs93017',
  'gs93016',
  'gs97014',
  'gs93016-pbt+asa-gf20',
  'gs93016-pbt+asa-gf30',
  'gs93016-pbt',
  'gs93016-pbt-gf15',
  'gs93016-pbt-gf20',
  'gs93016-pbt-gf30',
  'gs93016-pbt-gb20',
  'gs93016-pet-gf30',
  'gs93016-pet-gf45',
  'gs93016-pet-(mx20+gf15)',
  'gs93042',
  'gs93016-pa66',
  'gs93016-pa66-gf30',
  'gs93016-pa66-gf35',
  'gs93016-pa66-gf50',
  'gs93016-pa6-gf15',
  'gs93016-pa6-gf30',
  'gs93016-pa66-gf15',
  'gs93016-pa66-gf25'],
 'byd': ['byd-ty-d13f05-0106', 'byd-ty-d13f05-0043'],
 'bosch': ['n28 bn07-gf010',
  'n28 bn07-o001',
  'n28 bn07-gf014',
  'n28 bn07-gf032',
  'n28 bn08-gf009',
  'n28 bn08-gf013',
  'n28 bn07-gf028',
  'n28 bn22-x003',
  'n28 bn22-x009',
  'n28 bn22-o034',
  'n28 bn09-gf027',
  'n28 bn09-gf026',
  'n28 bn09-gf024',
  'n28 bn07-gf019',
  'n28 bn08-gf018',
  'n28 bn07-gf003',
  'n28 bn07-gf012',
  'n28 bn07-gf023',
  'n28 bn07-gf051',
  'n28 bn14-gf010',
  'n28 bn22-o024',
  'n28 bn22-o027',
  'n28 bn22-o025',
  'n28 bn22-o026',
  'n28 bn22-o004',
  'n28 bn22-o028',
  'n28 bn22-o010',
  'n28 bn22-x013',
  'n28 bn22-x006',
  'n28 bn22-x022',
  'n28 bn22-x010',
  'n28 bn22-x014',
  'n28 bn22-x015',
  'n28 bn22-x016',
  'n28 bn22-o017',
  'n28 bn22-o014',
  'n28 bn22-o015',
  'n28 bn22-x017',
  'n28 bn22-o037',
  'n28 bn22-x005',
  'n28 bn22-x021',
  'n28 bn90-21-005',
  'n28 bn90-21-004',
  'n28 bn90-21-008',
  'n28 bn34-ox036',
  'n28 bn34-ox067',
  'n28 bn34-ox035',
  'n28 bn34-ox 017',
  'n28 bn35-x001',
  'n28 bn02-gf053',
  'n28 bn02-gf034',
  'n28 bn02-gf126',
  'n28 bn02-gf128',
  'n28 bn02-gf073',
  'n28 bn05-ox020',
  'n28 bn05-ox019',
  'n28 bn02-gf122',
  'n28 bn05-ox088',
  'n28 bn05-ox036',
  'n28 bn05-ox049',
  'n28 bn05-ox089',
  'n28 bn02-o035'],
 'catl': ['pa66-gf30-x-i0x', 'pa66-gf25-a-i01', 'pa66-gf25-a-01'],
 'changan': ['mts-f01-02-001-a3'],
 'chery': ['cmp.pbt.a1',
  'cmp.pbt.g2',
  'cmp.pbt.33',
  'cmp.pa66.a1',
  'cmp.pa66.g3',
  'cmp.pa66.g6',
  'cmp.pa66.g7',
  'cmp.pa6.g3',
  'cmp.pa66.a2'],
 'continental': ['sn 57908-7',
  'tst n 055 47.12',
  'sn 57908-17',
  'sn 57908-11',
  'sn 57908-6',
  'tst n 055 47.27',
  'sn 57908-4',
  'tst n 055 54.10',
  'tst n 055 54.07',
  'tst n 055 54.12',
  '30.5251-0367.7',
  'tst n 055 54.23',
  'tst n 055 58.01',
  'tst n 055 58.03',
  'tst n 055 58.12',
  'tst n 055 54.32',
  'tst n 055 54.30',
  'tst n 055 54.11',
  'tst n 055 54.03',
  'tst n 055 54.25',
  'tst n 055 54.16',
  'tst n 055 54.14',
  'sn 57914-7',
  'tst n 055 54.22',
  'tst n 055 54.37',
  'tst n 055 54.13',
  'tst n 055 54.15',
  'tst n 055 54.09',
  'tst n 055 54.18',
  'tst n 055 54.35',
  'tst n 055 54.44',
  'tst n 055 54.40',
  'tst n 055 54.17',
  'tst n 055 72.01-000',
  'tst n 055 72.03-001'],
 'dongfeng motor': ['slclbg2016018',
  'slclbg2019011',
  'slclbg2018035',
  'eqcl-67-2017 tpe 55d'],
 'evergrande auto': ['egw.pl.0603-pom-co'],
 'faw group': ['jf03-28'],
 'ford': ['wss-m4d725-b1',
  'wss-m4d929-a3',
  'wss-m4d1017-a1',
  'wrs-m4d625-a3',
  'wsb-m4d921-a',
  'wsb-m4d883-a1',
  'wsk-m4d635-a1',
  'wsk-m4d635-a3',
  'wsk-m4d635-a2',
  'wsk-m4d840-a5',
  'wsb-m4d840-a4',
  'wsk-m4d840-a3',
  'wss-m4d840-a6',
  'wss-m4d840-b1',
  'wsk-m4d840-a1',
  'wsb-m4d677-a',
  'wsb-m4d678-a',
  'wsb-m4d679-a',
  'wsb-m4d680-a',
  'wss-m4d865-b5',
  'wss-m4d865-b7',
  'wss-m4d865-b4',
  'wss-m4d865-b8',
  'wss-m4d865-b1',
  'wss-m4d865-b3',
  'wsk-m4d639-a',
  'wss-m4d1014-a',
  'wsk-m4d895-a1',
  'wsk-m4d896-a1',
  'wsk-m4d636-a',
  'wsk-m4d636-a2',
  'wrs-m4d673-b2',
  'wsl-m4d807-a',
  'wsf-m4d803-a2',
  'wss-m4d1063-a1',
  'wss-m4d1063-a2',
  'wsk-m4d840-a2',
  'wsk-m4d635-a4',
  'wsk-m4d618-a2',
  'wsf-m4d618-a',
  'wss-m4d1006-a1',
  'wss-m98p14-a7',
  'wss-m98p14-a3',
  'wsd-m2d378-a1',
  'wss-m9p9-d2',
  'wsd-m2d379-a1',
  'wsd-m2d380-a1',
  'wsd-m2d381-a1',
  'wsd-m2d382-a1',
  'wsd-m2d441-a',
  'wsd-m2d378-a4',
  'wss-m2d378-b1',
  'wss-m2d510-a6',
  'wss-m2d379-b1',
  'wss-m2d380-b1',
  'wss-m9p14-a1',
  'wss-m2d281-b1',
  'wss-m2d382-b1',
  'wss-m2d510-a5',
  'wss-m2d510-a7',
  'wss-m2d510-a8',
  'wss-m4d648-b1',
  'wss-m4d706-b1',
  'wss-m4d1016-a1',
  'wss-m4d752-b1',
  'wss-m4d673-b1',
  'wsk-m4d665-a2',
  'wss-m4d993-b1',
  'wss-m4d1038-a1',
  'wss-m98p13-e',
  'wsk-m4d591-a',
  'wss-m4d703-b1',
  'wss-m4d1009-a1',
  'wss-m98p14-a9',
  'wss-m4d861-a3',
  'wss-m4d861-a4',
  'wss-m4d706-a4',
  'wsk-m4d666-a',
  'wss-m4d666-b1',
  'wss-m4d666-a2'],
 'geely': ['q/jly j7111001a-2016â‘¢',
  'q/jly j7110235b-2018â‘¡',
  'q/jly j7110166b-2017',
  'q/jl j124010-2019'],
 'general motors (gm)': ['gmw16733p-pbt-gf30',
  'gmw16733p-pbt-gf15',
  'gmw16459p-pbt-gf30w',
  'gmw16733p-pbt-gf30f',
  'gmw17249',
  'gmw18161p-pbt+pet-gf55',
  'gmw16873p-pbt+pet-m7gf33',
  'gmw17448p-pbt+pet-gf15m15',
  'gmw16873p-pbt+pet-m5gf25',
  'gmw3038p-pa66-gf35h',
  'gmw3038p-pa66-gf35j',
  'gmw3029p-pa6-gf30h',
  'gmw22p-pom-c1',
  'gmw22p-pom-c4',
  'gmw22p-pom-c2',
  'gmw17810p-pa66-gf40',
  'gmw17810p-pa66-gf60',
  'gmw17697p-pp-gf20e',
  'gmw15890p-pp-gf20e-class-u',
  'gmw15890p-pp-gf20e',
  'gmw15890p-pp-gf30e',
  'gmw16272',
  'gmw15890p-pp-gf40',
  'gmw15890p-pp-gf40-class-u',
  'gmw17697p-pp-gf40',
  'gmw15890p-pp-gf50 type 50',
  'gmw16272p-pp-gf50',
  'gmw15890p-pp-gf60',
  'gmw17802p-pa6-t1',
  'gmw17025p-pbt',
  'gmw17521p-pps-gf40e',
  'gmw17521p-pps-gf40',
  'gmw17519p-pps-(gf45-md20)',
  'gmw17769p-pps-t2',
  'gmw16720p-pe',
  'gmw22p-pom-c3',
  'gmw18026p-pom',
  'gmw17968p-pom-gf20',
  'gmw17968p-pom-gf25',
  'gmw17008p-pom-c2',
  'gmw16278p-pom-type c2',
  'gmw17195p-pom-t2',
  'gmw17624p-pom',
  'gmw18052p-pom',
  'gmw22p-pom-c2p1',
  'gmw22p-pom-c2p2',
  'gmw16657p-pom',
  'gmw16924p-pom-c4',
  'gmw16924p-pom-c2',
  'gmw17327p-tpc-et-type 1',
  'gmw17327p-tpc-et-type 2',
  'gmw17327p-tpc-et-type 3m1',
  'gmw17327p-tpc-et-type 3m2h',
  'gmw17327p-tpc-et-type 3m2',
  'gmw17327p-tpc-et-type 4',
  'gmw17186p-tpc-et-type 2',
  'gmw17327p-tpc-et-type 5',
  'gmw17327p-tpc-et-type 6',
  'gmw17187p-tpc-et-type 2',
  'gmw17187p-tpc-et-type 3',
  'gmw17457p-tpc-et-type 2',
  'gmw17479p-tpc-et-type 1b',
  'gmw17479p-tpc-et-type 1a',
  'gmw16278p-pom-type c3',
  'gmw15813p-tpv-(epdm+pp)-type 4',
  'gmw15813p-tpv-(epdm+pp)-type 5',
  'gmw15813p-tpv-(epdm+pp)-type 6',
  'gmw15813p-tpv-(epdm+pp)-type 7',
  'gmw15813p-tpv-(epdm+pp)-type 8',
  'gmw15813p-tpv-(epdm+pp)-type 9',
  'gmw15813p-tpv-(epdm+pp)-type 10',
  'gmw15813p-tpv-(epdm+pp)-type 2',
  'gmw15812p-tpv(epdm+pp)-type 4m',
  'gmw15812p-tpv(epdm+pp)-type 4e',
  'gmw15812p-tpv(epdm+pp)-type 5m',
  'gmw15812p-tpv(epdm+pp)-type 5e',
  'gmw15825p-tpv(epdm + pp) type 5',
  'gmw15812p-tpv(epdm+pp)-type 6e',
  'gmw15812p-tpv(epdm+pp)-type 7m',
  'gmw15812p-tpv(epdm+pp)-type 7e',
  'gmw15825p-tpv(epdm+pp)-type-6',
  'gmw15812p-tpv(epdm+pp)-type 8m',
  'gmw15812p-tpv(epdm+pp)-type 8e',
  'gmw15812p-tpv(epdm+pp)-type 9',
  'gmw15812p-tpv(epdm+pp)-type 10e',
  'gmw15816p-tpv-epdm+pp-class-i-type 4',
  'gmw15816p-tpv-epdm+pp-class-i-type-5',
  'gmw15816p-tpv-epdm+pp-class-i-type-6',
  'gmw16036p-pa66',
  'gmw17602p-pa612',
  'gmw17349p-pa66',
  'gmw3038p-pa66-gf15h',
  'gmw3038p-pa66-gf25h',
  'gmw16270p-pa66-gf25',
  'gmw3038p-pa66-gf25j',
  'gmw3038p-pa66-gf30h',
  'gmw16270p-pa66-gf30',
  'gmw3038p-pa66-gf30j',
  'gmw16802p-pa66-gf35',
  'gmw17961p-pa-gf35-t1',
  'gmw3038p-pa66-gf45h',
  'gmw3038p-pa66-gf45j',
  'gmw3038p-pa66-gf50h',
  'gmw3038p-pa66-gf50j',
  'gmw3029p-pa6-gf15h',
  'gmw16582p-pa6-gf15',
  'gmw16582p-pa6-gf30',
  'gmw3029p-pa6-gf35h',
  'gmw3029p-pa6-gf50h',
  'gmw17599p-pa612-gf35',
  'gmw17263p-pa66-gf15',
  'gmw17263p-pa66-gf35',
  'gmw17385p-pa6-gf40',
  'gmw17481p-pa66-gf25',
  'gmw18122p-pa-gf25-typea2',
  'gmw18122p-pa-gf25-typeaf',
  'gmw16799p-ppa-t2',
  'gmw16356p-ppa-gf15',
  'gmw16356p-ppa-gf35',
  'gmw16360p-ppa-gf35',
  'gmw16356p-ppa-gf45',
  'gmw16360p-ppa-gf45',
  'gmw16357p-ppa-gf35',
  'gmw18066p-ppa-gf15',
  'gmw18066p-ppa-gf35',
  'gmw17558p-pa612',
  'gmw17604p-pa612',
  'gmw16558p-pa66-t3',
  'gmw16447p-pa66-t2',
  'gmw16558p-pa66-t1',
  'gmw17961p-pa-gf35-t3',
  'gmw17047p-pa-gf50',
  'gmw16447p-pa66-t3',
  'gmw17430p-pa66-t2',
  'gmw16370p-pa66',
  'gmw16558p-pa66-t2',
  'gmw17577p-pa6-t2',
  'gmw17961p-pa-gf35-t2'],
 'great wall motor': ['mp12-05', 'mp05-01', 'mp01 lg-01', 'mp01-lg-03'],
 'honda': ['0094z-ghaf-9810-m1'],
 'hyundai': ['ms941-03 type f-5',
  'ms237-09 type a',
  'ms237-09 type b',
  'ms216-03 type c',
  'ms941-03 type f-5 frv0',
  'ms216-03 type b',
  'ms941-03 type f-5 frv0 cti0',
  'ms941-03 type f-3 ah',
  'ms941-03 type f-3 hi',
  'ms941-03 type f-5 ah',
  'ms216-03 type f-2',
  'ms941-03 type f-1',
  'ms941-03 type f-3',
  'ms216-03 type f-1',
  'ms244-02 type a-1',
  'ms244-02 type a-2',
  'ms237-14 type a',
  'ms237-05 type a-2',
  'ms237-05 type d',
  'ms237-05 type a-1',
  'ms220-24 type e',
  'ms220-24 type e',
  'ms220-24 type d',
  'ms220-24 type b',
  'ms220-24 type c',
  'ms220-24 type g',
  'ms220-08 type a',
  'ms220-24 type a',
  'ms220-08 type d',
  'ms237-09 type e-1',
  'ms237-05 type b',
  'ms237-05 type e-1',
  'ms941-03 type m-1',
  'ms237-12 type a',
  'ms237-05 type c',
  'ms216-05 type b',
  'ms220-05 type a',
  'ms220-05 type b',
  'ms220-31 type a1',
  'ms220-05 type c',
  'ms220-31 type a2',
  'ms220-05 type d',
  'ms220-05 type e',
  'ms220-05 type g',
  'ms220-05 type h',
  'ms220-05 type k',
  'ms220-05 type j',
  'ms220-13 type d-1',
  'ms220-05 type p',
  'ms220-05 c',
  'ms220-05 p',
  'ms220-05 type l',
  'ms220-05 type m',
  'ms220-13 type c-1',
  'ms220-05 type n',
  'ms220-13 type f-1',
  'ms220-05 type r',
  'ms220-13 type e-1',
  'ms941-03 type j-2',
  'ms941-03 type p-2 frvo',
  'ms211-37 type d',
  'ms211-46 type e',
  'ms211-46 type b',
  'ms211-66 type b',
  'ms941-03 type a-2',
  'ms941-03 type a-5',
  'ms941-03 type a-6',
  'ms211-47 type a-2-3',
  'ms941-03 type a-7',
  'ms211-37 type e',
  'ms211-36 type a-1',
  'ms211-66 type c',
  'ms211-47 type a-3',
  'ms211-44 type c',
  'ms941-03 type d-2',
  'ms941-03 type d-3',
  'ms211-56 type',
  'ms941-03 type a-3 hi',
  'ms211-72 type a',
  'ms941-03 type a-5 frv0',
  'ms941-12 type b',
  'ms941-03 type n-4',
  'ms211-19 type b-1',
  'ms211-80 type b',
  'ms211-35 type c',
  'ms211-46 type c-2',
  'ms211-72 type b'],
 'iveco': ['iveco 5244', 'iveco 15-5244'],
 'li auto': ['q/lia5310038', 'q/lia5310020', 'q/lia5310050', 'q/lia5310057'],
 'man': ['man m3236', 'm3236 a7', 'm3236 a5', 'm3236 a6', 'man m3236 a7'],
 'mercedes-benz': ['dbl5410',
  'dbl5408',
  'dbl5409',
  'dbl5405-06-pom-c',
  'dbl 5416',
  'dbl5404',
  'dbl5418',
  'dbl5416',
  'dbl5403 pbt-i-gf15',
  'dbl5410.00 pbt+asa gf30',
  'dbl5404.19 pbt+asa-gf15',
  'dbl5419.90 pbt-gf30',
  'dbl5420.00 pbt-gf30',
  'dbl5416.90 pbt-gf30',
  'dbl5403.51 pbt-gf30',
  'dbl5403 pbt-gf30',
  'dbl5420',
  'dbl5403',
  'dbl5405',
  'dbl5406',
  'dbl5405-07-pom-c',
  'dbl5562.50 tpc',
  'dbl5562 aa41 tpu',
  'dbl5562 aa41 tpv',
  'dbl5562 aa39 tpc',
  'dbl5562.50 tpc-et',
  'dbl5562 tpc',
  'dbl5562.34 tps',
  'dbl5562.aa39 tpc',
  'dbl5562.aa41 tpu',
  'dbl5562.34 tpv',
  'dbl5562.aa41 tpv',
  'dbl5562.34 tpu',
  'dbl5562.36',
  'dbl5562.31',
  'dbl5562.50',
  'dbl5562.34',
  'dbl5562.33',
  'dbl5562.15',
  'dbl5562.17',
  'dbl5562',
  'dbl5422',
  'dbl5562-30',
  'std4376-7',
  'dbl5410.00 pa66',
  'dbl5409.20 pa66',
  'dbl5403.00 pa66',
  'dbl5403.21 pa66',
  'dbl5416.aa90 pa66',
  'dbl5410.00 pa66 gf25',
  'dbl5408.45 pa66 gf30',
  'dbl5410.00 pa66 gf30',
  'dbl5406.22 pa66 gf30',
  'dbl5406.21 pa66 gf30',
  'dbl5409.24 pa66 gf30',
  'dbl5409.25 pa66 gf35',
  'dbl5403.00 pa66 gf35',
  'dbl5408.50 pa66',
  'dbl5405.05 pagg gf35',
  'dbl5405.05 pa66 gf35',
  'dbl5408.50 pa66 gf35',
  'dbl5403.32 pa66 gf35',
  'dbl5409.35 pa66 gf50',
  'dbl5403.33 pa66 gf50',
  'dbl5403 pa66 gf20',
  'dbl5410.00 pa6 gf15',
  'dbl5408.24 pa6 gf15',
  'dbl5404.00 pa6 gf15',
  'dbl5410.10 pa6 gf15',
  'dbl5403.11 pa6 gf30',
  'dbl5410.00 pa6 gf30',
  'dbl5408.30 pa6 gf30',
  'dbl5404.14 pa6 gf30',
  'dbl5409.10 pa6 gf35',
  'dbl5410.00 pa66 gf15',
  'dbl5410.01 pa66-i',
  'dbl5408.21 pa6-hi',
  'dbl5408.25 pa6 gf15',
  'dbl5406.10 pa66 gf30',
  'dbl5406.00 ppa gf30',
  'dbl5408.65 ppa gf35',
  'dbl5406.00 pa12',
  'dbl5403.22 pa66-i',
  'dbl5408.52 pa66 gf35',
  'dbl5408.55 (pa66+pa6) - gf50',
  'dbl5410.01 pa6-i',
  'dbl5404.15 pa6-hi',
  'dbl5410.00 pa66-i',
  'dbl5404.00 pa6'],
 'nio': ['nio-sm.51.010-c6',
  'nio-sm.51.010-c4',
  'nio-sm.51.010',
  'nio-sm.51.041',
  'n-008-0001',
  'nio-sm.51.007-c2',
  'n-008-0002',
  'nio-sm.51.003'],
 'nissan': ['pbtp(g)-1x-30',
  'pbtp(g30)-1nx-1',
  'pbtp(g)-1nx-30',
  'pom-ic1-1',
  'pom-ic3-1',
  'pom-ic2-1',
  'ev02b',
  'ev02c',
  'pom-ivx-1',
  'pom-ihx-1',
  'ub15b',
  'ep03-3',
  'pom-inx -w2-1',
  'pom-inx -w1-1',
  'pom(0xx)-ixx-1'],
 'saic motor': ['smtc 5 310 018',
  'smtc 5 310 038',
  'smtc 5 310 055',
  'smtc 5 310 015',
  'smtc 5 310 020',
  'smtc 5 310 041',
  'smtc 5 4000 003',
  'smtc 5 320 024'],
 'stellantis-chrysler': ['cpn 5253',
  'cpn 3945',
  'cpn 4314',
  'cpn 2403',
  'cpn 2425',
  'cpn 2252',
  'cpn 4675',
  'cpn 3199',
  'cpn 2512',
  'cpn 2253 ms-db-400',
  'cpn 3946',
  'cpn 3669',
  'cpn 3764',
  'cpn 3763',
  'cpn 2810',
  'cpn 2666',
  'cpn 5476',
  'cpn 3504',
  'cpn 5341',
  'cpn 4165',
  'cpn 1906',
  'cpn 2500 ms.50095',
  'cpn 3761 ms-db-100',
  'cpn 4570',
  'cpn 4597',
  'cpn 4155',
  'cpn 4240',
  'cpn 1986',
  'cpn 2794',
  'cpn 2436',
  'cpn 1586',
  'cpn 3766',
  'cpn 4931',
  'cpn 4097',
  'cpn 4096',
  'cpn 4109',
  'cpn 3111',
  'cpn 3905',
  'cpn 3110',
  'cpn 1758',
  'cpn 4624',
  'cpn 3694',
  'cpn 4731',
  'cpn 5109',
  'cpn 5104',
  'cpn 5149',
  'cpn 3778',
  'cpn 4949',
  'cpn 5307',
  'cpn 3608',
  'cpn 4451',
  'cpn 5346',
  'cpn 5157',
  'cpn 5347',
  'cpn 4423 ms.50103',
  'cpn 4635 ms.50103',
  'cpn 4615 ms.50103',
  'cpn 4631 ms.50103',
  'cpn 4656 ms.50103',
  'cpn 4479 ms.50103',
  'cpn 2425 ms.50103',
  'cpn 4076 ms.50103',
  'cpn 2512 ms.50103',
  'cpn 2252 ms.50103',
  'cpn 2724 ms.50103',
  'cpn 3502 ms-db-570',
  'cpn 4241 ms-db-570',
  'cpn 3502',
  'cpn 4270',
  'cpn 4111',
  'cpn 1532',
  'cpn 5090',
  'cpn 5280',
  'cpn 5291',
  'cpn 5290',
  'cpn 5080',
  'cpn 5310',
  'cpn 2726',
  'cpn 2940',
  'cpn 5237',
  'cpn 3379',
  'cpn 2560 ms-db-448',
  'cpn 4894 ms-db-448',
  'cpn 4906 ms-db-448',
  'cpn 2313 ms-db-448',
  'cpn 2576 ms-db-448',
  'cpn 3042 ms-db-448',
  'cpn 2270 ms-db-448',
  'cpn 2760 ms-db-448',
  'cpn 3831 ms-db-448',
  'cpn 4154 ms-db-585',
  'cpn 3887 ms-db-585',
  'cpn 3095 ms-db-448',
  'cpn 3098 ms-db-448',
  'cpn 4038 ms-db-448',
  'cpn 2703 ms-db-448',
  'cpn 5161 ms-db-448',
  'cpn 1986 ms-db 100',
  'cpn 2315 ms-db 100',
  'cpn 1532 ms-db 100',
  'cpn 1586 ms-db 100',
  'cpn 3331 ms.50103',
  'cpn 3519 ms.50103',
  'cpn 2621 ms.50103',
  'cpn 3692 ms.50103',
  'cpn 2600 ms.50103',
  'cpn 2660 ms.50103',
  'cpn 5251 ms.50103',
  'cpn 3425 ms.50103',
  'cpn 3080 ms.50103',
  'cpn 3055 ms.50103',
  'cpn 3587 ms.50103',
  'ms-ar-100 agn',
  'ms-ar-100 bgn',
  'ms-ar-100 cgn',
  'ms-ar-100 dgn',
  'ms-ar-100 egn',
  'ms-ar-100 fgn',
  'ms-ar-100 ggn',
  'ms-ar-100 amn',
  'ms-ar-100 bmn',
  'ms-ar-100 amv',
  'ms-ar-100 agv',
  'ms-ar-100 bmv-hf',
  'ms-ar-100 bmv',
  'ms-ar-100 bmv2-hf',
  'ms-ar-100 bgv',
  'ms-ar-100 cgv',
  'ms-ar-100 cmv',
  'ms-ar-100 dgv',
  'ms-ar-100 dmv',
  'ms-ar-100 egv',
  'ms-ar-100 ggv',
  'ms-ar-100 hgv',
  'ms-ar-100 afn',
  'ms-ar-100 amv2-hf',
  'ms-ar-27a',
  'ms-ar-100 cmv2',
  'ms-db-226',
  'ms-ar-100 dmv2-hf',
  'ms-ar-100 hgn',
  'cpn 2012 ms.50017',
  'cpn 1948 ms.50017',
  'cpn 1938 ms.50017',
  'cpn 1899 ms.50017',
  'cpn 1076 ms.50017',
  'cpn 1618 ms.50017',
  'cpn 2551 ms.50017',
  'cpn 2239 ms.50017',
  'cpn 2125 ms.50017',
  'cpn 2601 ms.50017',
  'cpn 4367 ms.50017',
  'cpn 4018 ms.50017',
  'cpn 4818 ms.50017',
  'cpn 1900 ms.50017',
  'cpn 2224 ms.50017',
  'cpn 2327 ms.50017',
  'cpn 1853 ms.50017',
  'cpn 4777 ms.50017',
  'cpn 2508 ms.50017',
  'cpn 2183 ms.50017',
  'cpn 4967 ms.50017',
  'cpn 4499 ms.50017',
  'cpn 3840 ms.50017',
  'cpn 4269 ms.50017',
  'cpn 3266 ms.50017',
  'cpn 4075 ms.50017',
  'cpn 4765 ms.50017',
  'cpn 2461 ms.50017',
  'cpn 2184 ms.50017',
  'cpn 3155 ms.50017',
  'cpn 2735 ms.50017',
  'cpn 2670 ms.50017',
  'cpn 4973 ms.50017',
  'cpn 3933 ms.50091',
  'cpn 4189 ms.50091',
  'cpn 4190 ms.50091',
  'cpn 4696 ms.50091',
  'cpn 4749 ms.50091',
  'cpn 4178 ms.50091',
  'cpn 4449 ms.50091',
  'cpn 5292 ms.50091',
  'cpn 4970 ms.50017',
  'cpn 1826 ms.50017',
  'cpn 2055 ms.50017',
  'cpn 5139 ms.50017',
  'cpn 2345 ms.50017',
  'cpn 2456 ms.50017',
  'cpn 2959 ms.50017',
  'cpn 3850 ms.50017',
  'cpn 2565 ms.50017',
  'cpn 2438 ms.50017',
  'cpn 3433 ms.50017',
  'cpn 2776 ms.50017',
  'cpn 3492 ms.50017',
  'cpn 5077 ms.50017'],
 'stellantis-fca group': ['55235',
  'pom 80.45 e',
  'pom 100.55',
  'pom 75.70',
  '55248-02 emp80',
  '55248-02 emp60',
  '55248-02 emp70',
  '55248-02 emp90',
  '55248-02 emp140',
  '55248-02 emp50',
  '55248-02 emp150'],
 'stellantis-psa group': ['qk 000637',
  'qk 000638',
  'qk 000657',
  'qk 006521',
  'qk 006511',
  'qk 006611',
  'qk 0006612',
  'qk 000606',
  'qk 000613',
  'qk 000615',
  'qk 0006615',
  'qk 000614',
  '01994_18_01672',
  'b62 0300',
  'qk 005611',
  'qk 005621',
  'qk 005641',
  '01378_20_04386',
  'b62-0300',
  '01378_23_01240',
  '01378_22_03585'],
 'tesla': ['tm-1005-40',
  'tm-1005-50',
  'tm-1005-40cu1',
  'tm-1001-12',
  'tm-1001-22',
  'tm-1001-202220',
  'tm-1001-102220',
  'tm-1001-tmep 3082',
  'tm-1006 102160'],
 'vw group': ['vw 50136',
  'vw 50127',
  'vw 50133',
  'vw 50134',
  'vw 50125',
  'vw 44045',
  'vw 50136-pbt-i-gf15',
  'vw 50136-pbt-i-gf30',
  'vw 50136-pbt-7-a',
  'vw 50136-pbt-1-a',
  'vw 50136-pbt-3-a',
  'vw 50136-pbt-6-a',
  'vw 50137',
  'tl 524 76',
  'tl 526 36c',
  'tl 526 36a',
  'vw 50180',
  'tl 526 36b',
  'tl 522 77',
  'vw 50123 tpc-et 55d',
  'vw 50123',
  'vw 50123 tpc-et',
  'tl 526 83 tpc-et',
  'tl 522 81-b tpc-et',
  'tl 522 81-a tpc-et',
  'tl 522 81-d tpc-et',
  'tl 522 81-c tpc-et',
  'tl 526 41c',
  'vw 52703',
  'vw tl 527 03',
  'vw tl 526 41-c',
  'tl 526 41d',
  'vw 50133 pa66-1-a',
  'vw 50127 pa66-1',
  'vw 50133 pa66-1',
  'vw 50133 pa66-3-a',
  'vw 50133 pa66-5-a',
  'vw 50127 pa66-7',
  'vw 50133 pa66-6-a',
  'vw 50127 pa66-007',
  'tl 520 62 pa66-gf30',
  'tl 526 82 pa66-gf30',
  'tl 539 pa66-gf30',
  'vw 50133 pa66-7-a',
  'vw 50127 pa66-8',
  'vw 50127 pa66-10',
  'vw 50133 pa66-8-a',
  'vw 50125 pa6-004',
  'vw 50134 pa6-3-a',
  'tl 524 40 pa6-gf30',
  'vw 50134 pa6-7-a',
  'vw 50125 pa6-007',
  'vw 50134 pa6-8-a',
  'vw 50134 pa6-10-a',
  'vw 50125 pa6-010',
  'tl 524 40-a pa6-gf50',
  'vw 50127 pa66-4',
  'vw 50127 pa66-igf14',
  'vw 50127 pa66-011',
  'vw 50134 pa6-2-a',
  'vw 50127 pa66-fr(30)',
  'vw 50133 pa66-2-a',
  'vw 50127 pa66-2',
  'tl 520 62 pa-gf35',
  'tl 501 34 pa6',
  'vw 50127 pa66-3'],
 'zf group': ['zf 7832 050 153']}

In [172]:
remove_cert_with_oem = []
ignore_certs = [
    ("bosch", "gs93016-pa66"),
    ("nissan", "as26"),
    ("geely", "q/jly j7111001a-2016â‘¢"),
    ("geely", "q/jly j7110235b-2018â‘¡"),
    # ("stellantis-chrysler", "b62 0300"),
    # ("stellantis-fca group", "b62 0300"),
]

for oem in auto_certs:
    for x in auto_certs[oem]:
        if re.match(fr'^{re.escape(oem)}', x.strip()):
            new_cert = re.sub(fr'^{re.escape(oem)}', '', x.strip()).strip('- ')
            try:
                eval(new_cert)
            except:
                print(f"adding '{new_cert}' under '{oem}' oem")
                auto_certs[oem].append(new_cert)
                remove_cert_with_oem.append((oem, x))

ignore_certs += remove_cert_with_oem
for oem in auto_certs:
    temp = []
    for i in ignore_certs:
        if i[0] == oem:
            temp.append(i[1])

    auto_certs[oem] = [re.sub("(\s+)", " ", x.strip().lower()) for x in auto_certs[oem] if x not in temp]

ignore_certs

adding 'ty-d13f05-0106' under 'byd' oem
adding 'ty-d13f05-0043' under 'byd' oem
adding 'm3236' under 'man' oem
adding 'm3236 a7' under 'man' oem
adding 'sm.51.010-c6' under 'nio' oem
adding 'sm.51.010-c4' under 'nio' oem
adding 'sm.51.010' under 'nio' oem
adding 'sm.51.041' under 'nio' oem
adding 'sm.51.007-c2' under 'nio' oem
adding 'sm.51.003' under 'nio' oem

[('bosch', 'gs93016-pa66'),
 ('nissan', 'as26'),
 ('geely', 'q/jly j7111001a-2016â‘¢'),
 ('geely', 'q/jly j7110235b-2018â‘¡'),
 ('byd', 'byd-ty-d13f05-0106'),
 ('byd', 'byd-ty-d13f05-0043'),
 ('man', 'man m3236'),
 ('man', 'man m3236 a7'),
 ('nio', 'nio-sm.51.010-c6'),
 ('nio', 'nio-sm.51.010-c4'),
 ('nio', 'nio-sm.51.010'),
 ('nio', 'nio-sm.51.041'),
 ('nio', 'nio-sm.51.007-c2'),
 ('nio', 'nio-sm.51.003')]

In [173]:
# identify duplicates

for oem in auto_certs:
    for cert in auto_certs[oem]:
        for oem2 in auto_certs:
            if oem!=oem2 and cert in auto_certs[oem2]:
                print(f"'{cert}' present in '{oem}' and '{oem2}'")

In [174]:
railway_certifications_combinations

[('R23 - HL3 (EN 45545-2)', 'R23', 'HL3', 'EN 45545-2'),
 ('R24 - HL3 (EN 45545-2)', 'R24', 'HL3', 'EN 45545-2'),
 ('R22 - HL2 (EN 45545-2)', 'R22', 'HL2', 'EN 45545-2'),
 ('R26 - V0 (EN 45545-2)', 'R26', 'V0', 'EN 45545-2'),
 ('R22 - HL3 (EN 45545-2)', 'R22', 'HL3', 'EN 45545-2'),
 ('R24 - HL2 (EN 45545-2)', 'R24', 'HL2', 'EN 45545-2'),
 ('R23 - HL2 (EN 45545-2)', 'R23', 'HL2', 'EN 45545-2'),
 ('R22 - HL1 (EN 45545-2)', 'R22', 'HL1', 'EN 45545-2')]

In [175]:
auto_certifications = []
for oem in auto_certs:
    for cert in auto_certs[oem]:
        auto_certifications.append((oem, cert))
        
    if len(auto_certs[oem]) < 5:
        for cert in auto_certs[oem]:
            auto_certifications.append((oem, cert))

        for cert in auto_certs[oem]:
            auto_certifications.append((oem, cert))

    # add again
    if len(auto_certs[oem]) < 3:
        for cert in auto_certs[oem]:
            auto_certifications.append((oem, cert))

        for cert in auto_certs[oem]:
            auto_certifications.append((oem, cert))

In [176]:
auto_certifications[:5]

[('baic', 'q-bjev 01.59'),
 ('baic', 'q-bjev 01.33'),
 ('baic', 'bas-491'),
 ('baic', 'bas-492'),
 ('baic', 'q-bjev 01.59')]

In [177]:
print(len(auto_certifications))

973

In [178]:
auto_syns = synonym_df2[synonym_df2['TYPE']=='auto cert'][['DEFINED_NAME', 'SYNONYMS']].groupby(by='DEFINED_NAME')['SYNONYMS'].apply(list).to_dict()
for i in auto_syns:
    if i not in auto_syns[i]:
        auto_syns[i].append(i)
        
auto_syns

{'mercedes-benz': ['mercedes-benz',
  'daimler',
  'daimler-benz',
  'daimler mercedes',
  'daimler mercedes-benz',
  'daimler mercedes-benz group',
  'mercedes',
  'mercedes-benz group (daimier)'],
 'vw group': ['vw group', 'vw', 'bentley']}

In [179]:
auto_syns_mapping = {}
for meaning, syns in auto_syns.items():
    for syn in syns:
        auto_syns_mapping[syn] = meaning

auto_syns_mapping

{'mercedes-benz': 'mercedes-benz',
 'daimler': 'mercedes-benz',
 'daimler-benz': 'mercedes-benz',
 'daimler mercedes': 'mercedes-benz',
 'daimler mercedes-benz': 'mercedes-benz',
 'daimler mercedes-benz group': 'mercedes-benz',
 'mercedes': 'mercedes-benz',
 'mercedes-benz group (daimier)': 'mercedes-benz',
 'vw group': 'vw group',
 'vw': 'vw group',
 'bentley': 'vw group'}

#### Auto Certifications

In [180]:
auto_cert = random.choice(auto_certifications)
auto_name = auto_cert[0]
auto_cert_name = auto_cert[1]
print(auto_name)
print(auto_cert_name)

stellantis-chrysler
cpn 2776 ms.50017

In [181]:
auto_certifications

[('baic', 'q-bjev 01.59'),
 ('baic', 'q-bjev 01.33'),
 ('baic', 'bas-491'),
 ('baic', 'bas-492'),
 ('baic', 'q-bjev 01.59'),
 ('baic', 'q-bjev 01.33'),
 ('baic', 'bas-491'),
 ('baic', 'bas-492'),
 ('baic', 'q-bjev 01.59'),
 ('baic', 'q-bjev 01.33'),
 ('baic', 'bas-491'),
 ('baic', 'bas-492'),
 ('bmw', 'gs93017'),
 ('bmw', 'gs93016'),
 ('bmw', 'gs97014'),
 ('bmw', 'gs93016-pbt+asa-gf20'),
 ('bmw', 'gs93016-pbt+asa-gf30'),
 ('bmw', 'gs93016-pbt'),
 ('bmw', 'gs93016-pbt-gf15'),
 ('bmw', 'gs93016-pbt-gf20'),
 ('bmw', 'gs93016-pbt-gf30'),
 ('bmw', 'gs93016-pbt-gb20'),
 ('bmw', 'gs93016-pet-gf30'),
 ('bmw', 'gs93016-pet-gf45'),
 ('bmw', 'gs93016-pet-(mx20+gf15)'),
 ('bmw', 'gs93042'),
 ('bmw', 'gs93016-pa66'),
 ('bmw', 'gs93016-pa66-gf30'),
 ('bmw', 'gs93016-pa66-gf35'),
 ('bmw', 'gs93016-pa66-gf50'),
 ('bmw', 'gs93016-pa6-gf15'),
 ('bmw', 'gs93016-pa6-gf30'),
 ('bmw', 'gs93016-pa66-gf15'),
 ('bmw', 'gs93016-pa66-gf25'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('bosch', 'n28 bn07-gf010'),
 ('bosch', 'n28 bn07-o001'),
 ('bosch', 'n28 bn07-gf014'),
 ('bosch', 'n28 bn07-gf032'),
 ('bosch', 'n28 bn08-gf009'),
 ('bosch', 'n28 bn08-gf013'),
 ('bosch', 'n28 bn07-gf028'),
 ('bosch', 'n28 bn22-x003'),
 ('bosch', 'n28 bn22-x009'),
 ('bosch', 'n28 bn22-o034'),
 ('bosch', 'n28 bn09-gf027'),
 ('bosch', 'n28 bn09-gf026'),
 ('bosch', 'n28 bn09-gf024'),
 ('bosch', 'n28 bn07-gf019'),
 ('bosch', 'n28 bn08-gf018'),
 ('bosch', 'n28 bn07-gf003'),
 ('bosch', 'n28 bn07-gf012'),
 ('bosch', 'n28 bn07-gf023'),
 ('bosch', 'n28 bn07-gf051'),
 ('bosch', 'n28 bn14-gf010'),
 ('bosch', 'n28 bn22-o024'),
 ('bosch', 'n28 bn22-o027'),
 ('bosch', 'n28 bn22-o025'),
 ('bosch', 'n28 bn22-o026'),
 ('bosch', 'n28 bn22-o004'),
 ('bosch', 'n28 bn22-o028'),
 ('bosch', 'n28 bn22-o010'),
 ('bosch', 'n28 bn22-x013'),
 ('bosch', 'n28 bn22-x006'),
 ('bosch', 'n28 bn22-x022'),
 ('bosch', 'n28 bn22-x010'),
 ('bosch', 'n28 bn22-x014'),
 ('bosch', 'n28 bn22-x015'),
 ('bosch', 'n28 bn22-x016'),
 ('bosch', 'n28 bn22-o017'),
 ('bosch', 'n28 bn22-o014'),
 ('bosch', 'n28 bn22-o015'),
 ('bosch', 'n28 bn22-x017'),
 ('bosch', 'n28 bn22-o037'),
 ('bosch', 'n28 bn22-x005'),
 ('bosch', 'n28 bn22-x021'),
 ('bosch', 'n28 bn90-21-005'),
 ('bosch', 'n28 bn90-21-004'),
 ('bosch', 'n28 bn90-21-008'),
 ('bosch', 'n28 bn34-ox036'),
 ('bosch', 'n28 bn34-ox067'),
 ('bosch', 'n28 bn34-ox035'),
 ('bosch', 'n28 bn34-ox 017'),
 ('bosch', 'n28 bn35-x001'),
 ('bosch', 'n28 bn02-gf053'),
 ('bosch', 'n28 bn02-gf034'),
 ('bosch', 'n28 bn02-gf126'),
 ('bosch', 'n28 bn02-gf128'),
 ('bosch', 'n28 bn02-gf073'),
 ('bosch', 'n28 bn05-ox020'),
 ('bosch', 'n28 bn05-ox019'),
 ('bosch', 'n28 bn02-gf122'),
 ('bosch', 'n28 bn05-ox088'),
 ('bosch', 'n28 bn05-ox036'),
 ('bosch', 'n28 bn05-ox049'),
 ('bosch', 'n28 bn05-ox089'),
 ('bosch', 'n28 bn02-o035'),
 ('catl', 'pa66-gf30-x-i0x'),
 ('catl', 'pa66-gf25-a-i01'),
 ('catl', 'pa66-gf25-a-01'),
 ('catl', 'pa66-gf30-x-i0x'),
 ('catl', 'pa66-gf25-a-i01'),
 ('catl', 'pa66-gf25-a-01'),
 ('catl', 'pa66-gf30-x-i0x'),
 ('catl', 'pa66-gf25-a-i01'),
 ('catl', 'pa66-gf25-a-01'),
 ('changan', 'mts-f01-02-001-a3'),
 ('changan', 'mts-f01-02-001-a3'),
 ('changan', 'mts-f01-02-001-a3'),
 ('changan', 'mts-f01-02-001-a3'),
 ('changan', 'mts-f01-02-001-a3'),
 ('chery', 'cmp.pbt.a1'),
 ('chery', 'cmp.pbt.g2'),
 ('chery', 'cmp.pbt.33'),
 ('chery', 'cmp.pa66.a1'),
 ('chery', 'cmp.pa66.g3'),
 ('chery', 'cmp.pa66.g6'),
 ('chery', 'cmp.pa66.g7'),
 ('chery', 'cmp.pa6.g3'),
 ('chery', 'cmp.pa66.a2'),
 ('continental', 'sn 57908-7'),
 ('continental', 'tst n 055 47.12'),
 ('continental', 'sn 57908-17'),
 ('continental', 'sn 57908-11'),
 ('continental', 'sn 57908-6'),
 ('continental', 'tst n 055 47.27'),
 ('continental', 'sn 57908-4'),
 ('continental', 'tst n 055 54.10'),
 ('continental', 'tst n 055 54.07'),
 ('continental', 'tst n 055 54.12'),
 ('continental', '30.5251-0367.7'),
 ('continental', 'tst n 055 54.23'),
 ('continental', 'tst n 055 58.01'),
 ('continental', 'tst n 055 58.03'),
 ('continental', 'tst n 055 58.12'),
 ('continental', 'tst n 055 54.32'),
 ('continental', 'tst n 055 54.30'),
 ('continental', 'tst n 055 54.11'),
 ('continental', 'tst n 055 54.03'),
 ('continental', 'tst n 055 54.25'),
 ('continental', 'tst n 055 54.16'),
 ('continental', 'tst n 055 54.14'),
 ('continental', 'sn 57914-7'),
 ('continental', 'tst n 055 54.22'),
 ('continental', 'tst n 055 54.37'),
 ('continental', 'tst n 055 54.13'),
 ('continental', 'tst n 055 54.15'),
 ('continental', 'tst n 055 54.09'),
 ('continental', 'tst n 055 54.18'),
 ('continental', 'tst n 055 54.35'),
 ('continental', 'tst n 055 54.44'),
 ('continental', 'tst n 055 54.40'),
 ('continental', 'tst n 055 54.17'),
 ('continental', 'tst n 055 72.01-000'),
 ('continental', 'tst n 055 72.03-001'),
 ('dongfeng motor', 'slclbg2016018'),
 ('dongfeng motor', 'slclbg2019011'),
 ('dongfeng motor', 'slclbg2018035'),
 ('dongfeng motor', 'eqcl-67-2017 tpe 55d'),
 ('dongfeng motor', 'slclbg2016018'),
 ('dongfeng motor', 'slclbg2019011'),
 ('dongfeng motor', 'slclbg2018035'),
 ('dongfeng motor', 'eqcl-67-2017 tpe 55d'),
 ('dongfeng motor', 'slclbg2016018'),
 ('dongfeng motor', 'slclbg2019011'),
 ('dongfeng motor', 'slclbg2018035'),
 ('dongfeng motor', 'eqcl-67-2017 tpe 55d'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('faw group', 'jf03-28'),
 ('faw group', 'jf03-28'),
 ('faw group', 'jf03-28'),
 ('faw group', 'jf03-28'),
 ('faw group', 'jf03-28'),
 ('ford', 'wss-m4d725-b1'),
 ('ford', 'wss-m4d929-a3'),
 ('ford', 'wss-m4d1017-a1'),
 ('ford', 'wrs-m4d625-a3'),
 ('ford', 'wsb-m4d921-a'),
 ('ford', 'wsb-m4d883-a1'),
 ('ford', 'wsk-m4d635-a1'),
 ('ford', 'wsk-m4d635-a3'),
 ('ford', 'wsk-m4d635-a2'),
 ('ford', 'wsk-m4d840-a5'),
 ('ford', 'wsb-m4d840-a4'),
 ('ford', 'wsk-m4d840-a3'),
 ('ford', 'wss-m4d840-a6'),
 ('ford', 'wss-m4d840-b1'),
 ('ford', 'wsk-m4d840-a1'),
 ('ford', 'wsb-m4d677-a'),
 ('ford', 'wsb-m4d678-a'),
 ('ford', 'wsb-m4d679-a'),
 ('ford', 'wsb-m4d680-a'),
 ('ford', 'wss-m4d865-b5'),
 ('ford', 'wss-m4d865-b7'),
 ('ford', 'wss-m4d865-b4'),
 ('ford', 'wss-m4d865-b8'),
 ('ford', 'wss-m4d865-b1'),
 ('ford', 'wss-m4d865-b3'),
 ('ford', 'wsk-m4d639-a'),
 ('ford', 'wss-m4d1014-a'),
 ('ford', 'wsk-m4d895-a1'),
 ('ford', 'wsk-m4d896-a1'),
 ('ford', 'wsk-m4d636-a'),
 ('ford', 'wsk-m4d636-a2'),
 ('ford', 'wrs-m4d673-b2'),
 ('ford', 'wsl-m4d807-a'),
 ('ford', 'wsf-m4d803-a2'),
 ('ford', 'wss-m4d1063-a1'),
 ('ford', 'wss-m4d1063-a2'),
 ('ford', 'wsk-m4d840-a2'),
 ('ford', 'wsk-m4d635-a4'),
 ('ford', 'wsk-m4d618-a2'),
 ('ford', 'wsf-m4d618-a'),
 ('ford', 'wss-m4d1006-a1'),
 ('ford', 'wss-m98p14-a7'),
 ('ford', 'wss-m98p14-a3'),
 ('ford', 'wsd-m2d378-a1'),
 ('ford', 'wss-m9p9-d2'),
 ('ford', 'wsd-m2d379-a1'),
 ('ford', 'wsd-m2d380-a1'),
 ('ford', 'wsd-m2d381-a1'),
 ('ford', 'wsd-m2d382-a1'),
 ('ford', 'wsd-m2d441-a'),
 ('ford', 'wsd-m2d378-a4'),
 ('ford', 'wss-m2d378-b1'),
 ('ford', 'wss-m2d510-a6'),
 ('ford', 'wss-m2d379-b1'),
 ('ford', 'wss-m2d380-b1'),
 ('ford', 'wss-m9p14-a1'),
 ('ford', 'wss-m2d281-b1'),
 ('ford', 'wss-m2d382-b1'),
 ('ford', 'wss-m2d510-a5'),
 ('ford', 'wss-m2d510-a7'),
 ('ford', 'wss-m2d510-a8'),
 ('ford', 'wss-m4d648-b1'),
 ('ford', 'wss-m4d706-b1'),
 ('ford', 'wss-m4d1016-a1'),
 ('ford', 'wss-m4d752-b1'),
 ('ford', 'wss-m4d673-b1'),
 ('ford', 'wsk-m4d665-a2'),
 ('ford', 'wss-m4d993-b1'),
 ('ford', 'wss-m4d1038-a1'),
 ('ford', 'wss-m98p13-e'),
 ('ford', 'wsk-m4d591-a'),
 ('ford', 'wss-m4d703-b1'),
 ('ford', 'wss-m4d1009-a1'),
 ('ford', 'wss-m98p14-a9'),
 ('ford', 'wss-m4d861-a3'),
 ('ford', 'wss-m4d861-a4'),
 ('ford', 'wss-m4d706-a4'),
 ('ford', 'wsk-m4d666-a'),
 ('ford', 'wss-m4d666-b1'),
 ('ford', 'wss-m4d666-a2'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('general motors (gm)', 'gmw16733p-pbt-gf30'),
 ('general motors (gm)', 'gmw16733p-pbt-gf15'),
 ('general motors (gm)', 'gmw16459p-pbt-gf30w'),
 ('general motors (gm)', 'gmw16733p-pbt-gf30f'),
 ('general motors (gm)', 'gmw17249'),
 ('general motors (gm)', 'gmw18161p-pbt+pet-gf55'),
 ('general motors (gm)', 'gmw16873p-pbt+pet-m7gf33'),
 ('general motors (gm)', 'gmw17448p-pbt+pet-gf15m15'),
 ('general motors (gm)', 'gmw16873p-pbt+pet-m5gf25'),
 ('general motors (gm)', 'gmw3038p-pa66-gf35h'),
 ('general motors (gm)', 'gmw3038p-pa66-gf35j'),
 ('general motors (gm)', 'gmw3029p-pa6-gf30h'),
 ('general motors (gm)', 'gmw22p-pom-c1'),
 ('general motors (gm)', 'gmw22p-pom-c4'),
 ('general motors (gm)', 'gmw22p-pom-c2'),
 ('general motors (gm)', 'gmw17810p-pa66-gf40'),
 ('general motors (gm)', 'gmw17810p-pa66-gf60'),
 ('general motors (gm)', 'gmw17697p-pp-gf20e'),
 ('general motors (gm)', 'gmw15890p-pp-gf20e-class-u'),
 ('general motors (gm)', 'gmw15890p-pp-gf20e'),
 ('general motors (gm)', 'gmw15890p-pp-gf30e'),
 ('general motors (gm)', 'gmw16272'),
 ('general motors (gm)', 'gmw15890p-pp-gf40'),
 ('general motors (gm)', 'gmw15890p-pp-gf40-class-u'),
 ('general motors (gm)', 'gmw17697p-pp-gf40'),
 ('general motors (gm)', 'gmw15890p-pp-gf50 type 50'),
 ('general motors (gm)', 'gmw16272p-pp-gf50'),
 ('general motors (gm)', 'gmw15890p-pp-gf60'),
 ('general motors (gm)', 'gmw17802p-pa6-t1'),
 ('general motors (gm)', 'gmw17025p-pbt'),
 ('general motors (gm)', 'gmw17521p-pps-gf40e'),
 ('general motors (gm)', 'gmw17521p-pps-gf40'),
 ('general motors (gm)', 'gmw17519p-pps-(gf45-md20)'),
 ('general motors (gm)', 'gmw17769p-pps-t2'),
 ('general motors (gm)', 'gmw16720p-pe'),
 ('general motors (gm)', 'gmw22p-pom-c3'),
 ('general motors (gm)', 'gmw18026p-pom'),
 ('general motors (gm)', 'gmw17968p-pom-gf20'),
 ('general motors (gm)', 'gmw17968p-pom-gf25'),
 ('general motors (gm)', 'gmw17008p-pom-c2'),
 ('general motors (gm)', 'gmw16278p-pom-type c2'),
 ('general motors (gm)', 'gmw17195p-pom-t2'),
 ('general motors (gm)', 'gmw17624p-pom'),
 ('general motors (gm)', 'gmw18052p-pom'),
 ('general motors (gm)', 'gmw22p-pom-c2p1'),
 ('general motors (gm)', 'gmw22p-pom-c2p2'),
 ('general motors (gm)', 'gmw16657p-pom'),
 ('general motors (gm)', 'gmw16924p-pom-c4'),
 ('general motors (gm)', 'gmw16924p-pom-c2'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 1'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 2'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 3m1'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 3m2h'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 3m2'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 4'),
 ('general motors (gm)', 'gmw17186p-tpc-et-type 2'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 5'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 6'),
 ('general motors (gm)', 'gmw17187p-tpc-et-type 2'),
 ('general motors (gm)', 'gmw17187p-tpc-et-type 3'),
 ('general motors (gm)', 'gmw17457p-tpc-et-type 2'),
 ('general motors (gm)', 'gmw17479p-tpc-et-type 1b'),
 ('general motors (gm)', 'gmw17479p-tpc-et-type 1a'),
 ('general motors (gm)', 'gmw16278p-pom-type c3'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 4'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 5'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 6'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 7'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 8'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 9'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 10'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 2'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 4m'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 4e'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 5m'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 5e'),
 ('general motors (gm)', 'gmw15825p-tpv(epdm + pp) type 5'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 6e'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 7m'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 7e'),
 ('general motors (gm)', 'gmw15825p-tpv(epdm+pp)-type-6'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 8m'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 8e'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 9'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 10e'),
 ('general motors (gm)', 'gmw15816p-tpv-epdm+pp-class-i-type 4'),
 ('general motors (gm)', 'gmw15816p-tpv-epdm+pp-class-i-type-5'),
 ('general motors (gm)', 'gmw15816p-tpv-epdm+pp-class-i-type-6'),
 ('general motors (gm)', 'gmw16036p-pa66'),
 ('general motors (gm)', 'gmw17602p-pa612'),
 ('general motors (gm)', 'gmw17349p-pa66'),
 ('general motors (gm)', 'gmw3038p-pa66-gf15h'),
 ('general motors (gm)', 'gmw3038p-pa66-gf25h'),
 ('general motors (gm)', 'gmw16270p-pa66-gf25'),
 ('general motors (gm)', 'gmw3038p-pa66-gf25j'),
 ('general motors (gm)', 'gmw3038p-pa66-gf30h'),
 ('general motors (gm)', 'gmw16270p-pa66-gf30'),
 ('general motors (gm)', 'gmw3038p-pa66-gf30j'),
 ('general motors (gm)', 'gmw16802p-pa66-gf35'),
 ('general motors (gm)', 'gmw17961p-pa-gf35-t1'),
 ('general motors (gm)', 'gmw3038p-pa66-gf45h'),
 ('general motors (gm)', 'gmw3038p-pa66-gf45j'),
 ('general motors (gm)', 'gmw3038p-pa66-gf50h'),
 ('general motors (gm)', 'gmw3038p-pa66-gf50j'),
 ('general motors (gm)', 'gmw3029p-pa6-gf15h'),
 ('general motors (gm)', 'gmw16582p-pa6-gf15'),
 ('general motors (gm)', 'gmw16582p-pa6-gf30'),
 ('general motors (gm)', 'gmw3029p-pa6-gf35h'),
 ('general motors (gm)', 'gmw3029p-pa6-gf50h'),
 ('general motors (gm)', 'gmw17599p-pa612-gf35'),
 ('general motors (gm)', 'gmw17263p-pa66-gf15'),
 ('general motors (gm)', 'gmw17263p-pa66-gf35'),
 ('general motors (gm)', 'gmw17385p-pa6-gf40'),
 ('general motors (gm)', 'gmw17481p-pa66-gf25'),
 ('general motors (gm)', 'gmw18122p-pa-gf25-typea2'),
 ('general motors (gm)', 'gmw18122p-pa-gf25-typeaf'),
 ('general motors (gm)', 'gmw16799p-ppa-t2'),
 ('general motors (gm)', 'gmw16356p-ppa-gf15'),
 ('general motors (gm)', 'gmw16356p-ppa-gf35'),
 ('general motors (gm)', 'gmw16360p-ppa-gf35'),
 ('general motors (gm)', 'gmw16356p-ppa-gf45'),
 ('general motors (gm)', 'gmw16360p-ppa-gf45'),
 ('general motors (gm)', 'gmw16357p-ppa-gf35'),
 ('general motors (gm)', 'gmw18066p-ppa-gf15'),
 ('general motors (gm)', 'gmw18066p-ppa-gf35'),
 ('general motors (gm)', 'gmw17558p-pa612'),
 ('general motors (gm)', 'gmw17604p-pa612'),
 ('general motors (gm)', 'gmw16558p-pa66-t3'),
 ('general motors (gm)', 'gmw16447p-pa66-t2'),
 ('general motors (gm)', 'gmw16558p-pa66-t1'),
 ('general motors (gm)', 'gmw17961p-pa-gf35-t3'),
 ('general motors (gm)', 'gmw17047p-pa-gf50'),
 ('general motors (gm)', 'gmw16447p-pa66-t3'),
 ('general motors (gm)', 'gmw17430p-pa66-t2'),
 ('general motors (gm)', 'gmw16370p-pa66'),
 ('general motors (gm)', 'gmw16558p-pa66-t2'),
 ('general motors (gm)', 'gmw17577p-pa6-t2'),
 ('general motors (gm)', 'gmw17961p-pa-gf35-t2'),
 ('great wall motor', 'mp12-05'),
 ('great wall motor', 'mp05-01'),
 ('great wall motor', 'mp01 lg-01'),
 ('great wall motor', 'mp01-lg-03'),
 ('great wall motor', 'mp12-05'),
 ('great wall motor', 'mp05-01'),
 ('great wall motor', 'mp01 lg-01'),
 ('great wall motor', 'mp01-lg-03'),
 ('great wall motor', 'mp12-05'),
 ('great wall motor', 'mp05-01'),
 ('great wall motor', 'mp01 lg-01'),
 ('great wall motor', 'mp01-lg-03'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('hyundai', 'ms941-03 type f-5'),
 ('hyundai', 'ms237-09 type a'),
 ('hyundai', 'ms237-09 type b'),
 ('hyundai', 'ms216-03 type c'),
 ('hyundai', 'ms941-03 type f-5 frv0'),
 ('hyundai', 'ms216-03 type b'),
 ('hyundai', 'ms941-03 type f-5 frv0 cti0'),
 ('hyundai', 'ms941-03 type f-3 ah'),
 ('hyundai', 'ms941-03 type f-3 hi'),
 ('hyundai', 'ms941-03 type f-5 ah'),
 ('hyundai', 'ms216-03 type f-2'),
 ('hyundai', 'ms941-03 type f-1'),
 ('hyundai', 'ms941-03 type f-3'),
 ('hyundai', 'ms216-03 type f-1'),
 ('hyundai', 'ms244-02 type a-1'),
 ('hyundai', 'ms244-02 type a-2'),
 ('hyundai', 'ms237-14 type a'),
 ('hyundai', 'ms237-05 type a-2'),
 ('hyundai', 'ms237-05 type d'),
 ('hyundai', 'ms237-05 type a-1'),
 ('hyundai', 'ms220-24 type e'),
 ('hyundai', 'ms220-24 type e'),
 ('hyundai', 'ms220-24 type d'),
 ('hyundai', 'ms220-24 type b'),
 ('hyundai', 'ms220-24 type c'),
 ('hyundai', 'ms220-24 type g'),
 ('hyundai', 'ms220-08 type a'),
 ('hyundai', 'ms220-24 type a'),
 ('hyundai', 'ms220-08 type d'),
 ('hyundai', 'ms237-09 type e-1'),
 ('hyundai', 'ms237-05 type b'),
 ('hyundai', 'ms237-05 type e-1'),
 ('hyundai', 'ms941-03 type m-1'),
 ('hyundai', 'ms237-12 type a'),
 ('hyundai', 'ms237-05 type c'),
 ('hyundai', 'ms216-05 type b'),
 ('hyundai', 'ms220-05 type a'),
 ('hyundai', 'ms220-05 type b'),
 ('hyundai', 'ms220-31 type a1'),
 ('hyundai', 'ms220-05 type c'),
 ('hyundai', 'ms220-31 type a2'),
 ('hyundai', 'ms220-05 type d'),
 ('hyundai', 'ms220-05 type e'),
 ('hyundai', 'ms220-05 type g'),
 ('hyundai', 'ms220-05 type h'),
 ('hyundai', 'ms220-05 type k'),
 ('hyundai', 'ms220-05 type j'),
 ('hyundai', 'ms220-13 type d-1'),
 ('hyundai', 'ms220-05 type p'),
 ('hyundai', 'ms220-05 c'),
 ('hyundai', 'ms220-05 p'),
 ('hyundai', 'ms220-05 type l'),
 ('hyundai', 'ms220-05 type m'),
 ('hyundai', 'ms220-13 type c-1'),
 ('hyundai', 'ms220-05 type n'),
 ('hyundai', 'ms220-13 type f-1'),
 ('hyundai', 'ms220-05 type r'),
 ('hyundai', 'ms220-13 type e-1'),
 ('hyundai', 'ms941-03 type j-2'),
 ('hyundai', 'ms941-03 type p-2 frvo'),
 ('hyundai', 'ms211-37 type d'),
 ('hyundai', 'ms211-46 type e'),
 ('hyundai', 'ms211-46 type b'),
 ('hyundai', 'ms211-66 type b'),
 ('hyundai', 'ms941-03 type a-2'),
 ('hyundai', 'ms941-03 type a-5'),
 ('hyundai', 'ms941-03 type a-6'),
 ('hyundai', 'ms211-47 type a-2-3'),
 ('hyundai', 'ms941-03 type a-7'),
 ('hyundai', 'ms211-37 type e'),
 ('hyundai', 'ms211-36 type a-1'),
 ('hyundai', 'ms211-66 type c'),
 ('hyundai', 'ms211-47 type a-3'),
 ('hyundai', 'ms211-44 type c'),
 ('hyundai', 'ms941-03 type d-2'),
 ('hyundai', 'ms941-03 type d-3'),
 ('hyundai', 'ms211-56 type'),
 ('hyundai', 'ms941-03 type a-3 hi'),
 ('hyundai', 'ms211-72 type a'),
 ('hyundai', 'ms941-03 type a-5 frv0'),
 ('hyundai', 'ms941-12 type b'),
 ('hyundai', 'ms941-03 type n-4'),
 ('hyundai', 'ms211-19 type b-1'),
 ('hyundai', 'ms211-80 type b'),
 ('hyundai', 'ms211-35 type c'),
 ('hyundai', 'ms211-46 type c-2'),
 ('hyundai', 'ms211-72 type b'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('li auto', 'q/lia5310038'),
 ('li auto', 'q/lia5310020'),
 ('li auto', 'q/lia5310050'),
 ('li auto', 'q/lia5310057'),
 ('li auto', 'q/lia5310038'),
 ('li auto', 'q/lia5310020'),
 ('li auto', 'q/lia5310050'),
 ('li auto', 'q/lia5310057'),
 ('li auto', 'q/lia5310038'),
 ('li auto', 'q/lia5310020'),
 ('li auto', 'q/lia5310050'),
 ('li auto', 'q/lia5310057'),
 ('man', 'm3236 a7'),
 ('man', 'm3236 a5'),
 ('man', 'm3236 a6'),
 ('man', 'm3236'),
 ('man', 'm3236 a7'),
 ('mercedes-benz', 'dbl5410'),
 ('mercedes-benz', 'dbl5408'),
 ('mercedes-benz', 'dbl5409'),
 ('mercedes-benz', 'dbl5405-06-pom-c'),
 ('mercedes-benz', 'dbl 5416'),
 ('mercedes-benz', 'dbl5404'),
 ('mercedes-benz', 'dbl5418'),
 ('mercedes-benz', 'dbl5416'),

In [182]:
additional_autocerts = [
    ('li auto', 'lia5310020'),
    ('li auto', 'lia5310038'),
    ('li auto', 'lia5310050'),
    ('li auto', 'lia5310057'),
    ('li auto', 'q-lia5310020'),
    ('li auto', 'q-lia5310038'),
    ('li auto', 'q-lia5310050'),
    ('li auto', 'q-lia5310057'),
    ("geely", "q/jly j7111001a-2016"),
    ("geely", "q/jly j7110235b-2018"),
    ("geely", "q/jly j7111001a-2016"),
    ("geely", "q/jly j7110235b-2018"),
]

auto_certifications += additional_autocerts
auto_certifications

[('baic', 'q-bjev 01.59'),
 ('baic', 'q-bjev 01.33'),
 ('baic', 'bas-491'),
 ('baic', 'bas-492'),
 ('baic', 'q-bjev 01.59'),
 ('baic', 'q-bjev 01.33'),
 ('baic', 'bas-491'),
 ('baic', 'bas-492'),
 ('baic', 'q-bjev 01.59'),
 ('baic', 'q-bjev 01.33'),
 ('baic', 'bas-491'),
 ('baic', 'bas-492'),
 ('bmw', 'gs93017'),
 ('bmw', 'gs93016'),
 ('bmw', 'gs97014'),
 ('bmw', 'gs93016-pbt+asa-gf20'),
 ('bmw', 'gs93016-pbt+asa-gf30'),
 ('bmw', 'gs93016-pbt'),
 ('bmw', 'gs93016-pbt-gf15'),
 ('bmw', 'gs93016-pbt-gf20'),
 ('bmw', 'gs93016-pbt-gf30'),
 ('bmw', 'gs93016-pbt-gb20'),
 ('bmw', 'gs93016-pet-gf30'),
 ('bmw', 'gs93016-pet-gf45'),
 ('bmw', 'gs93016-pet-(mx20+gf15)'),
 ('bmw', 'gs93042'),
 ('bmw', 'gs93016-pa66'),
 ('bmw', 'gs93016-pa66-gf30'),
 ('bmw', 'gs93016-pa66-gf35'),
 ('bmw', 'gs93016-pa66-gf50'),
 ('bmw', 'gs93016-pa6-gf15'),
 ('bmw', 'gs93016-pa6-gf30'),
 ('bmw', 'gs93016-pa66-gf15'),
 ('bmw', 'gs93016-pa66-gf25'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('byd', 'ty-d13f05-0106'),
 ('byd', 'ty-d13f05-0043'),
 ('bosch', 'n28 bn07-gf010'),
 ('bosch', 'n28 bn07-o001'),
 ('bosch', 'n28 bn07-gf014'),
 ('bosch', 'n28 bn07-gf032'),
 ('bosch', 'n28 bn08-gf009'),
 ('bosch', 'n28 bn08-gf013'),
 ('bosch', 'n28 bn07-gf028'),
 ('bosch', 'n28 bn22-x003'),
 ('bosch', 'n28 bn22-x009'),
 ('bosch', 'n28 bn22-o034'),
 ('bosch', 'n28 bn09-gf027'),
 ('bosch', 'n28 bn09-gf026'),
 ('bosch', 'n28 bn09-gf024'),
 ('bosch', 'n28 bn07-gf019'),
 ('bosch', 'n28 bn08-gf018'),
 ('bosch', 'n28 bn07-gf003'),
 ('bosch', 'n28 bn07-gf012'),
 ('bosch', 'n28 bn07-gf023'),
 ('bosch', 'n28 bn07-gf051'),
 ('bosch', 'n28 bn14-gf010'),
 ('bosch', 'n28 bn22-o024'),
 ('bosch', 'n28 bn22-o027'),
 ('bosch', 'n28 bn22-o025'),
 ('bosch', 'n28 bn22-o026'),
 ('bosch', 'n28 bn22-o004'),
 ('bosch', 'n28 bn22-o028'),
 ('bosch', 'n28 bn22-o010'),
 ('bosch', 'n28 bn22-x013'),
 ('bosch', 'n28 bn22-x006'),
 ('bosch', 'n28 bn22-x022'),
 ('bosch', 'n28 bn22-x010'),
 ('bosch', 'n28 bn22-x014'),
 ('bosch', 'n28 bn22-x015'),
 ('bosch', 'n28 bn22-x016'),
 ('bosch', 'n28 bn22-o017'),
 ('bosch', 'n28 bn22-o014'),
 ('bosch', 'n28 bn22-o015'),
 ('bosch', 'n28 bn22-x017'),
 ('bosch', 'n28 bn22-o037'),
 ('bosch', 'n28 bn22-x005'),
 ('bosch', 'n28 bn22-x021'),
 ('bosch', 'n28 bn90-21-005'),
 ('bosch', 'n28 bn90-21-004'),
 ('bosch', 'n28 bn90-21-008'),
 ('bosch', 'n28 bn34-ox036'),
 ('bosch', 'n28 bn34-ox067'),
 ('bosch', 'n28 bn34-ox035'),
 ('bosch', 'n28 bn34-ox 017'),
 ('bosch', 'n28 bn35-x001'),
 ('bosch', 'n28 bn02-gf053'),
 ('bosch', 'n28 bn02-gf034'),
 ('bosch', 'n28 bn02-gf126'),
 ('bosch', 'n28 bn02-gf128'),
 ('bosch', 'n28 bn02-gf073'),
 ('bosch', 'n28 bn05-ox020'),
 ('bosch', 'n28 bn05-ox019'),
 ('bosch', 'n28 bn02-gf122'),
 ('bosch', 'n28 bn05-ox088'),
 ('bosch', 'n28 bn05-ox036'),
 ('bosch', 'n28 bn05-ox049'),
 ('bosch', 'n28 bn05-ox089'),
 ('bosch', 'n28 bn02-o035'),
 ('catl', 'pa66-gf30-x-i0x'),
 ('catl', 'pa66-gf25-a-i01'),
 ('catl', 'pa66-gf25-a-01'),
 ('catl', 'pa66-gf30-x-i0x'),
 ('catl', 'pa66-gf25-a-i01'),
 ('catl', 'pa66-gf25-a-01'),
 ('catl', 'pa66-gf30-x-i0x'),
 ('catl', 'pa66-gf25-a-i01'),
 ('catl', 'pa66-gf25-a-01'),
 ('changan', 'mts-f01-02-001-a3'),
 ('changan', 'mts-f01-02-001-a3'),
 ('changan', 'mts-f01-02-001-a3'),
 ('changan', 'mts-f01-02-001-a3'),
 ('changan', 'mts-f01-02-001-a3'),
 ('chery', 'cmp.pbt.a1'),
 ('chery', 'cmp.pbt.g2'),
 ('chery', 'cmp.pbt.33'),
 ('chery', 'cmp.pa66.a1'),
 ('chery', 'cmp.pa66.g3'),
 ('chery', 'cmp.pa66.g6'),
 ('chery', 'cmp.pa66.g7'),
 ('chery', 'cmp.pa6.g3'),
 ('chery', 'cmp.pa66.a2'),
 ('continental', 'sn 57908-7'),
 ('continental', 'tst n 055 47.12'),
 ('continental', 'sn 57908-17'),
 ('continental', 'sn 57908-11'),
 ('continental', 'sn 57908-6'),
 ('continental', 'tst n 055 47.27'),
 ('continental', 'sn 57908-4'),
 ('continental', 'tst n 055 54.10'),
 ('continental', 'tst n 055 54.07'),
 ('continental', 'tst n 055 54.12'),
 ('continental', '30.5251-0367.7'),
 ('continental', 'tst n 055 54.23'),
 ('continental', 'tst n 055 58.01'),
 ('continental', 'tst n 055 58.03'),
 ('continental', 'tst n 055 58.12'),
 ('continental', 'tst n 055 54.32'),
 ('continental', 'tst n 055 54.30'),
 ('continental', 'tst n 055 54.11'),
 ('continental', 'tst n 055 54.03'),
 ('continental', 'tst n 055 54.25'),
 ('continental', 'tst n 055 54.16'),
 ('continental', 'tst n 055 54.14'),
 ('continental', 'sn 57914-7'),
 ('continental', 'tst n 055 54.22'),
 ('continental', 'tst n 055 54.37'),
 ('continental', 'tst n 055 54.13'),
 ('continental', 'tst n 055 54.15'),
 ('continental', 'tst n 055 54.09'),
 ('continental', 'tst n 055 54.18'),
 ('continental', 'tst n 055 54.35'),
 ('continental', 'tst n 055 54.44'),
 ('continental', 'tst n 055 54.40'),
 ('continental', 'tst n 055 54.17'),
 ('continental', 'tst n 055 72.01-000'),
 ('continental', 'tst n 055 72.03-001'),
 ('dongfeng motor', 'slclbg2016018'),
 ('dongfeng motor', 'slclbg2019011'),
 ('dongfeng motor', 'slclbg2018035'),
 ('dongfeng motor', 'eqcl-67-2017 tpe 55d'),
 ('dongfeng motor', 'slclbg2016018'),
 ('dongfeng motor', 'slclbg2019011'),
 ('dongfeng motor', 'slclbg2018035'),
 ('dongfeng motor', 'eqcl-67-2017 tpe 55d'),
 ('dongfeng motor', 'slclbg2016018'),
 ('dongfeng motor', 'slclbg2019011'),
 ('dongfeng motor', 'slclbg2018035'),
 ('dongfeng motor', 'eqcl-67-2017 tpe 55d'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('evergrande auto', 'egw.pl.0603-pom-co'),
 ('faw group', 'jf03-28'),
 ('faw group', 'jf03-28'),
 ('faw group', 'jf03-28'),
 ('faw group', 'jf03-28'),
 ('faw group', 'jf03-28'),
 ('ford', 'wss-m4d725-b1'),
 ('ford', 'wss-m4d929-a3'),
 ('ford', 'wss-m4d1017-a1'),
 ('ford', 'wrs-m4d625-a3'),
 ('ford', 'wsb-m4d921-a'),
 ('ford', 'wsb-m4d883-a1'),
 ('ford', 'wsk-m4d635-a1'),
 ('ford', 'wsk-m4d635-a3'),
 ('ford', 'wsk-m4d635-a2'),
 ('ford', 'wsk-m4d840-a5'),
 ('ford', 'wsb-m4d840-a4'),
 ('ford', 'wsk-m4d840-a3'),
 ('ford', 'wss-m4d840-a6'),
 ('ford', 'wss-m4d840-b1'),
 ('ford', 'wsk-m4d840-a1'),
 ('ford', 'wsb-m4d677-a'),
 ('ford', 'wsb-m4d678-a'),
 ('ford', 'wsb-m4d679-a'),
 ('ford', 'wsb-m4d680-a'),
 ('ford', 'wss-m4d865-b5'),
 ('ford', 'wss-m4d865-b7'),
 ('ford', 'wss-m4d865-b4'),
 ('ford', 'wss-m4d865-b8'),
 ('ford', 'wss-m4d865-b1'),
 ('ford', 'wss-m4d865-b3'),
 ('ford', 'wsk-m4d639-a'),
 ('ford', 'wss-m4d1014-a'),
 ('ford', 'wsk-m4d895-a1'),
 ('ford', 'wsk-m4d896-a1'),
 ('ford', 'wsk-m4d636-a'),
 ('ford', 'wsk-m4d636-a2'),
 ('ford', 'wrs-m4d673-b2'),
 ('ford', 'wsl-m4d807-a'),
 ('ford', 'wsf-m4d803-a2'),
 ('ford', 'wss-m4d1063-a1'),
 ('ford', 'wss-m4d1063-a2'),
 ('ford', 'wsk-m4d840-a2'),
 ('ford', 'wsk-m4d635-a4'),
 ('ford', 'wsk-m4d618-a2'),
 ('ford', 'wsf-m4d618-a'),
 ('ford', 'wss-m4d1006-a1'),
 ('ford', 'wss-m98p14-a7'),
 ('ford', 'wss-m98p14-a3'),
 ('ford', 'wsd-m2d378-a1'),
 ('ford', 'wss-m9p9-d2'),
 ('ford', 'wsd-m2d379-a1'),
 ('ford', 'wsd-m2d380-a1'),
 ('ford', 'wsd-m2d381-a1'),
 ('ford', 'wsd-m2d382-a1'),
 ('ford', 'wsd-m2d441-a'),
 ('ford', 'wsd-m2d378-a4'),
 ('ford', 'wss-m2d378-b1'),
 ('ford', 'wss-m2d510-a6'),
 ('ford', 'wss-m2d379-b1'),
 ('ford', 'wss-m2d380-b1'),
 ('ford', 'wss-m9p14-a1'),
 ('ford', 'wss-m2d281-b1'),
 ('ford', 'wss-m2d382-b1'),
 ('ford', 'wss-m2d510-a5'),
 ('ford', 'wss-m2d510-a7'),
 ('ford', 'wss-m2d510-a8'),
 ('ford', 'wss-m4d648-b1'),
 ('ford', 'wss-m4d706-b1'),
 ('ford', 'wss-m4d1016-a1'),
 ('ford', 'wss-m4d752-b1'),
 ('ford', 'wss-m4d673-b1'),
 ('ford', 'wsk-m4d665-a2'),
 ('ford', 'wss-m4d993-b1'),
 ('ford', 'wss-m4d1038-a1'),
 ('ford', 'wss-m98p13-e'),
 ('ford', 'wsk-m4d591-a'),
 ('ford', 'wss-m4d703-b1'),
 ('ford', 'wss-m4d1009-a1'),
 ('ford', 'wss-m98p14-a9'),
 ('ford', 'wss-m4d861-a3'),
 ('ford', 'wss-m4d861-a4'),
 ('ford', 'wss-m4d706-a4'),
 ('ford', 'wsk-m4d666-a'),
 ('ford', 'wss-m4d666-b1'),
 ('ford', 'wss-m4d666-a2'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('geely', 'q/jly j7110166b-2017'),
 ('geely', 'q/jl j124010-2019'),
 ('general motors (gm)', 'gmw16733p-pbt-gf30'),
 ('general motors (gm)', 'gmw16733p-pbt-gf15'),
 ('general motors (gm)', 'gmw16459p-pbt-gf30w'),
 ('general motors (gm)', 'gmw16733p-pbt-gf30f'),
 ('general motors (gm)', 'gmw17249'),
 ('general motors (gm)', 'gmw18161p-pbt+pet-gf55'),
 ('general motors (gm)', 'gmw16873p-pbt+pet-m7gf33'),
 ('general motors (gm)', 'gmw17448p-pbt+pet-gf15m15'),
 ('general motors (gm)', 'gmw16873p-pbt+pet-m5gf25'),
 ('general motors (gm)', 'gmw3038p-pa66-gf35h'),
 ('general motors (gm)', 'gmw3038p-pa66-gf35j'),
 ('general motors (gm)', 'gmw3029p-pa6-gf30h'),
 ('general motors (gm)', 'gmw22p-pom-c1'),
 ('general motors (gm)', 'gmw22p-pom-c4'),
 ('general motors (gm)', 'gmw22p-pom-c2'),
 ('general motors (gm)', 'gmw17810p-pa66-gf40'),
 ('general motors (gm)', 'gmw17810p-pa66-gf60'),
 ('general motors (gm)', 'gmw17697p-pp-gf20e'),
 ('general motors (gm)', 'gmw15890p-pp-gf20e-class-u'),
 ('general motors (gm)', 'gmw15890p-pp-gf20e'),
 ('general motors (gm)', 'gmw15890p-pp-gf30e'),
 ('general motors (gm)', 'gmw16272'),
 ('general motors (gm)', 'gmw15890p-pp-gf40'),
 ('general motors (gm)', 'gmw15890p-pp-gf40-class-u'),
 ('general motors (gm)', 'gmw17697p-pp-gf40'),
 ('general motors (gm)', 'gmw15890p-pp-gf50 type 50'),
 ('general motors (gm)', 'gmw16272p-pp-gf50'),
 ('general motors (gm)', 'gmw15890p-pp-gf60'),
 ('general motors (gm)', 'gmw17802p-pa6-t1'),
 ('general motors (gm)', 'gmw17025p-pbt'),
 ('general motors (gm)', 'gmw17521p-pps-gf40e'),
 ('general motors (gm)', 'gmw17521p-pps-gf40'),
 ('general motors (gm)', 'gmw17519p-pps-(gf45-md20)'),
 ('general motors (gm)', 'gmw17769p-pps-t2'),
 ('general motors (gm)', 'gmw16720p-pe'),
 ('general motors (gm)', 'gmw22p-pom-c3'),
 ('general motors (gm)', 'gmw18026p-pom'),
 ('general motors (gm)', 'gmw17968p-pom-gf20'),
 ('general motors (gm)', 'gmw17968p-pom-gf25'),
 ('general motors (gm)', 'gmw17008p-pom-c2'),
 ('general motors (gm)', 'gmw16278p-pom-type c2'),
 ('general motors (gm)', 'gmw17195p-pom-t2'),
 ('general motors (gm)', 'gmw17624p-pom'),
 ('general motors (gm)', 'gmw18052p-pom'),
 ('general motors (gm)', 'gmw22p-pom-c2p1'),
 ('general motors (gm)', 'gmw22p-pom-c2p2'),
 ('general motors (gm)', 'gmw16657p-pom'),
 ('general motors (gm)', 'gmw16924p-pom-c4'),
 ('general motors (gm)', 'gmw16924p-pom-c2'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 1'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 2'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 3m1'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 3m2h'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 3m2'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 4'),
 ('general motors (gm)', 'gmw17186p-tpc-et-type 2'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 5'),
 ('general motors (gm)', 'gmw17327p-tpc-et-type 6'),
 ('general motors (gm)', 'gmw17187p-tpc-et-type 2'),
 ('general motors (gm)', 'gmw17187p-tpc-et-type 3'),
 ('general motors (gm)', 'gmw17457p-tpc-et-type 2'),
 ('general motors (gm)', 'gmw17479p-tpc-et-type 1b'),
 ('general motors (gm)', 'gmw17479p-tpc-et-type 1a'),
 ('general motors (gm)', 'gmw16278p-pom-type c3'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 4'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 5'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 6'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 7'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 8'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 9'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 10'),
 ('general motors (gm)', 'gmw15813p-tpv-(epdm+pp)-type 2'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 4m'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 4e'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 5m'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 5e'),
 ('general motors (gm)', 'gmw15825p-tpv(epdm + pp) type 5'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 6e'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 7m'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 7e'),
 ('general motors (gm)', 'gmw15825p-tpv(epdm+pp)-type-6'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 8m'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 8e'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 9'),
 ('general motors (gm)', 'gmw15812p-tpv(epdm+pp)-type 10e'),
 ('general motors (gm)', 'gmw15816p-tpv-epdm+pp-class-i-type 4'),
 ('general motors (gm)', 'gmw15816p-tpv-epdm+pp-class-i-type-5'),
 ('general motors (gm)', 'gmw15816p-tpv-epdm+pp-class-i-type-6'),
 ('general motors (gm)', 'gmw16036p-pa66'),
 ('general motors (gm)', 'gmw17602p-pa612'),
 ('general motors (gm)', 'gmw17349p-pa66'),
 ('general motors (gm)', 'gmw3038p-pa66-gf15h'),
 ('general motors (gm)', 'gmw3038p-pa66-gf25h'),
 ('general motors (gm)', 'gmw16270p-pa66-gf25'),
 ('general motors (gm)', 'gmw3038p-pa66-gf25j'),
 ('general motors (gm)', 'gmw3038p-pa66-gf30h'),
 ('general motors (gm)', 'gmw16270p-pa66-gf30'),
 ('general motors (gm)', 'gmw3038p-pa66-gf30j'),
 ('general motors (gm)', 'gmw16802p-pa66-gf35'),
 ('general motors (gm)', 'gmw17961p-pa-gf35-t1'),
 ('general motors (gm)', 'gmw3038p-pa66-gf45h'),
 ('general motors (gm)', 'gmw3038p-pa66-gf45j'),
 ('general motors (gm)', 'gmw3038p-pa66-gf50h'),
 ('general motors (gm)', 'gmw3038p-pa66-gf50j'),
 ('general motors (gm)', 'gmw3029p-pa6-gf15h'),
 ('general motors (gm)', 'gmw16582p-pa6-gf15'),
 ('general motors (gm)', 'gmw16582p-pa6-gf30'),
 ('general motors (gm)', 'gmw3029p-pa6-gf35h'),
 ('general motors (gm)', 'gmw3029p-pa6-gf50h'),
 ('general motors (gm)', 'gmw17599p-pa612-gf35'),
 ('general motors (gm)', 'gmw17263p-pa66-gf15'),
 ('general motors (gm)', 'gmw17263p-pa66-gf35'),
 ('general motors (gm)', 'gmw17385p-pa6-gf40'),
 ('general motors (gm)', 'gmw17481p-pa66-gf25'),
 ('general motors (gm)', 'gmw18122p-pa-gf25-typea2'),
 ('general motors (gm)', 'gmw18122p-pa-gf25-typeaf'),
 ('general motors (gm)', 'gmw16799p-ppa-t2'),
 ('general motors (gm)', 'gmw16356p-ppa-gf15'),
 ('general motors (gm)', 'gmw16356p-ppa-gf35'),
 ('general motors (gm)', 'gmw16360p-ppa-gf35'),
 ('general motors (gm)', 'gmw16356p-ppa-gf45'),
 ('general motors (gm)', 'gmw16360p-ppa-gf45'),
 ('general motors (gm)', 'gmw16357p-ppa-gf35'),
 ('general motors (gm)', 'gmw18066p-ppa-gf15'),
 ('general motors (gm)', 'gmw18066p-ppa-gf35'),
 ('general motors (gm)', 'gmw17558p-pa612'),
 ('general motors (gm)', 'gmw17604p-pa612'),
 ('general motors (gm)', 'gmw16558p-pa66-t3'),
 ('general motors (gm)', 'gmw16447p-pa66-t2'),
 ('general motors (gm)', 'gmw16558p-pa66-t1'),
 ('general motors (gm)', 'gmw17961p-pa-gf35-t3'),
 ('general motors (gm)', 'gmw17047p-pa-gf50'),
 ('general motors (gm)', 'gmw16447p-pa66-t3'),
 ('general motors (gm)', 'gmw17430p-pa66-t2'),
 ('general motors (gm)', 'gmw16370p-pa66'),
 ('general motors (gm)', 'gmw16558p-pa66-t2'),
 ('general motors (gm)', 'gmw17577p-pa6-t2'),
 ('general motors (gm)', 'gmw17961p-pa-gf35-t2'),
 ('great wall motor', 'mp12-05'),
 ('great wall motor', 'mp05-01'),
 ('great wall motor', 'mp01 lg-01'),
 ('great wall motor', 'mp01-lg-03'),
 ('great wall motor', 'mp12-05'),
 ('great wall motor', 'mp05-01'),
 ('great wall motor', 'mp01 lg-01'),
 ('great wall motor', 'mp01-lg-03'),
 ('great wall motor', 'mp12-05'),
 ('great wall motor', 'mp05-01'),
 ('great wall motor', 'mp01 lg-01'),
 ('great wall motor', 'mp01-lg-03'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('honda', '0094z-ghaf-9810-m1'),
 ('hyundai', 'ms941-03 type f-5'),
 ('hyundai', 'ms237-09 type a'),
 ('hyundai', 'ms237-09 type b'),
 ('hyundai', 'ms216-03 type c'),
 ('hyundai', 'ms941-03 type f-5 frv0'),
 ('hyundai', 'ms216-03 type b'),
 ('hyundai', 'ms941-03 type f-5 frv0 cti0'),
 ('hyundai', 'ms941-03 type f-3 ah'),
 ('hyundai', 'ms941-03 type f-3 hi'),
 ('hyundai', 'ms941-03 type f-5 ah'),
 ('hyundai', 'ms216-03 type f-2'),
 ('hyundai', 'ms941-03 type f-1'),
 ('hyundai', 'ms941-03 type f-3'),
 ('hyundai', 'ms216-03 type f-1'),
 ('hyundai', 'ms244-02 type a-1'),
 ('hyundai', 'ms244-02 type a-2'),
 ('hyundai', 'ms237-14 type a'),
 ('hyundai', 'ms237-05 type a-2'),
 ('hyundai', 'ms237-05 type d'),
 ('hyundai', 'ms237-05 type a-1'),
 ('hyundai', 'ms220-24 type e'),
 ('hyundai', 'ms220-24 type e'),
 ('hyundai', 'ms220-24 type d'),
 ('hyundai', 'ms220-24 type b'),
 ('hyundai', 'ms220-24 type c'),
 ('hyundai', 'ms220-24 type g'),
 ('hyundai', 'ms220-08 type a'),
 ('hyundai', 'ms220-24 type a'),
 ('hyundai', 'ms220-08 type d'),
 ('hyundai', 'ms237-09 type e-1'),
 ('hyundai', 'ms237-05 type b'),
 ('hyundai', 'ms237-05 type e-1'),
 ('hyundai', 'ms941-03 type m-1'),
 ('hyundai', 'ms237-12 type a'),
 ('hyundai', 'ms237-05 type c'),
 ('hyundai', 'ms216-05 type b'),
 ('hyundai', 'ms220-05 type a'),
 ('hyundai', 'ms220-05 type b'),
 ('hyundai', 'ms220-31 type a1'),
 ('hyundai', 'ms220-05 type c'),
 ('hyundai', 'ms220-31 type a2'),
 ('hyundai', 'ms220-05 type d'),
 ('hyundai', 'ms220-05 type e'),
 ('hyundai', 'ms220-05 type g'),
 ('hyundai', 'ms220-05 type h'),
 ('hyundai', 'ms220-05 type k'),
 ('hyundai', 'ms220-05 type j'),
 ('hyundai', 'ms220-13 type d-1'),
 ('hyundai', 'ms220-05 type p'),
 ('hyundai', 'ms220-05 c'),
 ('hyundai', 'ms220-05 p'),
 ('hyundai', 'ms220-05 type l'),
 ('hyundai', 'ms220-05 type m'),
 ('hyundai', 'ms220-13 type c-1'),
 ('hyundai', 'ms220-05 type n'),
 ('hyundai', 'ms220-13 type f-1'),
 ('hyundai', 'ms220-05 type r'),
 ('hyundai', 'ms220-13 type e-1'),
 ('hyundai', 'ms941-03 type j-2'),
 ('hyundai', 'ms941-03 type p-2 frvo'),
 ('hyundai', 'ms211-37 type d'),
 ('hyundai', 'ms211-46 type e'),
 ('hyundai', 'ms211-46 type b'),
 ('hyundai', 'ms211-66 type b'),
 ('hyundai', 'ms941-03 type a-2'),
 ('hyundai', 'ms941-03 type a-5'),
 ('hyundai', 'ms941-03 type a-6'),
 ('hyundai', 'ms211-47 type a-2-3'),
 ('hyundai', 'ms941-03 type a-7'),
 ('hyundai', 'ms211-37 type e'),
 ('hyundai', 'ms211-36 type a-1'),
 ('hyundai', 'ms211-66 type c'),
 ('hyundai', 'ms211-47 type a-3'),
 ('hyundai', 'ms211-44 type c'),
 ('hyundai', 'ms941-03 type d-2'),
 ('hyundai', 'ms941-03 type d-3'),
 ('hyundai', 'ms211-56 type'),
 ('hyundai', 'ms941-03 type a-3 hi'),
 ('hyundai', 'ms211-72 type a'),
 ('hyundai', 'ms941-03 type a-5 frv0'),
 ('hyundai', 'ms941-12 type b'),
 ('hyundai', 'ms941-03 type n-4'),
 ('hyundai', 'ms211-19 type b-1'),
 ('hyundai', 'ms211-80 type b'),
 ('hyundai', 'ms211-35 type c'),
 ('hyundai', 'ms211-46 type c-2'),
 ('hyundai', 'ms211-72 type b'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('iveco', 'iveco 5244'),
 ('iveco', 'iveco 15-5244'),
 ('li auto', 'q/lia5310038'),
 ('li auto', 'q/lia5310020'),
 ('li auto', 'q/lia5310050'),
 ('li auto', 'q/lia5310057'),
 ('li auto', 'q/lia5310038'),
 ('li auto', 'q/lia5310020'),
 ('li auto', 'q/lia5310050'),
 ('li auto', 'q/lia5310057'),
 ('li auto', 'q/lia5310038'),
 ('li auto', 'q/lia5310020'),
 ('li auto', 'q/lia5310050'),
 ('li auto', 'q/lia5310057'),
 ('man', 'm3236 a7'),
 ('man', 'm3236 a5'),
 ('man', 'm3236 a6'),
 ('man', 'm3236'),
 ('man', 'm3236 a7'),
 ('mercedes-benz', 'dbl5410'),
 ('mercedes-benz', 'dbl5408'),
 ('mercedes-benz', 'dbl5409'),
 ('mercedes-benz', 'dbl5405-06-pom-c'),
 ('mercedes-benz', 'dbl 5416'),
 ('mercedes-benz', 'dbl5404'),
 ('mercedes-benz', 'dbl5418'),
 ('mercedes-benz', 'dbl5416'),

In [183]:
all_oems = []
for i in auto_certifications:
    if i[0] not in all_oems:
        all_oems.append(i[0])

all_oems

['baic',
 'bmw',
 'byd',
 'bosch',
 'catl',
 'changan',
 'chery',
 'continental',
 'dongfeng motor',
 'evergrande auto',
 'faw group',
 'ford',
 'geely',
 'general motors (gm)',
 'great wall motor',
 'honda',
 'hyundai',
 'iveco',
 'li auto',
 'man',
 'mercedes-benz',
 'nio',
 'nissan',
 'saic motor',
 'stellantis-chrysler',
 'stellantis-fca group',
 'stellantis-psa group',
 'tesla',
 'vw group',
 'zf group']

In [184]:
ignore_common_values =  processing_types + product_functions + delivery_forms + all_brands + all_polymers
temp = list(processing_syns.values()) + list(feature_syns.values()) + list(delivery_form_syns.values()) + list(polymer_syns.values()) + list(brand_syns.values())
for i in temp:
    ignore_common_values.extend(i)

ignore_common_values

['injection molding',
 'other extrusion',
 'film extrusion',
 'profile extrusion',
 'sheet extrusion',
 'multi injection molding',
 'coextrusion',
 'compression molding',
 'blow molding',
 'calendering',
 'selective reinforcement',
 'thermoforming',
 'transfer molding',
 'coatable',
 'casting',
 'porous sintering',
 'gel extrusion',
 'fiber spinning / gel spinning',
 'ram extrusion',
 'extrusion blow molding',
 'rotational molding',
 'foam processing',
 'extrusion - wire and cable',
 'extrusion - small tubing',
 'injection blow molding',
 'extrusion - hose',
 'blowmolding',
 'bm',
 'blow moulding',
 'blow moldable',
 'blow molded',
 'calandering',
 'calendered',
 'calendr',
 'calenderable',
 'castable',
 'coating',
 'polymeric coating',
 'spin coating',
 'compression moulding',
 'matched-die moulding',
 'matched-die molding',
 'matched die molding',
 'matched die moulding',
 'cold compression',
 'hot compression',
 'compmold',
 'compression moldable',
 'compression mouldable',
 'hose extrusion',
 'extrusion - ram',
 'cable extrusion',
 'wire extrusion',
 'extrusion wire coating',
 'extrusion cable coating',
 'wire coating',
 'cable coating',
 'extrusion blow moulding',
 'extrusion blow moldable',
 'extrusion blow mouldable',
 'extrusion - blow molding',
 'fibre spinning / gel spinning',
 'fibre spinning / gel extrusion',
 'fiber spinning / gel extrusion',
 'fiber spinning',
 'fibre spinning',
 'semi melt spinning',
 'gel-electrospinning',
 'gel electrospinning',
 'gel spinning',
 'extrusion - gel',
 'cast film extrusion',
 'extrusion - film',
 'foam extrusion',
 'foamable',
 'bead foam extrusion',
 'physical foaming',
 'foaming',
 'mucell',
 'injection blow moulding',
 'injection blow moldable',
 'ibm',
 'injection moldable',
 'injection moulding',
 'injmold',
 'injmould',
 'injection',
 'injection mouldable',
 'melt blowing / nonwovens',
 'melt blown',
 'multi injection moulding',
 'multi-material injection molding',
 'multi material injection molding',
 'multi-material injection moulding',
 'multi material injection moulding',
 'mmm',
 'multi injection moldable',
 'multi injection mouldable',
 '2k injection molding',
 '2k injection moulding',
 'double shot molding',
 'double shot moulding',
 'otherex',
 'extrusion - other',
 'power coating / sintering',
 'poweder coating',
 'sintering',
 'profex',
 'profilextrusion',
 'extrusion - profile',
 'rotomolding',
 'rotomoulding',
 'rotomoldable',
 'rotomouldable',
 'rm',
 'rotational moulding',
 'rotational moldable',
 'rotational mouldable',
 'sheet',
 'sheetex',
 'extrusion - sheet',
 'thermo forming',
 'thermo',
 'transfer moulding',
 'xfermol',
 'transfer moldable',
 'transfer mouldable',
 'high viscosity',
 'lubricants',
 'release agent',
 'high flow',
 'hydrolysis resistant',
 'low wear / low friction',
 'high impact or impact modified',
 'flame retardant',
 'u.v. stabilized or stable to weather',
 'heat stabilized or stable to heat',
 'high gloss',
 'recycled content',
 'sustainable',
 'medical/healthcare',
 'bio-content',
 'nucleated',
 'laser markable',
 'specialty appearance',
 'low warpage',
 'non-halogenated/red phosphorous free flame retardant',
 'static dissipative',
 'anti-static',
 'increased electrical conductivity',
 'chemical resistant',
 'low halide content',
 'increased thermal conductivity',
 'light stabilized or stable to light',
 'improved creep',
 'reduced gloss',
 'carbon capture',
 'low emissions',
 'light weight',
 'lead-free soldering resistant',
 'laser weldable',
 'thermal shock resistant',
 'platable',
 'hydrophilic',
 'improved weld line',
 'ultrasonic weldable',
 'laser direct structurable',
 'plasticizer',
 'static resistant',
 'static',
 'static resistance',
 'antistatic',
 'avoid static',
 'avoid static build',
 'avoid static build up',
 'bio-based',
 'bio',
 'biobased',
 'reduce carbon capture',
 'reduced carbon footprint',
 'eco-c',
 'carbon footprint',
 'iso 14067',
 'carbon capture and utilization',
 'ccu',
 'acid resistant',
 'acid resistance',
 'chem resistance',
 'chem resistant',
 'anti chemical',
 'anti acid',
 'anti-chemical',
 'anti-acid',
 'chemical resistance',
 'flameretardent',
 'fr',
 'flame retarding agent',
 'flamret',
 'flamretag',
 'flame resistant',
 'flame resistance',
 'halogenated fr',
 'halogenated',
 'halogenated flame retardant',
 'stable to heat',
 'heat resistance',
 'heat tolerant',
 'high heat performance',
 'high heat',
 'heat stabilized',
 'heat stabilised',
 'heat',
 'heat stable',
 'high heat conditions',
 'resistant to heat',
 'thermal resistance',
 'thermal resistant',
 'anti heat',
 'anti-heat',
 'heat resistant',
 'high mv',
 'high flowability',
 'low viscosity',
 'easy flow',
 'thin wall',
 'low wall',
 'enhanced gloss',
 'highgloss',
 'impact modified',
 'toughened',
 'impact resistance',
 'impact resistant',
 'anti impact',
 'anti-impact',
 'impact grade',
 'impact modification',
 'improved toughness',
 'tough',
 'im',
 'low mv',
 'low flow',
 'highvisc',
 'hr',
 'hydrolysis',
 'water resistant',
 'anti hydrolysis',
 'hydrolysis resistance',
 'water resistance',
 'anti-hydrolysis',
 'anti-water',
 'hydrostable',
 'not hygroscopic',
 'hydrophile',
 'absorbent',
 'water affinity',
 'hydrophilicity',
 'creep resistance',
 'creep resistant',
 'anti creep',
 'anti-creep',
 'weld line improved',
 'weld line strength',
 'electro conductive',
 'electrical conductivity',
 'heat dissipation',
 'lds',
 'laser direct structuring',
 'laser direct structuring (lds)',
 'lm',
 'lasermarkable',
 'laser marking',
 'lasermark',
 'laser transparent',
 'lasertr',
 'lasertransparent',
 'laser weld',
 'laser transmission',
 'lt',
 'surface mount solderable',
 'smd solderable',
 'lead-free reflow solderable',
 'lead-free solderability',
 'lead-free soldering resistance',
 'pb free solder reflow',
 'anti lead free soldering',
 'light stabilised or stable to light',
 'light stabilised',
 'light stabilized',
 'stable to light',
 'light weighting',
 'replacement for aluminum',
 'metal replacement',
 'low emission',
 'reduced emission',
 'low-e',
 'lowemiss',
 'emissions',
 'low formaldehyde',
 'low voc',
 'low warp',
 'warp resistant',
 'lowwarp',
 'high flatness',
 'warp resistance',
 'anti warp',
 'anti-warp',
 'low wear',
 'low friction',
 'tribo',
 'tribological',
 'low wear and friction',
 'tribological modified',
 'tribology',
 'good sliding',
 'lw',
 'abrasion resistance',
 'abrasion resistant',
 'silicone modified',
 'ptfe modified',
 'silicon oil concentrate',
 'silicone',
 'silicone concentrate',
 'tf',
 'friction',
 'lubricated',
 'lubric',
 'medical',
 'medical grade',
 'medgrade',
 'medhc',
 'medical grades',
 'healthcare',
 'medical grade technology',
 'mt',
 'med',
 'halogen free',
 'haogen free',
 'nhfr',
 'hffr',
 'halogen free flame retardant',
 'non-halogenated',
 'non-halogenated fr',
 'high crystallinity',
 'highly crystalline',
 'highest cristalline',
 'plasticiser',
 'plasti',
 'plateable',
 'plating grade',
 'contains recycle',
 'recycle',
 'recycled',
 'post consumer recycle',
 'post-consumer recycle',
 'pcr',
 'pir',
 'post industrial recycle',
 'post-industrial recycle',
 'low gloss',
 'redugloss',
 'release',
 'lx',
 'appearance',
 'aesthetical',
 'good aesthetics',
 'visual fx',
 'esd',
 'esd modified',
 'elecdiss',
 'elec diss',
 'electdiss',
 'elect diss',
 'electrostatic dissipation',
 'electrostatic dissipative',
 'green',
 'circular economy',
 'environmentally friendly',
 'sustainability',
 'eco',
 'thermal shock resistance',
 'thermal shock',
 'shock resistance',
 'shock resistant',
 'anti thermal shock',
 'anti-thermal shock',
 'u.v. stabilized',
 'u.v. stabilised',
 'u.v. stabilised or stable to weather',
 'uv resistant',
 'uv',
 'anti uv',
 'anti-uv',
 'uv-stabilized',
 'exposure to outdoor sunlight',
 'uv resistent',
 'uvres',
 'uv stabilise',
 'uv stability',
 'weather resistance',
 'weather resistant',
 'uv resistance',
 'weatherable',
 'stable to weather',
 'weather',
 'solar resistance',
 'pellets',
 'granules',
 'tape',
 'powder',
 'micropowder',
 'micro powder',
 'micro-powder',
 'pelets',
 'pellet',
 'cfr',
 'tp',
 'ecomid',
 'pip',
 'mcm',
 'ge',
 'tc',
 'ol',
 'tx',
 'lft',
 'celstran lft',
 'zenite',
 'thermx',
 'ze',
 'fri',
 'sp',
 've',
 'hyt',
 'cnl',
 'fortron',
 'santoprene',
 'fo',
 'opp',
 'mid',
 'pf',
 'lp',
 'oc',
 'cl',
 'fa',
 'frianyl',
 'zyt',
 'celstran',
 'celanex',
 'cs',
 'hostaform',
 'celcon',
 'po',
 'ff',
 'ot',
 'kepital',
 'pultrusion',
 'hf',
 'va',
 'cp',
 'cn',
 'coolpoly',
 'rynite',
 'cra',
 'vectra',
 'crastin',
 'bf',
 'hytrel',
 'lfrt',
 'vamc',
 'celanyl',
 'blue ridge',
 'kep',
 'neo',
 'lftr',
 'pb',
 'fp',
 'zytel',
 'br',
 'am',
 'gur',
 'cs lft',
 'stp',
 'ta',
 'ryn',
 'cx',
 'forflex',
 'kepamid',
 'abistir',
 'impet',
 'blueridge',
 'blendfor',
 'omnilon',
 'nylfor',
 'ateva',
 'selar',
 'factor',
 'tecnoprene',
 'neolast',
 'omnicarb',
 'sofpur',
 'micromax',
 'tarnoform',
 'nilamid',
 'celapex',
 'omnitech',
 'pibifor',
 'vamac',
 'kepex',
 'pipelon',
 'vitaldose',
 'forprene',
 'cecopoly',
 'clarifoil',
 'compel',
 'talcoprene',
 'litepol',
 'sikamid',
 'laprene',
 'elvamide',
 'keploy',
 'vandar',
 'stirofor',
 'amcel',
 'polifor',
 'omnipro',
 'sofprene',
 'maximid',
 'minlon',
 'pibiter',
 'pbt',
 'pet',
 'pa66',
 'pa6',
 'pa*',
 'pom',
 'pa666',
 'pe-hd',
 'pp',
 'pps',
 'tpu',
 'pc',
 'abs',
 'lcp',
 'pe-uhmw',
 'pe-hmw',
 'tpc',
 'tpv',
 'pct',
 'pa612',
 'pa6t/xt',
 'pa6t/66',
 'pa66/6t',
 'pa610',
 'evac',
 'pvdf',
 'smah',
 'pa6t/6i',
 'ps',
 'pa12',
 'paste',
 'copolyester',
 'ptt',
 'pe-ld',
 'pa1010',
 'sebs',
 'peek',
 'pamxd6',
 'asa',
 'sbs',
 'tpo',
 'aem',
 'acrylonitrile-butadiene-styrene',
 'ethylene methylacrylate',
 'ethylene-vinyl-acetate',
 'eva',
 'liquid crystal polymer',
 'liquid - crystalline polymer',
 'lcpa',
 'long chain nylon',
 'long chain pa',
 'polyamide',
 'pa',
 'nylon',
 'polyamide 1010',
 'nylon 1010',
 'pa 1010',
 'polyamide 10/10',
 'nylon 10/10',
 'pa10/10',
 'pa 10/10',
 'polyamide 10,10',
 'nylon 10,10',
 'pa 10,10',
 'pa10,10',
 'polyamide 10-10',
 'nylon 10-10',
 'pa 10-10',
 'pa10-10',
 'polyamide 12',
 'nylon 12',
 'pa 12',
 'nylon 6',
 'pa 6',
 'polyamide 6',
 'polyamide 610',
 'nylon 610',
 'pa 610',
 'nylon 6-10',
 'polyamide 6-10',
 'pa 6-10',
 'pa6-10',
 'nylon 6/10',
 'polyamide 6/10',
 'pa 6/10',
 'pa6/10',
 'nylon 6,10',
 'polyamide 6,10',
 'pa 6,10',
 'pa6,10',
 'polyamide 612',
 'nylon 612',
 'pa 612',
 'nylon 6-12',
 'polyamide 6-12',
 'pa 6-12',
 'pa6-12',
 'nylon 6/12',
 'polyamide 6/12',
 'pa 6/12',
 'pa6/12',
 'nylon 6,12',
 'polyamide 6,12',
 'pa 6,12',
 'pa6,12',
 'polyamide 66',
 'nylon 66',
 'pa 66',
 'nylon 6-6',
 'polyamide 6-6',
 'pa 6-6',
 'pa6-6',
 'nylon 6/6',
 'polyamide 6/6',
 'pa 6/6',
 'pa6/6',
 'nylon 6,6',
 'polyamide 6,6',
 'pa 6,6',
 'pa6,6',
 'pa66,6t',
 'pa66-6t',
 'pa 66,6t',
 'pa 66/6t',
 'pa 66-6t',
 'nylon 66,6t',
 'nylon 66/6t',
 'nylon 66-6t',
 'polyamide 666',
 'nylon 666',
 'pa 666',
 'nylon 66-6',
 'polyamide 66-6',
 'pa 66-6',
 'pa66-6',
 'nylon 66/6',
 'polyamide 66/6',
 'pa 66/6',
 'pa66/6',
 'nylon 66,6',
 'polyamide 66,6',
 'pa 66,6',
 'pa66,6',
 'pa6t',
 'pa6t,66',
 'pa6t-66',
 'pa 6t,66',
 'pa 6t/66',
 'pa 6t-66',
 'nylon 6t,66',
 'nylon 6t/66',
 'nylon 6t-66',
 '6t6i',
 'pa6t,6i',
 'pa6t-6i',
 'pa 6t,6i',
 'pa 6t/6i',
 'pa 6t-6i',
 'nylon 6t,6i',
 'nylon 6t/6i',
 'nylon 6t-6i',
 '6txt',
 'pa6t,xt',
 'pa6t-xt',
 'pa 6t,xt',
 'pa 6t/xt',
 'pa 6t-xt',
 'nylon 6t,xt',
 'nylon 6t/xt',
 'nylon 6t-xt',
 'poly-m-xylylenadipamid',
 'polybutylene terephthalate',
 'polycarbonate',
 'polycyclohexylenedimethylene terephthalate',
 'hdpe',
 'high density polyethylene',
 'pehd',
 'hd-pe',
 'hmwpe',
 'high molecular weight polyethylene',
 'hmw-pe',
 'peld',
 'ldpe',
 'low density polyethylene',
 'ld-pe',
 'uhmwpe',
 'ultra high molecular weight polyethylene',
 'uhmw-pe',
 'uhmw',
 'umpe',
 'polyetheretherketone',
 'polyether ether ketone',
 'polyether',
 'polyethylene terephthalate',
 'polyoxymethylene (acetal)',
 'polyoxymethylene',
 'acetal copolymer',
 'polyformaldehyde',
 'copolymer',
 'acetal',
 'polyacetal',
 'polypropylene',
 'ppa',
 'polyphthalamide',
 'semi aromatic polyamide',
 'semi aromatic pa',
 'polyphenylene sulfide',
 'polyphenylene sulphide',
 'polystyrene',
 'ptfe',
 'polytetrafluoroethylene',
 'teflon',
 'polytrimethylene terephthalate',
 'poly(vinylidene fluoride)',
 'styrene-butadiene-styrene',
 'styrene-ethylene-butadiene-styrene',
 'styrene-maleic anhydride',
 'copolyester thermoplastic elastomer',
 'thermoplastic copolyester',
 'copolyester elastomer',
 'tpc-et',
 'cope',
 'tpe',
 'thermoplastic elastomer',
 'olefinic thermoplastic elastomer',
 'thermoplastic polyurethane',
 'thermoplastic vulcanizate',
 'thermoplastic vulcanizates',
 'thermoplastic rubber vulcanisate',
 'ethylene propylene thermoplastic rubber',
 'eptr',
 'pp-epdm',
 'ppepdm',
 'pp epdm',
 'blow molding',
 'blowmolding',
 'bm',
 'blow moulding',
 'blow moldable',
 'blow molded',
 'calendering',
 'calandering',
 'calendered',
 'calendr',
 'calenderable',
 'casting',
 'castable',
 'coatable',
 'coating',
 'polymeric coating',
 'spin coating',
 'coextrusion',
 'compression molding',
 'compression moulding',
 'matched-die moulding',
 'matched-die molding',
 'matched die molding',
 'matched die moulding',
 'cold compression',
 'hot compression',
 'compmold',
 'compression moldable',
 'compression mouldable',
 'extrusion - hose',
 'hose extrusion',
 'extrusion - ram',
 'ram extrusion',
 'extrusion - small tubing',
 'extrusion - wire and cable',
 'cable extrusion',
 'wire extrusion',
 'extrusion wire coating',
 'extrusion cable coating',
 'wire coating',
 'cable coating',
 'extrusion blow molding',
 'extrusion blow moulding',
 'extrusion blow moldable',
 'extrusion blow mouldable',
 'extrusion - blow molding',
 'fiber spinning / gel spinning',
 'fibre spinning / gel spinning',
 'fibre spinning / gel extrusion',
 'fiber spinning / gel extrusion',
 'fiber spinning',
 'fibre spinning',
 'semi melt spinning',
 'gel-electrospinning',
 'gel electrospinning',
 'gel spinning',
 'extrusion - gel',
 'gel extrusion',
 'film extrusion',
 'cast film extrusion',
 'extrusion - film',
 'foam processing',
 'foam extrusion',
 'foamable',
 'bead foam extrusion',
 'physical foaming',
 'foaming',
 'mucell',
 'injection blow molding',
 'injection blow moulding',
 'injection blow moldable',
 'ibm',
 'injection molding',
 'injection moldable',
 'injection moulding',
 'injmold',
 'injmould',
 'injection',
 'injection mouldable',
 'melt blowing / nonwovens',
 'melt blown',
 'multi injection molding',
 'multi injection moulding',
 'multi-material injection molding',
 'multi material injection molding',
 'multi-material injection moulding',
 'multi material injection moulding',
 'mmm',
 'multi injection moldable',
 'multi injection mouldable',
 '2k injection molding',
 '2k injection moulding',
 'double shot molding',
 'double shot moulding',
 'other extrusion',
 'otherex',
 'extrusion - other',
 'power coating / sintering',
 'poweder coating',
 'porous sintering',
 'sintering',
 'profile extrusion',
 'profex',
 'profilextrusion',
 'extrusion - profile',
 'rotational molding',
 'rotomolding',
 'rotomoulding',
 'rotomoldable',
 'rotomouldable',
 'rm',
 'rotational moulding',
 'rotational moldable',
 'rotational mouldable',
 'selective reinforcement',
 'sheet extrusion',
 'sheet',
 'sheetex',
 'extrusion - sheet',
 'thermoforming',
 'thermo forming',
 'thermo',
 'transfer molding',
 'transfer moulding',
 'xfermol',
 'transfer moldable',
 'transfer mouldable',
 'anti-static',
 'static resistant',
 'static',
 'static resistance',
 'antistatic',
 'avoid static',
 'avoid static build',
 'avoid static build up',
 'bio-content',
 'bio-based',
 'bio',
 'biobased',
 'carbon capture',
 'reduce carbon capture',
 'reduced carbon footprint',
 'eco-c',
 'carbon footprint',
 'iso 14067',
 'carbon capture and utilization',
 'ccu',
 'reduce carbon capture',
 'reduced carbon footprint',
 'chemical resistant',
 'acid resistant',
 'acid resistance',
 'chem resistance',
 'chem resistant',
 'anti chemical',
 'anti acid',
 'anti-chemical',
 'anti-acid',
 'chemical resistance',
 'flame retardant',
 'flameretardent',
 'fr',
 'flame retarding agent',
 'flamret',
 'flamretag',
 'flame resistant',
 'flame resistance',
 'halogenated fr',
 'halogenated',
 'halogenated flame retardant',
 'heat stabilized or stable to heat',
 'stable to heat',
 'heat resistance',
 'heat tolerant',
 'high heat performance',
 'high heat',
 'heat stabilized',
 'heat stabilised',
 'heat',
 'heat stable',
 'high heat conditions',
 'resistant to heat',
 'thermal resistance',
 'thermal resistant',
 'anti heat',
 'anti-heat',
 'heat resistant',
 'high flow',
 'high mv',
 'high flowability',
 'low viscosity',
 'easy flow',
 'thin wall',
 'low wall',
 'high gloss',
 'enhanced gloss',
 'highgloss',
 'impact modified',
 'high impact or impact modified',
 'toughened',
 'impact resistance',
 'impact resistant',
 'anti impact',
 'anti-impact',
 'impact grade',
 'impact modification',
 'improved toughness',
 'tough',
 'im',
 'high viscosity',
 'low mv',
 'low flow',
 'highvisc',
 'hr',
 'hydrolysis resistant',
 'hydrolysis',
 'water resistant',
 'anti hydrolysis',
 'hydrolysis resistance',
 'water resistance',
 'anti-hydrolysis',
 'anti-water',
 'hydrostable',
 'not hygroscopic',
 'hydrophilic',
 'hydrophile',
 'absorbent',
 'water affinity',
 'hydrophilicity',
 'improved creep',
 'creep resistance',
 'creep resistant',
 'anti creep',
 'anti-creep',
 'improved weld line',
 'weld line improved',
 'weld line strength',
 'increased electrical conductivity',
 ...]

In [185]:
auto_syns_mapping

{'mercedes-benz': 'mercedes-benz',
 'daimler': 'mercedes-benz',
 'daimler-benz': 'mercedes-benz',
 'daimler mercedes': 'mercedes-benz',
 'daimler mercedes-benz': 'mercedes-benz',
 'daimler mercedes-benz group': 'mercedes-benz',
 'mercedes': 'mercedes-benz',
 'mercedes-benz group (daimier)': 'mercedes-benz',
 'vw group': 'vw group',
 'vw': 'vw group',
 'bentley': 'vw group'}

In [186]:
# needs to be added to the synonym table
auto_syns_mapping['mercedes'] = 'mercedes-benz'

## Applications

In [187]:
app_industry_df = app_industry_df[['Medical & Pharma', 'Consumer Goods', 'Automotive & Transportation',
       'Electrical & Electronics', 'Industrial', 'Not Mapped',]]
app_industry_df

,Medical & Pharma,Consumer Goods,Automotive & Transportation,Electrical & Electronics,Industrial,Not Mapped
0,connection ring for natural glove,box for specimen collection,anti-slip mat for door storage box,bobbin housing for dishwasher,rod for knee replacement sizer,aerosol valve for over the counter (otc) valve...
1,autoinjector-anaphylaxis,"sprayers-throat tubes, nebulization inserts, j...",backlit knob-actuator,bracket for smartphone,filter bottle-shaft parts,antenna for wireless temperature probe
2,autoinjector-retraction assembly,tube for disinfection cabinet,carrier for back rest,projector-lock,hose for technical gardening,gear housing for pain management drug delivery...
3,clamp for feeding catheter,guide for paper transport,clip for recliner,lithium ion battery separator (libs) for power...,refrigerator-spring finger,tablet dispenser
4,dispension monitoring for diabetes pharmaceuti...,remote control for rudder,duct for air conditioner (ac),protection channel for wiring harness,wire control kit for firearm furniture,vending machine for hospital linen
...,...,...,...,...,...,...
213,NaN,NaN,trunk components,NaN,NaN,NaN
214,NaN,NaN,tube for air suspension,NaN,NaN,NaN
215,NaN,NaN,turn signal-shaft base,NaN,NaN,NaN
216,NaN,NaN,web sense retractor for seat belt,NaN,NaN,NaN
217,NaN,NaN,wiper arm,NaN,NaN,NaN

In [188]:
app_industry_df = app_industry_df.fillna('')
app_industry_data = app_industry_df.to_dict('list')
app_industry_data

{'Medical & Pharma': ['connection ring for natural glove',
  'autoinjector-anaphylaxis',
  'autoinjector-retraction assembly',
  'clamp for feeding catheter',
  'dispension monitoring for diabetes pharmaceutical preparation',
  'dose button for insulin pen',
  'drug delivery systems',
  'handle for flexible endoscopy',
  'hospital diagnostics & imaging',
  'metered dose inhaler (mdi)-dose counter',
  'plunger for intra ocular lens (iol)',
  'power transmission for metered dose inhaler (mdi)',
  'rod for orthopedic sizing device',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'Consumer Goods': ['box for specimen collection',
  'sprayers-throat tubes, nebulization inserts, joints',
  'tube for disinfection cabinet',
  'guide for paper transport',
  'remote control for rudder',
  'tire and rim association (tra) compliant wheel rim for all terrain vehicle (atv)',
  'wheel rim for gravel bike',
  'accumulator for water pump',
  'actuator for aerosol valve',
  'cassette stove-valve',
  'clip for nail gun',
  'clip for vine',
  'end cap cover for gear',
  'faucet-valve',
  'pumping unit for dispenser',
  'support for conveyor belt',
  '"aqua pro" gear program',
  'blade holder for ice hockey shoes',
  'valve for cosmetic',
  'wire guides, clamps, clips, collars, buttons, guides',
  'pinch clamp for lab use',
  'back for chair',
  'back frame for office chair',
  'back lower portion for office chair',
  'bearing for furniture',
  'brewing system-dispenser button',
  'buckle and shoes',
  'button for appliance',
  "children's carriage-gear",
  'consumer filtration',
  'cover for dishwasher impeller',
  'cylinder for lock',
  'damper for sunglass compartment',
  'dishwasher-rack clips',
  'dishwasher-roller',
  'driving bridge for beard and hair trimmer',
  'filling valve for toilet flushing mechanism',
  'fishing reel',
  'flip tines for dishwasher',
  'front plate for grease free coffee brewing unit',
  'furniture-gear',
  'gear box for washing machine transmission',
  'gear for window shade',
  'gear for window shade cable guide',
  'gearbox for washing machine',
  'grip for appliance',
  'guide rail for furniture',
  'holding structure for camera',
  'housing for dishwasher',
  'impeller for oven',
  'inlet valve for dishwasher',
  'insert for razor handle',
  'joint for baby pram',
  'lawn trimmer-cable drum housing and cover',
  'leveling leg for dishwasher leak pan',
  'lid lock for washing machine',
  'lock for home door',
  'lower rack clip for dishwasher',
  'mascara-stick',
  'plug for coffee machine brewing unit',
  'pole for ski',
  'refrigerator-food drawer roller',
  'roller for dishwasher',
  'seatback frame for hybrid chair',
  'shifter base for washing machine',
  'slider for vacuum cleaner',
  'sliding for dishwasher',
  'spray valve for perfume',
  'strike door plate for dishwasher',
  'sun umbrella articulation',
  'support for saddle storage system',
  'television parts',
  'toilet flushing units',
  'toothbrush tube base for oral care',
  'torsion plate for footwear',
  'vacuum cleaner for pool',
  'vacuum cleaner-gear',
  'valve for drink machine',
  'water tank seal for wet dry vacuum cleaner',
  'water valve for refrigerator',
  'wingnut for dishwasher',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'Automotive & Transportation': ['anti-slip mat for door storage box',
  'backlit knob-actuator',
  'carrier for back rest',
  'clip for recliner',
  'duct for air conditioner (ac)',
  'key lock',
  'mirror for door',
  'adjustment for lighting',
  'housing for light control',
  'housing for lighting sensor',
  'plate for backlight',
  'protective cap for electronical & electronics',
  'structural for smart phone station (sps) display',
  'support for electromagnetic compatibility (emc) filter',
  'terminal for battery fuse',
  'washer nozzle for camera',
  'bracket for air duct',
  'clip for stud mount',
  'cold air hose for coupling box cooling',
  'connector for control power transformer (cpt)',
  'connector for water coolant circuit',
  'cover cap for gear drive',
  'fastener for fuel pipe',
  'holder for thermal management module (tmm)',
  'isolator for spring cup',
  'mount for nozzle',
  'o ring spacer for battery cooling line',
  'rotary valve for thermal management module (tmm)',
  'seal for battery access panel',
  'side cover for water channel',
  'structural brackets & beams',
  'adapter for interior',
  'bearing cage for interior',
  'bracket for console',
  'cover for cell super control (csc)',
  'fastener for panel',
  'grommet-top post',
  'lever for air conditioner (ac)',
  'mount for hinge',
  'spring plate',
  'structural support for console',
  'air channel for mass air flow (maf) sensor',
  'air duct adapter for defroster',
  'automobile (gasoline)-fuel module',
  'automotive air register',
  'automotive brake pedal',
  'automotive bushing-bearing cover',
  'automotive cargo area-hook',
  'automotive chassis-bracket',
  'automotive connector-clip',
  'automotive connector-pin',
  'automotive console link-strip retainer',
  'automotive cover-bracket',
  'automotive cup holder-housing',
  'automotive door-lock cover',
  'automotive door-stopper',
  'automotive fr bumper-retainer',
  'automotive fuel delivery module (fdm)',
  'automotive fuel module-ec pump',
  'automotive fuel pump',
  'automotive fuel reservoir and flange',
  'automotive fuel supply system-filter box body',
  'automotive fuel supply system-flange',
  'automotive fuel supply system-holder',
  'automotive fuel tank-flange',
  'automotive grommet',
  'automotive instrument panel and console system-trim clip',
  'automotive motorcycle-key cover',
  'automotive rear fuel tank-baffle',
  'automotive retainer-fastener',
  'automotive seat-latch housing',
  'automotive sensor-drive cover, adapter',
  'automotive side bumper-fastener and support',
  'automotive spring cassette-housing',
  'automotive spring drive-cover',
  'automotive spring-sleeve',
  'automotive steering column control module (sccm)-button',
  'automotive webbing guide',
  'automotive window lift-cursor',
  'automotive-2w fuel delivery module (fdm)',
  'automotive-4 way headrest',
  'ball valve for engine',
  'base plate for seat cushion length adjustment (scla)',
  'battery module for electric powertrain',
  'bellow for suspension',
  'blade for wiper',
  'bobbin for fuel tank isolation valve (ftiv)',
  'bobbin for pressure control solenoid valve (pcsv)',
  'bobbin for starter',
  'body-clip',
  'boot for propeller shaft',
  'boot for steering/suspension',
  'bracket for battery pack cable routing',
  'bracket for cup holder',
  'bracket for filler pipe',
  'bracket for headlight grille',
  'braking motor system for automobile & transportation',
  'brushless fuel delivery module (fdm) for gasoline engine',
  'bumper for hood',
  'camshaft positioning sensor (cmps) for turbo engine',
  'cap for sunroof',
  'capless fuel supply system',
  'carrier plate for seat cushion length adjustment (scla)',
  'channel for glass run',
  'charging panel for electric vehicle (ev)',
  'clip for door lift',
  'collar spring for clutch',
  'connector for automotive video navigation (avn)',
  'connector for electric mobility (e-mobility)',
  'connector for engine cooling system',
  'connector for ignition',
  'constant velocity joint (cvj) rear boot for motorcycle',
  'control handle for exterior mirror',
  'cooling module for dual clutch transmission (dct)',
  'core lever for transmission',
  'counter bearing cap for sun visor',
  'cover for engine valve',
  'cover for sunroof',
  'cover seal for engine',
  'cup holder for interior',
  'defroster for electric vehicle (ev)',
  'diaphragm for drive shaft',
  'distance adjustment for head rest',
  'distribution plate for fuel cell stack',
  'drop gate for tailgate latch',
  'duct for air intake',
  'electrical header for steering',
  'emergency charger cable for electric vehicle (ev)',
  'end cap for battery module',
  'end cap for outer beltline seal (obls)',
  'fender bracket (rh/lh)',
  'filter for diesel exhaust fluid (def)',
  'fixation for battery pack cable',
  'flange holder for fuel pump',
  'floor mat retainer system',
  'fuse assembly protection box for under the hood (uth)',
  'gas generator for seat belt',
  'gasket for door mirror',
  'gear for seat adjuster',
  'grommet clip for door panel',
  'guide bushing for headrest',
  'guide for headlamp',
  'guide plate for seat length adjuster',
  'handphone holder for motorcycle',
  'height position sensor for vehicle',
  'high voltage (hv) connector for electric vehicle (ev) powertrain',
  'hinge for fuel lid',
  'hinge for panel truck',
  'holder for safety belt',
  'housing for airbag',
  'housing for battery pyro switch',
  'housing for brake bushing',
  'housing for convertible roof',
  'housing for intercooler tank',
  'housing for safety belt system',
  'inlet control valve (icv) for fuel supply system',
  'insulated cover of electric vehicle (ev) charger',
  'latch for society of automotive engineers (sae) connector',
  'lens barrel for automotive compact camera module (ccm)',
  'linear actuator for two wheeler',
  'liner for floor',
  'lithium ion battery separator (libs) for plug-in hybrid electric vehicle (phev)',
  'lithium-ion battery separator (libs) for electric vehicle (ev)',
  'locknut for railway',
  'louver for truck',
  'middle gear for throttle body',
  'mini driver for power seat',
  'mirror for rearview',
  'motor housings & covers (traction motors)',
  'motor stator for electric cooling pump',
  'oil pan for hybrid transmission',
  'outer belt line seal (obls) for door',
  'outlet for intercooler',
  'pad for instrument panel (ip)',
  'partial hybrid electric vehicle (phev)',
  'pedals & gear shift systems',
  'pedestrian protection bracket',
  'pedestrian protection bracket for bumper',
  'powertrain-service cover',
  'protective cap for electric mobility',
  'pushrod retainer for plug-in hybrid electric vehicle (phev)',
  'quick connector (battery thermal management)',
  'rebound bumper for suspension',
  'resonator for engine',
  'sail for roof load carrying',
  'seal for bumper',
  'seal for seat recliner',
  'seat belt guide & pillar loop',
  'seat belt retractor',
  'seat belt-web guide',
  'selector shift actuator (ssa) for double clutch transmission (dct)',
  'sensor housing for fuel pump rotor',
  'shell for headrest',
  'side cover for dual clutch transmission (dct)',
  'skin for instrument panel (ip)',
  'skirt fairing for trunk body',
  'sleeve for accelerator pedal',
  'slider for headrest',
  'speed sensor for turbocharged truck',
  'spring element for seat cushion length adjustment (scla)',
  'spring side bearing for automotive',
  'steering column-eccentric disc',
  'strut for trunk door',
  'substrate for armrest',
  'support for seat motor',
  'support yoke for rack and pinion (r&p)',
  'temperature sensor for electric vehicle (ev) battery',
  'thumb wheel for air conditioner (ac)',
  'traction inverter for electric truck',
  'travel restrictor for chassis',
  'travel stop for belt tensioner',
  'trim for overhead console (ohc)',
  'trim for seat rail',
  'trunk components',
  'tube for air suspension',
  'turn signal-shaft base',
  'web sense retractor for seat belt',
  'wiper arm'],
 'Electrical & Electronics': ['bobbin housing for dishwasher',
  'bracket for smartphone',
  'projector-lock',
  'lithium ion battery separator (libs) for power battery',
  'protection channel for wiring harness',
  'actuator for circuit breaker',
  'connector for fan',
  'holder for motor generator coil',
  'housing for exhaust gas',
  'motor generator coil-holder',
  'spindle nut for chair drive',
  'spool for cable',
  'spool for fiber cable',
  'switch for rotary selector',
  'water pumping unit for electrical unit',
  'cover for cooling fan',
  'cable bracing for connector',
  'isolation disk for connector',
  'seal for micro valve',
  'structural for headwear reader',
  'thermal gap filler for connector',
  'antenna baseplate for 5g base station',
  'antenna baseplate for 5g infrastructure',
  'antenna for 5g',
  'box for capacitor',
  'clip for electronic button',
  'coil bobbin for scanner',
  'connector for electrical cable',
  'connector for game machine',
  'connector for surveillance camera',
  'contact holder for high speed data connector',
  'damper for mobile phone camera module',
  'filter for antenna',
  'gear wheel for electrical device',
  'holder for cell phone camera actuator',
  'holder for projector camera',
  'key for computer',
  'lithium ion battery separator (libs) for prismatic battery',
  'manifold for laser printer',
  'quick push connector for fiber to the "x" (fftx)',
  'seal for camera',
  'shield cover for antenna wire',
  'smartphones',
  'speaker for mobile phone',
  'support for switch',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'Industrial': ['rod for knee replacement sizer',
  'filter bottle-shaft parts',
  'hose for technical gardening',
  'refrigerator-spring finger',
  'wire control kit for firearm furniture',
  'rudder for jet',
  'support for railway bridge',
  'butt adaptor for military, weapons, munitions',
  'expansion joint for building & construction',
  'fiber for textiles',
  'head for cable tie',
  'masterbatch fabrication',
  'bolt for conveyor',
  'brush cutter-gear',
  'bulb for blowing air',
  'casing for monolever',
  'check valve clapper for vacuum pump',
  'clip for slider rail',
  'coupling for hose',
  'diaphragm for filter press',
  'downhole pipe for oil & gas',
  'flange for water meter',
  'flexible pipe for oil & gas',
  'gear for flowmeter',
  'glazing for curtain wall',
  'hinge for conveyor belt',
  'housing for irrigation pressure regulator',
  'nurseries (irrigation)-water manifold',
  'porous plate for filtration',
  'poultry slaughter equipment-gear',
  'retainer for pump bushing',
  'scan belt for conveyor',
  'seal for hydraulic pump',
  'sleeve for compressor shaft',
  'sprayer for irrigation',
  'tube protection for oil industry steel pipes',
  'valve for liquid package',
  'washer for acetylene burner',
  'water management (irrigation & drainage)',
  'water swivel',
  'wheel for ramp conveyor belt',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'Not Mapped': ['aerosol valve for over the counter (otc) valve stem',
  'antenna for wireless temperature probe',
  'gear housing for pain management drug delivery device',
  'tablet dispenser',
  'vending machine for hospital linen',
  'base for shower',
  'bracket mount for camera',
  'cartridge for stapler',
  'coin acceptor for vending machine',
  'curtains',
  'dial for skiing boot',
  'faucet for drinking water',
  'frame for coffee brewing chamber',
  'gear for air conditioner (ac)',
  'gear for toy',
  'helmet-clip',
  'housing for appliance',
  'impeller for air conditioner',
  'kinematics for blinds',
  'mat for floor',
  'motor for appliance',
  'motor for vacuum cleaner',
  'protection case for lithium ion battery',
  'robot vacuum cleaner for pool',
  'seat for chair',
  'small appliance',
  'small appliances',
  'smart device',
  'toilet-valve',
  'valve for toilet',
  'adjustment for safety belt',
  'annulus gear for starter motor',
  'bearing for trolling motor',
  'bowl for fuel module',
  'bracket for accelerator pedal',
  'cable tie for non-automotive',
  'carrier for lithium ion battery (lib) module',
  'connector housing for light detection and ranging (lidar)',
  'gear wheel for window regulator',
  'header for electronic control unit (ecu)',
  'high voltage (hv) connector for battery',
  'outlet for air conditioning (ac)',
  'pressurizing duct for turbocharger',
  'wheel for window',
  'window-winding handle',
  'air conditioner-control housing',
  'capacitor holder for printed circuit board (pcb)',
  'carrier for light emitting diode (led) reflector',
  'connector for data transmission',
  'holder for cable',
  'insulator for connector',
  'jacket for fiber',
  'lens base for camera',

In [189]:
app_industry_df2 = app_industry_df2[['Medical & Pharma', 'Consumer Goods', 'Automotive & Transportation',
       'Electrical & Electronics', 'Industrial', 'Not Mapped',]]
app_industry_df2

,Medical & Pharma,Consumer Goods,Automotive & Transportation,Electrical & Electronics,Industrial,Not Mapped
0,hips implant,washing machine pump,active grille,Electrical & Electronics,abrasion sheet,junction box
1,syringe stopper,electric stove,adas,circuit breaker,water meter housing,junction box plastic
2,prosthetic dog ear,cooker handle,ags vanes,5g antenna,conveyor belts,busbar
3,hip implant,refrigerator,aircraft,5g antenna for electrical & electronics,seal for industrial headlights,oil pump plastic
4,orthopedic implant,beer,airspring,power electronics insulation,sliding for farm machine,nylbond
...,...,...,...,...,...,...
410,NaN,NaN,NaN,NaN,NaN,wine adapter
411,NaN,NaN,NaN,NaN,NaN,profiles
412,NaN,NaN,NaN,NaN,NaN,bus bars
413,NaN,NaN,NaN,NaN,NaN,overmolding
414,NaN,NaN,NaN,NaN,NaN,slush molding over carbon filter

In [190]:
app_industry_df2 = app_industry_df2.fillna('')
app_industry_data2 = app_industry_df2.to_dict('list')
app_industry_data2

{'Medical & Pharma': ['hips implant',
  'syringe stopper',
  'prosthetic dog ear',
  'hip implant',
  'orthopedic implant',
  'medical',
  'peristaltic pump gears',
  'peristaltic tub',
  'housing in a medical',
  'medical',
  'cap for laboratory glass bottle',
  'peristaltic tubing',
  'dental part',
  'glucose monitor',
  'drug delivery',
  'metered dose counter',
  'cryogenic',
  'dental',
  'screw in injection device',
  'drug elution',
  'peristaltic pump',
  'implanted medical devices',
  'medical devices',
  'insulin pen',
  'wearable insulin pump',
  'auto-injector',
  'wearable pump',
  'plunger stopper for anesthesia syringe',
  'drug delivery device',
  'autoinjectors that is a good sliding partner',
  'lead screws in autoinjectors',
  'healtcare',
  'hip replacement',
  'x-ray',
  'connector port for iv bag',
  'implantable',
  'controlled release of drugs',
  'autoinjector pen plunger',
  'knees implant',
  'autoinjectors',
  'implant',
  'insulin pump',
  'mdi valve',
  'peristaltic pump tubing',
  'iv bag',
  'pharma drug delivery',
  'insulin injector pen',
  'medical implant',
  'intravenous bag',
  'autoinjector',
  'primary drug container',
  'pipette filter',
  'filter for pipette',
  'body implant',
  'knee replacement',
  'connector port for intravenous bag',
  'acetabular cup',
  'housing in a medical',
  'elastomer connector port for intravenous bag',
  'Autoinjectors',
  'connector port for IV bag',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'Consumer Goods': ['washing machine pump',
  'electric stove',
  'cooker handle',
  'refrigerator',
  'beer',
  'beer machine part',
  'paint can nozzle',
  'microwave oven',
  'toothbrushes',
  'beer machine',
  'part in beer machine',
  'footwear',
  'stocking',
  'toilet seat cover',
  'copy machine',
  'paint can nozzles',
  'baby stroller for consumer goods',
  'cap for lipstick',
  'baby chair for consumer goods',
  'microwave oven component',
  'part in a beer machine',
  'running shoes',
  'baking trays',
  'cap for refrigerator water filter',
  'ski bindings',
  'hinge for consumer goods furniture',
  'microwave component',
  'pump in washing machine',
  'beer keg component',
  'bicycle tyre',
  'motor housing for robot vacuum cleaner',
  'beer machine component',
  'part in a beer keg',
  'washing machine',
  'toys',
  'bread pan',
  'lego block',
  'hair dryer',
  'part for slingshot',
  'coffee maker',
  'beer kegs',
  'consumer electronics',
  'part on a beer machine',
  'diaphragm for consumer goods pump',
  'sunglasses bin',
  'beer keg part',
  'foot pedal for floor vacuum',
  'gear for robot vacuum',
  'nozzle for a paint can',
  'connector for consumer goods',
  'toilet seats',
  'beer keg pump',
  'dispenser slider for coffee machine',
  'office chair',
  'toy gears',
  'footwear midsole',
  'diapers',
  'tooth brush',
  'wear',
  'water filter for homewhole',
  'steam bucket',
  'part of a beer keg',
  'toothbrush',
  'microwave oven part',
  'artificial cow hoof',
  'dishwasher',
  'beer keg',
  'wig',
  'soda caps liner',
  'toilet seat covers',
  'microwave',
  'part for a beer machine',
  'footware',
  'pump application in a washing machine',
  'sausage packaging',
  'water purifier',
  'appliance',
  'gas appliance',
  'bathroom faucet',
  'consumer',
  'washing machine transmission gear',
  'furniture',
  'front plate for tasmanian devil free coffee brewing unit',
  'shower cartridge valve',
  'stove knob',
  'cell phone case',
  'bracket for lawn mower',
  'cell phone case',
  'soft-touch toothbrush overmolding',
  'cell phone cover',
  'loud speaker grill',
  'consumer electronics antenna',
  'pump in a washing machine',
  'push on bushing for dishwasher',
  'flushing systems',
  'fishing line',
  'door frame - hinges - door lock - handle - knobs',
  'kitchen ovens',
  'door frame - hinges - door lock - handle - knobs',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'Automotive & Transportation': ['active grille',
  'adas',
  'ags vanes',
  'aircraft',
  'airspring',
  'axial flux motor stator housing',
  'bearing for center console',
  'belt bracket for door trim panel',
  'bin mat for console',
  'bonnet',
  'brake pads',
  'bumper',
  'cac',
  'cap for distributor',
  'cap for pull handle',
  'carrier plate',
  'chc',
  'clip for roof bar',
  'coolant',
  'coolant hose',
  'coolant hoses',
  'coolant pipes',
  'coolant tube',
  'coolant tubes',
  'coolant tubing',
  'cooling',
  'cooling hoses',
  'cooling line',
  'cooling lines',
  'cooling pipes',
  'cooling tubes',
  'core for air filter',
  'corner mold',
  'cowl vent grill',
  'cyclinderhead covers',
  'cylindehead cover',
  'dashboard',
  'dynamic weather seal',
  'electric motor',
  'emotor',
  'e-motor',
  'engine cover',
  'engine mounts',
  'engine parts',
  'epb gears',
  'exterior weatherable',
  'fascia brackets',
  'fcv',
  'fenders',
  'flux capacitor',
  'front end module',
  'fuel flange',
  'fuel flanges',
  'fuel pomp',
  'fuel pump impeller',
  'fuel*pump*impeller',
  'glass run channel',
  'glove box',
  'grae for motor mounts',
  'grc',
  'grc foot',
  'grc lip',
  'grill vent part',
  'head cover',
  'head lamp house',
  'headlamp house',
  'headlight',
  'headrest',
  'headrests',
  'heads up display',
  'horn fluid reservoir',
  'housing for battery gas exhaust',
  'immersed coolant',
  'immersed coolant hose',
  'immersion cooling',
  'infill',
  'interior trim',
  'ip',
  'ip frame',
  'motor spool',
  'multicontrol valves',
  'oil pan',
  'oilpan',
  'part for water pump-impeller',
  'plastic suspension bellows',
  'power battery cooling pipe',
  'power train',
  'powertrain connectors',
  'propulsion cooling',
  'radiator',
  'radiator end tank',
  'radiator end tank',
  'raiator',
  'rast 2,5 and 5 connectors',
  'rocker cover',
  'rocker cover oil',
  'seat bolster',
  'seat cover box',
  'seat cushion',
  'seat head cover box',
  'slipcoat',
  'spoiler',
  'stator busbar',
  'strut bellow',
  'strut bumper',
  'suite for air-intake manifold',
  'suspension',
  'suspension belllow',
  'suspension bellow',
  'suspension bellows',
  'suspensions bellow',
  'suspsension bellow',
  'tailgate',
  'tailgate housing',
  'tailgate tube housing',
  'thermal management',
  'thermal management module',
  'thermal management valve',
  'thermo management housing',
  'thermo managment systems',
  'tmm',
  'under - the - hood ( uth )',
  'upper frame for console',
  'vent grill',
  'visible interior parts',
  'washer-m6 bolt',
  'wheel speed',
  'electrical cars',
  'fuel cap',
  'tailgate protective tube housing',
  'tailgate spring sleeve',
  'cap for fuel valve',
  'auto seat head cover box',
  'automotive trunk',
  'automotive seating',
  'cap for fuel module',
  'crossbeam for automotive and transportation',
  'auto',
  'automotive',
  'back door plate for automotive & transportation',
  'automotive headset cover box',
  'back cover for automotive & transportation',
  'ev coolant hose',
  'flange for fuel module',
  'housing for a tailgate spring',
  'cvj boots',
  'oil filter for automotive & transportation',
  'ev connector',
  'automotive camera base',
  'active grille shutter',
  'under-the-hood (uth)',
  'head lamp housing',
  'automotive camera mount',
  'ev electric motor',
  'auto camera base',
  'cap for fuel tank',
  'chc',
  'cylinder head cover',
  'engine mount',
  'air intake manifold',
  'car cross beams',
  'auto application film',
  'ev cooling hoses',
  'automotive seat head cover box',
  'automotive seat head box',
  'tailgate protective housing',
  'adas camera bracket',
  'camshafts',
  'ev charge insulation',
  'cross car beam',
  'ev immersed coolant hose',
  'e-vehicle connector',
  'adas windshield bracket',
  '2k injection molding skin (air bag cover, center consoles, instrument panels, doors, pillars)',
  'cap for fuel vapor valve',
  '5g antenna ( adas )',
  'tube housing for tailgate',
  'car camera',
  'bumper beam',
  'car trunk',
  'adas front camera heaters',
  'cvj boot',
  'ev charger station frame',
  'automotive housing',
  'seal for headlights',
  'ev charger',
  'gasoline cap',
  'passenger wagon interior components',
  'filter for automatic transmission fluid (atf)',
  'ev',
  'low pressure tank for automotive & transportation',
  'headlight guard',
  '3-way coolant valve for automotive & transportation',
  'bus - bar for batteries',
  'sump filter for automotive transmission',
  'electric vehicle connector',
  'automotive water pump-impeller',
  'air intake manifolds for auto',
  'fuel tank',
  'housing for gasoline particulate filter ( gpf ) pressure sensor',
  'auto seating headrest',
  'latch for tailgate',
  'auto exterior roof extender',
  'filter for automatic transmission fluid ( atf )',
  'fuel cap for automotive fuel',
  'electrical vehicle connector',
  'on-board charger ( obc ) in ev',
  'bumper for crankshaft pulley isolator',
  'ev charging',
  'seat trim',
  'auto seat headrest',
  'window crank for automotive & transportation',
  'wall box application in ev charging station',
  'electrical vehicle cooling hose',
  'car roof',
  'automotive seat cover',
  'electric cover for automotive & transportation',
  'camera base for automotive',
  'headlight protection',
  'compact camera module ( ccm ) for automotive',
  'auto lighting',
  'cooling tank for trucks',
  'jounce bumper',
  'electronic housing in automotive',
  'blinker fluid reservoir',
  'car dashboard',
  'ev hose cooling',
  'headlight protection gear',
  'seal for a headlight',
  'vehicle dashboard',
  'e-mobility',
  'auto camera',
  'back cover for meter cluster',
  'exterior auto',
  'cooling tan for trucks',
  'automotive interior carpets',
  'tire carrier support for automotive & transportation',
  'air intake manifolds',
  'ignition coils',
  'engine cooling',
  'thermal management materials for ev',
  'automotive camera',
  'cap for fuel pump module',
  'protective housing for tailgate',
  'accelerator pedal for automotive & transportation',
  'push button seat belt',
  'automotive boots without squeaking noise',
  'electric vehicles',
  'fuel pump impellers',
  'vehicle trunk',
  'electro car cooling thermostat',
  'car mats',
  'ski for snowmobile',
  'ev charging gun',
  'electric powertrain',
  'cover for engine',
  'automotive interior',
  'automotive overmolded busbar',
  'automotive seat',
  'instrument panels in automotive',
  'electric auto connector',
  'cap for rear wiper',
  'end clip for automotive & transportation',
  'protective housings for the tailgate',
  'auto coolant',
  'auto passenger bracket',
  'cooling hoses for ev',
  'automotive sensor housing',
  'automotive interior fastener',
  'air outlet for automotive & transportation',
  'connector for ev',
  'suspension part',
  'control valve for carbon cannister',
  'outdoor automotive',
  'automotive camera part',
  'bus - bar for e-motor',
  'bumper for auto',
  'rear spoiler',
  'busbars in traction motors',
  'auto cable t4',
  'ev cooling',
  'bosch fuel cell battery',
  'full truck',
  'bmw gen6 ix',
  'busbar in automotive',
  'body plug for automotive & transportation',
  'guiding piece for head lamp',
  'ball socket for head lamp',
  'housing for gasoline particulate filter (gpf) pressure sensor',
  'crossbeam for automotive & transportation',
  'fuel rail',
  'wheel speed sensor',
  'safety belt buckles',
  'junction box on automotive',
  'exterior uv applications in auto',
  'protective tube housing for a tailgate',
  'auto coolant',
  'vehicle chassis',
  'intakemanifold',
  'macpherson top mount bearing',
  'auto connector',
  'automotive & transportation',
  'ev battery',
  'seat head cover box for automobiles',
  'air duct bracket for automotive & transportation',
  'bmw gen6 ix models',
  'automotive cooling hose',
  'heads up display heatsink',
  'safety belt push buttons',
  'auto cross beams',
  'compact camera module (ccm) for automotive',
  'vehicle mounted charging port',
  'bearing seal for automotive & transportation',
  'automotive camera bases',
  "passenger car's seating",
  'wheel speed sensors',
  'profile for bus',
  'headlamp housing',
  'auto for fan and shrouds',
  'automotive radar housing',
  'exterior applications in auto',
  'chc',
  'bev inverter',
  'interior auto',
  'auto interior',
  'tmm housing of bev',
  'bezel for head lamp',
  'side reflector for automotive & transportation',
  'ev cooling lines',
  'ev car',
  'air ducts, hoses & resonators',
  'turbo gasolene engine/diesel',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'Electrical & Electronics': ['Electrical & Electronics',
  'circuit breaker',
  '5g antenna',
  '5g antenna for electrical & electronics',
  'power electronics insulation',
  'electronics',
  'parts in a light aligner',
  'ddr',
  'light aligner',
  'charger plug',
  'mobile antenna',
  'light aligner part',
  'computer keyboard tab',
  'cable jacketing',
  'cable insulation',
  'curcuit breaker',
  'electrolyzer frame',
  'miniature circuit breaker ( mcb ) housing',
  'circuit breakers',
  '5g antenna for telecommunications',
  'eletronics',
  'mcb ( circuit breakers )',
  'mobile phone frame',
  'charging plug',
  'electrolyzer',
  '120a outdoor connector for electrical & electronics',
  'light alighner',
  'smt solder for vhdm connector',
  'smartphone mainboard cover',
  'domestic circuit breaker',
  'miniature circuit breaker (mcb) housing',
  '40 amp disconnector for electrical & electronics',
  'computer keyboard',
  'keyboard scissors',
  'laptop keyboard',
  'computer',
  'part for power electronics insulation',
  'keyboard',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',

In [191]:
app_industry_data_cleaned = {}
for i in app_industry_data:
    app_industry_data_cleaned[i.lower()] = [re.sub("(\s+)", " ", x.strip().lower()) for x in app_industry_data[i] if x] + [re.sub("(\s+)", " ", x.strip().lower()) for x in app_industry_data2[i] if x]

app_industry_data_cleaned

{'medical & pharma': ['connection ring for natural glove',
  'autoinjector-anaphylaxis',
  'autoinjector-retraction assembly',
  'clamp for feeding catheter',
  'dispension monitoring for diabetes pharmaceutical preparation',
  'dose button for insulin pen',
  'drug delivery systems',
  'handle for flexible endoscopy',
  'hospital diagnostics & imaging',
  'metered dose inhaler (mdi)-dose counter',
  'plunger for intra ocular lens (iol)',
  'power transmission for metered dose inhaler (mdi)',
  'rod for orthopedic sizing device',
  'hips implant',
  'syringe stopper',
  'prosthetic dog ear',
  'hip implant',
  'orthopedic implant',
  'medical',
  'peristaltic pump gears',
  'peristaltic tub',
  'housing in a medical',
  'medical',
  'cap for laboratory glass bottle',
  'peristaltic tubing',
  'dental part',
  'glucose monitor',
  'drug delivery',
  'metered dose counter',
  'cryogenic',
  'dental',
  'screw in injection device',
  'drug elution',
  'peristaltic pump',
  'implanted medical devices',
  'medical devices',
  'insulin pen',
  'wearable insulin pump',
  'auto-injector',
  'wearable pump',
  'plunger stopper for anesthesia syringe',
  'drug delivery device',
  'autoinjectors that is a good sliding partner',
  'lead screws in autoinjectors',
  'healtcare',
  'hip replacement',
  'x-ray',
  'connector port for iv bag',
  'implantable',
  'controlled release of drugs',
  'autoinjector pen plunger',
  'knees implant',
  'autoinjectors',
  'implant',
  'insulin pump',
  'mdi valve',
  'peristaltic pump tubing',
  'iv bag',
  'pharma drug delivery',
  'insulin injector pen',
  'medical implant',
  'intravenous bag',
  'autoinjector',
  'primary drug container',
  'pipette filter',
  'filter for pipette',
  'body implant',
  'knee replacement',
  'connector port for intravenous bag',
  'acetabular cup',
  'housing in a medical',
  'elastomer connector port for intravenous bag',
  'autoinjectors',
  'connector port for iv bag'],
 'consumer goods': ['box for specimen collection',
  'sprayers-throat tubes, nebulization inserts, joints',
  'tube for disinfection cabinet',
  'guide for paper transport',
  'remote control for rudder',
  'tire and rim association (tra) compliant wheel rim for all terrain vehicle (atv)',
  'wheel rim for gravel bike',
  'accumulator for water pump',
  'actuator for aerosol valve',
  'cassette stove-valve',
  'clip for nail gun',
  'clip for vine',
  'end cap cover for gear',
  'faucet-valve',
  'pumping unit for dispenser',
  'support for conveyor belt',
  '"aqua pro" gear program',
  'blade holder for ice hockey shoes',
  'valve for cosmetic',
  'wire guides, clamps, clips, collars, buttons, guides',
  'pinch clamp for lab use',
  'back for chair',
  'back frame for office chair',
  'back lower portion for office chair',
  'bearing for furniture',
  'brewing system-dispenser button',
  'buckle and shoes',
  'button for appliance',
  "children's carriage-gear",
  'consumer filtration',
  'cover for dishwasher impeller',
  'cylinder for lock',
  'damper for sunglass compartment',
  'dishwasher-rack clips',
  'dishwasher-roller',
  'driving bridge for beard and hair trimmer',
  'filling valve for toilet flushing mechanism',
  'fishing reel',
  'flip tines for dishwasher',
  'front plate for grease free coffee brewing unit',
  'furniture-gear',
  'gear box for washing machine transmission',
  'gear for window shade',
  'gear for window shade cable guide',
  'gearbox for washing machine',
  'grip for appliance',
  'guide rail for furniture',
  'holding structure for camera',
  'housing for dishwasher',
  'impeller for oven',
  'inlet valve for dishwasher',
  'insert for razor handle',
  'joint for baby pram',
  'lawn trimmer-cable drum housing and cover',
  'leveling leg for dishwasher leak pan',
  'lid lock for washing machine',
  'lock for home door',
  'lower rack clip for dishwasher',
  'mascara-stick',
  'plug for coffee machine brewing unit',
  'pole for ski',
  'refrigerator-food drawer roller',
  'roller for dishwasher',
  'seatback frame for hybrid chair',
  'shifter base for washing machine',
  'slider for vacuum cleaner',
  'sliding for dishwasher',
  'spray valve for perfume',
  'strike door plate for dishwasher',
  'sun umbrella articulation',
  'support for saddle storage system',
  'television parts',
  'toilet flushing units',
  'toothbrush tube base for oral care',
  'torsion plate for footwear',
  'vacuum cleaner for pool',
  'vacuum cleaner-gear',
  'valve for drink machine',
  'water tank seal for wet dry vacuum cleaner',
  'water valve for refrigerator',
  'wingnut for dishwasher',
  'washing machine pump',
  'electric stove',
  'cooker handle',
  'refrigerator',
  'beer',
  'beer machine part',
  'paint can nozzle',
  'microwave oven',
  'toothbrushes',
  'beer machine',
  'part in beer machine',
  'footwear',
  'stocking',
  'toilet seat cover',
  'copy machine',
  'paint can nozzles',
  'baby stroller for consumer goods',
  'cap for lipstick',
  'baby chair for consumer goods',
  'microwave oven component',
  'part in a beer machine',
  'running shoes',
  'baking trays',
  'cap for refrigerator water filter',
  'ski bindings',
  'hinge for consumer goods furniture',
  'microwave component',
  'pump in washing machine',
  'beer keg component',
  'bicycle tyre',
  'motor housing for robot vacuum cleaner',
  'beer machine component',
  'part in a beer keg',
  'washing machine',
  'toys',
  'bread pan',
  'lego block',
  'hair dryer',
  'part for slingshot',
  'coffee maker',
  'beer kegs',
  'consumer electronics',
  'part on a beer machine',
  'diaphragm for consumer goods pump',
  'sunglasses bin',
  'beer keg part',
  'foot pedal for floor vacuum',
  'gear for robot vacuum',
  'nozzle for a paint can',
  'connector for consumer goods',
  'toilet seats',
  'beer keg pump',
  'dispenser slider for coffee machine',
  'office chair',
  'toy gears',
  'footwear midsole',
  'diapers',
  'tooth brush',
  'wear',
  'water filter for homewhole',
  'steam bucket',
  'part of a beer keg',
  'toothbrush',
  'microwave oven part',
  'artificial cow hoof',
  'dishwasher',
  'beer keg',
  'wig',
  'soda caps liner',
  'toilet seat covers',
  'microwave',
  'part for a beer machine',
  'footware',
  'pump application in a washing machine',
  'sausage packaging',
  'water purifier',
  'appliance',
  'gas appliance',
  'bathroom faucet',
  'consumer',
  'washing machine transmission gear',
  'furniture',
  'front plate for tasmanian devil free coffee brewing unit',
  'shower cartridge valve',
  'stove knob',
  'cell phone case',
  'bracket for lawn mower',
  'cell phone case',
  'soft-touch toothbrush overmolding',
  'cell phone cover',
  'loud speaker grill',
  'consumer electronics antenna',
  'pump in a washing machine',
  'push on bushing for dishwasher',
  'flushing systems',
  'fishing line',
  'door frame - hinges - door lock - handle - knobs',
  'kitchen ovens',
  'door frame - hinges - door lock - handle - knobs'],
 'automotive & transportation': ['anti-slip mat for door storage box',
  'backlit knob-actuator',
  'carrier for back rest',
  'clip for recliner',
  'duct for air conditioner (ac)',
  'key lock',
  'mirror for door',
  'adjustment for lighting',
  'housing for light control',
  'housing for lighting sensor',
  'plate for backlight',
  'protective cap for electronical & electronics',
  'structural for smart phone station (sps) display',
  'support for electromagnetic compatibility (emc) filter',
  'terminal for battery fuse',
  'washer nozzle for camera',
  'bracket for air duct',
  'clip for stud mount',
  'cold air hose for coupling box cooling',
  'connector for control power transformer (cpt)',
  'connector for water coolant circuit',
  'cover cap for gear drive',
  'fastener for fuel pipe',
  'holder for thermal management module (tmm)',
  'isolator for spring cup',
  'mount for nozzle',
  'o ring spacer for battery cooling line',
  'rotary valve for thermal management module (tmm)',
  'seal for battery access panel',
  'side cover for water channel',
  'structural brackets & beams',
  'adapter for interior',
  'bearing cage for interior',
  'bracket for console',
  'cover for cell super control (csc)',
  'fastener for panel',
  'grommet-top post',
  'lever for air conditioner (ac)',
  'mount for hinge',
  'spring plate',
  'structural support for console',
  'air channel for mass air flow (maf) sensor',
  'air duct adapter for defroster',
  'automobile (gasoline)-fuel module',
  'automotive air register',
  'automotive brake pedal',
  'automotive bushing-bearing cover',
  'automotive cargo area-hook',
  'automotive chassis-bracket',
  'automotive connector-clip',
  'automotive connector-pin',
  'automotive console link-strip retainer',
  'automotive cover-bracket',
  'automotive cup holder-housing',
  'automotive door-lock cover',
  'automotive door-stopper',
  'automotive fr bumper-retainer',
  'automotive fuel delivery module (fdm)',
  'automotive fuel module-ec pump',
  'automotive fuel pump',
  'automotive fuel reservoir and flange',
  'automotive fuel supply system-filter box body',
  'automotive fuel supply system-flange',
  'automotive fuel supply system-holder',
  'automotive fuel tank-flange',
  'automotive grommet',
  'automotive instrument panel and console system-trim clip',
  'automotive motorcycle-key cover',
  'automotive rear fuel tank-baffle',
  'automotive retainer-fastener',
  'automotive seat-latch housing',
  'automotive sensor-drive cover, adapter',
  'automotive side bumper-fastener and support',
  'automotive spring cassette-housing',
  'automotive spring drive-cover',
  'automotive spring-sleeve',
  'automotive steering column control module (sccm)-button',
  'automotive webbing guide',
  'automotive window lift-cursor',
  'automotive-2w fuel delivery module (fdm)',
  'automotive-4 way headrest',
  'ball valve for engine',
  'base plate for seat cushion length adjustment (scla)',
  'battery module for electric powertrain',
  'bellow for suspension',
  'blade for wiper',
  'bobbin for fuel tank isolation valve (ftiv)',
  'bobbin for pressure control solenoid valve (pcsv)',
  'bobbin for starter',
  'body-clip',
  'boot for propeller shaft',
  'boot for steering/suspension',
  'bracket for battery pack cable routing',
  'bracket for cup holder',
  'bracket for filler pipe',
  'bracket for headlight grille',
  'braking motor system for automobile & transportation',
  'brushless fuel delivery module (fdm) for gasoline engine',
  'bumper for hood',
  'camshaft positioning sensor (cmps) for turbo engine',
  'cap for sunroof',
  'capless fuel supply system',
  'carrier plate for seat cushion length adjustment (scla)',
  'channel for glass run',
  'charging panel for electric vehicle (ev)',
  'clip for door lift',
  'collar spring for clutch',
  'connector for automotive video navigation (avn)',
  'connector for electric mobility (e-mobility)',
  'connector for engine cooling system',
  'connector for ignition',
  'constant velocity joint (cvj) rear boot for motorcycle',
  'control handle for exterior mirror',
  'cooling module for dual clutch transmission (dct)',
  'core lever for transmission',
  'counter bearing cap for sun visor',
  'cover for engine valve',
  'cover for sunroof',
  'cover seal for engine',
  'cup holder for interior',
  'defroster for electric vehicle (ev)',
  'diaphragm for drive shaft',
  'distance adjustment for head rest',
  'distribution plate for fuel cell stack',
  'drop gate for tailgate latch',
  'duct for air intake',
  'electrical header for steering',
  'emergency charger cable for electric vehicle (ev)',
  'end cap for battery module',
  'end cap for outer beltline seal (obls)',
  'fender bracket (rh/lh)',
  'filter for diesel exhaust fluid (def)',
  'fixation for battery pack cable',
  'flange holder for fuel pump',
  'floor mat retainer system',
  'fuse assembly protection box for under the hood (uth)',
  'gas generator for seat belt',
  'gasket for door mirror',
  'gear for seat adjuster',
  'grommet clip for door panel',
  'guide bushing for headrest',
  'guide for headlamp',
  'guide plate for seat length adjuster',
  'handphone holder for motorcycle',
  'height position sensor for vehicle',
  'high voltage (hv) connector for electric vehicle (ev) powertrain',
  'hinge for fuel lid',
  'hinge for panel truck',
  'holder for safety belt',
  'housing for airbag',
  'housing for battery pyro switch',
  'housing for brake bushing',
  'housing for convertible roof',
  'housing for intercooler tank',
  'housing for safety belt system',
  'inlet control valve (icv) for fuel supply system',
  'insulated cover of electric vehicle (ev) charger',
  'latch for society of automotive engineers (sae) connector',
  'lens barrel for automotive compact camera module (ccm)',
  'linear actuator for two wheeler',
  'liner for floor',
  'lithium ion battery separator (libs) for plug-in hybrid electric vehicle (phev)',
  'lithium-ion battery separator (libs) for electric vehicle (ev)',
  'locknut for railway',
  'louver for truck',
  'middle gear for throttle body',
  'mini driver for power seat',
  'mirror for rearview',
  'motor housings & covers (traction motors)',
  'motor stator for electric cooling pump',
  'oil pan for hybrid transmission',
  'outer belt line seal (obls) for door',
  'outlet for intercooler',
  'pad for instrument panel (ip)',
  'partial hybrid electric vehicle (phev)',
  'pedals & gear shift systems',
  'pedestrian protection bracket',
  'pedestrian protection bracket for bumper',
  'powertrain-service cover',
  'protective cap for electric mobility',
  'pushrod retainer for plug-in hybrid electric vehicle (phev)',
  'quick connector (battery thermal management)',
  'rebound bumper for suspension',
  'resonator for engine',
  'sail for roof load carrying',
  'seal for bumper',
  'seal for seat recliner',
  'seat belt guide & pillar loop',
  'seat belt retractor',
  'seat belt-web guide',
  'selector shift actuator (ssa) for double clutch transmission (dct)',
  'sensor housing for fuel pump rotor',
  'shell for headrest',
  'side cover for dual clutch transmission (dct)',
  'skin for instrument panel (ip)',
  'skirt fairing for trunk body',
  'sleeve for accelerator pedal',
  'slider for headrest',
  'speed sensor for turbocharged truck',
  'spring element for seat cushion length adjustment (scla)',
  'spring side bearing for automotive',
  'steering column-eccentric disc',
  'strut for trunk door',
  'substrate for armrest',
  'support for seat motor',
  'support yoke for rack and pinion (r&p)',
  'temperature sensor for electric vehicle (ev) battery',
  'thumb wheel for air conditioner (ac)',
  'traction inverter for electric truck',
  'travel restrictor for chassis',
  'travel stop for belt tensioner',
  'trim for overhead console (ohc)',
  'trim for seat rail',
  'trunk components',
  'tube for air suspension',
  'turn signal-shaft base',
  'web sense retractor for seat belt',
  'wiper arm',
  'active grille',
  'adas',
  'ags vanes',
  'aircraft',
  'airspring',
  'axial flux motor stator housing',
  'bearing for center console',
  'belt bracket for door trim panel',
  'bin mat for console',
  'bonnet',
  'brake pads',
  'bumper',
  'cac',
  'cap for distributor',
  'cap for pull handle',
  'carrier plate',
  'chc',
  'clip for roof bar',
  'coolant',
  'coolant hose',
  'coolant hoses',
  'coolant pipes',
  'coolant tube',
  'coolant tubes',
  'coolant tubing',
  'cooling',
  'cooling hoses',
  'cooling line',
  'cooling lines',
  'cooling pipes',
  'cooling tubes',
  'core for air filter',
  'corner mold',
  'cowl vent grill',
  'cyclinderhead covers',
  'cylindehead cover',
  'dashboard',
  'dynamic weather seal',
  'electric motor',
  'emotor',
  'e-motor',
  'engine cover',
  'engine mounts',
  'engine parts',
  'epb gears',
  'exterior weatherable',
  'fascia brackets',
  'fcv',
  'fenders',
  'flux capacitor',
  'front end module',
  'fuel flange',
  'fuel flanges',
  'fuel pomp',
  'fuel pump impeller',
  'fuel*pump*impeller',
  'glass run channel',
  'glove box',
  'grae for motor mounts',
  'grc',
  'grc foot',
  'grc lip',
  'grill vent part',
  'head cover',
  'head lamp house',
  'headlamp house',
  'headlight',
  'headrest',
  'headrests',
  'heads up display',
  'horn fluid reservoir',
  'housing for battery gas exhaust',
  'immersed coolant',
  'immersed coolant hose',
  'immersion cooling',
  'infill',
  'interior trim',
  'ip',
  'ip frame',
  'motor spool',
  'multicontrol valves',
  'oil pan',
  'oilpan',
  'part for water pump-impeller',
  'plastic suspension bellows',
  'power battery cooling pipe',
  'power train',
  'powertrain connectors',
  'propulsion cooling',
  'radiator',
  'radiator end tank',
  'radiator end tank',
  'raiator',
  'rast 2,5 and 5 connectors',
  'rocker cover',
  'rocker cover oil',
  'seat bolster',
  'seat cover box',
  'seat cushion',
  'seat head cover box',
  'slipcoat',
  'spoiler',
  'stator busbar',
  'strut bellow',
  'strut bumper',
  'suite for air-intake manifold',
  'suspension',
  'suspension belllow',
  'suspension bellow',
  'suspension bellows',
  'suspensions bellow',
  'suspsension bellow',
  'tailgate',
  'tailgate housing',
  'tailgate tube housing',
  'thermal management',
  'thermal management module',
  'thermal management valve',
  'thermo management housing',
  'thermo managment systems',
  'tmm',
  'under - the - hood ( uth )',
  'upper frame for console',
  'vent grill',
  'visible interior parts',
  'washer-m6 bolt',
  'wheel speed',
  'electrical cars',
  'fuel cap',
  'tailgate protective tube housing',
  'tailgate spring sleeve',
  'cap for fuel valve',
  'auto seat head cover box',
  'automotive trunk',
  'automotive seating',
  'cap for fuel module',
  'crossbeam for automotive and transportation',
  'auto',
  'automotive',
  'back door plate for automotive & transportation',
  'automotive headset cover box',
  'back cover for automotive & transportation',
  'ev coolant hose',
  'flange for fuel module',
  'housing for a tailgate spring',
  'cvj boots',
  'oil filter for automotive & transportation',
  'ev connector',
  'automotive camera base',
  'active grille shutter',
  'under-the-hood (uth)',
  'head lamp housing',
  'automotive camera mount',
  'ev electric motor',
  'auto camera base',
  'cap for fuel tank',
  'chc',
  'cylinder head cover',
  'engine mount',
  'air intake manifold',
  'car cross beams',
  'auto application film',
  'ev cooling hoses',
  'automotive seat head cover box',
  'automotive seat head box',
  'tailgate protective housing',
  'adas camera bracket',
  'camshafts',
  'ev charge insulation',
  'cross car beam',
  'ev immersed coolant hose',
  'e-vehicle connector',
  'adas windshield bracket',
  '2k injection molding skin (air bag cover, center consoles, instrument panels, doors, pillars)',
  'cap for fuel vapor valve',
  '5g antenna ( adas )',
  'tube housing for tailgate',
  'car camera',
  'bumper beam',
  'car trunk',
  'adas front camera heaters',
  'cvj boot',
  'ev charger station frame',
  'automotive housing',
  'seal for headlights',
  'ev charger',
  'gasoline cap',
  'passenger wagon interior components',
  'filter for automatic transmission fluid (atf)',
  'ev',
  'low pressure tank for automotive & transportation',
  'headlight guard',
  '3-way coolant valve for automotive & transportation',
  'bus - bar for batteries',
  'sump filter for automotive transmission',
  'electric vehicle connector',
  'automotive water pump-impeller',
  'air intake manifolds for auto',
  'fuel tank',
  'housing for gasoline particulate filter ( gpf ) pressure sensor',
  'auto seating headrest',
  'latch for tailgate',
  'auto exterior roof extender',
  'filter for automatic transmission fluid ( atf )',
  'fuel cap for automotive fuel',
  'electrical vehicle connector',
  'on-board charger ( obc ) in ev',
  'bumper for crankshaft pulley isolator',
  'ev charging',
  'seat trim',

In [192]:
for ind in app_industry_data_cleaned:
    print(len(app_industry_data_cleaned[ind]))

74
180
550
83
94
519

In [193]:
for ind in app_industry_data_cleaned:
    for app in app_industry_data_cleaned[ind]:
        for ind2 in app_industry_data_cleaned:
            if ind != ind2 and app in app_industry_data_cleaned[ind2]:
                print(f"'{app}' present in {ind} and {ind2}")

In [194]:
for ind in app_industry_data_cleaned:
    temp = []
    for app in app_industry_data_cleaned[ind]:
        if app not in temp:
            temp.append(app)

    app_industry_data_cleaned[ind] = temp

for ind in app_industry_data_cleaned:
    print(len(app_industry_data_cleaned[ind]))

70
178
546
83
94
508

In [195]:
for ind in app_industry_data_cleaned:
    for app in app_industry_data_cleaned[ind]:
        if len(app) < 4:
            print(app)

wig
cac
chc
fcv
grc
ip
tmm
ev
ddr
rod
5g
pv
ccm
ewp
fan
oil

In [196]:
ignore_apps = [
    'ip',
    'pv',
    'oil',
    'water',
    'medical',
]

for ind in app_industry_data_cleaned:
    app_industry_data_cleaned[ind] = [app for app in app_industry_data_cleaned[ind] if app not in ignore_apps]

for ind in app_industry_data_cleaned:
    for app in app_industry_data_cleaned[ind]:
        if len(app) < 4:
            print(app)

wig
cac
chc
fcv
grc
tmm
ev
ddr
rod
5g
ccm
ewp
fan

In [197]:
for ind in app_industry_data_cleaned:
    print(len(app_industry_data_cleaned[ind]))

69
178
545
83
94
505

In [198]:
app_industry_data_cleaned

{'medical & pharma': ['connection ring for natural glove',
  'autoinjector-anaphylaxis',
  'autoinjector-retraction assembly',
  'clamp for feeding catheter',
  'dispension monitoring for diabetes pharmaceutical preparation',
  'dose button for insulin pen',
  'drug delivery systems',
  'handle for flexible endoscopy',
  'hospital diagnostics & imaging',
  'metered dose inhaler (mdi)-dose counter',
  'plunger for intra ocular lens (iol)',
  'power transmission for metered dose inhaler (mdi)',
  'rod for orthopedic sizing device',
  'hips implant',
  'syringe stopper',
  'prosthetic dog ear',
  'hip implant',
  'orthopedic implant',
  'peristaltic pump gears',
  'peristaltic tub',
  'housing in a medical',
  'cap for laboratory glass bottle',
  'peristaltic tubing',
  'dental part',
  'glucose monitor',
  'drug delivery',
  'metered dose counter',
  'cryogenic',
  'dental',
  'screw in injection device',
  'drug elution',
  'peristaltic pump',
  'implanted medical devices',
  'medical devices',
  'insulin pen',
  'wearable insulin pump',
  'auto-injector',
  'wearable pump',
  'plunger stopper for anesthesia syringe',
  'drug delivery device',
  'autoinjectors that is a good sliding partner',
  'lead screws in autoinjectors',
  'healtcare',
  'hip replacement',
  'x-ray',
  'connector port for iv bag',
  'implantable',
  'controlled release of drugs',
  'autoinjector pen plunger',
  'knees implant',
  'autoinjectors',
  'implant',
  'insulin pump',
  'mdi valve',
  'peristaltic pump tubing',
  'iv bag',
  'pharma drug delivery',
  'insulin injector pen',
  'medical implant',
  'intravenous bag',
  'autoinjector',
  'primary drug container',
  'pipette filter',
  'filter for pipette',
  'body implant',
  'knee replacement',
  'connector port for intravenous bag',
  'acetabular cup',
  'elastomer connector port for intravenous bag'],
 'consumer goods': ['box for specimen collection',
  'sprayers-throat tubes, nebulization inserts, joints',
  'tube for disinfection cabinet',
  'guide for paper transport',
  'remote control for rudder',
  'tire and rim association (tra) compliant wheel rim for all terrain vehicle (atv)',
  'wheel rim for gravel bike',
  'accumulator for water pump',
  'actuator for aerosol valve',
  'cassette stove-valve',
  'clip for nail gun',
  'clip for vine',
  'end cap cover for gear',
  'faucet-valve',
  'pumping unit for dispenser',
  'support for conveyor belt',
  '"aqua pro" gear program',
  'blade holder for ice hockey shoes',
  'valve for cosmetic',
  'wire guides, clamps, clips, collars, buttons, guides',
  'pinch clamp for lab use',
  'back for chair',
  'back frame for office chair',
  'back lower portion for office chair',
  'bearing for furniture',
  'brewing system-dispenser button',
  'buckle and shoes',
  'button for appliance',
  "children's carriage-gear",
  'consumer filtration',
  'cover for dishwasher impeller',
  'cylinder for lock',
  'damper for sunglass compartment',
  'dishwasher-rack clips',
  'dishwasher-roller',
  'driving bridge for beard and hair trimmer',
  'filling valve for toilet flushing mechanism',
  'fishing reel',
  'flip tines for dishwasher',
  'front plate for grease free coffee brewing unit',
  'furniture-gear',
  'gear box for washing machine transmission',
  'gear for window shade',
  'gear for window shade cable guide',
  'gearbox for washing machine',
  'grip for appliance',
  'guide rail for furniture',
  'holding structure for camera',
  'housing for dishwasher',
  'impeller for oven',
  'inlet valve for dishwasher',
  'insert for razor handle',
  'joint for baby pram',
  'lawn trimmer-cable drum housing and cover',
  'leveling leg for dishwasher leak pan',
  'lid lock for washing machine',
  'lock for home door',
  'lower rack clip for dishwasher',
  'mascara-stick',
  'plug for coffee machine brewing unit',
  'pole for ski',
  'refrigerator-food drawer roller',
  'roller for dishwasher',
  'seatback frame for hybrid chair',
  'shifter base for washing machine',
  'slider for vacuum cleaner',
  'sliding for dishwasher',
  'spray valve for perfume',
  'strike door plate for dishwasher',
  'sun umbrella articulation',
  'support for saddle storage system',
  'television parts',
  'toilet flushing units',
  'toothbrush tube base for oral care',
  'torsion plate for footwear',
  'vacuum cleaner for pool',
  'vacuum cleaner-gear',
  'valve for drink machine',
  'water tank seal for wet dry vacuum cleaner',
  'water valve for refrigerator',
  'wingnut for dishwasher',
  'washing machine pump',
  'electric stove',
  'cooker handle',
  'refrigerator',
  'beer',
  'beer machine part',
  'paint can nozzle',
  'microwave oven',
  'toothbrushes',
  'beer machine',
  'part in beer machine',
  'footwear',
  'stocking',
  'toilet seat cover',
  'copy machine',
  'paint can nozzles',
  'baby stroller for consumer goods',
  'cap for lipstick',
  'baby chair for consumer goods',
  'microwave oven component',
  'part in a beer machine',
  'running shoes',
  'baking trays',
  'cap for refrigerator water filter',
  'ski bindings',
  'hinge for consumer goods furniture',
  'microwave component',
  'pump in washing machine',
  'beer keg component',
  'bicycle tyre',
  'motor housing for robot vacuum cleaner',
  'beer machine component',
  'part in a beer keg',
  'washing machine',
  'toys',
  'bread pan',
  'lego block',
  'hair dryer',
  'part for slingshot',
  'coffee maker',
  'beer kegs',
  'consumer electronics',
  'part on a beer machine',
  'diaphragm for consumer goods pump',
  'sunglasses bin',
  'beer keg part',
  'foot pedal for floor vacuum',
  'gear for robot vacuum',
  'nozzle for a paint can',
  'connector for consumer goods',
  'toilet seats',
  'beer keg pump',
  'dispenser slider for coffee machine',
  'office chair',
  'toy gears',
  'footwear midsole',
  'diapers',
  'tooth brush',
  'wear',
  'water filter for homewhole',
  'steam bucket',
  'part of a beer keg',
  'toothbrush',
  'microwave oven part',
  'artificial cow hoof',
  'dishwasher',
  'beer keg',
  'wig',
  'soda caps liner',
  'toilet seat covers',
  'microwave',
  'part for a beer machine',
  'footware',
  'pump application in a washing machine',
  'sausage packaging',
  'water purifier',
  'appliance',
  'gas appliance',
  'bathroom faucet',
  'consumer',
  'washing machine transmission gear',
  'furniture',
  'front plate for tasmanian devil free coffee brewing unit',
  'shower cartridge valve',
  'stove knob',
  'cell phone case',
  'bracket for lawn mower',
  'soft-touch toothbrush overmolding',
  'cell phone cover',
  'loud speaker grill',
  'consumer electronics antenna',
  'pump in a washing machine',
  'push on bushing for dishwasher',
  'flushing systems',
  'fishing line',
  'door frame - hinges - door lock - handle - knobs',
  'kitchen ovens'],
 'automotive & transportation': ['anti-slip mat for door storage box',
  'backlit knob-actuator',
  'carrier for back rest',
  'clip for recliner',
  'duct for air conditioner (ac)',
  'key lock',
  'mirror for door',
  'adjustment for lighting',
  'housing for light control',
  'housing for lighting sensor',
  'plate for backlight',
  'protective cap for electronical & electronics',
  'structural for smart phone station (sps) display',
  'support for electromagnetic compatibility (emc) filter',
  'terminal for battery fuse',
  'washer nozzle for camera',
  'bracket for air duct',
  'clip for stud mount',
  'cold air hose for coupling box cooling',
  'connector for control power transformer (cpt)',
  'connector for water coolant circuit',
  'cover cap for gear drive',
  'fastener for fuel pipe',
  'holder for thermal management module (tmm)',
  'isolator for spring cup',
  'mount for nozzle',
  'o ring spacer for battery cooling line',
  'rotary valve for thermal management module (tmm)',
  'seal for battery access panel',
  'side cover for water channel',
  'structural brackets & beams',
  'adapter for interior',
  'bearing cage for interior',
  'bracket for console',
  'cover for cell super control (csc)',
  'fastener for panel',
  'grommet-top post',
  'lever for air conditioner (ac)',
  'mount for hinge',
  'spring plate',
  'structural support for console',
  'air channel for mass air flow (maf) sensor',
  'air duct adapter for defroster',
  'automobile (gasoline)-fuel module',
  'automotive air register',
  'automotive brake pedal',
  'automotive bushing-bearing cover',
  'automotive cargo area-hook',
  'automotive chassis-bracket',
  'automotive connector-clip',
  'automotive connector-pin',
  'automotive console link-strip retainer',
  'automotive cover-bracket',
  'automotive cup holder-housing',
  'automotive door-lock cover',
  'automotive door-stopper',
  'automotive fr bumper-retainer',
  'automotive fuel delivery module (fdm)',
  'automotive fuel module-ec pump',
  'automotive fuel pump',
  'automotive fuel reservoir and flange',
  'automotive fuel supply system-filter box body',
  'automotive fuel supply system-flange',
  'automotive fuel supply system-holder',
  'automotive fuel tank-flange',
  'automotive grommet',
  'automotive instrument panel and console system-trim clip',
  'automotive motorcycle-key cover',
  'automotive rear fuel tank-baffle',
  'automotive retainer-fastener',
  'automotive seat-latch housing',
  'automotive sensor-drive cover, adapter',
  'automotive side bumper-fastener and support',
  'automotive spring cassette-housing',
  'automotive spring drive-cover',
  'automotive spring-sleeve',
  'automotive steering column control module (sccm)-button',
  'automotive webbing guide',
  'automotive window lift-cursor',
  'automotive-2w fuel delivery module (fdm)',
  'automotive-4 way headrest',
  'ball valve for engine',
  'base plate for seat cushion length adjustment (scla)',
  'battery module for electric powertrain',
  'bellow for suspension',
  'blade for wiper',
  'bobbin for fuel tank isolation valve (ftiv)',
  'bobbin for pressure control solenoid valve (pcsv)',
  'bobbin for starter',
  'body-clip',
  'boot for propeller shaft',
  'boot for steering/suspension',
  'bracket for battery pack cable routing',
  'bracket for cup holder',
  'bracket for filler pipe',
  'bracket for headlight grille',
  'braking motor system for automobile & transportation',
  'brushless fuel delivery module (fdm) for gasoline engine',
  'bumper for hood',
  'camshaft positioning sensor (cmps) for turbo engine',
  'cap for sunroof',
  'capless fuel supply system',
  'carrier plate for seat cushion length adjustment (scla)',
  'channel for glass run',
  'charging panel for electric vehicle (ev)',
  'clip for door lift',
  'collar spring for clutch',
  'connector for automotive video navigation (avn)',
  'connector for electric mobility (e-mobility)',
  'connector for engine cooling system',
  'connector for ignition',
  'constant velocity joint (cvj) rear boot for motorcycle',
  'control handle for exterior mirror',
  'cooling module for dual clutch transmission (dct)',
  'core lever for transmission',
  'counter bearing cap for sun visor',
  'cover for engine valve',
  'cover for sunroof',
  'cover seal for engine',
  'cup holder for interior',
  'defroster for electric vehicle (ev)',
  'diaphragm for drive shaft',
  'distance adjustment for head rest',
  'distribution plate for fuel cell stack',
  'drop gate for tailgate latch',
  'duct for air intake',
  'electrical header for steering',
  'emergency charger cable for electric vehicle (ev)',
  'end cap for battery module',
  'end cap for outer beltline seal (obls)',
  'fender bracket (rh/lh)',
  'filter for diesel exhaust fluid (def)',
  'fixation for battery pack cable',
  'flange holder for fuel pump',
  'floor mat retainer system',
  'fuse assembly protection box for under the hood (uth)',
  'gas generator for seat belt',
  'gasket for door mirror',
  'gear for seat adjuster',
  'grommet clip for door panel',
  'guide bushing for headrest',
  'guide for headlamp',
  'guide plate for seat length adjuster',
  'handphone holder for motorcycle',
  'height position sensor for vehicle',
  'high voltage (hv) connector for electric vehicle (ev) powertrain',
  'hinge for fuel lid',
  'hinge for panel truck',
  'holder for safety belt',
  'housing for airbag',
  'housing for battery pyro switch',
  'housing for brake bushing',
  'housing for convertible roof',
  'housing for intercooler tank',
  'housing for safety belt system',
  'inlet control valve (icv) for fuel supply system',
  'insulated cover of electric vehicle (ev) charger',
  'latch for society of automotive engineers (sae) connector',
  'lens barrel for automotive compact camera module (ccm)',
  'linear actuator for two wheeler',
  'liner for floor',
  'lithium ion battery separator (libs) for plug-in hybrid electric vehicle (phev)',
  'lithium-ion battery separator (libs) for electric vehicle (ev)',
  'locknut for railway',
  'louver for truck',
  'middle gear for throttle body',
  'mini driver for power seat',
  'mirror for rearview',
  'motor housings & covers (traction motors)',
  'motor stator for electric cooling pump',
  'oil pan for hybrid transmission',
  'outer belt line seal (obls) for door',
  'outlet for intercooler',
  'pad for instrument panel (ip)',
  'partial hybrid electric vehicle (phev)',
  'pedals & gear shift systems',
  'pedestrian protection bracket',
  'pedestrian protection bracket for bumper',
  'powertrain-service cover',
  'protective cap for electric mobility',
  'pushrod retainer for plug-in hybrid electric vehicle (phev)',
  'quick connector (battery thermal management)',
  'rebound bumper for suspension',
  'resonator for engine',
  'sail for roof load carrying',
  'seal for bumper',
  'seal for seat recliner',
  'seat belt guide & pillar loop',
  'seat belt retractor',
  'seat belt-web guide',
  'selector shift actuator (ssa) for double clutch transmission (dct)',
  'sensor housing for fuel pump rotor',
  'shell for headrest',
  'side cover for dual clutch transmission (dct)',
  'skin for instrument panel (ip)',
  'skirt fairing for trunk body',
  'sleeve for accelerator pedal',
  'slider for headrest',
  'speed sensor for turbocharged truck',
  'spring element for seat cushion length adjustment (scla)',
  'spring side bearing for automotive',
  'steering column-eccentric disc',
  'strut for trunk door',
  'substrate for armrest',
  'support for seat motor',
  'support yoke for rack and pinion (r&p)',
  'temperature sensor for electric vehicle (ev) battery',
  'thumb wheel for air conditioner (ac)',
  'traction inverter for electric truck',
  'travel restrictor for chassis',
  'travel stop for belt tensioner',
  'trim for overhead console (ohc)',
  'trim for seat rail',
  'trunk components',
  'tube for air suspension',
  'turn signal-shaft base',
  'web sense retractor for seat belt',
  'wiper arm',
  'active grille',
  'adas',
  'ags vanes',
  'aircraft',
  'airspring',
  'axial flux motor stator housing',
  'bearing for center console',
  'belt bracket for door trim panel',
  'bin mat for console',
  'bonnet',
  'brake pads',
  'bumper',
  'cac',
  'cap for distributor',
  'cap for pull handle',
  'carrier plate',
  'chc',
  'clip for roof bar',
  'coolant',
  'coolant hose',
  'coolant hoses',
  'coolant pipes',
  'coolant tube',
  'coolant tubes',
  'coolant tubing',
  'cooling',
  'cooling hoses',
  'cooling line',
  'cooling lines',
  'cooling pipes',
  'cooling tubes',
  'core for air filter',
  'corner mold',
  'cowl vent grill',
  'cyclinderhead covers',
  'cylindehead cover',
  'dashboard',
  'dynamic weather seal',
  'electric motor',
  'emotor',
  'e-motor',
  'engine cover',
  'engine mounts',
  'engine parts',
  'epb gears',
  'exterior weatherable',
  'fascia brackets',
  'fcv',
  'fenders',
  'flux capacitor',
  'front end module',
  'fuel flange',
  'fuel flanges',
  'fuel pomp',
  'fuel pump impeller',
  'fuel*pump*impeller',
  'glass run channel',
  'glove box',
  'grae for motor mounts',
  'grc',
  'grc foot',
  'grc lip',
  'grill vent part',
  'head cover',
  'head lamp house',
  'headlamp house',
  'headlight',
  'headrest',
  'headrests',
  'heads up display',
  'horn fluid reservoir',
  'housing for battery gas exhaust',
  'immersed coolant',
  'immersed coolant hose',
  'immersion cooling',
  'infill',
  'interior trim',
  'ip frame',
  'motor spool',
  'multicontrol valves',
  'oil pan',
  'oilpan',
  'part for water pump-impeller',
  'plastic suspension bellows',
  'power battery cooling pipe',
  'power train',
  'powertrain connectors',
  'propulsion cooling',
  'radiator',
  'radiator end tank',
  'raiator',
  'rast 2,5 and 5 connectors',
  'rocker cover',
  'rocker cover oil',
  'seat bolster',
  'seat cover box',
  'seat cushion',
  'seat head cover box',
  'slipcoat',
  'spoiler',
  'stator busbar',
  'strut bellow',
  'strut bumper',
  'suite for air-intake manifold',
  'suspension',
  'suspension belllow',
  'suspension bellow',
  'suspension bellows',
  'suspensions bellow',
  'suspsension bellow',
  'tailgate',
  'tailgate housing',
  'tailgate tube housing',
  'thermal management',
  'thermal management module',
  'thermal management valve',
  'thermo management housing',
  'thermo managment systems',
  'tmm',
  'under - the - hood ( uth )',
  'upper frame for console',
  'vent grill',
  'visible interior parts',
  'washer-m6 bolt',
  'wheel speed',
  'electrical cars',
  'fuel cap',
  'tailgate protective tube housing',
  'tailgate spring sleeve',
  'cap for fuel valve',
  'auto seat head cover box',
  'automotive trunk',
  'automotive seating',
  'cap for fuel module',
  'crossbeam for automotive and transportation',
  'auto',
  'automotive',
  'back door plate for automotive & transportation',
  'automotive headset cover box',
  'back cover for automotive & transportation',
  'ev coolant hose',
  'flange for fuel module',
  'housing for a tailgate spring',
  'cvj boots',
  'oil filter for automotive & transportation',
  'ev connector',
  'automotive camera base',
  'active grille shutter',
  'under-the-hood (uth)',
  'head lamp housing',
  'automotive camera mount',
  'ev electric motor',
  'auto camera base',
  'cap for fuel tank',
  'cylinder head cover',
  'engine mount',
  'air intake manifold',
  'car cross beams',
  'auto application film',
  'ev cooling hoses',
  'automotive seat head cover box',
  'automotive seat head box',
  'tailgate protective housing',
  'adas camera bracket',
  'camshafts',
  'ev charge insulation',
  'cross car beam',
  'ev immersed coolant hose',
  'e-vehicle connector',
  'adas windshield bracket',
  '2k injection molding skin (air bag cover, center consoles, instrument panels, doors, pillars)',
  'cap for fuel vapor valve',
  '5g antenna ( adas )',
  'tube housing for tailgate',
  'car camera',
  'bumper beam',
  'car trunk',
  'adas front camera heaters',
  'cvj boot',
  'ev charger station frame',
  'automotive housing',
  'seal for headlights',
  'ev charger',
  'gasoline cap',
  'passenger wagon interior components',
  'filter for automatic transmission fluid (atf)',
  'ev',
  'low pressure tank for automotive & transportation',
  'headlight guard',
  '3-way coolant valve for automotive & transportation',
  'bus - bar for batteries',
  'sump filter for automotive transmission',
  'electric vehicle connector',
  'automotive water pump-impeller',
  'air intake manifolds for auto',
  'fuel tank',
  'housing for gasoline particulate filter ( gpf ) pressure sensor',
  'auto seating headrest',
  'latch for tailgate',
  'auto exterior roof extender',
  'filter for automatic transmission fluid ( atf )',
  'fuel cap for automotive fuel',
  'electrical vehicle connector',
  'on-board charger ( obc ) in ev',
  'bumper for crankshaft pulley isolator',
  'ev charging',
  'seat trim',
  'auto seat headrest',
  'window crank for automotive & transportation',
  'wall box application in ev charging station',
  'electrical vehicle cooling hose',
  'car roof',
  'automotive seat cover',

In [199]:
all_apps_industries = []
for ind in app_industry_data_cleaned:
    if ind=='not mapped':
        all_apps_industries.append((app, None))
    else:
        for app in app_industry_data_cleaned[ind]:
            all_apps_industries.append((app, ind))

all_apps_industries

[('connection ring for natural glove', 'medical & pharma'),
 ('autoinjector-anaphylaxis', 'medical & pharma'),
 ('autoinjector-retraction assembly', 'medical & pharma'),
 ('clamp for feeding catheter', 'medical & pharma'),
 ('dispension monitoring for diabetes pharmaceutical preparation',
  'medical & pharma'),
 ('dose button for insulin pen', 'medical & pharma'),
 ('drug delivery systems', 'medical & pharma'),
 ('handle for flexible endoscopy', 'medical & pharma'),
 ('hospital diagnostics & imaging', 'medical & pharma'),
 ('metered dose inhaler (mdi)-dose counter', 'medical & pharma'),
 ('plunger for intra ocular lens (iol)', 'medical & pharma'),
 ('power transmission for metered dose inhaler (mdi)', 'medical & pharma'),
 ('rod for orthopedic sizing device', 'medical & pharma'),
 ('hips implant', 'medical & pharma'),
 ('syringe stopper', 'medical & pharma'),
 ('prosthetic dog ear', 'medical & pharma'),
 ('hip implant', 'medical & pharma'),
 ('orthopedic implant', 'medical & pharma'),
 ('peristaltic pump gears', 'medical & pharma'),
 ('peristaltic tub', 'medical & pharma'),
 ('housing in a medical', 'medical & pharma'),
 ('cap for laboratory glass bottle', 'medical & pharma'),
 ('peristaltic tubing', 'medical & pharma'),
 ('dental part', 'medical & pharma'),
 ('glucose monitor', 'medical & pharma'),
 ('drug delivery', 'medical & pharma'),
 ('metered dose counter', 'medical & pharma'),
 ('cryogenic', 'medical & pharma'),
 ('dental', 'medical & pharma'),
 ('screw in injection device', 'medical & pharma'),
 ('drug elution', 'medical & pharma'),
 ('peristaltic pump', 'medical & pharma'),
 ('implanted medical devices', 'medical & pharma'),
 ('medical devices', 'medical & pharma'),
 ('insulin pen', 'medical & pharma'),
 ('wearable insulin pump', 'medical & pharma'),
 ('auto-injector', 'medical & pharma'),
 ('wearable pump', 'medical & pharma'),
 ('plunger stopper for anesthesia syringe', 'medical & pharma'),
 ('drug delivery device', 'medical & pharma'),
 ('autoinjectors that is a good sliding partner', 'medical & pharma'),
 ('lead screws in autoinjectors', 'medical & pharma'),
 ('healtcare', 'medical & pharma'),
 ('hip replacement', 'medical & pharma'),
 ('x-ray', 'medical & pharma'),
 ('connector port for iv bag', 'medical & pharma'),
 ('implantable', 'medical & pharma'),
 ('controlled release of drugs', 'medical & pharma'),
 ('autoinjector pen plunger', 'medical & pharma'),
 ('knees implant', 'medical & pharma'),
 ('autoinjectors', 'medical & pharma'),
 ('implant', 'medical & pharma'),
 ('insulin pump', 'medical & pharma'),
 ('mdi valve', 'medical & pharma'),
 ('peristaltic pump tubing', 'medical & pharma'),
 ('iv bag', 'medical & pharma'),
 ('pharma drug delivery', 'medical & pharma'),
 ('insulin injector pen', 'medical & pharma'),
 ('medical implant', 'medical & pharma'),
 ('intravenous bag', 'medical & pharma'),
 ('autoinjector', 'medical & pharma'),
 ('primary drug container', 'medical & pharma'),
 ('pipette filter', 'medical & pharma'),
 ('filter for pipette', 'medical & pharma'),
 ('body implant', 'medical & pharma'),
 ('knee replacement', 'medical & pharma'),
 ('connector port for intravenous bag', 'medical & pharma'),
 ('acetabular cup', 'medical & pharma'),
 ('elastomer connector port for intravenous bag', 'medical & pharma'),
 ('box for specimen collection', 'consumer goods'),
 ('sprayers-throat tubes, nebulization inserts, joints', 'consumer goods'),
 ('tube for disinfection cabinet', 'consumer goods'),
 ('guide for paper transport', 'consumer goods'),
 ('remote control for rudder', 'consumer goods'),
 ('tire and rim association (tra) compliant wheel rim for all terrain vehicle (atv)',
  'consumer goods'),
 ('wheel rim for gravel bike', 'consumer goods'),
 ('accumulator for water pump', 'consumer goods'),
 ('actuator for aerosol valve', 'consumer goods'),
 ('cassette stove-valve', 'consumer goods'),
 ('clip for nail gun', 'consumer goods'),
 ('clip for vine', 'consumer goods'),
 ('end cap cover for gear', 'consumer goods'),
 ('faucet-valve', 'consumer goods'),
 ('pumping unit for dispenser', 'consumer goods'),
 ('support for conveyor belt', 'consumer goods'),
 ('"aqua pro" gear program', 'consumer goods'),
 ('blade holder for ice hockey shoes', 'consumer goods'),
 ('valve for cosmetic', 'consumer goods'),
 ('wire guides, clamps, clips, collars, buttons, guides', 'consumer goods'),
 ('pinch clamp for lab use', 'consumer goods'),
 ('back for chair', 'consumer goods'),
 ('back frame for office chair', 'consumer goods'),
 ('back lower portion for office chair', 'consumer goods'),
 ('bearing for furniture', 'consumer goods'),
 ('brewing system-dispenser button', 'consumer goods'),
 ('buckle and shoes', 'consumer goods'),
 ('button for appliance', 'consumer goods'),
 ("children's carriage-gear", 'consumer goods'),
 ('consumer filtration', 'consumer goods'),
 ('cover for dishwasher impeller', 'consumer goods'),
 ('cylinder for lock', 'consumer goods'),
 ('damper for sunglass compartment', 'consumer goods'),
 ('dishwasher-rack clips', 'consumer goods'),
 ('dishwasher-roller', 'consumer goods'),
 ('driving bridge for beard and hair trimmer', 'consumer goods'),
 ('filling valve for toilet flushing mechanism', 'consumer goods'),
 ('fishing reel', 'consumer goods'),
 ('flip tines for dishwasher', 'consumer goods'),
 ('front plate for grease free coffee brewing unit', 'consumer goods'),
 ('furniture-gear', 'consumer goods'),
 ('gear box for washing machine transmission', 'consumer goods'),
 ('gear for window shade', 'consumer goods'),
 ('gear for window shade cable guide', 'consumer goods'),
 ('gearbox for washing machine', 'consumer goods'),
 ('grip for appliance', 'consumer goods'),
 ('guide rail for furniture', 'consumer goods'),
 ('holding structure for camera', 'consumer goods'),
 ('housing for dishwasher', 'consumer goods'),
 ('impeller for oven', 'consumer goods'),
 ('inlet valve for dishwasher', 'consumer goods'),
 ('insert for razor handle', 'consumer goods'),
 ('joint for baby pram', 'consumer goods'),
 ('lawn trimmer-cable drum housing and cover', 'consumer goods'),
 ('leveling leg for dishwasher leak pan', 'consumer goods'),
 ('lid lock for washing machine', 'consumer goods'),
 ('lock for home door', 'consumer goods'),
 ('lower rack clip for dishwasher', 'consumer goods'),
 ('mascara-stick', 'consumer goods'),
 ('plug for coffee machine brewing unit', 'consumer goods'),
 ('pole for ski', 'consumer goods'),
 ('refrigerator-food drawer roller', 'consumer goods'),
 ('roller for dishwasher', 'consumer goods'),
 ('seatback frame for hybrid chair', 'consumer goods'),
 ('shifter base for washing machine', 'consumer goods'),
 ('slider for vacuum cleaner', 'consumer goods'),
 ('sliding for dishwasher', 'consumer goods'),
 ('spray valve for perfume', 'consumer goods'),
 ('strike door plate for dishwasher', 'consumer goods'),
 ('sun umbrella articulation', 'consumer goods'),
 ('support for saddle storage system', 'consumer goods'),
 ('television parts', 'consumer goods'),
 ('toilet flushing units', 'consumer goods'),
 ('toothbrush tube base for oral care', 'consumer goods'),
 ('torsion plate for footwear', 'consumer goods'),
 ('vacuum cleaner for pool', 'consumer goods'),
 ('vacuum cleaner-gear', 'consumer goods'),
 ('valve for drink machine', 'consumer goods'),
 ('water tank seal for wet dry vacuum cleaner', 'consumer goods'),
 ('water valve for refrigerator', 'consumer goods'),
 ('wingnut for dishwasher', 'consumer goods'),
 ('washing machine pump', 'consumer goods'),
 ('electric stove', 'consumer goods'),
 ('cooker handle', 'consumer goods'),
 ('refrigerator', 'consumer goods'),
 ('beer', 'consumer goods'),
 ('beer machine part', 'consumer goods'),
 ('paint can nozzle', 'consumer goods'),
 ('microwave oven', 'consumer goods'),
 ('toothbrushes', 'consumer goods'),
 ('beer machine', 'consumer goods'),
 ('part in beer machine', 'consumer goods'),
 ('footwear', 'consumer goods'),
 ('stocking', 'consumer goods'),
 ('toilet seat cover', 'consumer goods'),
 ('copy machine', 'consumer goods'),
 ('paint can nozzles', 'consumer goods'),
 ('baby stroller for consumer goods', 'consumer goods'),
 ('cap for lipstick', 'consumer goods'),
 ('baby chair for consumer goods', 'consumer goods'),
 ('microwave oven component', 'consumer goods'),
 ('part in a beer machine', 'consumer goods'),
 ('running shoes', 'consumer goods'),
 ('baking trays', 'consumer goods'),
 ('cap for refrigerator water filter', 'consumer goods'),
 ('ski bindings', 'consumer goods'),
 ('hinge for consumer goods furniture', 'consumer goods'),
 ('microwave component', 'consumer goods'),
 ('pump in washing machine', 'consumer goods'),
 ('beer keg component', 'consumer goods'),
 ('bicycle tyre', 'consumer goods'),
 ('motor housing for robot vacuum cleaner', 'consumer goods'),
 ('beer machine component', 'consumer goods'),
 ('part in a beer keg', 'consumer goods'),
 ('washing machine', 'consumer goods'),
 ('toys', 'consumer goods'),
 ('bread pan', 'consumer goods'),
 ('lego block', 'consumer goods'),
 ('hair dryer', 'consumer goods'),
 ('part for slingshot', 'consumer goods'),
 ('coffee maker', 'consumer goods'),
 ('beer kegs', 'consumer goods'),
 ('consumer electronics', 'consumer goods'),
 ('part on a beer machine', 'consumer goods'),
 ('diaphragm for consumer goods pump', 'consumer goods'),
 ('sunglasses bin', 'consumer goods'),
 ('beer keg part', 'consumer goods'),
 ('foot pedal for floor vacuum', 'consumer goods'),
 ('gear for robot vacuum', 'consumer goods'),
 ('nozzle for a paint can', 'consumer goods'),
 ('connector for consumer goods', 'consumer goods'),
 ('toilet seats', 'consumer goods'),
 ('beer keg pump', 'consumer goods'),
 ('dispenser slider for coffee machine', 'consumer goods'),
 ('office chair', 'consumer goods'),
 ('toy gears', 'consumer goods'),
 ('footwear midsole', 'consumer goods'),
 ('diapers', 'consumer goods'),
 ('tooth brush', 'consumer goods'),
 ('wear', 'consumer goods'),
 ('water filter for homewhole', 'consumer goods'),
 ('steam bucket', 'consumer goods'),
 ('part of a beer keg', 'consumer goods'),
 ('toothbrush', 'consumer goods'),
 ('microwave oven part', 'consumer goods'),
 ('artificial cow hoof', 'consumer goods'),
 ('dishwasher', 'consumer goods'),
 ('beer keg', 'consumer goods'),
 ('wig', 'consumer goods'),
 ('soda caps liner', 'consumer goods'),
 ('toilet seat covers', 'consumer goods'),
 ('microwave', 'consumer goods'),
 ('part for a beer machine', 'consumer goods'),
 ('footware', 'consumer goods'),
 ('pump application in a washing machine', 'consumer goods'),
 ('sausage packaging', 'consumer goods'),
 ('water purifier', 'consumer goods'),
 ('appliance', 'consumer goods'),
 ('gas appliance', 'consumer goods'),
 ('bathroom faucet', 'consumer goods'),
 ('consumer', 'consumer goods'),
 ('washing machine transmission gear', 'consumer goods'),
 ('furniture', 'consumer goods'),
 ('front plate for tasmanian devil free coffee brewing unit',
  'consumer goods'),
 ('shower cartridge valve', 'consumer goods'),
 ('stove knob', 'consumer goods'),
 ('cell phone case', 'consumer goods'),
 ('bracket for lawn mower', 'consumer goods'),
 ('soft-touch toothbrush overmolding', 'consumer goods'),
 ('cell phone cover', 'consumer goods'),
 ('loud speaker grill', 'consumer goods'),
 ('consumer electronics antenna', 'consumer goods'),
 ('pump in a washing machine', 'consumer goods'),
 ('push on bushing for dishwasher', 'consumer goods'),
 ('flushing systems', 'consumer goods'),
 ('fishing line', 'consumer goods'),
 ('door frame - hinges - door lock - handle - knobs', 'consumer goods'),
 ('kitchen ovens', 'consumer goods'),
 ('anti-slip mat for door storage box', 'automotive & transportation'),
 ('backlit knob-actuator', 'automotive & transportation'),
 ('carrier for back rest', 'automotive & transportation'),
 ('clip for recliner', 'automotive & transportation'),
 ('duct for air conditioner (ac)', 'automotive & transportation'),
 ('key lock', 'automotive & transportation'),
 ('mirror for door', 'automotive & transportation'),
 ('adjustment for lighting', 'automotive & transportation'),
 ('housing for light control', 'automotive & transportation'),
 ('housing for lighting sensor', 'automotive & transportation'),
 ('plate for backlight', 'automotive & transportation'),
 ('protective cap for electronical & electronics',
  'automotive & transportation'),
 ('structural for smart phone station (sps) display',
  'automotive & transportation'),
 ('support for electromagnetic compatibility (emc) filter',
  'automotive & transportation'),
 ('terminal for battery fuse', 'automotive & transportation'),
 ('washer nozzle for camera', 'automotive & transportation'),
 ('bracket for air duct', 'automotive & transportation'),
 ('clip for stud mount', 'automotive & transportation'),
 ('cold air hose for coupling box cooling', 'automotive & transportation'),
 ('connector for control power transformer (cpt)',
  'automotive & transportation'),
 ('connector for water coolant circuit', 'automotive & transportation'),
 ('cover cap for gear drive', 'automotive & transportation'),
 ('fastener for fuel pipe', 'automotive & transportation'),
 ('holder for thermal management module (tmm)', 'automotive & transportation'),
 ('isolator for spring cup', 'automotive & transportation'),
 ('mount for nozzle', 'automotive & transportation'),
 ('o ring spacer for battery cooling line', 'automotive & transportation'),
 ('rotary valve for thermal management module (tmm)',
  'automotive & transportation'),
 ('seal for battery access panel', 'automotive & transportation'),
 ('side cover for water channel', 'automotive & transportation'),
 ('structural brackets & beams', 'automotive & transportation'),
 ('adapter for interior', 'automotive & transportation'),
 ('bearing cage for interior', 'automotive & transportation'),
 ('bracket for console', 'automotive & transportation'),
 ('cover for cell super control (csc)', 'automotive & transportation'),
 ('fastener for panel', 'automotive & transportation'),
 ('grommet-top post', 'automotive & transportation'),
 ('lever for air conditioner (ac)', 'automotive & transportation'),
 ('mount for hinge', 'automotive & transportation'),
 ('spring plate', 'automotive & transportation'),
 ('structural support for console', 'automotive & transportation'),
 ('air channel for mass air flow (maf) sensor', 'automotive & transportation'),
 ('air duct adapter for defroster', 'automotive & transportation'),
 ('automobile (gasoline)-fuel module', 'automotive & transportation'),
 ('automotive air register', 'automotive & transportation'),
 ('automotive brake pedal', 'automotive & transportation'),
 ('automotive bushing-bearing cover', 'automotive & transportation'),
 ('automotive cargo area-hook', 'automotive & transportation'),
 ('automotive chassis-bracket', 'automotive & transportation'),
 ('automotive connector-clip', 'automotive & transportation'),
 ('automotive connector-pin', 'automotive & transportation'),
 ('automotive console link-strip retainer', 'automotive & transportation'),
 ('automotive cover-bracket', 'automotive & transportation'),
 ('automotive cup holder-housing', 'automotive & transportation'),
 ('automotive door-lock cover', 'automotive & transportation'),
 ('automotive door-stopper', 'automotive & transportation'),
 ('automotive fr bumper-retainer', 'automotive & transportation'),
 ('automotive fuel delivery module (fdm)', 'automotive & transportation'),
 ('automotive fuel module-ec pump', 'automotive & transportation'),
 ('automotive fuel pump', 'automotive & transportation'),
 ('automotive fuel reservoir and flange', 'automotive & transportation'),
 ('automotive fuel supply system-filter box body',
  'automotive & transportation'),
 ('automotive fuel supply system-flange', 'automotive & transportation'),
 ('automotive fuel supply system-holder', 'automotive & transportation'),
 ('automotive fuel tank-flange', 'automotive & transportation'),
 ('automotive grommet', 'automotive & transportation'),
 ('automotive instrument panel and console system-trim clip',
  'automotive & transportation'),
 ('automotive motorcycle-key cover', 'automotive & transportation'),
 ('automotive rear fuel tank-baffle', 'automotive & transportation'),
 ('automotive retainer-fastener', 'automotive & transportation'),
 ('automotive seat-latch housing', 'automotive & transportation'),
 ('automotive sensor-drive cover, adapter', 'automotive & transportation'),
 ('automotive side bumper-fastener and support',
  'automotive & transportation'),
 ('automotive spring cassette-housing', 'automotive & transportation'),
 ('automotive spring drive-cover', 'automotive & transportation'),
 ('automotive spring-sleeve', 'automotive & transportation'),
 ('automotive steering column control module (sccm)-button',
  'automotive & transportation'),
 ('automotive webbing guide', 'automotive & transportation'),
 ('automotive window lift-cursor', 'automotive & transportation'),
 ('automotive-2w fuel delivery module (fdm)', 'automotive & transportation'),
 ('automotive-4 way headrest', 'automotive & transportation'),
 ('ball valve for engine', 'automotive & transportation'),
 ('base plate for seat cushion length adjustment (scla)',
  'automotive & transportation'),
 ('battery module for electric powertrain', 'automotive & transportation'),
 ('bellow for suspension', 'automotive & transportation'),
 ('blade for wiper', 'automotive & transportation'),
 ('bobbin for fuel tank isolation valve (ftiv)',
  'automotive & transportation'),
 ('bobbin for pressure control solenoid valve (pcsv)',
  'automotive & transportation'),
 ('bobbin for starter', 'automotive & transportation'),
 ('body-clip', 'automotive & transportation'),
 ('boot for propeller shaft', 'automotive & transportation'),
 ('boot for steering/suspension', 'automotive & transportation'),
 ('bracket for battery pack cable routing', 'automotive & transportation'),
 ('bracket for cup holder', 'automotive & transportation'),
 ('bracket for filler pipe', 'automotive & transportation'),
 ('bracket for headlight grille', 'automotive & transportation'),
 ('braking motor system for automobile & transportation',
  'automotive & transportation'),
 ('brushless fuel delivery module (fdm) for gasoline engine',
  'automotive & transportation'),
 ('bumper for hood', 'automotive & transportation'),
 ('camshaft positioning sensor (cmps) for turbo engine',
  'automotive & transportation'),
 ('cap for sunroof', 'automotive & transportation'),
 ('capless fuel supply system', 'automotive & transportation'),
 ('carrier plate for seat cushion length adjustment (scla)',
  'automotive & transportation'),
 ('channel for glass run', 'automotive & transportation'),
 ('charging panel for electric vehicle (ev)', 'automotive & transportation'),
 ('clip for door lift', 'automotive & transportation'),
 ('collar spring for clutch', 'automotive & transportation'),
 ('connector for automotive video navigation (avn)',
  'automotive & transportation'),
 ('connector for electric mobility (e-mobility)',
  'automotive & transportation'),
 ('connector for engine cooling system', 'automotive & transportation'),
 ('connector for ignition', 'automotive & transportation'),
 ('constant velocity joint (cvj) rear boot for motorcycle',
  'automotive & transportation'),
 ('control handle for exterior mirror', 'automotive & transportation'),
 ('cooling module for dual clutch transmission (dct)',
  'automotive & transportation'),
 ('core lever for transmission', 'automotive & transportation'),
 ('counter bearing cap for sun visor', 'automotive & transportation'),
 ('cover for engine valve', 'automotive & transportation'),
 ('cover for sunroof', 'automotive & transportation'),
 ('cover seal for engine', 'automotive & transportation'),
 ('cup holder for interior', 'automotive & transportation'),
 ('defroster for electric vehicle (ev)', 'automotive & transportation'),
 ('diaphragm for drive shaft', 'automotive & transportation'),

### Region

In [200]:
am_region_df = am_region_df.fillna('')
am_region_data = am_region_df.to_dict('list')
am_region_data

{'Country': ['United States',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'Colombia',
  'Chile',
  'Peru',
  'Venezuela',
  'Ecuador',
  'Bolivia',
  'Paraguay',
  'Uruguay',
  'Guyana',
  'Suriname',
  'Belize',
  'Costa Rica',
  'El Salvador',
  'Guatemala',
  'Honduras',
  'Nicaragua',
  'Panama',
  'Cuba',
  'Haiti',
  'Dominican Republic',
  'Jamaica',
  'Trinidad and Tobago',
  'Bahamas',
  'Barbados',
  'Saint Lucia',
  'USA',
  'US',
  'CA',
  'MX',
  'BR',
  'AR'],
 'State': ['California',
  'Texas',
  'New York',
  'Florida',
  'Illinois',
  'Pennsylvania',
  'Ohio',
  'Georgia, U.S.',
  'North Carolina',
  'Michigan',
  'Ontario',
  'Quebec',
  'British Columbia',
  'Alberta',
  'Nova Scotia',
  'Jalisco',
  'Nuevo León',
  'São Paulo',
  'Rio de Janeiro',
  'Minas Gerais',
  'Buenos Aires',
  'Córdoba',
  'Santa Fe',
  'Antioquia',
  'Valle del Cauca',
  'Lima',
  'Cusco',
  'Santiago Metropolitan',
  'Valparaíso',
  'Mendoza',
  'NY',
  'TX',
  'BC',
  '',
  '',
  ''],
 'City': ['New York City',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Toronto',
  'Montreal',
  'Vancouver',
  'Calgary',
  'Edmonton',
  'Mexico City',
  'Guadalajara',
  'Monterrey',
  'São Paulo',
  'Rio de Janeiro',
  'Buenos Aires',
  'Córdoba',
  'Rosario',
  'Bogotá',
  'Medellín',
  'Lima',
  'Santiago',
  'Quito',
  'Caracas',
  'Havana',
  'San Marino, California',
  '',
  '',
  '',
  '',
  ''],
 'Continent': ['americas',
  'north america',
  'south america',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '']}

In [201]:
am_region_data_cleaned = {}
for i in am_region_data:
    am_region_data_cleaned[i.lower()] = [re.sub("(\s+)", " ", x.strip().lower()) for x in am_region_data[i] if x]

am_region_data_cleaned

{'country': ['united states',
  'canada',
  'mexico',
  'brazil',
  'argentina',
  'colombia',
  'chile',
  'peru',
  'venezuela',
  'ecuador',
  'bolivia',
  'paraguay',
  'uruguay',
  'guyana',
  'suriname',
  'belize',
  'costa rica',
  'el salvador',
  'guatemala',
  'honduras',
  'nicaragua',
  'panama',
  'cuba',
  'haiti',
  'dominican republic',
  'jamaica',
  'trinidad and tobago',
  'bahamas',
  'barbados',
  'saint lucia',
  'usa',
  'us',
  'ca',
  'mx',
  'br',
  'ar'],
 'state': ['california',
  'texas',
  'new york',
  'florida',
  'illinois',
  'pennsylvania',
  'ohio',
  'georgia, u.s.',
  'north carolina',
  'michigan',
  'ontario',
  'quebec',
  'british columbia',
  'alberta',
  'nova scotia',
  'jalisco',
  'nuevo león',
  'são paulo',
  'rio de janeiro',
  'minas gerais',
  'buenos aires',
  'córdoba',
  'santa fe',
  'antioquia',
  'valle del cauca',
  'lima',
  'cusco',
  'santiago metropolitan',
  'valparaíso',
  'mendoza',
  'ny',
  'tx',
  'bc'],
 'city': ['new york city',
  'los angeles',
  'chicago',
  'houston',
  'phoenix',
  'philadelphia',
  'san antonio',
  'san diego',
  'dallas',
  'san jose',
  'toronto',
  'montreal',
  'vancouver',
  'calgary',
  'edmonton',
  'mexico city',
  'guadalajara',
  'monterrey',
  'são paulo',
  'rio de janeiro',
  'buenos aires',
  'córdoba',
  'rosario',
  'bogotá',
  'medellín',
  'lima',
  'santiago',
  'quito',
  'caracas',
  'havana',
  'san marino, california'],
 'continent': ['americas', 'north america', 'south america']}

In [202]:
emea_region_df = emea_region_df.fillna('')
emea_region_data = emea_region_df.to_dict('list')
emea_region_data

{'Country': ['France',
  'Germany',
  'Italy',
  'Spain',
  'United Kingdom',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Greece',
  'Portugal',
  'Turkey',
  'Israel',
  'Saudi Arabia',
  'United Arab Emirates',
  'Qatar',
  'Kuwait',
  'Oman',
  'Bahrain',
  'Jordan',
  'Lebanon',
  'Egypt',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Morocco',
  'UK',
  'UAE',
  'FR',
  'NL',
  'SA',
  'ZA',
  'DE',
  'GB',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Belarus',
  'Benin',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cameroon',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Comoros',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Djibouti',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Faroe Islands',
  'Gabon',
  'Gambia',
  'Ghana',
  'Gibraltar',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Hungary',
  'Iceland',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle Of Man',
  'Ivory Coast',
  'Jersey',
  'Latvia',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Mozambique',
  'Namibia',
  'Niger',
  'Palestine',
  'Poland',
  'Romania',
  'Rwanda',
  'San Marino',
  'Sao Tome & Principe',
  'Senegal',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'Sudan',
  'Swaziland',
  'Syria',
  'Tanzania',
  'Togo',
  'Tunisia',
  'Uganda',
  'Ukraine',
  'Vatican City',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'],
 'State': ['Bavaria',
  'Baden-Württemberg',
  'North Rhine-Westphalia',
  'Hesse',
  'Lower Saxony',
  'Rhineland-Palatinate',
  'Saxony',
  'Thuringia',
  'Brandenburg',
  'Berlin',
  'Hamburg',
  'Bremen',
  'Catalonia',
  'Andalusia',
  'Madrid',
  'Valencia',
  'Lombardy',
  'Sicily',
  'Tuscany',
  'Lazio',
  'Île-de-France',
  "Provence-Alpes-Côte d'Azur",
  'Auvergne-Rhône-Alpes',
  'Scotland',
  'Wales',
  'Northern Ireland',
  'Gauteng',
  'Western Cape',
  'Eastern Cape',
  'KwaZulu-Natal',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'City': ['Paris',
  'Berlin',
  'Rome',
  'Madrid',
  'London',
  'Amsterdam',
  'Brussels',
  'Zurich',
  'Vienna',
  'Stockholm',
  'Oslo',
  'Copenhagen',
  'Helsinki',
  'Athens',
  'Lisbon',
  'Istanbul',
  'Tel Aviv',
  'Riyadh',
  'Dubai',
  'Doha',
  'Kuwait City',
  'Muscat',
  'Manama',
  'Amman',
  'Beirut',
  'Cairo',
  'Johannesburg',
  'Lagos',
  'Nairobi',
  'Casablanca',
  'DXB',
  'frankfurt-iph',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'Continent': ['eu',
  'europe',
  'europe middle east africa',
  'emea',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '']}

In [203]:
emea_region_data_cleaned = {}
for i in emea_region_data:
    emea_region_data_cleaned[i.lower()] = [re.sub("(\s+)", " ", x.strip().lower()) for x in emea_region_data[i] if x]

emea_region_data_cleaned

{'country': ['france',
  'germany',
  'italy',
  'spain',
  'united kingdom',
  'netherlands',
  'belgium',
  'switzerland',
  'austria',
  'sweden',
  'norway',
  'denmark',
  'finland',
  'greece',
  'portugal',
  'turkey',
  'israel',
  'saudi arabia',
  'united arab emirates',
  'qatar',
  'kuwait',
  'oman',
  'bahrain',
  'jordan',
  'lebanon',
  'egypt',
  'south africa',
  'nigeria',
  'kenya',
  'morocco',
  'uk',
  'uae',
  'fr',
  'nl',
  'sa',
  'za',
  'de',
  'gb',
  'albania',
  'algeria',
  'andorra',
  'angola',
  'belarus',
  'benin',
  'bosnia and herzegovina',
  'botswana',
  'bulgaria',
  'burkina faso',
  'burundi',
  'cameroon',
  'cape verde',
  'central african republic',
  'chad',
  'comoros',
  'croatia',
  'cyprus',
  'czech republic',
  'democratic republic of the congo',
  'djibouti',
  'equatorial guinea',
  'eritrea',
  'estonia',
  'ethiopia',
  'faroe islands',
  'gabon',
  'gambia',
  'ghana',
  'gibraltar',
  'guernsey',
  'guinea',
  'guinea-bissau',
  'hungary',
  'iceland',
  'iran',
  'iraq',
  'ireland',
  'isle of man',
  'ivory coast',
  'jersey',
  'latvia',
  'lesotho',
  'liberia',
  'libya',
  'liechtenstein',
  'lithuania',
  'luxembourg',
  'macedonia',
  'madagascar',
  'malawi',
  'mali',
  'malta',
  'mauritania',
  'mauritius',
  'moldova',
  'monaco',
  'montenegro',
  'mozambique',
  'namibia',
  'niger',
  'palestine',
  'poland',
  'romania',
  'rwanda',
  'san marino',
  'sao tome & principe',
  'senegal',
  'serbia',
  'slovakia',
  'slovenia',
  'somalia',
  'sudan',
  'swaziland',
  'syria',
  'tanzania',
  'togo',
  'tunisia',
  'uganda',
  'ukraine',
  'vatican city',
  'western sahara',
  'yemen',
  'zambia',
  'zimbabwe'],
 'state': ['bavaria',
  'baden-württemberg',
  'north rhine-westphalia',
  'hesse',
  'lower saxony',
  'rhineland-palatinate',
  'saxony',
  'thuringia',
  'brandenburg',
  'berlin',
  'hamburg',
  'bremen',
  'catalonia',
  'andalusia',
  'madrid',
  'valencia',
  'lombardy',
  'sicily',
  'tuscany',
  'lazio',
  'île-de-france',
  "provence-alpes-côte d'azur",
  'auvergne-rhône-alpes',
  'scotland',
  'wales',
  'northern ireland',
  'gauteng',
  'western cape',
  'eastern cape',
  'kwazulu-natal'],
 'city': ['paris',
  'berlin',
  'rome',
  'madrid',
  'london',
  'amsterdam',
  'brussels',
  'zurich',
  'vienna',
  'stockholm',
  'oslo',
  'copenhagen',
  'helsinki',
  'athens',
  'lisbon',
  'istanbul',
  'tel aviv',
  'riyadh',
  'dubai',
  'doha',
  'kuwait city',
  'muscat',
  'manama',
  'amman',
  'beirut',
  'cairo',
  'johannesburg',
  'lagos',
  'nairobi',
  'casablanca',
  'dxb',
  'frankfurt-iph'],
 'continent': ['eu', 'europe', 'europe middle east africa', 'emea']}

In [204]:
ap_region_df = ap_region_df.fillna('')
ap_region_data = ap_region_df.to_dict('list')
ap_region_data

{'Country': ['Australia',
  'China',
  'India',
  'Japan',
  'South Korea',
  'Indonesia',
  'Malaysia',
  'New Zealand',
  'Philippines',
  'Singapore',
  'Thailand',
  'Vietnam',
  'Bangladesh',
  'Pakistan',
  'Sri Lanka',
  'Nepal',
  'Myanmar',
  'Cambodia',
  'Laos',
  'Brunei',
  'Mongolia',
  'Fiji',
  'Papua New Guinea',
  'Maldives',
  'Bhutan',
  'Timor-Leste',
  'Solomon Islands',
  'Vanuatu',
  'Samoa',
  'Tonga',
  'AUS',
  'CHN',
  'IND',
  'KOR',
  'JPN',
  'SGP',
  'NZ',
  'indian'],
 'State': ['New South Wales',
  'Victoria',
  'Queensland',
  'Western Australia',
  'Tasmania',
  'Maharashtra',
  'Karnataka',
  'Tamil Nadu',
  'Gujarat',
  'Beijing',
  'Shanghai',
  'Guangdong',
  'Sichuan',
  'Hokkaido',
  'Kyoto',
  'Osaka',
  'Seoul',
  'Busan',
  'Jakarta',
  'Bali',
  'Selangor',
  'Kuala Lumpur',
  'Auckland',
  'Wellington',
  'Manila',
  'Bangkok',
  'Ho Chi Minh City',
  'Hanoi',
  'Colombo',
  'Punjab',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'City': ['Sydney',
  'Melbourne',
  'Brisbane',
  'Perth',
  'Adelaide',
  'Mumbai',
  'Bangalore',
  'Chennai',
  'Ahmedabad',
  'Beijing',
  'Shanghai',
  'Guangzhou',
  'Shenzhen',
  'Tokyo',
  'Osaka',
  'Nagoya',
  'Seoul',
  'Busan',
  'Jakarta',
  'Surabaya',
  'Kuala Lumpur',
  'George Town',
  'Auckland',
  'Christchurch',
  'Manila',
  'Bangkok',
  'Ho Chi Minh City',
  'Hanoi',
  'Colombo',
  'Karachi',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'Continent': ['asia',
  'apac',
  'asia pacific',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '']}

In [205]:
ap_region_data_cleaned = {}
for i in ap_region_data:
    ap_region_data_cleaned[i.lower()] = [re.sub("(\s+)", " ", x.strip().lower()) for x in ap_region_data[i] if x]

ap_region_data_cleaned

{'country': ['australia',
  'china',
  'india',
  'japan',
  'south korea',
  'indonesia',
  'malaysia',
  'new zealand',
  'philippines',
  'singapore',
  'thailand',
  'vietnam',
  'bangladesh',
  'pakistan',
  'sri lanka',
  'nepal',
  'myanmar',
  'cambodia',
  'laos',
  'brunei',
  'mongolia',
  'fiji',
  'papua new guinea',
  'maldives',
  'bhutan',
  'timor-leste',
  'solomon islands',
  'vanuatu',
  'samoa',
  'tonga',
  'aus',
  'chn',
  'ind',
  'kor',
  'jpn',
  'sgp',
  'nz',
  'indian'],
 'state': ['new south wales',
  'victoria',
  'queensland',
  'western australia',
  'tasmania',
  'maharashtra',
  'karnataka',
  'tamil nadu',
  'gujarat',
  'beijing',
  'shanghai',
  'guangdong',
  'sichuan',
  'hokkaido',
  'kyoto',
  'osaka',
  'seoul',
  'busan',
  'jakarta',
  'bali',
  'selangor',
  'kuala lumpur',
  'auckland',
  'wellington',
  'manila',
  'bangkok',
  'ho chi minh city',
  'hanoi',
  'colombo',
  'punjab'],
 'city': ['sydney',
  'melbourne',
  'brisbane',
  'perth',
  'adelaide',
  'mumbai',
  'bangalore',
  'chennai',
  'ahmedabad',
  'beijing',
  'shanghai',
  'guangzhou',
  'shenzhen',
  'tokyo',
  'osaka',
  'nagoya',
  'seoul',
  'busan',
  'jakarta',
  'surabaya',
  'kuala lumpur',
  'george town',
  'auckland',
  'christchurch',
  'manila',
  'bangkok',
  'ho chi minh city',
  'hanoi',
  'colombo',
  'karachi'],
 'continent': ['asia', 'apac', 'asia pacific']}

In [206]:
region_abbr_list = []
imp_abbr = ['usa', 'us', 'ny', 'uk', 'uae', 'eu', 'aus', 'chn', 'ind', 'kor', 'jpn']
all_regions_data = {'continent': [], 'country': [], 'state': [], 'city': []}

for k in am_region_data_cleaned:
    for v in am_region_data_cleaned[k]:
        if len(v)<4 and v not in imp_abbr:
            region_abbr_list.append(v)
        else:
            all_regions_data[k].append((v, 'americas'))

for k in emea_region_data_cleaned:
    for v in emea_region_data_cleaned[k]:
        if len(v)<4 and v not in imp_abbr:
            region_abbr_list.append(v)
        else:
            all_regions_data[k].append((v, 'europe middle east africa'))

for k in ap_region_data_cleaned:
    for v in ap_region_data_cleaned[k]:
        if len(v)<4 and v not in imp_abbr:
            region_abbr_list.append(v)
        else:
            all_regions_data[k].append((v, 'asia pacific'))
            
region_abbr_list

['ca',
 'mx',
 'br',
 'ar',
 'tx',
 'bc',
 'fr',
 'nl',
 'sa',
 'za',
 'de',
 'gb',
 'dxb',
 'sgp',
 'nz']

In [207]:
all_regions_data

{'continent': [('americas', 'americas'),
  ('north america', 'americas'),
  ('south america', 'americas'),
  ('eu', 'europe middle east africa'),
  ('europe', 'europe middle east africa'),
  ('europe middle east africa', 'europe middle east africa'),
  ('emea', 'europe middle east africa'),
  ('asia', 'asia pacific'),
  ('apac', 'asia pacific'),
  ('asia pacific', 'asia pacific')],
 'country': [('united states', 'americas'),
  ('canada', 'americas'),
  ('mexico', 'americas'),
  ('brazil', 'americas'),
  ('argentina', 'americas'),
  ('colombia', 'americas'),
  ('chile', 'americas'),
  ('peru', 'americas'),
  ('venezuela', 'americas'),
  ('ecuador', 'americas'),
  ('bolivia', 'americas'),
  ('paraguay', 'americas'),
  ('uruguay', 'americas'),
  ('guyana', 'americas'),
  ('suriname', 'americas'),
  ('belize', 'americas'),
  ('costa rica', 'americas'),
  ('el salvador', 'americas'),
  ('guatemala', 'americas'),
  ('honduras', 'americas'),
  ('nicaragua', 'americas'),
  ('panama', 'americas'),
  ('cuba', 'americas'),
  ('haiti', 'americas'),
  ('dominican republic', 'americas'),
  ('jamaica', 'americas'),
  ('trinidad and tobago', 'americas'),
  ('bahamas', 'americas'),
  ('barbados', 'americas'),
  ('saint lucia', 'americas'),
  ('usa', 'americas'),
  ('us', 'americas'),
  ('france', 'europe middle east africa'),
  ('germany', 'europe middle east africa'),
  ('italy', 'europe middle east africa'),
  ('spain', 'europe middle east africa'),
  ('united kingdom', 'europe middle east africa'),
  ('netherlands', 'europe middle east africa'),
  ('belgium', 'europe middle east africa'),
  ('switzerland', 'europe middle east africa'),
  ('austria', 'europe middle east africa'),
  ('sweden', 'europe middle east africa'),
  ('norway', 'europe middle east africa'),
  ('denmark', 'europe middle east africa'),
  ('finland', 'europe middle east africa'),
  ('greece', 'europe middle east africa'),
  ('portugal', 'europe middle east africa'),
  ('turkey', 'europe middle east africa'),
  ('israel', 'europe middle east africa'),
  ('saudi arabia', 'europe middle east africa'),
  ('united arab emirates', 'europe middle east africa'),
  ('qatar', 'europe middle east africa'),
  ('kuwait', 'europe middle east africa'),
  ('oman', 'europe middle east africa'),
  ('bahrain', 'europe middle east africa'),
  ('jordan', 'europe middle east africa'),
  ('lebanon', 'europe middle east africa'),
  ('egypt', 'europe middle east africa'),
  ('south africa', 'europe middle east africa'),
  ('nigeria', 'europe middle east africa'),
  ('kenya', 'europe middle east africa'),
  ('morocco', 'europe middle east africa'),
  ('uk', 'europe middle east africa'),
  ('uae', 'europe middle east africa'),
  ('albania', 'europe middle east africa'),
  ('algeria', 'europe middle east africa'),
  ('andorra', 'europe middle east africa'),
  ('angola', 'europe middle east africa'),
  ('belarus', 'europe middle east africa'),
  ('benin', 'europe middle east africa'),
  ('bosnia and herzegovina', 'europe middle east africa'),
  ('botswana', 'europe middle east africa'),
  ('bulgaria', 'europe middle east africa'),
  ('burkina faso', 'europe middle east africa'),
  ('burundi', 'europe middle east africa'),
  ('cameroon', 'europe middle east africa'),
  ('cape verde', 'europe middle east africa'),
  ('central african republic', 'europe middle east africa'),
  ('chad', 'europe middle east africa'),
  ('comoros', 'europe middle east africa'),
  ('croatia', 'europe middle east africa'),
  ('cyprus', 'europe middle east africa'),
  ('czech republic', 'europe middle east africa'),
  ('democratic republic of the congo', 'europe middle east africa'),
  ('djibouti', 'europe middle east africa'),
  ('equatorial guinea', 'europe middle east africa'),
  ('eritrea', 'europe middle east africa'),
  ('estonia', 'europe middle east africa'),
  ('ethiopia', 'europe middle east africa'),
  ('faroe islands', 'europe middle east africa'),
  ('gabon', 'europe middle east africa'),
  ('gambia', 'europe middle east africa'),
  ('ghana', 'europe middle east africa'),
  ('gibraltar', 'europe middle east africa'),
  ('guernsey', 'europe middle east africa'),
  ('guinea', 'europe middle east africa'),
  ('guinea-bissau', 'europe middle east africa'),
  ('hungary', 'europe middle east africa'),
  ('iceland', 'europe middle east africa'),
  ('iran', 'europe middle east africa'),
  ('iraq', 'europe middle east africa'),
  ('ireland', 'europe middle east africa'),
  ('isle of man', 'europe middle east africa'),
  ('ivory coast', 'europe middle east africa'),
  ('jersey', 'europe middle east africa'),
  ('latvia', 'europe middle east africa'),
  ('lesotho', 'europe middle east africa'),
  ('liberia', 'europe middle east africa'),
  ('libya', 'europe middle east africa'),
  ('liechtenstein', 'europe middle east africa'),
  ('lithuania', 'europe middle east africa'),
  ('luxembourg', 'europe middle east africa'),
  ('macedonia', 'europe middle east africa'),
  ('madagascar', 'europe middle east africa'),
  ('malawi', 'europe middle east africa'),
  ('mali', 'europe middle east africa'),
  ('malta', 'europe middle east africa'),
  ('mauritania', 'europe middle east africa'),
  ('mauritius', 'europe middle east africa'),
  ('moldova', 'europe middle east africa'),
  ('monaco', 'europe middle east africa'),
  ('montenegro', 'europe middle east africa'),
  ('mozambique', 'europe middle east africa'),
  ('namibia', 'europe middle east africa'),
  ('niger', 'europe middle east africa'),
  ('palestine', 'europe middle east africa'),
  ('poland', 'europe middle east africa'),
  ('romania', 'europe middle east africa'),
  ('rwanda', 'europe middle east africa'),
  ('san marino', 'europe middle east africa'),
  ('sao tome & principe', 'europe middle east africa'),
  ('senegal', 'europe middle east africa'),
  ('serbia', 'europe middle east africa'),
  ('slovakia', 'europe middle east africa'),
  ('slovenia', 'europe middle east africa'),
  ('somalia', 'europe middle east africa'),
  ('sudan', 'europe middle east africa'),
  ('swaziland', 'europe middle east africa'),
  ('syria', 'europe middle east africa'),
  ('tanzania', 'europe middle east africa'),
  ('togo', 'europe middle east africa'),
  ('tunisia', 'europe middle east africa'),
  ('uganda', 'europe middle east africa'),
  ('ukraine', 'europe middle east africa'),
  ('vatican city', 'europe middle east africa'),
  ('western sahara', 'europe middle east africa'),
  ('yemen', 'europe middle east africa'),
  ('zambia', 'europe middle east africa'),
  ('zimbabwe', 'europe middle east africa'),
  ('australia', 'asia pacific'),
  ('china', 'asia pacific'),
  ('india', 'asia pacific'),
  ('japan', 'asia pacific'),
  ('south korea', 'asia pacific'),
  ('indonesia', 'asia pacific'),
  ('malaysia', 'asia pacific'),
  ('new zealand', 'asia pacific'),
  ('philippines', 'asia pacific'),
  ('singapore', 'asia pacific'),
  ('thailand', 'asia pacific'),
  ('vietnam', 'asia pacific'),
  ('bangladesh', 'asia pacific'),
  ('pakistan', 'asia pacific'),
  ('sri lanka', 'asia pacific'),
  ('nepal', 'asia pacific'),
  ('myanmar', 'asia pacific'),
  ('cambodia', 'asia pacific'),
  ('laos', 'asia pacific'),
  ('brunei', 'asia pacific'),
  ('mongolia', 'asia pacific'),
  ('fiji', 'asia pacific'),
  ('papua new guinea', 'asia pacific'),
  ('maldives', 'asia pacific'),
  ('bhutan', 'asia pacific'),
  ('timor-leste', 'asia pacific'),
  ('solomon islands', 'asia pacific'),
  ('vanuatu', 'asia pacific'),
  ('samoa', 'asia pacific'),
  ('tonga', 'asia pacific'),
  ('aus', 'asia pacific'),
  ('chn', 'asia pacific'),
  ('ind', 'asia pacific'),
  ('kor', 'asia pacific'),
  ('jpn', 'asia pacific'),
  ('indian', 'asia pacific')],
 'state': [('california', 'americas'),
  ('texas', 'americas'),
  ('new york', 'americas'),
  ('florida', 'americas'),
  ('illinois', 'americas'),
  ('pennsylvania', 'americas'),
  ('ohio', 'americas'),
  ('georgia, u.s.', 'americas'),
  ('north carolina', 'americas'),
  ('michigan', 'americas'),
  ('ontario', 'americas'),
  ('quebec', 'americas'),
  ('british columbia', 'americas'),
  ('alberta', 'americas'),
  ('nova scotia', 'americas'),
  ('jalisco', 'americas'),
  ('nuevo león', 'americas'),
  ('são paulo', 'americas'),
  ('rio de janeiro', 'americas'),
  ('minas gerais', 'americas'),
  ('buenos aires', 'americas'),
  ('córdoba', 'americas'),
  ('santa fe', 'americas'),
  ('antioquia', 'americas'),
  ('valle del cauca', 'americas'),
  ('lima', 'americas'),
  ('cusco', 'americas'),
  ('santiago metropolitan', 'americas'),
  ('valparaíso', 'americas'),
  ('mendoza', 'americas'),
  ('ny', 'americas'),
  ('bavaria', 'europe middle east africa'),
  ('baden-württemberg', 'europe middle east africa'),
  ('north rhine-westphalia', 'europe middle east africa'),
  ('hesse', 'europe middle east africa'),
  ('lower saxony', 'europe middle east africa'),
  ('rhineland-palatinate', 'europe middle east africa'),
  ('saxony', 'europe middle east africa'),
  ('thuringia', 'europe middle east africa'),
  ('brandenburg', 'europe middle east africa'),
  ('berlin', 'europe middle east africa'),
  ('hamburg', 'europe middle east africa'),
  ('bremen', 'europe middle east africa'),
  ('catalonia', 'europe middle east africa'),
  ('andalusia', 'europe middle east africa'),
  ('madrid', 'europe middle east africa'),
  ('valencia', 'europe middle east africa'),
  ('lombardy', 'europe middle east africa'),
  ('sicily', 'europe middle east africa'),
  ('tuscany', 'europe middle east africa'),
  ('lazio', 'europe middle east africa'),
  ('île-de-france', 'europe middle east africa'),
  ("provence-alpes-côte d'azur", 'europe middle east africa'),
  ('auvergne-rhône-alpes', 'europe middle east africa'),
  ('scotland', 'europe middle east africa'),
  ('wales', 'europe middle east africa'),
  ('northern ireland', 'europe middle east africa'),
  ('gauteng', 'europe middle east africa'),
  ('western cape', 'europe middle east africa'),
  ('eastern cape', 'europe middle east africa'),
  ('kwazulu-natal', 'europe middle east africa'),
  ('new south wales', 'asia pacific'),
  ('victoria', 'asia pacific'),
  ('queensland', 'asia pacific'),
  ('western australia', 'asia pacific'),
  ('tasmania', 'asia pacific'),
  ('maharashtra', 'asia pacific'),
  ('karnataka', 'asia pacific'),
  ('tamil nadu', 'asia pacific'),
  ('gujarat', 'asia pacific'),
  ('beijing', 'asia pacific'),
  ('shanghai', 'asia pacific'),
  ('guangdong', 'asia pacific'),
  ('sichuan', 'asia pacific'),
  ('hokkaido', 'asia pacific'),
  ('kyoto', 'asia pacific'),
  ('osaka', 'asia pacific'),
  ('seoul', 'asia pacific'),
  ('busan', 'asia pacific'),
  ('jakarta', 'asia pacific'),
  ('bali', 'asia pacific'),
  ('selangor', 'asia pacific'),
  ('kuala lumpur', 'asia pacific'),
  ('auckland', 'asia pacific'),
  ('wellington', 'asia pacific'),
  ('manila', 'asia pacific'),
  ('bangkok', 'asia pacific'),
  ('ho chi minh city', 'asia pacific'),
  ('hanoi', 'asia pacific'),
  ('colombo', 'asia pacific'),
  ('punjab', 'asia pacific')],
 'city': [('new york city', 'americas'),
  ('los angeles', 'americas'),
  ('chicago', 'americas'),
  ('houston', 'americas'),
  ('phoenix', 'americas'),
  ('philadelphia', 'americas'),
  ('san antonio', 'americas'),
  ('san diego', 'americas'),
  ('dallas', 'americas'),
  ('san jose', 'americas'),
  ('toronto', 'americas'),
  ('montreal', 'americas'),
  ('vancouver', 'americas'),
  ('calgary', 'americas'),
  ('edmonton', 'americas'),
  ('mexico city', 'americas'),
  ('guadalajara', 'americas'),
  ('monterrey', 'americas'),
  ('são paulo', 'americas'),
  ('rio de janeiro', 'americas'),
  ('buenos aires', 'americas'),
  ('córdoba', 'americas'),
  ('rosario', 'americas'),
  ('bogotá', 'americas'),
  ('medellín', 'americas'),
  ('lima', 'americas'),
  ('santiago', 'americas'),
  ('quito', 'americas'),
  ('caracas', 'americas'),
  ('havana', 'americas'),
  ('san marino, california', 'americas'),
  ('paris', 'europe middle east africa'),
  ('berlin', 'europe middle east africa'),
  ('rome', 'europe middle east africa'),
  ('madrid', 'europe middle east africa'),
  ('london', 'europe middle east africa'),
  ('amsterdam', 'europe middle east africa'),
  ('brussels', 'europe middle east africa'),
  ('zurich', 'europe middle east africa'),
  ('vienna', 'europe middle east africa'),
  ('stockholm', 'europe middle east africa'),
  ('oslo', 'europe middle east africa'),
  ('copenhagen', 'europe middle east africa'),
  ('helsinki', 'europe middle east africa'),
  ('athens', 'europe middle east africa'),
  ('lisbon', 'europe middle east africa'),
  ('istanbul', 'europe middle east africa'),
  ('tel aviv', 'europe middle east africa'),
  ('riyadh', 'europe middle east africa'),
  ('dubai', 'europe middle east africa'),
  ('doha', 'europe middle east africa'),
  ('kuwait city', 'europe middle east africa'),
  ('muscat', 'europe middle east africa'),
  ('manama', 'europe middle east africa'),
  ('amman', 'europe middle east africa'),
  ('beirut', 'europe middle east africa'),
  ('cairo', 'europe middle east africa'),
  ('johannesburg', 'europe middle east africa'),
  ('lagos', 'europe middle east africa'),
  ('nairobi', 'europe middle east africa'),
  ('casablanca', 'europe middle east africa'),
  ('frankfurt-iph', 'europe middle east africa'),
  ('sydney', 'asia pacific'),
  ('melbourne', 'asia pacific'),
  ('brisbane', 'asia pacific'),
  ('perth', 'asia pacific'),
  ('adelaide', 'asia pacific'),
  ('mumbai', 'asia pacific'),
  ('bangalore', 'asia pacific'),
  ('chennai', 'asia pacific'),
  ('ahmedabad', 'asia pacific'),
  ('beijing', 'asia pacific'),
  ('shanghai', 'asia pacific'),
  ('guangzhou', 'asia pacific'),
  ('shenzhen', 'asia pacific'),
  ('tokyo', 'asia pacific'),
  ('osaka', 'asia pacific'),
  ('nagoya', 'asia pacific'),
  ('seoul', 'asia pacific'),
  ('busan', 'asia pacific'),
  ('jakarta', 'asia pacific'),
  ('surabaya', 'asia pacific'),
  ('kuala lumpur', 'asia pacific'),
  ('george town', 'asia pacific'),
  ('auckland', 'asia pacific'),
  ('christchurch', 'asia pacific'),
  ('manila', 'asia pacific'),
  ('bangkok', 'asia pacific'),
  ('ho chi minh city', 'asia pacific'),
  ('hanoi', 'asia pacific'),
  ('colombo', 'asia pacific'),
  ('karachi', 'asia pacific')]}

### Cleaning Grades and CGrades

In [208]:
all_cgrades = [x.replace('®', '').replace('™', '').strip() for x in all_cgrades]
all_gradenames = [x.replace('®', '').replace('™', '').strip() for x in all_gradenames]

In [209]:
len(all_cgrades), len(all_gradenames)

(12257, 18148)

In [210]:
remove_suffixes = ['(ok1)', '(extra)', '(f1 apply gy/bk only)', '(r&d sample)', '(short version)', '(complete data)', '(before new yc)', '(extrusion)', '(condensed data)', '(r&d trial sample)', '(spcl)', '(eu)', '(us)', '(inte)', '(inte', '(condensed)', '(simplified)', '(dev)', '(old version)', '(old)', '(developmental)', ' - asia', ' - europe', ' - americas']

temp = []
for cg in all_cgrades:   
    for suffix in remove_suffixes:
        cg = re.sub(r'{}$'.format(re.escape(suffix.lower())), '', cg.lower())
    temp.append(re.sub("(\s+)", " ", cg.replace('®', '').replace('™', '').strip())) 

all_cgrades = [value.strip() for value in temp]

temp = []
for g in all_gradenames:   
    for suffix in remove_suffixes:
        g = re.sub(r'{}$'.format(re.escape(suffix.lower())), '', g.lower())
    temp.append(re.sub("(\s+)", " ", g.replace('®', '').replace('™', '').strip())) 

all_gradenames = [value.strip() for value in temp]
all_gradenames

['kep f20-03',
 'cnl b3 j gf15 nc 1102/r',
 'frianyl b3 gf25 x v0',
 'celcon uv140lg',
 'ze 650',
 'cs pp-gf20-02 black',
 'rynite 530hte nc010',
 'lftr pp-gf40-0403 black',
 'stp 251-80w232',
 'santoprene 281-55med',
 'hf s 9364uv',
 'pultrusion pa66-gf50-02 af3001 natural',
 'celcon m270 eco-b',
 'hostaform ec270tx',
 'hostaform slidex c0304 xap2',
 'lft pp-gf60-0453 p10/10',
 'santoprene 8221-85m300',
 'zenite 5115l',
 'pultrusion pp-gf40-20 ad3004 black',
 'hyt htr8332 bk320',
 'stp 691-73w175',
 'htr sc976 nc010',
 'celanyl b3 n hh bk 9004/z/uv',
 'celstran pp-gf30-0403 p7',
 'cnl a3 gf35 bk 9005/u',
 'hf c 2521 xap',
 'hf s 9364 lpb',
 'santoprene 101-87 eco-r',
 'hyt 40cb',
 'celstran cfr-tp pet gf60-10',
 'zytel lc6210 bk010',
 'kepital f10-52h lof',
 'crastin fr684nh1 nc010',
 'xgc',
 'gur 4130',
 'kepital f20-03 colored',
 'cs lft tpu-gf50-01 ad3002 black',
 'fo 6165a4',
 'hf c 27021 xap2 ls',
 'lftr pp-gf40-0455 eco-b352soul 4pk blk',
 'celstran lft pp-gf40-03-black',
 'lft pp-gf20-0553 ad9600r black',
 'fortron 1130t4',
 'celanex 2003hr',
 'fortron 1140l6',
 'gur x 160',
 'celanyl b3 w mgf2015 nc 1102/1',
 'lfrt pp-gf50-0455 p10/10',
 'hytrel htr8745lv bk320',
 'kepital tx-11hk',
 'cs lft tpu-cf40-01',
 'fortron 1120l4',
 'celanex xfr 6842 gf15',
 'santoprene 8291-85tl',
 'hostaform lw90bsx',
 'zytel st7301 nc010',
 'stp 8123-45s100',
 'lft pp-gf30-0453 eco-b 352 p10/10',
 'zyt 70g50hslr bk509',
 'pultrusion pp-gf50-0455 p10/10',
 'hyt 3046 nc010',
 'cs pp-gf30-0455 p10/10',
 'cnl b3 h gf30 nc 1102/2a',
 'cnl a2 j05 m30 bk 9005/r/uv',
 'vectra e540i',
 'celanyl b3 j10 bk 9005/t',
 'hytrel htr8936 bk320',
 'cnl b2 hh gf30 bk 9005/1',
 'celstran lft pa66-cf40-02 af3004 natural',
 'hf c 2521',
 'cnl a3 hhr3 gf35 bk 9005',
 'zenite sea30n r1',
 'celstran lft cfr-tp hdpe gf70-01',
 'lft pp-gf30-0403 eco-b 352 p10',
 'fri b3 gf30 v0 gy 7035/l',
 'hyt 4068 eco-b 652',
 'zyt 80g14ahs bk099',
 'pultrusion pp-gf30-0403 p10',
 'frianyl b3 w gf25 v0e bk 9004/yg',
 'hf m30rs',
 'vectra v143xl',
 'ryn fr543 bk507',
 'celstran pp-gf40-0455 p10 titan black',
 'hf fk 2:25',
 'hyt htr8856 nc030',
 'kep f30-34',
 'ecomid b gf33 bk 9005/1c',
 'cnl b3 h gcf2406 bk 9005',
 'zyt htnfr52g45nhf bk337',
 'celstran pp-gf20-0553 ad9600r black',
 'celstran tpu-gf30-01 af3001 natural',
 'cp d5506',
 'cs pp-gf30-0553 black',
 'gur 4032',
 'cs pa66-gf30-07',
 'cnl b2 hw gf30 nc 1102/3',
 'zytel st801 nc010',
 'zyt 157hsl bk010',
 'vectra e840i lds',
 'cnl b2 w gf33 nc 1102/1c',
 'cs lft pp-gf40-0455 p10 titan black',
 'celanyl b3 gcf2006 bk 9005',
 'cs lft pps-gf40-01 af3001 natural',
 'celstran lft tpu-gf60-01 af3001 natural',
 'hostaform c 2521 xap',
 'stp 151-70w256',
 'kep et-20r7g bk',
 'rynite gw520cs1 nc010',
 'cra s600f40 nc010',
 'lftr pp-gf40-0414 p10',
 'hf c 9021 fc',
 'frianyl b2 h gf30 v0xi nc 1101/2',
 'celanyl b3 gf50 nc 1102',
 'santoprene 273-40',
 'hostaform lx90z',
 'crastin hr5315hfs bk591',
 'rynite 545 bk504',
 'cnl b3 h gf35 nc 1102/2',
 'frianyl b3 gf30 v0xi nc 1101/b',
 'cnl a3 hh bk 9005/2',
 'cn uv270z',
 'fri c3 h v0',
 'pultrusion pp-gf20-0501 black',
 'stp 271-80',
 'cs pp-gf50-02- natural',
 'gur 2105',
 'cnl b3 hh j40 nc 1102/3',
 'celstran pa6-gf50-01 af3001 natural',
 'lftr pps-sf50-03',
 'zytel fe3734 nc010',
 'cx 3200',
 've mt1305',
 'zyt 101 nc010',
 'cnl a2 h j10 nc 1102/e',
 'zytel 101f bkb009',
 'zytel fr95g25v0nh bk458',
 'ecomid b hh j8 bk 9005/1b',
 'cnl b3 gf30 e bk 9005',
 'cnl a3 h gb30 nc 1101',
 'fri a3 gf35 v0 bk 9005/m',
 'frianyl a3 v2 a',
 'lftr pp-gf60-0453 hf black',
 'ghr 8110',
 'kepital et-20r3 bk',
 'hyt htr8808 bk316',
 'fortron 1140t4',
 'santoprene 201-73',
 'zyt 70g33l nc010',
 'dym',
 'cx 2401mt eco-b 352',
 'vectra e845i lds',
 'zytel 45hsb nc010',
 'santoprene 8221-60',
 'cs pa6-gf40-01 af3001 natural',
 'fo 6160b4',
 'zyt 70g43l nc010',
 'stp 271-87',
 'santoprene 121-75m200',
 'zenite 6130l',
 'htr 4069',
 'cs cfr-tp pa66 gf60-02',
 'hytrel htr4275 bk600',
 'pultrusion pp-gf60-25 ad3002 black',
 'pultrusion pps-gf40-02 ad3002 black',
 'vectra mt4310',
 'cs lft pa66-gf50-02 ad3019 black',
 'celstran pa66-gf30-02 ad3002 black',
 'cs lft tpu-gf60-01 af3001 natural',
 'celanyl a2 hh gf30 bk 9005/2c',
 'cnl b2 hh gf15 bk 9005/1',
 'lftr pp-gf20-0501 black',
 'frianyl b3 gf30 x v0',
 'stp 8291-85tl',
 'lfrt pa66-gf50-02-natural',
 'htr htr8163hvbk',
 'kep tx-11h',
 'fri a3 w v2 bk 9005/u',
 'lft pp-gf50-0455 p10/10',
 'stp 8281-55b1med',
 'hyt htr8341c bk320',
 'cs cfr-tp pps cf60-01',
 'stp 121-75m200',
 'zenite 650',
 'cs pps-gf40-02 ad3002 black',
 'zytel fg53 nc010',
 'zyt htn51g15hsl nc010',
 'zytel 74g33w bk196',
 'zenite 51301l',
 'htr htr8532 nc010',
 'frianyl a3 h gf25 v0xi bk 9004/2',
 'stp 8211-55',
 'cs lft pp-gf30-0501 p10',
 'cnl a3 w gf30 bk 9005/b',
 'hhr',
 'santoprene 101-73',
 'kepital tx-21',
 'ecomid b h gf30 bk 9004/2',
 'zyt 158l nc010',
 'cra 6134 nc010',
 'fri a3 h gf25 v0xi bk 9004/2',
 'lftr pp-gf30-0405 p10/10',
 'crastin st830fruv nc010',
 'ryn re5231 bk533',
 'cs lft pp-gf60-02 ad3019',
 'ecomid arx h gf30 bk 9005/d',
 'zyt 73g50hsla bk416',
 'cs lft pa66-sf50-02 af3005',
 'ryn 940 nc010',
 'fortron mt9140l6',
 'cs lft pp-gf60-0453 p10/10',
 'hf m15hp',
 'celanyl a3 d10 bk 9005/g',
 'celstran lft pa66-gf60-02-natural',
 'cs pa66-gf20-02p11/12',
 'fri a3 h gf25 v0 nc 1102/eb',
 'zytel 70g13hs1l nc010',
 'hostaform mt8u01 eco-b',
 'cs pp-gf40-0455 p10/10',
 'lft pp-gf40-0403 black',
 'lftr abs-gf40-05 natural',
 'cnl a3 j10 gf13 nc 1102/e',
 'celanex xfr 6852 gf30',
 'rynite 815er bk503',
 'cs lft pp-gf60-0453 hf black',
 'fri b3 w gf30 v0e bk 9004/yg',
 'cp d1202',
 'pultrusion pa66-cf40-02 af3004 natural',
 'celanyl a3 gf30 bk 9005/a',
 'santoprene 191-55 pa',
 'santoprene rc8001',
 'hf tf-10xap',
 'ze 6130l',
 'frianyl b3 gf25 v0',
 'celstran pa66-gf50-02 af3001 natural',
 'pultrusion pp-gf30-0403 p7',
 'hyt 5033fg nc010',
 'cs pbt-gf40-08',
 'celstran pp-gf30-0553 eco-b 352 black',
 'zytel 70g50hslr bk509',
 'rynite 408 bk515',
 'kep f40-03',
 'zyt pls93g35dh1 bk549',
 'lfrt cfr-tp pa66 gf60-02',
 'ecomid a h gf15 bk 9004/2',
 'zytel fg70g30hsr2 bk309',
 'cs tpu-gf30-01 ad3002 black',
 'fri a3 w gf25 v0e bk 9004/yg',
 'kepital f20-03hc lof2',
 'rynite re5264e nc010',
 'zyt htn53g60lrhf bk083',
 'zytel fr7026v0f bk001',
 'zytel 70g25hslr bk099',
 'frianyl b3 gf30 v0xi bk 7021/a',
 'ecomid b gf33 bk 9005/1a',
 'hytrel htr8241',
 'hostaform fk 1:25',
 'kep et-20r3 bk',
 'lfrt pp-gf30-0553 black',
 'zyt htn54g15hslr nc010',
 'cs pps-cf40-01',
 'hostaform mr130ar',
 'hyt htr8068',
 'celstran lft pp-gf40-0403 black',
 'celstran lft pp-gf50-0453 p10/10',
 'celstran pp-gf30-02 af 3001',
 'vectra e135i',
 'zyt 73g45 bk263',
 'zytel 80g33hs1l bk104',
 'lfrt pa6-gf60-01 p11/10',
 'zytel 73g40t bk416',
 'hostaform xgc25 xap eco-b',
 'hostaform s 9364 eco-c 772',
 'cs lft pp-gf30-03-ad3002',
 'hostaform mt12r01 eco-b',
 'hyt htr8206',
 'hostaform lu-02xap',
 'celanyl b2 w gf43 nc 1102/1b',
 'celanyl a3 hh gf20 nc 1102/ha',
 'zyt fr73g30v0nh1 eco-r 311 n904lm',
 'cra fr684nh1 nc010',
 'hostaform s 9243 xap2 eco-b',
 'pultrusion cfr-tp pp gf60-13',
 'zenite 5244l',
 'ice',
 'cs lft pa66-gf20-02p11/12',
 'zyt htn52g35ef bk420',
 'celstran pps-gf50-01 af3001 natural',
 'celstran lft tpu-cf40-01',
 'hf s 9243 xap2 eco-b',
 'cnl a3 h d20 bk 9005/k',
 'vectra b230',
 'gur 4150-3 l',
 'lft pp-gf60-0403 p10/10',
 'celstran cfr-tp pp gf70-13',
 'pultrusion pa66-gf30-02 ad3002 black',
 'hytrel htr8856 nc030',
 'fo 6341l4',
 'zytel htn54g15hslr nc010',
 'hf s 9243 xap2 eco-c 772',
 'celstran lft pa66-gf30-07',
 'kepital f20-03 lof',
 'vectra e473i',
 'celstran lft pp-gf30-0455 p10/10',
 'santoprene 101-87',
 'hf lw90ewx',
 'zytel rs lc3060 nc010',
 'celstran pp-gf40-02-black',
 'fo ice 504l hr',
 'celanyl b2 w gf33 nc 1102/1a',
 'frianyl b3 v0 or 2003/j',
 'hf m10ae',
 'celstran lft pp-gf30-0501p10/13',
 'hostaform c 13031 xap',
 'htr htr3048 bk459',
 'celstran cfr-tp pa6 gf60-03',
 've b230',
 'hyt htr8532 nc010',
 'hostaform lw90ewx',
 'celstran pp-gf20-02 natural',
 'celanyl b2 gf15 bk 9005/1',
 'hostaform sxt90z-01 xap',
 'hyt 4069 eco-b 652',
 'fortron 4184l4',
 'cs abs-gf40-05 natural',
 'celanyl b3 gb50 nc 1102',
 'celstran pp-gf40-20 ad3004 black',
 'fri a3 rv0 gn 6017/w',
 'hyt 6359fg nc010',
 'fri a3 gf25 x v0',
 'hostaform s 9362 xap2 eco-b',
 'zytel 105f bk010',
 'pultrusion cfr-tp pet gf60-10',
 'zenite 5130l',
 'kepital f30-03',
 'cs pp-gf30-0403 p10',
 'celanyl b2 hh gf25 nc 1102/1',
 'celanex 2302 gv1/20',
 'lft pa6-gf40-01 ad3002 black',
 'cx 2302 gv1/30 eco-r',
 'hf s 9364 xap2 eco-b',
 'htr dym250s bk472',
 'fortron fx530t4',
 'cs lft pp-gf40-0453 eco-b 352 black',
 'celanyl a3 gf30 bk 9005/j',
 'crastin fr684nh1 or162',
 'frianyl b3 gf30 v0',
 'ryn re15022 nc010',
 'celstran pa66-gf20-02p11/12',
 'kepital f20-33',
 'cs lft tpu-gf50-01 af3001 natural',
 'hf mt8u05',
 'rynite 415hp nc010',
 'lfrt pp-gf40-0501 black',
 'celanyl a3 w gf30 bk 9005/u',
 'cs pa66-gf50-02 p7',
 'cs lft pp-gf30-0453 eco-b 352 p10/10',
 'celstran pp-gf30-0403 p10',
 'lfrt pp-gf40-0455 eco-b352soul 4pk blk',
 'cs lft pa66-gf40-02 ad3004 black',
 'celanyl a2 w gf33 nc 1102/1c',
 'lftr pa66-gf60-02-natural',
 'hostaform c 9021 as',
 'cra fg6130 nc010',
 'cx 2002sw1',
 'fortron 4665b6',
 'santoprene rc8008',
 'fortron 1140l4',
 'cnl b2 hh gf50 bk 9005/2',
 'santoprene 591-56w175',
 'hf rf2464',
 'cs pa66-af35-01 af3003 natural 6mm',
 'pultrusion pbt-gf50-08',
 'fo 1115l0',
 'celanyl a3 h gf30 tm1 bk 9005/k',
 'lfrt pp-gf40-0414 p10',
 'cx 2002-2fc',
 'thermx cg023',
 'cs lft pa66-gf60-02-natural',
 'zytel 70g30hsl nc010',
 'celanyl a3 hh gcf2010 bk 9005/1',
 'celanyl a3 bk 6600/uv/1',
 'pultrusion tpu-gf30-01 af3001 natural',
 'lfrt cfr-tp pps cf60-01',
 'celstran pp-gf30-0453 p10/10',
 'zenite 5145l',
 'lft pa6-gf30-01',
 'cx 3400-2',
 'hyt htr8997 nc010',
 'hf m25ie',
 'lfrt pp-gf60-02 ad3019',
 'ze 5130l',
 'frianyl b3 v0',
 'htr 3078 eco-b 752',
 'cn m270 eco-b',
 'hytrel g5544',
 'cra s600f10 nc010',
 'cs pp-gf60-02 ad3019',
 'htr htr8223 bk320',
 'cx 2408mt gf20',
 'hytrel htr8206',
 'cs pa66-gf50-02-natural',
 'celanyl a3 k30 bk 9004',
 'celstran cfr-tp pa66 cf60-02',
 've mt4310',
 'lft pp-gf40-0455 eco-b352soul 4pk blk',
 'cra ce15330 nc010',
 'lftr pp-gf20-02 black',
 'lftr pa66-gf40-02 ad3002 black',
 'lft pp-gf30-02 ad 3019',
 'zytel bm73g15ths bk317',
 'cs lft pa6-gf30-01',
 'stp 9103-42e',
 'lft pa66-af35-02 af3003 natural',
 'hyt g4078 nc010',
 'celstran pp-gf40-0403 black',
 'frianyl a3 nh a v2 bt nc 1102/w',
 'cnl b3 gf30 e gy 7035/yg',
 'cs pa66-sf50-02 af3005',
 'hytrel htr8908eco-b 452 bk320',
 'pultrusion pp-gf40-0453 black',
 'hostaform c 9021 m xap2',
 'stp 6nm901a55/iw blk',
 'celanyl b3 gf30 nc 1102',
 'cnl b2 hh gf50 bk 9005/3',
 'santoprene 101-80 eco-r',
 'cnl b3 w gf30 gy 7035',
 'pultrusion dev pp-gf50-0405e black',
 'lfrt pp-gf30-0403 p7',
 'cs lft pp-gf30-02 ad 3002',
 'hf sx90',
 'celanyl xs3 gf60 bk 9005/c ef',
 'celstran pa66-gf40-02 ad3002 black',
 'gur 4018 ep eco-b',
 'celanex 5206hg',
 'hostaform c 9021 aw xap2 ls',
 'gur 2022 fines',
 'cs lft pa66-gf40-01',
 'pultrusion pa66-gf50-28 ad3020',
 'ecomid arx h gf30 bk 9005/n',
 've e440i',
 'frianyl b3 v0 bk 9005/o',
 'lftr pp-gf40-0501 black',
 'pultrusion cfr-tp hdpe gf70-01',
 'lft pa66-sf50-02 af3005',
 'lfrt pp-gf30-0403 p10/10',
 'celcon lw90-f2',
 'celcon m25',
 'cra sk605 nc010',
 'cp d3612',
 'celanyl b2 h gf30 bk 9005/2',
 'lfrt pa66-gf40-07',
 'celstran lft pp-gf30-0551 eco-b 352 black',
 'hostaform c 2521 xap2',
 'hf c 13021 fc',
 'celanyl a3 cf30 bk 9005',
 'zytel 77g33hs1l nc010',
 'cn m140',
 'stp 8281-55med',
 'lftr pa66-gf50-02 ad3019 black',
 'fo 4332l6',
 'celcon m90sw',
 'cs pa66-gf50-02 ad3002 black',
 'zytel pls95g50dh2 bk261',
 'zyt st801 bk010',
 'gur 4012 f',
 'hyt 6356',
 'hytrel 6356',
 'celanyl a4 e gf25 bk 9005',
 'htr 6356bkb',
 'zenite 251',
 'celanyl a2 w gf50 nc 1102/1',
 'fri a3 gf20 v0',
 'celanyl b2 gb30 bk 9005/1',
 'zytel 70g43l nc010',
 'lft tpu-gf50-01 af3001 natural',
 'htr 60lw',
 'celanyl b3 w nc 1102/1',
 'ryn fg530 nc011',
 'cnl b2 w gf43 nc 1102/1b',
 'hf mt12u03 eco-b',
 'fo fx4382t1',
 'lft pa66-gf60-0101p10',
 'fortron mt9140l4',
 'zyt 73g30l eco-r 231 bk300',
 'celcon ce66fc gv1/25',
 'lft pp-gf60-0403 hf black',
 'cnl a3 hh gf30 nc 1102/ha',
 'cnl a3 d10 nc 1102/c',
 'celanex 2414mt',
 'lftr pp-gf40-0453 xva 103h blk',
 'vectra a435',
 'zytel htn51g35hsl nc010',
 'fri a3 v0',
 'celstran lft cfr-tp pp gf70-13',
 'celanyl a3 h gf15 tp05s bk 9005/z',
 'fri b3 gf25 v0',
 'lftr pp-gf30-0551 black',
 'pultrusion pa66-gf40-02 ad3002 black',
 'zytel htn54g35ef bk420',
 'lfrt pp-gf40-0414 p7',
 'cs pp-gf60-0453 bf p10/10',
 'cnl b2 gf15 bk 9005/1',
 'fortron ice 504l hr',
 'zyt 42a nc010',
 'celanex xfr 4840',
 'crastin 6140 nc010',
 'vectra a515',
 'cnl a2 hh j14 bk 9005/2',
 'zytel 70g35hslx bk357',
 'zytel 73g50hsla bk416',
 'cs lft pp-gf40-20 ad3004 black',
 'hytrel 7246hs bk320',
 'cnl a3 h j18 bk 9005/3',
 'lft pp-gf60-0453 bf p10/10',
 'ze 7755',
 'crastin fr685nh1 nc010',
 'hytrel 5526 bk203',
 'gur 4130 cr',
 'cra lw9030 bk851',
 'lftr pp-gf20-02 natural',
 'cnl a3 j8 gf13 nc 1102/1',
 'santoprene 203-50',
 'lftr tpu-gf40-01 ad3002 black',
 'cs pp-gf30-03-ad3002',
 'celanex 2500-6fc',
 'lfrt pehd-gf60-01',
 'lfrt pp-gf40-0453 eco-b 352 black',
 'vectra e440i',
 'zytel 101l bkb080',
 'ze sea20n',
 'hf c 9021 10/9005',
 'cn m450',
 'celanyl a3 gf30 tm2 gy 7022/a',
 'fortron 6850l6',
 'frianyl a3 gf25 v0',
 'hf lx90',
 'zytel lc6601 bk551',
 'hostaform xgc25 xap eco-c 672',
 'celanex 2004-2',
 'celanex 2302 gv1/30',
 'pultrusion tpu-cf40-01',
 'celanyl b3 w gb30 nc 1102',
 'frianyl b3 gf25 v0 bk 9005/p/f1',
 'fri a3 h gf25 v0 gy 7016/e',
 'cn m15hp',
 'lfrt pp-gf40-0453 xva 103h blk',
 'cs pp-gf20-02 natural',
 'cs lft pa66-gf50-28 ad3020',
 'cp e5521',
 'rynite 550hte bk503',
 'hostaform c 13031 k',
 'zytel htn510eft bk010',
 'celanyl b2 hh gf35 bk 9005/1',
 'pultrusion pp-gf30-0501p10/13',
 'zytel 73g30t bk261',
 'celanex 4022',
 'htr sc988 nc010',
 'coolpoly d5506',
 'cs lft pehd-gf40-01',
 'celstran pa66-gf50-02 ad3019 black',
 'zytel 80g14a nc010a',
 'ryn fr515 nc010',
 'pultrusion pp-gf60-02 ad3002 black',
 'zytel 77g43l nc010',
 'stp 8221-85m300',
 'celanyl a2 hh j16 nc 1102/2b',
 'cnl a3 j10 bk 9005/e',
 'frianyl a3 gf25 v0xi bk 7021/a',
 'htr 5555hs',
 'fo 1140l6',
 'crastin lw9320 nc010',
 'santoprene 121-87',
 'fri a3 rv0 gy 7012/h',
 'zyt htn510eft bk010',
 'cnl b2 hh gf15 bk 9005/3a',
 'fortron ces51 n',
 'frianyl b3 gf20 v2',
 'pultrusion pa66-gf30-02-d af3001 natural',
 'stp 291-60b150',
 'htr 4053fg nc010',
 'fortron ces 6145 lcg',
 'hostaform lm90',
 'hostaform c 9021 xap2 ls',
 'rynite hr540suv bk544',
 'hyt 4068fg',
 'hyt 6356bkb',
 'tx te4005',
 'cx 2003hr',
 'zytel sc315 nc010',
 'hytrel 7246hs nc010',
 'cnl a3 gf15 nc 1102/z',
 'lftr tpu-gf50-01 ad3002 black',
 'kep f25-03 lof',
 'hf c 9021 ls 10/1570',
 'cs lft pa66-gf30-02-d af3001 natural',
 'hyt g4074',
 'fortron ice 504l',
 'zytel htn54g35hslr bk031',
 'hytrel 4069',
 've e845i lds',
 'celstran pa66-gf50-02 ad3007',
 'celcon gb25',
 'cs pa66-gf50-02 ad3007',
 'hytrel htr8532 nc010',
 'celcon lw90-s2',
 'lftr pa66-gf50-0111p10/11',
 'celanyl a3 hh j6 bk 9005/3',
 'cs pp-gf40-0501 black',
 'stp 8211-75',
 'fri a3 gf25 v0 bk 9005',
 'zenite 17311 eft',
 'hf xgc25 ef xap2',
 'cnl b2 hh gf15 nc 1102/3a',
 'cnl b3 w gb30 nc 1102',
 'hf c 9021 tf5',
 'celanyl b2 h gf50 bk 2000/uv/1',
 'hf lu-02xap',
 'cra s600f10 bk851',
 'cra fr685nh1 nc010',
 'hytrel g3548 nc010',
 'cs lft cfr-tp pps cf60-01',
 'fortron 6160b4',
 'hostaform c 9021 fc',
 'cs lft pp-gf40-0453 black',
 'frianyl a3 w v2',
 'celanex 7716',
 'pultrusion pa66-gf50-0112p7.5/10',
 'celstran lft pp-gf40-0414 p7',
 'cn lw25-s2',
 'ecomid a h j10 bk 9017/a',
 'vectra a115',
 'lftr tpu-gf30-01 af3001 natural',
 'hyt htr8908eco-b 452 bk320',
 'cnl a2 w gf43 nc 1102/1',
 'cx 2300 gv3/20',
 'zyt mt409ahs nc010',
 'hyt htr8855 nc010',
 'lftr pp-gf30-0453 p10/10',
 'fo 0203',
 'crastin sk601 nc010',
 'celstran pp-gf20-0553 xva 103h black',
 'fri a3 h s30 v0xi nc 1101/a',
 'htr htr4275 bk600',
 'hytrel htr8068',
 'lfrt tpu-gf40-01 ad3002 black',
 'cs lft pa66-gf60-02 ad3004 black',
 'fri a3 w gf35 v0e bk 9004/yg',
 'stp 101-64',
 'cs pa66-gf40-02 ad3002 black',
 'cnl xs3 gf60 wt 9016/c ef',
 'cnl a2 hh gf33 bk 9005/1a',
 'celcon m90-07',
 'lfrt pa6-gf40-01 af3001 natural',
 'fri b3 gf30 v0xi bk 7021/a',
 'fortron 6165a4',
 'cnl b2 hh gf33 bk 269/uv/1',
 've mt4350',
 'cx 4302',
 've a530',
 'cs lft pp-gf40-0405 p10/10',
 'rynite 830er bk503',
 'pultrusion pa66-gf50-02-natural',
 'crastin s620f20 nc010',
 'htr 4556',
 'hostaform c 9021 gv1/30 3134',
 'celanyl b3 hh gfb1020 bk 9005/2',
 'thermx te4005',
 'zyt fr7026v0f nc010',
 'cnl a3 h gf30 bk 9005/r',
 'santoprene 8191-55b100',
 'ecomid arx h gf35 bk 9005/v',
 'lft pp-gf50-02- natural',
 'cs pa6-gf60-01 p11/10',
 'ze 7130',
 'hf xgc15-lw01 xap',
 'hostaform mt8u05',
 'celanyl b2 w gf13 nc 1102/1a',
 'ecomid b hh mgf3010 bk 2000/uv/1',
 'hf xgc25 ef xap2 eco-c 672',
 'kepital te-33a lof nat',
 'hostaform c 9021 gv1/20 xgm',
 'pultrusion pa66-gf50-02 p7',
 'zytel fr50 nc010',
 'cs pp-gf40-0403 black',
 'celstran lft pp-gf30-0453 eco-b 352 p10/10',
 'celcon uv25z',
 'lfrt pa6-gf40-01 ad3002 black',
 'hf s 27244 xap2',
 'cnl a3 gb20 bk 9005/u',
 'kepital f25-03h',
 'lft cfr-tp pa66 cf60-02',
 'gur 4116',
 'santoprene 8201-80',
 'celstran pp-gf40-03-black',
 'santoprene 201-64',
 'hytrel 4039',
 'pultrusion pp-gf50-0453 p10/10',
 'celanex 2405mt',
 'lfrt pp-gf40-0455 p10/10',
 'htr g5544',
 'hytrel 3078 eco-b 752',
 'cra hr5330hf bk503',
 'cx 2004-2',
 'hf mt8r02',
 'gur 2126-2',
 'celanyl a3 gf50 bk 9005/u',
 'celstran pp-gf30-0501p10/13',
 'hostaform slidex c0313 xap2',
 'pultrusion cfr-tp pa66 gf60-02',
 'celcon mc90-hm',
 'hf s 9364',
 'hf m30rs eco-b',
 'zytel 70g13l nc010',
 'celanex 2004-2t',
 'celstran lft abs-gf40-05 natural',
 'lftr pa6-gf60-01 af3001 natural',
 'lft pa66-gf50-07',
 'hostaform xgc25-lw01 xap',
 'cn uv25z',
 'cra hr5315hfs bk591',
 'cnl a3 w j4 nc 1102/1',
 'santoprene 111-35',
 'cra sk609 bk851',
 'lfrt pp-gf30-0453 p10/10',
 'fortron ice 716a',
 'cnl b2 h gf55 bk 2000/uv/n/1',
 'hf c 2521 ls',
 'cra lw9030 nc010',
 'fortron 1115l0',
 'hf c 9021 gv3/30',
 'cs lft cfr-tp pp gf60-13',
 'cs lft pa66-gf40-02 ad3002 black',
 'celanyl b3 gb30 nc 1102',
 'cnl b3 h j5 nc 1102/3',
 'lfrt pa66-sf50-02 af3005',
 'zytel pls93g35dh1 bk549',
 'hostaform c 9021 gv1/10',
 'pultrusion cfr-tp pa66 cf60-02',
 'celstran lft pa66-gf50-28 ad3020',
 'pultrusion pa66-gf60-02-natural',
 'frianyl a3 gf30 v0 bk 9005',
 'eco-b',
 'kep f10-52h',
 'cnl a2 hh /uv/2',
 'hostaform mt8u01',
 'pultrusion pp-gf40-03-black',
 'santoprene 6sd001a30 nat',
 'cra lw9320 bk851',
 'gur 4022 eco-b',
 'stp 8211-55b100',
 'zytel 70g50 eco-r 311 blk1',
 'pultrusion pp-gf40-0455 soul 4pk black',
 'hostaform mt24f01',
 'lft pp-gf40-03-black',
 'lftr pp-gf30-0455 p10/10',
 'hostaform uv270z xap2',
 'celanyl b3 h gf35 nc 1102/2',
 'celstran pp-gf40-0453 black',
 'cs pa6-gf40-01 ad3002 black',
 'ecomid b hh j6 gf23 bk 9005/1',
 'fo 4184l6',
 'celstran pa6-gf60-01 af3001 natural',
 'fri b3 gf30 v0 nc 1102/ts',
 'cs lft pp-gf40-02-black',
 'pultrusion pp-gf30-02 ad 3019',
 'celanyl a2 hh j14 bk 9005/2',
 'lft pp-gf40-0501 black',
 'cnl b3 gfb1020 wt 9001/f',
 'santoprene 101-60w261',
 'lft pp-gf30-0553 eco-b 352 black',
 'thermx led 0201',
 'crastin ce15315 bk010',
 'lftr pehd-gf60-01',
 've j540',
 'cn m90-07',
 'cra sk603 bk851',
 'frianyl a3 gf30 v0 bk 9005/mm',
 'cs cfr-tp pa6 cf60-03',
 'cs lft pa66-gf50-0111p7.5/11',
 'lft pa66-gf40-02 ad3004 black',
 'celanyl b3 h nc 1102/2b',
 'celcon cf802 10/9022',
 'cra s600f20 bk851',
 'lfrt tpu-gf60-01 af3001 natural',
 'hostaform mt12u03 eco-b',
 'cs pp-gf30-0403 eco-b 352 p10/10',
 'pultrusion pa66-gf40-01',
 'zytel 70g30hslr eco-r 312 bk099',

In [211]:
all_brands_without_syns

['ecomid',
 'zenite',
 'thermx',
 'fortron',
 'santoprene',
 'frianyl',
 'celstran',
 'celanex',
 'hostaform',
 'celcon',
 'kepital',
 'coolpoly',
 'rynite',
 'vectra',
 'crastin',
 'hytrel',
 'celanyl',
 'zytel',
 'gur',
 'forflex',
 'kepamid',
 'abistir',
 'impet',
 'blueridge',
 'blendfor',
 'omnilon',
 'nylfor',
 'ateva',
 'selar',
 'factor',
 'tecnoprene',
 'neolast',
 'omnicarb',
 'sofpur',
 'micromax',
 'tarnoform',
 'nilamid',
 'celapex',
 'omnitech',
 'pibifor',
 'vamac',
 'kepex',
 'pipelon',
 'vitaldose',
 'forprene',
 'cecopoly',
 'clarifoil',
 'compel',
 'talcoprene',
 'litepol',
 'sikamid',
 'laprene',
 'elvamide',
 'keploy',
 'vandar',
 'stirofor',
 'amcel',
 'polifor',
 'omnipro',
 'sofprene',
 'maximid',
 'minlon',
 'pibiter']

In [212]:
grades_without_brands = []
grade_prefix = {}
for i in all_gradenames:
    brand_found = False
    for j in all_brands:
        if not brand_found and j == i.split()[0]:
            brand_found = True
            break
    if not brand_found:
        grades_without_brands.append(i)
        if i.split()[0] in grade_prefix:
            grade_prefix[i.split()[0]] += 1 
        else:
            grade_prefix[i.split()[0]] = 1

In [213]:
{k: v for k, v in sorted(grade_prefix.items(), key=lambda item: item[1], reverse=True)}

{'htr': 283,
 'im': 79,
 'at': 26,
 'bexloy': 25,
 'etpv': 12,
 'sofpurle': 9,
 'ghr': 5,
 'active': 5,
 'nylind': 5,
 'forgrin': 5,
 'celanese': 5,
 'pet': 4,
 'sofpurl': 4,
 'holo': 4,
 'sofpurs': 4,
 'fxj9507': 3,
 'eco': 2,
 'carboprene': 2,
 'reblend': 2,
 'zytelrs': 2,
 'shine-e': 2,
 'zytelhtn51g35eft': 2,
 'retelan': 2,
 'xgc': 1,
 'dym': 1,
 'hhr': 1,
 'ice': 1,
 'eco-b': 1,
 'xap': 1,
 'slidex': 1,
 'lof2': 1,
 'icf': 1,
 'hrlm': 1,
 'scxxx': 1,
 'hsl': 1,
 'sea': 1,
 'hte': 1,
 'wrf': 1,
 'pcxxx': 1,
 'pls/xt': 1,
 'frhr': 1,
 'fit': 1,
 'lof': 1,
 'xfr': 1,
 'hslr': 1,
 'hrt': 1,
 'hfs': 1,
 'eco-r': 1,
 'htn': 1,
 'xap2': 1,
 'nkx-101': 1,
 'cabofor': 1,
 'jkx-1292': 1,
 'dev.': 1,
 'holrsn01': 1,
 'nkx-1010a': 1,
 'vizilon': 1,
 'kematal': 1,
 'jkx-1295': 1,
 'tecnoprenefk5u': 1,
 'b3': 1,
 'terra': 1,
 'ch0281-1': 1,
 'jkx-1291': 1,
 's224-55a': 1,
 'sd001': 1,
 'pryltex': 1,
 'zytelhtnfe270083': 1,
 'volo': 1,
 'k3045.x01': 1,
 'lumid': 1,
 'zytelhtn51g45eft': 1,
 'jkx-1296': 1,
 'jkx-1294': 1}

In [214]:
grade_prefixes = all_brands + ['lanyl', 'omax', 'fprene', 'lanex', 'htr', 'lifor', 'tin', 'lstran', 'ynite', 'nicarb', 'omid', 'duct', 'lcon', 'teva', 'pet', 'nlon', 'fpur', 'nipro']
grade_prefixes = list(set(grade_prefixes))

In [215]:
len(grades_without_brands)

543

In [216]:
random.shuffle(all_gradenames)
all_gradenames = [x for x in all_gradenames if x not in ['pet']]

grade_brand_prefix_count = {}
filtered_gradenames = []
without_prefix = []
without_prefix2 = []
for i in all_gradenames:
    brand_found = False
    for j in grade_prefixes:
        if not brand_found and j == i.split()[0]:
            brand_found = True
            if j not in grade_brand_prefix_count:
                try:
                    if i.split(j+' ')[1] not in without_prefix:
                        without_prefix.append(i.split(j+' ')[1])
                        grade_brand_prefix_count[j] = 1
                        filtered_gradenames.append(i)
                except:
                    if i not in without_prefix:
                        without_prefix.append(i)
                        grade_brand_prefix_count[j] = 1
                        filtered_gradenames.append(i)

                
            elif j in grade_brand_prefix_count and grade_brand_prefix_count[j] < 70:
                try:
                    if i.split(j+' ')[1] not in without_prefix:
                        without_prefix.append(i.split(j+' ')[1])
                        grade_brand_prefix_count[j] += 1
                        filtered_gradenames.append(i)
                except:
                    if i not in without_prefix:
                        without_prefix.append(i)
                        grade_brand_prefix_count[j] += 1
                        filtered_gradenames.append(i)
            else:
                try:
                    if i.split(j+' ')[1] not in without_prefix:
                        without_prefix2.append(i.split(j+' ')[1])
                except:
                    if i not in without_prefix:
                        without_prefix2.append(i)
                
            break
            
    if not brand_found:
        without_prefix.append(i)
        filtered_gradenames.append(i)

len(filtered_gradenames)

4434

In [217]:
without_prefix2

['73g15hsl bk363',
 'efe1091 bk010',
 'fe3667 nc010',
 'htn92g45dh2 bk083',
 '70g35hslr bk416lm_bu',
 'htnfr55g50nhlw gy061',
 'htn53g60lrhf nc010',
 'rs lc3030 nc010',
 'htnwrf51g30 nc010',
 '158 nc010 - bu',
 'fn727 nc010',
 'htnwrf51mp20 nc010',
 'mt409ahs nc010',
 '70g25ef nc010',
 '75cg30hsl bk409',
 '72g33l bk031',
 'e50 nc010',
 '153hsl bkb038',
 'lc7601 nc010',
 'rs lc3090 nc010 - bu',
 'htnfe150062 bk544',
 'fr70m30v0 bk010',
 'fn718 bk230',
 '70g33hs1l bk031x',
 'htnfe350174 nc010',
 '101f nc010-bu',
 'sc315 nc010 - bu',
 'fe5313 bk032',
 'fe15004 bk032d',
 'st800hsl bk152',
 'fr15 nc010',
 '73g30hslc bk416',
 '74g35arx eco-r 311 blk1',
 '70g30psr nc010',
 'nvh70g35hsla bk152',
 '70g35hsl bk020a',
 '450hslx nc010',
 '101f bk009',
 '80g33l nc010',
 'lc7202 bk',
 '80g30arx eco-r 311 blk1',
 'pls95g40dh1t bk261',
 'fe170032 bk155',
 '159 nc010',
 'bm7300fnh bk317',
 'rs htn59g50ldp bk108',
 '70g50hslr bk509',
 '70g20hsl bk039b',
 'fe5510 bk512j',
 'st801aw bk195',
 'fg77g33l nc010',
 'a3 h j10 gf13 nc 1102/e',
 '70g25hslr bk099',
 '8018hs nc010',
 'a3 h gf35 bk 9005/u',
 'fr73200tc bk245',
 'fe8164 nc010',
 'htn50g40ef bk083lm',
 '7301l eco-r 331 bk300',
 'a3 tm2 gy 7022/a',
 'htnfe170023 bk168',
 '151f nc010',
 '75lg50hsl bk031',
 'a3 tm1 bk 9005/mm',
 'a3 gf60 bk 9005/n',
 'lc6601 bk551',
 '73g35ths bk511',
 'a3 w gf30 bk 9005/u',
 'b2 hh gf30 uv bk 9005/2',
 'b3 h d7 nc 1102/2c',
 'cdv808 bk409',
 'a3 w j10 gf13 bk 9005/p/1',
 'rs 32cg20hsl bk409',
 'a2 hh gf25 bk 9005/e',
 'htnfe150078 bk',
 '73g60hsla bk416-bu',
 'lc6210 bk010',
 '70g13l nc010',
 'b3 gfb1020 gy 7038/c',
 'a2 hh j7 gf15 bk 9005/uv/2',
 'htnfr52g35bl bk337',
 'xt6 j10 hh gf10 bk 9005/e',
 'b2 hh gf50 bk 9005/t1',
 'e51hsb nc010',
 'lc7701 nc010 - bu',
 'xs3 gf60 bn 8000',
 'b3 hh j10 gf40 bk 9005/e',
 'b2 w gf15 nc 1102/1',
 'htnfe350161 bk083',
 'a3 gf30 tf15 nc 1102/e',
 'htnlw5035hs bk031',
 'rs lc2600 bk043a',
 '70g35hsrx bk099',
 'bm73g25ths bk317',
 'htn53g50lr bn517',
 'a3 hh gf33 nc 1102/hw',
 'b3 j6 gf40 nc 1102/1',
 'htn510eft nc010',
 'xs3 gf40 bk 9005/v',
 'b3 j8 gf7 bk 2000/uv/1',
 'lc7701 nc010',
 'fe210079 nc010',
 'fr70g25v0 nc010',
 '70g30hslr nc010',
 'htn53gm40hsl bk083',
 'fe13026 nc010',
 'b3 gf30 wt 9003/d',
 'b2 hh gf33 bk 9005/1',
 '70g33gra bk350',
 'htnfr55g55nhlw bk337',
 'htnfr52g35bl bk337',
 'b3 d10 nc 1102/r',
 'a4 e gf25 bk 9005',
 'htn52g45hsl bk083',
 'wrf101a nc010',
 'b3 gf25 gy 7021/d',
 '70g33l bk031',
 'b3 gf15 bk 9005/e',
 'lc7602 bk010a-bu',
 'fe370096 bk bu',
 'fg70g43l nc010',
 'fr50 bk153',
 'rs lc1000 bk385 - bu',
 'xt6 hh gf35 bk 9005/c',
 'b3 gf15 gy 7037/a',
 'htnfe8219 nc010',
 'b3 h gf30 nc 1102/2a',
 '7331f nc010',
 'xt6 gf30 bk 9005/c',
 'a3 h gf30 tm1 bk 9005/k',
 'a3 d10 bk 9005/a',
 'b3 gf50 bk 9005/e',
 'htnfr52g45nhlw bk337',
 'htn52g35ef bk420',
 'htnfe150004 bk083-bu',
 'lt70g35ef bk601',
 'fe5514 nc010',
 'a2 w gf33 nc 1102/1c',
 '153hsl nc010 - bu',
 '103fhs nc010',
 'htn52gm50ef wt001',
 '70g30hsl bk039b',
 'lft pp-gf50-04 natural',
 'htn55g55tlw bk117',
 'e42a nc010',
 'b3 gf20 bk 269/uv/i/1',
 'rs lc3090 nc010 - bu',
 '70g60hsl bk359',
 'pls95g35dh1ef bk314lm',
 'a2 h j20 bk 2000/uv/1',
 '101f nc010',
 'lft pp-gf20-0553 xva black',
 'htnfe150098 bk236lt',
 'lft pp-gf40-0455 eco-b 352 soul 4pk black',
 'lc6601 nc010',
 'a2 hh gf20 nc 1102/1',
 'a3 s10 nc 1102',
 'a3 w j4 yl 40051/1',
 'a3 a h gcf1213 nc 7016/f',
 'b2 hh gf30 bk 1500/uv/ef/o/1',
 'pp-gf40-0414 p10/10d',
 'lc6210 bk010 - bu',
 'rc70gm36 bk001',
 'xt6 gf30 tf10 bk 9005/c',
 '73g30ef bk314lm',
 'efe1032l nc010',
 'lc7602 bk010 - bu',
 'fe390036 bk001',
 'efe8089b bk416-bu',
 'lft pa66-af35-02 af3003 natural',
 'cfr-tp pps-cf67-01',
 'lft pa6-sf10-01',
 '70g33hs1l bk416lm',
 'htnfr42g30nh nc010',
 'st801uv bk010',
 '70g33w nc010',
 'lft pp-gf30-0403 eco-b 352 p10',
 'fg44hsb nc010',
 'htnfe130004 bk_dev',
 'b3 gf30 bk 9005/u',
 'lft pp-gf40-0414 p7/10',
 '74g33w nc010',
 'htn42g30ef bk083lm',
 'rs lc2600 bk385 - bu',
 'a2 hh j10 bk 9005 (nx)',
 '79g13hsl bk039',
 '132f nc010',
 'a2 hh gf30 nc 1102/3b',
 'b3 hh sgf1809 bk 9005/2',
 '80g14ahs bk099',
 'a3 w j4 yl 40051/1',
 'rs htn59g55lwsf nc010',
 'fe8217hs bk010',
 '70g30hsl bk039b',
 '103fhs nc010-bu',
 'lft pp-gf25-0403 p10/10',
 'fe5382 bk276',
 'fr70m30v0 gy450',
 'nvh70g35hsla2 bk416',
 '70g25hslr bk099',
 'a3 h gf15 bk 9005/e',
 'a3 h j20 bk 9005/c/uv',
 'b3 j gf12 gy 7024/t',
 'htnfe350157 bk211',
 'lft pa6-gf60-01 ac3005 gray',
 '73g40t nc010',
 'a3 w gf30 bk 9005/y',
 'htn510eft bk010',
 '1106',
 'b3 h gf30 nc 1102/2c',
 '5704',
 'a3 gf50 nc 1102/j',
 'xt1 hhr gf35 bk 9005/c',
 '70g60hsla bk099',
 'fe310065 nc010',
 'a3 j15 gf30 nc 1102/e',
 'htnfg301 nc010',
 'lft pa66-gf40-02 ad3002 black',
 'jkx-1061',
 'b3 h gy 20396/uv/o/1',
 'lft pa66-gf60-0101p10',
 'lf6141',
 'fe340084 bk195',
 '3209hrt',
 'lcbm6301 bk010',
 'jkx-994',
 'fe190009 bk409',
 'a3 gf30 bk 9005/te',
 '420hsl bk010',
 'a3 rv0 gn 6018/j',
 'a3 hhr gf35 bk 9005/e',
 'a3 gf25 v0xi',
 'b3 n bk 9005/d',
 'pp-gf40-0455 p10/10',
 'lft pa6-cf40-01',
 'rs lc2800 nc010 - bu',
 'gv1/15 fl',
 'b2 gf30 tf10 bk 9005/c',
 'b3 j10 bk 9005/u',
 'htnfr52g15bl nc010',
 'lf172',
 'b3 h gf30 nc 1102/e',
 'b3 gf30 v0 bl 5015/g',
 'lft pa6-gf30/cf20-13 ad3002 black',
 'fe340084 bk195',
 '3213',
 'pa66-cf40-01-us',
 'lft pa66-gf50-02 p7/12',
 'a3 w j20 nc 1102/fd/1',
 '5734',
 'a3 rv0 bk 9005/p',
 'lft pom-gf35-04 af3001',
 'fe13026 bkb009',
 'htn55g55tlw bk773',
 'jkx-1239',
 '5734',
 'b3 j10 bl 5015/l',
 '5870',
 'htn54g35ef nc010-bu',
 'tc501',
 '9507',
 '2014',
 'pbt-gf30-09 af3001',
 'b3 l bk 9005/u',
 's324-75a',
 'lft pa66-gf50-02 p7/12',
 'htn51g35hslrt bk420',
 '2160',
 'lft pp-gf20-0503 black',
 '4933d',
 '450hslx bk152',
 'lft pp-gf20-0553 eco-b 352 black',
 'a3 rv0 bk 9005/sz',
 'mt419ahs bk010',
 'b2 gf50 bk 9005',
 'lft pp-gf20-0503 black',
 '189ns8465 nero micro',
 'qm44d',
 '2360 gv1/30 fl',
 'a3 hh gf50 nc 1102/ha',
 'lft cfr-tp hdpe gf70-01',
 '540100a92 neutro',
 'a3 rv0 gy 7046/e',
 'rs lc3160 nc010',
 '73g40t bk416',
 'b3 gf30 nc 1102',
 '2005',
 'z s825-40a',
 'fr73200tc bk245',
 'fr50 bk505',
 'a3 v2 nc 1102/v',
 'a3 gf33 tf15s bk 9005/i/1',
 'lft pa66-gf40-01',
 '1711',
 'htn51gm60ths bk083',
 'abs-gf40-05 natural',
 '0f01e',
 'a2 hh j16 nc 1102/2b',
 'lft pehd-gf40-01',
 'b3 j10 nc 1102/e',
 '450hsl bk152',
 'b3 gf25 gy 7035/s_old',
 'pbt-sf10-03',
 'pe826',
 'fr70g30v0nh1 bk314lm',
 'htnfr52g30l nc010',
 'htnfe130004 nc010',
 'qf482',
 'fg70g50hsla bk309-bu',
 '3309hrhf ec4566',
 'htn51g35ef nc010',
 'htnfe350157 bk218',
 'rs lc1610 bk387',
 'htnfe250038 wt409',
 '330 nc010',
 'b3 h gf30 bk 9005/u',
 'bm7300ths bk317',
 '3214',
 '5483',
 'b3 nh v2 nc 1102',
 'lft tpu-gf40-01-x',
 'b3 w nc 1102/uv/n/1',
 '73g40t nc010',
 '4341',
 '7335f nc010',
 'rs 32g10do bk236',
 'e41hsb nc010',
 '8m24 a30',
 '353bs2165/sf bianco',
 'qs870',
 'lft pbt-gf50-01',
 '830000550 neutro',
 'a3 gf30 bk 9005/tb',
 '77g43l bk031',
 'a2 wr gf30 nc 1102/2a',
 'fe290013 bk420',
 'b2 gf40 tf15 nc 1102/r',
 'fg50 nc010-bu',
 'rs lc1800 nc010',
 '70g15ef nc010',
 '1935r',
 'lft pp-gf40-0455 p10 titan black',
 'fe170075 bk242',
 '6146a',
 'a3 v0xi',
 'xt6 j10 hh gf15 nc 1102/r',
 '7474n',
 'a3 h j10 gf13 nc 1102/e',
 '2008fc',
 'jkx-1178',
 'pa6 gfxx model',
 'a2 h j10 gy 7035/e',
 'htn55g55lwsf bk752a-bu',
 'b3 j gf15 nc 1102/r',
 '189nsl050 nero micro s light',
 'dev 3209hrhf',
 'a3 w gf30 gy 7035/l',
 'lc6210 bk010 - bu',
 'lft pa66-cf20-02 af3004 natural',
 '70g50hsrx bk099',
 '520100a85',
 'htn54g35ef nc010-bu',
 'll501',
 'a3 rv0 yl 1021/a',
 'b3 hh kgf2515 gy 7001/e',
 'a3 gf25 v0',
 'lft tpu-gf50-01 af3001 natural',
 '1908',
 'pls93g35dh1 bk549',
 '9c602',
 'htn53g38ths bkb083-bu',
 '83f000962/k neutro',
 'b3 h gf35 bk 9005/2',
 '5424',
 'b3 gf30 v0 rd 3000/p',
 '2001',
 '54029za90/p nero',
 '73g30tgi bk267',
 'lft pp-gf50-10',
 'rs htn59g55lwsf wt164',
 'a3 j gf15 bk 9005/u',
 'lft pp-gf30-x293 p11/1x',
 'lft +pp-gf45-04cn15/10',
 'st801ahs bk010',
 'b3 hh j40 nc 1102/3',
 'htnfr51g35l nc010',
 'z ce197-50a',
 '21153/62 bianco snow',
 'a3 gf24 v0 yl 1018/c',
 'xs3 gf60 bk 9005/c ef',
 '52019ta85 grigio',
 'a3 rv0 yl 1018/s',
 'lft dev pp-gf40-0414 e-r221 black',
 'dev pp-gf40-0453 e-r221 black',
 'a3 rv0 bl 5017/t/yg',
 '8m35p a75',
 '830901765 nero',
 '83ee00a25 neutro',
 'a2 gf15 bk 9005/1',
 'qp603',
 '83e29za30 nero',
 'pp-gf40-0414 p7/10',
 'a3 hh gf50 bk 9005/ag',
 '7780',
 '2130',
 'b3 j gf15 bk 9005/u',
 'a4 hh gf50 nc 1102',
 '3114',
 'cfr-tp hdpe-cf65-01',
 'xs3 gf60 bg 1019/i/ef',
 'lft pp-gf60-0403 p10/10',
 'lft pa66-gf30-07',
 'a3 v2 a nc 1102/v',
 '744r',
 '73g15hsl eco-r 311 blk1',
 'pp-gf40-0414 p7',
 'htn53g50lrhf wt424',
 'bm73g15p bk317',
 '3300-2 old',
 'lft pa66-sf50-02 af3005',
 'dev a3 h gf15 v0',
 'a3 gf30 tf15 nc 1102/a',
 'a3 w gf30 gy 7012/h',
 '249n10075 nero',
 'lft tpu-gf40-01 ac3021 gray med',
 '70g50hsla bk039b',
 'jkx-1092',
 '8m3 d50',
 '5483',
 '3309hrhf ey4592',
 'cfr-tp pp-gf80-13',
 'r700-65a',
 'a3 rv0 gy 7038/p',
 'a3 gf30 tm2 gy 7022/a',
 'fe110007 nc010',
 'b3 gfb1515 bk 9011/e/uv',
 'b3 gf30 bk 9005/e',
 'a2 hhr j16 bk 9005/uv/2',
 '72g33w nc010',
 'b3 gf20 bk 9005/e',
 '74g33j nc010',
 '239nz5130 sofprene nero',
 'a3 rv0 gn 6001/e',
 '3202-2lm',
 '4597r',
 '8mf3 a75',
 'pls95g35dh1 nc010',
 'll612g',
 'lft cfr-tp pa66 cf60-02',
 'lft pp-gf30-02 ad 3002',
 '5780r',
 'a3 hhr gf30 bk 9005',
 'b3 gf25 v0 bk 9005/p/f1',
 'htn52g15hsl nc010',
 '8ad0125n/g4 neutro',
 'fe18005 nc010',
 'qs869',
 '70g10sc bk010',
 'a3 d10 nc 1102/c',
 '230c04070 crepe',
 'pbt-sf10-02',
 'b3 w mgf2515 nc 1102/1b',
 's511-65a',
 'lft pa66-gf60-02 p11/14',
 'fe5355 bk031',
 'a3 j gf25 v1 nc 1102/p',
 'a3 h bk 9005/2a',
 'a3 hhr gf30 nc 1102',
 'fr70m30gw gy450',
 '70g13hs1l nc010',
 'htn54g35hslr nc010',
 'a3 hh j10 gf13 nc 1102/e',
 '0001l',
 'a3 rv0 nc 1102/m',
 'lft pp-gf40-0501 black',
 'lft pp-gf30-0553 natural',
 '1662z',
 'c3 h v0 bk 9005',
 '830000872 neutro',
 'lf121',
 'htn53g50lr bn517',
 '2405mt natural a',
 'jkx-1038',
 '435-60a',
 'a3 rv0 gn 6018/s',
 'a3 h gf30 nc 1102/r',
 'xl11h',
 'a3 rv0 gy 7016/m/yg',
 'ptx20-02',
 '830000696 neutro',
 'lft pp-gf50-10',
 '830901545 nero',
 'lc7202 bk195',
 '5524',
 'a3 v2 gy 7045/p',
 'lft cfr-tp peek cf55-01',
 '7165',
 's 9064',
 'lft pps-gf50-01 af3001 natural',
 '1462z',
 'bq10',
 'a3 w gf35 gy 7040/s',
 'pp-gf60-0453 p10/10',
 '6500r',
 'pp-gf20-0503 black',
 'rs 3261thsl bk041a - bu',
 'htnfe150088 bk083',
 'fr73g20gwf gy372',
 'a3 d10 bk 9005/k',
 'jkx-1234',
 'lft pbt-cf40-08',
 'htnfe150016 bk337',
 'xt1 hh gf50 bk 9005/c',
 'pc310 nc010 - bu',
 '73g45l nc010',
 'a3 wr gf30 gy 7038/e',
 '7301l eco-r 331 bk300',
 'lft pp-gf40-02 ad3019 black',
 'a3 h bk 9005/s',
 'htnwrf51g30s nc010',
 '119n87188s nero',
 'lft pp-gf30-0403 fr01 v0 p10/10',
 'fe4200 bk136',
 'nvh95g35hsl bk314lm',
 'j-600r',
 'c3 hh gf60 bk 9005/z',
 '301abe260v ambra (rif. 1a002)(van)',
 '2004-2',
 'fr73m25gwf nc010',
 '4922n',
 'me601',
 'a3 gf25 v0xi bk 7021/x',
 'xt6 gf30 bk 9005/b',
 'base 21076/60r marrone talco',
 'cb100',
 '80g30arx eco-r 311 blk1',
 'xr800-70a',
 'jkx-1029',
 'jkx-1082',
 'b3 gf25 v0',
 '8e0 d50',
 'efe1068 nc010ta',
 'lft pp-gf50-0405 hf black',
 '830000865 neutro',
 'a3 gf30 v0 gy 7035',
 '219n07655r nero',
 'lft +pp-gf30-05cn05/10',
 'jkx-1124',
 'b3 h gf60 nc 1102/2',
 'jkx-1019',
 'b2 gf30 bk 600/lm',
 '389ns0170 nero',
 'a3 rv0 gy 7030/d',
 'a3 j gf30 bk 9005/p',
 'b3 w',
 'pp-gf30-0403 fr01 v0 p10/10',
 '80g33hs1l nc010',
 'lft pp-gf50-0405e black',
 '5434i',
 '3316a',
 'b3 tf10 nc 1102',
 '2302 gv1/30 lw',
 'c 27021 ast',
 'htnfe350064 bk544',
 'j600d',
 'xfr 6842 gf10',
 'c3 hh gf60 bk 9011/a',
 '40 nc010',
 '83f000960 neutro',
 'fe270020 bk039',
 '830000824 neutro',
 '1721',
 '2003 gv1/10',
 's337f-62a',
 '7416',
 'b3 v0 wt 9016/s',
 'lft pp-gf30-0551 black',
 '6142d',
 'efe3410 nc010',
 '830000561 neutro',
 '8ml35 001 a60',
 '2150',
 'lg450uv-d',
 'efe1117 nc010',
 '5715r',
 'b2 w nc 1102/1',
 '3300c',
 'xs3 s gf50 bk 9005/f',
 'base 21-307/60 9b blu',
 '219n01780 nero',
 's510-60a',
 '8mc a65',
 'fe5105 bk083',
 'jkx-1276',
 '83f000545 neutro',
 '215b06963 verde',
 '3300-2lm',
 '74g50arx eco-r 311 blk1',
 'fe130019 nc010',
 '830901616/2 nero',
 '3309hrt',
 '0f49a',
 '4879d',
 'fr95g25v0nh nc010-bu',
 'lft pp-gf40-10 black',
 'htn51lg50hsl bk083',
 '72g33w bk196',
 'a3 wr gf30 nc 1102/f',
 'jkx-1078',
 'dupl80g',
 'jkx-1034',
 's600f30 nc010',
 'a3 h j20 nc 1102/t',
 '405a/50',
 '830000918 neutro',
 'pp-gf60-25 ad3002 black',
 'a3 gf25 v0 gy 7044/j/yg',
 '830901545 nero',
 '8mcf3d a75',
 'b3 v0 gy 7016/b/yg',
 'sx90',
 'b3 v0 gy 7035/y',
 'b2 hh gf50 bk 9005/2',
 'lft cfr-tp pp cf60-13',
 'lx2002',
 'c 27021 tf',
 'b3 gf30 v0 or 2003',
 'a3 rv0 bk 9005/f',
 'b3 j10 bk 9005/u',
 '73g35ths bk511',
 'b3 w nc 1102/1',
 'a3 gf20 v0 gy 7035/s old',
 'a3 rv0 bn 8019/p',
 'a3 rv0 wt 9001/t',
 'lft pp-gf30-0553 eco-b 352 black',
 'lft pp-gf60-0406 p10/10',
 'htn330 nc010',
 'ds30-2',
 'c 9021 tf',
 'htn53g35hslr bk083',
 'fr70g25v0nh bk314lm',
 'htnfr520nh nc010',
 '73g30hsl bk416',
 'a2 hh gy 7024 /uv/2',
 'lw9330lt bk596',
 'a2 hh gf50 bk 9005/1b',
 '70g33w nc010',
 'lft pa66-gf60-02 ad3004 black',
 'xs3 gf40 bk 9005/v',
 'xt4 gf50 bk 9005/c',
 '2500 eco-b',
 'lft pps-sf6-01 af3005 natural',
 'lw140 hpxap-s2',
 'a3 hh gf15 bk 9005/e',
 'b2 hh j5 gf50 bk 9005/3',
 'hfb22',
 '91hs1 nc010',
 'ce219003 nc010',
 '70g30hslr eco-r bk099',
 'a3 gf25 v0xi nc 1101/l',
 '383px8665 panna',
 'lf121',
 'fr70g30v0nh1 or169-bu',
 'a3 whh gf30 gy 7035/2',
 'lft pa66-gf40-02p11',
 'lm90',
 'xs3 gf60 bk 9005/a/uv',
 'jkx-1068',
 'xs3 gf45 tfm12 gy 7022/a',
 '1172',
 'pe316',
 'pp-gf60-0453 bf p10/10',
 'jkx-1176',
 'a3 v2 bk 9005/u',
 'qp603',
 'fr82g30v0 bkb523',
 'a3 h j18 bk 9005/3',
 'rs lc4601 nc010 - bu',
 'dev 83ge9za60 nero',
 'mt2008',
 '830000952 neutro',
 'a3 hh gf30 nc 1102',
 'b3 gfb1515 tm2 bk 9011/uv',
 'tpu-gf60-01 af3001 natural',
 'a3 wr gf30 nc 1102/f',
 'lft cfr-tp pp cf60-13',
 'a3 h gf20 nc 1102/2',
 'a3 gf15 nc 1102/z',
 '83f000952 neutro',
 'htn53g50hslr nc010',
 'fe18005 nc010',
 'b3 v2 a gy 7035',
 'lft pp-gf20-0555 mistral blk',
 'a3 hh gf50 bk 9005/ag',
 '4321',
 'rs lc4601 bk010 - bu',
 'm30rs eco-b',
 'lft pa66-gf50-20 ad3007',
 'st801uv bk010',
 '5436d',
 'b2 gf30 bk 9005/1',
 'xl11h',
 'a3 gf20 v0 bk 9005/b',
 'base 38y/62 0c crepe',
 'a3 rv0 gn 6010/f',
 'b s25 v2 eco-r nc 1102',
 'ckx-5768',
 '312-60a',
 '9c601',
 '8mg a55',
 '6500hf',
 'wrf101a nc010',
 's327-65a',
 '5874',
 '220sv8160 neutro t.sughero',
 '460sn0155 neutro sughero',
 'ckx-5761 10/5358dw black',
 'a3 rv0 bk 9005/f',
 'lft pa66-cf40-01',
 'pp-gf30-0501 p8/13',
 'lft cfr-tp peek cf55-01',
 'a3 gf20 tf20 nc 1102/e',
 '830000640 neutro',
 'pls95g35dh1 nc010',
 'a3 rv0 gn 6010/f',
 'jkx-1022',
 '5000',
 '83fg00959/c neutro',
 'st830fr bk507',
 'a3 gf25 v0xi bk 9004/a',
 'dev pp-gf50-0405e black',
 'htnfr52g30l nc010',
 '83f000862 neutro',
 '8070',
 '70g35hslra4 nc010',
 's 4000p ct',
 '189nsslxx2 nero',
 'htn51g35hsl bk083j',
 '3315-32',
 'a3 rv0 rd 3000',
 '211a21065 ambra',
 '83e29za90 nero',
 'b3 gf20 v2 gy 7035/w',
 's 9243 xap2 eco-b',
 '3300-2 old',
 'st801w nc010',
 'pa6-sf10-01',
 'a3 hh j5 gf15 bk 8126/2',
 '1400fc',
 '83e000832/ab natural',
 'c 9021 gv3/10',
 'ckx-5661',
 '5448',
 'a3 rv0 gy 7011/p',
 'm90jg',
 '0041z',
 'xs3 gf50 bk 9005/v',
 '3309hrlm ed4222',
 '83f000962 neutro',
 '219n99965r nero',
 '5776b',
 'b3 gf60 nc 1102/p',
 'lw90-01',
 's217-65a',
 'a3 n v2 wt 9002/s',
 'mr130ar',
 'lft pp-gf30-0405 p10/10',
 'a3 j gf40 bk 9005/u',
 '2000',
 'a3 hh gf50 bk 9005/ag_old',
 'ce134000 bk223',
 'b3 h gf30 nc 1102/e',
 'lc7603 bk195',
 '2300b gv1/30fc',
 'lw9030 bk851',
 'b3 gf30 wt 9003/dm',
 'a3 j10 gf13 nc 1102/e',
 'a3 v2 yl 1023/w',
 '83h901808 nero',
 'xfr 6842 gf30 hrct',
 '9770r',
 'pa66-cf40-01',
 'a2 hh gf35 bk 9005 (nx)',
 'greentape 951p2',
 '6838',
 'lft pet-gf50-01-1',
 'jfx-0193',
 'fr70g25gwnh wt409',
 '6509hr',
 'lft cfr-tp tpu-cf60-01',
 'xt1 hh gf35 bk 9005/c',
 'fe5514 nc010',
 'c 9021 tf xap2',
 'htn54g15hslr nc010-bu',
 '70gb30hsl nc010',
 'htn52g35hsl nc010',
 '83f000951 neutro',
 'htnfe150005 bk083',
 '72g33l bk031',
 'pe828',
 '189nsslxx3 nero',
 '83f000971 neutro',
 's 27072 ws 10/1570',
 'b3 gf30 v0 wt 9003/p',
 'lc7602 bk010a',
 'fn727 nc010a',
 'b3 w gf25 v0e bk 9004/yg',
 'lft pp-gf30-0455 p10/10',
 'ckx-5589',
 'b2 hh gf50 bk 9005',
 'c 27021 tf',
 '490hs bk010',
 'lft cfr-tp pps-cf67-01',
 'lf142',
 'htnfe150099 wt212',
 '5880',
 '54059za60/ct nero',
 '0031z',
 'a3 rv0 or 2003/x',
 'rs htn59g55lwsf nc010',
 'b2 gf30 bk 9005 (nx)',
 '70g13l bk239',
 'a3 rv0 wt 9010/p',
 'b3 w gf30 rd 3000/p',
 'lf161',
 'lc7601 nc010 - bu',
 'xfr 6842 gf30 hrct',
 'a3 rv0 bl 5015/y',
 'a3 hh gf30 or 2003/t',
 'fe150065 nc010',
 '2414mt',
 '830901957 nero',
 'pp-gf30-0551 eco-b 352 black',
 'b3 v2 gy 7035/e',
 'pa6-gf30-03 fr01 v0 p10/10',
 '8ef a55',
 '1711',
 '7292',
 'a3 rv0 gy 7035/p',
 'fr98g30v0nh2 n911alm',
 'st801hs bk010',
 'lft pa66-gf40-02 ad3004 black',
 'jkx-1045',
 'lft pp-gf40-0455 eco-b 352 soul 4pk black',
 'b3 gf25 nc 1102',
 'a3 h d7 gy 7035/2',
 '239bz4773/sf blu peacoat p. 19-3',
 'xs3 j05 gf35 bk 9005/v',
 'a3 gf25 v0 bk 9005',
 'fe5349 bk083m',
 'e50 nc010',
 '830000541 neutro',
 'a3 hh bk 9005/1',
 'a3 rv0 bl 5014/p',
 'greentape 9k7v',
 '103hsl nc010',
 '73g40hsl nc010',
 'a3 h gf33 nc 1102/2a',
 'mt12u03 eco-b',
 '8031',
 'fr684nh1 or162',
 'c3 gf10 tf20 v2xi nc 1101/r',
 '2302hf gv1/30',
 'lft pa66-gf50-02 p11/14',
 's600f40 bk851',
 'd3200lc',
 'lft pa66-gf50-02 ad3019 black',
 'st801 nc010a',
 '8452',
 'greentape 951pt',
 'a3 j gf30 bk 9005/p',
 'lgc90-qx',
 'j-600r',
 '490 nc010a',
 'j602',
 'b3 gf30 v0 bk 9005/c',
 'rs htn59g55e bk083',
 '3216hr',
 'a3 h gf25 v0 gy 7038/r',
 'a2 gf33 bk 2000/uv/1',
 'pp-gf60-02 ad3019',
 'a2 hhr gf30 bk 9005 (nx)',
 'fe5171 nc010',
 '83k901990 nero',
 'lt70g30hslr bk494',
 'xt4 gf30 v0i gy 7035/a/yg',
 '3300a',
 'b3 h gy 20396/uv/o/1',
 'xt6 j10 hh gf15 nc 1102/r',
 'b2 h gf15/1',
 'xt 20',
 'b3 w gb30 bk 9005/u',
 'dev 5035-32-05',
 'sk645fr nc010',
 '83f00y602 neutro',
 'dmx65g30ah bk407',
 'a3 h j20 nc 1102/2',
 '83mm00a55 neutro',
 'pp-gf30-10 ad 3019 black',
 '6407',
 'b3 j gf05 bk 9005/u',
 '120sv1865 neutro t.sughero',
 'fr70g30gwnh nc010',
 'lft pp-gf60-0403 hf black',
 'nkx-8002',
 'a3 rv0 bl 5019/m',
 '249n18865 nero',
 'lft pps-sf50-03',
 'b3 hw gf25 nc 1102',
 '830000861 neutro',
 'a3 rv0 gn 6017/n',
 'intexar te-11c',
 'a3 gf25 v0xi',
 '0012z',
 '5725b',
 'lft pa66-gf50-02 p7',
 'lft pom-sf4-03',
 'lft pp-gf60-02 ad3019',
 '1921',
 '4014',
 '83fb00962 g',
 'b3 w gf33 nc 1102/fd/1',
 '83fs00543 neutro',
 '7331f nc010',
 'b3 mgf2515 bk 9005/n',
 '350phs2 nc010',
 '70g13hs1l bk031',
 'a3 gf25 v0 gy 7001/i',
 'ce2055 nc010-bu',
 'ckx-5698',
 'fg621f50 nc010',
 'm30rs eco-b',
 'lp dev ',
 '83ee00a25 neutro',
 'fe150065 nc010',
 'fg70g30hslr nc010',
 'fe3218 nc010',
 'efe4179hs bk473',
 'htnfr52g30nhf bk337',
 'fr82g33v1 bkb523',
 '444-80a-100 natural',
 's229-55a',
 'jkx-979',
 'jkx-1021',
 'b3 gf20 v2 gy 7035/w',
 's600f20 nc010',
 '83ff00a84 neutro',
 'c 9021 sw xap2 ls',
 'base 21115/60 ghiac 3gs06 talco',
 '7345w',
 '70g33hs1l gyb255',
 '137vz5068/sf viola 19-3731',
 'lft pa66-gf50-02-natural',
 '219n98865r nero',
 'c 27021 as',
 'qs876',
 '8ks9p1a60 nero',
 'a3 gf20 v0 nc 1102',
 'b3 gf50 bk 269/1',
 'lm140lg',
 'fr685nh2 or168',
 's511-50a',
 'pbt-sf6-03',
 'a3 e gf25 v0',
 '6129 nc010',
 'htnocpfe350157 bk218',
 '831000911 neutro',
 'lf162',
 '74g33ehsl bk354',
 '1721',
 'lc7601 bk010 - bu',
 'lwfr684nh2 bk591lm',
 'b3 hh d8/1',
 'htnfe18502 bk434a',
 'bm7300fnh bk317',
 'slw9030 bk851',
 'a3 rv0 gn 6018/d',
 '2002fc',
 '502200a40 neutro',
 'lc7603 bk195',
 '4330',
 'xgc25 xap eco-c 672',
 '70g33l bk031',
 'z s825-55a/ce197-55a',
 'uv25z xap2',
 'rs lc1600 nc010 - bu',
 'lc6200 bk385 - bu',
 'lft pa66-gf20-02p11/12',
 'a3 hh gf30 bk 9005/f',

In [218]:
filtered_gradenames = filtered_gradenames + random.sample(without_prefix2, 500)
filtered_gradenames = [x.strip('+/-') for x in filtered_gradenames]
filtered_gradenames[-20:]

['5450h',
 '9c602',
 'z ce198-60a',
 'fr50 nc010',
 '540200a45 neutro',
 '830308914 bianco',
 'xs3 gf60 nc 1102/e',
 'mt8f01',
 'jkx-1049',
 'b3 h gf35 bk 9005/2',
 '219n10155r nero',
 'b3 hh gfb1020 bk 9005/2',
 'xs3 gf60 wt 9016/c ef',
 '8ks901a90/h nero',
 'a3 v2 a bk 9005/g',
 '350phs3 bk010',
 '185bs8060 beige micro',
 'lft roving fv vergine ms500',
 'xt4 gf30 v0i bk 9005/d',
 'b3 w gf33 nc 1102/fd/1']

In [219]:
len(filtered_gradenames)

4934

In [220]:
sorted(filtered_gradenames, key=len)[:100]

['im',
 'pb',
 'hte',
 'xgc',
 'lof',
 'hfs',
 'ice',
 'xap',
 'fit',
 'dym',
 'icf',
 'htn',
 'wrf',
 'hsl',
 'xfr',
 'sea',
 'hhr',
 'hrt',
 'frhr',
 'hslr',
 'lof2',
 'xap2',
 'hrlm',
 '0030',
 '5731',
 '3216',
 '5028',
 '4321',
 '2004',
 '5727',
 '7881',
 '2071',
 '1106',
 'lft ',
 '2031',
 '5418',
 '3316',
 '4047',
 '6474',
 '7105',
 '2011',
 '7105',
 '7082',
 '2041',
 '4195',
 's150',
 '8173',
 '1959',
 'pcxxx',
 'eco-r',
 'eco r',
 'sd001',
 'eco-b',
 'eco b',
 'scxxx',
 'impet',
 '5450h',
 'pe316',
 'thr35',
 '1401a',
 'j-600',
 'me614',
 'qp603',
 '3300a',
 'hfb21',
 '1748r',
 'qs874',
 '5082r',
 'hfb31',
 'bq331',
 'qm44h',
 'ht602',
 'pe825',
 '5504n',
 '5063d',
 'bq131',
 'e8 uv',
 'qq620',
 '0022z',
 'll602',
 'bq922',
 '9475r',
 '4597r',
 '0001b',
 '0f79a',
 '2008a',
 'pe510',
 '4879d',
 'lf79a',
 'cb200',
 '0f30e',
 'j600w',
 '7499r',
 'ht603',
 '8152b',
 '1642z',
 'qp601',
 'lf79a',
 'bq226',
 '5450h']

## Templates and Data Generation

In [221]:
st = time.time() 

feature_count = 0
processing_count = 0
del_count = 0

brand_count = 0
polymer_count = 0
app_count = 0

nsf_count = 0
water_count = 0
railway_count = 0
auto_cert_count = 0

prop_count = 0
prop_range_count = 0
prop_abb_count = 0

ul_prop_count = 0
ul_sub_prop_count = 0
filler_count = 0

region_count = 0
ignore_terms_count = 0

# queries_thershold = 1000
auto_th = 2500
rail_th = 1500
water_th = 1000
nsf_th = 1000


prop_th = 2000
prop_rm_th = 1000
prop_abb_th = 1000

fill_th = 2500
ul_prop_th = 1500
ul_sub_prop_th = 1400


process_th = 3500
feat_th = 6500
del_th = 2000

brand_th = 6000
poly_th = 6500
app_th = 3000
region_th = 3000
ignore_terms_th = 2000

auto_th_reached = False
rail_th_reached = False
water_th_reached = False
nsf_th_reached = False

prop_th_reached = False
prop_rm_th_reached = False
prop_abb_th_reached = False

fill_th_reached = False
ul_prop_th_reached = False
ul_sub_prop_th_reached = False

process_th_reached = False
feat_th_reached = False
del_th_reached = False

brand_th_reached = False
poly_th_reached = False
app_th_reached = False

region_th_reached = False
ignore_terms_th_reached = False

status = [  
    'auto_th_not_reached',  
    'rail_th_not_reached',  
    'water_th_not_reached',  
    'nsf_th_not_reached',  
    'prop_th_not_reached',  
    'prop_rm_th_not_reached',  
    'prop_abb_th_not_reached',  
    'fill_th_not_reached',  
    'ul_prop_th_not_reached',  
    'ul_sub_prop_th_not_reached',  
    'process_th_not_reached',  
    'feat_th_not_reached',  
    'del_th_not_reached',  
    'brand_th_not_reached',  
    'poly_th_not_reached',  
    'app_th_not_reached',
    'region_th_not_reached',
    'ignore_terms_th_not_reached',   
]

generated_data = []
# while any(x < queries_thershold for x in [feature_count, processing_count, del_count, brand_count, polymer_count]):    
while auto_cert_count < auto_th or railway_count < rail_th or nsf_count < nsf_th or water_count < water_th \
    or prop_count < prop_th or prop_range_count < prop_rm_th or prop_abb_count < prop_abb_th \
    or filler_count < fill_th or  ul_prop_count < ul_prop_th or  ul_sub_prop_count < ul_sub_prop_th \
    or processing_count < process_th or feature_count < feat_th or del_count < del_th \
    or brand_count < brand_th or polymer_count < poly_th or app_count < app_th or region_count < region_th:        
  
    if not auto_th_reached and auto_cert_count >= (auto_th - 1):  
        status.remove('auto_th_not_reached')  
        auto_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not rail_th_reached and railway_count >= (rail_th - 1):  
        status.remove('rail_th_not_reached')  
        rail_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not water_th_reached and water_count >= (water_th - 1):  
        status.remove('water_th_not_reached')  
        water_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not nsf_th_reached and nsf_count >= (nsf_th - 1):  
        status.remove('nsf_th_not_reached')  
        nsf_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not prop_th_reached and prop_count >= (prop_th - 1):  
        status.remove('prop_th_not_reached')  
        prop_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not prop_rm_th_reached and prop_range_count >= (prop_rm_th - 1):  
        status.remove('prop_rm_th_not_reached')  
        prop_rm_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not prop_abb_th_reached and prop_abb_count >= (prop_abb_th - 1):  
        status.remove('prop_abb_th_not_reached')  
        prop_abb_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not fill_th_reached and filler_count >= (fill_th - 1):  
        status.remove('fill_th_not_reached')  
        fill_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not ul_prop_th_reached and ul_prop_count >= (ul_prop_th - 1):  
        status.remove('ul_prop_th_not_reached')  
        ul_prop_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not ul_sub_prop_th_reached and ul_sub_prop_count >= (ul_sub_prop_th - 1):  
        status.remove('ul_sub_prop_th_not_reached')  
        ul_sub_prop_th_reached = True  
        print("time taken: ", int(time.time() - st))  
        print("\n", status, "\n")  
      
    if not process_th_reached and processing_count >= (process_th - 1):
        status.remove('process_th_not_reached')
        process_th_reached = True
        print("time taken: ", int(time.time() - st))
        print("\n", status, "\n")
    
    if not feat_th_reached and feature_count >= (feat_th - 1):
        status.remove('feat_th_not_reached')
        feat_th_reached = True
        print("time taken: ", int(time.time() - st))
        print("\n", status, "\n")
    
    if not del_th_reached and del_count >= (del_th - 1):
        status.remove('del_th_not_reached')
        del_th_reached = True
        print("time taken: ", int(time.time() - st))
        print("\n", status, "\n")
    
    if not brand_th_reached and brand_count >= (brand_th - 1):
        status.remove('brand_th_not_reached')
        brand_th_reached = True
        print("time taken: ", int(time.time() - st))
        print("\n", status, "\n")
    
    if not poly_th_reached and polymer_count >= (poly_th - 1):
        status.remove('poly_th_not_reached')
        poly_th_reached = True
        print("time taken: ", int(time.time() - st))
        print("\n", status, "\n")
    
    if not app_th_reached and app_count >= (app_th - 1):
        status.remove('app_th_not_reached')
        app_th_reached = True
        print("time taken: ", int(time.time() - st))
        print("\n", status, "\n") 

    if not region_th_reached and region_count >= (region_th - 1):
        status.remove('region_th_not_reached')
        region_th_reached = True
        print("time taken: ", int(time.time() - st))
        print("\n", status, "\n")

    if not ignore_terms_th_reached and ignore_terms_count >= (ignore_terms_th - 1):
        status.remove('ignore_terms_th_not_reached')
        ignore_terms_th_reached = True
        print("time taken: ", int(time.time() - st))
        print("\n", status, "\n")
    
    processing = random.choice(processing_types).lower()
    feature = random.choice(product_functions).lower()
    delivery_form = random.choice(delivery_forms).lower()   
    brand = random.choice(all_brands_without_syns).lower()       
    polymer = random.choice(all_polymers).lower()       
    grade = random.choice(filtered_gradenames).lower()
    is_grade_without_space = random.choice([False, False, False, False, False, False, True])
    if is_grade_without_space:
        grade = grade.replace(' ', '')
    nsf = random.choice(nsf_certifications).lower()
    water = random.choice(water_certifications_combinations)
    water_name = water[0].lower()
    railway = random.choice(railway_certifications_combinations)

    app_ind = random.choice(all_apps_industries)
    application = app_ind[0]
    industry = app_ind[1]

    continent, continent_region = random.choice(all_regions_data['continent'])
    country, country_region = random.choice(all_regions_data['country'])
    state, state_region = random.choice(all_regions_data['state'])
    city, city_region = random.choice(all_regions_data['city'])
    competitor_grade = random.choice(all_cgrades)
    # for suffix in remove_suffixes:
    #     competitor_grade = re.sub(r'{}$'.format(re.escape(suffix)), '', competitor_grade) 
        
    competitor_grade = re.sub(r'^\((.*)\)$', r'\1', competitor_grade)
    competitor_grade = competitor_grade.strip()
    is_comp_grade_without_space = random.choice([False, False, False, False, False, False, True])
    if is_comp_grade_without_space:
        competitor_grade = competitor_grade.replace(' ', '')

    ignore_term = random.choice(ignore_terms)
    ignore_term2 = random.choice(ignore_terms)
    while ignore_term2 == ignore_term:
        ignore_term2 = random.choice(ignore_terms)
    
    k = random.choice([0, 1, 2])
    if k==0:
        railway_name = railway[0]
    elif k==1:
        railway_name = railway[0].split(' (')[0]
    elif k==2:
        railway_name = "".join(railway[0].split(' (')[0].split('-'))
        
    railway_name = ' '.join(railway_name.split()).lower()
    
    
    processing2 = random.choice(processing_types).lower()        
    while processing2 == processing:
        processing2 = random.choice(processing_types).lower()
        
    feature2 = random.choice(product_functions).lower()
    while feature2 == feature:
        feature2 = random.choice(product_functions).lower()
         
    delivery_form2 = random.choice(delivery_forms).lower()
    while delivery_form2 == delivery_form:
        delivery_form2 = random.choice(delivery_forms).lower()

    brand2 = random.choice(all_brands_without_syns).lower()      
    while brand2 == brand:
        brand2 = random.choice(all_brands_without_syns).lower()
    
    polymer2 = random.choice(all_polymers).lower()
    while polymer2 == polymer:
        polymer2 = random.choice(all_polymers).lower()

    is_processing_syn = random.choice([False, True, True, True])
    if is_processing_syn and processing in processing_syns:
        processing = random.choice(processing_syns[processing])
        
    is_processing_syn = random.choice([False, True, True, True])
    if is_processing_syn and processing2 in processing_syns:
        processing2 = random.choice(processing_syns[processing2])

    is_feature_syn = random.choice([False, True, True, True])
    if is_feature_syn and feature in feature_syns:
        feature = random.choice(feature_syns[feature])
        
    is_feature_syn = random.choice([False, True, True, True])
    if is_feature_syn and feature2 in feature_syns:
        feature2 = random.choice(feature_syns[feature2])

    is_delivery_syn = random.choice([False, True, True, True])
    if is_delivery_syn and delivery_form in delivery_form_syns:
        delivery_form = random.choice(delivery_form_syns[delivery_form])
        
    is_delivery_syn = random.choice([False, True, True, True])
    if is_delivery_syn and delivery_form2 in delivery_form_syns:
        delivery_form2 = random.choice(delivery_form_syns[delivery_form2])

    is_polymer_syn = random.choice([False, True, True, True])
    if is_polymer_syn and polymer in polymer_syns:
        polymer = random.choice(polymer_syns[polymer])
        
    is_polymer_syn = random.choice([False, True, True, True])
    if is_polymer_syn and polymer2 in polymer_syns:
        polymer2 = random.choice(polymer_syns[polymer2])

    is_brand_syn = random.choice([False, True, True, True])
    if is_brand_syn and brand in brand_syns:
        brand = random.choice(brand_syns[brand])

    is_brand_syn = random.choice([False, True, True, True])
    if len(brand)<4:
        while len(brand2)>3:
            brand2 = random.choice(all_brands_without_syns).lower()
        
            brand_temp = brand            
            if brand_temp in brand_syn_mapping:
                brand_temp = brand_syn_mapping[brand_temp]

            while brand2 == brand_temp:
                brand2 = random.choice(all_brands_without_syns).lower()

            brand2 = random.choice(brand_syns[brand2])

    elif is_brand_syn and brand2 in brand_syns:
        brand2 = random.choice(brand_syns[brand2])
        if len(brand2)<4:
            while len(brand2)<4:
                brand2 = random.choice(all_brands_without_syns).lower()
            
                brand_temp = brand            
                if brand_temp in brand_syn_mapping:
                    brand_temp = brand_syn_mapping[brand_temp]
    
                while brand2 == brand_temp:
                    brand2 = random.choice(all_brands_without_syns).lower() 

                brand2 = random.choice(brand_syns[brand2])

    auto_cert = random.choice(auto_certifications)
    oem_name = auto_cert[0].lower()
    if oem_name in auto_syns:
        oem_name = random.choice(auto_syns[oem_name])
    auto_cert_name = auto_cert[1].lower()
    
    auto_cert2 = random.choice(auto_certifications)
    oem_name2 = auto_cert2[0].lower()
    if oem_name2 in auto_syns:
        oem_name2 = random.choice(auto_syns[oem_name2])
    auto_cert_name2 = auto_cert2[1].lower()
    
    while auto_cert2==auto_cert:
        auto_cert2 = random.choice(auto_certifications)
        oem_name2 = auto_cert2[0].lower()
        if oem_name2 in auto_syns:
            oem_name2 = random.choice(auto_syns[oem_name2])
        auto_cert_name2 = auto_cert2[1].lower()

    auto_cert_name = random.choice([auto_cert_name, auto_cert_name, auto_cert_name, auto_cert_name.replace(' ', ''), re.sub('[^A-Za-z0-9]+', '', auto_cert_name), re.sub('[^A-Za-z0-9]+', '', auto_cert_name), re.sub("(\s+)", " ", re.sub('[^A-Za-z0-9]+', ' ', auto_cert_name)).strip(), re.sub("(\s+)", " ", re.sub('[^A-Za-z0-9]+', ' ', auto_cert_name)).strip()])    
    auto_cert_name2 = random.choice([auto_cert_name2, auto_cert_name2, auto_cert_name2, auto_cert_name2.replace(' ', ''), re.sub('[^A-Za-z0-9]+', '', auto_cert_name2), re.sub('[^A-Za-z0-9]+', '', auto_cert_name2), re.sub("(\s+)", " ", re.sub('[^A-Za-z0-9]+', ' ', auto_cert_name2)).strip(), re.sub("(\s+)", " ", re.sub('[^A-Za-z0-9]+', ' ', auto_cert_name2)).strip()])

    railway2 = random.choice(railway_certifications_combinations)
    k = random.choice([0, 1, 2])
    if k==0:
        railway_name2 = railway2[0]
    elif k==1:
        railway_name2 = railway2[0].split(' (')[0]
    elif k==2:
        railway_name2 = "".join(railway2[0].split(' (')[0].split('-'))
        
    railway_name2 = ' '.join(railway_name2.split()).lower()
    
    while railway2==railway:
        railway2 = random.choice(railway_certifications_combinations)
        k = random.choice([0, 1, 2])
        if k==0:
            railway_name2 = railway2[0]
        elif k==1:
            railway_name2 = railway2[0].split(' (')[0]
        elif k==2:
            railway_name2 = "".join(railway2[0].split(' (')[0].split('-'))
            
        railway_name2 = ' '.join(railway_name2.split()).lower()

    property_details , property = get_property()
    property2_details , property2 = get_property()
    
    while property2 == property:
        property2_details , property2 = get_property()

    property_abb_details , property_abb = get_property_abb()
    property_abb2_details , property_abb2 = get_property_abb()

    while property_abb2 == property_abb or (" " in property_abb2 and " " not in property_abb) or (" " in property_abb and " " not in property_abb2):
        property_abb2_details , property_abb2 = get_property_abb()

    common_modifier = random.choice([False, False, False, True])
    property_rm_details , property_rm = get_property_range_modifier(common_modifier)

    property_rm2_details , property_rm2 = get_property_range_modifier(common_modifier)
    while property_rm2 == property_rm:
        property_rm2_details , property_rm2 = get_property_range_modifier(common_modifier)

    filler_details, filler = get_random_filler()
    
    ul_property_details, ul_property = get_ul_property()
    ul_property2_details, ul_property2 = get_ul_property()
    while ul_property2 == ul_property:
        ul_property2_details, ul_property2 = get_ul_property()

    ul_sub_property_details, ul_sub_property = get_ul_sub_property()
    # this will add two min thichness
    # ul_sub_property2_details, ul_sub_property2 = get_ul_sub_property()
    # while ul_sub_property2 == ul_sub_property:
    #     ul_sub_property2_details, ul_sub_property2 = get_ul_sub_property()

    is_feature_spell_correct = False
    corrected_feature = ''
    if len(feature.replace('-', ' ').replace('/', ' ').split()[0])>4:
        is_feature_spell_correct = random.choice([False, False, False, False, False, False, False, False, False, False, False, False, False, True])
        if is_feature_spell_correct:
            corrected_feature = feature
            n = random.choice(range(len(feature)))
            if len(feature.split()[0])>4:
                feature = random.choice([feature[1:], feature[:n] + feature[n+1:]])
            else:
                feature = feature[:n] + feature[n+1:]

    templates = [ 
        (f"{railway_name.lower().replace('r', 'r ').replace('h', 'h ').replace('v0', 'v 0')}", "{railway_name}"),
        (f"{railway_name.lower().replace('r', 'r-').replace('h', 'h-').replace('v0', 'v-0')}", "{railway_name}"),
        (f"{railway_name.lower().replace('(en 45545-2)', '(en 455452)')}", "{railway_name}"),
        (f"{railway_name.lower().replace('(en 45545-2)', 'en 455452')}", "{railway_name}"),
        (f"{railway_name.lower().replace('(en 45545-2)', 'en')}", "{railway_name}"),
        (f"{railway_name.lower().replace(' ', '')}", "{railway_name}"),
        (f"{railway_name}", "{railway_name}"),
        
        (f"{railway_name} {railway_name2}", "{railway_name} {railway_name2}"),
        (f"{railway_name} and {railway_name2}", "{railway_name} and {railway_name2}"),
        (f"{railway_name} or {railway_name2}", "{railway_name} or {railway_name2}"),
        (f"{railway_name}, {railway_name2}", "{railway_name}, {railway_name2}"),
        
        (f"{auto_cert_name}", "{auto_cert_name}"),
        (f"{auto_cert_name} approval", "{auto_cert_name} approval"),
        (f"{auto_cert_name} auto spec", "{auto_cert_name} auto spec"),
        (f"{auto_cert_name} auto approval", "{auto_cert_name} auto approval"),
        (f"{auto_cert_name}", "{auto_cert_name}"),
        (f"{auto_cert_name} approval", "{auto_cert_name} approval"),
        (f"{auto_cert_name} auto spec", "{auto_cert_name} auto spec"),
        (f"{auto_cert_name} auto approval", "{auto_cert_name} auto approval"),
        
        (f"{oem_name}", "{oem_name}"),
        (f"{oem_name} approval", "{oem_name} approval"),
        (f"{oem_name} auto spec", "{oem_name} auto spec"),
        (f"{oem_name} auto approval", "{oem_name} auto approval"),

        (f"{oem_name} {auto_cert_name}", "{oem_name} {auto_cert_name}"),
        # (f"{oem_name}: {auto_cert_name}", "{oem_name}: {auto_cert_name}"),
        (f"{oem_name} - {auto_cert_name}", "{oem_name} - {auto_cert_name}"),
        (f"{oem_name} ({auto_cert_name})", "{oem_name} ({auto_cert_name})"),
        (f"{oem_name} auto specs {auto_cert_name}", "{oem_name} auto specs {auto_cert_name}"),
        # (f"{oem_name} auto specs approved {auto_cert_name}", "{oem_name} auto specs {auto_cert_name}"),
        
        (f"{auto_cert_name} {auto_cert_name2}", "{auto_cert_name} {auto_cert_name2}"),
        (f"{auto_cert_name} {auto_cert_name2}", "{auto_cert_name} {auto_cert_name2}"),
        (f"{auto_cert_name} {auto_cert_name2} approval", "{auto_cert_name} {auto_cert_name2} approval"),
        (f"{auto_cert_name} {auto_cert_name2} auto spec", "{auto_cert_name} {auto_cert_name2} auto spec"),
        # (f"{auto_cert_name} {auto_cert_name2} auto approval", "{auto_cert_name} {auto_cert_name2} auto approval"),
        
        (f"{auto_cert_name} and {auto_cert_name2}", "{auto_cert_name} and {auto_cert_name2}"),
        (f"{auto_cert_name} + {auto_cert_name2}", "{auto_cert_name} + {auto_cert_name2}"),
        (f"{auto_cert_name} or {auto_cert_name2}", "{auto_cert_name} or {auto_cert_name2}"),
        (f"{auto_cert_name}, {auto_cert_name2}", "{auto_cert_name}, {auto_cert_name2}"),
        
        (f"{oem_name} {auto_cert_name} {oem_name2} {auto_cert_name2}", "{oem_name} {auto_cert_name} {oem_name2} {auto_cert_name2}"),
        (f"{oem_name} {auto_cert_name} and {oem_name2} {auto_cert_name2}", "{oem_name} {auto_cert_name} and {oem_name2} {auto_cert_name2}"),
        (f"{oem_name} {auto_cert_name} or {oem_name2} {auto_cert_name2}", "{oem_name} {auto_cert_name} or {oem_name2} {auto_cert_name2}"),
        # (f"{oem_name}: {auto_cert_name} {oem_name2}: {auto_cert_name2}", "{oem_name}: {auto_cert_name} {oem_name2}: {auto_cert_name2}"),
        (f"{oem_name} - {auto_cert_name} {oem_name2} - {auto_cert_name2}", "{oem_name} - {auto_cert_name} {oem_name2} - {auto_cert_name2}"),
        (f"{oem_name} ({auto_cert_name}) {oem_name2} ({auto_cert_name2})", "{oem_name} ({auto_cert_name}) {oem_name2} ({auto_cert_name2})"),
        
        (f"{property_rm}", "{property_rm}"),
        (f"{property_rm} {property_rm2}", "{property_rm} {property_rm2}"),
        (f"{property_rm} and {property_rm2}", "{property_rm} and {property_rm2}"),
        (f"{property_rm} or {property_rm2}", "{property_rm} or {property_rm2}"),
        (f"{property_rm},  {property_rm2}", "{property_rm}, {property_rm2}"),
        
        (f"{property_rm} {property} {feature} {filler}", "{property_rm} {property} {feature} {filler}"),
        (f"{property_rm} {property} good {feature} {filler}", "{property_rm} {property} good {feature} {filler}"),
        (f"{property_rm} and {property} high {feature} with {filler}", "{property_rm} and {property} high {feature} with {filler}"),
        (f"{property_rm} and {property} excellent {feature} with {filler}", "{property_rm} and {property} excellent {feature} with {filler}"),
        
        (f"{filler} {feature} {property_rm} {property}", "{filler} {feature} {property_rm} {property}"),
        (f"{property_rm}, {property}, {feature}, {filler}", "{property_rm}, {property}, {feature}, {filler}"),
        (f"{property} good {feature} {filler} {property_rm}", "{property} good {feature} {filler} {property_rm}"),
        (f"{property} and high {feature} {property_rm} with {filler}", "{property} and high {feature} {property_rm} with {filler}"),
        (f"excellent {feature} {property_rm} and {property} with {filler}", "excellent {feature} {property_rm} and {property} with {filler}"),
        
        (f"{property_rm} {property}", "{property_rm} {property}"),
        (f"{property_rm}, {property}", "{property_rm}, {property}"),
        (f"{property_rm} and {property}", "{property_rm} and {property}"),
        (f"{property_rm} or {property}", "{property_rm} or {property}"),
        (f"{property_rm} + {property}", "{property_rm} + {property}"),
        
        (f"{property_rm} {feature}", "{property_rm} {feature}"),
        (f"{property_rm} with excellent {feature}", "{property_rm} with excellent {feature}"),
        (f"{property_rm} good {feature}", "{property_rm} good {feature}"),
        (f"{property_rm}, high {feature}", "{property_rm}, high {feature}"),
        (f"{property_rm} and {feature}", "{property_rm} and {feature}"),
        (f"{property_rm} + {feature}", "{property_rm} + {feature}"),
        
        (f"{property_rm} {filler}", "{property_rm} {filler}"),
        (f"{property_rm}, {filler}", "{property_rm}, {filler}"),
        (f"{property_rm} and {filler}", "{property_rm} and {filler}"),
        (f"{property_rm} + {filler}", "{property_rm} + {filler}"),
        
        (f"good {feature}", "good {feature}"),
        (f"{grade} with excellent {feature}", "{grade} with excellent {feature}"),
        (f"{brand} with good {feature} {feature2}", "{brand} with good {feature} {feature2}"),
        (f"{brand} with good {feature} and {feature2}", "{brand} with good {feature} and {feature2}"),
        
        (f"grade with {property_abb}", "grade with {property_abb}"),
        (f"material with {property_abb}", "material with {property_abb}"),
        (f"{property_abb}", "{property_abb}"),
        (f"{property_abb}", "{property_abb}"),
        (f"{property_abb}", "{property_abb}"),
        (f"{property_abb} {property_abb2}", "{property_abb} {property_abb2}"),
        (f"{property_abb}, {property_abb2}", "{property_abb}, {property_abb2}"),
        (f"{property_abb} and {property_abb2}", "{property_abb} and {property_abb2}"),
        (f"{property_abb} or {property_abb2}", "{property_abb} or {property_abb2}"),
        
        (f"{ul_property}", "{ul_property}"),
        (f"{ul_property}", "{ul_property}"),
        
        (f"{ul_property} {ul_property2}", "{ul_property} {ul_property2}"),
        (f"{ul_property} {ul_property2}", "{ul_property} {ul_property2}"),
        
        
        (f"{ul_sub_property}", "{ul_sub_property}"),       
        (f"{ul_sub_property}", "{ul_sub_property}"),       

        # (f"{ul_sub_property} {ul_sub_property2}", "{ul_sub_property} {ul_sub_property2}"),
        # (f"{ul_sub_property} {ul_sub_property2}", "{ul_sub_property} {ul_sub_property2}"),
        
        (f"{filler}", "{filler}"),
        (f"{filler}", "{filler}"),

        (f"{brand} {brand2}", "{brand} {brand2}"),
        (f"{brand} {brand2}", "{brand} {brand2}"),
        (f"{brand} and {brand2}", "{brand} and {brand2}"),
        (f"{brand}, {brand2}", "{brand}, {brand2}"),

        (f"{brand} {brand2} {polymer}", "{brand} {brand2} {polymer}"),
        (f"{brand} {brand2} {polymer}", "{brand} {brand2} {polymer}"),
        (f"{brand} {brand2} and {polymer}", "{brand} {brand2} and {polymer}"),
        (f"{brand}, {brand2}, {polymer}", "{brand}, {brand2}, {polymer}"),

        (f"{brand} {brand2} {feature}", "{brand} {brand2} {feature}"),
        (f"{brand} {brand2} {feature}", "{brand} {brand2} {feature}"),
        (f"{brand} {brand2} and {feature}", "{brand} {brand2} and {feature}"),
        (f"{brand}, {brand2}, {feature}", "{brand}, {brand2}, {feature}"),

        (f"{brand} {brand2} {filler}", "{brand} {brand2} {filler}"),
        (f"{brand} {brand2} {filler}", "{brand} {brand2} {filler}"),
        (f"{brand} {brand2} and {filler}", "{brand} {brand2} and {filler}"),
        (f"{brand}, {brand2}, {filler}", "{brand}, {brand2}, {filler}"),    
        
        (f"{brand} grade with {property_abb}, and {ul_property}", "{brand} grade with {property_abb}, and {ul_property}"),
        (f"{brand} grade with {property_abb}, and {ul_sub_property}", "{brand} grade with {property_abb}, and {ul_sub_property}"),
        (f"{filler} {feature} {polymer}", "{filler} {feature} {polymer}"),
        (f"{polymer} with {property_abb} {property_abb2}", "{polymer} with {property_abb} {property_abb2}"),
        (f"{feature} {property_abb} {polymer} {processing}", "{feature} {property_abb} {polymer} {processing}"),
        (f"products with {property_abb}", "products with {property_abb}"),
        (f"{brand} {property_abb}; {property_abb2}", "{brand} {property_abb}; {property_abb2}"),
        (f"Find a material that is {property_abb}", "Find a material that is {property_abb}"),
        (f"{property_abb}", "{property_abb}"),
        (f"{polymer} {property_abb} {polymer2}", "{polymer} {property_abb} {polymer2}"),
        (f"looking for a {polymer} {filler} with {property_abb}", "looking for a {polymer} {filler} with {property_abb}"),
        (f"get {polymer} material with the condition, {property_abb}", "get {polymer} material with the condition, {property_abb}"),
        (f"{polymer} with {property_abb}", "{polymer} with {property_abb}"),
        (f"{feature}, {polymer}, with {property_abb}", "{feature}, {polymer}, with {property_abb}"),
        (f"{property_abb} {polymer}", "{property_abb} {polymer}"),
        (f"{property_abb} {feature}", "{property_abb} {feature}"),
        (f"{polymer} {property_abb}, {feature}", "{polymer} {property_abb}, {feature}"),
        (f"{brand} {property_abb}", "{brand} {property_abb}"),
        
        (f"{brand} grade with {property_rm}, and {ul_property}", "{brand} grade with {property_rm}, and {ul_property}"),
        (f"{brand} grade with {property_rm}, and {ul_sub_property}", "{brand} grade with {property_rm}, and {ul_sub_property}"),
        (f"{filler} {feature} {polymer}", "{filler} {feature} {polymer}"),
        (f"{polymer} with {property_rm} {property_rm2}", "{polymer} with {property_rm} {property_rm2}"),
        (f"{feature} {property_rm} {polymer} {processing}", "{feature} {property_rm} {polymer} {processing}"),
        (f"products with {property_rm}", "products with {property_rm}"),
        (f"{brand} {property_rm}; {property_rm2}", "{brand} {property_rm}; {property_rm2}"),
        (f"Find a material that is {property_rm}", "Find a material that is {property_rm}"),
        (f"{property_rm}", "{property_rm}"),
        (f"{polymer} {property_rm} {polymer2}", "{polymer} {property_rm} {polymer2}"),
        (f"looking for a {polymer} {filler} with {property_rm}", "looking for a {polymer} {filler} with {property_rm}"),
        (f"get {polymer} material with the condition, {property_rm}", "get {polymer} material with the condition, {property_rm}"),
        (f"{polymer} with {property_rm}", "{polymer} with {property_rm}"),
        (f"{feature}, {polymer}, with {property_rm}", "{feature}, {polymer}, with {property_rm}"),
        (f"{property_rm} {polymer}", "{property_rm} {polymer}"),
        (f"{property_rm} {feature}", "{property_rm} {feature}"),
        (f"{polymer} {property_rm}, {feature}", "{polymer} {property_rm}, {feature}"),
        (f"{brand} {property_rm}", "{brand} {property_rm}"),
        
        
        (f"{application}", "{application}"),
        (f"{polymer}", "{polymer}"),
        (f"{polymer} {feature}", "{polymer} {feature}"),
        # (f"{application} {polymer}", "{application} {polymer}"),
        (f"{feature}", "{feature}"),
        (f"good {feature}", "good {feature}"),
        (f"{brand} {feature}", "{brand} {feature}"),
        (f"{polymer} {processing}", "{polymer} {processing}"),
        # (f"{application} {brand}", "{application} {brand}"),
        (f"{brand} {polymer}", "{brand} {polymer}"),
        (f"{grade} {polymer}", "{grade} {polymer}"),
        # (f"{application} {feature}", "{application} {feature}"),
        # (f"{application} {polymer} {feature}", "{application} {polymer} {feature}"),
        (f"{brand} {processing}", "{brand} {processing}"),
        (f"{processing}", "{processing}"),
        # (f"{polymer} {competitor_grade}", "{polymer} {competitor_grade}"),
        # (f"{application} {processing}", "{application} {processing}"),
        (f"{grade} {brand}", "{grade} {brand}"),
        # (f"{application} {brand} {feature}", "{application} {brand} {feature}"),
        # (f"{brand} {competitor_grade}", "{brand} {competitor_grade}"),
        (f"{brand} {polymer} {feature}", "{brand} {polymer} {feature}"),
        # (f"{grade} {application}", "{grade} {application}"),
        # (f"{grade} {competitor_grade}", "{grade} {competitor_grade}"),
        (f"{polymer} {feature} {processing}", "{polymer} {feature} {processing}"),
        # (f"{polymer} {nsf_cert}", "{polymer} {nsf_cert}"),
        # (f"{application} {competitor_grade}", "{application} {competitor_grade}"),
        (f"{brand} {delivery_form}", "{brand} {delivery_form}"),
        # (f"{application} {polymer} {processing}", "{application} {polymer} {processing}"),
        # (f"{nsf_cert}", "{nsf_cert}"),
        (f"{grade} {feature}", "{grade} {feature}"),
        (f"{grade} with excellent {feature}", "{grade} with excellent {feature}"),
        (f"{feature} {processing}", "{feature} {processing}"),
        (f"{polymer} {delivery_form}", "{polymer} {delivery_form}"),
        # (f"{grade} {brand} {polymer}", "{grade} {brand} {polymer}"),
        (f"{brand} {polymer} {processing}", "{brand} {polymer} {processing}"),
        # (f"{application} {brand} {processing}", "{application} {brand} {processing}"),
        # (f"{brand} {nsf_cert}", {brand} {nsf_cert}"),
        (f"{grade} {processing}", "{grade} {processing}"),
        # (f"{feature} {competitor_grade}", "{feature} {competitor_grade}"),
        # (f"{grade} {polymer} {competitor_grade}", "{grade} {polymer} {competitor_grade}"),
        # (f"{application} {delivery_form}", "{application} {delivery_form}"),
        (f"{grade} {feature} {delivery_form}", "{grade} {feature} {delivery_form}"),
        # (f"{grade} {application} {feature}", "{grade} {application} {feature}"),
        (f"{delivery_form}", "{delivery_form}"),
        (f"{grade} {polymer} {feature}", "{grade} {polymer} {feature}"),
        (f"{polymer} {feature} {delivery_form}", "{polymer} {feature} {delivery_form}"),
        # (f"{application} {brand} {delivery_form}", "{application} {brand} {delivery_form}" ),
        (f"{grade} {polymer} {feature} {delivery_form}", "{grade} {polymer} {feature} {delivery_form}"),
        (f"{brand} {feature} {processing}", "{brand} {feature} {processing}"),
        # (f"{delivery_form} {competitor_grade}", "{delivery_form} {competitor_grade}"),
        
        (f"{polymer}, {feature}", "{polymer}, {feature}"),
        (f"{application}, {polymer}", "{application}, {polymer}"),
        (f"{brand}, {feature}", "{brand}, {feature}"),
        (f"{polymer}, {processing}", "{polymer}, {processing}"),
        (f"{application}, {brand}", "{application}, {brand}"),
        (f"{brand}, {polymer}", "{brand}, {polymer}"),
        (f"{grade}, {polymer}", "{grade}, {polymer}"),
        (f"{application}, {feature}", "{application}, {feature}"),
        (f"{application}, {polymer}, {feature}", "{application}, {polymer}, {feature}"),
        (f"{brand}, {processing}", "{brand}, {processing}"),
        # (f"{polymer}, {competitor_grade}", "{polymer}, {competitor_grade}"),
        (f"{application}, {processing}", "{application}, {processing}"),
        (f"{grade}, {brand}", "{grade}, {brand}"),
        (f"{application}, {brand}, {feature}", "{application}, {brand}, {feature}"),
        # (f"{brand}, {competitor_grade}", "{brand}, {competitor_grade}"),
        (f"{brand}, {polymer}, {feature}", "{brand}, {polymer}, {feature}"),
        (f"{grade}, {application}", "{grade}, {application}"),
        # (f"{grade}, {competitor_grade}", "{grade}, {competitor_grade}"),
        (f"{polymer}, {feature}, {processing}", "{polymer}, {feature}, {processing}"),
        # (f"{polymer}, {nsf_cert}", "{polymer}, {nsf_cert}"),
        # (f"{application}, {competitor_grade}", ),
        (f"{brand}, {delivery_form}", "{brand}, {delivery_form}"),
        (f"{application}, {polymer}, {processing}", "{application}, {polymer}, {processing}"),
        # (f"{nsf_cert}", "{nsf_cert}"),
        (f"{grade}, {feature}", "{grade}, {feature}"),
        (f"{feature}, {processing}", "{feature}, {processing}"),
        (f"{polymer}, {delivery_form}", "{polymer}, {delivery_form}"),
        (f"{grade}, {brand}, {polymer}", "{grade}, {brand}, {polymer}"),
        (f"{brand}, {polymer}, {processing}", "{brand}, {polymer}, {processing}"),
        (f"{application}, {brand}, {processing}", "{application}, {brand}, {processing}"),
        # (f"{brand}, {nsf_cert}", "{brand}, {nsf_cert}"),
        (f"{grade}, {processing}", "{grade}, {processing}"),
        # (f"{feature}, {competitor_grade}", "{feature}, {competitor_grade}"),
        # (f"{grade}, {polymer}, {competitor_grade}", "{grade}, {polymer}, {competitor_grade}"),
        (f"{application}, {delivery_form}", "{application}, {delivery_form}"),
        (f"{grade}, {feature}, {delivery_form}", "{grade}, {feature}, {delivery_form}"),
        (f"{grade}, {application}, {feature}", "{grade}, {application}, {feature}"),
        (f"{delivery_form}", "{delivery_form}"),
        (f"{grade}, {polymer}, {feature}", "{grade}, {polymer}, {feature}"),
        (f"{polymer}, {feature}, {delivery_form}", "{polymer}, {feature}, {delivery_form}"),
        (f"{application}, {brand}, {delivery_form}", "{application}, {brand}, {delivery_form}"),
        (f"{grade}, {polymer}, {feature}, {delivery_form}", "{grade}, {polymer}, {feature}, {delivery_form}"),
        (f"{brand}, {feature}, {processing}", "{brand}, {feature}, {processing}"),
        # (f"{delivery_form}, {competitor_grade}", "{delivery_form}, {competitor_grade}"),
        
        # twice same entity
        (f"{polymer}, {polymer2}", "{polymer}, {polymer2}"),
        (f"{polymer}, {feature}, {feature2}", "{polymer}, {feature}, {feature2}"),
        (f"{polymer}, {polymer2}, {feature}", "{polymer}, {polymer2}, {feature}"),
        (f"{application}, {polymer}, {polymer2}", "{application}, {polymer}, {polymer2}"),
        (f"{feature}, {feature2}", "{feature}, {feature2}"),
        (f"{brand}, {feature}, {feature2}", "{brand}, {feature}, {feature2}"),
        (f"{polymer}, {polymer2}, {processing}", "{polymer}, {polymer2}, {processing}"),
        (f"{polymer}, {processing}, {processing2}", "{polymer}, {processing}, {processing2}"),
        
        # (f"{brand}, {polymer}, {polymer2}", "{brand}, {polymer}, {polymer2}"),
        # (f"{grade}, {polymer}, {polymer2}", "{grade}, {polymer}, {polymer2}"),
        (f"{application}, {feature}, {feature2}", "{application}, {feature}, {feature2}"),
        # (f"{application}, {polymer}, {polymer2}, {feature}", "{application}, {polymer}, {polymer2}, {feature}"),
        (f"{application}, {polymer}, {feature}, {feature2}", "{application}, {polymer}, {feature}, {feature2}"),
        (f"{brand}, {processing}, {processing2}", "{brand}, {processing}, {processing2}"),
        
        (f"{brand}, {delivery_form}, {delivery_form2}", "{brand}, {delivery_form}, {delivery_form2}"),
        (f"{polymer}, {delivery_form} , {delivery_form2}", "{polymer}, {delivery_form} , {delivery_form2}"),
        # (f"{polymer}, {polymer2} , {delivery_form2}", "{polymer}, {polymer2} , {delivery_form2}"),
        (f"{application}, {delivery_form}, {delivery_form2}", "{application}, {delivery_form}, {delivery_form2}"),
    
        
        (f"{polymer} {polymer2}", "{polymer} {polymer2}"),
        (f"{polymer} {feature} {feature2}", "{polymer} {feature} {feature2}"),
        (f"{polymer} {polymer2} {feature}", "{polymer} {polymer2} {feature}"),
        (f"{application} {polymer} {polymer2}", "{application} {polymer} {polymer2}"),
        (f"{feature} {feature2}", "{feature} {feature2}"),
        (f"{brand} {feature} {feature2}", "{brand} {feature} {feature2}"),
        (f"{polymer} {polymer2} {processing}", "{polymer} {polymer2} {processing}"),
        (f"{polymer} {processing} {processing2}", "{polymer} {processing} {processing2}"),
        
        # (f"{brand} {polymer} {polymer2}", "{brand} {polymer} {polymer2}"),
        # (f"{grade} {polymer} {polymer2}", "{grade} {polymer} {polymer2}"),
        (f"{application} {feature} {feature2}", "{application} {feature} {feature2}"),
        # (f"{application} {polymer} {polymer2} {feature}", "{application} {polymer} {polymer2} {feature}"),
        (f"{application} {polymer} {feature} {feature2}", "{application} {polymer} {feature} {feature2}"),
        (f"{brand} {processing} {processing2}", "{brand} {processing} {processing2}"),
        
        (f"{brand} {delivery_form} {delivery_form2}", "{brand} {delivery_form} {delivery_form2}"),
        (f"{polymer} {delivery_form} , {delivery_form2}", "{polymer} {delivery_form} , {delivery_form2}"),
        # (f"{polymer} {polymer2} , {delivery_form2}", "{polymer} {polymer2} , {delivery_form2}"),
        (f"{application} {delivery_form} {delivery_form2}", "{application} {delivery_form} {delivery_form2}"),
        
        (f"{polymer} and {polymer2}", "{polymer} and {polymer2}"),
        (f"{polymer} and {feature} and {feature2}", "{polymer} and {feature} and {feature2}"),
        (f"{polymer} and {polymer2} and {feature}", "{polymer} and {polymer2} and {feature}"),
        (f"{application} and {polymer} and {polymer2}", "{application} and {polymer} and {polymer2}"),
        (f"{feature} and {feature2}", "{feature} and {feature2}"),
        (f"{brand} and {feature} and {feature2}", "{brand} and {feature} and {feature2}"),
        (f"{polymer} and {polymer2} and {processing}", "{polymer} and {polymer2} and {processing}"),
        (f"{polymer} and {processing} and {processing2}", "{polymer} and {processing} and {processing2}"),
        
        # (f"{brand} and {polymer} and {polymer2}", "{brand} and {polymer} and {polymer2}"),
        # (f"{grade} and {polymer} and {polymer2}", "{grade} and {polymer} and {polymer2}"),
        (f"{application} and {feature} and {feature2}", "{application} and {feature} and {feature2}"),
        # (f"{application} and {polymer} and {polymer2} and {feature}", "{application} and {polymer} and {polymer2} and {feature}"),
        (f"{application} and {polymer} and {feature} and {feature2}", "{application} and {polymer} and {feature} and {feature2}"),
        (f"{brand} and {processing} and {processing2}", "{brand} and {processing} and {processing2}"),
        
        (f"{brand} and {delivery_form} and {delivery_form2}", "{brand} and {delivery_form} and {delivery_form2}"),
        (f"{polymer} and {delivery_form} , {delivery_form2}", "{polymer} and {delivery_form} , {delivery_form2}"),
        # (f"{polymer} and {polymer2} , {delivery_form2}", "{polymer} and {polymer2} , {delivery_form2}"),
        (f"{application} and {delivery_form} and {delivery_form2}", "{application} and {delivery_form} and {delivery_form2}"),
        
        # nsf water railway
        (f"{nsf}", "{nsf}"),
        (f"{nsf} certification", "{nsf} certification"),
        (f"{nsf} certified", "{nsf} certified"),
        (f"{nsf} grades", "{nsf} grades"),
        (f"grade with {nsf}", "grade with {nsf}"),

        (f"{water_name}", "{water_name}"),
        (f"{water_name} certification", "{water_name} certification"),
        (f"{water_name} certified", "{water_name} certified"),
        (f"{water_name} grades", "{water_name} grades"),
        (f"grade with {water_name}", "grade with {water_name}"),

        (f"{nsf}, {feature}", "{nsf}, {feature}"),
        (f"{delivery_form}, {nsf}", "{delivery_form}, {nsf}"),
        (f"{nsf}, {processing}", "{nsf}, {processing}"),
        (f"{application}, {nsf}", "{application}, {nsf}"),
        (f"{nsf}, {feature}", "{nsf}, {feature}"),
        (f"{brand}, {nsf}", "{brand}, {nsf}"),
        (f"{nsf}, {processing}", "{nsf}, {processing}"),
        (f"{nsf}, {brand}", "{nsf}, {brand}"),
        
        (f"{water_name}, {feature}", "{water_name}, {feature}"),
        (f"{delivery_form}, {water_name}", "{delivery_form}, {water_name}"),
        (f"{water_name}, {processing}", "{water_name}, {processing}"),
        (f"{application}, {water_name}", "{application}, {water_name}"),
        (f"{water_name}, {feature}", "{water_name}, {feature}"),
        (f"{brand}, {water_name}", "{brand}, {water_name}"),
        (f"{water_name}, {processing}", "{water_name}, {processing}"),
        (f"{water_name}, {brand}", "{water_name}, {brand}"),

        (f"{railway_name} certification", "{railway_name} certification"),
        (f"{railway_name} certified", "{railway_name} certified"),
        (f"{railway_name}, {feature}", "{railway_name}, {feature}"),
        (f"{delivery_form}, {railway_name}", "{delivery_form}, {railway_name}"),
        (f"{railway_name}, {processing}", "{railway_name}, {processing}"),
        (f"{application}, {railway_name}", "{application}, {railway_name}"),
        (f"{railway_name}, {feature}", "{railway_name}, {feature}"),
        (f"{brand}, {railway_name}", "{brand}, {railway_name}"),
        (f"{railway_name}, {processing}", "{railway_name}, {processing}"),
        (f"{railway_name}, {brand}", "{railway_name}, {brand}"),
        
        (f"{nsf} {feature}", "{nsf} {feature}"),
        (f"{delivery_form} {nsf}", "{delivery_form} {nsf}"),
        (f"{nsf} {processing}", "{nsf} {processing}"),
        (f"{application} {nsf}", "{application} {nsf}"),
        (f"{nsf} {feature}", "{nsf} {feature}"),
        (f"{brand} {nsf}", "{brand} {nsf}"),
        (f"{nsf} {processing}", "{nsf} {processing}"),
        (f"{nsf} {brand}", "{nsf} {brand}"),
        
        (f"{water_name} {feature}", "{water_name} {feature}"),
        (f"{delivery_form} {water_name}", "{delivery_form} {water_name}"),
        (f"{water_name} {processing}", "{water_name} {processing}"),
        (f"{application} {water_name}", "{application} {water_name}"),
        (f"{water_name} {feature}", "{water_name} {feature}"),
        (f"{brand} {water_name}", "{brand} {water_name}"),
        (f"{water_name} {processing}", "{water_name} {processing}"),
        (f"{water_name} {brand}", "{water_name} {brand}"),
        
        (f"{railway_name} {feature}", "{railway_name} {feature}"),
        (f"{delivery_form} {railway_name}", "{delivery_form} {railway_name}"),
        (f"{railway_name} {processing}", "{railway_name} {processing}"),
        (f"{application} {railway_name}", "{application} {railway_name}"),
        (f"{railway_name} {feature}", "{railway_name} {feature}"),
        (f"{brand} {railway_name}", "{brand} {railway_name}"),
        (f"{railway_name} {processing}", "{railway_name} {processing}"),
        (f"{railway_name} {brand}", "{railway_name} {brand}"),
        
        (f"{nsf} and {feature}", "{nsf} and {feature}"),
        (f"{delivery_form} and {nsf}", "{delivery_form} and {nsf}"),
        (f"{nsf} and {processing}", "{nsf} and {processing}"),
        (f"{application} and {nsf}", "{application} and {nsf}"),
        (f"{nsf} and {feature}", "{nsf} and {feature}"),
        (f"{brand} and {nsf}", "{brand} and {nsf}"),
        (f"{nsf} and {processing}", "{nsf} and {processing}"),
        (f"{nsf} and {brand}", "{nsf} and {brand}"),
        
        (f"{water_name} and {feature}", "{water_name} and {feature}"),
        (f"{delivery_form} and {water_name}", "{delivery_form} and {water_name}"),
        (f"{water_name} and {processing}", "{water_name} and {processing}"),
        (f"{application} and {water_name}", "{application} and {water_name}"),
        (f"{water_name} and {feature}", "{water_name} and {feature}"),
        (f"{brand} and {water_name}", "{brand} and {water_name}"),
        (f"{water_name} and {processing}", "{water_name} and {processing}"),
        (f"{water_name} and {brand}", "{water_name} and {brand}"),
        
        (f"{railway_name} and {feature}", "{railway_name} and {feature}"),
        (f"{delivery_form} and {railway_name}", "{delivery_form} and {railway_name}"),
        (f"{railway_name} and {processing}", "{railway_name} and {processing}"),
        (f"{application} and {railway_name}", "{application} and {railway_name}"),
        (f"{railway_name} and {feature}", "{railway_name} and {feature}"),
        (f"{brand} and {railway_name}", "{brand} and {railway_name}"),
        (f"{railway_name} and {processing}", "{railway_name} and {processing}"),
        (f"{railway_name} and {brand}", "{railway_name} and {brand}"),

        # auto and other certiications
        (f"{railway_name} {auto_cert_name}", "{railway_name} {auto_cert_name}"),
        (f"{railway_name} {auto_cert_name}", "{railway_name} {auto_cert_name}"),
        (f"{railway_name}, {auto_cert_name} certifications", "{railway_name}, {auto_cert_name} certifications"),
        (f"{railway_name} and {auto_cert_name}", "{railway_name} and {auto_cert_name}"),
        (f"{railway_name} certification {auto_cert_name} approval", "{railway_name} certification {auto_cert_name} approval"),
        (f"{railway_name} {auto_cert_name} {oem_name}", "{railway_name} {auto_cert_name} {oem_name}"),
        (f"{railway_name} {oem_name} {auto_cert_name}", "{railway_name} {oem_name} {auto_cert_name}"),
        (f"{railway_name} {oem_name}", "{railway_name} {oem_name}"),
        (f"{oem_name} {railway_name}", "{oem_name} {railway_name}"),
        (f"{oem_name} {auto_cert_name} {railway_name}", "{oem_name} {auto_cert_name} {railway_name}"),
        (f"{auto_cert_name} {oem_name} {railway_name}", "{auto_cert_name} {oem_name} {railway_name}"),
        (f"{auto_cert_name} {railway_name}", "{auto_cert_name} {railway_name}"),
        (f"{auto_cert_name} {railway_name}", "{auto_cert_name} {railway_name}"),

        (f"{water_name} {auto_cert_name}", "{water_name} {auto_cert_name}"),
        (f"{water_name} {auto_cert_name}", "{water_name} {auto_cert_name}"),
        (f"{water_name}, {auto_cert_name} certifications", "{water_name}, {auto_cert_name} certifications"),
        (f"{water_name} and {auto_cert_name}", "{water_name} and {auto_cert_name}"),
        (f"{water_name} certified and {auto_cert_name} approved", "{water_name} certified and {auto_cert_name} approved"),
        (f"{water_name} {auto_cert_name} {oem_name}", "{water_name} {auto_cert_name} {oem_name}"),
        (f"{water_name} {oem_name} {auto_cert_name}", "{water_name} {oem_name} {auto_cert_name}"),
        (f"{water_name} {oem_name}", "{water_name} {oem_name}"),
        (f"{oem_name} {water_name}", "{oem_name} {water_name}"),
        (f"{oem_name} {auto_cert_name} {water_name}", "{oem_name} {auto_cert_name} {water_name}"),
        (f"{auto_cert_name} {oem_name} {water_name}", "{auto_cert_name} {oem_name} {water_name}"),
        (f"{auto_cert_name} {water_name}", "{auto_cert_name} {water_name}"),
        (f"{auto_cert_name} {water_name}", "{auto_cert_name} {water_name}"),

        (f"{nsf} {auto_cert_name}", "{nsf} {auto_cert_name}"),
        (f"{nsf} {auto_cert_name}", "{nsf} {auto_cert_name}"),
        (f"{nsf}, {auto_cert_name} certifications", "{nsf}, {auto_cert_name} certifications"),
        (f"{nsf} and {auto_cert_name}", "{nsf} and {auto_cert_name}"),
        (f"{nsf} certification and {auto_cert_name} approved", "{nsf} certification and {auto_cert_name} approved"),
        (f"{nsf} {auto_cert_name} {oem_name}", "{nsf} {auto_cert_name} {oem_name}"),
        (f"{nsf} {oem_name} {auto_cert_name}", "{nsf} {oem_name} {auto_cert_name}"),
        (f"{nsf} {oem_name}", "{nsf} {oem_name}"),
        (f"{oem_name} {nsf}", "{oem_name} {nsf}"),
        (f"{oem_name} {auto_cert_name} {nsf}", "{oem_name} {auto_cert_name} {nsf}"),
        (f"{auto_cert_name} {oem_name} {nsf}", "{auto_cert_name} {oem_name} {nsf}"),
        (f"{auto_cert_name} {nsf}", "{auto_cert_name} {nsf}"),
        (f"{auto_cert_name} {nsf}", "{auto_cert_name} {nsf}"),

        (f"{nsf}, {water_name}, {railway_name}, {auto_cert_name} certifications", "{nsf}, {water_name}, {railway_name}, {auto_cert_name} certifications"),
        (f"{water_name}, {railway_name}, {nsf}, {auto_cert_name} certifications", "{water_name}, {railway_name}, {nsf}, {auto_cert_name} certifications"),
        (f"{railway_name}, {nsf}, {water_name}, {auto_cert_name} certifications", "{railway_name}, {nsf}, {water_name}, {auto_cert_name} certifications"),
        (f"{auto_cert_name}, {railway_name}, {nsf}, {water_name} certifications", "{auto_cert_name}, {railway_name}, {nsf}, {water_name} certifications"),
        (f"{nsf}, {water_name}, {railway_name}, {oem_name} certifications", "{nsf}, {water_name}, {railway_name}, {oem_name} certifications"),
        (f"{water_name}, {railway_name}, {nsf}, {oem_name} certifications", "{water_name}, {railway_name}, {nsf}, {oem_name} certifications"),
        (f"{railway_name}, {nsf}, {water_name}, {oem_name} certifications", "{railway_name}, {nsf}, {water_name}, {oem_name} certifications"),
        (f"{oem_name}, {railway_name}, {nsf}, {water_name} certifications", "{oem_name}, {railway_name}, {nsf}, {water_name} certifications"),
        
        # no space
        (f"{processing.replace(' ', '')}", "{processing}"),
        (f"{feature.replace(' ', '')}", "{feature}"),

        (f"{polymer} {filler}", "{polymer} {filler}"),
        # (f"{ul_property} in UL listing", "{ul_property} in UL listing"),
        (f"{ul_property}", "{ul_property}"),
        (f"Need a grade with a {ul_property}", "Need a grade with a {ul_property}"),
        (f"{ul_property} specification for {grade}", "{ul_property} specification for {grade}"),
        (f"{brand} grade with a {ul_property}", "{brand} grade with a {ul_property}"),
        (f"{brand} grade with {property}, and {ul_property}", "{brand} grade with {property}, and {ul_property}"),
        (f"{polymer} {ul_property}", "{polymer} {ul_property}"),
        (f"{polymer} with {ul_property}", "{polymer} with {ul_property}"),
        (f"{ul_property} and {ul_property2} grade", "{ul_property} and {ul_property2} grade"),
        (f"grade for {application} with {ul_property}", "grade for {application} with {ul_property}"),
        (f"can you recommend a {ul_property} {polymer} {brand} grade", "can you recommend a {ul_property} {polymer} {brand} grade"),
        (f"{polymer} {processing} grade that is {ul_property}", "{polymer} {processing} grade that is {ul_property}"),
        (f"{brand} {ul_property}", "{brand} {ul_property}"),
        (f"{ul_property}", "{ul_property}"),
        
        # (f"{ul_sub_property} in UL listing", "{ul_sub_property} in UL listing"),
        (f"{ul_sub_property}", "{ul_sub_property}"),
        (f"Need a grade with a {ul_sub_property}", "Need a grade with a {ul_sub_property}"),
        (f"{ul_sub_property} specification for {grade}", "{ul_sub_property} specification for {grade}"),
        (f"{brand} grade with a {ul_sub_property}", "{brand} grade with a {ul_sub_property}"),
        (f"{brand} grade with {property}, and {ul_sub_property}", "{brand} grade with {property}, and {ul_sub_property}"),
        (f"{polymer} {ul_sub_property}", "{polymer} {ul_sub_property}"),
        (f"{polymer} with {ul_sub_property}", "{polymer} with {ul_sub_property}"),
        # (f"{ul_sub_property} and {ul_sub_property2} grade", "{ul_sub_property} and {ul_sub_property2} grade"),
        (f"grade for {application} with {ul_sub_property}", "grade for {application} with {ul_sub_property}"),
        (f"can you recommend a {ul_sub_property} {polymer} {brand} grade", "can you recommend a {ul_sub_property} {polymer} {brand} grade"),
        (f"{polymer} {processing} grade that is {ul_sub_property}", "{polymer} {processing} grade that is {ul_sub_property}"),
        (f"{brand} {ul_sub_property}", "{brand} {ul_sub_property}"),
        (f"{ul_sub_property}", "{ul_sub_property}"),
        (f"flexible {polymer} grades", "flexible {polymer} grades"),
        (f"{filler} {feature} {polymer}", "{filler} {feature} {polymer}"),
        (f"{polymer} with {property} {property2}", "{polymer} with {property} {property2}"),
        (f"{feature} {property} {polymer} {processing}", "{feature} {property} {polymer} {processing}"),
        (f"{polymer} for {processing}", "{polymer} for {processing}"),
        (f"{feature} material", "{feature} material"),
        (f"products with {property}", "products with {property}"),
        (f"{feature} {polymer} {application} {feature2}", "{feature} {polymer} {application} {feature2}"),
        # (f"{MODIFIER_RANGE} {property} grade", "{MODIFIER_RANGE} {property} grade"),
        (f"{filler} {polymer}", "{filler} {polymer}"),
        (f"{brand} {property}; {property2}", "{brand} {property}; {property2}"),
        (f"Find a material that is {property}", "Find a material that is {property}"),
        (f"{feature} {filler}", "{feature} {filler}"),
        (f"{polymer} {filler}", "{polymer} {filler}"),
        (f"{property}", "{property}"),
        (f"{processing} {grade} {brand} that is {feature}", "{processing} {grade} {brand} that is {feature}"),
        # (f"grade meet {AUTO_CERT}", "grade meet {AUTO_CERT}"),
        (f"{polymer} {property} {polymer2}", "{polymer} {property} {polymer2}"),
        (f"looking for a {polymer} {filler} with {property}", "looking for a {polymer} {filler} with {property}"),
        (f"{application} {brand}", "{application} {brand}"),
        (f"{application} grades", "{application} grades"),
        (f"{polymer} {filler} {feature}", "{polymer} {filler} {feature}"),
        # (f"{polymer} with {MODIFIER_RANGE} {property}", "{polymer} with {MODIFIER_RANGE} {property}"),
        (f"get {polymer} material with the condition, {property}", "get {polymer} material with the condition, {property}"),
        (f"a {polymer} with {filler}", "a {polymer} with {filler}"),
        (f"{polymer} with {property}", "{polymer} with {property}"),
        (f"{feature}, {polymer}, with {property}", "{feature}, {polymer}, with {property}"),
        # (f"Yellow Card {brand} {grade}", "Yellow Card {brand} {grade}"),
        # (f"{polymer} silver color", "{polymer} silver color"),
        (f"{property} {polymer}", "{property} {polymer}"),
        (f"{polymer} for {application} with {property}", "{polymer} for {application} with {property}"),
        (f"{polymer} {filler} {feature}", "{polymer} {filler} {feature}"),
        (f"{polymer} {filler} with good {feature}", "{polymer} {filler} with good {feature}"),
        (f"{property} {feature}", "{property} {feature}"),
        (f"{polymer} with {nsf} approval", "{polymer} with {nsf} approval"),
        (f"flexible {polymer} for {processing}", "flexible {polymer} for {processing}"),
        (f"{polymer} with good {feature}", "{polymer} with good {feature}"),
        # (f"{feature} and {feature2} {polymer} for {application} application with {AUTO_CERT} approval", "{feature} and {feature2} {polymer} for {application} application with {AUTO_CERT} approval"),
        (f"{filler} {feature} {polymer}", "{filler} {feature} {polymer}"),
        (f"{polymer} {property}, {feature}", "{polymer} {property}, {feature}"),
        (f"{polymer} {filler} with {feature}", "{polymer} {filler} with {feature}"),
        (f"{feature} grade for {application} solution", "{feature} grade for {application} solution"),
        (f"can you recommend a {feature} {filler} {polymer} grade that is approved for {application}", "can you recommend a {feature} {filler} {polymer} grade that is approved for {application}"),
        # (f"SEBS {property}", "SEBS {property}"),
        (f"material with {filler}", "material with {filler}"),
        (f"{polymer} for {application} {feature}", "{polymer} for {application} {feature}"),
        # (f"is {polymer} anti-oxidate", "is {polymer} anti-oxidate"),
        # (f"{polymer} can reduce the vibration and noise", "{polymer} can reduce the vibration and noise"),
        (f"{brand} {property}", "{brand} {property}"),
        (f"{filler} in {polymer}", "{filler} in {polymer}"),
        (f"{property} grade", "{property} grade"),
        
        (f"{brand} grade with {property_rm}, and {ul_property}", "{brand} grade with {property_rm}, and {ul_property}"),
        (f"{brand} grade with {property_rm}, and {ul_sub_property}", "{brand} grade with {property_rm}, and {ul_sub_property}"),
        (f"{polymer} with {property_rm} {property_rm2}", "{polymer} with {property_rm} {property_rm2}"),
        (f"{feature} {property_rm} {polymer} {processing}", "{feature} {property_rm} {polymer} {processing}"),
        (f"products with {property_rm}", "products with {property_rm}"),
        (f"{brand} {property_rm}; {property_rm2}", "{brand} {property_rm}; {property_rm2}"),
        (f"Find a material that is {property_rm}", "Find a material that is {property_rm}"),
        (f"{property_rm}", "{property_rm}"),
        (f"{polymer} {property_rm} {polymer2}", "{polymer} {property_rm} {polymer2}"),
        (f"looking for a {polymer} {filler} with {property_rm}", "looking for a {polymer} {filler} with {property_rm}"),
        (f"get {polymer} material with the condition, {property_rm}", "get {polymer} material with the condition, {property_rm}"),
        (f"{polymer} with {property_rm}", "{polymer} with {property_rm}"),
        (f"{feature}, {polymer}, with {property_rm}", "{feature}, {polymer}, with {property_rm}"),
        (f"{property_rm} {polymer}", "{property_rm} {polymer}"),
        (f"{polymer} for {application} with {property_rm}", "{polymer} for {application} with {property_rm}"),
        (f"{property_rm} {feature}", "{property_rm} {feature}"),
        (f"{polymer} {property_rm}, {feature}", "{polymer} {property_rm}, {feature}"),
        (f"material with {filler}", "material with {filler}"),
        (f"{brand} {property_rm}", "{brand} {property_rm}"),
        (f"{property_rm} grade", "{property_rm} grade"),
        
        (f"{brand} grade with {property_abb}, and {ul_property}", "{brand} grade with {property_abb}, and {ul_property}"),
        (f"{brand} grade with {property_abb}, and {ul_sub_property}", "{brand} grade with {property_abb}, and {ul_sub_property}"),
        (f"{polymer} with {property_abb} {property_abb2}", "{polymer} with {property_abb} {property_abb2}"),
        (f"{feature} {property_abb} {polymer} {processing}", "{feature} {property_abb} {polymer} {processing}"),
        (f"products with {property_abb}", "products with {property_abb}"),
        (f"{brand} {property_abb}; {property_abb2}", "{brand} {property_abb}; {property_abb2}"),
        (f"Find a material that is {property_abb}", "Find a material that is {property_abb}"),
        (f"{property_abb}", "{property_abb}"),
        (f"{polymer} {property_abb} {polymer2}", "{polymer} {property_abb} {polymer2}"),
        (f"looking for a {polymer} {filler} with {property_abb}", "looking for a {polymer} {filler} with {property_abb}"),
        (f"get {polymer} material with the condition, {property_abb}", "get {polymer} material with the condition, {property_abb}"),
        (f"{polymer} with {property_abb}", "{polymer} with {property_abb}"),
        (f"{feature}, {polymer}, with {property_abb}", "{feature}, {polymer}, with {property_abb}"),
        (f"{property_abb} {polymer}", "{property_abb} {polymer}"),
        (f"{polymer} for {application} with {property_abb}", "{polymer} for {application} with {property_abb}"),
        (f"{property_abb} {feature}", "{property_abb} {feature}"),
        (f"{polymer} {property_abb}, {feature}", "{polymer} {property_abb}, {feature}"),
        (f"material with {filler}", "material with {filler}"),
        (f"{brand} {property_abb}", "{brand} {property_abb}"),
        (f"{property_abb} grade", "{property_abb} grade"),

        # adding filler templates
        (f"{feature} {polymer} {filler}", "{feature} {polymer} {filler}"),
        (f"{polymer} {filler}", "{polymer} {filler}"),
        (f"material with {polymer} {filler}", "material with {polymer} {filler}"),
        (f"{oem_name} {filler}", "{oem_name} {filler}"),
        (f"{auto_cert_name} {filler}", "{auto_cert_name} {filler}"),
        (f"{auto_cert_name} {filler}", "{auto_cert_name} {filler}"),
        (f"{filler} {oem_name}", "{filler} {oem_name}"),
        (f"{filler} {auto_cert_name}", "{filler} {auto_cert_name}"),
        (f"{filler} {auto_cert_name}", "{filler} {auto_cert_name}"),
        (f"{auto_cert_name} {oem_name} {filler}", "{auto_cert_name} {oem_name} {filler}"),
        (f"{filler} {auto_cert_name} {oem_name}", "{filler} {auto_cert_name} {oem_name}"),
        (f"{ul_sub_property} {filler}", "{ul_sub_property} {filler}"),
        (f"{filler} {ul_sub_property}", "{filler} {ul_sub_property}"),

        # region templates
        (f"{filler} {brand} available in {continent}", "{filler} {brand} available in {continent}"),
        (f"{polymer} for {continent} {application}", "{polymer} for {continent} {application}"),
        (f"{polymer} available in {country}", "{polymer} available in {country}"),
        (f"what {polymer} grades are available in {country}?", "what {polymer} grades are available in {country}?"),
        (f"{application} for {country}", "{application} for {country}"),
        (f"{continent} sourced {polymer}", "{continent} sourced {polymer}"),
        (f"{continent} {feature} grades", "{continent} {feature} grades"),
        (f"i want a {continent} {polymer} grade with {feature}", "i want a {continent} {polymer} grade with {feature}"),
        (f"i want an offset to {competitor_grade} for {country}", "i want an offset to {competitor_grade} for {country}"),
        (f"{brand} offset to {competitor_grade} for {city}", "{brand} offset to {competitor_grade} for {city}"),
        (f"{feature}, {feature2} grade for {city}", "{feature}, {feature2} grade for {city}"),
        (f"{polymer} grade available for {country} to use in {application}", "{polymer} grade available for {country} to use in {application}"),
        (f"{grade} grades available to {country} and {feature}", "{grade} grades available to {country} and {feature}"),
        (f"grades which are sold in {state} and have {oem_name} approvals", "grades which are sold in {state} and have {oem_name} approvals"),
        (f"{competitor_grade} offset, black, {country}, {feature}", "{competitor_grade} offset, black, {country}, {feature}"),
        (f"{feature} {brand} importable to {country}", "{feature}{brand} importable to {country}"),
        (f"{property} {polymer} to buy in {country}", "{property} {polymer} to buy in {country}"),
        (f"{country} approved food grade {brand}", "{country} approved food grade {brand}"),
        (f"{feature} {polymer} to ship to {country}", "{feature} {polymer} to ship to {country}"),
        (f"{country} sourceable {polymer} for {application}", "{country} sourceable {polymer} for {application}"),
        (f"{polymer} sourced from {country} for {application}", "{polymer} sourced from {country} for {application}"),
        (f"{water_name} approved {polymer} purchasable in {country}", "{water_name} approved {polymer} purchasable in {country}"),
        (f"{feature} {brand} obtainable in {country}", "{feature} {brand} obtainable in {country}"),
        (f"{competitor_grade} {continent}", "{competitor_grade} {continent}"),

        (f"what {polymer} grades are available in {state}?", "what {polymer} grades are available in {state}?"),
        (f"what {polymer} grades are available in {city}?", "what {polymer} grades are available in {city}?"),
        (f"{polymer} grade available for {state} to use in {application}", "{polymer} grade available for {state} to use in {application}"),
        (f"{polymer} grade available for {city} to use in {application}", "{polymer} grade available for {city} to use in {application}"),
        (f"{feature} {brand} importable to {state}", "{feature}{brand} importable to {state}"),
        (f"{feature} {brand} importable to {city}", "{feature}{brand} importable to {city}"),		
        (f"{property} {polymer} to buy in {state}", "{property} {polymer} to buy in {state}"),
        (f"{property} {polymer} to buy in {city}", "{property} {polymer} to buy in {city}"),
		(f"{polymer}, {feature}, {state}", "{polymer}, {feature}, {state}"),
		(f"{polymer} {feature} {state}", "{polymer}, {feature}, {state}"),
		(f"{polymer}, {feature}, {city}", "{polymer}, {feature}, {city}"),
		(f"{polymer} {feature} {city}", "{polymer}, {feature}, {city}"),
		(f"{country} sourced {brand}", "{country} sourced {brand}"),
		(f"{continent} sourced {brand}", "{continent} sourced {brand}"),

		(f"{continent}", "{continent}"),
		(f"{country}", "{country}"),
		(f"{state}", "{state}"),
		(f"{city}", "{city}"),
		(f"{continent}", "{continent}"),
		(f"{country}", "{country}"),
		(f"{state}", "{state}"),
		(f"{city}", "{city}"),

        (f"{application} for {oem_name}", "{application} for {oem_name}"),
        (f"{application} for {oem_name}", "{application} for {oem_name}"),
        (f"{application} for {oem_name}", "{application} for {oem_name}"),
        (f"{application} for {oem_name}", "{application} for {oem_name}"),
        (f"{application} for {oem_name}", "{application} for {oem_name}"),
        (f"{application}, {oem_name}", "{application}, {oem_name}"),
        (f"{oem_name}, {application}", "{oem_name}, {application}"),
        (f"{oem_name} for {application}", "{oem_name} for {application}"),
        (f"{oem_name} approved for {application}", "{oem_name} approved for {application}"),
        (f"{auto_cert_name} certification for {application}", "{auto_cert_name} certification for {application}"),
        (f"{oem_name}-{auto_cert_name} approved for {application}", "{oem_name}-{auto_cert_name} approved for {application}"),
        (f"{application} with {oem_name}-{auto_cert_name} approval", "{application} with {oem_name}-{auto_cert_name} approval}"),

        (f"{ignore_term}", "{ignore_term}"),
        (f"{ul_property} {ignore_term}", "{ul_property} {ignore_term}"),
        (f"{ul_sub_property} {ignore_term}", "{ul_sub_property} {ignore_term}"),
        (f"{ignore_term} {property}", "{ignore_term} {property}"),
        (f"{filler} {ignore_term}", "{filler} {ignore_term}"),

        (f"{oem_name} {ignore_term}", "{oem_name} {ignore_term}"),
        (f"{auto_cert_name} {ignore_term}", "{auto_cert_name} {ignore_term}"),
        (f"{auto_cert_name} {ignore_term}", "{auto_cert_name} {ignore_term}"),
        (f"{feature} {ignore_term}", "{feature} {ignore_term}"),
        (f"{brand} {ignore_term}", "{brand} {ignore_term}"),
        (f"{polymer} {ignore_term}", "{polymer} {ignore_term}"),

        (f"{ignore_term} {oem_name}", "{ignore_term} {oem_name}"),
        (f"{ignore_term} {auto_cert_name}", "{ignore_term} {auto_cert_name}"),
        (f"{ignore_term} {auto_cert_name}", "{ignore_term} {auto_cert_name}"),
        (f"{ignore_term} {feature}", "{ignore_term} {feature}"),
        (f"{ignore_term} {brand}", "{ignore_term} {brand}"),
        (f"{ignore_term} {polymer}", "{ignore_term} {polymer}"),

        (f"{oem_name} and {ignore_term}", "{oem_name} and {ignore_term}"),
        (f"{auto_cert_name} and {ignore_term}", "{auto_cert_name} and {ignore_term}"),
        (f"{auto_cert_name} and {ignore_term}", "{auto_cert_name} and {ignore_term}"),
        (f"{feature} and {ignore_term}", "{feature} and {ignore_term}"),
        (f"{brand} and {ignore_term}", "{brand} and {ignore_term}"),
        (f"{polymer} and {ignore_term}", "{polymer} and {ignore_term}"),

        (f"{ignore_term} and {oem_name}", "{ignore_term} and {oem_name}"),
        (f"{ignore_term} and {auto_cert_name}", "{ignore_term} and {auto_cert_name}"),
        (f"{ignore_term} and {auto_cert_name}", "{ignore_term} and {auto_cert_name}"),
        (f"{ignore_term} and {feature}", "{ignore_term} and {feature}"),
        (f"{ignore_term} and {brand}", "{ignore_term} and {brand}"),
        (f"{ignore_term} and {polymer}", "{ignore_term} and {polymer}"),


        (f"{oem_name}, {ignore_term} and {ignore_term2}", "{oem_name}, {ignore_term} and {ignore_term2}"),
        (f"{auto_cert_name}, {ignore_term} and {ignore_term2}", "{auto_cert_name}, {ignore_term} and {ignore_term2}"),
        (f"{auto_cert_name}, {ignore_term} and {ignore_term2}", "{auto_cert_name}, {ignore_term} and {ignore_term2}"),
        (f"{feature}, {ignore_term} and {ignore_term2}", "{feature}, {ignore_term} and {ignore_term2}"),
        (f"{brand}, {ignore_term} and {ignore_term2}", "{brand}, {ignore_term} and {ignore_term2}"),
        (f"{polymer}, {ignore_term} and {ignore_term2}", "{polymer}, {ignore_term} and {ignore_term2}"),

        (f"{ignore_term}, {ignore_term2} and {oem_name}", "{ignore_term}, {ignore_term2} and {oem_name}"),
        (f"{ignore_term}, {ignore_term2} and {auto_cert_name}", "{ignore_term}, {ignore_term2} and {auto_cert_name}"),
        (f"{ignore_term}, {ignore_term2} and {auto_cert_name}", "{ignore_term}, {ignore_term2} and {auto_cert_name}"),
        (f"{ignore_term}, {ignore_term2} and {feature}", "{ignore_term}, {ignore_term2} and {feature}"),
        (f"{ignore_term}, {ignore_term2} and {brand}", "{ignore_term}, {ignore_term2} and {brand}"),
        (f"{ignore_term}, {ignore_term2} and {polymer}", "{ignore_term}, {ignore_term2} and {polymer}"),

        (f"{filler} materials", "{filler} materials"),
        (f"{filler} grades", "{filler} grades"),
        (f"grades with {filler}", "grades with {filler}"),
        (f"materials with {filler}", "materials with {filler}"),
        (f"grades that have {property}", "grades that have {property}"),
        (f"materials that have {property}", "materials that have {property}"),
        (f"grades that have {ul_property}", "grades that have {ul_property}"),
        (f"materials that have {ul_property}", "materials that have {ul_property}"),
        (f"grades that have {ul_sub_property}", "grades that have {ul_sub_property}"),
        (f"materials that have {ul_sub_property}", "materials that have {ul_sub_property}"),

    ]

    output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [],  'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}
    random_query = random.choice(templates)
    query = random_query[0]

    if "{processing}" in random_query[1]:
        if processing in processing_syn_mapping:
            processing = processing_syn_mapping[processing]
            
        output['PROCESSING'].append(processing)
        if processing_count < process_th:
            processing_count += 1
        else:
            continue
    
    if "{processing2}" in random_query[1]:
        if processing2 in processing_syn_mapping:
            processing2 = processing_syn_mapping[processing2]
            
        output['PROCESSING'].append(processing2)
        if processing_count < process_th:
            processing_count += 1
        else:
            continue

    if "{feature}" in random_query[1]:
        if is_feature_spell_correct and corrected_feature:
            print(feature, random_query)
            feature = corrected_feature
        
        if feature in feature_syn_mapping:
            feature = feature_syn_mapping[feature]
            
        output['FEATURE'].append(feature)
        if feature_count < feat_th:
            feature_count += 1
        else:
            continue

    if "{feature2}" in random_query[1]:
        if feature2 in feature_syn_mapping:
            feature2 = feature_syn_mapping[feature2]
            
        output['FEATURE'].append(feature2)
        if feature_count < feat_th:
            feature_count += 1
        else:
            continue

    if "{delivery_form}" in random_query[1]:
        if delivery_form in delivery_syn_mapping:
            delivery_form = delivery_syn_mapping[delivery_form]
            
        output['DELIVERY_FORM'].append(delivery_form)
        if del_count < del_th:
            del_count += 1
        else:
            continue

    if "{delivery_form2}" in random_query[1]:
        if delivery_form2 in delivery_syn_mapping:
            delivery_form2 = delivery_syn_mapping[delivery_form2]
            
        output['DELIVERY_FORM'].append(delivery_form2)
        if del_count < del_th:
            del_count += 1
        else:
            continue

    if "{brand}" in random_query[1]:
        if brand in brand_syn_mapping:
            brand = brand_syn_mapping[brand]
            
        output['BRAND'].append(brand)
        if brand_count < brand_th:
            brand_count += 1
        else:
            continue

    if "{brand2}" in random_query[1]:
        if brand2 in brand_syn_mapping:
            brand2 = brand_syn_mapping[brand2]
            
        output['BRAND'].append(brand2)
        if brand_count < brand_th:
            brand_count += 1
        else:
            continue

    if "{polymer}" in random_query[1]:
        if polymer in polymer_syn_mapping:
            polymer = polymer_syn_mapping[polymer]
            
        output['POLYMER'].append(polymer)
        if polymer_count < poly_th:
            polymer_count += 1
        else:
            continue

    if "{polymer2}" in random_query[1]:
        if polymer2 in polymer_syn_mapping:
            polymer2 = polymer_syn_mapping[polymer2]
            
        output['POLYMER'].append(polymer2)
        if polymer_count < poly_th:
            polymer_count += 1
        else:
            continue

    if "{application}" in random_query[1]:
        if "oem_name" in random_query[1] or 'auto_cert_name' in random_query[1]:
            if industry == 'automotive & transportation':
                 print("#"*25, '\n', random_query[0], '\n', "#"*25)
            else:
                continue
            
        output['APPLICATION'].append(application)
        if industry != 'not mapped':
            output['INDUSTRY'].append(industry)
        if app_count < app_th:
            app_count += 1
        else:
            continue

    if "{continent}" in random_query[1]:
        output['REGION'].append(continent_region)
        if region_count < region_th:
            region_count += 1
        else:
            continue

    if "{country}" in random_query[1]:
        output['REGION'].append(country_region)
        if region_count < region_th:
            region_count += 1
        else:
            continue

    if "{state}" in random_query[1]:
        output['REGION'].append(state_region)
        if region_count < region_th:
            region_count += 1
        else:
            continue

    if "{city}" in random_query[1]:
        output['REGION'].append(city_region)
        if region_count < region_th:
            region_count += 1
        else:
            continue

    if "{grade}" in random_query[1]:
        output['GRADE'].append(grade)

    if "{competitor_grade}" in random_query[1]:
        output['COMPETITOR_GRADE'].append(competitor_grade)

    if "{nsf}" in random_query[1]:
        output['NSF_CERT'].append(nsf)
        if nsf_count < nsf_th:
            nsf_count += 1
            print("nsf: ", nsf_count)
        else:
            continue

    if "{ignore_term}" in random_query[1]:
        # here we are considering count based on query
        if ignore_terms_count < ignore_terms_th:
            ignore_terms_count += 1
        else:
            continue

    if "{water_name}" in random_query[1]:
        output['WATER_CERT'].append({"Standard": water[1].lower(), "Temp": [water[2].lower()]})
        if water_count < water_th:
            water_count += 1
            print("water: ", water_count)
        else:
            continue

    if "{railway_name}" in random_query[1]:
        output['RAILWAY_CERT'].append({"Standard": railway[3].lower(), "Hazard_Level": [railway[2].lower()], "Req_Set": [railway[1].lower()]})
        if railway_count < rail_th:
            railway_count += 1
        else:
            continue

    if "{railway_name2}" in random_query[1]:
        output['RAILWAY_CERT'][0]['Hazard_Level'].append(railway2[2].lower())
        output['RAILWAY_CERT'][0]['Req_Set'].append(railway2[1].lower())
        if railway_count < rail_th:
            railway_count += 1
        else:
            continue

    if  "{auto_cert_name}" in random_query[1]:
        output['AUTO_CERT'].append({'OEM': auto_cert[0], 'CERTS': [auto_cert_name]})
        if auto_cert_count < auto_th:
            auto_cert_count += 1
        else:
            continue
    
    if "{auto_cert_name2}" in random_query[1]:
        if auto_cert[0].lower() == auto_cert2[0].lower():
            output['AUTO_CERT'][0]['CERTS'].append(auto_cert_name2)
        else:
            output['AUTO_CERT'].append({'OEM': auto_cert2[0], 'CERTS': [auto_cert_name2]})
            
        if auto_cert_count < auto_th:
            auto_cert_count += 1
        else:
            continue
        
    if "{oem_name}" in random_query[1] and not "{auto_cert_name}" in random_query[1]:
        output['AUTO_CERT'].append({'OEM': auto_cert[0].lower(), 'CERTS': ['all']})
        if auto_cert_count < auto_th:
            auto_cert_count += 1
        else:
            continue

    if "{oem_name2}" in random_query[1] and not "{auto_cert_name2}" in random_query[1]:
        if auto_cert[0].lower() == auto_cert2[0].lower():
            continue
            
        output['AUTO_CERT'].append({'OEM': auto_cert2[0].lower(), 'CERTS': ['all']})
        if auto_cert_count < auto_th:
            auto_cert_count += 1
        else:
            continue

    if "{property}" in random_query[1]:
        output['PROPERTY'].append(property_details)
        if prop_count < prop_th:
            prop_count += 1
        else:
            continue

    if "{property2}" in random_query[1]:
        output['PROPERTY'].append(property2_details)
        if prop_count < prop_th:
            prop_count += 1
        else:
            continue

    if "{property_abb}" in random_query[1]:
        output['PROPERTY'].append(property_abb_details)
        if prop_abb_count < prop_abb_th:
            prop_abb_count += 1
        else:
            continue

    if "{property_abb2}" in random_query[1]:
        output['PROPERTY'].append(property_abb2_details)
        if prop_abb_count < prop_abb_th:
            prop_abb_count += 1
        else:
            continue

    if "{ul_property}" in random_query[1]:
        output['PROPERTY'].append(ul_property_details)
        if ul_prop_count < ul_prop_th:
            ul_prop_count += 1
        else:
            continue

    if "{ul_property2}" in random_query[1]:
        output['PROPERTY'].append(ul_property2_details)
        if ul_prop_count < ul_prop_th:
            ul_prop_count += 1
        else:
            continue
      
    # list of dicts
    if "{filler}" in random_query[1]:
        output['FILLER'].extend(filler_details)
        if filler_count < fill_th:
            filler_count += 1
        else:
            continue

    if "{property_rm}" in random_query[1]:
        output['PROPERTY'].extend(property_rm_details)
        if prop_range_count < prop_rm_th:
            prop_range_count += 1
        else:
            continue

    if "{property_rm2}" in random_query[1]:
        output['PROPERTY'].extend(property_rm2_details)
        if prop_range_count < prop_rm_th:
            prop_range_count += 1
        else:
            continue

    if "{ul_sub_property}" in random_query[1]:
        output['PROPERTY'].extend(ul_sub_property_details)
        if ul_sub_prop_count < ul_sub_prop_th:
            ul_sub_prop_count += 1
        else:
            continue

    # if "{ul_sub_property2}" in random_query[1]:
    #     output['PROPERTY'].extend(ul_sub_property2_details)
    #     if ul_sub_prop_count < ul_sub_prop_th:
    #         ul_sub_prop_count += 1
    #     else:
    #         continue

    row = {'Query': query,'Output': output} 
    if row not in generated_data:
        generated_data.append(row)
            
    
# generated_data[:50]

C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_6740\1632742568.py:10: DeprecationWarning: randrange() will raise TypeError in the future
  value = random.randrange(i[1],i[2])
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_6740\2640670372.py:21: DeprecationWarning: randrange() will raise TypeError in the future
  value = random.randrange(p_metadata[1],p_metadata[2])
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_6740\164086352.py:13: DeprecationWarning: randrange() will raise TypeError in the future
  value = random.randrange(p_metadata[1],p_metadata[2])

$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.16e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '2.16e-07', 'min': '1.94e-07', 'max': '2.38e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 1.76e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity', 'modifier': {'value': '1.76e-07', 'min': '1.58e-07', 'max': '1.94e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  1
nsf:  1
nsf:  2
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 9.63e-07
nsf:  3
nsf:  4
mpact resistant ('mpact resistant flow233.41 semi aromatic pa compression moldable', '{feature} {property_abb} {polymer} {processing}')
nsf:  5
contain recycle ('ktw, contain recycle', '{water_name}, {feature}')
water:  2
water:  3
water:  4
nsf:  6
nsf:  7
water:  5
nsf:  8
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 9.44e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 flow (m²/s)', 'modifier': {'value': '9.44e-07', 'min': '8.50e-07', 'max': '1.04e-06', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  6
nsf:  9
nsf:  10
nsf:  11
nsf:  12
water:  7
nsf:  13
nsf:  14
nsf:  15
water:  8
water:  9
nsf:  16
nsf:  17
water:  10
nsf:  18
nsf:  19
nsf:  20
nsf:  21
nsf:  22
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 7.76e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)', 'modifier': {'value': '7.76e-07', 'min': '6.98e-07', 'max': '8.54e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
#########################
 automotive cargo area-hook with daimler mercedes-dbl5409.20 pa66 approval
 #########################
water:  11
water:  12
nsf:  23
water:  13
edical grades ('thermoplastic vulcanizate and edical grades and lead-free soldering resistance', '{polymer} and {feature} and {feature2}')
water:  14
water:  15
water:  16
water:  17
nsf:  24
water:  18
nsf:  25
water:  19
water:  20
water:  21
nsf:  26
water:  22
water:  23
nsf:  27
water:  24
water:  25
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3.29e-07
water:  26
#########################
 daimler-benz approved for adapter for interior
 #########################
water:  27
nsf:  28
water:  28
nsf:  29
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 3.42e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity', 'modifier': {'value': '3.42e-07', 'min': '3.08e-07', 'max': '3.76e-07', 'unit': None}, 'property_type': 'property'}
water:  29
water:  30
water:  31
nsf:  30
water:  32
water:  33
water:  34
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.09e-07
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3.22e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '3.22e-07', 'min': '2.90e-07', 'max': '3.54e-07', 'unit': None}, 'property_type': 'property'}
#########################
 automotive fuel supply system-holder for daimler
 #########################
water:  35
hermal shock ('nylon 6,12, hermal shock, heat resistant', '{polymer}, {feature}, {feature2}')
nsf:  31
water:  36
water:  37
water:  38
nsf:  32
water:  39
water:  40
nsf:  33
water:  41
#########################
 tailgate housing for bmw
 #########################
water:  42
water:  43
water:  44
water:  45
water:  46
nsf:  34
nsf:  35
nsf:  36
nsf:  37
water:  47
nsf:  38
nsf:  39
#########################
 auto for vw
 #########################
nsf:  40
nsf:  41
water:  48
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 7.56e-07
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 1.037e-06
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)', 'modifier': {'value': '1.04e-06', 'min': '9.33e-07', 'max': '1.14e-06', 'unit': None}, 'property_type': 'property'}
water:  49
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 1.022e-06
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)', 'modifier': {'value': '1.02e-06', 'min': '9.20e-07', 'max': '1.12e-06', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  50
nsf:  42
water:  51
nsf:  43
water:  52
nsf:  44
nsf:  45
nsf:  46
nsf:  47
nsf:  48
water:  53
nsf:  49
water:  54
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 3.87e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity', 'modifier': {'value': '3.87e-07', 'min': '3.48e-07', 'max': '4.26e-07', 'unit': None}, 'property_type': 'property'}
asermark ('asermark, low density polyethylene, with 1mhz df =highest', '{feature}, {polymer}, with {property_rm}')
water:  55
nsf:  50
water:  56
water:  57
water:  58
nsf:  51
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3.26e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '3.26e-07', 'min': '2.93e-07', 'max': '3.59e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
nsf:  52
water:  59
nsf:  53
water:  60
nsf:  54
water:  61
water:  62
nsf:  55
water:  63
water:  64
nsf:  56
water:  65
water:  66
#########################
 bosch for resonator for engine
 #########################
thermal shock resstance ('kepital f10-03h lof, thermal shock resstance', '{grade}, {feature}')
nsf:  57
water:  67
water:  68
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3e-07
water:  69
#########################
 general motors (gm)-gmw17558ppa612 approved for emotor
 #########################
nsf:  58
water:  70
nsf:  59
nsf:  60
water:  71
nsf:  61
water:  72
#########################
 hinge for fuel lid for ford
 #########################
water:  73
aser markable ('nilamid b5 j20 bk 9005/x, nylon 66, aser markable', '{grade}, {polymer}, {feature}')
nsf:  62
water:  74
nsf:  63
nsf:  64
nsf:  65
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3.21e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '3.21e-07', 'min': '2.89e-07', 'max': '3.53e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  75
water:  76
nsf:  66
water:  77
nsf:  67
nsf:  68
nsf:  69
water:  78
nsf:  70
water:  79
water:  80
#########################
 flange for fuel module for li auto
 #########################
emissins ('amcel emissins sheetex', '{brand} {feature} {processing}')
nsf:  71
water:  81
medgrad ('kepital medgrad', '{brand} {feature}')
nsf:  72
water:  82
nsf:  73
water:  83
nsf:  74
water:  84
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3.02e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '3.02e-07', 'min': '2.72e-07', 'max': '3.32e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
nsf:  75
nsf:  76
water:  85
nsf:  77
nsf:  78
water:  86
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 5.87e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity', 'modifier': {'value': '5.87e-07', 'min': '5.28e-07', 'max': '6.46e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  87
nsf:  79
nsf:  80
#########################
 stellantis-chrysler approved for housing for battery pyro switch
 #########################
#########################
 great wall motor for housing for gasoline particulate filter (gpf) pressure sensor
 #########################
nsf:  81
#########################
 n28bn08-gf018 certification for rear spoiler
 #########################
nsf:  82
water:  88
nsf:  83
water:  89
water:  90
nsf:  84
water:  91
eplacement for aluminum ('nsf 42 and eplacement for aluminum', '{nsf} and {feature}')
nsf:  85
nsf:  86
nsf:  87
nsf:  88
water:  92
nsf:  89
water:  93
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3.65e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '3.65e-07', 'min': '3.29e-07', 'max': '4.02e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
nsf:  90
nsf:  91
water:  94
water:  95
nsf:  92
nsf:  93
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 5.35e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity', 'modifier': {'value': '5.35e-07', 'min': '4.81e-07', 'max': '5.88e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  96
nsf:  94
water:  97
water:  98
nsf:  95
water:  99
water:  100
laertr ('sh a - 91.0 laertr', '{property_abb} {feature}')
nsf:  96
#########################
 washer-m6 bolt for vw
 #########################
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 0 to 1.8, picking another random number: 0.343932481
************************* negative exponential
{'property_name': 'dimensional change', 'modifier': {'value': '3.44e-01', 'min': '3.10e-01', 'max': '3.78e-01', 'unit': '%'}, 'property_type': 'ul_property'}
nsf:  97
nsf:  98
nsf:  99
water:  101
nsf:  100
#########################
 stellantis-fca group approved for holder for safety belt
 #########################
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3.62e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '3.62e-07', 'min': '3.26e-07', 'max': '3.98e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  102
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3.05e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '3.05e-07', 'min': '2.74e-07', 'max': '3.36e-07', 'unit': None}, 'property_type': 'property'}
water:  103
water:  104
nsf:  101
water:  105
nsf:  102
nsf:  103
water:  106
nsf:  104
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 5.85e-07
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.52e-07
nsf:  105
nsf:  106
water:  107
nsf:  107
water:  108
water:  109
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 4.82e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity', 'modifier': {'value': '4.82e-07', 'min': '4.34e-07', 'max': '5.30e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
nsf:  108
water:  110
water:  111
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 1.518e-06
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 flow (m²/s)', 'modifier': {'value': '1.52e-06', 'min': '1.37e-06', 'max': '1.67e-06', 'unit': None}, 'property_type': 'property'}
nsf:  109
water:  112
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.83e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '2.83e-07', 'min': '2.55e-07', 'max': '3.11e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  113
water:  114
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 6.04e-07
nsf:  110
water:  115
nsf:  111
nsf:  112
water:  116
nsf:  113
water:  117
nsf:  114
nsf:  115
water:  118
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 8.59e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 flow (m²/s)', 'modifier': {'value': '8.59e-07', 'min': '7.73e-07', 'max': '9.45e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  119
nsf:  116
nsf:  117
nsf:  118
ydrophile ('compmod=moderate with excellent ydrophile', '{property_rm} with excellent {feature}')
susainability ('d = 84 susainability', '{property_abb} {feature}')
hlogen free flame retardant ('vectra laprene and hlogen free flame retardant', '{brand} {brand2} and {feature}')
nsf:  119
water:  120
water:  121
#########################
 suspensions bellow for mercedes
 #########################
#########################
 coolant tube for stellantis-fca group
 #########################
water:  122
nsf:  120
nsf:  121
nsf:  122
nsf:  123
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range -110 to 140, picking another random number: 54.119884384
nsf:  124
water:  123
#########################
 automotive fuel reservoir and flange for stellantis-chrysler
 #########################
water:  124
water:  125
nsf:  125
nsf:  126
nsf:  127
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.73e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity', 'modifier': {'value': '2.73e-07', 'min': '2.46e-07', 'max': '3.00e-07', 'unit': None}, 'property_type': 'property'}
nsf:  128
#########################
 floor mat retainer system with continental-sn579147 approval
 #########################
nsf:  129
nsf:  130
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.32e-07
nsf:  131
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 0 to 1.8, picking another random number: 1.197314216
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.3e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity', 'modifier': {'value': '2.30e-07', 'min': '2.07e-07', 'max': '2.53e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
#########################
 immersed coolant hose for bosch
 #########################
water:  126
nsf:  132
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 1.26e-07
nsf:  133
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.48e-07
nsf:  134
water:  127
nsf:  135
water:  128
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 1.71e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 flow (m²/s)', 'modifier': {'value': '1.71e-07', 'min': '1.54e-07', 'max': '1.88e-07', 'unit': None}, 'property_type': 'property'}
#########################
 fuel*pump*impeller for stellantis-chrysler
 #########################
water:  129
nsf:  136
water:  130
nsf:  137
water:  131
nsf:  138
water:  132
water:  133
tatic ('elongational stress f iso 21304 2 150 10 mpa =lowest and parallel linear thermal expansion close to 221.54e-6/k high tatic with glass less than 64', '{property_rm} and {property} high {feature} with {filler}')
water:  134
water:  135
nsf:  139
water:  136
nsf:  140
water:  137
nsf:  141
water:  138
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 1.99e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '1.99e-07', 'min': '1.79e-07', 'max': '2.19e-07', 'unit': None}, 'property_type': 'property'}
nsf:  142
water:  139
nsf:  143
water:  140
nsf:  144
nsf:  145
nsf:  146
water:  141
nsf:  147
water:  142
water:  143
nsf:  148
water:  144
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 1.78e-07
water:  145
water:  146
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.75e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '2.75e-07', 'min': '2.48e-07', 'max': '3.03e-07', 'unit': None}, 'property_type': 'property'}
water:  147
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.34e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 through plane (m²/s)', 'modifier': {'value': '2.34e-07', 'min': '2.11e-07', 'max': '2.57e-07', 'unit': None}, 'property_type': 'property'}
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 5.27e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity', 'modifier': {'value': '5.27e-07', 'min': '4.74e-07', 'max': '5.80e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
water:  148
nsf:  149
ight stabilized ('microwave oven component copolyester ight stabilized shock resistance', '{application} {polymer} {feature} {feature2}')
nsf:  150
water:  149
nsf:  151
ight stabilized or stable to light ('compmod=10802 mpa ight stabilized or stable to light', '{property} {feature}')
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2.2e-07 to 1.08e-06, picking another random number: 5.64e-07
************************* negative exponential
{'property_name': 'effective thermal diffusivity iso 22007-4 crossflow (m²/s)', 'modifier': {'value': '5.64e-07', 'min': '5.08e-07', 'max': '6.20e-07', 'unit': 'm²/s'}, 'property_type': 'property'}
brasion resistant ('pa66 flex = 59678mpa, brasion resistant', '{polymer} {property_abb}, {feature}')
nsf:  152
nsf:  153
nsf:  154
water:  150
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 2e-11 to 1.79e-06, picking another random number: 1.206e-06
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 3.09e-07
halogen fre ('polyamide 6/6 halogen fre gel spinning', '{polymer} {feature} {processing}')
nsf:  155
nsf:  156
#########################
 grc lip for bmw
 #########################
nsf:  157
water:  151
nsf:  158
mproved weld line ('nsf 61 at 23 degrees mproved weld line', '{water_name} {feature}')
water:  152
nsf:  159
nsf:  160
water:  153
nsf:  161
nsf:  162
water:  154
nsf:  163
water:  155
nsf:  164
edical grade ('hytrel nylon 6-12 edical grade', '{brand} {polymer} {feature}')
water:  156
water:  157
water:  158
water:  159
$$$$$$$$$$$$$$$$$$$$ value was 0.0 for property range 1.3e-07 to 3.8e-07, picking another random number: 2.75e-07
************************* negative exponential

In [222]:
templates

[('r 24 h l2', '{railway_name}'),
 ('r-24 h-l2', '{railway_name}'),
 ('r24 hl2', '{railway_name}'),
 ('r24 hl2', '{railway_name}'),
 ('r24 hl2', '{railway_name}'),
 ('r24hl2', '{railway_name}'),
 ('r24 hl2', '{railway_name}'),
 ('r24 hl2 r22 - hl3 (en 45545-2)', '{railway_name} {railway_name2}'),
 ('r24 hl2 and r22 - hl3 (en 45545-2)', '{railway_name} and {railway_name2}'),
 ('r24 hl2 or r22 - hl3 (en 45545-2)', '{railway_name} or {railway_name2}'),
 ('r24 hl2, r22 - hl3 (en 45545-2)', '{railway_name}, {railway_name2}'),
 ('gmw15812p-tpv(epdm+pp)-type 8m', '{auto_cert_name}'),
 ('gmw15812p-tpv(epdm+pp)-type 8m approval', '{auto_cert_name} approval'),
 ('gmw15812p-tpv(epdm+pp)-type 8m auto spec', '{auto_cert_name} auto spec'),
 ('gmw15812p-tpv(epdm+pp)-type 8m auto approval',
  '{auto_cert_name} auto approval'),
 ('gmw15812p-tpv(epdm+pp)-type 8m', '{auto_cert_name}'),
 ('gmw15812p-tpv(epdm+pp)-type 8m approval', '{auto_cert_name} approval'),
 ('gmw15812p-tpv(epdm+pp)-type 8m auto spec', '{auto_cert_name} auto spec'),
 ('gmw15812p-tpv(epdm+pp)-type 8m auto approval',
  '{auto_cert_name} auto approval'),
 ('general motors (gm)', '{oem_name}'),
 ('general motors (gm) approval', '{oem_name} approval'),
 ('general motors (gm) auto spec', '{oem_name} auto spec'),
 ('general motors (gm) auto approval', '{oem_name} auto approval'),
 ('general motors (gm) gmw15812p-tpv(epdm+pp)-type 8m',
  '{oem_name} {auto_cert_name}'),
 ('general motors (gm) - gmw15812p-tpv(epdm+pp)-type 8m',
  '{oem_name} - {auto_cert_name}'),
 ('general motors (gm) (gmw15812p-tpv(epdm+pp)-type 8m)',
  '{oem_name} ({auto_cert_name})'),
 ('general motors (gm) auto specs gmw15812p-tpv(epdm+pp)-type 8m',
  '{oem_name} auto specs {auto_cert_name}'),
 ('gmw15812p-tpv(epdm+pp)-type 8m wssm4d648b1',
  '{auto_cert_name} {auto_cert_name2}'),
 ('gmw15812p-tpv(epdm+pp)-type 8m wssm4d648b1',
  '{auto_cert_name} {auto_cert_name2}'),
 ('gmw15812p-tpv(epdm+pp)-type 8m wssm4d648b1 approval',
  '{auto_cert_name} {auto_cert_name2} approval'),
 ('gmw15812p-tpv(epdm+pp)-type 8m wssm4d648b1 auto spec',
  '{auto_cert_name} {auto_cert_name2} auto spec'),
 ('gmw15812p-tpv(epdm+pp)-type 8m and wssm4d648b1',
  '{auto_cert_name} and {auto_cert_name2}'),
 ('gmw15812p-tpv(epdm+pp)-type 8m + wssm4d648b1',
  '{auto_cert_name} + {auto_cert_name2}'),
 ('gmw15812p-tpv(epdm+pp)-type 8m or wssm4d648b1',
  '{auto_cert_name} or {auto_cert_name2}'),
 ('gmw15812p-tpv(epdm+pp)-type 8m, wssm4d648b1',
  '{auto_cert_name}, {auto_cert_name2}'),
 ('general motors (gm) gmw15812p-tpv(epdm+pp)-type 8m ford wssm4d648b1',
  '{oem_name} {auto_cert_name} {oem_name2} {auto_cert_name2}'),
 ('general motors (gm) gmw15812p-tpv(epdm+pp)-type 8m and ford wssm4d648b1',
  '{oem_name} {auto_cert_name} and {oem_name2} {auto_cert_name2}'),
 ('general motors (gm) gmw15812p-tpv(epdm+pp)-type 8m or ford wssm4d648b1',
  '{oem_name} {auto_cert_name} or {oem_name2} {auto_cert_name2}'),
 ('general motors (gm) - gmw15812p-tpv(epdm+pp)-type 8m ford - wssm4d648b1',
  '{oem_name} - {auto_cert_name} {oem_name2} - {auto_cert_name2}'),
 ('general motors (gm) (gmw15812p-tpv(epdm+pp)-type 8m) ford (wssm4d648b1)',
  '{oem_name} ({auto_cert_name}) {oem_name2} ({auto_cert_name2})'),
 ('charpy impact strength unnotch =lowest', '{property_rm}'),
 ('charpy impact strength unnotch =lowest charpy double notch (excellent)',
  '{property_rm} {property_rm2}'),
 ('charpy impact strength unnotch =lowest and charpy double notch (excellent)',
  '{property_rm} and {property_rm2}'),
 ('charpy impact strength unnotch =lowest or charpy double notch (excellent)',
  '{property_rm} or {property_rm2}'),
 ('charpy impact strength unnotch =lowest,  charpy double notch (excellent)',
  '{property_rm}, {property_rm2}'),
 ('charpy impact strength unnotch =lowest tape flexural modulus of 50513mpa in the range of 43546 - 68336 non-halogenated aramid fiber whisker with 31 total filler load',
  '{property_rm} {property} {feature} {filler}'),
 ('charpy impact strength unnotch =lowest tape flexural modulus of 50513mpa in the range of 43546 - 68336 good non-halogenated aramid fiber whisker with 31 total filler load',
  '{property_rm} {property} good {feature} {filler}'),
 ('charpy impact strength unnotch =lowest and tape flexural modulus of 50513mpa in the range of 43546 - 68336 high non-halogenated with aramid fiber whisker with 31 total filler load',
  '{property_rm} and {property} high {feature} with {filler}'),
 ('charpy impact strength unnotch =lowest and tape flexural modulus of 50513mpa in the range of 43546 - 68336 excellent non-halogenated with aramid fiber whisker with 31 total filler load',
  '{property_rm} and {property} excellent {feature} with {filler}'),
 ('aramid fiber whisker with 31 total filler load non-halogenated charpy impact strength unnotch =lowest tape flexural modulus of 50513mpa in the range of 43546 - 68336',
  '{filler} {feature} {property_rm} {property}'),
 ('charpy impact strength unnotch =lowest, tape flexural modulus of 50513mpa in the range of 43546 - 68336, non-halogenated, aramid fiber whisker with 31 total filler load',
  '{property_rm}, {property}, {feature}, {filler}'),
 ('tape flexural modulus of 50513mpa in the range of 43546 - 68336 good non-halogenated aramid fiber whisker with 31 total filler load charpy impact strength unnotch =lowest',
  '{property} good {feature} {filler} {property_rm}'),
 ('tape flexural modulus of 50513mpa in the range of 43546 - 68336 and high non-halogenated charpy impact strength unnotch =lowest with aramid fiber whisker with 31 total filler load',
  '{property} and high {feature} {property_rm} with {filler}'),
 ('excellent non-halogenated charpy impact strength unnotch =lowest and tape flexural modulus of 50513mpa in the range of 43546 - 68336 with aramid fiber whisker with 31 total filler load',
  'excellent {feature} {property_rm} and {property} with {filler}'),
 ('charpy impact strength unnotch =lowest tape flexural modulus of 50513mpa in the range of 43546 - 68336',
  '{property_rm} {property}'),
 ('charpy impact strength unnotch =lowest, tape flexural modulus of 50513mpa in the range of 43546 - 68336',
  '{property_rm}, {property}'),
 ('charpy impact strength unnotch =lowest and tape flexural modulus of 50513mpa in the range of 43546 - 68336',
  '{property_rm} and {property}'),
 ('charpy impact strength unnotch =lowest or tape flexural modulus of 50513mpa in the range of 43546 - 68336',
  '{property_rm} or {property}'),
 ('charpy impact strength unnotch =lowest + tape flexural modulus of 50513mpa in the range of 43546 - 68336',
  '{property_rm} + {property}'),
 ('charpy impact strength unnotch =lowest non-halogenated',
  '{property_rm} {feature}'),
 ('charpy impact strength unnotch =lowest with excellent non-halogenated',
  '{property_rm} with excellent {feature}'),
 ('charpy impact strength unnotch =lowest good non-halogenated',
  '{property_rm} good {feature}'),
 ('charpy impact strength unnotch =lowest, high non-halogenated',
  '{property_rm}, high {feature}'),
 ('charpy impact strength unnotch =lowest and non-halogenated',
  '{property_rm} and {feature}'),
 ('charpy impact strength unnotch =lowest + non-halogenated',
  '{property_rm} + {feature}'),
 ('charpy impact strength unnotch =lowest aramid fiber whisker with 31 total filler load',
  '{property_rm} {filler}'),
 ('charpy impact strength unnotch =lowest, aramid fiber whisker with 31 total filler load',
  '{property_rm}, {filler}'),
 ('charpy impact strength unnotch =lowest and aramid fiber whisker with 31 total filler load',
  '{property_rm} and {filler}'),
 ('charpy impact strength unnotch =lowest + aramid fiber whisker with 31 total filler load',
  '{property_rm} + {filler}'),
 ('good non-halogenated', 'good {feature}'),
 ('sp 389nw0148 nero with excellent non-halogenated',
  '{grade} with excellent {feature}'),
 ('hf with good non-halogenated anti-acid',
  '{brand} with good {feature} {feature2}'),
 ('hf with good non-halogenated and anti-acid',
  '{brand} with good {feature} and {feature2}'),
 ('grade with sh a - 91.0', 'grade with {property_abb}'),
 ('material with sh a - 91.0', 'material with {property_abb}'),
 ('sh a - 91.0', '{property_abb}'),
 ('sh a - 91.0', '{property_abb}'),
 ('sh a - 91.0', '{property_abb}'),
 ('sh a - 91.0 soft (91.0)', '{property_abb} {property_abb2}'),
 ('sh a - 91.0, soft (91.0)', '{property_abb}, {property_abb2}'),
 ('sh a - 91.0 and soft (91.0)', '{property_abb} and {property_abb2}'),
 ('sh a - 91.0 or soft (91.0)', '{property_abb} or {property_abb2}'),
 ('2011/65/eu mat of +863 compliant', '{ul_property}'),
 ('2011/65/eu mat of +863 compliant', '{ul_property}'),
 ('2011/65/eu mat of +863 compliant f-3 dres', '{ul_property} {ul_property2}'),
 ('2011/65/eu mat of +863 compliant f-3 dres', '{ul_property} {ul_property2}'),
 ('flamerating = vo', '{ul_sub_property}'),
 ('flamerating = vo', '{ul_sub_property}'),
 ('aramid fiber whisker with 31 total filler load', '{filler}'),
 ('aramid fiber whisker with 31 total filler load', '{filler}'),
 ('hf kep', '{brand} {brand2}'),
 ('hf kep', '{brand} {brand2}'),
 ('hf and kep', '{brand} and {brand2}'),
 ('hf, kep', '{brand}, {brand2}'),
 ('hf kep polyamide 6-6', '{brand} {brand2} {polymer}'),
 ('hf kep polyamide 6-6', '{brand} {brand2} {polymer}'),
 ('hf kep and polyamide 6-6', '{brand} {brand2} and {polymer}'),
 ('hf, kep, polyamide 6-6', '{brand}, {brand2}, {polymer}'),
 ('hf kep non-halogenated', '{brand} {brand2} {feature}'),
 ('hf kep non-halogenated', '{brand} {brand2} {feature}'),
 ('hf kep and non-halogenated', '{brand} {brand2} and {feature}'),
 ('hf, kep, non-halogenated', '{brand}, {brand2}, {feature}'),
 ('hf kep aramid fiber whisker with 31 total filler load',
  '{brand} {brand2} {filler}'),
 ('hf kep aramid fiber whisker with 31 total filler load',
  '{brand} {brand2} {filler}'),
 ('hf kep and aramid fiber whisker with 31 total filler load',
  '{brand} {brand2} and {filler}'),
 ('hf, kep, aramid fiber whisker with 31 total filler load',
  '{brand}, {brand2}, {filler}'),
 ('hf grade with sh a - 91.0, and 2011/65/eu mat of +863 compliant',
  '{brand} grade with {property_abb}, and {ul_property}'),
 ('hf grade with sh a - 91.0, and flamerating = vo',
  '{brand} grade with {property_abb}, and {ul_sub_property}'),
 ('aramid fiber whisker with 31 total filler load non-halogenated polyamide 6-6',
  '{filler} {feature} {polymer}'),
 ('polyamide 6-6 with sh a - 91.0 soft (91.0)',
  '{polymer} with {property_abb} {property_abb2}'),
 ('non-halogenated sh a - 91.0 polyamide 6-6 fibre spinning',
  '{feature} {property_abb} {polymer} {processing}'),
 ('products with sh a - 91.0', 'products with {property_abb}'),
 ('hf sh a - 91.0; soft (91.0)', '{brand} {property_abb}; {property_abb2}'),
 ('Find a material that is sh a - 91.0',
  'Find a material that is {property_abb}'),
 ('sh a - 91.0', '{property_abb}'),
 ('polyamide 6-6 sh a - 91.0 polyamide 10,10',
  '{polymer} {property_abb} {polymer2}'),
 ('looking for a polyamide 6-6 aramid fiber whisker with 31 total filler load with sh a - 91.0',
  'looking for a {polymer} {filler} with {property_abb}'),
 ('get polyamide 6-6 material with the condition, sh a - 91.0',
  'get {polymer} material with the condition, {property_abb}'),
 ('polyamide 6-6 with sh a - 91.0', '{polymer} with {property_abb}'),
 ('non-halogenated, polyamide 6-6, with sh a - 91.0',
  '{feature}, {polymer}, with {property_abb}'),
 ('sh a - 91.0 polyamide 6-6', '{property_abb} {polymer}'),
 ('sh a - 91.0 non-halogenated', '{property_abb} {feature}'),
 ('polyamide 6-6 sh a - 91.0, non-halogenated',
  '{polymer} {property_abb}, {feature}'),
 ('hf sh a - 91.0', '{brand} {property_abb}'),
 ('hf grade with charpy impact strength unnotch =lowest, and 2011/65/eu mat of +863 compliant',
  '{brand} grade with {property_rm}, and {ul_property}'),
 ('hf grade with charpy impact strength unnotch =lowest, and flamerating = vo',
  '{brand} grade with {property_rm}, and {ul_sub_property}'),
 ('aramid fiber whisker with 31 total filler load non-halogenated polyamide 6-6',
  '{filler} {feature} {polymer}'),
 ('polyamide 6-6 with charpy impact strength unnotch =lowest charpy double notch (excellent)',
  '{polymer} with {property_rm} {property_rm2}'),
 ('non-halogenated charpy impact strength unnotch =lowest polyamide 6-6 fibre spinning',
  '{feature} {property_rm} {polymer} {processing}'),
 ('products with charpy impact strength unnotch =lowest',
  'products with {property_rm}'),
 ('hf charpy impact strength unnotch =lowest; charpy double notch (excellent)',
  '{brand} {property_rm}; {property_rm2}'),
 ('Find a material that is charpy impact strength unnotch =lowest',
  'Find a material that is {property_rm}'),
 ('charpy impact strength unnotch =lowest', '{property_rm}'),
 ('polyamide 6-6 charpy impact strength unnotch =lowest polyamide 10,10',
  '{polymer} {property_rm} {polymer2}'),
 ('looking for a polyamide 6-6 aramid fiber whisker with 31 total filler load with charpy impact strength unnotch =lowest',
  'looking for a {polymer} {filler} with {property_rm}'),
 ('get polyamide 6-6 material with the condition, charpy impact strength unnotch =lowest',
  'get {polymer} material with the condition, {property_rm}'),
 ('polyamide 6-6 with charpy impact strength unnotch =lowest',
  '{polymer} with {property_rm}'),
 ('non-halogenated, polyamide 6-6, with charpy impact strength unnotch =lowest',
  '{feature}, {polymer}, with {property_rm}'),
 ('charpy impact strength unnotch =lowest polyamide 6-6',
  '{property_rm} {polymer}'),
 ('charpy impact strength unnotch =lowest non-halogenated',
  '{property_rm} {feature}'),
 ('polyamide 6-6 charpy impact strength unnotch =lowest, non-halogenated',
  '{polymer} {property_rm}, {feature}'),
 ('hf charpy impact strength unnotch =lowest', '{brand} {property_rm}'),
 ('cover for sunroof', '{application}'),
 ('polyamide 6-6', '{polymer}'),
 ('polyamide 6-6 non-halogenated', '{polymer} {feature}'),
 ('non-halogenated', '{feature}'),
 ('good non-halogenated', 'good {feature}'),
 ('hf non-halogenated', '{brand} {feature}'),
 ('polyamide 6-6 fibre spinning', '{polymer} {processing}'),
 ('hf polyamide 6-6', '{brand} {polymer}'),
 ('sp 389nw0148 nero polyamide 6-6', '{grade} {polymer}'),
 ('hf fibre spinning', '{brand} {processing}'),
 ('fibre spinning', '{processing}'),
 ('sp 389nw0148 nero hf', '{grade} {brand}'),
 ('hf polyamide 6-6 non-halogenated', '{brand} {polymer} {feature}'),
 ('polyamide 6-6 non-halogenated fibre spinning',
  '{polymer} {feature} {processing}'),
 ('hf micro-powder', '{brand} {delivery_form}'),
 ('sp 389nw0148 nero non-halogenated', '{grade} {feature}'),
 ('sp 389nw0148 nero with excellent non-halogenated',
  '{grade} with excellent {feature}'),
 ('non-halogenated fibre spinning', '{feature} {processing}'),
 ('polyamide 6-6 micro-powder', '{polymer} {delivery_form}'),
 ('hf polyamide 6-6 fibre spinning', '{brand} {polymer} {processing}'),
 ('sp 389nw0148 nero fibre spinning', '{grade} {processing}'),
 ('sp 389nw0148 nero non-halogenated micro-powder',
  '{grade} {feature} {delivery_form}'),
 ('micro-powder', '{delivery_form}'),
 ('sp 389nw0148 nero polyamide 6-6 non-halogenated',
  '{grade} {polymer} {feature}'),
 ('polyamide 6-6 non-halogenated micro-powder',
  '{polymer} {feature} {delivery_form}'),
 ('sp 389nw0148 nero polyamide 6-6 non-halogenated micro-powder',
  '{grade} {polymer} {feature} {delivery_form}'),
 ('hf non-halogenated fibre spinning', '{brand} {feature} {processing}'),
 ('polyamide 6-6, non-halogenated', '{polymer}, {feature}'),
 ('cover for sunroof, polyamide 6-6', '{application}, {polymer}'),
 ('hf, non-halogenated', '{brand}, {feature}'),
 ('polyamide 6-6, fibre spinning', '{polymer}, {processing}'),
 ('cover for sunroof, hf', '{application}, {brand}'),
 ('hf, polyamide 6-6', '{brand}, {polymer}'),
 ('sp 389nw0148 nero, polyamide 6-6', '{grade}, {polymer}'),
 ('cover for sunroof, non-halogenated', '{application}, {feature}'),
 ('cover for sunroof, polyamide 6-6, non-halogenated',
  '{application}, {polymer}, {feature}'),
 ('hf, fibre spinning', '{brand}, {processing}'),
 ('cover for sunroof, fibre spinning', '{application}, {processing}'),
 ('sp 389nw0148 nero, hf', '{grade}, {brand}'),
 ('cover for sunroof, hf, non-halogenated',
  '{application}, {brand}, {feature}'),
 ('hf, polyamide 6-6, non-halogenated', '{brand}, {polymer}, {feature}'),
 ('sp 389nw0148 nero, cover for sunroof', '{grade}, {application}'),
 ('polyamide 6-6, non-halogenated, fibre spinning',
  '{polymer}, {feature}, {processing}'),
 ('hf, micro-powder', '{brand}, {delivery_form}'),
 ('cover for sunroof, polyamide 6-6, fibre spinning',
  '{application}, {polymer}, {processing}'),
 ('sp 389nw0148 nero, non-halogenated', '{grade}, {feature}'),
 ('non-halogenated, fibre spinning', '{feature}, {processing}'),
 ('polyamide 6-6, micro-powder', '{polymer}, {delivery_form}'),
 ('sp 389nw0148 nero, hf, polyamide 6-6', '{grade}, {brand}, {polymer}'),
 ('hf, polyamide 6-6, fibre spinning', '{brand}, {polymer}, {processing}'),
 ('cover for sunroof, hf, fibre spinning',
  '{application}, {brand}, {processing}'),
 ('sp 389nw0148 nero, fibre spinning', '{grade}, {processing}'),
 ('cover for sunroof, micro-powder', '{application}, {delivery_form}'),
 ('sp 389nw0148 nero, non-halogenated, micro-powder',
  '{grade}, {feature}, {delivery_form}'),
 ('sp 389nw0148 nero, cover for sunroof, non-halogenated',
  '{grade}, {application}, {feature}'),
 ('micro-powder', '{delivery_form}'),
 ('sp 389nw0148 nero, polyamide 6-6, non-halogenated',
  '{grade}, {polymer}, {feature}'),
 ('polyamide 6-6, non-halogenated, micro-powder',
  '{polymer}, {feature}, {delivery_form}'),
 ('cover for sunroof, hf, micro-powder',
  '{application}, {brand}, {delivery_form}'),
 ('sp 389nw0148 nero, polyamide 6-6, non-halogenated, micro-powder',
  '{grade}, {polymer}, {feature}, {delivery_form}'),
 ('hf, non-halogenated, fibre spinning', '{brand}, {feature}, {processing}'),
 ('polyamide 6-6, polyamide 10,10', '{polymer}, {polymer2}'),
 ('polyamide 6-6, non-halogenated, anti-acid',
  '{polymer}, {feature}, {feature2}'),
 ('polyamide 6-6, polyamide 10,10, non-halogenated',
  '{polymer}, {polymer2}, {feature}'),
 ('cover for sunroof, polyamide 6-6, polyamide 10,10',
  '{application}, {polymer}, {polymer2}'),
 ('non-halogenated, anti-acid', '{feature}, {feature2}'),
 ('hf, non-halogenated, anti-acid', '{brand}, {feature}, {feature2}'),
 ('polyamide 6-6, polyamide 10,10, fibre spinning',
  '{polymer}, {polymer2}, {processing}'),
 ('polyamide 6-6, fibre spinning, blow molding',
  '{polymer}, {processing}, {processing2}'),
 ('cover for sunroof, non-halogenated, anti-acid',
  '{application}, {feature}, {feature2}'),
 ('cover for sunroof, polyamide 6-6, non-halogenated, anti-acid',
  '{application}, {polymer}, {feature}, {feature2}'),
 ('hf, fibre spinning, blow molding', '{brand}, {processing}, {processing2}'),
 ('hf, micro-powder, powder', '{brand}, {delivery_form}, {delivery_form2}'),
 ('polyamide 6-6, micro-powder , powder',
  '{polymer}, {delivery_form} , {delivery_form2}'),
 ('cover for sunroof, micro-powder, powder',
  '{application}, {delivery_form}, {delivery_form2}'),
 ('polyamide 6-6 polyamide 10,10', '{polymer} {polymer2}'),
 ('polyamide 6-6 non-halogenated anti-acid', '{polymer} {feature} {feature2}'),
 ('polyamide 6-6 polyamide 10,10 non-halogenated',
  '{polymer} {polymer2} {feature}'),
 ('cover for sunroof polyamide 6-6 polyamide 10,10',
  '{application} {polymer} {polymer2}'),
 ('non-halogenated anti-acid', '{feature} {feature2}'),
 ('hf non-halogenated anti-acid', '{brand} {feature} {feature2}'),
 ('polyamide 6-6 polyamide 10,10 fibre spinning',
  '{polymer} {polymer2} {processing}'),
 ('polyamide 6-6 fibre spinning blow molding',
  '{polymer} {processing} {processing2}'),
 ('cover for sunroof non-halogenated anti-acid',
  '{application} {feature} {feature2}'),
 ('cover for sunroof polyamide 6-6 non-halogenated anti-acid',
  '{application} {polymer} {feature} {feature2}'),

## Generated Data Value Count

In [223]:
print("total queries", len(generated_data))

counts = {
    'feature_count': feature_count, 'processing_count': processing_count, 'del_count': del_count, 'brand_count': brand_count, 
    'polymer_count': polymer_count, 'app_count': app_count, 'nsf_count': nsf_count, 'water_count': water_count, 'railway_count': railway_count,
    'filler_count': filler_count, 'ul_prop_count': ul_prop_count, 'ul_sub_prop_count': ul_sub_prop_count, 'prop_abb_count': prop_abb_count, 
    'prop_range_count': prop_range_count, 'prop_count': prop_count, 'auto_cert_count': auto_cert_count,
}
counts

total queries 18763

{'feature_count': 6500,
 'processing_count': 3500,
 'del_count': 2000,
 'brand_count': 6000,
 'polymer_count': 6500,
 'app_count': 3000,
 'nsf_count': 1000,
 'water_count': 1000,
 'railway_count': 1500,
 'filler_count': 2500,
 'ul_prop_count': 1500,
 'ul_sub_prop_count': 1400,
 'prop_abb_count': 1000,
 'prop_range_count': 1000,
 'prop_count': 2000,
 'auto_cert_count': 2500}

In [224]:
gen_df = pd.DataFrame(generated_data)
cols = ["Sl. No."] + list(gen_df)
gen_df["Sl. No."] = list(range(1, len(gen_df)+1))
gen_df = gen_df[cols]
gen_df

,Sl. No.,Query,Output
0,1,dtul1.8mpa=high lubricated,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
1,2,"blueridge, impet, total load of 94","{'GRADE': [], 'APPLICATION': [], 'BRAND': ['bl..."
2,3,los angeles,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
3,4,high current arc ignition (hai): plc3,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
4,5,looking for a pa 666 full load upto 39 with ex...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
...,...,...,...
18758,18759,i want an offset to durethan bkv50h2.0ef 90151...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
18759,18760,i want an offset to tarolox200g3 for slovakia,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
18760,18761,polyshine pbt d223 gf15 fr emea,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
18761,18762,pbt2000-201d asia,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
18762,18763,norway,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."

In [225]:
# gen_df.to_excel("./prod_generated_data_29_11_24.xlsx", header=True, index=False)
# gen_df.to_excel("./prod_generated_data_27_01_25.xlsx", header=True, index=False)
gen_df.to_excel(f"./prod_generated_data_{data_version}.xlsx", header=True, index=False)

## Additional Generated Data

### Data for Queries with Multiple UL Properties

In [226]:
multi_ul_sub_props = {'Query': [], 'Output': []}

for i in range(1, 50):
    p_details, query = get_ul_sub_properties()
    output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': p_details, 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}
    multi_ul_sub_props['Query'].append(query)
    multi_ul_sub_props['Output'].append(output)
    
multi_ul_sub_props_df = pd.DataFrame(multi_ul_sub_props)

cols = ["Sl. No."] + list(multi_ul_sub_props_df)
multi_ul_sub_props_df["Sl. No."] = list(range(1, len(multi_ul_sub_props_df)+1))
multi_ul_sub_props_df = multi_ul_sub_props_df[cols]
multi_ul_sub_props_df

got same properties
got same properties
got same properties
got same properties
got same properties
got same properties
got same properties

,Sl. No.,Query,Output
0,1,flame rating at 3.1mm v0 and glow wire temp of...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
1,2,749°c glow wire ignition temperature @ 0.8mm a...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
2,3,"flammabilityclassification of v 0, gwi temp 3m...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
3,4,relative thermal index - mechanical impact (rt...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
4,5,"hotwireignition of plc 0, high-current arc ign...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
5,6,relative thermal index ele (145°c) around 15% ...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
6,7,"high ampere arc ignition plc1, flame class rat...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
7,8,flamerate v 1 and relative thermal index - mec...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
8,9,rti-e maximum 149°c and glow-wire flammability...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
9,10,glow wire: 569.76 °c plc 1 (60 - 119) high-cur...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
10,11,85°c relative thermal index @ 1.2mm relative t...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
11,12,"rti-s=149°c, gwit at 0.6 780°c","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
12,13,relative thermal index - electrical (rti elec)...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
13,14,relative thermal index - electrical (rti elec)...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
14,15,"plc-3 hot wire ignition, min thickness 3, 666 ...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
15,16,"rtie minimum 69 °c and glow wire flame 714°c, ...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
16,17,gwf index between 536 - 1097°c and higharcigni...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
17,18,"high current arc ignition plc2, relative therm...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
18,19,flame rate=v 0 rti-s @ 1 of 178 °c,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
19,20,"relative thermal index strength - 124 °c, flam...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
20,21,"min thickness 3, 68 relative thermal index - m...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
21,22,"gwf index = 660 °c in the range of 20%, flamer...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
22,23,"high amp arc ignition: plc-0, flammabilityrati...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
23,24,"high amperage arc ignition category plc 0, fla...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
24,25,"hot wire ignition (hwi): plc1, flame class rat...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
25,26,"rti-s 102 - 247, high current arc @ 2.2 of plc-3","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
26,27,flame v-0 807 °c glow wire flame index @ 1.6mm,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
27,28,relative thermal index - mechanical strength: ...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
28,29,"rtiimp=179 °c, hwi at 5 of plc 2","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
29,30,gwitemperature=787fahrenheit and hwi plc 4 at ...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
30,31,relative thermal index - mechanical impact (rt...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
31,32,"rti imp = 213°f from 126 - 311, relative therm...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
32,33,"5 va flameclassification @ 1.6mm, glow wire fl...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
33,34,"hwi=plc4, plc 0 high current arc ignition (hai...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
34,35,"hot wire ignition @ 2 plc 2, rtiele=109kelvin","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
35,36,relative thermal index strength greater than 7...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
36,37,"rtii @ 1 of 98, glow wire flammability index g...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
37,38,"relative thermal index min 103 °c, 106 °c rela...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
38,39,high amp plc4 1mm thick. plc 4 (7 through 14 s...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
39,40,"hot-wireignition of plc-4, glow wire flame ind...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
40,41,"5-va, 0.1mm thickness high current arc ignitio...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
41,42,ul listed at 0.5mm of vo and relative thermal ...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
42,43,high amp-plc-3 v2 flamerating @ 1.5mm,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
43,44,"current ignition (plc 1), min thickness 0.1, 5...","{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
44,45,rti strength 217 °c from 125 - 265 flammabilit...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
45,46,relative thermal index mechanical strength <=1...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
46,47,high amp - plc-2 and flammability rating class...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
47,48,relative thermal index - electrical @ 0.7 of 1...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
48,49,5vb fr and glow wire temperature at 6mm 948,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."

In [227]:
# multi_ul_sub_props_df.to_excel("./multi_ul_sub_props_29_11_24.xlsx", header=True, index=False)
# multi_ul_sub_props_df.to_excel("./multi_ul_sub_props_27_01_25.xlsx", header=True, index=False)
multi_ul_sub_props_df.to_excel(f"./multi_ul_sub_props_{data_version}.xlsx", header=True, index=False)

### Data for queries with only Certification

In [228]:
auto_certifications_data = {'Query': [], 'Output': []}

for i in auto_certifications:
    query = random.choice([
        f"{i[0]} {i[1]}",
        f"{i[0]} {i[1]}",
        f"{i[0]} - {i[1]}",
        f"{i[0]} - {i[1]}",
        f"{i[0]} {i[1]} certification",
        f"{i[0]} {i[1]} auto approval",

        f"{i[1]} {i[0]}",

        f"{i[0]} {i[1]}",
        f"{i[0]} {i[1]}",
        f"{i[0]} - {i[1]}",
        f"{i[0]} - {i[1]}",
        f"{i[0]} {i[1]} certification",
        f"{i[0]} {i[1]} auto approval",

        f"{i[1]} {i[0]}",
        
        f"{i[0]} certifcation {i[1]} approval",
        f"{i[0]} auto approval {i[1]}",
        f"{i[0]} auto approval {i[1]} certifcation",

        f"{i[0]} certifcation {i[1]} approved",
        f"{i[0]} auto approved {i[1]}",
        f"{i[0]} auto approved {i[1]} certifcation",
        f"{i[0]} {i[1]} auto approved",

    ])
    output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [{'OEM': i[0], 'CERTS': [i[1]]}], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}
    auto_certifications_data['Query'].append(query)
    auto_certifications_data['Output'].append(output)
    
auto_certifications_data_df = pd.DataFrame(auto_certifications_data)

cols = ["Sl. No."] + list(auto_certifications_data_df)
auto_certifications_data_df["Sl. No."] = list(range(1, len(auto_certifications_data_df)+1))
auto_certifications_data_df = auto_certifications_data_df[cols]
auto_certifications_data_df

,Sl. No.,Query,Output
0,1,baic q-bjev 01.59 certification,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
1,2,baic - q-bjev 01.33,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
2,3,baic bas-491,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
3,4,baic bas-492,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
4,5,baic - q-bjev 01.59,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
...,...,...,...
980,981,li auto q-lia5310057 certification,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
981,982,geely q/jly j7111001a-2016,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
982,983,geely q/jly j7110235b-2018 auto approval,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
983,984,geely auto approved q/jly j7111001a-2016 certi...,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
984,985,geely q/jly j7110235b-2018,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."

In [229]:
# auto_certifications_data_df.to_excel("./auto_certifications_data_29_11_24.xlsx", header=True, index=False)
# auto_certifications_data_df.to_excel("./auto_certifications_data_27_01_25.xlsx", header=True, index=False)
auto_certifications_data_df.to_excel(f"./auto_certifications_data_{data_version}.xlsx", header=True, index=False)

### Data for Queries with only Grade / Competitor Grade

In [230]:
len(all_cgrades)

12257

In [231]:
len(filtered_gradenames)

4934

In [ ]:
filtered_gradenames[:25]

In [233]:
grade_cgrade_data = {'Query': [], 'Output': []}
for i in filtered_gradenames:
    i = i.replace('®', '').replace('™', '').strip()
    i = re.sub(r'^\((.*)\)$', r'\1', i)
    for suffix in remove_suffixes:
        i = re.sub(r'{}$'.format(re.escape(suffix)), '', i)

    i = i.strip()
    is_grade_without_space = random.choice([False, False, False, False, False, False, True])
    if is_grade_without_space:
        i = i.replace(' ', '')
        
    query = random.choice([
        f"{i} grade",
        f"looking for {i}",
        f"{i} material",
        f"{i}",
    ])
    output = {'GRADE': [i], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}
    grade_cgrade_data['Query'].append(query)
    grade_cgrade_data['Output'].append(output)

for i in all_cgrades:
    i = i.replace('®', '').replace('™', '').strip()
    i = re.sub(r'^\((.*)\)$', r'\1', i)
    for suffix in remove_suffixes:
        i = re.sub(r'{}$'.format(re.escape(suffix)), '', i)
        
    i = re.sub(r'{}$'.format(re.escape('')), '', i) 
    i = i.strip()
    is_comp_grade_without_space = random.choice([False, False, False, False, False, False, True])
    if is_comp_grade_without_space:
        i = i.replace(' ', '')
    query = random.choice([
        f"alternative for {i}",
        f"alternative to {i}",
        f"offset for {i}",
        f"offset to {i}",
        f"{i} offset",
        f"{i}",
    ])
    output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [i], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}
    grade_cgrade_data['Query'].append(query)
    grade_cgrade_data['Output'].append(output)

    
grade_cgrade_data_df = pd.DataFrame(grade_cgrade_data)

cols = ["Sl. No."] + list(grade_cgrade_data_df)
grade_cgrade_data_df["Sl. No."] = list(range(1, len(grade_cgrade_data_df)+1))
grade_cgrade_data_df = grade_cgrade_data_df[cols]
grade_cgrade_data_df

,Sl. No.,Query,Output
0,1,hostaform xgc15-lw01 xap material,"{'GRADE': ['hostaform xgc15-lw01 xap'], 'APPLI..."
1,2,looking for zenite 7140x,"{'GRADE': ['zenite 7140x'], 'APPLICATION': [],..."
2,3,lftr tpu-gf60-01-x,"{'GRADE': ['lftr tpu-gf60-01-x'], 'APPLICATION..."
3,4,kepex 3730gf,"{'GRADE': ['kepex 3730gf'], 'APPLICATION': [],..."
4,5,looking for hostaform c 9021 s1,"{'GRADE': ['hostaform c 9021 s1'], 'APPLICATIO..."
...,...,...,...
17186,17187,ultrasint pa6 fr black offset,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
17187,17188,alternative for epimix pbt nc q101,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
17188,17189,offset to tarolox gfr 2,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
17189,17190,nylene mach 6 offset,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
17190,17191,offset to genestar gn2330-1,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."

In [234]:
# grade_cgrade_data_df.to_excel("./grade_cgrade_data_29_11_24.xlsx", header=True, index=False)
# grade_cgrade_data_df.to_excel("./grade_cgrade_data_27_01_25.xlsx", header=True, index=False)
grade_cgrade_data_df.to_excel(f"./grade_cgrade_data_{data_version}.xlsx", header=True, index=False)

### Data for Queries with only Certification Nubmber (to avoid any confusion with grade/cgrade numbers)

In [235]:
certs_with_numbers = {
    'bmw': ['gs93016', '93016'],
    'bosch': ['gf019', 'ox067', 'bn02-gf034', 'bn05-ox019'],
    'catl': ['gf25-a-i01', 'gf30-x-i0x'],
    'ford': ['m4d639', 'm4d1016-a1', 'm4d861-a4', 'm4d1014'],
    'geely': ['p1 0370', '0367', '0369'],
    'general motors (gm)': ['17025', '17327p', '17327', '15702-250051', '250051', '15702-250058', '250058', 'pet.002', '15702-120032', '120032', '16270p', '16270', '3038p', '15702-110080', '18066', '17961', '110052'],
    'honda': ['0094z', 'ghaf-9810-m1', '9810-m1', '9810'],
    'hyundai': ['216-03', '94103', '220-24', '220-08 type a', '211-72'],
    'mercedes-benz': ['5403', '5562', '5562 aa39', '5403.21', '5408.45'],
    'nio': ['sm.51.010', 'sm.51', '51.010', '51010', '51.003', '51.010-c4'],
    'opel (psa)': ['000637', '006611', '0006612', '0006615'],
    'stellantis - chrysl': ['50103', 'db-448', '50017'],
    'stellantis-psa group': ['0300', '620300', '62 0300'],
    'tesla': ['1006', '102160', '1006 102160'],
    'vw group': ['50136', '52683', '50127', '50125'],
    'valeo': ['15009', '15006'],
}

In [236]:
certs_with_numbers_data = {'Query': [], 'Output': []}

for oem in certs_with_numbers:
    for cert in certs_with_numbers[oem]:
        query = random.choice([
            f"{cert} certified",
            f"{cert} certification",
            f"{cert} certifications",
            f"grade with {cert} certified",
            f"material with {cert} certified",
            f"{cert} certified grade",
            f"{cert} certified material",
        ])
        output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [{'OEM': oem, 'CERTS': [cert]}], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}
        certs_with_numbers_data['Query'].append(query)
        certs_with_numbers_data['Output'].append(output)
        certs_with_numbers_data['Query'].append(f"{cert}")
        certs_with_numbers_data['Output'].append(output)

gen_auto_num_df = pd.DataFrame(certs_with_numbers_data)
cols = ["Sl. No."] + list(gen_auto_num_df)
gen_auto_num_df["Sl. No."] = list(range(1, len(gen_auto_num_df)+1))
gen_auto_num_df = gen_auto_num_df[cols]
gen_auto_num_df

,Sl. No.,Query,Output
0,1,grade with gs93016 certified,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
1,2,gs93016,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
2,3,grade with 93016 certified,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
3,4,93016,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
4,5,material with gf019 certified,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
...,...,...,...
137,138,50125,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
138,139,15009 certification,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
139,140,15009,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
140,141,15006 certifications,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."
141,142,15006,"{'GRADE': [], 'APPLICATION': [], 'BRAND': [], ..."

In [237]:
# gen_auto_num_df.to_excel("./prod_generated_data_auto_num_29_11_24.xlsx", header=True, index=False)
# gen_auto_num_df.to_excel("./prod_generated_data_auto_num_27_01_25.xlsx", header=True, index=False)
gen_auto_num_df.to_excel(f"./prod_generated_data_auto_num_{data_version}.xlsx", header=True, index=False)

### Data for "Melting temperature of Celcon m90?" type of queries

In [238]:
prop_grade_data = {'Query': [], 'Output': []}
for i in range(50):
    g = random.choice(filtered_gradenames)
    g = g.replace('®', '').replace('™', '').strip()
    g = re.sub(r'^\((.*)\)$', r'\1', g)
    for suffix in remove_suffixes:
        g = re.sub(r'{}$'.format(re.escape(suffix)), '', g)

    g = g.strip()
    is_grade_without_space = random.choice([False, False, False, False, False, False, True])
    if is_grade_without_space:
        g = g.replace(' ', '')

    p_metadata = random.choice(property_and_values)
    property_name = p_metadata[-1].lower()
    property_name_meaning = p_metadata[0].lower()
    property_details = {'property_name': property_name_meaning, 'modifier': {'value': None, 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}

    query = random.choice([
        f"{property_name} of {g}",
        f"{property_name} of {g}",
        f"{property_name} of {g}",
        f"{property_name} of {g}?",
        f"{property_name} value of {g}?",
        f"what is the {property_name} of {g}?",
        f"what is the {property_name} value of {g}?",
    ])
    output = {'GRADE': [g], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [property_details], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}
    prop_grade_data['Query'].append(query)
    prop_grade_data['Output'].append(output)

gen_prop_grade_df = pd.DataFrame(prop_grade_data)
cols = ["Sl. No."] + list(gen_prop_grade_df)
gen_prop_grade_df["Sl. No."] = list(range(1, len(gen_prop_grade_df)+1))
gen_prop_grade_df = gen_prop_grade_df[cols]
gen_prop_grade_df

,Sl. No.,Query,Output
0,1,"tangent delta, 1mhz of frianyl a3 rv0 or 2011/...","{'GRADE': ['frianyl a3 rv0 or 2011/p(s)'], 'AP..."
1,2,what is the strain at break 50 mm/min of a3 rv...,"{'GRADE': ['a3 rv0 bk 9005/aa'], 'APPLICATION'..."
2,3,what is the elongation at break 50 mm/min valu...,"{'GRADE': ['celcon uv270z'], 'APPLICATION': []..."
3,4,dissipation factor of htn51g45hslr bk420,"{'GRADE': ['htn51g45hslr bk420'], 'APPLICATION..."
4,5,what is the melt index of hf xt 90?,"{'GRADE': ['hf xt 90'], 'APPLICATION': [], 'BR..."
5,6,what is the yield strain 50 mm/min value of cr...,"{'GRADE': ['crastin t803 nc010'], 'APPLICATION..."
6,7,what is the nominal break elongation value of ...,"{'GRADE': ['lft pa66-cf40-01-us'], 'APPLICATIO..."
7,8,surface resistivity of lft pbt-gf40-09?,"{'GRADE': ['lft pbt-gf40-09'], 'APPLICATION': ..."
8,9,what is the izod impact strength unnotch value...,"{'GRADE': ['fortronfx4330t7'], 'APPLICATION': ..."
9,10,what is the break elongation 5mm/min value of ...,"{'GRADE': ['va 9116'], 'APPLICATION': [], 'BRA..."
10,11,melt mass flow rate value of b3 h gf30 nc 1102/e?,"{'GRADE': ['b3 h gf30 nc 1102/e'], 'APPLICATIO..."
11,12,what is the tensile stress at 50% strain value...,"{'GRADE': ['stp 8211-45'], 'APPLICATION': [], ..."
12,13,"tensile stress at 100% deformation, perpendicu...","{'GRADE': ['ateva 1807asb'], 'APPLICATION': []..."
13,14,intrvisc of sofprenebase35smod/55antry359as06,{'GRADE': ['sofprenebase35smod/55antry359as06'...
14,15,effective thermal diffusivity of sofprene s229...,"{'GRADE': ['sofprene s229-60a'], 'APPLICATION'..."
15,16,dielectric factor at 100hz of hostaform m90xap,"{'GRADE': ['hostaform m90xap'], 'APPLICATION':..."
16,17,what is the coefficient of linear thermal expa...,"{'GRADE': ['kepital te-22s'], 'APPLICATION': [..."
17,18,what is the charpy impact strength notch of la...,"{'GRADE': ['laprene 8m3x5901a75'], 'APPLICATIO..."
18,19,failure flex strain of ryn545bk504,"{'GRADE': ['ryn545bk504'], 'APPLICATION': [], ..."
19,20,nominal break strain of cra 6003 nc010,"{'GRADE': ['cra 6003 nc010'], 'APPLICATION': [..."
20,21,tape flex stress of fortron 1140e7,"{'GRADE': ['fortron 1140e7'], 'APPLICATION': [..."
21,22,what is the flexural strength of fri xt6 gf30 ...,"{'GRADE': ['fri xt6 gf30 v0i bk 9005'], 'APPLI..."
22,23,flexible of zenite 7755,"{'GRADE': ['zenite 7755'], 'APPLICATION': [], ..."
23,24,charpy unnotched impact of fo1100l0,"{'GRADE': ['fo1100l0'], 'APPLICATION': [], 'BR..."
24,25,"what is the mould-shrinkage, parallel of 83fm9...","{'GRADE': ['83fm9za70 nero'], 'APPLICATION': [..."
25,26,moulding shrinkage of gur 4113,"{'GRADE': ['gur 4113'], 'APPLICATION': [], 'BR..."
26,27,h20 absorption of lftr pa66-sf10-02,"{'GRADE': ['lftr pa66-sf10-02'], 'APPLICATION'..."
27,28,what is the strebr at 50mm/min of ve v201p?,"{'GRADE': ['ve v201p'], 'APPLICATION': [], 'BR..."
28,29,elongation yield 50 mm/min of 237fz4752z fuxia...,"{'GRADE': ['237fz4752z fuxia l698'], 'APPLICAT..."
29,30,strain break 5mm/min of cx 1500a,"{'GRADE': ['cx 1500a'], 'APPLICATION': [], 'BR..."
30,31,what is the n tenile impact of omnipro hpp tf2...,"{'GRADE': ['omnipro hpp tf20 av'], 'APPLICATIO..."
31,32,izod notched impact strength of lp8eca65b,"{'GRADE': ['lp8eca65b'], 'APPLICATION': [], 'B..."
32,33,mold shrinkage (td) of gur 5113?,"{'GRADE': ['gur 5113'], 'APPLICATION': [], 'BR..."
33,34,tensile strength tape value of cx 2300 gv1/50?,"{'GRADE': ['cx 2300 gv1/50'], 'APPLICATION': [..."
34,35,tensile strain at break of z ce198-60a,"{'GRADE': ['z ce198-60a'], 'APPLICATION': [], ..."
35,36,tape flex strength of hf xgc10 ef xap2,"{'GRADE': ['hf xgc10 ef xap2'], 'APPLICATION':..."
36,37,what is the charpy double notch value of rynit...,"{'GRADE': ['rynite pcr108 bk515'], 'APPLICATIO..."
37,38,"tensile stress at 100% deformation, perpendicu...","{'GRADE': ['minlon 11c40 bkb086'], 'APPLICATIO..."
38,39,what is the charpy notched impact strength val...,{'GRADE': ['celstran lft pp-gf60-0453 bf p10/1...
39,40,charpy unnotched value of kepital fs2022?,"{'GRADE': ['kepital fs2022'], 'APPLICATION': [..."
40,41,melting temperature of htn52g35hsl nc010?,"{'GRADE': ['htn52g35hsl nc010'], 'APPLICATION'..."
41,42,tensile stress at yield of hyt htr9010 nc010,"{'GRADE': ['hyt htr9010 nc010'], 'APPLICATION'..."
42,43,elongation yield 50 mm/min of impet 2700 gv1/45,"{'GRADE': ['impet 2700 gv1/45'], 'APPLICATION'..."
43,44,what is the vicat softing temp at 50°c/h 50n v...,"{'GRADE': ['cx 3200'], 'APPLICATION': [], 'BRA..."
44,45,sh d of celstran lft pbt-sf10-03?,"{'GRADE': ['celstran lft pbt-sf10-03'], 'APPLI..."
45,46,what is the glass transition of fp 6e5901a80?,"{'GRADE': ['fp 6e5901a80'], 'APPLICATION': [],..."
46,47,elongational stress f of lfrt cfr-tp pet gf60-10,"{'GRADE': ['lfrt cfr-tp pet gf60-10'], 'APPLIC..."
47,48,tensile creep modulus at 1h of frianyl a3 v2 o...,"{'GRADE': ['frianyl a3 v2 or 2003/p'], 'APPLIC..."
48,49,flexural stress at 3.5% iso 178 (mpa) of impet...,"{'GRADE': ['impet 830r'], 'APPLICATION': [], '..."
49,50,unnotch charpy impact value of hostaform s 936...,"{'GRADE': ['hostaform s 9364 xap2 eco-c 772'],..."

In [239]:
# gen_prop_grade_df.to_excel("./prod_generated_data_prop_grade_29_11_24.xlsx", header=True, index=False)
# gen_prop_grade_df.to_excel("./prod_generated_data_prop_grade_27_11_25.xlsx", header=True, index=False)
gen_prop_grade_df.to_excel(f"./prod_generated_data_prop_grade_{data_version}.xlsx", header=True, index=False)

## Enhancement Data (enhancement_queries.xlsx)

### Data for Polymer-Total Load ("POM 15%") and Brand-Total Load ("Celcon 15%")

In [240]:
# poly_brand_total_load_data = {'Query': [], 'Output': []}
# for i in range(30):
#     tl = random.choice(list(range(10, 61)))
#     brand = random.choice(all_brands).lower()       
        
#     is_brand_syn = random.choice([False, False, True])
#     if is_brand_syn and brand in brand_syns:
#         brand = random.choice(brand_syns[brand])

#     query = random.choice([
#         f"{brand} {tl}%",
#         f"{brand} {tl}%",
#         f"{brand}{tl}%",
#         f"{tl}% {brand}",
#         f"{tl}% {brand}",
#         f"{tl}%{brand}",
#     ])

#     if brand in brand_syn_mapping:
#         brand_meaning = brand_syn_mapping[brand]
#     else:
#         brand_meaning = brand
        
#     output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}        
#     output['BRAND'].append(brand_meaning)
#     output['FILLER'].append({'total_load': {'value': tl, 'min': tl-5, 'max': tl+5}})
#     poly_brand_total_load_data['Query'].append(query)
#     poly_brand_total_load_data['Output'].append(output)

# for i in range(30):
#     tl = random.choice(list(range(10, 61)))
#     polymer = random.choice(all_polymers).lower()  
    
#     is_polymer_syn = random.choice([False, True, True])
#     if is_polymer_syn and polymer in polymer_syns:
#         polymer = random.choice(polymer_syns[polymer])
    
#     query = random.choice([
#         f"{polymer} {tl}%",
#         f"{polymer} {tl}%",
#         f"{polymer}{tl}%",
#         f"{tl}% {polymer}",
#         f"{tl}% {polymer}",
#         f"{tl}%{polymer}",
#     ])

#     if polymer in polymer_syn_mapping:
#         polymer_meaning = polymer_syn_mapping[polymer]
#     else:
#         polymer_meaning = polymer
            
#     output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}        
#     output['POLYMER'].append(polymer_meaning)
#     output['FILLER'].append({'total_load': {'value': tl, 'min': tl-5, 'max': tl+5}})
#     poly_brand_total_load_data['Query'].append(query)
#     poly_brand_total_load_data['Output'].append(output)

# gen_poly_brand_total_load_df = pd.DataFrame(poly_brand_total_load_data)
# cols = ["Sl. No."] + list(gen_poly_brand_total_load_df)
# gen_poly_brand_total_load_df["Sl. No."] = list(range(1, len(gen_poly_brand_total_load_df)+1))
# gen_poly_brand_total_load_df = gen_poly_brand_total_load_df[cols]
# gen_poly_brand_total_load_df

In [241]:
## gen_poly_brand_total_load_df.to_excel("./prod_generated_data_poly_brand_tl_29_11_24.xlsx", header=True, index=False)

### Data for the properties that has common name

In [242]:
# ambiguity_prop_syns_mapping = {
#     'charpy': 'charpy',
#     'izod': 'izod',
#     # 'flammability': 'flammability',
#     'impact': 'impact strength',
#     'notched impact': 'notched impact',
#     'shore': 'shore',
#     'shore hardness': 'shore',
#     'strain at break': 'strain at break',
#     'strength': 'tensile stress',
#     'stress at 100% elongation': 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
#     'stress at break': 'stress at break',
#     'temperature': 'temperature',
#     'tensile': 'tensile',
#     'tensile strength': 'tensile strength',
#     'tensile stress at 100% elongation': 'tensile stress at 100% elongation iso 37 perpendicular (mpa)',
#     'tensile stress at break': 'stress at break',
#     'viscosity': 'viscosity',
# }

In [243]:
# prop_ambiguity_data = {'Query': [], 'Output': []}

# for i in range(5):
#     for syn in ambiguity_prop_syns_mapping:
#         v = random.randint(10, 200)
#         query = random.choice([
#             f"{syn} of {v}",
#             f"{syn} {v}",
#             f"{v} {syn}",
#             f"{syn} = {v}",
#             f"{v} = {syn}",
#             f"{syn}: {v}",
    
#         ])
#         output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}         
#         output['PROPERTY'].append({'property_name': ambiguity_prop_syns_mapping[syn], 'modifier': {'value': v, 'min': v*0.9, 'max': v*1.1, 'unit': ''}, 'property_type': 'property'})
#         prop_ambiguity_data['Query'].append(query)
#         prop_ambiguity_data['Output'].append(output)


# gen_prop_ambiguity_df = pd.DataFrame(prop_ambiguity_data)
# cols = ["Sl. No."] + list(gen_prop_ambiguity_df)
# gen_prop_ambiguity_df["Sl. No."] = list(range(1, len(gen_prop_ambiguity_df)+1))
# gen_prop_ambiguity_df = gen_prop_ambiguity_df[cols]
# gen_prop_ambiguity_df

In [244]:
## gen_prop_ambiguity_df.to_excel("./prod_generated_data_prop_ambiguity_29_11_24.xlsx", header=True, index=False)

### Data for Region

In [245]:
# addtional_region_data = {'asia pacific': ['indian',
#   'australian',
#   'japanese',
#   'russian',
#   'chinese',
#   'korean',
#   'thai',
#   'vietnamese',
#   'indonesian',
#   'malaysian',
#   'philippine',
#   'new zealander'],
#  'europe middle east africa': ['italian',
#   'french',
#   'german',
#   'south african',
#   'spanish',
#   'british',
#   'egyptian',
#   'swedish',
#   'norwegian',
#   'finnish',
#   'danish',
#   'polish',
#   'dutch',
#   'belgian',
#   'swiss',
#   'austrian'],
#  'americas': ['brazilian',
#   'canadian',
#   'mexican',
#   'argentinian',
#   'chilean',
#   'peruvian',
#   'colombian',
#   'venezuelan',
#   'uruguayan',
#   'cuban',
#   'jamaican']}

In [246]:
# region_data = {'Query': [], 'Output': []}

# for i in addtional_region_data:
#     for j in addtional_region_data[i]:
#         query = random.choice([
#             f"{j} grades",
#             f"{j} materials",
#             f"{j}",
#         ])
#         output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': [i]}
#         region_data['Query'].append(query)
#         region_data['Output'].append(output)


# for i in addtional_region_data:
#     for j in addtional_region_data[i]:
#         query = random.choice([
#             f"{j} grades",
#             f"{j} materials",
#             f"{j}",
#         ])
#         output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': [i]}
#         region_data['Query'].append(query)
#         region_data['Output'].append(output)

    
# region_data_df = pd.DataFrame(region_data)

# cols = ["Sl. No."] + list(region_data_df)
# region_data_df["Sl. No."] = list(range(1, len(region_data_df)+1))
# region_data_df = region_data_df[cols]
# region_data_df

In [247]:
## region_data_df.to_excel("./region_queries_29_11_24.xlsx", header=True, index=False)

### Data for "NB" value properties

In [248]:
# nb_properties = []
# for p_details in unique_values['Property']:
#     if p_details['String_value_for_toggle']:
#         nb_properties.append(p_details['PROPERTY_NAME_UI'].lower())

# nb_properties

In [249]:
# property_and_nb_values = []
# for i in nb_properties:
#     for j in property_and_values:
#         if j[0] in i:
#             if (j[0], j[-1], 'nb') not in property_and_nb_values:
#                 property_and_nb_values.append((j[0], j[-1], 'nb'))

# property_and_nb_values

In [250]:
# prop_nb_data = {'Query': [], 'Output': []}
# property_and_nb_values = [
#     ('charpy', 'charpy'),
#     ('izod', 'izod'),
#     ('impact strength', 'impact'),
# ]
# for i in range(25):
#     for p in property_and_nb_values:
#         pname = p[1]
#         query = random.choice([
#             f"{pname} nobreak",
#             f"{pname} no break",
#             f"{pname} no-break",
#             f"{pname} nb",
            
#             f"nobreak {pname}",
#             f"no break {pname}",
#             f"no-break {pname}",
#             f"nb {pname}",
            
#             f"{pname} (nobreak)",
#             f"{pname} (no break)",
#             f"{pname} (no-break)",
#             f"{pname} (nb)",
            
#             f"(nobreak) {pname}",
#             f"(no break) {pname}",
#             f"(no-break) {pname}",
#             f"(nb) {pname}",
#         ])
#         output = {'GRADE': [], 'APPLICATION': [], 'BRAND': [], 'POLYMER': [], 'PROPERTY': [{'property_name': p[0], 'modifier': {'value': 'nb', 'min': None, 'max': None, 'unit': ''}, 'property_type': 'property'}], 'FILLER': [], 'FEATURE': [], 'PROCESSING': [], 'DELIVERY_FORM': [], 'COMPETITOR_GRADE': [], 'AUTO_CERT': [], 'RAILWAY_CERT': [], 'WATER_CERT': [], 'NSF_CERT': [], 'INDUSTRY': [], 'REGION': []}
#         prop_nb_data['Query'].append(query)
#         prop_nb_data['Output'].append(output)
    
# prop_nb_data_df = pd.DataFrame(prop_nb_data)

# cols = ["Sl. No."] + list(prop_nb_data_df)
# prop_nb_data_df["Sl. No."] = list(range(1, len(prop_nb_data_df)+1))
# prop_nb_data_df = prop_nb_data_df[cols]
# prop_nb_data_df

In [251]:
## prop_nb_data_df.to_excel("./prop_nb_data_29_11_24.xlsx", header=True, index=False)