In [10]:
# !pip install thefuzz

In [11]:
import re, copy
import json
from thefuzz import fuzz
from thefuzz import process as process
import pandas as pd

In [12]:
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine

#QA Snowflake connection #using for Hot-fix of Flouring release
# snowflake_connection_string = "jdbc:snowflake://celanese-celanytics.privatelink.snowflakecomputing.com/?user=SVC_ADF&password=<SNOWFLAKE_PASSWORD>&db=ANALYTICS_QA&warehouse=REPORTING_WH&role=DATA_ANALYST_GST"
#Dev Snowflake connection
snowflake_connection_string = "jdbc:snowflake://celanese-celanytics.privatelink.snowflakecomputing.com/?user=SVC_ADF&password=<SNOWFLAKE_PASSWORD>&db=ANALYTICS_DEV&warehouse=REPORTING_WH&role=DATA_ANALYST_GST"
parts = snowflake_connection_string.split("//")[1].split("/")  
account = ".".join(parts[0].split('.')[:2]) 
user = parts[1].split('user=')[1].split('&')[0] 
password = parts[1].split('password=')[1].split('&')[0] 
database = parts[1].split('db=')[1].split('&')[0]
warehouse = parts[1].split('warehouse=')[1].split('&')[0]  
role = parts[1].split('role=')[1]

engine = create_engine(URL(
    account = account,
    user = user,
    password = password,
    database = database,
    schema = 'gst_curated',
    warehouse = warehouse,
    role = role
))
cur = engine.connect()

engine = create_engine(URL(
    account = account,
    user = user,
    password = password,
    database = "ANALYTICS_DEV",
    # database = "ANALYTICS_QA", #use for skipping the new brands updated in the Dev #F-hot-fix
    schema = 'gst_curated',
    warehouse = warehouse,
    role = role
))
cur_dev = engine.connect()

def read_data_from_snowflake_table(cur,query):
    df = pd.read_sql(query, cur)
    return df

In [13]:
competitor_data = read_data_from_snowflake_table(cur,"select * from competitor_data")
competitor_names = competitor_data['competitor'].unique()

In [15]:
outOfScopeData = json.load(open("../dependencies/outOfScopeData.json"))

outOfScopeDataGrades = outOfScopeData['grades']

normalized_unique_values_current = json.load(open("../dependencies/normalized_unique_values_for_grade_mapping.json"))

In [16]:
[i for i in normalized_unique_values_current["GRADE"] if "nylon" in i]

[]

In [17]:
unique_values = json.load(open("../dependencies/unique_values_22_02_24.json"))
def normalize_string(s):
    # Remove special characters and convert to lower case
    return re.sub(r'\W+', '', s).lower()

In [18]:
# def find_substring_items(list1, list2):
#     result = []
#     for item2 in list2:
#         for item1 in list1:
#             if len(item1)>3 and item1 in item2:
#                 print({item1:item2})
#                 result.append(item2)
#                 break  # Break to avoid duplicate entries of the same item2
#     return result

# items_to_remove_from_comp_grade = find_substring_items(unique_values['BRAND'], unique_values['COMPETITOR_GRADE'])

In [19]:
# unique_values['COMPETITOR_GRADE'] = [item for item in unique_values['COMPETITOR_GRADE'] if item not in items_to_remove_from_comp_grade]

unique_values['GRADE_WITHOUT_BRAND'] = list(set(unique_values['GRADE_WITHOUT_BRAND'] + ["dym", "eco-b", "eco b","eco-r", "eco r", "fit", "frhr", "hfs", "hhr",
"hrlm", "hrt", "hsl", "hslr", "hte", "htn", "htr", "ice", 
"icf", "lof", "lof2", "pcxxx", "pls/xt", 
"scxxx", "sea", "slidex", "wrf", "xap", "xap2", "xfr", "xgc"]))

# with open("../dependencies/unique_values_01_02_24.json", "w") as fp:
#     json.dump(unique_values , fp)

In [20]:
database

'ANALYTICS_DEV'

In [21]:
color_code_df = read_data_from_snowflake_table(cur_dev,"""select * from GST_CURATED.AUSP_SAP_MATERIAL_COLOR_CODE""")
# color_code_df = read_data_from_snowflake_table(cur_dev,"""select * from GST_CURATED.AUSP_SAP_MATERIAL_COLOR_CODE""")
ce_grades_with_color_code = color_code_df['sap_material_desc'].unique().tolist()
ce_grades_with_color_code = list(set([grade.lower().lstrip('zzdel').lstrip("dev ").strip() for grade in ce_grades_with_color_code]))
ce_grades_with_color_code = list(set([grade for grade in ce_grades_with_color_code if grade!='']))
ce_grades_with_color_code = list(set([normalize_string(i) for i in ce_grades_with_color_code]))

In [22]:
[i for i in ce_grades_with_color_code if "nw02" in i]

['nnw02xapcd3501blackimpa1',
 'nnw02cf2001naturalimpa1',
 'coilelecherionw0201solvlv24vdc',
 'coilelecherionw0200220v',
 'nnw02blackimpa1']

In [23]:
len(ce_grades_with_color_code)

434001

In [24]:
spt = read_data_from_snowflake_table(cur,"""select * from SPT""")
ce_grades = spt['product_cd'].unique().tolist()

In [25]:
spt_brands = [re.sub(r'\W+', '', brand).lower() for brand in list(spt['product_line'].unique())]
display(len(spt_brands))

35

In [ ]:
# validating the list of ce grades present (since for bug 203909 minlon grades were not populated in unique value list)
# df_ce_grades = pd.DataFrame(ce_grades)
# df_ce_grades.to_csv('celanese_grades_list.csv', index=False, header=False)

In [32]:
features = read_data_from_snowflake_table(cur,"""select * from FEATURE""")
all_features =list(set(features[features['property_name'].isin(['Special characteristics', 'Processing','Delivery form'])]['value_assmnt_si']))

In [33]:
col = 'brand'
feature = 'feature'
ignore_syn=[]
ignore_key=[]
positives = []
# SYNONYM data from dev database i.e. "analytics_dev". Refer to "DEFINED_NAME" and "SYNONYMS".
synonym_df = read_data_from_snowflake_table(cur_dev,"""select * from SYNONYM""")
synonym_df.columns = [x.upper() if x.islower() else x for x in synonym_df.columns]
synonym_df = synonym_df.apply(lambda x: x.str.lower())
display(synonym_df.head())
feature_synonyms = synonym_df.copy()

synonym_df = synonym_df[synonym_df['TYPE'] == col]
# feature_df = synonym_df[synonym_df['TYPE'] == feature]

synonym_df2 = synonym_df[["DEFINED_NAME", "SYNONYMS"]].copy()
synonym_df2 = synonym_df2.dropna().reset_index(drop=True)
# synonym_df2 = synonym_df2[synonym_df2['SYNONYMS'].apply(lambda x : False if ";" in x else True)].reset_index(drop=True)
# synonym_df2 = synonym_df2[synonym_df2['SYNONYMS'].apply(lambda x : True if ";" in x else False)].reset_index(drop=True)
brand_synonyms = synonym_df2.to_dict(orient='records')
brands_with_synonym = [item['DEFINED_NAME'] for item in brand_synonyms]
brand_synonyms  = {item['DEFINED_NAME']: item['SYNONYMS'] for item in brand_synonyms}
for k in brand_synonyms:
    if ";" in brand_synonyms[k]:
        brand_synonyms[k] = [x.strip() for x in  brand_synonyms[k].split(';') if x!=k]

brand_synonyms['ateva'] = ['at']
brands_with_synonym.append('ateva')


new_grade_names = []
for i in brands_with_synonym:
   brand_pattern = fr'^{re.escape(i)}\b'
   for grade in unique_values['GRADE']:
      if re.match(brand_pattern, grade):
         for s in brand_synonyms[i]:
            new_grade_names.append(re.sub(brand_pattern, s, grade))

# new_grade_names

        TYPE   DEFINED_NAME                                           SYNONYMS
0  auto cert  mercedes-benz  mercedes-benz; daimler; daimler-benz; daimler ...
1  auto cert       vw group                              vw group; vw; bentley
2      brand        abistir                                            abistir
3      brand          amcel                                          amcel; am
4      brand             at                                                 at

In [34]:
feature_synonyms = feature_synonyms[feature_synonyms['TYPE'] == feature]
feature_synonyms2 = feature_synonyms[["DEFINED_NAME", "SYNONYMS"]].copy()
feature_synonyms2 = feature_synonyms2.dropna().reset_index(drop=True)

In [35]:
feature_synonyms2['SYNONYM_LIST'] = feature_synonyms2['SYNONYMS'].apply(lambda x: [i.strip() for i in x.split(';') if len(i.strip())>1] if ";" in x else [i.strip() for i in x.split(',') if len(i.strip())>1] if "," in x else [x])

In [36]:
feature_synonyms2

,DEFINED_NAME,SYNONYMS,SYNONYM_LIST
0,anti-static,anti-static; static resistant; static; static ...,"[anti-static, static resistant, static, static..."
1,bio-content,bio-content; bio-based; bio; biobased; eco-b,"[bio-content, bio-based, bio, biobased, eco-b]"
2,carbon capture,carbon capture; reduce carbon capture; reduced...,"[carbon capture, reduce carbon capture, reduce..."
3,recycled content,recycled content; contains recycle; recycle; r...,"[recycled content, contains recycle, recycle, ..."
4,flame retardant,flame retardant; flameretardent; fr; flame ret...,"[flame retardant, flameretardent, fr, flame re..."
5,heat stabilized,heat stabilized or stable to heat; stable to h...,"[heat stabilized or stable to heat, stable to ..."
6,high flow,high flow; high mv; high flowability; low visc...,"[high flow, high mv, high flowability, low vis..."
7,high gloss,high gloss; enhanced gloss; highgloss,"[high gloss, enhanced gloss, highgloss]"
8,high viscosity,high viscosity; low mv; low flow; highvisc,"[high viscosity, low mv, low flow, highvisc]"
9,hydrolysis resistant,hydrolysis resistant; hydrolysis; water resist...,"[hydrolysis resistant, hydrolysis, water resis..."
10,hydrophilic,hydrophilic; hydrophile; absorbent; water aff...,"[hydrophilic, hydrophile, absorbent, water aff..."
11,impact modified,impact modified; high impact or impact modifie...,"[impact modified, high impact or impact modifi..."
12,improved creep,improved creep; creep resistance; creep resist...,"[improved creep, creep resistance, creep resis..."
13,improved weld line,improved weld line; weld line improved; weld l...,"[improved weld line, weld line improved, weld ..."
14,increased electrical conductivity,increased electrical conductivity; electro con...,"[increased electrical conductivity, electro co..."
15,increased thermal conductivity,increased thermal conductivity; thermal conduc...,"[increased thermal conductivity, thermal condu..."
16,laser direct structurable,laser direct structurable; lds; laser direct s...,"[laser direct structurable, lds, laser direct ..."
17,laser markable,laser markable; lm; lasermarkable; laser marki...,"[laser markable, lm, lasermarkable, laser mark..."
18,laser weldable,laser weldable; lt; laser transparent; lasertr...,"[laser weldable, lt, laser transparent, lasert..."
19,lead-free soldering resistant,lead-free soldering resistant; surface mount s...,"[lead-free soldering resistant, surface mount ..."
20,light stabilized,light stabilized or stable to light; light sta...,"[light stabilized or stable to light, light st..."
21,light weight,light weight; light weighting; replacement for...,"[light weight, light weighting, replacement fo..."
22,low emissions,low emissions; low emission; reduced emission;...,"[low emissions, low emission, reduced emission..."
23,low halide content,low halide content,[low halide content]
24,low warpage,low warpage; low warp; warp resistant; lowwarp...,"[low warpage, low warp, warp resistant, lowwar..."
25,low wear / low friction,low wear / low friction; low wear; low frictio...,"[low wear / low friction, low wear, low fricti..."
26,lubricants,lubricants; lubricated; lubric,"[lubricants, lubricated, lubric]"
27,medical/healthcare,medical/healthcare; medical; medical grade; me...,"[medical/healthcare, medical, medical grade, m..."
28,non-halogenated/red phosphorous free flame ret...,non-halogenated/red phosphorous free flame ret...,[non-halogenated/red phosphorous free flame re...
29,nucleated,nucleated; high crystallinity; highly crystall...,"[nucleated, high crystallinity, highly crystal..."
30,pfas-free,"ptfe-free, no pfas, forever chemical free, ptf...","[ptfe-free, no pfas, forever chemical free, pt..."
31,plasticizer,plasticizer; plasticiser; plasti,"[plasticizer, plasticiser, plasti]"
32,platable,platable; plateable; plating grade,"[platable, plateable, plating grade]"
33,reduced gloss,reduced gloss; low gloss; redugloss,"[reduced gloss, low gloss, redugloss]"
34,release agent,release agent; release,"[release agent, release]"
35,specialty appearance,specialty appearance; lx; metalx; appearance; ...,"[specialty appearance, lx, metalx, appearance,..."
36,static dissipative,static dissipative; esd; esd modified; elecdis...,"[static dissipative, esd, esd modified, elecdi..."
37,sustainable,sustainable; green; circular economy; eco; env...,"[sustainable, green, circular economy, eco, en..."
38,thermal shock resistant,thermal shock resistant; thermal shock resista...,"[thermal shock resistant, thermal shock resist..."
39,u.v. stabilized,u.v. stabilized; u.v. stabilised; u.v. stabili...,"[u.v. stabilized, u.v. stabilised, u.v. stabil..."
40,ultrasonic weldable,ultrasonic weldable,[ultrasonic weldable]

In [37]:
feature_syn_dict = feature_synonyms2.to_dict(orient='records')
feature_syn_dict = {item['DEFINED_NAME']: item['SYNONYM_LIST'] for item in feature_syn_dict}

In [38]:
feature_syn_dict

{'anti-static': ['anti-static',
  'static resistant',
  'static',
  'static resistance',
  'antistatic',
  'avoid static',
  'avoid static build',
  'avoid static build up'],
 'bio-content': ['bio-content', 'bio-based', 'bio', 'biobased', 'eco-b'],
 'carbon capture': ['carbon capture',
  'reduce carbon capture',
  'reduced carbon footprint',
  'carbon footprint',
  'carbon footprint',
  'iso 14067',
  'carbon capture and utilization',
  'ccu',
  'eco-c'],
 'recycled content': ['recycled content',
  'contains recycle',
  'recycle',
  'recycled',
  'eco-r',
  'post consumer recycle',
  'post-consumer recycle',
  'pcr',
  'pir',
  'post industrial recycle',
  'post-industrial recycle'],
 'flame retardant': ['flame retardant',
  'flameretardent',
  'fr',
  'flame retarding agent',
  'flamret',
  'flamretag',
  'flame resistant',
  'flame resistance',
  'halogenated fr',
  'halogenated',
  'halogenated flame retardant'],
 'heat stabilized': ['heat stabilized or stable to heat',
  'stable to heat',
  'heat resistance',
  'heat resistant',
  'heat tolerant',
  'high heat performance',
  'high heat',
  'heat stabilized',
  'heat stabilised',
  'heat',
  'heat stable',
  'high heat conditions',
  'resistant to heat',
  'hhr',
  'thermal resistance',
  'thermal resistant',
  'anti heat',
  'anti-heat'],
 'high flow': ['high flow',
  'high mv',
  'high flowability',
  'low viscosity',
  'easy flow',
  'thin wall',
  'low wall'],
 'high gloss': ['high gloss', 'enhanced gloss', 'highgloss'],
 'high viscosity': ['high viscosity', 'low mv', 'low flow', 'highvisc'],
 'hydrolysis resistant': ['hydrolysis resistant',
  'hydrolysis',
  'water resistant',
  'anti hydrolysis',
  'hydrolysis resistance',
  'water resistance',
  'anti-hydrolysis',
  'anti-water',
  'hydrostable',
  'not hygroscopic'],
 'hydrophilic': ['hydrophilic',
  'hydrophile',
  'absorbent',
  'water affinity',
  'hydrophilicity',
  'hygroscopic'],
 'impact modified': ['impact modified',
  'high impact or impact modified',
  'toughened',
  'im',
  'impact resistance',
  'impact resistant',
  'anti impact',
  'anti-impact',
  'impact grade',
  'impact modification',
  'improved toughness',
  'tough'],
 'improved creep': ['improved creep',
  'creep resistance',
  'creep resistant',
  'anti creep',
  'anti-creep',
  'creep resistant'],
 'improved weld line': ['improved weld line',
  'weld line improved',
  'weld line strength'],
 'increased electrical conductivity': ['increased electrical conductivity',
  'electro conductive',
  'electrical conductivity'],
 'increased thermal conductivity': ['increased thermal conductivity',
  'thermal conductivity',
  'heat dissipation'],
 'laser direct structurable': ['laser direct structurable',
  'lds',
  'laser direct structuring',
  'laser direct structuring (lds)'],
 'laser markable': ['laser markable',
  'lm',
  'lasermarkable',
  'laser marking',
  'lasermark'],
 'laser weldable': ['laser weldable',
  'lt',
  'laser transparent',
  'lasertr',
  'lasertransparent',
  'laser weld',
  'laser transmission'],
 'lead-free soldering resistant': ['lead-free soldering resistant',
  'surface mount solderable',
  'smd solderable',
  'lead-free reflow solderable',
  'lead-free solderability',
  'lead-free soldering resistance',
  'pb free solder reflow',
  'anti lead free soldering'],
 'light stabilized': ['light stabilized or stable to light',
  'light stabilised or stable to light',
  'light stabilised',
  'light stabilized',
  'stable to light'],
 'light weight': ['light weight',
  'light weighting',
  'replacement for aluminum',
  'metal replacement'],
 'low emissions': ['low emissions',
  'low emission',
  'reduced emission',
  'low-e',
  'lowemiss',
  'emissions',
  'low formaldehyde',
  'low voc'],
 'low halide content': ['low halide content'],
 'low warpage': ['low warpage',
  'low warp',
  'warp resistant',
  'lowwarp',
  'high flatness',
  'warp resistance',
  'anti warp',
  'anti-warp'],
 'low wear / low friction': ['low wear / low friction',
  'low wear',
  'low friction',
  'tribo',
  'tribological',
  'low wear and friction',
  'tribological modified',
  'tribology',
  'good sliding',
  'lw',
  'abrasion resistance',
  'abrasion resistant',
  'silicone modified',
  'ptfe modified',
  'silicon oil concentrate',
  'silicone',
  'silicone concentrate',
  'tf'],
 'lubricants': ['lubricants', 'lubricated', 'lubric'],
 'medical/healthcare': ['medical/healthcare',
  'medical',
  'medical grade',
  'medgrade',
  'medhc',
  'medical grades',
  'healthcare',
  'medical grade technology',
  'mt',
  'med'],
 'non-halogenated/red phosphorous free flame retardant': ['non-halogenated/red phosphorous free flame retardant',
  'halogen free',
  'haogen free',
  'nhfr',
  'hffr',
  'halogen free flame retardant',
  'non-halogenated',
  'non-halogenated fr'],
 'nucleated': ['nucleated',
  'high crystallinity',
  'highly crystalline',
  'highest cristalline'],
 'pfas-free': ['ptfe-free',
  'no pfas',
  'forever chemical free',
  'ptfe free',
  'pfas free',
  'pfas-free',
  'pfas alternatives',
  'pfas-alternatives'],
 'plasticizer': ['plasticizer', 'plasticiser', 'plasti'],
 'platable': ['platable', 'plateable', 'plating grade'],
 'reduced gloss': ['reduced gloss', 'low gloss', 'redugloss'],
 'release agent': ['release agent', 'release'],
 'specialty appearance': ['specialty appearance',
  'lx',
  'metalx',
  'appearance',
  'aesthetical',
  'good aesthetics',
  'visual fx'],
 'static dissipative': ['static dissipative',
  'esd',
  'esd modified',
  'elecdiss',
  'elec diss',
  'electdiss',
  'elect diss',
  'electrostatic dissipation',
  'electrostatic dissipative'],
 'sustainable': ['sustainable',
  'green',
  'circular economy',
  'eco',
  'environmentally friendly',
  'sustainability'],
 'thermal shock resistant': ['thermal shock resistant',
  'thermal shock resistance',
  'thermal shock',
  'shock resistance',
  'shock resistant',
  'anti thermal shock',
  'anti-thermal shock'],
 'u.v. stabilized': ['u.v. stabilized',
  'u.v. stabilised',
  'u.v. stabilized or stable to weather',
  'u.v. stabilised or stable to weather',
  'uv resistant',
  'uv',
  'anti uv',
  'anti-uv',
  'uv-stabilized',
  'exposure to outdoor sunlight',
  'uv resistent',
  'uvres',
  'uv stabilise',
  'uv',
  'uv stability',
  'weather resistance',
  'weather resistant',
  'uv resistance',
  'weatherable',
  'stable to weather',
  'weather',
  'solar resistance'],
 'ultrasonic weldable': ['ultrasonic weldable']}

In [39]:
for k in feature_syn_dict:
    if ";" in feature_syn_dict[k]:
        feature_syn_dict[k] = [x.strip() for x in  feature_syn_dict[k].split(';') if x!=k]
feature_syn_dict

feature_list = []

for k, v in feature_syn_dict.items():
    temp_list = []
    temp_list.append(k)
    if isinstance(v, list):
        temp_list.append(v)
    # else:
    #     feature_list.append(v)
    feature_list.append(temp_list)
feature_list

[['anti-static',
  ['anti-static',
   'static resistant',
   'static',
   'static resistance',
   'antistatic',
   'avoid static',
   'avoid static build',
   'avoid static build up']],
 ['bio-content', ['bio-content', 'bio-based', 'bio', 'biobased', 'eco-b']],
 ['carbon capture',
  ['carbon capture',
   'reduce carbon capture',
   'reduced carbon footprint',
   'carbon footprint',
   'carbon footprint',
   'iso 14067',
   'carbon capture and utilization',
   'ccu',
   'eco-c']],
 ['recycled content',
  ['recycled content',
   'contains recycle',
   'recycle',
   'recycled',
   'eco-r',
   'post consumer recycle',
   'post-consumer recycle',
   'pcr',
   'pir',
   'post industrial recycle',
   'post-industrial recycle']],
 ['flame retardant',
  ['flame retardant',
   'flameretardent',
   'fr',
   'flame retarding agent',
   'flamret',
   'flamretag',
   'flame resistant',
   'flame resistance',
   'halogenated fr',
   'halogenated',
   'halogenated flame retardant']],
 ['heat stabilized',
  ['heat stabilized or stable to heat',
   'stable to heat',
   'heat resistance',
   'heat resistant',
   'heat tolerant',
   'high heat performance',
   'high heat',
   'heat stabilized',
   'heat stabilised',
   'heat',
   'heat stable',
   'high heat conditions',
   'resistant to heat',
   'hhr',
   'thermal resistance',
   'thermal resistant',
   'anti heat',
   'anti-heat']],
 ['high flow',
  ['high flow',
   'high mv',
   'high flowability',
   'low viscosity',
   'easy flow',
   'thin wall',
   'low wall']],
 ['high gloss', ['high gloss', 'enhanced gloss', 'highgloss']],
 ['high viscosity', ['high viscosity', 'low mv', 'low flow', 'highvisc']],
 ['hydrolysis resistant',
  ['hydrolysis resistant',
   'hydrolysis',
   'water resistant',
   'anti hydrolysis',
   'hydrolysis resistance',
   'water resistance',
   'anti-hydrolysis',
   'anti-water',
   'hydrostable',
   'not hygroscopic']],
 ['hydrophilic',
  ['hydrophilic',
   'hydrophile',
   'absorbent',
   'water affinity',
   'hydrophilicity',
   'hygroscopic']],
 ['impact modified',
  ['impact modified',
   'high impact or impact modified',
   'toughened',
   'im',
   'impact resistance',
   'impact resistant',
   'anti impact',
   'anti-impact',
   'impact grade',
   'impact modification',
   'improved toughness',
   'tough']],
 ['improved creep',
  ['improved creep',
   'creep resistance',
   'creep resistant',
   'anti creep',
   'anti-creep',
   'creep resistant']],
 ['improved weld line',
  ['improved weld line', 'weld line improved', 'weld line strength']],
 ['increased electrical conductivity',
  ['increased electrical conductivity',
   'electro conductive',
   'electrical conductivity']],
 ['increased thermal conductivity',
  ['increased thermal conductivity',
   'thermal conductivity',
   'heat dissipation']],
 ['laser direct structurable',
  ['laser direct structurable',
   'lds',
   'laser direct structuring',
   'laser direct structuring (lds)']],
 ['laser markable',
  ['laser markable', 'lm', 'lasermarkable', 'laser marking', 'lasermark']],
 ['laser weldable',
  ['laser weldable',
   'lt',
   'laser transparent',
   'lasertr',
   'lasertransparent',
   'laser weld',
   'laser transmission']],
 ['lead-free soldering resistant',
  ['lead-free soldering resistant',
   'surface mount solderable',
   'smd solderable',
   'lead-free reflow solderable',
   'lead-free solderability',
   'lead-free soldering resistance',
   'pb free solder reflow',
   'anti lead free soldering']],
 ['light stabilized',
  ['light stabilized or stable to light',
   'light stabilised or stable to light',
   'light stabilised',
   'light stabilized',
   'stable to light']],
 ['light weight',
  ['light weight',
   'light weighting',
   'replacement for aluminum',
   'metal replacement']],
 ['low emissions',
  ['low emissions',
   'low emission',
   'reduced emission',
   'low-e',
   'lowemiss',
   'emissions',
   'low formaldehyde',
   'low voc']],
 ['low halide content', ['low halide content']],
 ['low warpage',
  ['low warpage',
   'low warp',
   'warp resistant',
   'lowwarp',
   'high flatness',
   'warp resistance',
   'anti warp',
   'anti-warp']],
 ['low wear / low friction',
  ['low wear / low friction',
   'low wear',
   'low friction',
   'tribo',
   'tribological',
   'low wear and friction',
   'tribological modified',
   'tribology',
   'good sliding',
   'lw',
   'abrasion resistance',
   'abrasion resistant',
   'silicone modified',
   'ptfe modified',
   'silicon oil concentrate',
   'silicone',
   'silicone concentrate',
   'tf']],
 ['lubricants', ['lubricants', 'lubricated', 'lubric']],
 ['medical/healthcare',
  ['medical/healthcare',
   'medical',
   'medical grade',
   'medgrade',
   'medhc',
   'medical grades',
   'healthcare',
   'medical grade technology',
   'mt',
   'med']],
 ['non-halogenated/red phosphorous free flame retardant',
  ['non-halogenated/red phosphorous free flame retardant',
   'halogen free',
   'haogen free',
   'nhfr',
   'hffr',
   'halogen free flame retardant',
   'non-halogenated',
   'non-halogenated fr']],
 ['nucleated',
  ['nucleated',
   'high crystallinity',
   'highly crystalline',
   'highest cristalline']],
 ['pfas-free',
  ['ptfe-free',
   'no pfas',
   'forever chemical free',
   'ptfe free',
   'pfas free',
   'pfas-free',
   'pfas alternatives',
   'pfas-alternatives']],
 ['plasticizer', ['plasticizer', 'plasticiser', 'plasti']],
 ['platable', ['platable', 'plateable', 'plating grade']],
 ['reduced gloss', ['reduced gloss', 'low gloss', 'redugloss']],
 ['release agent', ['release agent', 'release']],
 ['specialty appearance',
  ['specialty appearance',
   'lx',
   'metalx',
   'appearance',
   'aesthetical',
   'good aesthetics',
   'visual fx']],
 ['static dissipative',
  ['static dissipative',
   'esd',
   'esd modified',
   'elecdiss',
   'elec diss',
   'electdiss',
   'elect diss',
   'electrostatic dissipation',
   'electrostatic dissipative']],
 ['sustainable',
  ['sustainable',
   'green',
   'circular economy',
   'eco',
   'environmentally friendly',
   'sustainability']],
 ['thermal shock resistant',
  ['thermal shock resistant',
   'thermal shock resistance',
   'thermal shock',
   'shock resistance',
   'shock resistant',
   'anti thermal shock',
   'anti-thermal shock']],
 ['u.v. stabilized',
  ['u.v. stabilized',
   'u.v. stabilised',
   'u.v. stabilized or stable to weather',
   'u.v. stabilised or stable to weather',
   'uv resistant',
   'uv',
   'anti uv',
   'anti-uv',
   'uv-stabilized',
   'exposure to outdoor sunlight',
   'uv resistent',
   'uvres',
   'uv stabilise',
   'uv',
   'uv stability',
   'weather resistance',
   'weather resistant',
   'uv resistance',
   'weatherable',
   'stable to weather',
   'weather',
   'solar resistance']],
 ['ultrasonic weldable', ['ultrasonic weldable']]]

In [40]:
for i in feature_list:
    if len(i) != 2:
        print('False')
    if not isinstance(i[0], str) and not isinstance(i[1], list):
        print('False')

    # break

In [41]:
synonym_df_new = read_data_from_snowflake_table(cur_dev,"""select * from SYNONYM""")
synonym_df_new.columns = [x.upper() if x.islower() else x for x in synonym_df_new.columns]

#### start of chemical resistance and medical certifications synonyms

In [42]:
chem_res = spt[spt['temp_c2'].str.lower().str.startswith('chemical')]

subset = chem_res[['property_id', 'property_name', 'value_assmnt_si', 'non_std_test_cond_desc']].drop_duplicates(subset='property_name').reset_index(drop=True)

df_sorted = (
    subset.assign(
        _PROPERTY_NAME_lower=subset['property_name'].str.lower(),
        _VALUE_ASSMNT_SI_lower=subset['value_assmnt_si'].str.lower()
    )
    .sort_values(['_PROPERTY_NAME_lower', '_VALUE_ASSMNT_SI_lower'])
    .drop(columns=['_PROPERTY_NAME_lower', '_VALUE_ASSMNT_SI_lower'])
    .reset_index(drop=True)
)

df_sorted.head()

,property_id,property_name,value_assmnt_si,non_std_test_cond_desc
0,340,"Acids, Formic Acid","Resistant, Long-term Exposure",23°C
1,384,"Acids, Hydrochloric Acid","Resistant, Long-term Exposure",23°C
2,252,"Acids, Strong (pH 0-3)","Resistant, Long-term Exposure",23°C
3,473,"Acids, Sulfuric Acid",No Data Available,23°C
4,261,"Acids, Weak","Limited Resistance, Short-term Exposure",23°C

In [50]:
chem_syn = synonym_df_new[synonym_df_new['TYPE'].str.lower().str.startswith('chemical')]
chem_syn

,TYPE,DEFINED_NAME,SYNONYMS
65,CHEMICAL RESISTANCE,"Acids, Formic Acid",Methanoic acid; HCOOH; Concentrated formic aci...
66,CHEMICAL RESISTANCE,"Acids, Hydrochloric Acid",Muriatic acid; HCl; Concentrated HCl (37%); Di...
67,CHEMICAL RESISTANCE,"Acids, Strong (pH 0-3)",Mineral acids; inorganic acids; Nitric acid (H...
68,CHEMICAL RESISTANCE,"Acids, Sulfuric Acid",Oil of vitriol; H₂SO₄; Concentrated sulfuric a...
69,CHEMICAL RESISTANCE,"Acids, Weak",Organic acids; mild acids; Acetic acid (vinega...
70,CHEMICAL RESISTANCE,"Alcohols, Long-Chain Alcohols (> C4)",Higher alcohols; fatty alcohols; Hexanol; Octa...
71,CHEMICAL RESISTANCE,"Alcohols, Short-Chain Alcohols (C1-C4)",Lower alcohols; light alcohols; Methanol; Etha...
72,CHEMICAL RESISTANCE,"Alkalies/Bases, Strong (pH 11-14)",Caustic solutions; alkali hydroxides; Sodium h...
73,CHEMICAL RESISTANCE,"Alkalies/Bases, Weak",Mild alkaline solutions; Sodium bicarbonate (N...
74,CHEMICAL RESISTANCE,"Coolants, Aqueous Glycol-Based Coolant",Antifreeze solutions; radiator fluids; Ethylen...
75,CHEMICAL RESISTANCE,"Coolants, Non-Aqueous Coolant",Dielectric coolants; synthetic heat transfer f...
76,CHEMICAL RESISTANCE,"Fuels, Diesel Fuel",Gas oil; automotive diesel; Ultra-low sulfur d...
77,CHEMICAL RESISTANCE,"Fuels, Gasoline Fuel",Petrol; motor fuel; E10/E15 ethanol-blended ga...
78,CHEMICAL RESISTANCE,"Hydrocarbons, Aromatic Hydrocarbon",Aromatics; BTX hydrocarbons; Benzene; Toluene;...
79,CHEMICAL RESISTANCE,"Oils & Greases, Greases",Lubricating grease; bearing grease; Lithium gr...
80,CHEMICAL RESISTANCE,"Oils & Greases, Mineral Oil",Petroleum oil; paraffinic oil; Transformer oil...
81,CHEMICAL RESISTANCE,"Oils & Greases, Natural Oil",Bio-oils; vegetable oils; Soybean oil; Palm oi...
82,CHEMICAL RESISTANCE,"Oils & Greases, Synthetic Oil",Engineered lubricants; artificial oils; Polyal...
83,CHEMICAL RESISTANCE,"Oxidizers, Oxidizing Agents",Oxidants; bleaching agents; Hydrogen peroxide ...
84,CHEMICAL RESISTANCE,"Oxidizers, Ozone",O₃; activated oxygen; Ozone gas in water treat...
85,CHEMICAL RESISTANCE,"Phenolic Compounds, Phenols",Hydroxybenzenes; phenolic derivatives; Phenol ...
86,CHEMICAL RESISTANCE,"Solvents, Halogenated Solvent",Chlorinated solvents; fluorinated solvents; Tr...
87,CHEMICAL RESISTANCE,"Solvents, Non-Halogenated Solvent",hydrocarbon solvents; Acetone; MEK (methyl eth...
88,CHEMICAL RESISTANCE,"Water & Aqueous Solutions, Salt Solutions",Brines; saline solutions; Sodium chloride brin...
89,CHEMICAL RESISTANCE,"Water & Aqueous Solutions, Water",Deionized water; purified water; DI water; RO ...

In [53]:
valid_format = json.load(open("../dependencies/chemical_resistance.json"))
valid_format

{'acids': [{'sub_category': 'formic acid',
   'resistance_level': 'limited resistance, short-term exposure',
   'synonyms': ['methanoic acid',
    'hcooh',
    'concentrated formic acid >85%',
    'dilute formic acid solutions',
    'industrial-grade formic acid',
    'formate acid',
    'hydrogen carboxylic acid',
    'formylic acid',
    'formic acid solution',
    'ant sting acid',
    'red ant acid'],
   'temperature': '23'},
  {'sub_category': 'hydrochloric acid',
   'resistance_level': 'limited resistance, short-term exposure',
   'synonyms': ['muriatic acid',
    'hcl',
    'concentrated hcl (37%)',
    'dilute hydrochloric acid (5â€“20%)',
    'hydrogen chloride solution',
    'aqueous hydrogen chloride',
    'chlorohydric acid',
    'hydronium chloride solution',
    'hydrochloride acid',
    'hydrogen chloride aqueous'],
   'temperature': '23'},
  {'sub_category': 'strong (ph 0-3)',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['mineral acids',
    'inorganic acids',
    'nitric acid (hnoâ‚ƒ)',
    'phosphoric acid (hâ‚ƒpoâ‚„)',
    'perchloric acid (hcloâ‚„)',
    'hydrofluoric acid (hf)',
    'highly acidic media',
    'low-ph acids',
    'aggressive acid systems',
    'strong proton donors',
    'acidic process fluids',
    'high-acidity solutions',
    'corrosive acid mixtures',
    'low-ph chemicals',
    'industrial strong acids',
    'severe acidic environments',
    'chromic acid solution (h2cro4)',
    'hydrobromic acid (hbr)',
    'hydriodic acid (hi)',
    'chloric acid (hclo3)'],
   'temperature': '23'},
  {'sub_category': 'sulfuric acid',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['oil of vitriol',
    'hâ‚‚soâ‚„',
    'concentrated sulfuric acid (95â€“98%)',
    'battery acid (~30â€“40%)',
    'oleum (fuming sulfuric acid)',
    'dihydrogen sulfate',
    'hydrogen sulfate acid',
    'sulphuric acid',
    'sulfuric acid solution',
    'diprotic sulfur acid',
    'strong sulfate acid',
    'electrolyte acid (20-30%)',
    'spirit of sulfur',
    'diluted sulfuric acid'],
   'temperature': '23'},
  {'sub_category': 'weak',
   'resistance_level': 'limited resistance, short-term exposure',
   'synonyms': ['organic acids',
    'mild acids',
    'acetic acid (vinegar)',
    'citric acid',
    'lactic acid',
    'carbonic acid',
    'mild acidic media',
    'low-strength acids',
    'buffered acid systems',
    'partially dissociated acids',
    'moderately acidic solutions',
    'weak proton donors',
    'mild organic acid blends',
    'dilute acidic media',
    'ph 3-6',
    'boric acid (h3bo3)',
    'benzoic acid (c6h5cooh)',
    'carboxybenzene (c6h5cooh)',
    'phenylformic acid (c6h5cooh)',
    'benzene carboxylic acid (c6h5cooh)',
    'hypochlorous acid (hclo)'],
   'temperature': '23'}],
 'alcohols': [{'sub_category': 'long-chain alcohols (> c4)',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['higher alcohols',
    'fatty alcohols',
    'hexanol',
    'octanol',
    'lauryl alcohol (dodecanol)',
    'stearyl alcohol',
    'extended-chain alcohols',
    'c5+ alcohols',
    'alkanols above c4',
    'hydrophobic alcohols',
    'fatty alkanols',
    'long-carbon alcohols',
    'industrial fatty alcohol blends',
    'high-molecular-weight alcohols',
    'wax alcohols',
    'aliphatic alcohol',
    'cyclohexane (c6h12)',
    'cetyl alcohol, c16',
    'stearyl alcohol, c18',
    'lauryl alcohol',
    'lignoceryl alcohol, c24 (wood creosote)',
    'ceryl alcohol, c26 (beeswax alcohol)'],
   'temperature': '23'},
  {'sub_category': 'short-chain alcohols (c1-c4)',
   'resistance_level': 'limited resistance, short-term exposure',
   'synonyms': ['lower alcohols',
    'light alcohols',
    'methanol',
    'ethanol (denatured alcohol, bioethanol)',
    'isopropanol (ipa)',
    'butanol',
    'c1-c4 alkanols',
    'volatile alcohols',
    'light alkanols',
    'monohydric short alcohols',
    'low-molecular-weight alcohols',
    'short-carbon alcohols',
    'primary solvent alcohols',
    'industrial light alcohols',
    'simple alcohols',
    'ethylene glycol (eg, meg)',
    'propylene glycol',
    'butanediol (butane-1,2-diol)',
    'isopropyl alcohol (ipa)',
    'propan-2-ol (ipa)',
    'n-propanol'],
   'temperature': '23'}],
 'alkalies/bases': [{'sub_category': 'strong (ph 11-14)',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['caustic solutions',
    'alkali hydroxides',
    'sodium hydroxide (naoh, caustic soda)',
    'potassium hydroxide (koh)',
    'calcium hydroxide (lime slurry) (ca(oh)2)',
    'highly alkaline media',
    'caustic alkalis',
    'strong alkaline solutions',
    'high-ph bases',
    'alkaline process chemicals',
    'corrosive bases',
    'strong proton acceptors',
    'industrial alkali systems',
    'severe alkaline environments',
    'concentrated bases',
    'barium hydroxide (ba(oh2))',
    'tetramethylammonium hydroxide (tmah)',
    'tetrabutylammonium hydroxide (tbah)',
    'tetraethyl ammonium hydroxide (teah)',
    '25% ethylenediamine (eda) solution'],
   'temperature': '23'},
  {'sub_category': 'weak',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['mild alkaline solutions',
    'sodium bicarbonate (nahco3)',
    'sodium carbonate (soda ash)',
    'dilute ammonia solutions',
    'mild alkaline media',
    'low-strength bases',
    'moderately alkaline solutions',
    'weak proton acceptors',
    'buffered alkaline systems',
    'low-causticity bases',
    'mild alkalis',
    'partially ionized bases',
    'dilute alkaline chemicals',
    'soft alkaline solutions',
    'ammonium hydroxide',
    'ammonia water',
    'ammonia aqueous',
    'sodium acetate',
    'aniline (aminobenzene)',
    'dimethylamine (dma)',
    'trimethylamine',
    'diethylamine',
    'triethylamine (tea, et3n, net3)',
    'ethylenediamine (eda)',
    'ammonium hydroxide solution',
    'amines (organic bases)'],
   'temperature': '23'}],
 'coolants': [{'sub_category': 'aqueous glycol-based coolant',
   'resistance_level': 'limited resistance, short-term exposure',
   'synonyms': ['antifreeze solutions',
    'radiator fluids',
    'ethylene glycol + water mixtures',
    'propylene glycol coolants',
    'corrosion-inhibited glycol fluids',
    'water-glycol coolants',
    'glycol-water coolants',
    'liquid cooling mixtures',
    'heat-transfer antifreeze',
    'engine coolant mixtures',
    'aqueous thermal fluids',
    'waterborne coolants',
    'glycol heat-transfer media',
    'cooling loop fluids',
    'water-diluted antifreeze',
    'coolant glysantin g48, 1:1 in water',
    'g12e 050 z3',
    'valeo service g13',
    'g30',
    'g48',
    'g12',
    'g12 evo',
    'byd antifreeze coolant',
    'lopal e8107',
    'nissan long-life antifreeze l255n-c',
    'lopal coolant series (e31, e32, e701, e380, c05, c08, c31)',
    'coolion se01',
    'total coolelf series',
    'mobil delvacâ„¢ extended life coolant/antifreeze series'],
   'temperature': '23'},
  {'sub_category': 'non-aqueous coolant',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['dielectric coolants',
    'synthetic heat transfer fluids',
    'silicone oils',
    'fluorinated fluids (e.g., 3m fluorinert)',
    'mineral oil-based coolants',
    'water-free coolants',
    'anhydrous coolants',
    'non-water thermal fluids',
    'dry cooling media',
    'waterless heat-transfer fluids',
    'electrical cooling fluids',
    'anhydrous thermal media',
    'closed-loop synthetic coolants',
    'nonpolar coolants'],
   'temperature': '23'}],
 'fuels': [{'sub_category': 'diesel fuel',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['gas oil',
    'automotive diesel',
    'ultra-low sulfur diesel (ulsd)',
    'biodiesel (fame blends like b20)',
    'marine diesel',
    'compression-ignition fuel',
    'diesel oil',
    'middle-distillate fuel',
    'road diesel',
    'diesel blendstock',
    'distillate diesel fuel',
    'no. 2 diesel',
    'compression engine fuel',
    'automotive gasoil',
    'diesel hydrocarbon fuel',
    'no. 1 diesel',
    'bs vi diesel',
    'no. 0 diesel (china)',
    'no. -10 diesel (china)',
    'diesel fuel (pref. iso 1817 liquid f)',
    'diesel en 590',
    'iso 1817 liquid f (iso-octane/toluene = 60/40)',
    'iso 1817 liquid h (c12-c18/tetralin = 80/20)',
    'mobil synergy diesel efficient series',
    'mobil diesel efficient series'],
   'temperature': '23'},
  {'sub_category': 'gasoline fuel',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['petrol',
    'motor fuel',
    'e10/e15 ethanol-blended gasoline',
    'reformulated gasoline',
    'aromatic-rich gasoline blends',
    'spark-ignition fuel',
    'motor gasoline',
    'petrol fuel',
    'gasoline blendstock',
    'automotive gasoline',
    'gasoline hydrocarbons',
    'fuel-grade gasoline',
    'road gasoline',
    'gasoline blend',
    'standard fuel without alcohol (pref. iso 1817 liquid c)',
    'standard fuel without alcohol (pref. iso 1817 liquid c)',
    'iso 1817 liquid 1 - e5',
    'iso 1817 liquid 2 - m15e4',
    'iso 1817 liquid 3 - m3e7',
    'iso 1817 liquid 4 - m15',
    'iso 1817 fuel g - e15',
    'iso 1817 fuel h - e15',
    'iso 1817 fuel i - m15',
    'iso 1817 fuel k - m85',
    'iso 1817 liquid a - 100% iso-octane',
    'iso 1817 liquid b - iso-octane/toluene = 70/30',
    'iso 1817 liquid c - iso-octane/toluene = 50/50',
    'iso 1817 liquid d - iso-octane/toluene = 50/50',
    'iso 1817 liquid e - iso-octane/toluene = 60/40',
    'iso 1817 liquid g - 100% toluene',
    'mobil synergy series',
    'mobil synergy supreme+ series'],
   'temperature': '23'}],
 'hydrocarbons': [{'sub_category': 'aromatic hydrocarbon',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['aromatics',
    'btx hydrocarbons',
    'benzene',
    'toluene',
    'xylene (o-, m-, p-xylene)',
    'styrene',
    'arene compounds',
    'arene solvents',
    'monocyclic aromatics',
    'aromatic organics',
    'aromatic solvent blends',
    'ring-containing hydrocarbons',
    'benzenoid hydrocarbons',
    'aromatic vocs',
    'arene chemicals',
    'aromatic fractions',
    'polycyclic aromatic hydrocarbons',
    'naphthalene',
    'anthracene',
    'phenanthrene',
    'ethylbenzene',
    'biphenyl',
    'cumene'],
   'temperature': '23'}],
 'oils & greases': [{'sub_category': 'greases',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['lubricating grease',
    'bearing grease',
    'lithium grease',
    'calcium sulfonate grease',
    'ptfe grease',
    'silicone grease',
    'semi-solid lubricants',
    'lubricant greases',
    'industrial grease compounds',
    'thickened lubricants',
    'mechanical greases',
    'lubricating pastes',
    'tribological greases',
    'multi-purpose greases',
    'semi-fluid lubricants',
    'lubricant compounds',
    'oil no. 1 (irm 901)',
    'oil no. 2 (irm 902)',
    'oil no. 3 (irm 903)',
    'lopal e51',
    'lopal extra (k15, k8, k10, k5)',
    'lopal mp-k2',
    'lopal xhp-k6',
    'total quartz 9000 series',
    'total quartz 5000 series',
    'total quartz ineo xtra',
    'total ceran series',
    'total altis series',
    'total axa series',
    'total bio series',
    'total copal series',
    'total multis series',
    'total nevastane series',
    'total nateria series',
    'mobil 1 series',
    'mobil super series',
    'mobil super moto series',
    'mobil delvac modern grease series',
    'mobil delvac 1 series'],
   'temperature': '23'},
  {'sub_category': 'mineral oil',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['petroleum oil',
    'paraffinic oil',
    'transformer oil',
    'hydraulic oil (petroleum-based)',
    'white mineral oil',
    'petroleum-derived oil',
    'mineral lubricating oil',
    'hydrocarbon oil',
    'refined petroleum oil',
    'base mineral oil',
    'paraffinic mineral lubricant',
    'petroleum lubricant',
    'petroleum base stock',
    'technical mineral oil',
    'sae 10w40 multigrade motor oil',
    'sae 80/90 hypoid-gear oil',
    'insulating oil',
    'motor oil os206 304 ref.eng.oil, isp',
    'automatic hypoid-gear oil shell donax tx',
    'hydraulic oil pentosin chf 202',
    'total isovoltine series',
    'mobil dte 25',
    'mobil dte 26',
    'mobil dte 27',
    'shell tellus zinc free s3 vx',
    'shell tellus zinc free s3 mx',
    'shell tellus s2 vx',
    'shell tellus s2 mx',
    'shell tellus s2 va',
    'shell tellus s2 ma'],
   'temperature': '23'},
  {'sub_category': 'natural oil',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['bio-oils',
    'vegetable oils',
    'soybean oil',
    'palm oil',
    'castor oil',
    'linseed oil',
    'renewable oils',
    'plant-derived oils',
    'biogenic oils',
    'naturally sourced oils',
    'agricultural oils',
    'triglyceride oils',
    'renewable lubricants',
    'seed oils',
    'naturally occurring oils',
    'bio-based oils',
    'olive oil',
    'coconut oil',
    'peanut oil',
    'sesame oil',
    'tung oil'],
   'temperature': '23'},
  {'sub_category': 'synthetic oil',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['engineered lubricants',
    'artificial oils',
    'polyalphaolefin (pao)',
    'ester-based oils',
    'pag (polyalkylene glycol) oils',
    'silicone oils',
    'man-made lubricants',
    'chemically synthesized oils',
    'synthetic lubricants',
    'formulated base oils',
    'laboratory-produced oils',
    'high-performance lubricants',
    'artificial lubricants',
    'synthetic fluid oils',
    'designer lubricants',
    'engineered oil fluids',
    'phosphate ester',
    'fire-resistant fluid',
    'fluorinated oil',
    'perfluoropolyethers (pfpe)',
    'atf oil',
    'automatic transmission fluid',
    'brake oil',
    'lopal e26',
    'lopal e27',
    'lopal e16',
    'lopal e29',
    'lopal 1 series',
    'lopal atf 9600',
    'lopal atf 9800',
    'lopal atf 6400',
    'lopal atf 10x',
    'lopal e61 (brake oil)',
    'total fluidmatic series',
    'total transmission series',
    'total hbf 3 (dot 3)',
    'total hbf 4 (dot 4)',
    'total hbf 5.1',
    'mobil delvac 1 transmission series',
    'mobil delvac 1 series'],
   'temperature': '23'}],
 'oxidizers': [{'sub_category': 'oxidizing agents',
   'resistance_level': 'no data available',
   'synonyms': ['oxidants',
    'bleaching agents',
    'hydrogen peroxide (hâ‚‚oâ‚‚)',
    'sodium hypochlorite (bleach) (naclo)',
    'potassium permanganate (kmno4)',
    'chlorine gas',
    'oxidizing chemicals',
    'oxidative reagents',
    'electron-accepting agents',
    'oxidation promoters',
    'strong oxidizers',
    'industrial oxidants',
    'reactive oxidizing media',
    'oxidative chemicals',
    'oxidation agents',
    'chemical oxidizers',
    'potassium dichromate (k2cr2o7)',
    'red potassium chromate (k2cr2o7)',
    'sodium peroxide (na2o2)',
    'manganese dioxide (mno2)'],
   'temperature': '23'},
  {'sub_category': 'ozone',
   'resistance_level': 'limited resistance, short-term exposure',
   'synonyms': ['oâ‚ƒ',
    'activated oxygen',
    'ozone gas in water treatment',
    'ozonated air streams',
    'trioxygen',
    'reactive oxygen species o3',
    'ozone oxidant',
    'atmospheric ozone',
    'ozone-enriched gas',
    'triatomic oxygen',
    'o3 gas',
    'ozone stream'],
   'temperature': '23'}],
 'phenolic compounds': [{'sub_category': 'phenols',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['hydroxybenzenes',
    'phenolic derivatives',
    'phenol (carbolic acid)',
    'bisphenol a (bpa)',
    'cresols',
    'resorcinol',
    'phenolic compounds',
    'phenolic chemicals',
    'aromatic hydroxyl compounds',
    'phenol derivatives',
    'hydroxy aromatic compounds',
    'phenolic substances',
    'phenolic organics',
    'phenol-class compounds',
    'aryl alcohol derivatives',
    'phenolic materials',
    'phenol solution',
    'p-diphenol',
    'hydroquinone',
    'pyrocatechol',
    'o-diphenol',
    'm-diphenol',
    'catechol',
    'naphthol (naphthalen-1-ol)',
    'Î±-naphthol (1-naphthol)',
    'Î²-naphthol (2-naphthol)'],
   'temperature': '23'}],
 'solvents': [{'sub_category': 'halogenated solvent',
   'resistance_level': 'limited resistance, short-term exposure',
   'synonyms': ['chlorinated solvents',
    'fluorinated solvents',
    'trichloroethylene (tce)',
    'perchloroethylene (pce)',
    'methylene chloride',
    'chloroform (chcl3)',
    'halogen-containing solvents',
    'organohalogen solvents',
    'halogenated organic solvents',
    'chloro-solvents',
    'halo-solvents',
    'halocarbon solvents',
    'halogen-bearing solvents',
    'industrial halogenated fluids',
    'halogen-substituted solvents',
    'dense organic solvents',
    'chlorinated hydrocarbons',
    'tetrachloromethane (ccl4, ctc)',
    'carbon tetrachloride (ccl4, ctc)',
    'chlorobenzene (c6h5cl)',
    '1,2-dichlorobenzene (c6h4cl2)',
    'freon',
    'cfc-12',
    'tribromomethane (chbr3)',
    'bromoform (chbr3)',
    'tetrabromoethane'],
   'temperature': '23'},
  {'sub_category': 'non-halogenated solvent',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['hydrocarbon solvents',
    'acetone',
    'mek (methyl ethyl ketone)',
    'ethyl acetate',
    'toluene',
    'hexane',
    'halogen-free solvents',
    'non-halogen solvents',
    'ketone solvents',
    'ester solvents',
    'nonchlorinated solvents',
    'diethyl ether (etyhyl ether)',
    'ethanol (ethyl alcohol)',
    'isopropyl alcohol (ipa)',
    'propan-2-ol (ipa)',
    'cyclohexane',
    'xylene (o-, m-, p-xylene)',
    'thf (tetrahydrofuran)',
    'iso-octane'],
   'temperature': '23'}],
 'water & aqueous solutions': [{'sub_category': 'salt solutions',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['brines',
    'saline solutions',
    'sodium chloride brine',
    'calcium chloride solution',
    'seawater',
    'potassium chloride solutions',
    'electrolyte solutions',
    'ionic salt mixtures',
    'aqueous salt media',
    'dissolved salt systems',
    'saltwater solutions',
    'saline media',
    'inorganic salt solutions',
    'conductive aqueous solutions',
    'brine media',
    'salt-containing liquids',
    'zinc chloride solution',
    'sodium carbonate solution'],
   'temperature': '23'},
  {'sub_category': 'water',
   'resistance_level': 'resistant, long-term exposure',
   'synonyms': ['deionized water',
    'purified water',
    'di water',
    'ro water',
    'distilled water',
    'process water',
    'cooling water',
    'h2o',
    'aqua',
    'universal solvent',
    'neutral water',
    'fresh water',
    'aqueous medium',
    'water phase',
    'utility water',
    'clean water',
    'potable water'],
   'temperature': '23'}]}

In [56]:
valid_format_nested = [
    [
        category,
        [
            list(item.values()) if isinstance(item, dict) else item
            for item in entries
        ]
    ]
    for category, entries in valid_format.items()
]

valid_format_nested

[['acids',
  [['formic acid',
    'limited resistance, short-term exposure',
    ['methanoic acid',
     'hcooh',
     'concentrated formic acid >85%',
     'dilute formic acid solutions',
     'industrial-grade formic acid',
     'formate acid',
     'hydrogen carboxylic acid',
     'formylic acid',
     'formic acid solution',
     'ant sting acid',
     'red ant acid'],
    '23'],
   ['hydrochloric acid',
    'limited resistance, short-term exposure',
    ['muriatic acid',
     'hcl',
     'concentrated hcl (37%)',
     'dilute hydrochloric acid (5â€“20%)',
     'hydrogen chloride solution',
     'aqueous hydrogen chloride',
     'chlorohydric acid',
     'hydronium chloride solution',
     'hydrochloride acid',
     'hydrogen chloride aqueous'],
    '23'],
   ['strong (ph 0-3)',
    'resistant, long-term exposure',
    ['mineral acids',
     'inorganic acids',
     'nitric acid (hnoâ‚ƒ)',
     'phosphoric acid (hâ‚ƒpoâ‚„)',
     'perchloric acid (hcloâ‚„)',
     'hydrofluoric acid (hf)',
     'highly acidic media',
     'low-ph acids',
     'aggressive acid systems',
     'strong proton donors',
     'acidic process fluids',
     'high-acidity solutions',
     'corrosive acid mixtures',
     'low-ph chemicals',
     'industrial strong acids',
     'severe acidic environments',
     'chromic acid solution (h2cro4)',
     'hydrobromic acid (hbr)',
     'hydriodic acid (hi)',
     'chloric acid (hclo3)'],
    '23'],
   ['sulfuric acid',
    'resistant, long-term exposure',
    ['oil of vitriol',
     'hâ‚‚soâ‚„',
     'concentrated sulfuric acid (95â€“98%)',
     'battery acid (~30â€“40%)',
     'oleum (fuming sulfuric acid)',
     'dihydrogen sulfate',
     'hydrogen sulfate acid',
     'sulphuric acid',
     'sulfuric acid solution',
     'diprotic sulfur acid',
     'strong sulfate acid',
     'electrolyte acid (20-30%)',
     'spirit of sulfur',
     'diluted sulfuric acid'],
    '23'],
   ['weak',
    'limited resistance, short-term exposure',
    ['organic acids',
     'mild acids',
     'acetic acid (vinegar)',
     'citric acid',
     'lactic acid',
     'carbonic acid',
     'mild acidic media',
     'low-strength acids',
     'buffered acid systems',
     'partially dissociated acids',
     'moderately acidic solutions',
     'weak proton donors',
     'mild organic acid blends',
     'dilute acidic media',
     'ph 3-6',
     'boric acid (h3bo3)',
     'benzoic acid (c6h5cooh)',
     'carboxybenzene (c6h5cooh)',
     'phenylformic acid (c6h5cooh)',
     'benzene carboxylic acid (c6h5cooh)',
     'hypochlorous acid (hclo)'],
    '23']]],
 ['alcohols',
  [['long-chain alcohols (> c4)',
    'resistant, long-term exposure',
    ['higher alcohols',
     'fatty alcohols',
     'hexanol',
     'octanol',
     'lauryl alcohol (dodecanol)',
     'stearyl alcohol',
     'extended-chain alcohols',
     'c5+ alcohols',
     'alkanols above c4',
     'hydrophobic alcohols',
     'fatty alkanols',
     'long-carbon alcohols',
     'industrial fatty alcohol blends',
     'high-molecular-weight alcohols',
     'wax alcohols',
     'aliphatic alcohol',
     'cyclohexane (c6h12)',
     'cetyl alcohol, c16',
     'stearyl alcohol, c18',
     'lauryl alcohol',
     'lignoceryl alcohol, c24 (wood creosote)',
     'ceryl alcohol, c26 (beeswax alcohol)'],
    '23'],
   ['short-chain alcohols (c1-c4)',
    'limited resistance, short-term exposure',
    ['lower alcohols',
     'light alcohols',
     'methanol',
     'ethanol (denatured alcohol, bioethanol)',
     'isopropanol (ipa)',
     'butanol',
     'c1-c4 alkanols',
     'volatile alcohols',
     'light alkanols',
     'monohydric short alcohols',
     'low-molecular-weight alcohols',
     'short-carbon alcohols',
     'primary solvent alcohols',
     'industrial light alcohols',
     'simple alcohols',
     'ethylene glycol (eg, meg)',
     'propylene glycol',
     'butanediol (butane-1,2-diol)',
     'isopropyl alcohol (ipa)',
     'propan-2-ol (ipa)',
     'n-propanol'],
    '23']]],
 ['alkalies/bases',
  [['strong (ph 11-14)',
    'resistant, long-term exposure',
    ['caustic solutions',
     'alkali hydroxides',
     'sodium hydroxide (naoh, caustic soda)',
     'potassium hydroxide (koh)',
     'calcium hydroxide (lime slurry) (ca(oh)2)',
     'highly alkaline media',
     'caustic alkalis',
     'strong alkaline solutions',
     'high-ph bases',
     'alkaline process chemicals',
     'corrosive bases',
     'strong proton acceptors',
     'industrial alkali systems',
     'severe alkaline environments',
     'concentrated bases',
     'barium hydroxide (ba(oh2))',
     'tetramethylammonium hydroxide (tmah)',
     'tetrabutylammonium hydroxide (tbah)',
     'tetraethyl ammonium hydroxide (teah)',
     '25% ethylenediamine (eda) solution'],
    '23'],
   ['weak',
    'resistant, long-term exposure',
    ['mild alkaline solutions',
     'sodium bicarbonate (nahco3)',
     'sodium carbonate (soda ash)',
     'dilute ammonia solutions',
     'mild alkaline media',
     'low-strength bases',
     'moderately alkaline solutions',
     'weak proton acceptors',
     'buffered alkaline systems',
     'low-causticity bases',
     'mild alkalis',
     'partially ionized bases',
     'dilute alkaline chemicals',
     'soft alkaline solutions',
     'ammonium hydroxide',
     'ammonia water',
     'ammonia aqueous',
     'sodium acetate',
     'aniline (aminobenzene)',
     'dimethylamine (dma)',
     'trimethylamine',
     'diethylamine',
     'triethylamine (tea, et3n, net3)',
     'ethylenediamine (eda)',
     'ammonium hydroxide solution',
     'amines (organic bases)'],
    '23']]],
 ['coolants',
  [['aqueous glycol-based coolant',
    'limited resistance, short-term exposure',
    ['antifreeze solutions',
     'radiator fluids',
     'ethylene glycol + water mixtures',
     'propylene glycol coolants',
     'corrosion-inhibited glycol fluids',
     'water-glycol coolants',
     'glycol-water coolants',
     'liquid cooling mixtures',
     'heat-transfer antifreeze',
     'engine coolant mixtures',
     'aqueous thermal fluids',
     'waterborne coolants',
     'glycol heat-transfer media',
     'cooling loop fluids',
     'water-diluted antifreeze',
     'coolant glysantin g48, 1:1 in water',
     'g12e 050 z3',
     'valeo service g13',
     'g30',
     'g48',
     'g12',
     'g12 evo',
     'byd antifreeze coolant',
     'lopal e8107',
     'nissan long-life antifreeze l255n-c',
     'lopal coolant series (e31, e32, e701, e380, c05, c08, c31)',
     'coolion se01',
     'total coolelf series',
     'mobil delvacâ„¢ extended life coolant/antifreeze series'],
    '23'],
   ['non-aqueous coolant',
    'resistant, long-term exposure',
    ['dielectric coolants',
     'synthetic heat transfer fluids',
     'silicone oils',
     'fluorinated fluids (e.g., 3m fluorinert)',
     'mineral oil-based coolants',
     'water-free coolants',
     'anhydrous coolants',
     'non-water thermal fluids',
     'dry cooling media',
     'waterless heat-transfer fluids',
     'electrical cooling fluids',
     'anhydrous thermal media',
     'closed-loop synthetic coolants',
     'nonpolar coolants'],
    '23']]],
 ['fuels',
  [['diesel fuel',
    'resistant, long-term exposure',
    ['gas oil',
     'automotive diesel',
     'ultra-low sulfur diesel (ulsd)',
     'biodiesel (fame blends like b20)',
     'marine diesel',
     'compression-ignition fuel',
     'diesel oil',
     'middle-distillate fuel',
     'road diesel',
     'diesel blendstock',
     'distillate diesel fuel',
     'no. 2 diesel',
     'compression engine fuel',
     'automotive gasoil',
     'diesel hydrocarbon fuel',
     'no. 1 diesel',
     'bs vi diesel',
     'no. 0 diesel (china)',
     'no. -10 diesel (china)',
     'diesel fuel (pref. iso 1817 liquid f)',
     'diesel en 590',
     'iso 1817 liquid f (iso-octane/toluene = 60/40)',
     'iso 1817 liquid h (c12-c18/tetralin = 80/20)',
     'mobil synergy diesel efficient series',
     'mobil diesel efficient series'],
    '23'],
   ['gasoline fuel',
    'resistant, long-term exposure',
    ['petrol',
     'motor fuel',
     'e10/e15 ethanol-blended gasoline',
     'reformulated gasoline',
     'aromatic-rich gasoline blends',
     'spark-ignition fuel',
     'motor gasoline',
     'petrol fuel',
     'gasoline blendstock',
     'automotive gasoline',
     'gasoline hydrocarbons',
     'fuel-grade gasoline',
     'road gasoline',
     'gasoline blend',
     'standard fuel without alcohol (pref. iso 1817 liquid c)',
     'standard fuel without alcohol (pref. iso 1817 liquid c)',
     'iso 1817 liquid 1 - e5',
     'iso 1817 liquid 2 - m15e4',
     'iso 1817 liquid 3 - m3e7',
     'iso 1817 liquid 4 - m15',
     'iso 1817 fuel g - e15',
     'iso 1817 fuel h - e15',
     'iso 1817 fuel i - m15',
     'iso 1817 fuel k - m85',
     'iso 1817 liquid a - 100% iso-octane',
     'iso 1817 liquid b - iso-octane/toluene = 70/30',
     'iso 1817 liquid c - iso-octane/toluene = 50/50',
     'iso 1817 liquid d - iso-octane/toluene = 50/50',
     'iso 1817 liquid e - iso-octane/toluene = 60/40',
     'iso 1817 liquid g - 100% toluene',
     'mobil synergy series',
     'mobil synergy supreme+ series'],
    '23']]],
 ['hydrocarbons',
  [['aromatic hydrocarbon',
    'resistant, long-term exposure',
    ['aromatics',
     'btx hydrocarbons',
     'benzene',
     'toluene',
     'xylene (o-, m-, p-xylene)',
     'styrene',
     'arene compounds',
     'arene solvents',
     'monocyclic aromatics',
     'aromatic organics',
     'aromatic solvent blends',
     'ring-containing hydrocarbons',
     'benzenoid hydrocarbons',
     'aromatic vocs',
     'arene chemicals',
     'aromatic fractions',
     'polycyclic aromatic hydrocarbons',
     'naphthalene',
     'anthracene',
     'phenanthrene',
     'ethylbenzene',
     'biphenyl',
     'cumene'],
    '23']]],
 ['oils & greases',
  [['greases',
    'resistant, long-term exposure',
    ['lubricating grease',
     'bearing grease',
     'lithium grease',
     'calcium sulfonate grease',
     'ptfe grease',
     'silicone grease',
     'semi-solid lubricants',
     'lubricant greases',
     'industrial grease compounds',
     'thickened lubricants',
     'mechanical greases',
     'lubricating pastes',
     'tribological greases',
     'multi-purpose greases',
     'semi-fluid lubricants',
     'lubricant compounds',
     'oil no. 1 (irm 901)',
     'oil no. 2 (irm 902)',
     'oil no. 3 (irm 903)',
     'lopal e51',
     'lopal extra (k15, k8, k10, k5)',
     'lopal mp-k2',
     'lopal xhp-k6',
     'total quartz 9000 series',
     'total quartz 5000 series',
     'total quartz ineo xtra',
     'total ceran series',
     'total altis series',
     'total axa series',
     'total bio series',
     'total copal series',
     'total multis series',
     'total nevastane series',
     'total nateria series',
     'mobil 1 series',
     'mobil super series',
     'mobil super moto series',
     'mobil delvac modern grease series',
     'mobil delvac 1 series'],
    '23'],
   ['mineral oil',
    'resistant, long-term exposure',
    ['petroleum oil',
     'paraffinic oil',
     'transformer oil',
     'hydraulic oil (petroleum-based)',
     'white mineral oil',
     'petroleum-derived oil',
     'mineral lubricating oil',
     'hydrocarbon oil',
     'refined petroleum oil',
     'base mineral oil',
     'paraffinic mineral lubricant',
     'petroleum lubricant',
     'petroleum base stock',
     'technical mineral oil',
     'sae 10w40 multigrade motor oil',
     'sae 80/90 hypoid-gear oil',
     'insulating oil',
     'motor oil os206 304 ref.eng.oil, isp',
     'automatic hypoid-gear oil shell donax tx',
     'hydraulic oil pentosin chf 202',
     'total isovoltine series',
     'mobil dte 25',
     'mobil dte 26',
     'mobil dte 27',
     'shell tellus zinc free s3 vx',
     'shell tellus zinc free s3 mx',
     'shell tellus s2 vx',
     'shell tellus s2 mx',
     'shell tellus s2 va',
     'shell tellus s2 ma'],
    '23'],
   ['natural oil',
    'resistant, long-term exposure',
    ['bio-oils',
     'vegetable oils',
     'soybean oil',
     'palm oil',
     'castor oil',
     'linseed oil',
     'renewable oils',
     'plant-derived oils',
     'biogenic oils',
     'naturally sourced oils',
     'agricultural oils',
     'triglyceride oils',
     'renewable lubricants',
     'seed oils',
     'naturally occurring oils',
     'bio-based oils',
     'olive oil',
     'coconut oil',
     'peanut oil',
     'sesame oil',
     'tung oil'],
    '23'],
   ['synthetic oil',
    'resistant, long-term exposure',
    ['engineered lubricants',
     'artificial oils',
     'polyalphaolefin (pao)',
     'ester-based oils',
     'pag (polyalkylene glycol) oils',
     'silicone oils',
     'man-made lubricants',
     'chemically synthesized oils',
     'synthetic lubricants',
     'formulated base oils',
     'laboratory-produced oils',
     'high-performance lubricants',
     'artificial lubricants',
     'synthetic fluid oils',
     'designer lubricants',
     'engineered oil fluids',
     'phosphate ester',
     'fire-resistant fluid',
     'fluorinated oil',
     'perfluoropolyethers (pfpe)',
     'atf oil',
     'automatic transmission fluid',
     'brake oil',
     'lopal e26',
     'lopal e27',
     'lopal e16',
     'lopal e29',
     'lopal 1 series',
     'lopal atf 9600',
     'lopal atf 9800',
     'lopal atf 6400',
     'lopal atf 10x',
     'lopal e61 (brake oil)',
     'total fluidmatic series',
     'total transmission series',
     'total hbf 3 (dot 3)',
     'total hbf 4 (dot 4)',
     'total hbf 5.1',
     'mobil delvac 1 transmission series',
     'mobil delvac 1 series'],
    '23']]],
 ['oxidizers',
  [['oxidizing agents',
    'no data available',
    ['oxidants',
     'bleaching agents',
     'hydrogen peroxide (hâ‚‚oâ‚‚)',
     'sodium hypochlorite (bleach) (naclo)',
     'potassium permanganate (kmno4)',
     'chlorine gas',
     'oxidizing chemicals',
     'oxidative reagents',
     'electron-accepting agents',
     'oxidation promoters',
     'strong oxidizers',
     'industrial oxidants',
     'reactive oxidizing media',
     'oxidative chemicals',
     'oxidation agents',
     'chemical oxidizers',
     'potassium dichromate (k2cr2o7)',
     'red potassium chromate (k2cr2o7)',
     'sodium peroxide (na2o2)',
     'manganese dioxide (mno2)'],
    '23'],
   ['ozone',
    'limited resistance, short-term exposure',
    ['oâ‚ƒ',
     'activated oxygen',
     'ozone gas in water treatment',
     'ozonated air streams',
     'trioxygen',
     'reactive oxygen species o3',
     'ozone oxidant',
     'atmospheric ozone',
     'ozone-enriched gas',
     'triatomic oxygen',
     'o3 gas',
     'ozone stream'],
    '23']]],
 ['phenolic compounds',
  [['phenols',
    'resistant, long-term exposure',
    ['hydroxybenzenes',
     'phenolic derivatives',
     'phenol (carbolic acid)',
     'bisphenol a (bpa)',
     'cresols',
     'resorcinol',
     'phenolic compounds',
     'phenolic chemicals',
     'aromatic hydroxyl compounds',
     'phenol derivatives',
     'hydroxy aromatic compounds',
     'phenolic substances',
     'phenolic organics',
     'phenol-class compounds',
     'aryl alcohol derivatives',
     'phenolic materials',
     'phenol solution',
     'p-diphenol',
     'hydroquinone',
     'pyrocatechol',
     'o-diphenol',
     'm-diphenol',
     'catechol',
     'naphthol (naphthalen-1-ol)',
     'Î±-naphthol (1-naphthol)',
     'Î²-naphthol (2-naphthol)'],
    '23']]],
 ['solvents',
  [['halogenated solvent',
    'limited resistance, short-term exposure',
    ['chlorinated solvents',
     'fluorinated solvents',
     'trichloroethylene (tce)',
     'perchloroethylene (pce)',
     'methylene chloride',
     'chloroform (chcl3)',
     'halogen-containing solvents',
     'organohalogen solvents',
     'halogenated organic solvents',
     'chloro-solvents',
     'halo-solvents',
     'halocarbon solvents',
     'halogen-bearing solvents',
     'industrial halogenated fluids',
     'halogen-substituted solvents',
     'dense organic solvents',
     'chlorinated hydrocarbons',
     'tetrachloromethane (ccl4, ctc)',
     'carbon tetrachloride (ccl4, ctc)',
     'chlorobenzene (c6h5cl)',
     '1,2-dichlorobenzene (c6h4cl2)',
     'freon',
     'cfc-12',
     'tribromomethane (chbr3)',
     'bromoform (chbr3)',
     'tetrabromoethane'],
    '23'],
   ['non-halogenated solvent',
    'resistant, long-term exposure',
    ['hydrocarbon solvents',
     'acetone',
     'mek (methyl ethyl ketone)',
     'ethyl acetate',
     'toluene',
     'hexane',
     'halogen-free solvents',
     'non-halogen solvents',
     'ketone solvents',
     'ester solvents',
     'nonchlorinated solvents',
     'diethyl ether (etyhyl ether)',
     'ethanol (ethyl alcohol)',
     'isopropyl alcohol (ipa)',
     'propan-2-ol (ipa)',
     'cyclohexane',
     'xylene (o-, m-, p-xylene)',
     'thf (tetrahydrofuran)',
     'iso-octane'],
    '23']]],
 ['water & aqueous solutions',
  [['salt solutions',
    'resistant, long-term exposure',
    ['brines',
     'saline solutions',
     'sodium chloride brine',
     'calcium chloride solution',
     'seawater',
     'potassium chloride solutions',
     'electrolyte solutions',
     'ionic salt mixtures',
     'aqueous salt media',
     'dissolved salt systems',
     'saltwater solutions',
     'saline media',
     'inorganic salt solutions',
     'conductive aqueous solutions',
     'brine media',
     'salt-containing liquids',
     'zinc chloride solution',
     'sodium carbonate solution'],
    '23'],
   ['water',
    'resistant, long-term exposure',
    ['deionized water',
     'purified water',
     'di water',
     'ro water',
     'distilled water',
     'process water',
     'cooling water',
     'h2o',
     'aqua',
     'universal solvent',
     'neutral water',
     'fresh water',
     'aqueous medium',
     'water phase',
     'utility water',
     'clean water',
     'potable water'],
    '23']]]]

In [57]:
# Medical certification synonyms
med_cert_synonyms = synonym_df_new[synonym_df_new['TYPE'] == 'MEDICAL CERT']
med_cert_synonyms
# synonym_df['TYPE'].unique()

,TYPE,DEFINED_NAME,SYNONYMS
151,MEDICAL CERT,CYTOTOXICITY,cytotoxicity; cell toxicity; cellular toxicity...
152,MEDICAL CERT,DERMAL_IRRITATION,dermal irritation; skin irritation; skin irrit...
153,MEDICAL CERT,GENETOXICITY,genotoxicity; genetic toxicity; mutagenicity; ...
154,MEDICAL CERT,HEMOLYSIS,hemolysis; haemolysis; blood compatibility; re...
155,MEDICAL CERT,MUSCLE_IMPLANTATION,muscle implantation; intramuscular implantatio...
156,MEDICAL CERT,PHYSICOCHEMICAL_COMPLIANCE,physicochemical compliance; physical chemical ...
157,MEDICAL CERT,PYROGENICITY,pyrogenicity; pyrogen test; pyrogen testing; f...
158,MEDICAL CERT,SYSTEMIC_TOXICITY,systemic toxicity; acute systemic toxicity; ge...

In [58]:
med_cert_synonyms['SYNONYMS'] = med_cert_synonyms['SYNONYMS'].apply(lambda x : x.replace(',', ';'))
med_cert_synonyms

C:\Users\DSCMS5\AppData\Local\Temp\21\ipykernel_8852\856581444.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  med_cert_synonyms['SYNONYMS'] = med_cert_synonyms['SYNONYMS'].apply(lambda x : x.replace(',', ';'))

,TYPE,DEFINED_NAME,SYNONYMS
151,MEDICAL CERT,CYTOTOXICITY,cytotoxicity; cell toxicity; cellular toxicity...
152,MEDICAL CERT,DERMAL_IRRITATION,dermal irritation; skin irritation; skin irrit...
153,MEDICAL CERT,GENETOXICITY,genotoxicity; genetic toxicity; mutagenicity; ...
154,MEDICAL CERT,HEMOLYSIS,hemolysis; haemolysis; blood compatibility; re...
155,MEDICAL CERT,MUSCLE_IMPLANTATION,muscle implantation; intramuscular implantatio...
156,MEDICAL CERT,PHYSICOCHEMICAL_COMPLIANCE,physicochemical compliance; physical chemical ...
157,MEDICAL CERT,PYROGENICITY,pyrogenicity; pyrogen test; pyrogen testing; f...
158,MEDICAL CERT,SYSTEMIC_TOXICITY,systemic toxicity; acute systemic toxicity; ge...

In [59]:
med_certs = []
for idx, row in med_cert_synonyms.iterrows():
    cert = []
    defined_name = row['DEFINED_NAME'].lower()
    synonyms = row['SYNONYMS']
    if ";" in synonyms:
        synonym_list = [s.strip() for s in synonyms.split(';') if s.strip()]
    elif "," in synonyms:
        synonym_list = [s.strip() for s in synonyms.split(',') if s.strip()]
    else:
        synonym_list = [synonyms.strip()] if synonyms.strip() else []
    
    # med_cert_synonyms.at[idx, 'SYNONYM_LIST'] = synonym_list
    cert.append(defined_name)
    cert.append(synonym_list)
    med_certs.append(cert)
med_certs

[['cytotoxicity',
  ['cytotoxicity',
   'cell toxicity',
   'cellular toxicity',
   'cell viability',
   'cell viability testing',
   'in vitro cytotoxicity',
   'cell compatibility',
   'biocompatibility cytotoxicity',
   'toxicity to cells',
   'cell culture toxicity',
   'cyto',
   'cytotox']],
 ['dermal_irritation',
  ['dermal irritation',
   'skin irritation',
   'skin irritation testing',
   'cutaneous irritation',
   'skin compatibility',
   'skin contact safety',
   'irritation potential',
   'dermatological irritation',
   'primary skin irritation',
   'skin reactivity',
   'intracutaneous reactivity',
   'intracutaneous',
   'intracutaenous test']],
 ['genetoxicity',
  ['genotoxicity',
   'genetic toxicity',
   'mutagenicity',
   'mutagenic potential',
   'dna damage assessment',
   'genetic damage testing',
   'ames test compliance',
   'chromosomal aberration testing',
   'genotoxic safety',
   'gene tox',
   'geno',
   'ames']],
 ['hemolysis',
  ['hemolysis',
   'haemolysis',
   'blood compatibility',
   'red blood cell compatibility',
   'rbc compatibility',
   'red blood cell lysis',
   'blood cell damage testing',
   'hemocompatibility']],
 ['muscle_implantation',
  ['muscle implantation',
   'intramuscular implantation',
   'implantation test',
   'implant compatibility',
   'local tissue response',
   'tissue implantation',
   'muscle tissue compatibility',
   'implantation biocompatibility',
   'in vivo implantation',
   'implantation']],
 ['physicochemical_compliance',
  ['physicochemical compliance',
   'physical chemical compliance',
   'physical and chemical characterization',
   'physicochemical characterization',
   'material characterization',
   'chemical characterization',
   'physical properties compliance',
   'chemical properties compliance',
   'material property compliance',
   'composition compliance',
   'material specification compliance',
   'physchem',
   'USP 661.1',
   'USP 661']],
 ['pyrogenicity',
  ['pyrogenicity',
   'pyrogen test',
   'pyrogen testing',
   'fever response',
   'fever-inducing substances',
   'endotoxin-related fever response',
   'bacterial endotoxin testing',
   'lal testing',
   'endotoxin compliance',
   'non-pyrogenic']],
 ['systemic_toxicity',
  ['systemic toxicity',
   'acute systemic toxicity',
   'general toxicity',
   'whole-body toxicity',
   'body-wide toxicity',
   'systemic safety',
   'systemic toxicological evaluation',
   'toxicity after exposure',
   'in vivo toxicity']]]

In [60]:
# Remove grades names from the color code grade names if it does not start with any of the actual brands in list
all_brands_list = []  
for key, values in brand_synonyms.items():  
    all_brands_list.append(key)  
    all_brands_list.extend(values)  


ce_grades_with_color_code = [grade for grade in ce_grades_with_color_code if any(grade.startswith(item) for item in all_brands_list)]
ce_grades_with_color_code = [i for i in ce_grades_with_color_code if "olultramid" not in i]
ce_grades_with_color_code = [i for i in ce_grades_with_color_code if "basf" not in i]
len(ce_grades_with_color_code)

404973

In [61]:
# ce_grades_with_color_code_new = [grade for grade in ce_grades_with_color_code if any(grade.startswith(item) for item in all_brands_list)]
# items_to_be_removed_from_unique_list = set(ce_grades_with_color_code) - set(ce_grades_with_color_code_new)
# normalized_unique_values_current["GRADE"] = list(set(normalized_unique_values_current["GRADE"])-items_to_be_removed_from_unique_list)

In [62]:
len(normalized_unique_values_current["GRADE"])

21202

In [63]:
# {'ecomid': 'ecomid', 'frianyl': 'frianyl', 'gur': 'gur', 'rynite': 'rynite'}

In [64]:
def normalize_query(s):
    # Remove special characters and convert to lower case
    return re.sub(r'\W+', '', s).lower()

In [65]:
unique_values.keys()

dict_keys(['BRAND', 'POLYMER', 'PROPERTY', 'FEATURE', 'FILLER', 'GRADE', 'CERTIFICATION', 'COMPETITOR_GRADE', 'APPLICATION', 'MODIFIER', 'UNIT', 'FILLER_PERCENTAGE', 'GRADE_WITHOUT_BRAND', 'COMPETITOR_GRADE_TRANSFORMED', 'COMP_GRADE_WITHOUT_BRAND', 'COMP_GRADE_TRANSFORMED_WITHOUT_BRAND'])

In [66]:
competitor_grades = read_data_from_snowflake_table(cur,"select * from competitor_data")
competitor_grades = list(set(competitor_grades['competitor_grade']))

In [67]:
normalized_values = {}
normalized_values['columnstoIgnore'] = []
normalized_values['GRADE'] = list(set([normalize_string(x) for x in unique_values['GRADE']] + [normalize_string(x) for x in unique_values['GRADE_WITHOUT_BRAND']] + [normalize_string(x) for x in new_grade_names]))
normalized_values['COMPETITOR_GRADE'] = list(set([normalize_string(x) for x in unique_values['COMPETITOR_GRADE']] + \
    [normalize_string(x) for x in unique_values['COMP_GRADE_WITHOUT_BRAND']] + \
    [normalize_string(x) for x in unique_values['COMPETITOR_GRADE_TRANSFORMED']] + \
    [normalize_string(x) for x in unique_values['COMP_GRADE_TRANSFORMED_WITHOUT_BRAND']]+\
    [normalize_string(x) for x in competitor_grades]))
    
normalized_values['columnstoIgnore'].extend([normalize_string(x) for x in unique_values['BRAND']])
normalized_values['columnstoIgnore'].extend([normalize_string(x) for x in unique_values['POLYMER']])
normalized_values['columnstoIgnore'].extend([normalize_string(x) for x in unique_values['FILLER']])
normalized_values['columnstoIgnore'].extend(outOfScopeData['brands'])
normalized_values['columnstoIgnore'] = list(set(normalized_values['columnstoIgnore']))
normalized_values['columnsforSubstringCheck'] = list(set([normalize_string(x) for x in unique_values['FEATURE']] + [normalize_string(x) for x in unique_values['PROPERTY']] + [normalize_string(x) for x in all_features]))

In [68]:
normalized_values['BRAND'] = [normalize_string(x) for x in unique_values['BRAND']]

In [69]:
for brand in spt_brands:
    if brand not in normalized_values['BRAND']:
        print(brand)
        normalized_values['BRAND'].append(brand)

normalized_values['BRAND'].sort()

minlon
talcoprene
neolast
pipelon
at
vitaldose
clarifoil

In [70]:
normalized_values['BRAND']

['at',
 'ateva',
 'celanex',
 'celanyl',
 'celcon',
 'celstran',
 'celstranlft',
 'clarifoil',
 'cn',
 'cnl',
 'coolpoly',
 'cp',
 'crastin',
 'cs',
 'cslft',
 'cx',
 'eco',
 'ecomid',
 'elvamide',
 'ff',
 'fo',
 'forflex',
 'fortron',
 'fp',
 'frianyl',
 'geolast',
 'geolast',
 'gur',
 'hf',
 'hostaform',
 'hytrel',
 'impet',
 'kep',
 'kepital',
 'laprene',
 'lcpa',
 'lftcelstran',
 'litepol',
 'lp',
 'minlon',
 'neolast',
 'omnipro',
 'omnitech',
 'pb',
 'pibiter',
 'pipelon',
 'po',
 'polifor',
 'rynite',
 'santoprene',
 'sofprene',
 'sofpur',
 'stp',
 'talcoprene',
 'tc',
 'tecnoprene',
 'thermx',
 'tp',
 'tx',
 'va',
 'vamac',
 'vandar',
 've',
 'vectra',
 'vitaldose',
 'ze',
 'zenite',
 'zytel',
 'zytelhtn',
 'zytellcpa',
 'zytelplsxt']

In [71]:
normalized_values.keys()

dict_keys(['columnstoIgnore', 'GRADE', 'COMPETITOR_GRADE', 'columnsforSubstringCheck', 'BRAND'])

In [72]:
region_cert_values_to_ignore_from_grade = ["china","asia","europe","america","ford","lfrt","impact72","industrial","bmw","ktw"]

In [73]:
applications_values_to_ignore_from_grade = ["pv", "hv", "pcb", "ccm", "mcb", "w&c", "tb", "usb", "sim", "lv", "labs", "smt", "fpc", "vcm", "rf", "ofc", "pc", "ff", "ac", "btb", "cmc", "bev", "wtb", "cpu", "ltcc", "vr", "htls", "eps", "rar", "lcd", "cgm", "iot"]

In [74]:
normalized_values['GRADE'] = list(set(normalized_values['GRADE'] + outOfScopeDataGrades + normalized_unique_values_current['GRADE']))
normalized_values['COMPETITOR_GRADE'] = list(set(normalized_values['COMPETITOR_GRADE'] + normalized_unique_values_current['COMPETITOR_GRADE']))
normalized_values['columnstoIgnore'] = list(set(normalized_values['columnstoIgnore'] + normalized_unique_values_current['columnstoIgnore'] + region_cert_values_to_ignore_from_grade + applications_values_to_ignore_from_grade))
normalized_values['columnsforSubstringCheck'] = list(set(normalized_values['columnsforSubstringCheck'] + normalized_unique_values_current['columnsforSubstringCheck']))

In [75]:
normalized_values['GRADE'] = list(set(normalized_values['GRADE'] + [normalize_string(i) for i in ce_grades])) # + ce_grades_with_color_code
normalized_values['COMPETITOR_GRADE'] = [i for i in normalized_values['COMPETITOR_GRADE'] if len(i)>2]

In [76]:
normalized_values['FEATURE'] = feature_list

In [77]:
normalized_values['MEDICAL_CERT'] = med_certs
normalized_values['CHEMICAL_RESISTANCE'] = valid_format_nested

In [ ]:
# validating the list of ce grades present (since for bug 203909 minlon grades were not populated in unique value list)
# df_ce_grades_normalized = pd.DataFrame(normalized_values['GRADE'])
# df_ce_grades_normalized.to_csv('celanese_grades__normalized_list.csv', index=False, header=False)

In [78]:
len(normalized_values['GRADE']), len(normalized_values['COMPETITOR_GRADE'])

(21822, 56885)

In [79]:
len(normalized_values['FEATURE'])

41

In [80]:
normalized_values["GRADE"] = [grade for grade in normalized_values["GRADE"] if any(grade.startswith(item) for item in all_brands_list)]
normalized_values["GRADE"] = [grade for grade in normalized_values["GRADE"] if "basf" not in grade]
len(normalized_values['GRADE'])

21225

In [ ]:
# #all_brands_list
# import csv
# # validating the list of ce grades present (since for bug 203909 minlon grades were not populated in unique value list)
# csv_filename = "brand_synonyms.csv"
# fieldnames = ["Brands", "Brand_Synonyms"]
# with open(csv_filename, mode='w', newline='') as file:
#     writer = csv.DictWriter(file, fieldnames=fieldnames)
#     writer.writeheader()
#     for brand, synonyms in brand_synonyms.items():
#         for synonym in synonyms:
#                 writer.writerow({"Brands": brand, "Brand_Synonyms": synonym})
# # df_brand_synonyms = pd.DataFrame(brand_synonyms)
# # df_brand_synonyms.to_csv('brand_synonyms.csv', index=False, header=False)

In [81]:
[i for i in ce_grades_with_color_code if "basf" in i]

[]

In [82]:
[i for i in normalized_values["GRADE"] if "nw02" in i]

[]

In [83]:
[i for i in ce_grades_with_color_code if "olultra" in i]

['colultramarineviolet525kgbag',
 'colultramarineblep3825kgbag',
 'colultramarinebl08',
 'colultramarinebl08hollidaypigments']

## Certification

In [84]:
import requests

def get_dev_unique_values():
    url = "https://apim-gst-dev.azure-api.net/func-uiproperties-d-ussc-01/func-ui-properties?userType=internal"
    
    headers = {
        "Content-Type": "application/json",
        "Ocp-Apim-Subscription-Key": "c2404e96bf0b471daf7f2b1091094fa1"
              }
    try:
        res = requests.post(url, headers=headers)
        res = res.json()
    except Exception as e:  
        print(e)
        
    return res

uniue_values = get_dev_unique_values()
print(uniue_values.keys())
uniue_values['results'].keys()

dict_keys(['success', 'status', 'results'])

dict_keys(['Property', 'Chemical_Resistance', 'Feature', 'UL', 'Certification', 'Auto_Approval', 'Brand', 'Polymer', 'Filler', 'Market', 'Industry_Group'])

In [85]:
all_auto_certs = []
for cert_data in uniue_values['results']['Auto_Approval']:
    for cert in cert_data['CERTIFICATIONS']:
        if cert_data['OEM_Name'].lower() == 'santoprene':
            print('found non oem')
        else:
            all_auto_certs.append((cert['CERTIFICATION'].lower(), cert_data['OEM_Name'].lower()))

all_auto_certs = list(set(all_auto_certs))
all_auto_certs

[('tl 522 81-b tpc-et', 'vw group'),
 ('gmw16733p-pbt-gf15', 'general motors (gm)'),
 ('ms-db-570 / cpn-3502', 'stellantis-chrysler'),
 ('ms.500017 / pa66.2810f.6i.hs', 'stellantis'),
 ('ms-db-21 / cpn-3608', 'stellantis-chrysler'),
 ('tl 524 40-a pa6-gf50', 'vw group'),
 ('dbl5405.05 pa66 gf35', 'mercedes-benz'),
 ('vw 50136', 'vw group'),
 ('tl 520 62 pa-gf35', 'vw group'),
 ('gmw17457p-tpc-et-type 2', 'general motors (gm)'),
 ('b62 0300 / 61/u4/225e/217m/c2b/c4', 'stellantis'),
 ('ms.50017 / cpn-4367', 'stellantis-chrysler'),
 ('b62 0300 / 61/u4/223e/211m/c2b/c4', 'stellantis'),
 ('dbl5403 pbt-i-gf15', 'mercedes-benz'),
 ('b62 0300 / 61/210m+/215e+/c1b', 'stellantis'),
 ('n-004-0047', 'nio'),
 ('tst n 055 54.37', 'continental'),
 ('ms.50095 / cpn-1986', 'stellantis-chrysler'),
 ('vw 50133 pa66-7-a', 'vw group'),
 ('ms.50103 / cpn-5292', 'stellantis-chrysler'),
 ('wsa-m4d768-a', 'ford'),
 ('jf03-26', 'faw group'),
 ('ms.50017 / cpn-2224', 'stellantis-chrysler'),
 ('gmw15890p-pp-gf60', 'general motors (gm)'),
 ('dbl5409.24 pa66 gf30', 'mercedes-benz'),
 ('ms.50017 / cpn-5187', 'stellantis-chrysler'),
 ('wsk-m4d840-a1', 'ford'),
 ('gmw17481p-pa66-gf25', 'general motors (gm)'),
 ('dbl5406.10 pa66 gf30', 'mercedes-benz'),
 ('b62 0300 / 61/222e/219m/h115', 'stellantis'),
 ('gmw15813p-tpv-(epdm+pp)-type 5', 'general motors (gm)'),
 ('ub22e', 'nissan'),
 ('wss-m2d378-b1', 'ford'),
 ('b62 0300 / 61/223e-219m/c4', 'stellantis'),
 ('ms220-05 type k', 'hyundai'),
 ('tl 526 83 tpc-et', 'vw group'),
 ('wrs-m4d625-a3', 'ford'),
 ('tst n 055 54.44', 'continental'),
 ('ms.50095 / cpn-2794', 'stellantis-chrysler'),
 ('ms216-05 type b', 'hyundai'),
 ('ms941-03 type f-3', 'hyundai'),
 ('gmw17702p-pa6-gf15', 'general motors (gm)'),
 ('vw 50133 pa66-3-a', 'vw group'),
 ('ms237-09 type d-2', 'hyundai'),
 ('ms-db-448 / cpn-3831', 'stellantis-chrysler'),
 ('ms.50095 / cpn-4240', 'stellantis-chrysler'),
 ('n28 bn09-gf034', 'bosch'),
 ('tl 520 62 pa66-gf30', 'vw group'),
 ('b62 0300 / 61/221e/215m/c1b', 'stellantis'),
 ('gs93016-pa66-gf25', 'bmw'),
 ('gmw17263p-pa66-gf35', 'general motors (gm)'),
 ('gmw15813p-tpv-(epdm+pp)-type 6', 'general motors (gm)'),
 ('b62 0300 / 61/u4/w1/221e/218m/h113', 'stellantis'),
 ('vw 50127 pa66-ig13', 'vw group'),
 ('gmw15812p-tpv(epdm+pp)-type 8m', 'general motors (gm)'),
 ('ms.50042 / cpn-5438', 'stellantis-chrysler'),
 ('gmw15816p-tpv-epdm+pp-class-i-type-5', 'general motors (gm)'),
 ('gmw17327p-tpc-et-type 2', 'general motors (gm)'),
 ('n28 bn02-gf034', 'bosch'),
 ('q/jly j7110166b-2017', 'geely'),
 ('ms.50095 / cpn-1586', 'stellantis-chrysler'),
 ('n28 bn22-x010', 'bosch'),
 ('q-bjev 01.59', 'baic'),
 ('ms220-05 type r', 'hyundai'),
 ('ms.50017 / cpn-3433', 'stellantis-chrysler'),
 ('ms.50103 / cpn-2403', 'stellantis-chrysler'),
 ('ms.50103 / cpn-2810', 'stellantis-chrysler'),
 ('wsd-m2d441-a', 'ford'),
 ('q/lia5310057', 'li auto'),
 ('ub20a, no spec, special part approval, see your ce account manager.',
  'nissan'),
 ('tst n 055 72.01-000', 'continental'),
 ('n28 bn05-ox036', 'bosch'),
 ('ms.50095 / cpn-3379', 'stellantis-chrysler'),
 ('gs97014', 'bmw'),
 ('dbl5420.00 pbt-gf30', 'mercedes-benz'),
 ('ms.50095 / cpn-5090', 'stellantis-chrysler'),
 ('vw 50133 pa66-4-a', 'vw group'),
 ('ms211-46 type c-2', 'hyundai'),
 ('vw 44045', 'vw group'),
 ('gmw17479p-tpc-et-type 2', 'general motors (gm)'),
 ('gs93016-pa66-gf15', 'bmw'),
 ('b62 0300 / 61/219m-/221e/11/h114/h412 + s620001 (3000h/190°)',
  'stellantis'),
 ('b62 / 0300 61/221e/215m/c1b', 'stellantis'),
 ('b62 0300 / 61/212m/215e-/h0412(freecordsc)/11', 'stellantis'),
 ('n28 bn08-gf018', 'bosch'),
 ('sn 57908-11', 'continental'),
 ('gmw17604p-pa612', 'general motors (gm)'),
 ('dbl5410.10 pa6 gf15', 'mercedes-benz'),
 ('tst n 055 54.17', 'continental'),
 ('gmw15890p-pp-gf40', 'general motors (gm)'),
 ('gmw3038p-pa66-gf35h', 'general motors (gm)'),
 ('gmw17968p-pom-gf25', 'general motors (gm)'),
 ('dbl5403 pa66 gf20', 'mercedes-benz'),
 ('ms.50017 / pa6.gf15.4500f.6i', 'stellantis'),
 ('ms.50017 / cpn-2055', 'stellantis-chrysler'),
 ('ms.50017 / cpn-2012', 'stellantis-chrysler'),
 ('wss-m98p14-a7', 'ford'),
 ('ms.50042 / pp-h.gf30.5500f.8i.hs', 'stellantis'),
 ('ms941-03 type a-11', 'hyundai'),
 ('vw 50127 pa66-10', 'vw group'),
 ('ub25c, no spec, special part approval, see your ce account manager.',
  'nissan'),
 ('vw 50137', 'vw group'),
 ('ms220-05 p', 'hyundai'),
 ('ms.50042 / pp-h.gb20-gf10.2700f.6i', 'stellantis'),
 ('ms.50103 / cpn-5175', 'stellantis-chrysler'),
 ('ms.50095 / cpn-3694', 'stellantis-chrysler'),
 ('gmw16356p-ppa-gf15', 'general motors (gm)'),
 ('n28 bn22-o027', 'bosch'),
 ('ms220-05 type m', 'hyundai'),
 ('ms237-12 type c-1', 'hyundai'),
 ('wss-m4d840-a6', 'ford'),
 ('ms.50103 / cpn-3080', 'stellantis-chrysler'),
 ('smtc 5 4000 003', 'saic motor'),
 ('tl 526 41c', 'vw group'),
 ('gmw15812p-tpv(epdm+pp)-type 4e', 'general motors (gm)'),
 ('gmw17482p-pa66-mf40', 'general motors (gm)'),
 ('ms.50017 / cpn-4967', 'stellantis-chrysler'),
 ('ms-db-448 / cpn-4843', 'stellantis-chrysler'),
 ('vw 50127 pa66-igf14', 'vw group'),
 ('gmw15813p-tpv-(epdm+pp)-type 8', 'general motors (gm)'),
 ('wrs-m4d673-b2', 'ford'),
 ('gmw16356p-ppa-gf35', 'general motors (gm)'),
 ('ms220-05 type g', 'hyundai'),
 ('dbl5562.34 tpv', 'mercedes-benz'),
 ('dbl5409.20 pa66', 'mercedes-benz'),
 ('ub22f, no spec, special part approval, see your ce account manager.',
  'renault'),
 ('tl 522 81-d tpc-et', 'vw group'),
 ('ms-db-570 / cpn-3243', 'stellantis-chrysler'),
 ('wsb-m4d680-a', 'ford'),
 ('ms-db-448 / cpn-2313', 'stellantis-chrysler'),
 ('ms-db-448 / cpn-4176', 'stellantis-chrysler'),
 ('ub09g, no spec, special part approval, see your ce account manager.',
  'renault'),
 ('b62 0300 / 61/u4/21e/216m/c2b/c4', 'stellantis'),
 ('n28 bn05-ox089', 'bosch'),
 ('n28 bn22-x005', 'bosch'),
 ('gmw17327p-tpc-et-type 3m1', 'general motors (gm)'),
 ('dbl5408.65 ppa gf35', 'mercedes-benz'),
 ('frm', 'renault'),
 ('ms.50091 / cpn-4178', 'stellantis-chrysler'),
 ('dbl5410.00 pa66 gf15', 'mercedes-benz'),
 ('n28 bn22-o028', 'bosch'),
 ('b62 0300 / 61/219e/217m/c4', 'stellantis'),
 ('n28 bn22-o017', 'bosch'),
 ('gmw17968p-pom-gf10', 'general motors (gm)'),
 ('vw 50133 pa66-8-a', 'vw group'),
 ('n28 bn90-34-009', 'bosch'),
 ('ms.50103 / cpn-4423', 'stellantis-chrysler'),
 ('n28 bn09-gf008', 'bosch'),
 ('ms.50103 / cpn-5342', 'stellantis-chrysler'),
 ('gmw3029p-pa6-gf30h', 'general motors (gm)'),
 ('dbl5410.01 pa66-i', 'mercedes-benz'),
 ('ms.50042 / pp-h.gf30.9400f.9i.hs', 'stellantis'),
 ('ms.50103 / cpn-4076', 'stellantis-chrysler'),
 ('ms.50017 / cpn-4818', 'stellantis-chrysler'),
 ('dbl5404.19 pbt+asa-gf15', 'mercedes-benz'),
 ('ms-db-448 / cpn-3095', 'stellantis-chrysler'),
 ('gmw17327p-tpc-et-type 3m2', 'general motors (gm)'),
 ('b62 0300 / 61/218e/215m/c1/c1b', 'stellantis'),
 ('ms-db-21 / cpn-5167', 'stellantis-chrysler'),
 ('ms.50017 / cpn-3850', 'stellantis-chrysler'),
 ('b62 0300 / 61/u4/ad1/w1/o1/ab1/e2/215m-218e/13/c1b', 'stellantis'),
 ('ms.50103 / cpn-3327', 'stellantis-chrysler'),
 ('vw 50123', 'vw group'),
 ('rms.2013', 'rivian'),
 ('n28 bn09-gf027', 'bosch'),
 ('wss-m4d673-b1', 'ford'),
 ('vw 50133 pa66-1', 'vw group'),
 ('gmw17479p-tpc-et-type 1b', 'general motors (gm)'),
 ('55248_02 emp80', 'stellantis'),
 ('tst n 055 54.23', 'continental'),
 ('tm-1001-12', 'tesla'),
 ('sn 57908-6', 'continental'),
 ('ms.50042 / pp-h-r.gf20.3200f.6i', 'stellantis'),
 ('tl 539 pa66-gf30', 'vw group'),
 ('gmw15890p-pp-gf50 type 50', 'general motors (gm)'),
 ('ms.50017 / cpn-1987', 'stellantis-chrysler'),
 ('gs93016-pbt-gf30', 'bmw'),
 ('ms.50210 / pom-c.2400f.6c.lf', 'stellantis'),
 ('ep03-3', 'nissan'),
 ('n28 bn10-x003', 'bosch'),
 ('dbl5408.25 pa6 gf15', 'mercedes-benz'),
 ('gs93016', 'bmw'),
 ('gmw17599p-pa612-gf35', 'general motors (gm)'),
 ('gmw3038p-pa66-gf15h', 'general motors (gm)'),
 ('gs93016-pbt-gf15', 'bmw'),
 ('ms237-05 type a-1', 'hyundai'),
 ('ms220-05 type h', 'hyundai'),
 ('dbl5408.45 pa66 gf30', 'mercedes-benz'),
 ('b62 0300 / 61/225e/218m/h412(g48)/c1', 'stellantis'),
 ('b62 0300 / 61/208m+/211e+/h708+(grease)', 'stellantis'),
 ('ms.50103 / cpn-3669', 'stellantis-chrysler'),
 ('ms.50017 / pa66-r.1500f.20i.tg', 'stellantis'),
 ('tst n 055 47.01', 'continental'),
 ('ms.50017 / cpn-1756', 'stellantis-chrysler'),
 ('gmw16733p-pbt-gf30', 'general motors (gm)'),
 ('wss-m4d865-b7', 'ford'),
 ('ms941-12 type b', 'hyundai'),
 ('smtc 5 310 015', 'saic motor'),
 ('nio-sm.51.010', 'nio'),
 ('n28 bn14-gf010', 'bosch'),
 ('n28 bn09-gf024', 'bosch'),
 ('wss-m4d666-a2', 'ford'),
 ('gmw16360p-ppa-gf35', 'general motors (gm)'),
 ('gmw16270p-pa66-gf25', 'general motors (gm)'),
 ('gmw15702-110060-pa6', 'general motors (gm)'),
 ('dbl5430', 'mercedes-benz'),
 ('ms.50095 / cpn-5289', 'stellantis-chrysler'),
 ('tl 522 88 pa6-i-md15', 'vw group'),
 ('ms.50017 / cpn-4498', 'stellantis-chrysler'),
 ('ms.50103 / pbt-gf20.6400f.7i', 'stellantis'),
 ('ms-db-448 / cpn-2312', 'stellantis-chrysler'),
 ('dbl5562-30', 'mercedes-benz'),
 ('ms211-36 type a-1', 'hyundai'),
 ('m 3236-a-6', 'man'),
 ('ms.50095 / cpn-2436', 'stellantis-chrysler'),
 ('vw 50134 pa6-7-a', 'vw group'),
 ('wsk-m4d896-a1', 'ford'),
 ('ms220-31 type a1', 'hyundai'),
 ('gmw3038p-pa66-gf30h', 'general motors (gm)'),
 ('dbl5562.50', 'mercedes-benz'),
 ('ms-db-585 / cpn-3887', 'stellantis-chrysler'),
 ('q/jly j7110166c-2024', 'geely'),
 ('ms-ar-100 fgn', 'stellantis-chrysler'),
 ('gmw15816p-tpv-epdm+pp-class-i-type-6', 'general motors (gm)'),
 ('vw 50136-pbt-i-gf15', 'vw group'),
 ('gs93016-pa66-mx40', 'bmw'),
 ('tl 526 34', 'vw group'),
 ('ms.50103 / cpn-3199', 'stellantis-chrysler'),
 ('ms.50103 / cpn-2425', 'stellantis-chrysler'),
 ('tst n 055 72.03-001', 'continental'),
 ('ms.50103 / cpn-5372', 'stellantis-chrysler'),
 ('mcr0000562', 'catl'),
 ('gmw16356p-ppa-gf45', 'general motors (gm)'),
 ('wsb-m4d883-a1', 'ford'),
 ('gmw15813p-tpv-(epdm+pp)-type 2', 'general motors (gm)'),
 ('dbl5408.21 pa6-hi', 'mercedes-benz'),
 ('dbl5405-07-pom-c', 'mercedes-benz'),
 ('b62 0300 / 61/213m/215e+/13/c1b', 'stellantis'),
 ('ms.50017 / cpn-2460', 'stellantis-chrysler'),
 ('gmw17968p-pom-gf20', 'general motors (gm)'),
 ('ms.50103 / cpn-2635', 'stellantis-chrysler'),
 ('dbl5562 aa41 tpv', 'mercedes-benz'),
 ('ms.50103 / cpn-4314', 'stellantis-chrysler'),
 ('ms.50103 / cpn-4189', 'stellantis-chrysler'),
 ('ms.50103 / cpn-2660', 'stellantis-chrysler'),
 ('wss-m4d752-b1', 'ford'),
 ('ms-db-448 / cpn-2760', 'stellantis-chrysler'),
 ('ms.50103 / pbt.2200f.5i', 'stellantis'),
 ('ms220-13 type e-1', 'hyundai'),
 ('dbl5562.50 tpc', 'mercedes-benz'),
 ('ms-db-21 / cpn-5347', 'stellantis-chrysler'),
 ('wsd-m2d382-a1', 'ford'),
 ('gmw16272', 'general motors (gm)'),
 ('wss-m4d929-a3', 'ford'),
 ('ms237-09 type a', 'hyundai'),
 ('ms.50017 / pa66.md40.5000f.3i', 'stellantis'),
 ('b62 0300 / 61/211e/209m/12/c1b', 'stellantis'),
 ('ms.50095 / cpn-5109', 'stellantis-chrysler'),
 ('wss-m98p14-a3', 'ford'),
 ('wss-m4d1063-a2', 'ford'),
 ('ms237-09 type b', 'hyundai'),
 ('gmw15812p-tpv(epdm+pp)-type 4m', 'general motors (gm)'),
 ('ms237-09 type d-1', 'hyundai'),
 ('slclbg2016018', 'dongfeng motor'),
 ('gmw17577p-pa6-t2', 'general motors (gm)'),
 ('gmw15890p-pp-gf20e-class-u', 'general motors (gm)'),
 ('wss-m4d823-b1', 'ford'),
 ('gmw17327p-tpc-et-type 5', 'general motors (gm)'),
 ('vw 50127', 'vw group'),
 ('ms.50017 / cpn-2125', 'stellantis-chrysler'),
 ('n28 bn90-21-005', 'bosch'),
 ('dbl5562.16', 'mercedes-benz'),
 ('b62 0300 / 61/219e/221ms/c1/c4', 'stellantis'),
 ('ms220-05 type j', 'hyundai'),
 ('tl 522 81-c tpc-et', 'vw group'),
 ('q/jly j7110235b-2018(2)', 'geely'),
 ('dbl5562.32', 'mercedes-benz'),
 ('ms.50017 / cpn-2184', 'stellantis-chrysler'),
 ('n28 bn22-x021', 'bosch'),
 ('b62 0300 / 61/31/u4/g1/52/213e/212m/y1/f1/f2/a1/p207m/k3/c1/j6/m1/q2/r1/t07/t131/z3/l208e',
  'stellantis'),
 ('n28 bn07-gf010', 'bosch'),
 ('dbl5408.30 pa6 gf30', 'mercedes-benz'),
 ('gmw16802p-pa66-gf35', 'general motors (gm)'),
 ('ms.50210 / pom-c.2000f.3c.ec', 'stellantis'),
 ('vw 50125 pa6-007', 'vw group'),
 ('tl 101 0', 'vw group'),
 ('gmw15812p-tpv(epdm+pp)-type 10e', 'general motors (gm)'),
 ('tl 526 36b', 'vw group'),
 ('pdtnvc15006 reve', 'valeo'),
 ('n28 bn09-ts027', 'bosch'),
 ('gmw18052p-pom', 'general motors (gm)'),
 ('ms.50017 / cpn-2727', 'stellantis-chrysler'),
 ('wsk-m4d840-a3', 'ford'),
 ('n28 bn22-x013', 'bosch'),
 ('b62 0300 / 61/221e/210m+/c2b', 'stellantis'),
 ('gmw3038p-pa66-gf45h', 'general motors (gm)'),
 ('ms-db-448 / cpn-2956', 'stellantis-chrysler'),
 ('ms.50156 / ppa.gf45-50.14000t.12c.hs', 'stellantis'),
 ('ms-db-448 / cpn-2576', 'stellantis-chrysler'),
 ('ms.90181 / pbt.gf30.9000t.3c.fr', 'stellantis'),
 ('ms211-66 type b', 'hyundai'),
 ('dbl5404', 'mercedes-benz'),
 ('ms211-56 type', 'hyundai'),
 ('ms.50095', 'stellantis'),
 ('ms.50095 / cpn-4931', 'stellantis-chrysler'),
 ('vw 50127 pa66-4', 'vw group'),
 ('vw 50136-pbt-6-a', 'vw group'),
 ('dbl5405-06-pom-c', 'mercedes-benz'),
 ('tst n 055 54.13', 'continental'),
 ('q/sqr s1-111-2012', 'chery'),
 ('gmw22p-pom-c1', 'general motors (gm)'),
 ('gmw3029p-pa6-gf35h', 'general motors (gm)'),
 ('b62 0300 / 61/31/u4/ad1/w1/219e/13/c1', 'stellantis'),
 ('ms211-45 type f', 'hyundai'),
 ('ms.50150 / pa66.gf35.10000t.11c.hs.gr', 'stellantis'),
 ('ms220-13 type d-1', 'hyundai'),
 ('ub27b, no spec, special part approval, see your ce account manager.',
  'renault'),
 ('ms.50017 / cpn-4777', 'stellantis-chrysler'),
 ('ms.50095 / cpn-4570', 'stellantis-chrysler'),
 ('ms-db-448 / cpn-2749', 'stellantis-chrysler'),
 ('wss-m4d1014-a', 'ford'),
 ('vw 50125 pa6-004', 'vw group'),
 ('wsd-m2d378-a4', 'ford'),
 ('gmw15812p-tpv(epdm+pp)-type 9', 'general motors (gm)'),
 ('gmw17769p-pps-t2', 'general motors (gm)'),
 ('ms941-03 type f-5 frv0', 'hyundai'),
 ('ms.50017 / cpn-4786', 'stellantis-chrysler'),
 ('ms220-05 type d', 'hyundai'),
 ('b62 0300 / 61/31/u4/g1/52/y1/f1/f2/a1/p207m/p208e/k3/c1/j6/m1/q2/r1/t07/t131/z3/l208e',
  'stellantis'),
 ('ms-ar-100 dmv2-hf', 'stellantis'),
 ('ms.50095 / pom-c.2900f.5i.le', 'stellantis'),
 ('ms.50095 / cpn-3110', 'stellantis-chrysler'),
 ('tst n 055 58.12', 'continental'),
 ('ms.50017 / cpn-4329', 'stellantis-chrysler'),
 ('wss-m98p13-e', 'ford'),
 ('wss-m2d382-b1', 'ford'),
 ('b62 0300 / h0412', 'stellantis'),
 ('ms.50103 / cpn-4749', 'stellantis-chrysler'),
 ('ms.50017 / cpn-4362', 'stellantis-chrysler'),
 ('smtc 5 310 020', 'saic motor'),
 ('ms.50103 / cpn-3764', 'stellantis-chrysler'),
 ('ub28a, no spec, special part approval, see your ce account manager.',
  'renault'),
 ('n28 bn05-ox049', 'bosch'),
 ('ms.50017 / cpn-2456', 'stellantis-chrysler'),
 ('n28 bn07-gf051', 'bosch'),
 ('ms941-03 type m-1', 'hyundai'),
 ('dbl5408.24 pa6 gf15', 'mercedes-benz'),
 ('ms.50017 / pa66-epdm.1600f.20i.hs', 'stellantis'),
 ('ms.502xx / pom-c.1550f.10c.tg', 'stellantis'),
 ('gmw17802p-pa6-t1', 'general motors (gm)'),
 ('gmw17327p-tpc-et-type 4', 'general motors (gm)'),
 ('ms.50095 / cpn-4270', 'stellantis-chrysler'),
 ('ms.50017 / cpn-4970', 'stellantis-chrysler'),
 ('gmw16272p-pp-gf50', 'general motors (gm)'),
 ('ms-ar-100 egn', 'stellantis-chrysler'),
 ('wsb-m4d840-a4', 'ford'),
 ('q-bjev 01.33', 'baic'),
 ('ms.50042 / pp-c-r.gf30.5000f.10i', 'stellantis'),
 ('dbl5562.34', 'mercedes-benz'),
 ('pom(0xx)-ixx-1', 'nissan'),
 ('b62 0300 / 61/223e/221m/c4', 'stellantis'),
 ('gs93016-pa66-gf35', 'bmw'),
 ('ms-db-448 / cpn-4477', 'stellantis-chrysler'),
 ('m 3236-a-5', 'man'),
 ('ms.50017 / cpn-2565', 'stellantis-chrysler'),
 ('ms.50017 / cpn-1853', 'stellantis-chrysler'),
 ('tl 524 40 pa6-gf30', 'vw group'),
 ('sn 57908-4', 'continental'),
 ('b62 0300 / 61/213m+/215e+/11/h115 + s62 0001 (130°c)', 'stellantis'),
 ('dbl5562.17', 'mercedes-benz'),
 ('ms.50103 / cpn-2621', 'stellantis-chrysler'),
 ('byd-ty-d13f05-0043', 'byd'),
 ('n28 bn34-ox067', 'bosch'),
 ('byd-ty-d13f17-0217', 'byd'),
 ('gmw15890p-pp-gf20e', 'general motors (gm)'),
 ('tst n 055 54.09', 'continental'),
 ('gs93016-pa66-gf50', 'bmw'),
 ('gmw16558p-pa66-t3', 'general motors (gm)'),
 ('frm 18-27-208 /---', 'renault'),
 ('ms.50017 / cpn-2183', 'stellantis-chrysler'),
 ('dbl5562.33', 'mercedes-benz'),
 ('ms.50095 / cpn-1758', 'stellantis-chrysler'),
 ('ms941-03 type n-4', 'hyundai'),
 ('dbl5562.50 tpc-et', 'mercedes-benz'),
 ('ms.50095 / cpn-5291', 'stellantis-chrysler'),
 ('wsk-m4d635-a1', 'ford'),
 ('ms941-03 type a-6', 'hyundai'),
 ('b62 0300 / 61/214m/c4', 'stellantis'),
 ('nio-sm.51.010-c4', 'nio'),
 ('gmw16459p-pbt-gf30w', 'general motors (gm)'),
 ('ms216-03 type b', 'hyundai'),
 ('wss-m9p9-d2', 'ford'),
 ('ms220-24 type c', 'hyundai'),
 ('wss-m4d1063-a1', 'ford'),
 ('ms-db-448 / cpn-2560', 'stellantis-chrysler'),
 ('b62 0300 / 61/223e-218m/c1/c4', 'stellantis'),
 ('tm-1005-40', 'tesla'),
 ('dbl5408.70 ppa gf45', 'mercedes-benz'),
 ('tl 526 22', 'vw group'),
 ('ms941-03 type f-5', 'hyundai'),
 ('dbl5403', 'mercedes-benz'),
 ('ms237-05 type a-2', 'hyundai'),
 ('dbl5403.33 pa66 gf50', 'mercedes-benz'),
 ('ms.50095 / cpn-4097', 'stellantis-chrysler'),
 ('dbl5408.50 pa66', 'mercedes-benz'),
 ('n28 bn07-gf028', 'bosch'),
 ('dbl5416', 'mercedes-benz'),
 ('pa6.gf50.14100f.15i.hs', 'stellantis-chrysler'),
 ('tst n 055 54.10', 'continental'),
 ('ms.50017 / cpn-4691', 'stellantis-chrysler'),
 ('ms.50017 / cpn-2508', 'stellantis-chrysler'),
 ('ms.50017 / pa66.gm40.7200f.30c.hs', 'stellantis'),
 ('gmw17349p-pa66', 'general motors (gm)'),
 ('ms237-12 type c-2', 'hyundai'),
 ('n-008-0002', 'nio'),
 ('tst n 055 54.35', 'continental'),
 ('50572', 'stellantis'),
 ('ms-db-21 / cpn-5149', 'stellantis-chrysler'),
 ('ms.50017 / cpn-5448', 'stellantis-chrysler'),
 ('dbl5410.01 pa6-i', 'mercedes-benz'),
 ('gmw17192p-pa66', 'general motors (gm)'),
 ('pbtp(g)-1nx-30', 'nissan'),
 ('ms-db-448 / cpn-5033', 'stellantis-chrysler'),
 ('n28 bn22-o024', 'bosch'),
 ('b62 0300 / 61/u4/225e-218m/c2b/c4', 'stellantis'),
 ('ms.50017 / cpn-4157r', 'stellantis-chrysler'),
 ('ms-ar-100 bmn', 'stellantis-chrysler'),
 ('ms211-47 type a-2', 'hyundai'),
 ('wss-m4d1038-a1', 'ford'),
 ('wss-m2d379-b1', 'ford'),
 ('ms237-05 type b', 'hyundai'),
 ('mcr0000561', 'catl'),
 ('dbl5562.34 tpu', 'mercedes-benz'),
 ('ms-db-21 / cpn-5109', 'stellantis-chrysler'),
 ('ms-db-448 / cpn-3356', 'stellantis-chrysler'),
 ('ms.50017 / cpn-3811', 'stellantis-chrysler'),
 ('ms-db-21 / pp.lgf30.6500f.21i.hs', 'stellantis'),
 ('n28 bn07-gf019', 'bosch'),
 ('ms.50017 / cpn-5077', 'stellantis-chrysler'),
 ('n28 bn02-gf023', 'bosch'),
 ('ms941-03 type f-3 ah', 'hyundai'),
 ('b62 0300 / 61/31/u4/w1/c1/j7/k3/m5/q3/r1/z3/208e', 'stellantis'),
 ('ms.50103 / cpn-2666', 'stellantis-chrysler'),
 ('gmw17187p-tpc-et-type 2', 'general motors (gm)'),
 ('dbl5562 aa39 tpc', 'mercedes-benz'),
 ('b62 0300 / 61/u4/ad1/w1/223e/13/c1', 'stellantis'),
 ('dbl5562.34 tps', 'mercedes-benz'),
 ('b62 0300 / 61/217e/214m/c4', 'stellantis'),
 ('ms237-12 type e', 'hyundai'),
 ('gmw3038p-pa66-gf30j', 'general motors (gm)'),
 ('dbl5410 pa66-1', 'mercedes-benz'),
 ('ms-db-448 / cpn-2703', 'stellantis-chrysler'),
 ('wsf-m4d737-a', 'ford'),
 ('ms.50017 / cpn-2554', 'stellantis-chrysler'),
 ('ms.50017 / cpn-4018', 'stellantis-chrysler'),
 ('dbl5410.00 pa6 gf15', 'mercedes-benz'),
 ('tl 526 41d', 'vw group'),
 ('ms.90181 / pbt.gf30.7000t.7c.hs.hf.hr', 'stellantis'),
 ('ms220-05 type c', 'hyundai'),
 ('ms.50017 / cpn-2239', 'stellantis-chrysler'),
 ('ms.50103 / cpn-3942', 'stellantis-chrysler'),
 ('smtc 5 310 025', 'saic motor'),
 ('vw 50133 pa66-5-a', 'vw group'),
 ('wsk-m4d635-a4', 'ford'),
 ('vw 50136-pbt-1-a', 'vw group'),
 ('b62 0300 / 61(only 2000/53/ec conformity)/213m/215e-/13/c1b', 'stellantis'),
 ('ub25c, no spec, special part approval, see your ce account manager.',
  'renault'),
 ('gmw17327p-tpc-et-type 6', 'general motors (gm)'),
 ('ms-db-21 / cpn-5346', 'stellantis-chrysler'),
 ('gmw16873p-pbt+pet-m5gf25', 'general motors (gm)'),
 ('ms941-03 type f-5 frv0 cti0', 'hyundai'),
 ('bas-492', 'baic'),
 ('n28 bn07-gf023', 'bosch'),

In [86]:
normalized_values['AUTO_CERT'] = [(normalize_string(x[0]), x[1]) for x in all_auto_certs]

In [87]:
normalized_values["GRADE"] = [i for i in normalized_values["GRADE"] if "amodel" not in i]

In [88]:
competitor_data2 = read_data_from_snowflake_table(cur,"select * from ANALYTICS_DEV.gst_curated.comp_offset_json_property_mapping")
# QA Snowflake connection
# competitor_data2 = read_data_from_snowflake_table(cur,"select * from ANALYTICS_QA.gst_curated.comp_offset_json_property_mapping")
competitor_data2.head()

,competitor,grade_name,feature,spt,property_id,property_name,value,unit,id,abbt,filler,polymer,grade_moisture_dependent,test_method,filler_load,filler_description,brand,competitor_old,brand_old,grade_name_old
0,MAIP S.R.L.,HIPRO CP FV30W U2,False,True,11,"Tensile stress at break, 5mm/min",50,MPa,10500197,PP-GF,GF,PP,False,ISO 527-1/-2,None,Glass Fiber,HIPRO,MAIP,HIPRO,HIPRO CP FV30W U2
1,SHPP Global Technologies,NORYL™ Resin NH5120RC3,False,True,11,"Tensile stress at break, 5mm/min",48,MPa,10475798,(PPE+PS),,"PPE,PS",False,ISO 527-1/-2,None,None,NORYL™,SABIC,NORYL™,NORYL™ Resin NH5120RC3
2,SHPP Global Technologies,LNP™ STAT-KON™ Compound DSL229,False,True,783,Tensile modulus,2450,MPa,10472991,(PC+PTFE),,"PC,PTFE",False,ASTM D 638,None,None,LNP™,SABIC,LNP™,LNP™ STAT-KON™ Compound DSL229
3,Uteksol,Solplast TH 60A9024 B,False,True,173,Shore A hardness 3s,60,,10514264,TPS,,TPS,False,ISO 48-4 / ISO 868,None,None,Solplast,Uteksol,Solplast,Solplast TH 60A9024 B
4,Kraiburg TPE,THERMOLAST® K TC7PRZ,True,False,1,Injection Molding,True,,10487316,TPE,,TPE,False,None,None,None,THERMOLAST®,KRAIBURG TPE,THERMOLAST®,THERMOLAST® K TC7PRZ

In [89]:
competitor_brands = competitor_data2['brand'].unique().tolist() + competitor_data2['brand_old'].unique().tolist()
competitor_brands = [x for x in competitor_brands if ('®' in x or '™' in x)]
# competitor_brands = list(set([x.strip(" ®™.-/,").lower() for x in competitor_brands if x]))
competitor_brands[:10]

['NORYL™',
 'LNP™',
 'THERMOLAST®',
 'XANTAR™',
 'Makrolon®',
 'BERGAMID®',
 'ExxonMobil™',
 'EcoLene™',
 'Tritan™',
 'Nypol®']

In [90]:
len(competitor_brands)

1688

In [91]:
for x in competitor_brands:
    x2 = x.strip(" ®™.-/,").lower()
    if ('®' in x2 or '™' in x2):
        print(x2)

tenac™-c
slovamid®66
slovamid®6
sabic® sabital
slovamid®66/6
p84®nt1
victrex® ht
p84®uht
sabic® stamax
victrex® st
victrex® fg
slovamid®6/66
victrex® wg
p84®nt2
sabic® supeer
slovamid®6/6t
emac®+
ebac®+
sabic® fortify
tenac™-c
slovamid®66
slovamid®6
slovamid®66/6
p84®nt1
p84®uht
slovamid®6/66
p84®nt2
slovamid®6/6t
emac®+
ebac®+

In [92]:
for i in competitor_brands:
    if len(i) < 5:
        print(i)

LNP™
DOW™
TPX®
NAS®
iOn™
XT®
LNP™
DOW™
TPX®
NAS®
iOn™
XT®

In [93]:
additional_competitor_brands = [
    'slovamid',
    'umg',
    'p84',
    'tenac',
    'eva', # also a OOS polymer

]
normalized_competitor_brands = [normalize_string(x) for x in competitor_brands+additional_competitor_brands]
normalized_competitor_brands = list(set(normalized_competitor_brands))
normalized_competitor_brands

['titanlene',
 'apinat',
 'surpass',
 'onflexv',
 'tisarbon',
 'exceed',
 'tecothane',
 'enviramid',
 'hipex',
 'valtra',
 'apel',
 'armovil',
 'riblene',
 'kresin',
 '3dxpro',
 'calibre',
 'starpet',
 'tenite',
 'daploy',
 'multilon',
 'solvadura',
 'palran',
 'exelene',
 'proflow',
 'alkamax',
 'eastalite',
 'compadur',
 'desmovit',
 'xantar',
 'ixef',
 'sinterline',
 'forstir',
 'tisaform',
 'formolon',
 'starmed',
 'saxalac',
 'sumipex',
 'vylopet',
 'kopla',
 'palstyrol',
 'neostar',
 'onflex',
 'ecopaxx',
 'technaset',
 'advance400',
 'kopa',
 'thermolast',
 'gravitech',
 'aurum',
 'borshape',
 'duragrip',
 'inspire',
 'tisblend',
 'achieve',
 'polyflam',
 'laser',
 'sumikaexcel',
 'agility',
 'bayblend',
 'ecodear',
 'niblend',
 'ecozen',
 'gitop',
 'clearlux',
 'chronoprene',
 'solef',
 'forlene',
 'stirolan',
 'isostyr',
 'bergadur',
 'saxatec',
 'vestakeep',
 'hiplex',
 'koolymer',
 'copec',
 'alkatane',
 'umgabs',
 'evathene',
 'naxell',
 'lnp',
 'isoplast',
 'sicoklar',
 'elite',
 'naxaloy',
 'nylene',
 '4pet',
 'vestoran',
 'tpx',
 'skypel',
 'purpolen',
 'glastic',
 'epitec',
 'fluorloop',
 'anjacom',
 'inzea',
 'titanx',
 'greenflex',
 'pebax',
 'paxon',
 'styronxtech',
 'elvax',
 'tpseal',
 '4max',
 'tafnex',
 'xuanwu',
 'optema',
 'udea',
 'apilon',
 'panlite',
 'nylatron',
 'hydrothane',
 'chemlon',
 'vustat',
 'dafneloy',
 'tisapet',
 'isoplen',
 'terralene',
 'maxxam',
 'dafnemid',
 'venelene',
 'hipscon',
 'revolve',
 'tecoflex',
 'vistamaxx',
 'palblend',
 'medselect',
 'nirion',
 'kepstan',
 'nas',
 'affinity',
 'clearblend',
 'eraclene',
 'victrexwg',
 'linathene',
 'verygreen',
 'diran',
 'thanelene',
 'fibrolon',
 'softflex',
 'ellene',
 'hyflon',
 'vydyne',
 'siveras',
 'raplan',
 'kralastic',
 'technipol',
 'technoter',
 'hipren',
 'pyramid',
 'sicoblend',
 'estaloc',
 'tribocomp',
 'terryl',
 'biocomp',
 'tenacc',
 'teonex',
 'amphora',
 'xenoy',
 'aarofill',
 'novamid',
 'ultzex',
 'oncolor',
 'paldur',
 'leona',
 'polyblend1100',
 'finalloy',
 'nylamid',
 'spelloy',
 'styron',
 'therpol',
 'wellamid',
 'tymax',
 'isoglass',
 'auromid',
 'edgeteksps',
 'sipolprene',
 'polidiemme',
 'dafnetherm',
 'badalac',
 'eastar',
 'asaprene',
 'easyfil',
 'kalix',
 'macoprene',
 'terrasol',
 'niretan',
 'centrex',
 'borpure',
 'selfy',
 'eastman',
 'dafneblend',
 'elastamax',
 'slovastyr',
 'toraycon',
 'auroran',
 'easycork',
 'stattech',
 'upes',
 'dafnelen',
 'attane',
 'dowsil',
 'venuz',
 'celex',
 'elpro',
 'apollox',
 'taisox',
 'carbonfil',
 'lucopren',
 'duratemp',
 'kynarsuperflex',
 'litaca',
 'tefabloc',
 'avaspire',
 'visico',
 'spectar',
 'ecomax',
 'premiglas',
 'magnum',
 'algoflon',
 'chronosil',
 'lotrène',
 'badalon',
 'makrolon',
 'garaflex',
 'ecoloy',
 'sicostirolo',
 'mediprene',
 'sunylon',
 'tairiloy',
 'xiameter',
 'skypet',
 'invista',
 'impact100',
 'bynel',
 'aspun',
 'hdglass',
 'apifive',
 'dinalon',
 'makropol',
 'greenisonyl',
 'alphalon',
 'marlex',
 'jsrexcelink',
 'clearscent',
 'hylar',
 'mapex',
 'polytron',
 'macolen',
 'compur',
 'borcoat',
 'revoloop',
 'formocon',
 'badatron',
 'p84nt1',
 'aspire',
 'dynalloy',
 'plastron',
 'enduraprene',
 'promyde',
 'nistil',
 'uttap',
 'versollan',
 'preelec',
 'titanzex',
 'compafid',
 'provista',
 'tarfuse',
 'ketaspire',
 'styroflex',
 'safron',
 'monprene',
 'stanyl',
 'ecovylopet',
 'palsafe',
 'innopol',
 'eva',
 'echo',
 'radel',
 'trilliant',
 'duraform',
 'rilsan',
 'daunyl',
 'thermax',
 'lucobit',
 'kostil',
 'escorene',
 'techniace',
 'maezio',
 'garathane',
 'kumsollan',
 'apizero',
 'soe',
 'tecotek',
 'appeel',
 'elevate',
 'velvex',
 'rilsamid',
 'sertene',
 'kapex',
 'sabicsabital',
 'antero',
 'nilac',
 'p84nt2',
 'liten',
 'versaflex',
 'sylgard',
 'sabicstamax',
 'nopla',
 'innate',
 'trilene',
 'treva',
 'admer',
 'tisakril',
 'evateno',
 'strapio',
 'ecovio',
 'primacor',
 'aquatuf',
 'absolan',
 'dafnetec',
 'resirene',
 'sabicsupeer',
 'polyfort',
 'polylux',
 'prototherm',
 'tisren',
 'terraprene',
 'sarlink',
 'colorfast',
 'luranyl',
 'crystalflex',
 'topester',
 'siltem',
 'biofibre',
 'aquasolve',
 'sinkral',
 'vestape',
 'drystar',
 'zedex',
 'acudel',
 'schularene',
 'sicoflex',
 'slovamid',
 'tecomid',
 'slovamid6',
 'engage',
 'ultradur',
 'scolefin',
 'elastocon',
 'badadur',
 'aurotron',
 'tivilon',
 'slovalen',
 'starclear',
 'preperm',
 'polyfast',
 'greenisofil',
 'umgwood',
 'cellwood',
 'ecofast',
 'reform',
 'novapol',
 'akrotek',
 'kraton',
 'ultrason',
 'halar',
 'elvaloy',
 'procyclen',
 'slovamid66t',
 'infinam',
 'saxalen',
 'victrexht',
 'palglas',
 'victrexfg',
 'cabelec',
 'stamylex',
 'clearflex',
 'velocity',
 'unipren',
 'aptiv',
 'ecomass',
 'tritan',
 'edgetek',
 'elastollan',
 'lighter',
 'optestat',
 'tenogell',
 'romiloy',
 'advancene',
 'surlyn',
 'biograde',
 'titanpro',
 'bormed',
 'estane',
 'isoglassxt',
 'badaprene',
 'chronothanep',
 'alcudia',
 'sibex',
 'badaflex',
 'protherm',
 'ravalene',
 'excellr',
 'emac',
 'fiberfil',
 'syncure',
 'baystar',
 'tuflin',
 'badamid',
 'astaloy',
 'alkadyne',
 'sclair',
 'apigo',
 'duranex',
 'borsafe',
 'bapolene',
 'paxothene',
 'starflam',
 'sipoltex',
 'metalfil',
 'formoleneformax',
 'hanit',
 'xytron',
 'serplene',
 'torelina',
 'versalloy',
 'thermylene',
 'isoform',
 'array',
 'styrolution',
 'envifill',
 'statrite',
 'cclear',
 'dryflex',
 'dynaflex',
 'isoclear',
 'eltex',
 'kopel',
 'ferrex',
 'arlen',
 'vestosint',
 'ravaplen',
 'topolymer',
 'pearlstick',
 'arnite',
 'agriplas',
 'electriplast',
 'niform',
 'umg',
 'absolac',
 'tairisan',
 'auroform',
 'noryl',
 'schulatec',
 'hylon',
 'enable',
 'strator',
 'bergaflex',
 'permastat',
 'cyrex',
 'durastar',
 'chronothanet',
 'epimax',
 'polyman',
 'formion',
 'p84uht',
 'eastalloy',
 'alkatuff',
 'tecoform',
 'triapol',
 'pharmalene',
 'bulksam',
 'cet',
 'accuguard',
 'norylgtx',
 'astamid',
 'niplene',
 'slovaster',
 'delrin',
 'ecdel',
 'verplen',
 'vivion',
 'glassx',
 'palform',
 'delpet',
 'tecdur',
 'flexifil',
 'safrene',
 'duracon',
 'wanthane',
 'stonefil',
 'polypur',
 'abscent',
 '4loy',
 'novodur',
 'valox',
 'tenopom',
 'hiprene',
 'lubrione',
 'snolen',
 'escor',
 'kopps',
 'aquaforce',
 'akestra',
 'hival',
 'tyril',
 'palprop',
 'unival',
 'polidan',
 'thermylon',
 'texin',
 'akromid',
 'naturtec',
 'slovamid66',
 'torlon',
 'ecolac',
 'exxtral',
 'cycoloy',
 'akroloy',
 'nucrel',
 'borpex',
 'saxamid',
 'kurarity',
 'kareline',
 '4lex',
 'firewire',
 'complet',
 'resomer',
 'titanvene',
 'aegis',
 'carbothane',
 'asaflex',
 'ecoflex',
 'deepgreen',
 'domamid',
 'isoglasslft',
 'polymist',
 'fortii',
 'ceroflex',
 'niblan',
 'mosten',
 'dafnelac',
 'hybrar',
 'armamid',
 'lavanta',
 'magicfil',
 'terratek',
 'mersalen',
 'dipolen',
 'nextend',
 '4pom',
 'novarex',
 'terez',
 'casico',
 'recythen',
 'vestodur',
 'rotec',
 'ion',
 'bapolan',
 'tairilac',
 'akulon',
 'anteo',
 'luran',
 'mablex',
 'utec',
 'ultramid',
 'kocetal',
 'anjaflam',
 'colorrx',
 'badaprop',
 'megol',
 'exxonmobil',
 'icom',
 'mvera',
 'alkathene',
 'schulaform',
 'ultraclean',
 'comtuf',
 'cristal',
 'pulse',
 'chronoflexc',
 'flexirene',
 'udel',
 'isoblend',
 'chronoflexal',
 'styrolux',
 'armobond',
 'proteq',
 'edistir',
 'borstar',
 'ecopellet',
 'xecarb',
 'alkateq',
 'dinaplen',
 'explore',
 'isoter',
 'bormod',
 'aarolene',
 'laperos',
 'acculoy',
 'optipren',
 'aurolen',
 'tairipro',
 'fingerprint',
 'pearlcoat',
 'genestar',
 'xt',
 'ecolene',
 'suprel',
 'innoprene',
 'polygrade',
 'eval',
 'spesin',
 'ultraform',
 'styronatech',
 'marlexhmn',
 '3dxmax',
 'badatechht',
 'zelas',
 'tpeprovamed',
 'lexan',
 'koblend',
 'ryton',
 'rigidex',
 'vectra',
 '3dxstat',
 'trogamid',
 'easywood',
 'hipten',
 'accutech',
 'cyrovu',
 'terluran',
 'ultem',
 'skygreen',
 'prisma',
 'palmid',
 'softest',
 'torlen',
 'schulamid',
 'aurolon',
 'cyrolite',
 'arylmax',
 'tufprene',
 'terblend',
 'neozex',
 'infuse',
 'makroblend',
 'chronoflex',
 'aqualoy',
 'optimax',
 'norylppx',
 'dowlex',
 'dafnestil',
 'redefyne',
 'amorvon',
 'unithene',
 'sabicfortify',
 'tairirex',
 'xelter',
 'durethan',
 'ixan',
 'tecodur',
 'thermorun',
 'kynarflex',
 'borcycle',
 'pearlbond',
 'borlink',
 'evolue',
 '4lac',
 'ecolon',
 'boreco',
 'tepex',
 '4mid',
 'aurocom',
 'glamide',
 'isplen',
 'limosolve',
 'sumikasuper',
 'acrymid',
 'anjatech',
 '4prop',
 'lucolit',
 'aurostyrol',
 'ravamid',
 'durapet',
 'badaform',
 'durepol',
 'unibrite',
 'dafneohm',
 'desmopan',
 'yparex',
 'ebac',
 'aplax',
 'hysun',
 'tisester',
 'alathon',
 'daiamid',
 'tecacomp',
 'titanex',
 'kynar',
 'astalac',
 'slovamid666',
 'cadence',
 'nylaforce',
 'continuum',
 'kopet',
 'lustran',
 'omnix',
 'evoprene',
 'mirathane',
 'topthane',
 'apec',
 'tecopet',
 'niloy',
 'formolene',
 'moretec',
 'ronfalin',
 'starflex',
 'technotep',
 'kophos',
 'thermatech',
 'emerge',
 'asrene',
 'dow',
 'amilan',
 'polifil',
 'greenisoglass',
 'auroblend',
 'zylar',
 'xydar',
 'aceso',
 'cogegum',
 'advance150',
 'percom',
 'carbonx',
 'aaroprime',
 'tislamid',
 'eastmaneastobond',
 'pellethane',
 'toyolac',
 'isonyl',
 'pearlthane',
 'vespel',
 'accucomp',
 'tarnamid',
 'arnitel',
 'formpoly',
 'dafnelan',
 'nymax',
 'luminy',
 'marflex',
 'nypol',
 'mafill',
 'flexomer',
 'bergamid',
 'aarogreen',
 'durabio',
 '4tech',
 'naxel',
 'thermoforce',
 'technamid',
 'xencor',
 'irogran',
 'nylabond',
 'schulablend',
 'resiprene',
 'terlux',
 'renatus',
 'victrexst',
 'lumicene',
 'alcryn',
 'primatop',
 'marvel',
 'cppryme',
 'xtel',
 'lucene',
 'exxelor',
 'starbond',
 'topas',
 'amodel',
 'tenac',
 'orgalloy',
 'vestamid',
 'acrylite',
 'aurodur',
 'tisoplen',
 'fibremod',
 'tisetilen',
 'somos',
 'hylac',
 'dafneglass',
 'triboforce',
 'excellen',
 'p84',
 'xyron',
 'fluorx',
 'borcom',
 'extem',
 'synprene',
 'abspro',
 'umgalloy',
 'akrolen',
 'tecolen',
 'meras',
 'hidura',
 'trimid',
 'gryfilen',
 'borclean',
 'petrotene',
 'precite',
 'dinaxan',
 'luvocom3fpaht',
 'hizex',
 'tecophilic',
 'dynastar',
 'trilac',
 'queo',
 'tuftec',
 'superlink',
 'silastic',
 'isodur',
 'schuladur',
 'hylex',
 'platamid',
 'septon',
 'supran',
 'endurance',
 'biorene',
 'isoryl',
 'tecoplast',
 'melos',
 'alamid',
 'lucofin',
 'bioflex',
 'exact',
 'osterlene',
 'piolen',
 'technyl',
 'armlen',
 'satran',
 'alphaseal',
 'firecon',
 'ecotria',
 'daplen',
 'mersamid',
 'recomyde',
 'etoma',
 'onforce',
 'embrace',
 'isofil',
 'anjaconduct',
 'nemcon',
 'pocan',
 'carborite',
 'dialac',
 'aurotec',
 'compamid',
 'avalon',
 '4dur',
 'sabic',
 'veradel',
 'victrex',
 'perlex',
 'flexnoryl',
 'premiject',
 'evalene',
 'aeroform',
 'durafide',
 'tristar',
 'pelprene',
 'ultrasint',
 'surlynreflectionsseries',
 'tairilite',
 'mbiobase',
 'resound']

In [94]:
for i in normalized_competitor_brands:
    if len(i) < 5:
        print(i)

apel
ixef
kopa
lnp
4pet
tpx
4max
udea
nas
upes
eva
echo
soe
emac
umg
cet
4loy
4lex
4pom
ion
utec
icom
udel
xt
eval
ixan
4lac
4mid
ebac
apec
dow
xtel
p84
queo
4dur

In [95]:
normalized_values['COMPETITOR_BRAND'] = normalized_competitor_brands
normalized_values.keys()

dict_keys(['columnstoIgnore', 'GRADE', 'COMPETITOR_GRADE', 'columnsforSubstringCheck', 'BRAND', 'FEATURE', 'MEDICAL_CERT', 'CHEMICAL_RESISTANCE', 'AUTO_CERT', 'COMPETITOR_BRAND'])

In [96]:
with open("../dependencies/normalized_unique_values_for_grade_mapping.json", "w") as fp:
    json.dump(normalized_values, fp)

## Competitor names

In [97]:
all_competitor_names_current = json.load(open("../dependencies/normalized_competitor_names.json"))

In [98]:
competitor_data = read_data_from_snowflake_table(cur,"select * from competitor_data")
competitor_names = competitor_data['competitor'].unique().tolist()

In [99]:

additional_competitor_data = read_data_from_snowflake_table(cur,"select * from COMPETITIVE_LEGAL_BRAND_PRODUCER_MAPPING")
additional_competitor_names = additional_competitor_data['mdc_competitor_name'].unique().tolist()
for item in additional_competitor_data['alternative_competitor_name']:
    if item!=None:
        additional_competitor_names.extend(item.split(";"))
additional_competitor_names = list(set(additional_competitor_names))

In [100]:
competitor_names = list(set(competitor_names+additional_competitor_names))

In [101]:
sample_comp_grades = [i.lower() for i in competitor_data['competitor_grade'].unique()]

In [102]:
def normalize_comp_names(comp_name):
    splitted_competitor_names = []
    if comp_name is not None: #fix for AttributeError: 'NoneType' object has no attribute 'lower'
        comp_name = comp_name.lower()
    splitted_competitor_names.append(comp_name)
    comp_name_split1 = []
    if comp_name is not None:
        comp_name_split1 = comp_name.split()
    comp_name_split2=[]
    for item in comp_name_split1:
        comp_name_split2.extend(item.split("_"))
    comp_name_split3=[]
    for item in comp_name_split2:
        comp_name_split3.extend(item.split("-"))
    comp_name_split4=[]
    for item in comp_name_split3:
        comp_name_split4.extend(item.split(","))
    comp_name_split5=[]
    for item in comp_name_split4:
        comp_name_split5.extend(item.split("&"))
    splitted_competitor_names.extend(comp_name_split5)
    return splitted_competitor_names

In [103]:
print(sum(x is None for x in competitor_names))


none_indices = [i for i, x in enumerate(competitor_names) if x is None]
print(none_indices)

print(len(competitor_names))

competitor_names = [x for x in competitor_names if x is not None] #handling all errors related to NoneType

print(len(competitor_names))

1
[229]
748
747

In [104]:
all_competitor_names = []
for comp_name in competitor_names:
    all_competitor_names.extend(normalize_comp_names(comp_name))
all_competitor_names=list(set(all_competitor_names))

all_competitor_names = [i for i in all_competitor_names if len(i)>2] #fix for TypeError: object of type 'NoneType' has no len()

In [105]:

# Create a new list to hold the filtered elements from 'a'  
filtered_a = []  
  
for item_a in all_competitor_names:  
    # Assume initially that the item is not a substring of any item in 'b'  
    is_substring = False  
    for item_b in sample_comp_grades:  
        if item_b.startswith(item_a) or item_b.endswith(item_a):  
            # If 'item_a' is found to be a substring of 'item_b', update the flag and break out of the loop  
            is_substring = True  
            print(item_a)
            break  
    # If 'item_a' is not a substring of any items in 'b', add it to the filtered list  
    if not is_substring:  
        filtered_a.append(item_a)  
  
# Optionally, if you need 'a' to be the list without the substrings, you can assign 'filtered_a' back to 'a'  
# all_competitor_names = filtered_a  
  
# print(all_competitor_names)

polyram
vamp
toray
kopla
ferro
dawn
taro
tech
akro
nylene
tasnee
epitec
nanovia
prime
the
jsr
chem
lapex
polymer
color
eastman
matrix
tpe
invista
comp
inno
petro
americas
lati
nova
polyblend
bada
biofibre
witcom
api
fabru
titan
pet
abs
prl
delrin
volaprint
hip
rsh
rtp
ram
ube
exxonmobil
elasto
sax
grivory
bond
ria
bio
sipol
star
pal
dow
elastron
plast
dic
ter
kimya
green
techno
top
europe
sabic
epi
total

In [106]:
comp_names_to_remove = ["witcom",
                        "kopla",
                        "victrex",
                        "prl",
                        "volaprint",
                        "nylene",
                    "grivory",
                    "delrin",
                    "rtp",
                    "kingfa",
                    "victrex"]

In [107]:
all_competitor_names = list(set(all_competitor_names+all_competitor_names_current))
all_competitor_names = [i for i in all_competitor_names if i not in comp_names_to_remove]

In [108]:
[i for i in all_competitor_names if i.startswith("delrin")]

['delrin usa, llc', 'delrin usa llc']

In [109]:

with open("../dependencies/normalized_competitor_names.json", "w") as fp:
    json.dump(all_competitor_names , fp)

In [ ]:
text = "mitsubishi chemicals co. delrin ultrdur xyz"
text_words = text.split()
print(text_words)
# Remove words from the start  
while text_words and text_words[0].lower() in all_competitor_names: 
    print(text_words[0].lower()) 
    text_words.pop(0)
    print(text_words)
# Remove words from the end  
while text_words and text_words[-1].lower() in all_competitor_names:  
    text_words.pop() 

' '.join(text_words).strip()

['mitsubishi', 'chemicals', 'co.', 'delrin', 'ultrdur', 'xyz']
mitsubishi
['chemicals', 'co.', 'delrin', 'ultrdur', 'xyz']
chemicals
['co.', 'delrin', 'ultrdur', 'xyz']
co.
['delrin', 'ultrdur', 'xyz']

'delrin ultrdur xyz'

In [ ]:
"mitsubishi" in all_competitor_names

True

In [ ]:
# validating the list of ce grades present (since for bug 203909 minlon grades were not populated in unique value list)
# df_ce_grades_normalized_new = pd.DataFrame(normalized_values['GRADE'])
# df_ce_grades_normalized_new.to_csv('celanese_grades__normalized_list_new.csv', index=False, header=False)

## Test

In [ ]:
%%time
query_for_grade_match = normalize_string("N 2770")
process.extract(query_for_grade_match, normalized_values['COMPETITOR_GRADE'])

CPU times: total: 359 ms
Wall time: 416 ms

[('n2770k', 91),
 ('ultraformn2770k', 90),
 ('ultraformn2770kat', 90),
 ('n2770kat', 90),
 ('revolven270', 80)]

In [ ]:
%%time
query_for_grade_match = normalize_string("h100")
process.extract(query_for_grade_match, normalized_values['GRADE'])

CPU times: total: 125 ms
Wall time: 151 ms

[('keph100', 90),
 ('neolasth100nc010', 90),
 ('neolasth100', 90),
 ('neoh100nc010', 90),
 ('kepitalh100', 90)]

In [ ]:
query_for_grade_match

'h100'

In [ ]:
unique_values.keys()

dict_keys(['BRAND', 'POLYMER', 'PROPERTY', 'FEATURE', 'FILLER', 'GRADE', 'CERTIFICATION', 'COMPETITOR_GRADE', 'APPLICATION', 'MODIFIER', 'UNIT', 'FILLER_PERCENTAGE', 'GRADE_WITHOUT_BRAND', 'COMPETITOR_GRADE_TRANSFORMED', 'COMP_GRADE_WITHOUT_BRAND', 'COMP_GRADE_TRANSFORMED_WITHOUT_BRAND'])

In [ ]:
for key in ['COMPETITOR_GRADE','BRAND', 'POLYMER', 'PROPERTY', 'FEATURE', 'FILLER', 'CERTIFICATION', 'APPLICATION', 'MODIFIER', 'UNIT', 'FILLER_PERCENTAGE']:
    
    print(key)
    for item in unique_values[key]:
        query_for_grade_match = normalize_string(item)
        if query_for_grade_match not in normalized_values['columnstoIgnore'] and not re.fullmatch(r'(\d+gf|gf\d+|\d+mf|mf\d+)', query_for_grade_match) and len(query_for_grade_match)>3:
            match = process.extract(query_for_grade_match, normalized_values['GRADE'], limit=1)
            if match[0][1]>=90:
                print(query_for_grade_match,": ", match[0][0])
    print("\n\n")
    break

COMPETITOR_GRADE
5220b :  rynitere5220bk503
adstifha1152 :  a115
akroloypaicf20black5268 :  icf
akroloypaicf30black5269 :  icf

KeyboardInterrupt:

In [ ]:
for key in ['BRAND', 'POLYMER', 'PROPERTY', 'FEATURE', 'FILLER', 'CERTIFICATION', 'APPLICATION', 'MODIFIER', 'UNIT', 'FILLER_PERCENTAGE']:
    print(key)
    for item in unique_values[key]:
        query_for_grade_match = normalize_string(item)
        if query_for_grade_match not in normalized_values['columnstoIgnore'] and not re.fullmatch(r'(\d+gf|gf\d+|\d+mf|mf\d+)', query_for_grade_match) and len(query_for_grade_match)>3:
            match = process.extract(query_for_grade_match, normalized_values['COMPETITOR_GRADE'], limit=1)
            if match[0][1]>=90:
                print(query_for_grade_match,": ", match[0][0])
    print("\n\n")

In [ ]:
re.fullmatch(r'(\d+gf|gf\d+|\d+mf|mf\d+)', "gf3000d")

In [ ]:
re.fullmatch(r'^(gf|mf)\d{2}$', "gf300")

In [ ]:
from elasticsearch import Elasticsearch, helpers

def get_es():
    ELASTIC_PASSWORD = "<ELASTICSEARCH_PASSWORD_DEV>"
    es = Elasticsearch(
        "https://elast-gst-nprd-ussc-01.es.privatelink.southcentralus.azure.elastic-cloud.com:9243",
        basic_auth=("elastic", ELASTIC_PASSWORD))
    print(es.info())
    return es

ES = get_es()
# fetch all ul properties
match_all_query = {
    "query": {
    "match_all": {}
    }
}

polymer_resp = ES.search(index='filter_polymer', body=match_all_query, size=100)
polymer_values = [hit['_source'] for hit in polymer_resp['hits']['hits']]