In [1]:
import pandas as pd
import numpy as np
import json

## Please update the filename before run all

In [2]:
filename ="./unique_values_31_08_23"

In [3]:
df1 = pd.read_csv("./uv files/SPT_old.csv")
df2 = pd.read_csv("./uv files/SPT.csv")
df_cleaned = pd.read_excel("./uv files/unique_values_02_06_23_cleaned_new.xlsx")
df_pn_cleaned = pd.read_excel("./uv files/property_name 6 cleaned.xlsx")
df_web = pd.read_excel("./uv files/Celanese website cleaned.xlsx")
df_abb = pd.read_excel("./uv files/Abbreviations-Synonyms List.xlsx")
df_abb_prp = pd.read_excel("./uv files/Abbreviations-Synonyms List v.2.xlsx", sheet_name='Sheet1')
df_abb_filler = pd.read_excel("./uv files/Abbreviations-Synonyms List v.2.xlsx", sheet_name='Sheet2')
df_abb_ft = pd.read_excel("./uv files/Abbreviations-Synonyms List v.2.xlsx", sheet_name='Sheet3')

# optional
# df_abb_prp2 = pd.read_excel("./uv files/abbreviations.xlsx", sheet_name='PROPERTY')
# df_abb_filler2 = pd.read_excel("./uv files/Abbreviations-Synonyms List v.2.xlsx", sheet_name='FILLER')
# df_abb_ft2 = pd.read_excel("./uv files/Abbreviations-Synonyms List v.2.xlsx", sheet_name='FEATURE')

with open('./uv files/german_prop_and_features_terms.json', 'r') as fp:
    german_terms = json.load(fp)

In [4]:
df1["PRODUCT_CD"] = df1["PRODUCT_CD"].str.lower().str.strip()
df2["PRODUCT_CD"] = df2["PRODUCT_CD"].str.lower().str.strip()
df_pn_cleaned["UNIT"] = df_pn_cleaned["UNIT"].str.lower().str.strip()
df_pn_cleaned["ALL UNITS"] = df_pn_cleaned["ALL UNITS"].str.lower().str.strip()

In [5]:
def get_abbreviations(df, col):
    abb = []
    for i in df[col].dropna().to_list():
        splits = i.split(';')
        splits = [a.lower().strip() for a in splits]
        abb.extend(splits)
    abb = list(set(abb))
    
    if "" in abb:
        abb.remove("")
    return abb

In [6]:
name_value = []
property_filter = ['B', 'f1', 'f3', 'f4', 'Group I', 'Group II', 'Group IIIa', 'Group IIIb', 'HB', 'NB', 'ND', 'Pellet', 
                   'PLC 0', 'PLC 1', 'PLC 2', 'PLC 3', 'PLC 4', 'PLC 5', 'PLC 6', 'SE', 'SE/0', 'V-0', 'V-1', 'V-2',]

df1_filtered = df1[df1["VALUE_ASSMNT_SI"].isin(property_filter)]
name_value += (df1_filtered["PROPERTY_NAME"] + " " + df1_filtered["VALUE_ASSMNT_SI"]).to_list()

df2_filtered = df2[df2["VALUE_ASSMNT_SI"].isin(property_filter)]
name_value += (df2_filtered["PROPERTY_NAME"] + " " + df2_filtered["VALUE_ASSMNT_SI"]).to_list()

In [7]:
remove_fillers =  [
    'aramid reinforced', 'carbon fiber reinforced', 'glass reinforced', 'mineral reinforced', 'mineral/glass reinforced', 
    'stainless steel reinforced', 'unfilled', 'aramid', 'carbon', 'glass', 'mineral', 'mineral/glass', 'stainsteel', 
    'unfilled', 'aramidverstärkt', 'carbonfaserverstärkt', 'glasverstärkt', 'mineralverstärkt', 'mineral/glasverstärkt', 
    'edelstahlverstärkt', 'ungefüllt', 'aramid', 'carbon', 'glas', 'mineral', 'mineral/glas', 'edelstahl', 'ungefüllt']

german_terms["fillers"] = remove_fillers

german_terms["features"] = [x for x in german_terms["features"] if x not in remove_fillers]

In [8]:
grade = ["fo 1140l4", "9021 eco-b", 'fo 1140l4 sd3002 black',]
grade.extend(list(set(df1["PRODUCT_CD"].dropna().to_list())))
grade.extend(list(set(df2["PRODUCT_CD"].dropna().to_list())))


property_list = (list(set(df_pn_cleaned["PROPERTY_NAME"].dropna().to_list())))
property_list += df_web["PROPERTY"].dropna().to_list()
property_list += df_abb["Property/Feature"].dropna().to_list() 
property_list += df_abb_prp["PROPERTY"].dropna().to_list()
property_list += get_abbreviations(df_abb, "Abbreviations/Synonyms")
property_list += name_value
property_list += german_terms['properties']

property_list += ['Specific Resistivity','Volume resistivity','Surface resistivity','Dissipation factor','Tensile stress at break',
'Tensile strain at break','Izod impact notched','Emission of organic compounds','Glow wire flammability index',
'Melt volume rate','Poissons ratio','Water absorption','Burning rate','Comparative tracking index','compressive stress',
"h20 absorption", "vda 270 rating", "humidity", "ul94 v0", "hdt200", "h2so4 (sulphuric acid)", "sulphuric acid", 
"h2so4"]

property_list += ['cti', 'comparative tracking index', 'comparative tracking index rating', 'cti plc 0', 'cti plc 1', 
                  'cti plc 2', 'cti plc 3', 'cti plc 4', 'cti plc 5', 'cti plc 6', 'comparative tracking index plc 0', 
                  'comparative tracking index plc 1', 'comparative tracking index plc 2', 
                  'comparative tracking index plc 3', 'comparative tracking index plc 4', 
                  'comparative tracking index plc 5', 'comparative tracking index plc 6', 
                  'comparative tracking index rating plc 0', 'comparative tracking index rating plc 1', 
                  'comparative tracking index rating plc 2', 'comparative tracking index rating plc 3', 
                  'comparative tracking index rating plc 4', 'comparative tracking index rating plc 5', 
                  'comparative tracking index rating plc 6', 'cti plc 0 class', 'cti plc 1 class', 'cti plc 2 class', 
                  'cti plc 3 class', 'cti plc 4 class', 'cti plc 5 class', 'cti plc 6 class', 
                  'comparative tracking index plc 0 class', 'comparative tracking index plc 1 class', 
                  'comparative tracking index plc 2 class', 'comparative tracking index plc 3 class', 
                  'comparative tracking index plc 4 class', 'comparative tracking index plc 5 class', 
                  'comparative tracking index plc 6 class', 'comparative tracking index rating plc 0 class', 
                  'comparative tracking index rating plc 1 class', 'comparative tracking index rating plc 2 class', 
                  'comparative tracking index rating plc 3 class', 'comparative tracking index rating plc 4 class', 
                  'comparative tracking index rating plc 5 class', 'comparative tracking index rating plc 6 class']

property_list += ['stiffness', 'mechanical strength', 'mechanical behavior', 'mechanical resistance', 
                  'mechanical properties', 'deformation', 'deformation stability', 'flexibility', 
                  'mechanical performance', 'modulus', 'strength', 'tensile strength', 'dense', 'heavy', 'impact', 
                  'impact resistance', 'durability', 'tough', 'solidity', 'impact resistant', 'dimensional', 'precise', 
                  'dimensional precision', 'impact', 'impact resistance', 'durability', 'tough', 'solidity', 
                  'impact resistant', 'thermal resistance', 'use temperature', 'flexural performance', 'rigid', 
                  'rigidity', 'stiffness', 'flow', 'flowability', 'flow rate', 'toughness', 'dimensional stability', 
                  'toughness', 'moisture absorption', 'thermal expansion', 'dissipation factor', 
                  'temperature performance', 'electrical strength', 'stiff', 'stiffness at high temp', 'melt index',  
                  'youngs e modulus', 'youngs modulus']

property_list +=['Acceptable shrinkage', 'Average particle size', 'Ball indention hardness', 'Brittleness temperature', 
                 'CLTE', 'Charpy impact', 'Charpy impact strength', 'Comparative tracking PLC 4', 
                 'Comparative tracking index', 'Comparative tracking index rating', 
                 'Comparative tracking index rating PLC3', 'Compressive modulus', 'Continuous service temp', 
                 'Continuous service temperature', 'DTUL at 1.8 MPa', 'Deflection Temperature Under Load (1.8 MPa)', 
                 'Deflection Temperature Under Load at 1.8 MPa', 'Deflection temperature under load (1.8 MPa)', 
                 'Deflection temperature under load at 1.8 MPa', 'Deflection temperature under load at 1.8 megapascals', 
                 'Dielectric constant', 'Dissipation factor', 'Electric strength', 'Electric strength (AC)', 
                 'Flame rating', 'Flammability', 'Flammability rating', 'Flex modulus', 'Flex strength', 
                 'Flexural modulus', 'Flexural strength', 'Flexural strength within a 10% range', 
                 'Heat deflection temperature', 'Heat deflection temperature at 0.45 MPa', 
                 'Heat deflection temperature at 0.45 megapascals', 'Heat deflection temperature at 0.45MPa', 
                 'Heat deflection temperature at 1.8 MPa', 'brittleness temperature', 'MVR', 'Melt flow rate', 
                 'Melt temp', 'Melt temperature', 'Melt volume rate', 'Melting temperature', 'Mold shrinkage', 
                 'Molecular weight', 'electric strength (AC)', 'Notched charpy impact', 'Notched impact', 
                 'Notched impact strength', 'Particle size', 'Shore D hardness', 'Shrinkage', 'Specific gravity', 
                 'Specific resistivity', 'Surface resistivity', 'Tear strength', 'Thermal conductivity', 
                 'Volume resistivity', 'Water absorption', 'Water absorption (equilibrium)', 'thruplane', 
                 'Brittleness temperature', 'Electric strength (AC)', 'Melt volume rate', 'Shore D hardness', 
                 'Flame rating of V0','FR V0','TC V0','MW','VR','HDT','DC','flame retardant V0','HDT C',
                 'TRP','TFE','particle size','DS','EMI sheilding', 'MFI', 'gravity', 'flash', 
                 "low maximum residual moisture content"]

property_list += ['ul', "flame rating of v-0", "v0 flame retardant", "ul94 v0", "ul v0", "v-0", "low-e", "plc 3", 
                  "plc3", "sg1.4", "1.3sg", "sg", "mv", "mvr", "fs", "fs", "unnotched charpy", "ni", 
                  "cold temp. performance", "flex str", "ductile down", "mfr", "izod", "brittleness temp", 
                  "compressive module", "shore d", "shore a", "e-modulus", "compressive load"]


competitor_grade = ['RG251','LFT','PX13012','WSS-M4D865B3','Valox 420seo',
                   'Talcoprene 1020CMV0 BK BLACK','KEPITAL F10-01 BBKF B853',
                  'CN m270 cf2001 natural','HTN 53G50H SLR Black',
                  'Santoprene 281-64MED','Forprene 6NM091A35', 
                  'stamax 30yk270ee', 'durethan akv25fn04', 'akromid b3 k8 9 fr', 'kingfa pa66-rg251', 'duracon m90-45', 
                   'duracon gb-25r', 'duracon ch-10', 'lnp lubricomp rfp36', 'rtp 4009 a', 'laperos ga481', 
                   'durafide 1140a64', 'lnp konduit compound px13012', 'lnp konduit px13012', 'rtp 3400-3 tfe 20',
                   "laperos ga481", "gb-25r", "akromid b3 k8 9 fr natural", "offset123", "plastron pax-cf40-02", 
                    "vicryst r8200", "basf23ab", "Ultraform N 2640 ES AT", "Solvay R-7-120 NAT", "Ryton R-4 220N",
                    "Zytel HTN 51 G35 HSL BK083", 
                  ]

certifications_list = ['NSF61','GMW15890P-PP-GF30E','Renault UB22c','FORD WSS-M98P14-A7','VW50125','GMW15813, Type 9',
'Mercedes DBL 5420','DBL-5420','NSF 61','GMW17521P-PPS-GF40-Type 2','GMW16924P-POM-C2','DBL 5420',
 'GMW15813 Type 9','Renault specification UB22c','UB22c','Ford WSS-M98P14-A7','DBL 5420 for Mercedes','WSS-M98P14-A7',
'GMW16924P-POM-C2']

certifications_list += [
'NSF61 certification at 23°C', 
'automotive specification GMW15890P-PP-GF30E', 
'Renault UB22c auto specification', 
'FORD WSS-M98P14-A7', 
'VW50125 auto approval', 
'GMW15813, Type 9 auto approval', 
'Mercedes DBL 5420 auto specification', 
'GMW15813, Type 9 auto approval', 
'NSF 61 certification at 23°C', 
'Mercedes DBL 5420 approval', 
'automotive specification GMW15890P-PP-GF30E', 
'GMW17521P-PPS-GF40-Type 2 auto approval', 
'automotive specification GMW16924P-POM-C2', 
'RENAULT UB22c auto approval', 
'automotive specification VW50125', 
'Mercedes auto specification DBL 5420', 
'Renault specification UB22c', 
'automotive specification GMW17521P-PPS-GF40-Type 2', 
'auto approval for GMW15890P-PP-GF30E', 
'automotive specification VW50125', 
'automotive specification GMW15813, Type 9', 
'Ford WSS-M98P14-A7 auto specification', 
'automotive specification DBL 5420 for Mercedes', 
'automotive specification VW50125', 
'GMW17521P-PPS-GF40-Type 2 auto approval', 
'FORD auto specification WSS-M98P14-A7', 
'FORD WSS-M98P14-A7 auto approval', 
'automotive specification VW50125', 
'automotive specification GMW16924P-POM-C2', 
'automotive specification GMW16924P-POM-C2', 
'auto specification WSS-M98P14-A7', 
'GMW16924P-POM-C2 auto spec', 
'Mercedes specification DBL 5420', 
'GM auto approval for GMW17521P-PPS-GF40-Type 2', 
'VW50125 auto specification', 
'FORD auto approval WSS-M98P14-A7', 
'GM auto approval GMW15890P-PP-GF30E', 
'automotive specification GMW17521P-PPS-GF40-Type 2', 
'FORD WSS-M98P14-A7 auto approval', 
'Mercedes auto approval DBL 5420 ', 
'GMW17521P-PPS-GF40-Type 2 auto specification', 
'Renault spec UB22c', 
'Auto approval for  GMW16924P-POM-C2 specification', 
'GM spec GMW16924P-POM-C2', 
'WSS-M98P14-A7 auto approval', 
'FORD auto approval WSS-M98P14-A7', 
'Auto approval against VW50125', 
'Mercedes DBL 5420 auto specification', 
'RENAULT spec UB22c', 
'FORD auto approval WSS-M98P14-A7', 
'automotive specification DBL 5420', 
'Auto approval for VW50125 spec', 
'GMW16924P-POM-C2 auto approval', 
'RENAULT auto approval UB22c', 
'Auto approval for WSS-M98P14-A7 spec', 
'auto specification VW50125', 
'automotive specification GMW15890P-PP-GF30E', "Volkswagen VW50125", "Volkswagen approved VW50125", 
"water approval", "drinking water approved", "national sanitation foundation certified @ 23°c", "acs", "chrysler", 
"vw50125", "gmw16924p-pom-c2", "gmw15890p-pp-gf30e", "vw50125", "wss-m98p14-a7", "vw50125", "wss-m98p14-a7", 
"dbl 5420", "dbl 5420 for mercedes", "gmw15813, type 9", "gmw15890p-pp-gf30e", "gmw16924p-pom-c2", 
"gmw17521p-pps-gf40-type 2", "vw50125", "evergrande", "ford wss-m98p14-a7", "ford wss-m98p14-a7", 
"gmw15813, type 9", "gmw16924p-pom-c2", "gmw16924p-pom-c2", "gmw17521p-pps-gf40-type 2", "mercedes dbl 5420", 
"renault ub22c", "wss-m98p14-a7", "cp", "bas", "dongfeng", "egw", "emp", "fiat", "frm", "ftm", "gmp", "gs", 
"great wall", "ip", "mercedes", "ms", "mts", "nsf", "pmp", "slclbg", "smtc", "saic", "stellantis", 
"fca group", "psa group", "fca", "psa", "tl", "tsm", "tst", "ub", "volkswagen", "vw", "vw50125", "wss", "wsk", 
"wras", "wrs", "zf",
    
"cp 1532", "cp 1586", "cp 1758", "cp 1906", "cp 1986", "cp 2436", "cp 2500", "cp 2726", "cp 2794", "cp 2940", "cp 3110", 
"cp 3111", "cp 3379", "cp 3502", "cp 3694", "cp 3761", "cp 3766", "cp 3778", "cp 3905", "cp 4096", "cp 4097", "cp 4109", 
"cp 4111", "cp 4155", "cp 4165", "cp 4240", "cp 4241", "cp 4270", "cp 4451", "cp 4570", "cp 4597", "cp 4624", "cp 4731", 
"cp 4931", "cp 5080", "cp 5090", "cp 5104", "cp 5109", "cp 5149", "cp 5157", "cp 5237", "cp 5280", "cp 5290", "cp 5291", 
"cp 5307", "cp 5310", "cp 5341", "cp 5346", "cp 5347", "cp 5476", "dt 00102.as pom - 001", "dt 00102.as pom - 002", 
"dt 00102.as pom - 003", "en 16421", "ep 03-3", "ep 03a", "ep 10-1c", "ep 14", "ep 15a", "ftm 64 0027", "ftm 64 0057", 
"ftm 69 0008", "ftm 69 0009", "ftm 69 0012", "gs93016", "gs93017", "gs93042", "gs97014", "ip 03a", "ip 13f", "ip 13g", 
"iveco15-5244 emp150", "iveco15-5244 emp70", "iveco15-5244 emp80", "iveco15-5244 emp90", "m 3236 a5", "m 3236 a6", 
"m 3236 a7", "mp 01 lg-01", "mp 01 lg-03", "mp 05-01", "gmw 15812, type 10e", "gmw 15812, type 4e", "gmw 15812, type 4m", 
"gmw 15812, type 5e", "gmw 15812, type 5m", "gmw 15812, type 6e", "gmw 15812, type 7e", "gmw 15812, type 7m", 
"gmw 15812, type 8e", "gmw 15812, type 9", "gmw 15812p, type 8m", "gmw 15813 type 9", "gmw 15813, type 10", 
"gmw 15813, type 2", "gmw 15813, type 4", "gmw 15813, type 5", "gmw 15813, type 6", "gmw 15813, type 7", 
"gmw 15813, type 8", "gmw 15813, type 9", "gmw 15816, type 4", "gmw 15816, type 5", "gmw 15816, type 6", 
"gmw 15816p-tpv, type 5", "gmw 15825, type 5", "gmw 15825,type 6", "gmw 15825p-tpv, type 5", "gmw 15890p-pp-gf20e", 
"gmw 15890p-pp-gf30", "gmw 15890p-pp-gf30e", "gmw 15890p-pp-gf40", "gmw 15890p-pp-gf50-type 50", "gmw 16272p-pp-gf40", 
"gmw 16272p-pp-gf50", "gmw 16278p-pom-type c2", "gmw 16278p-pom-type c3", "gmw 16657", "gmw 16720p-pe", 
"gmw 16720p-pe-uhmw", "gmw 16924p-pom-c2", "gmw 16924p-pom-c4", "gmw 17008p-pom-c2", "gmw 17195p-pom-t1", 
"gmw 17195p-pom-t2", "gmw 17519p-pps-gf45md20", "gmw 17521p-pps-gf40", "gmw 17521p-pps-gf40-type 2", 
"gmw 17521p-pps-gf40e", "gmw 17624p-pom", "gmw 17697p-pp-gf20e", "gmw 17769-pps-i-type 2", "gmw 17802p-pa6-t1", 
"gmw 17810p-pa66-gf40", "gmw 17810p-pa66-gf60", "gmw 17968p-pom-gf20", "gmw 17968p-pom-gf25", "gmw 18026p-pom", 
"gmw 22p-pom-c1", "gmw 22p-pom-c1u", "gmw 22p-pom-c2", "gmw 22p-pom-c2d", "gmw 22p-pom-c2l", "gmw 22p-pom-c2p1", 
"gmw 22p-pom-c2p2", "gmw 22p-pom-c2s", "gmw 22p-pom-c2u", "gmw 22p-pom-c3", "gmw 22p-pom-c3s", "gmw 22p-pom-c4", 
"gmw 22p-pom-c4u", "gmw 3029p-pa6-gf30h", "gmw 3038p-pa66-gf35j",  "ms 220-05, type", "ms 220-05, type a", 
"ms 220-05, type b", "ms 220-05, type c", "ms 220-05, type d", "ms 220-05, type e", "ms 220-05, type g", 
"ms 220-05, type h", "ms 220-05, type j", "ms 220-05, type k", "ms 220-05, type l", "ms 220-05, type m", 
"ms 220-05, type p", "ms 220-05, type r", "ms 220-13, type c-1", "ms 220-13, type d-1", "ms 220-13, type e-1", 
"ms 220-13, type f-1", "ms 220-31, type a1", "ms 220-31, type a2", "ms 237-09, type a", "ms 237-12, type a", 
"ms 244-02", "ms 244-02, type a-2", "ms 941-03, type p-2", "pmp01378_15_01942", "pmp01378_15_01959", 
"pmp01378_15_01961", "pmp01378_15_01962", "pmp01378_15_01963", "pmp01994_10_00137", "pmp01994_10_00138", 
"pmp01994_10_00139", "pmp01994_14_00001", "pom100.55", "pom60.100", "pom75.70", "pom80.45 e", "pom (0xx)-ixx-1", 
"r 22 - hl1 (en 45545-2)", "r 22 - hl2 (en 45545-2)", "r 22 - hl3 (en 45545-2)", "r 23 - hl2 (en 45545-2)", 
"r 23 - hl3 (en 45545-2)", "r 24 - hl2 (en 45545-2)", "r 24 - hl3 (en 45545-2)", "r 26 (0.8 mm) - v0 (en 45545-2)", 
"r 26 (1.6 mm) - v0 (en 45545-2)", "r 26 (3.2 mm) - v0 (en 45545-2)", "s 57914-7", "slclbg 2016018", "slclbg 2018035", 
"slclbg 2019011", "smtc5 310 015", "smtc5 310 020", "smtc5 310 041", "smtc5 320 024", "tl 52277", "tl 52476", 
"tl 52622 md03", "tl 52622 md04", "tl 52622 md05", "tl 52622 md06", "tl 52622 md07", "tl 52622 md22", 
"tl 52622 mdx1/12", "tl 52636-a", "tl 52636-b", "tl 52636-c", "tl 52641c", "tl 52641d", "tl 52703", "tsm 10-519", 
"tsm 5515-1b", "tsm 5515g-1", "tsm 5515g-1a", "tsm 5515g-1b", "tsm 5515g-1bl", "tsm 5515g-1bv", "tsm 5515g-1bvl", 
"tsm 5515g-1d", "tsm 5515g-1w", "tsm 5516g-1", "tsm 5606-1", "tsm 5606g-1", "tsm 5606g-2", "tsm 5709g-1", 
"tst055 54.03", "tst055 54.07", "tst055 54.09", "tst055 54.10", "tst055 54.11", "tst055 54.12", "tst055 54.13", 
"tst055 54.14", "tst055 54.15", "tst055 54.16", "tst055 54.17", "tst055 54.18", "tst055 54.19", "tst055 54.22", 
"tst055 54.23", "tst055 54.25", "tst055 54.30", "tst055 54.32", "tst055 54.35", "tst055 54.37", "tst055 54.40", 
"tst055 54.44", "tst055 58.01", "tst055 58.03", "tst055 58.12", "tst055 72.01-000", "tst055 72.03-001", "ub 02b", 
"ub 03f", "ub 09f", "ub 15", "ub 16b", "ub 22a", "ub 22b", "ub 22c", "ub 22d", "um 09g", "vw 44045", "vw 50123", 
"vw 50125", "vw 50127", "vw 50133", "vw 50134", "vw 50137", "vw 50180", "wras23c", "wras60c", "wras85c", 
"zf7832.050.153",
]

features_list = df_web["FEATURE"].dropna().to_list()
features_list += df_abb_ft["FEATURE"].dropna().to_list()
features_list += get_abbreviations(df_abb_ft, "Abbreviations/Synonyms")
features_list += german_terms['features']

features_list += ['Blow molding', 'porous sintering','Chemical resistance', "low-e",
 'Chemical resistant','Chemically resistant','recycled content', "PIR", "PCR",
 'Electrically conductive','Electrostatic dissipation',
 'Flame retardant','laser direct structuring',
 'light weighting','Good heat resistance','Heat resistance',
 'Heat resistant','High crystallinity','High flow','High flowability',
 'High heat performance','Highly crystalline',
 'Injection moldability','Injection moldable','Injection molding',
 'Laser direct structuring', 'Laser markable',
 'Lead-free solderability', 'Lead-free soldering',
 'Light weight', 'Light weighting', 'Low emission',
 'Low odor', 'Low warp', 'Low warpage', 'high heat conditions',
 'Platable', 'Plateable', 'Porous sintering',
 'Recycled content', 'Resistance to chemicals',
 'Resistant to chemicals', 'Resistant to heat', "electrostatic dissipative", "sintering", "heat stable",
 'Specialty appearance', 'Sustainable',
 'Thermally conductive','Tribological', "microwave resistant",
 'Wear resistance', 'Wear resistant','weld line improved', "blow moldable", "recycled", "tribologically modified",
 "ethyl alcohol resistant", "sheet", "profile", "resistance to water", "resistance to water at high temperature", 
"resistance to water at high temp.", "stable to heat", "impact modified", "stable to light", "stable to weather",
 "fda approved", "plating grade", "weld line strength", "laser marking"," exposure to outdoor sunlight"
                 
 ]


polymers = ['LCP', 'PPS', 'Nylon 66', 'Thermoplastic vulcanizates', 'Polyamide 66', 'PA6', 'polyethylene', 'POM', 
            'Polyoxymethylene', 'Polyphenylene sulfide', 'Liquid Crystal', 'TPV', 'PE-HMW', 'Polypropylene', 
            'Polyamide 6', 'PP', 'Acetal', 'PPA', 'Nylon', 'PA66', 'Nylon 6', 'Liquid crystal polymer', 
            'Acetal Copolymer', 'pa', "htn", "pe", "homo pom", "hmw-pe"]

polymers += ['pehd', 'hdpe', 'pehmw', 'hmwpe', 'peld', 'ldpe', 'peuhmw', 'uhmwpe', 'thermoplastic polyester', 
             'propylene carbonate and polycarbonate', 'Polycyclohexylenedimethylene terephthalate', 
             'Polyethylene terephthalate', 'Polyoxymethylene', 'Polypropylene', 'Polyphthalamide', 
             'Polyphenylene sulfide', 'Styrene-butadiene-styrene', 'Styrene butadiene styrene', 
             'Styrene-ethylene-butylene-styrene', 'Styrene ethylene butylene styrene', 
             'Thermoplastic polyester elastomers', 'Thermoplastic elastomers', 'tp vulcanizates',
             'Thermoplastic polyolefins', 'Thermoplastic polyurethane', 'Thermoplastic vulcanizates', 
             'Acrylonitrile Butadiene Styrene', 'Vamac Ethylene Acrylic Elastomer', 'Ethylene-Vinyl Acetate Copolymer', 
             'Liquid Crystal Polymer',  'Polyamide', 'Polyamide*', 'Polyamide 1010', 'Polyamide1010', 
             'Polyamide 6', 'Polyamide6', 'Nylon-6,10', 'Nylon610', 'Nylon 610', 'semicrystalline polyamide', 
             'Nylon 612', 'Nylon612',  'nylon', 'nylon66', 'nylon 66', 'nylon 666', 'nylon666', 
             'Polyamide 666', 'Polyamide666', 'Polyamide66', 'Polyamide 66']


fillers_list = df_abb_filler["FILLER"].dropna().to_list()
fillers_list += get_abbreviations(df_abb_filler, "Abbreviations/Synonyms")
fillers_list += german_terms['fillers']
fillers_list += ['Glass fiber (short)', '(GF+MD)65', 'Short glass fiber', 'Carbon fiber', 'glass fiber', 'Glass bead', 
                 'carbon fiber', 'Glass filled', 'mineral/glass reinforced', 'Long glass fiber', 'mineral/glass fiber', 
                 'Mineral & glass fiber', 'Unfilled', 'glass', 'stainless steel fiber', 'Graphite fiber', '(GF + MD) 65', 
                 'carbon fiber reinforced', 'GR', 'CF', 'glass reinforced', 'stainless steel reinforced', 
                 'Glass fiber (long)', 'GF', 'Mineral', 'mineral fiber', 'mineral', 'Polytetrafluoroethylene', 
                 'mineral reinforced', 'No filler', 'Glass', 'PTFE', 'aramid reinforced', 'GF30', 'Glass fiber & mineral', 
                 'unfilled', 'unreinforced', 'Mineral and glass fiber', 'aramid fiber', 'GF40', 
                 'non filled', 'without filled', 'virgin', "MD", "fiber content"]

fillers_list += ["gf25", "40gf", "gf15", "mb60", "glass/mineral", "glass/min", "mf", 
                "graphite -fiber", "graphite -filler load", "long -fiber", "long glass -fiber", "mineral -filler load", 
                 "ptfe -filler load", "specialty -filler load", "stainless steel -fiber", "stainless steel -fiber load", 
                 "graphite-fiber", "graphite-filler load", "long-fiber", "long glass-fiber", "mineral-filler load", 
                 "ptfe-filler load", "specialty-filler load", "stainless steel-fiber", "stainless steel-fiber load", 
                 'Short-glass-fiber', 'Shortglass-fiber', 'Short glass-fiber', 'Carbon-fiber', 'Carbon -fiber', 
                 'glass -fiber','glass-fiber' , 'Glass-bead', 'Glass -bead',  "aramid -fiber", "aramid-fiber load", 
                 "carbon-fiber load", "glass-bead load", "glass-fiber (continuous)", "glass-fiber (continuous) load", 
                 "glass-fiber (long)", "glass-fiber (long) load", "glass-fiber (short)", "glass-fiber (short) load", 
                 "glass-fiber load", "glass -fiber (continuous) load", "glass -fiber (long)", "glass -fiber (long) load", 
                 "glass -fiber (short)", "glass -fiber (short) load", "glass -fiber load", "min",
                "gf short", "gf, short", "gf (short)", "gf-short", "gf-long", "gf, long", "gf long", "gf (long)", "not filled", 
                ]

for j in ['gf', 'mf', 'min', 'mineral', 'glass']:
    for i in range(10, 76):
        fillers_list.append(j+str(i))
        fillers_list.append(str(i)+j)

Brands = ['CELCON', 'FRIANYL', 'GUR', 'Hostaform', 'ECOMID', 'VECTRA', 'ZENITE', 'SANTOPRENE', 'COOLPOLY', 'KEPITAL', 
          'CELANYL', 'CELSTRAN', 'FORTRON', 'HOSTAFORM',"Celstran LFT","LFT Celstran", "hf", "VE", "CN", "cnl", "eco"]


applications = ['light aligner', 'electric vehicle connector', 'suspension bellow', 'light aligner', 
                'lithium-ion battery separator', 'washing machine pump', 'microwave oven component', 
                'automotive camera base', 'water pump-impeller', 'auto seat headrest', 'machine slide guide', 
                'beer keg', 'electric vehicle connector', 'automotive seat head cover box', 'automotive camera base', 
                'electric vehicle connector', 'light aligner', 'tailgate protective tube housing', 'microwave oven', 
                'li-ion battery separator', 'water pump-impeller', 'li-ion battery separator', 'tailgate spring sleeve', 
                'beer machine', 'electric vehicle connector', 'microwave oven', 'paint can nozzle', 
                'water meter housing', 'tailgate protective tube housing', 'machine slide guide', '5G Antenna', 
                'machine slide guide', 'washing machine pump', 'microwave oven', 'automotive camera base', 
                'washing machine', 'light aligner', 'paint can nozzle', 'electric vehicle connector', 
                'tailgate spring sleeve', 'water meter housing', 'water pump-impeller', 
                'tailgate protective tube housing', 'water meter housing', 'auto seat headrest', 
                'automotive seat head cover box', 'suspension bellow', 'water pump-impeller', 
                'tailgate protective tube housing', 'suspension bellow', 'li-ion battery separator', 'fastener', 
               'aqua pro gear program', 'hands free access part', 'junior gear program', 'uno gear program', 
               "SMT solder" , "connector", "asp157896-03-b", "asp-157896-03-b", "asp-169554-01-b"]


units = []
units_list = list(set(df_pn_cleaned["ALL UNITS"].dropna().to_list()))
for i in units_list:
    units.extend(i.split(";"))
    
units += list(set(df_web["UNIT"].dropna().to_list() + units))
units+= ['ohm meters', 'kilograms per meter cube', 'W/m/K', 'degree Celsius', 'class', 's', 'Ω·m', 'dB', 'megapascal', 
         'E-4/°C', '%', 'kV/mm', 'degree °C', 'µgC/g', 'kilograms per meter cubed', 'degrees Celsius', 'mm²/s', 
         'centimeters cubed per 10 minutes', 'W/(m K)', 'min', 'mm', 'cm/cm/°C', '% by wt.', 'cm3/10min', '/°C', 'µm', 
         'grams per centimeter cubed', 'kJ/m2', 'g/10min', 'Ohm*m', 'kg/m3', 'kilograms per cubic meter', 'GPa', 
         'J/(kg K)', 'g/cm³', 'g/mol', 'J/m', 'kN/m', 'Ohm', 'centimeter cubed per 10 minutes', 'grams per 10 minutes', 
         'cm³/g', 'Ohm*cm', 'J', 'percent', 'kilojoules per meter squared', 'g/m²', 'grams per mole', 
         'grams per square centimeter', 'kilojoules per square meter', 'centimeter per centimeter per degree Celsius', 
         'cm³/10min', '% by vol.', 'R-Scale', 'Pa s', 'MPa', 'kilovolts per millimeter', 'E-4', 'micrometers', 'M-Scale', 
         'kg/m³', 'grams per cubic centimeter', 'Mpa', 'mm/min', 'kJ/m²', 'ml/g', 'kilonewton per meter', 
         'cubic centimeters per 10 minutes', 'megapascals', '°C', 'kilojoules per meter square', 'µg/g', 
         'degree celsius', 'degree fahrenheit', 'g/cm^3', 'j/m^2', 'ohm/m', 'gram/ccm', 'w/m.k', 'kjoule/m2', 'kg/m2', 
         'g/cc', 'gm/cm2', 'kg/m^3', 'kn/m', 'g/cm3', 'kj/m^3', 'kn/m', 'kv/mm', 'kg/cc', 'g/ml', 'kj/m^2', 'kj/jm^2', 
         'kg/m3', 'grams/cm^2', 'gr/mm3', 'kilonewton/m', "newton"]

In [9]:
# units, applications, Brands, fillers_list, polymers, features_list, certifications_list, competitor_grade, property_list

In [10]:
list(df_cleaned)

['BRAND',
 'POLYMER',
 'PROPERTY_NAME',
 'MODIFIER',
 'FEATURE',
 'FILLER',
 'FILLER_PERCENTAGE',
 'CERTIFICATION',
 'COMPETITOR_GRADE',
 'APPLICATION']

In [11]:
unique_values_dict = {}
for col in df_cleaned:
    uv = list(set(df_cleaned[col].dropna().tolist()))
    unique_values_dict[col] = uv

In [12]:
unique_values_dict["BRAND"] = list(set(unique_values_dict["BRAND"] + Brands))
unique_values_dict["POLYMER"] = list(set(unique_values_dict["POLYMER"] + polymers))
unique_values_dict["APPLICATION"] = list(set(unique_values_dict["APPLICATION"] + applications))
unique_values_dict["FILLER"] = list(set(unique_values_dict["FILLER"] + fillers_list))
unique_values_dict["FEATURE"] = list(set(unique_values_dict["FEATURE"] + features_list))
unique_values_dict["CERTIFICATION"] = list(set(unique_values_dict["CERTIFICATION"] + certifications_list))
unique_values_dict["COMPETITOR_GRADE"] = list(set(unique_values_dict["COMPETITOR_GRADE"] + competitor_grade))
unique_values_dict["PROPERTY_NAME"] = list(set(unique_values_dict["PROPERTY_NAME"] + property_list))
unique_values_dict["UNIT"] = units
unique_values_dict["GRADE"] = grade

In [13]:
for i in unique_values_dict["FILLER"]:
    if i in unique_values_dict["PROPERTY_NAME"]:
        unique_values_dict["PROPERTY_NAME"].remove(i)

In [14]:
unique_values_dict['PROPERTY'] = unique_values_dict["PROPERTY_NAME"]
del unique_values_dict["PROPERTY_NAME"]
print(unique_values_dict.keys())

dict_keys(['BRAND', 'POLYMER', 'MODIFIER', 'FEATURE', 'FILLER', 'FILLER_PERCENTAGE', 'CERTIFICATION', 'COMPETITOR_GRADE', 'APPLICATION', 'UNIT', 'GRADE', 'PROPERTY'])

In [15]:
# to remove (values should be lower case)
to_remove = {
    'FEATURE': ['mineral filler', 'nylon', 'unfilled', 'wear resistance', 'aramid reinforced', 'carbon fiber reinforced', 
                'glass reinforced', 'mineral reinforced', 'mineral/glass reinforced', 'stainless steel reinforced', 
                'unreinforced', 'glass fibre', "auto spec approved", "chlorine", "heat stabilised or stable to heat",
               "high impact or impact modified", "light stabilised or stable to light", 
                "u.v. stabilised or stable to weather", "chlor", "low wear / low friction",
               "drinking water approved"],
    
    'APPLICATION': ['coating', 'compression molding', 'extrusion', 'laser direct structuring (lds)', 'glassfiber', 'fiber',
                   'block', 'film', 'plasticizer', 'powder', '"aqua pro" gear program', '"hands free access" part',
                     '"junior" gear program', '"uno" gear program', 'laser marking', ],
    
    'PROPERTY': ['injection molding', 'injection moulding', 'carbon fiber load', 'glass fiber load', 'mineral filler load', 
             'total load', 'impact resistant', 'wear resistance', 'load', 'impact', "glass fiber (short) load nd", 
                 "glass fibre content", "mineral filler load nd", "ptfe filler load nd", "total load nd", 
                 "conductive filler load nd", "additional information", "96% h2so4 (sulphuric acid)", "fiber content",
                "necessary low maximum residual moisture content", "low-e", 
                "colour; black (bk) uncoloured (un)", "colour; black (bk) uncoloured (un) coloured (co)",
                "colour; black (bk) uncoloured (un) coloured (co) transparent (tr)",
                "flexural strength within a 10% range", ],
    
    'COMPETITOR_GRADE': ['wss-m4d865b3', 'santoprene 281-64med', 'wss-m4d865-b', 'wss-m4d865-b3', 'lft'] ,
    
    'UNIT': ['-', 'o c', 'oc', 'î©â·cm', 'ã—10-5/°c', 'shore d', 'rating', "shore d", "shore a", "%, linear / trans.",
             "linear / trans.", "class", "plc", "plc 0 class", "plc 1", "plc 1 class", "plc 2", 
             "plc 2 class", "plc 3", "plc 3 class", "plc 4", "plc 4 class", "plc 5", "plc 6", 'plc1', 'plc2',
             'plc3', 'plc4', 'plc5', 'plc6', "fast"], 
    
    'MODIFIER': ['-', 'o c', 'oc', 'î©â·cm', 'ã—10-5/°c', 'hr', "plc", "plc 0 class", "plc 1", "plc 1 class", "plc 2", 
                 "plc 2 class", "plc 3", "plc 3 class", "plc 4", "plc 4 class", "plc 5", "plc 6", 'plc1', 'plc2',
                'plc3', 'plc4', 'plc5', 'plc6', 'rating', 'rated', "shore d", "shore a", "linear / trans.", 
                 "%, linear / trans.", "class", 'v-0', "%",],
    
    'BRAND': ['at'],
    
    'FILLER': ["(gf +md)65", "(gf+md)65", "(gf + md) 65", "mineral & glass fiber", "mineral and glass fiber", "glass fiber & mineral",],
    'POLYMER': ["xxx"],
    'CERTIFICATION': [
        "auto approval against vw50125",
        "auto approval for  gmw16924p-pom-c2 specification",
        "auto approval for gmw15890p-pp-gf30e",
        "auto approval for vw50125 spec",
        "auto approval for wss-m98p14-a7 spec",
        "auto specification vw50125",
        "auto specification wss-m98p14-a7",
        "automotive specification dbl 5420",
        "automotive specification dbl 5420 for mercedes",
        "automotive specification gmw15813, type 9",
        "automotive specification gmw15890p-pp-gf30e",
        "automotive specification gmw16924p-pom-c2",
        "automotive specification gmw17521p-pps-gf40-type 2",
        "automotive specification vw50125",
        "evergrande auto",
        "ford wss-m98p14-a7 auto approval",
        "ford wss-m98p14-a7 auto specification",
        "gmw15813, type 9 auto approval",
        "gmw16924p-pom-c2 auto approval",
        "gmw16924p-pom-c2 auto spec",
        "gmw17521p-pps-gf40-type 2 auto approval",
        "gmw17521p-pps-gf40-type 2 auto specification",
        "mercedes dbl 5420 approval",
        "mercedes dbl 5420 auto specification",
        "renault ub22c auto approval",
        "renault ub22c auto specification",
        "vw50125 auto approval",
        "vw50125 auto specification",
        "wss-m98p14-a7 auto approval",
    ]
}


for l in to_remove:
    for i in to_remove[l]:
        unique_values_dict[l] = [x.lower() for x in unique_values_dict[l]]
        
        if i in unique_values_dict[l]:
            unique_values_dict[l].remove(i)
            
# some values might not get removed as data is not cleaned. 
# later part of the we are removing the values from the same dict

In [16]:
unique_values_df = pd.DataFrame(dict([(k, pd.Series(v)) for k,v in unique_values_dict.items()]))
unique_values_df

,BRAND,POLYMER,MODIFIER,FEATURE,FILLER,FILLER_PERCENTAGE,CERTIFICATION,COMPETITOR_GRADE,APPLICATION,UNIT,GRADE,PROPERTY
0,celanyl,pa612,89 m-scale,high crystallinity,45mineral,27.0 %,"ms 244-02, type a-2",sarlink 4175,ui control frame,mpa,fo 1140l4,flexmod149
1,talcoprene,styrene-butadiene-styrene,232 °c,extrusion,mf46,4.0 %,gmw 17195p-pom-t1,sarlink x5780b,automotive-double coil,kn/m,9021 eco-b,flexmod93
2,tecnoprene®,polyamide1010,0.79 e-4/°c,cl resistant,61glass,46.0 %,smtc5 310 020,pocan dp1105,accelerator pedal module,ohms,fo 1140l4 sd3002 black,melting temperature at 10°c /min
3,ve,acetal copolymer,q - m,recycled content,glass19,18.0 %,28 b 14-gf010,ultradur b 4300 g4 hispeed,automotive seat belt-guide,in/in/°f,hostaform c 9021 eco-b,gloss45
4,zytel® lcpa,tpv,e-4,coating,mineral10,7.0 %,gs 93017,rynite 545,router holder,1/k,kepital ts-22h,backpres
...,...,...,...,...,...,...,...,...,...,...,...,...
11783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,airplane-rudder,NaN,NaN,NaN
11784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,motor position switch/sensor (mps)-4 way,NaN,NaN,NaN
11785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,taps and related accessories,NaN,NaN,NaN
11786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,snowmobile fuel sender unit (fsu)-container/ho...,NaN,NaN,NaN
11787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,harnesses-connector,NaN,NaN,NaN

In [17]:
for col in unique_values_df:
    unique_values_df[col] = unique_values_df[col].str.lower().str.strip()

In [18]:
unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace("--", np.NaN)
unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace("-", np.NaN)
unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace('î©â·cm', np.NaN)
unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace('ã—10-5/°c', np.NaN)

unique_values_df["UNIT"] = unique_values_df["UNIT"].replace("--", np.NaN)
unique_values_df["UNIT"] = unique_values_df["UNIT"].replace("-", np.NaN)
unique_values_df["UNIT"] = unique_values_df["UNIT"].replace('î©â·cm', np.NaN)
unique_values_df["UNIT"] = unique_values_df["UNIT"].replace('ã—10-5/°c', np.NaN)


unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace("--$", np.NaN, regex=True)
unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace("-$", np.NaN, regex=True)

unique_values_df["UNIT"] = unique_values_df["UNIT"].replace("--$", np.NaN, regex=True)
unique_values_df["UNIT"] = unique_values_df["UNIT"].replace("-$", np.NaN, regex=True)

In [19]:
unique_values_df = unique_values_df.replace('ºc', "°c", regex=True)
unique_values_df = unique_values_df.replace('˚c', "°c", regex=True)
unique_values_df = unique_values_df.replace('℃', "°c", regex=True)

In [20]:
# unique_values_df["POLYMER"] = unique_values_df["POLYMER"].replace("(", "", regex=True)
# unique_values_df["POLYMER"] = unique_values_df["POLYMER"].replace(")", "", regex=True)

unique_values_df["POLYMER"] = unique_values_df["POLYMER"].replace('(aem)', 'aem')
unique_values_df["POLYMER"] = unique_values_df["POLYMER"].replace('(evac)', 'evac')

In [21]:
# unique_values_df["UNIT"] = unique_values_df["UNIT"].replace('ºc', "°c", regex=True)
unique_values_df["UNIT"] = unique_values_df["UNIT"].replace('â„ƒ', "°f", regex=True)
# unique_values_df["UNIT"] = unique_values_df["UNIT"].replace('˚c', "°c", regex=True)
# unique_values_df["UNIT"] = unique_values_df["UNIT"].replace('℃', "°c", regex=True)

unique_values_df["UNIT"] = unique_values_df["UNIT"].replace('ã—10-5 /°c', '-10-5 /°c', regex=True)
unique_values_df["UNIT"] = unique_values_df["UNIT"].replace('ã—105/°c', '-105 /°c', regex=True)

# unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace('ºc', "°c", regex=True)
unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace('â„ƒ', "°f", regex=True)
# unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace('˚c', "°c", regex=True)
# unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace('℃', "°c", regex=True)

unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace('ã—10-5 /°c', '-10-5 /°c', regex=True)
unique_values_df["MODIFIER"] = unique_values_df["MODIFIER"].replace('ã—105/°c', '-105 /°c', regex=True)

In [22]:
for col in unique_values_df:
    unique_values_df[col] = unique_values_df[col].str.strip()

unique_values_df.replace("", np.NaN, inplace=True)

In [23]:
for l in to_remove:
    for i in to_remove[l]:
        
        if i in unique_values_df[l].values:
            unique_values_df[l].replace(i, np.NaN, inplace=True)

In [24]:
def drop_duplicates(temp_df):
    for col in temp_df:
        uv = list(set(temp_df[col].dropna().tolist()))
        temp_df.loc[:, col] = uv + [np.NaN]*(len(temp_df.index) - len(uv))
    return temp_df

unique_values_df = drop_duplicates(unique_values_df.copy())
unique_values_df

,BRAND,POLYMER,MODIFIER,FEATURE,FILLER,FILLER_PERCENTAGE,CERTIFICATION,COMPETITOR_GRADE,APPLICATION,UNIT,GRADE,PROPERTY
0,lft celstran,pa612,89 m-scale,extrusion,45mineral,27.0 %,"ms 244-02, type a-2",sarlink 4175,ui control frame,w/m/k,hostaform c 9021 eco-b,comparative tracking index group ii
1,celanyl,polyamide66,232 °c,high crystallinity,mf46,46.0 %,gmw 17195p-pom-t1,sarlink x5780b,automotive-double coil,x10-5/k,kepital ts-22h,flexmod149
2,talcoprene,"nylon-6,10",q - m,cl resistant,61glass,4.0 %,smtc5 310 020,pocan dp1105,automotive seat belt-guide,in^-5/in/°f,zenite 450lds,flexmod93
3,cn,pa666,0.79 e-4/°c,release,glass19,18.0 %,28 b 14-gf010,ultradur b 4300 g4 hispeed,accelerator pedal module,ohms,coolpoly e5521,melting temperature at 10°c /min
4,tecnoprene®,ethylene-vinyl acetate copolymer,e-4,coating,mineral10,7.0 %,gs 93017,rynite 545,router holder,q - m,celstran pps-af35-01,gloss45
...,...,...,...,...,...,...,...,...,...,...,...,...
11783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,taps and related accessories,NaN,NaN,NaN
11784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,automotive rear bumper-bracket,NaN,NaN,NaN
11785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,snowmobile fuel sender unit (fsu)-container/ho...,NaN,NaN,NaN
11786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,harnesses-connector,NaN,NaN,NaN
11787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
for col in unique_values_df:
    unique_values_df[col] = unique_values_df[col].sort_values(ignore_index=True)

unique_values_df

,BRAND,POLYMER,MODIFIER,FEATURE,FILLER,FILLER_PERCENTAGE,CERTIFICATION,COMPETITOR_GRADE,APPLICATION,UNIT,GRADE,PROPERTY
0,amorphous ppa,abs,(kj/m²),anti-static,10gf,0 %,01378_15_02001,8000bs,(cement) renders,%,9021 eco-b,1.3sg
1,ateva,acetal,(mpa),antiblocking agent,10glass,12.0 %,01378_15_02346,8500bs,12-pin connector for electrical & electronics,% by vol.,celanyl a2 cf30 tfs15 bk 9005/c,416 edelstahl
2,ateva®,acetal copolymer,-0.024 e-4/°c,antiblockmittel,10mf,18.0 %,01994_14_00056,9000bs,12-way connector for automotive & transportation,% by wt.,celanyl a2 gf15 bk 9005/1,"416 edelstahl,16 µ-in,90f,pv2000,40 psi,50 ft/min"
3,at®,acrylonitrile butadiene styrene,-10-5 /°c,antistatisch,10min,2.0 %,01994_14_00057,9500bs,120a outdoor connector for electrical & electr...,(kj/m²),celanyl a2 gf33 bk 2000/uv/1,416 stainless
4,celanex,aem,-105 /°c,besch,10mineral,20.0 %,01994_14_00058,akromid b3 k8 9 fr,12v battery,(mpa),celanyl a2 gf33 bk 9005/1,"416 stainless,16 µ-in,90f,pv2000,40 psi,50 ft/min"
...,...,...,...,...,...,...,...,...,...,...,...,...
11783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zipper component for consumer goods,NaN,NaN,NaN
11784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zipper-slide,NaN,NaN,NaN
11785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zippers,NaN,NaN,NaN
11786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zone guard for industrial,NaN,NaN,NaN
11787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
import itertools

combinations = []
for pair in itertools.combinations(list(unique_values_df), r=2):
    combinations.append(pair)
# combinations

In [27]:
intersections = {}
for i in range(len(combinations)):
#     print(set(unique_values_df[combinations[i][0]].dropna()).intersection(set(unique_values_df[combinations[i][1]].dropna())))
    intersection = set(unique_values_df[combinations[i][0]].dropna()).intersection(set(unique_values_df[combinations[i][1]].dropna()))
    if intersection and combinations[i] !=('MODIFIER', 'UNIT'):
#         print(combinations[i])
        intersections[combinations[i]] = intersection
    
intersections

{('MODIFIER', 'FILLER_PERCENTAGE'): {'0 %', '4.5 %'},
 ('FEATURE', 'APPLICATION'): {'color concentrate',
  'lighting',
  'profile',
  'sheet'},
 ('FEATURE', 'UNIT'): {'hr'},
 ('FILLER', 'UNIT'): {'min'}}

In [28]:
unique_values_df

,BRAND,POLYMER,MODIFIER,FEATURE,FILLER,FILLER_PERCENTAGE,CERTIFICATION,COMPETITOR_GRADE,APPLICATION,UNIT,GRADE,PROPERTY
0,amorphous ppa,abs,(kj/m²),anti-static,10gf,0 %,01378_15_02001,8000bs,(cement) renders,%,9021 eco-b,1.3sg
1,ateva,acetal,(mpa),antiblocking agent,10glass,12.0 %,01378_15_02346,8500bs,12-pin connector for electrical & electronics,% by vol.,celanyl a2 cf30 tfs15 bk 9005/c,416 edelstahl
2,ateva®,acetal copolymer,-0.024 e-4/°c,antiblockmittel,10mf,18.0 %,01994_14_00056,9000bs,12-way connector for automotive & transportation,% by wt.,celanyl a2 gf15 bk 9005/1,"416 edelstahl,16 µ-in,90f,pv2000,40 psi,50 ft/min"
3,at®,acrylonitrile butadiene styrene,-10-5 /°c,antistatisch,10min,2.0 %,01994_14_00057,9500bs,120a outdoor connector for electrical & electr...,(kj/m²),celanyl a2 gf33 bk 2000/uv/1,416 stainless
4,celanex,aem,-105 /°c,besch,10mineral,20.0 %,01994_14_00058,akromid b3 k8 9 fr,12v battery,(mpa),celanyl a2 gf33 bk 9005/1,"416 stainless,16 µ-in,90f,pv2000,40 psi,50 ft/min"
...,...,...,...,...,...,...,...,...,...,...,...,...
11783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zipper component for consumer goods,NaN,NaN,NaN
11784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zipper-slide,NaN,NaN,NaN
11785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zippers,NaN,NaN,NaN
11786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,zone guard for industrial,NaN,NaN,NaN
11787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
unique_values_df = unique_values_df[['BRAND', 'POLYMER', 'PROPERTY', 'FEATURE', 'FILLER', 'GRADE', 'CERTIFICATION', 'COMPETITOR_GRADE', 'APPLICATION', 'MODIFIER', 'UNIT', 'FILLER_PERCENTAGE']]

In [30]:
unique_values_df.to_excel(filename + ".xlsx", index=False)

In [31]:
uniques = {}
for col in unique_values_df:
    uniques[col] = unique_values_df[col].dropna().to_list()

In [32]:
import json 

json_path = filename + '.json'
with open(json_path, 'w', encoding="utf-8") as fp:
    json.dump(uniques, fp, indent=2)

In [33]:
import re
import string
from nltk import ngrams
from spello.model import SpellCorrectionModel
import copy

In [34]:
UNIQUE_VALUES = copy.deepcopy(uniques)

## copy latest code from the code base

In [35]:
# comment the if part in add_spaces func
# add label in parameters and add if label in ['PROPERTY', 'FEATURE', 'FILLER']: # before possible_terms_for_german_detection = [] in data pre-processing func
# comment check_spelling(query) in data pre-processing func

In [36]:
with open(file="./cleaning_dependencies/german_terms_mapping.json") as f_in:
    GERMAN_MAPPING = json.load(fp=f_in)

In [37]:
def clean_cti_property(q) -> str:
    keywords = ['cti', 'comparative tracking index', 'comparative tracking index rating', 'comparative tracking rating',
                'comparative tracking']

    for keyword in keywords:
        if keyword in q:
            q = q.replace(f"{keyword} plc", f"{keyword} plc ")

            q = q.replace(f"{keyword} = plc", f"{keyword} plc ")
            q = q.replace(f"{keyword} of plc =", f"{keyword} plc ")
            q = q.replace(f"{keyword} of plc", f"{keyword} plc ")
            q = q.replace(f"{keyword} is plc", f"{keyword} plc ")
            q = q.replace(f"{keyword} as plc", f"{keyword} plc ")
            q = q.replace(f"{keyword} with plc =", f"{keyword} plc ")
            q = q.replace(f"{keyword} with plc", f"{keyword} plc ")
            q = q.replace(f"{keyword} select plc =", f"{keyword} plc ")
            q = q.replace(f"{keyword} select plc", f"{keyword} plc ")

            # for num in range(0, 7):
            #     q = q.replace(f"{keyword} {num} ", f"{keyword} plc {num} ")
            #     q = q.replace(f"{keyword} = {num} ", f"{keyword} plc {num} ")
            #     q = q.replace(f"{keyword} of {num} ", f"{keyword} plc {num} ")
            #     q = q.replace(f"{keyword} is {num} ", f"{keyword} plc {num} ")
            #     q = q.replace(f"{keyword} as {num} ", f"{keyword} plc {num} ")
            #     q = q.replace(f"{keyword} with {num} ", f"{keyword} plc {num} ")
            #     q = q.replace(f"{keyword} select {num} ", f"{keyword} plc {num} ")

            # max_value = 6
            # pattern = rf'\b{keyword}\s+(\d+)\b'
            # q = re.sub(pattern, lambda match: f"{keyword} plc {match.group(1)}" if int(match.group(1)) <= max_value and not match.group(1).isalpha() else match.group(0), q)

            # pattern = rf'\b{keyword}\s+=\s+(\d+)\b'
            # q = re.sub(pattern, lambda match: f"{keyword} plc {match.group(1)}" if int(match.group(1)) <= max_value and not match.group(1).isalpha() else match.group(0), q)

            # pattern = rf'\b{keyword}\s+of\s+(\d+)\b'
            # q = re.sub(pattern, lambda match: f"{keyword} plc {match.group(1)}" if int(match.group(1)) <= max_value and not match.group(1).isalpha() else match.group(0), q)

            # pattern = rf'\b{keyword}\s+is\s+(\d+)\b'
            # q = re.sub(pattern, lambda match: f"{keyword} plc {match.group(1)}" if int(match.group(1)) <= max_value and not match.group(1).isalpha() else match.group(0), q)

            # pattern = rf'\b{keyword}\s+as\s+(\d+)\b'
            # q = re.sub(pattern, lambda match: f"{keyword} plc {match.group(1)}" if int(match.group(1)) <= max_value and not match.group(1).isalpha() else match.group(0), q)

            # pattern = rf'\b{keyword}\s+with\s+(\d+)\b'
            # q = re.sub(pattern, lambda match: f"{keyword} plc {match.group(1)}" if int(match.group(1)) <= max_value and not match.group(1).isalpha() else match.group(0), q)

            # pattern = rf'\b{keyword}\s+select\s+(\d+)\b'
            # q = re.sub(pattern, lambda match: f"{keyword} plc {match.group(1)}" if int(match.group(1)) <= max_value and not match.group(1).isalpha() else match.group(0), q)

    # remove extra spaces
    q = re.sub("(\s+)", " ", q.strip())
    return q


def get_filtered_values() -> list:
    filtered_values = []
    units_list = []
    for k in UNIQUE_VALUES:
        for value in UNIQUE_VALUES[k]:
            words = value.split()
            for word in words:
                if (re.search("\.", word) or re.search("-", word) or re.search("/", word)) and (word not in ["-", "/", "."]):
                    filtered_values.append(word)
                    if k == "UNIT":
                        units_list.append(word)
    units_list += ["g/ml", "w/m.k", "kg/m^3", "g/cm^3", "kj/m^2", "g/cm^3", "grams/cm^2", "g/cc", "ohm/m",
                   "kj/m^3", "g/cc", "kg/m3", "kn/m", "kv/mm", "kg/m3", "g/cm3", "j/m^2", "kg/cc", "kn/m", "w/m.k"]
    filtered_values = list(set(filtered_values + units_list))
    return filtered_values, units_list



def add_spaces(text, values, units) -> str:
    words = text.split()
    updated_words = []
    for word in words:
        #         if any(word.startswith(v) for v in values):
#         if any(word in v for v in values) or any(word[1:] in v for v in values) or any(word[:-1] in v for v in values) or \
#                 any(word.endswith(v) for v in units) or any(word[:-1].endswith(v) for v in units):
#             # Word is substring in one of the lists, add word
#             #             print(word)
#             updated_words.append(word)
#         else:
        processed_word = word.replace("/", " / ")  # .replace("-", " -")
        pattern = r"(?<=\D)-(?=\d)|(?<=\d)-(?=\D)|(?<=\D)-(?=\D)"
        processed_word = re.sub(pattern, ' - ', processed_word)
        # 9.0x10^ -6 >>>>>>>>>> 9.0x10^-6
        processed_word = re.sub(
            r"(?<=\d)\^ - (?=\d)", '^-', processed_word)
        # 9.0e -6 >>>>>>>> 9.0e-6
        processed_word = re.sub(r"(?<=\d)e - (?=\d)", 'e-', processed_word)
        dot_pattern = r'(?<=[a-zA-Z])\.(?=[a-zA-Z])|(?<=[a-zA-Z])\.(?=\d)|(?<=\d)\.(?=[a-zA-Z])'
        processed_word = re.sub(dot_pattern, '. ', processed_word)
        updated_words.append(processed_word)

    cleaned_text = " ".join(updated_words)
    cleaned_text = re.sub("(\s+)", " ", cleaned_text.strip())
    cleaned_text = cleaned_text.replace("+/ -", "+/-")
    return cleaned_text


# Trim all the enities
def remove_brackets(labelled_text) -> str:
    for i in [("(", ")"), ("[", "]"), ("{", "}")]:
        if i[0] in labelled_text and not i[1] in labelled_text:
            labelled_text = labelled_text.replace(i[0], " ")
        elif i[1] in labelled_text and not i[0] in labelled_text:
            labelled_text = labelled_text.replace(i[1], " ")

#     # <> not include
#     labelled_text = labelled_text.strip("()").strip(
#         "[]").strip("{}").strip('""').strip("''").strip()
    if labelled_text:
        for i in [("(", ")"), ("[", "]"), ("{", "}"), ("'", "'"), ('"', '"')]:
            if i[0] == labelled_text[0] and i[1] == labelled_text[-1]:
                labelled_text = labelled_text[1:-1]
                break

    return labelled_text


def remove_unwanted_characters(labelled_text) -> str:
    trim_characters = ["=", "/", "-", ",", ":",
                       ";", "#", "$", "&", "*", "?", "|", "@"]
    if labelled_text and len(labelled_text) > 1 and labelled_text[0] in trim_characters and not labelled_text[1:].split()[0][0].isnumeric():  # or
        labelled_text = labelled_text[1:]

    if labelled_text and labelled_text[-1] in trim_characters:
        labelled_text = labelled_text[:-1]
    return labelled_text.strip()


def remove_hyphens(labelled_text) -> str:
    # converts "- -" to "-"
    labelled_text = re.sub(r'(- ){2,}', r'-', labelled_text)
    pattern = r'^(-+)(?![-.\d])|(?<![-.\d])(-+)$'
    labelled_text = re.sub(pattern, '', labelled_text)
    labelled_text = re.sub("(\s+)", " ", labelled_text.strip())
    return labelled_text


def trim(labelled_text) -> str:
    labelled_text_len = len(labelled_text)
    cleaned_labelled_text = remove_brackets(labelled_text)

    cleaned_labelled_text = remove_hyphens(cleaned_labelled_text)

    cleaned_labelled_text = remove_unwanted_characters(cleaned_labelled_text)

    if len(cleaned_labelled_text) == labelled_text_len:
        return cleaned_labelled_text
    else:
        return trim(cleaned_labelled_text)
    
    
def convert_property_shortforms_with_values(labelled_text) -> str:
    pattern = r"\d+\.\d+sg|sg\d+\.\d+|\d+sg|sg\d+|\d+\.\d+hdt|hdt\d+\.\d+|\d+hdt|hdt\d+"
    matches = re.findall(pattern, labelled_text)
    for match in matches:
        numbers = re.findall(r'[0-9.]+', match)
        text = re.findall(r'[a-z]+', match)
        labelled_text = labelled_text.replace(match, f"{text[0]} of {numbers[0]}", 1)
    return  labelled_text

In [38]:
def data_preprocessing(text, values, units, label) -> str:
    query = copy.deepcopy(text)

    # remove $, #, :
    query = query.replace('$', ' ').replace('#', ' ').replace(":", ' ')

    # replace 
    query = query.replace(";", ", ").replace("；", ", ").replace("~", '- ').replace("–", "-")
    

    # remove extra spaces
    query = re.sub("(\s+)", " ", query.strip())

    # trim
    query = trim(query)

    # replace multiple occurance with single occurance
    query = re.sub(r'[!@%?\'=&\.]+', lambda match: match.group(0)[0], query)
    query = re.sub(r'[,]+', lambda match: match.group(0)[0], query)

    # replace special characters to right format
    query = query.replace('（', "(").replace('）', ')').replace('ºc', "°c").replace(
        '˚c', "°c").replace('℃', "°c").replace('=<', "<=").replace('=>', '>=').lower()

    # find all occurrences of the pattern and add a space after each match
    pattern1 = r'(?<=[<>=!])(?=[^=])|(?<=[^<>=])(?=[<>=!])'
    query = re.sub(pattern1, ' ', query).replace("! =", "!=")

    # add space before and after for "+" "@" "|" "&"
    # we can include more characters inside the [] like r'([+,/-])'
    query = re.sub(r'([:&+@|()\[\]\{\}])', r' \1 ', query)
    # [{]}
    # add space after for ";", ":" "?" "%" ")"
    query = re.sub(r'([;?%])', r'\1 ', query)

    # add space before for "("
#     query = re.sub(r'([(]', r' \1', query)

    # add space after for ","
    pattern2 = r"(?<=\D),(?=\d)|(?<=\d),(?=\D)|(?<=\D),(?=\D)"
    query = re.sub(pattern2, ', ', query)

    # after adding spaces, we are removing if any multiple spaces exist
    query = re.sub("(\s+)", " ", query.strip())

#     .replace("( ", "(").replace(" )", ")").replace("[ ", "[").replace(" ]", "]").replace("? ? ?", "???").replace("? ?", "??")
    # remove unnecessary spaces
    query = query.replace("+ /", "+/")

    # converting some cases to right format
    # replace("<= >=", "<==>").
    query = query.replace("> / =", ">=").replace("< / =", "<=").replace(
        "= / >", ">=").replace("= / <", "<=").replace("< >=", "<=>")

    # add space for ".", "/", "-"
    query = add_spaces(query, values, units)

    #convert sg1.4, hdt200 to proper format
    query = convert_property_shortforms_with_values(query)

    query = clean_cti_property(query)
    
    if label in ['PROPERTY', 'FEATURE', 'FILLER']:
        
        possible_terms_for_german_detection = []
        search_query_splitted = query.split()
        search_query_splitted = [word.strip(
            string.punctuation) for word in search_query_splitted]
        threegrams = ngrams(search_query_splitted, 3)
        twograms = ngrams(search_query_splitted, 2)
        onegrams = ngrams(search_query_splitted, 1)

        # GERMAN_MAPPING = get_german_mapping()
        possible_terms_for_german_detection = [
            " ".join(grams) for grams in threegrams if " ".join(grams) in GERMAN_MAPPING]
        possible_terms_for_german_detection.extend(
            [" ".join(grams) for grams in twograms if " ".join(grams) in GERMAN_MAPPING])
        possible_terms_for_german_detection.extend(
            [" ".join(grams) for grams in onegrams if " ".join(grams) in GERMAN_MAPPING])

        for german_term in possible_terms_for_german_detection:
            query = query.replace(german_term, GERMAN_MAPPING[german_term])

    #query = check_spelling(query)

    query = query.replace("performance level category", "plc")

    # remove extra spaces (do always just before return)
    query = re.sub("(\s+)", " ", query.strip())
    return query

In [39]:
filtered_values, units_list = get_filtered_values()

In [40]:
chars = ["/", "-", '"' "(", ")", "[", "]"]
unique_values_new = {}
for label in UNIQUE_VALUES:
    unique_values_new[label] = []
    for v in UNIQUE_VALUES[label]:
        if any((c in chars) for c in v):
            unique_values_new[label].append(v)
        
# unique_values_new

In [41]:
unique_values_new_cleaned = {}
for label in unique_values_new:
    unique_values_new_cleaned[label] = []
    for v in unique_values_new[label]:
        v_cleaned = data_preprocessing(v, filtered_values, units_list, label)
        unique_values_new_cleaned[label].append(v_cleaned)
        
# unique_values_new_cleaned

In [42]:
for label in unique_values_new_cleaned:
    unique_values_new_cleaned[label] = sorted(list(set(unique_values_new_cleaned[label])))

In [43]:
for label in UNIQUE_VALUES:
    UNIQUE_VALUES[label] += unique_values_new_cleaned[label]
    UNIQUE_VALUES[label] = sorted(list(set(UNIQUE_VALUES[label])))

In [44]:
json_path2 = filename + '_preprocessed.json'
with open(json_path2, 'w', encoding="utf-8") as fp:
    json.dump(UNIQUE_VALUES, fp, indent=2)