In [1]:
import pandas as pd
import random
import numpy as np

In [2]:
df1 = pd.read_csv("./data/PROPERTY_old.csv")
df2 = pd.read_csv("./data/PROPERTY.csv")
df3 = pd.read_csv("./data/TDS_MAPPING.csv")
df4 = pd.read_csv("./data/CTQ.csv")

In [3]:
df1[["PROPERTY_NAME", "VALUE_ASSMNT_SI", "UNIT_OF_MEAS_SI"]]

                        PROPERTY_NAME VALUE_ASSMNT_SI UNIT_OF_MEAS_SI
0                    DTUL at 0.45 MPa             190              °C
1                             Density             940           kg/m³
2      Charpy notched impact strength             3.5           kJ/m²
3      Charpy notched impact strength               9           kJ/m²
4                    Flexural modulus           11000             MPa
...                               ...             ...             ...
22053         Tensile strain at break       10.000001               %
22054         Tensile strain at break       10.000000               %
22055         Tensile strain at break       50.000001               %
22056         Tensile strain at break       10.000000               %
22057         Tensile strain at break        4.000000               %

[22058 rows x 3 columns]

In [4]:
# df1["MODIFIER"] = df1["VALUE_ASSMNT_SI"] + " " + df1["UNIT_OF_MEAS_SI"]
df1["MODIFIER"] = df1["UNIT_OF_MEAS_SI"]
df1[["PROPERTY_NAME", "MODIFIER"]]

                        PROPERTY_NAME MODIFIER
0                    DTUL at 0.45 MPa       °C
1                             Density    kg/m³
2      Charpy notched impact strength    kJ/m²
3      Charpy notched impact strength    kJ/m²
4                    Flexural modulus      MPa
...                               ...      ...
22053         Tensile strain at break        %
22054         Tensile strain at break        %
22055         Tensile strain at break        %
22056         Tensile strain at break        %
22057         Tensile strain at break        %

[22058 rows x 2 columns]

In [5]:
# df2["MODIFIER"] = df2["VALUE_ASSMNT_SI"] + " " + df2["UNIT_OF_MEAS_SI"]
df2["MODIFIER"] = df2["UNIT_OF_MEAS_SI"]
df2[["PROPERTY_NAME", "MODIFIER"]]

                 PROPERTY_NAME MODIFIER
0          Melting temperature       °C
1              Tensile modulus      MPa
2      Tensile stress at yield      MPa
3                      Density    kg/m³
4                      Density    kg/m³
...                        ...      ...
22232  Tensile strain at break        %
22233  Tensile strain at break        %
22234  Tensile strain at break        %
22235  Tensile strain at break        %
22236  Tensile strain at break        %

[22237 rows x 2 columns]

In [6]:
df3[["TDS_PROPERTY", "TDS_UNIT"]]

                                           TDS_PROPERTY TDS_UNIT
0                                       % Crystallinity        %
1                                           24 hr, 23°C        %
2                            96% H2so4 (sulphuric Acid)    cm3/g
3                                   Abrasion Resistance        %
4                                   Abrasion resistance      mm3
...                                                 ...      ...
2706  Coef. of Linear Thermal Expansion, Parallel, m...      NaN
2707                       Dielectric Constant (100 Hz)      NaN
2708                        Dielectric Constant (1 MHz)      NaN
2709                             Charpy Impact Strength    kJ/m²
2710                                  Rockwell Hardness  M-Scale

[2711 rows x 2 columns]

In [7]:
df4

,USER_ENTERS,CEED_PROPERTY,TEST_METHOD,POLYMER,DB_VAR,SYNONYMS,MODIFIERS_LOW_RANGE,MODIFIERS_MEDIUM_RANGE,MODIFIERS_HIGH_RANGE,REPR_MODIFIER_LOW,REPR_MODIFIER_MEDIUM,REPR_MODIFIER_HIGH,MIN,INTERVAL_33_PERCENTILE,INTERVAL_2_66_PERCENTILE,MAX
0,Dk,"Dielectric constant (Dk), 1MHz",IEC 60250,ALL,elec_dielec_const_iec_1MHz,NaN,low; very low;,standard; typical; intermediate; common; fair;...,high; very high,low,moderate,high,2.70,3.81,4.00,32.0
1,Dissipation factor,"Dissipation factor, 1MHz",IEC 60250,ALL,elec_diss_fact_iec_1MHz,NaN,low; very low;,standard; typical; intermediate; common; fair;...,high; very high,low,moderate,high,0.03,50.00,80.00,1500.0
2,Electrical strength,"Electric strength, 23Â°C (AC)",IEC 60243-1,ALL,elec_elec_strgth_23C_AC_kV_mm,NaN,low; very low;,standard; typical; intermediate; common; fair;...,high; very high,low,moderate,high,2.40,22.25,35.00,59.0
3,Flexural Strength,"Flexural Modulus, 23Â°C",ISO 178,ALL,mec_flex_mod_iso_23_Mpa,Flexural performance; Rigid; Rigidity; Bend St...,lower; inferior; low,standard; typical; good; intermediate; common;...,maximum; best; superior; elevated; great; exce...,low,moderate,high,950.00,2800.00,9000.00,41000.0
4,Stiffness at High Temp,"Flexural Modulus, 80Â°C",ISO 178,ALL,mec_flex_mod_iso_80_Mpa,NaN,lower; inferior; low,standard; typical; good; intermediate; common;...,maximum; best; superior; elevated; great; exce...,low,moderate,high,450.00,5550.00,7200.00,13000.0
5,Hardness,"Ball indentation hardness, 30s",ISO 2039-1,ALL,mec_indent_hard_Mpa,NaN,low; very low;,standard; typical; intermediate; common; fair;...,high; very high,low,moderate,high,52.00,144.00,180.00,345.0
6,Toughness,Notched Charpy Impact,ISO 179/1eA,ALL,mec_notch_23_kJ_m2,Impact; impact resistance; durability; tough; ...,weak; lower; inferior; low,standard; typical; good; intermediate; common;...,maximum; best; superior; elevated; great; exce...,low,moderate,high,0.90,6.00,10.50,100.0
7,Mechanical Strength,Tensile Modulus,"ISO 527-1, -2",ALL,mec_ten_mod_MPa,Stiffness;Mechanical Strength; Mechanical Beha...,weak; lower; inferior; low,standard; typical; good; intermediate; common;...,maximum; best; superior; elevated; great; exce...,low,moderate,high,950.00,3200.00,9700.00,37277.0
8,Density,Density,ISO 1183,ALL,phy_dens_iso_kg_m3,Dense; Heavy,lower; inferior; low,standard; typical; good; intermediate; common;...,maximum; best; superior; elevated; great; exce...,low,moderate,high,890.00,1310.00,1410.00,2030.0
9,Melt index,"Melt flow rate, MFR",ISO 1133,ALL,phy_flow_rate_g_10min,Flow; Flowability; Flow rate,lower; inferior; low,standard; typical; good; intermediate; common;...,maximum; best; superior; elevated; great; exce...,low,moderate,high,0.10,3.00,9.02,75.0
10,Moisture absorption,"Humidity absorption, 23Â°C/50%RH",ISO 62,ALL,phy_humid_abs_per,NaN,low; excellent; superior; exceptional; best; o...,standard; typical; good; intermediate; common;...,poor; high; inferior;,low,moderate,high,0.00,0.20,1.50,3.5
11,Dimensional Stability,Mold Shrinkage,"ISO 294-4, 2577",ALL,phy_mold_shrk_par_Avg_per,Dimensional; precise; dimensional precision,best; superior; great; exceptional; really goo...,standard; typical; good; intermediate; common;...,low; poor; inferior,high,moderate,low,0.00,0.45,1.70,3.2
12,Thermal expansion,"Coeff. of linear therm expansion, parallel",ISO 11359-2,ALL,them_coef_lin_exp_par,Dimensional stability in elevated temp,best; superior; great; exceptional; really goo...,standard; typical; good; intermediate; common;...,low; poor; inferior,high,moderate,low,-0.02,0.44,1.10,1.5
13,Temperature performance,DTUL @ 1.8 Mpa,"ISO 75-1, -2",ALL,them_dtul_18_MPa_C,NaN,lower; inferior; low,standard; typical; good; intermediate; common;...,maximum; best; superior; elevated; great; exce...,low,moderate,high,38.00,100.00,210.00,340.0

In [8]:
def add_at(text, split_by=","):
    if split_by=="(":
        text_splits = text.split("(")
        text_splits = [i.strip() for i in text_splits]
        use_at = 0
        
        for i in range(1, len(text_splits)):
            if text_splits and (text_splits[i][:1].isdigit() or text_splits[i][:1] in ['+', '-']):
                use_at = i
                break

        if use_at:
#             print("at " + prop_name[use_at])
            text_splits[use_at] = "at " + text_splits[use_at]
            text = "(".join(text_splits)
            
    else:
        text_splits = text.split(",")
        text_splits = [i.strip() for i in text_splits]
        use_at = 0
        for i in range(1, len(text_splits)):
            if text_splits and (text_splits[i][:1].isdigit() or text_splits[i][:1] in ['+', '-']):
                use_at = i
                break

        if use_at:
    #         print("at " + text_splits[use_at-1])
            text_splits[use_at] = "at " + text_splits[use_at]
            text = ", ".join(text_splits)   

    return text

In [9]:
property_details = {}
remove = ["-", "--"]
for property_name, group in df1.groupby('PROPERTY_NAME'):
    property_name = property_name.strip()
    property_names = [property_name]
    split = False
    
    if ',' in property_name: 
        property_name = add_at(property_name, ",")
    elif '(' in property_name:
        property_name = add_at(property_name, "(")
        
    if ',' in property_name:
        property_name = property_name.split(",")
        for i in range(1, len(property_name)+1):
            prop_names = property_name[0: i]
            if len(prop_names) > 1:
                prop_name = " ".join(prop_names)
#                 prop_name2 = ",".join(prop_name)
#                 property_names.extend([prop_name1, prop_name2])
                property_names.append(prop_name)
            else:
                property_names.append(prop_names[0])
            
        split = True
        #"Tear strength, Method Ba, perpendicular" >>>>>>>>>>>"Tear strength"
    else:
        pass
        
   
    #group['modifier'] = group["VALUE_ASSMNT_SI"] + " " + group["UNIT_OF_MEAS_SI"]
    group['modifier'] = group["UNIT_OF_MEAS_SI"]
    modifiers = list(group['modifier'].dropna().unique())
    modifiers = [modifier.strip() for modifier in modifiers]
    modifiers = [i for i in modifiers if i]
    modifiers = [i for i in modifiers if i not in remove]
    
    property_names = list(set(property_names))
#     if len(property_names) > 1:
#         print(property_names, "\n")
    for p in property_names:
        if "(" in p and ")" not in p:
            p = p.replace("(","")
        
        if '@ ' in p:
            p = p.replace('@',random.choice(['at','@']))
        else:
            pass
        
        if p in property_details:
            property_details[p] = list(set(property_details[p] + modifiers))
        else:
            property_details[p] = modifiers
            
# property_details

In [10]:
len(property_details)

308

In [11]:
for property_name, group in df2.groupby('PROPERTY_NAME'):
    property_name = property_name.strip()
    property_names = [property_name]
    split = False
    
    if ',' in property_name: 
        property_name = add_at(property_name, ",")
    elif '(' in property_name:
        property_name = add_at(property_name, "(")
    
    if ',' in property_name:
        property_name = property_name.split(",")
        for i in range(1, len(property_name)+1):
            prop_names = property_name[0: i]
            if len(prop_names) > 1:
                prop_name = " ".join(prop_names)
#                 prop_name2 = ",".join(prop_name)
#                 property_names.extend([prop_name1, prop_name2])
                property_names.append(prop_name)
            else:
                property_names.append(prop_names[0])
            
        split = True
        #"Tear strength, Method Ba, perpendicular" >>>>>>>>>>>"Tear strength"
    else:
        pass
        
   
    #group['modifier'] = group["VALUE_ASSMNT_SI"] + " " + group["UNIT_OF_MEAS_SI"]
    group['modifier'] = group["UNIT_OF_MEAS_SI"]
    modifiers = list(group['modifier'].dropna().unique())
    modifiers = [modifier.strip() for modifier in modifiers]
    modifiers = [i for i in modifiers if i]
    modifiers = [i for i in modifiers if i not in remove]
    
    property_names = list(set(property_names))
#     if len(property_names) > 1:
#         print(property_names, "\n")
    for p in property_names:
        
        if "(" in p and ")" not in p:
            p = p.replace("(","")
                
        if '@ ' in p:
            p = p.replace('@',random.choice(['at','@']))
        else:
            pass
        
        if p in property_details:
            property_details[p] = list(set(property_details[p] + modifiers))
        else:
            property_details[p] = modifiers
            
# property_details

In [12]:
len(property_details)

322

In [13]:
for property_name, group in df3.groupby('TDS_PROPERTY'):
    property_name = property_name.strip()
    property_names = [property_name]
    split = False
    
    if ',' in property_name: 
        property_name = add_at(property_name, ",")
    elif '(' in property_name:
        property_name = add_at(property_name, "(")
    
    if ',' in property_name:
        
        prop = property_name.split(",")[0]
        if "(" in prop and ")" not in prop :
            prop = prop.split("(")[0]
            property_names.append(prop)
        
        property_name = property_name.split(",")
        for i in range(1, len(property_name)+1):
            prop_names = property_name[0: i]
            if len(prop_names) > 1:
                prop_name = " ".join(prop_names)
#                 prop_name2 = ",".join(prop_name)
#                 property_names.extend([prop_name1, prop_name2])
                property_names.append(prop_name)
            else:
                property_names.append(prop_names[0])
            
        split = True
        #"Tear strength, Method Ba, perpendicular" >>>>>>>>>>>"Tear strength"
    else:
        pass
        
   
    modifiers = list(group['TDS_UNIT'].dropna().unique())
    modifiers = [modifier.strip() for modifier in modifiers]
    modifiers = [i for i in modifiers if i]
    modifiers = [i for i in modifiers if i not in remove]
    
    property_names = list(set(property_names))
#     if len(property_names) > 1:
#         print(property_names, "\n")
    for p in property_names:

        if "(" in p and ")" not in p:
            p = p.replace("(","")
                
        if '@ ' in p:
            p = p.replace('@',random.choice(['at','@']))
        else:
            pass
        
        if p in property_details:
            property_details[p] = list(set(property_details[p] + modifiers))
        else:
            property_details[p] = modifiers
            
# property_details

In [14]:
p_synonyms = df4['SYNONYMS'].str.split(";", expand=True)

In [15]:
m1 = df4['MODIFIERS_LOW_RANGE'].str.split(";", expand=True)

In [16]:
m2 = df4['MODIFIERS_MEDIUM_RANGE'].str.split(";", expand=True)

In [17]:
m3 = df4['MODIFIERS_HIGH_RANGE'].str.split(";", expand=True)

In [18]:
# property_details.keys()

In [19]:
df1.drop_duplicates(subset="PROPERTY_NAME", inplace=True)
df2.drop_duplicates(subset="PROPERTY_NAME", inplace=True)
# df3.drop_duplicates(subset="TDS_PROPERTY", inplace=True)

In [20]:
# property_details2

In [21]:
df1[["PROPERTY_NAME", "MODIFIER"]]

                                        PROPERTY_NAME MODIFIER
0                                    DTUL at 0.45 MPa       °C
1                                             Density    kg/m³
2                      Charpy notched impact strength    kJ/m²
4                                    Flexural modulus      MPa
6                               Elongational Stress F      MPa
...                                               ...      ...
18667   Compression set, 70°C, 168h, Type 1, Method B        %
19599              Dielectric Constant, 60Hz, 2.01 mm        -
20877  Compression set, 100°C, 300h, Type 1, Method B        %
21329              Compression set, 23°C, 70h, Type A        %
21478               Dielectric Constant 60Hz, 2.01 mm        -

[202 rows x 2 columns]

In [22]:
df2[["PROPERTY_NAME", "MODIFIER"]]

                                        PROPERTY_NAME MODIFIER
0                                 Melting temperature       °C
1                                     Tensile modulus      MPa
2                             Tensile stress at yield      MPa
3                                             Density    kg/m³
5                                     DTUL at 1.8 MPa       °C
...                                               ...      ...
17919   Compression set, 70°C, 168h, Type 1, Method B        %
19506              Dielectric Constant, 60Hz, 2.01 mm        -
19534  Compression set, 100°C, 300h, Type 1, Method B        %
20296               Dielectric Constant 60Hz, 2.01 mm        -
21514              Compression set, 23°C, 70h, Type A        %

[202 rows x 2 columns]

In [23]:
property_list_new = ['Specific Resistivity','Volume resistivity','Surface resistivity','Dissipation factor','Tensile stress at break',
'Tensile strain at break','Izod impact notched','Emission of organic compounds','Glow wire flammability index',
'Melt volume rate','Poissons ratio','Water absorption','Burning rate','Comparative tracking index',
'compressive stress']

additional_properties="Stiffness, Mechanical Strength, Mechanical Behavior, Mechanical Resistance, mechanical properties, Deformation, Deformation stability, Flexibility, Mechanical performance, Modulus, Strength, Tensile strength, Dense, Heavy, Impact, impact resistance, durability, tough, solidity, impact resistant, Dimensional, precise, dimensional precision, Impact, impact resistance, durability, tough, solidity, impact resistant, Thermal resistance, use temperature, Flexural performance, Rigid, Rigidity, Stiffness, Flow, Flowability, Flow rate, Toughness, Dimensional Stability, Toughness, Moisture absorption, Thermal expansion, Dissipation factor, Temperature performance, Electrical strength, Stiff, Stiffness at High Temp, Melt index"
# additional_properties = additional_properties.lower()
additional_properties = additional_properties.split(", ")
property_list_new += additional_properties

for i in property_list_new:
    if i in property_details:
        print(i)
    else:
        property_details[i] = []

Specific Resistivity
Volume resistivity
Surface resistivity
Dissipation factor
Tensile stress at break
Tensile strain at break
Izod impact notched
Emission of organic compounds
Glow wire flammability index
Melt volume rate
Poissons ratio
Water absorption
Burning rate
Comparative tracking index
Tensile strength
Impact
Impact
impact resistance
durability
tough
solidity
impact resistant
Stiffness
Flowability
Toughness
Moisture absorption
Dissipation factor

In [24]:
final_df = pd.DataFrame()

keys = []
modifier = []
modifiers = []
for k,v in property_details.items():
    keys.append(k)
    if v:
        modifier.append(v[0])
    else:
        modifier.append("")
    modifiers.append(";".join(v))

final_df["PROPERTY_NAME"] = keys
final_df["MODIFIER"] = modifier
final_df["ALL MODIFIERS"] = modifiers
final_df

                       PROPERTY_NAME MODIFIER ALL MODIFIERS
0     Apparent viscosity at 1200 1/s     Pa s          Pa s
1      Apparent viscosity at 200 1/s     Pa s          Pa s
2                     Arc resistance      sec  sec;S;s;sec.
3           Average molecular weight    g/mol         g/mol
4              Average particle size       µm         µm;um
...                              ...      ...           ...
1851         Temperature performance
1852             Electrical strength
1853                           Stiff
1854          Stiffness at High Temp
1855                      Melt index

[1856 rows x 3 columns]

In [25]:
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.strip().str.lower()
final_df["MODIFIER"] = final_df["MODIFIER"].str.strip().str.lower()
final_df["ALL MODIFIERS"] = final_df["ALL MODIFIERS"].str.strip().str.lower()

In [26]:
replace_prop = [
    "bar flow 320℃", "heat deflection temperature 1.8mpa", "un notched charpy impact -30 edgewise",
    "compressive stress at 1 / 2 / 5 % nominal strain (10) -", 
    "water absorption at saturation in water of 23 °c (73°f)", 
    "limiting pv at 0.1 / 1 m/s cylindrical sleeve bearings", "izod notched impact strength iso 180/a (23°c)", 
    "surface resistivity 23°c 50% rh", 
    "clte flow (23°c) -", "molding shrinkage flow -", "relative permittivity εr : at 1 mhz -", 
    "notched izod impact 73°f(23°c)", "average mv(10 g/mol) 6", "oxygen index 2", "strain at break 80°c", 
    "average molar mass (average molecular weight) (1)", 
    "drying time*", "continuous allowable service temperature in air (20.000 hrs) (3)", 
    "back pressure **", "heat distortion temperature 18.5kgf/cm2", "shear strength 23℃", 
    'relative volume loss during wear test sand-slurry" : tivar® 1000=100"', 
    "compressive stress at 1 / 2 / 5 % nominal strain", "burning behavior ul 94", "tensile modulus of elasticity (10) -", 
    "deflection temperature at 0.46 mpa (66 psi)", "dynamic coefficient of friction (-)", 
    "water vapor transmission rate at 23 â„ƒ /85%r.h.", 
    "flexural modulus of elasticity -", "average spec. heat capacity 20-150 â„ƒ", 
    "melt volume-flow rate mvr at 190 °c and 10 kg", "heat deflection temperature 264psi", 
    "insulation resistance 3 (90°c)", "min. service temperature (5)", "unnotched izod impact 73°f (23°c)", 
    "taber abrasion resistance 1000 cycles", "flammability fmvss302", "hydrolytic stability 2", 
    "burning rate. thickness 1 mm", "strain at break 80c", "stress 10% deformation", 
    "insulation resistance 1 (90°c)", "min. service temperature (4)", 
    "hdt 0.45mpa", "flexural modulus of elasticity -", 
    "tensile modulus - chord 1", "elongation at break 23℃", "% crystallinity", 
    "heat deflection temperature: method a: 1.8 mpa (264 psi)", 
    'relative volume loss during a wear test in sand/water-slurry" ; tivar®1000 = 100"', 
    "compression set, 100°c, 22h, type 1, method b", "dielectric constant, 60hz, 1.93 mm", 
    "dielectric constant, 60hz, 1.96 mm", "compression set, 23°c, 168h, type a", 
    "tear strength, method ba, perpendicular", "electric strength, 23°c (ac)", 
    "elongation at break elast, perpendicular", "electric strength, 23°c (dc)", 
    "flame rating, 1.1 mm", "dissipation factor 23℃、60%rh、1mhz"]

for i in replace_prop:
    if i in list(final_df["PROPERTY_NAME"]):
        pass
    else:
        print(i)

In [27]:
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("bar flow 320℃","bar flow at 320℃")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("heat deflection temperature 1.8mpa","heat deflection temperature at 1.8mpa")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("un notched charpy impact -30 edgewise","unnotched charpy impact -30 edgewise")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("compressive stress at 1 / 2 / 5 % nominal strain (10) -","compressive stress at 2% nominal strain")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("water absorption at saturation in water of 23 °c (73°f)","water absorption at 23 °c")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("limiting pv at 0.1 / 1 m/s cylindrical sleeve bearings","limiting pv at 0.1m/s cylindrical sleeve bearings")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("izod notched impact strength iso 180/a (23°c)","izod notched impact strength")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("surface resistivity 23°c 50% rh","surface resistivity")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("clte flow (23°c) -","clte flow (23°c)")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("molding shrinkage flow -","molding shrinkage flow")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("relative permittivity εr : at 1 mhz -","relative permittivity")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("notched izod impact 73°f(23°c)","notched izod impact")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("average mv(10 g/mol) 6","average mv")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("oxygen index 2","oxygen index")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("strain at break 80°c","strain at break")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("average molar mass (average molecular weight) (1)","average molar mass")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("drying time*","drying time")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("continuous allowable service temperature in air (20.000 hrs) (3)","continuous allowable service temperature in air")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("back pressure **","back pressure")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("heat distortion temperature 18.5kgf/cm2","heat distortion temperature")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("shear strength 23℃","shear strength at 23℃")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('relative volume loss during wear test sand-slurry" : tivar® 1000=100"','relative volume loss during wear test sand-slurry')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("compressive stress at 1 / 2 / 5 % nominal strain","compressive stress at nominal strain")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("burning behavior ul 94","burning behavior")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("tensile modulus of elasticity (10) -","tensile modulus of elasticity")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("deflection temperature at 0.46 mpa (66 psi)","deflection temperature at 0.46 mpa")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("dynamic coefficient of friction (-)","dynamic coefficient of friction")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("water vapor transmission rate at 23 â„ƒ /85%r.h.","water vapor transmission rate")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("flexural modulus of elasticity -","flexural modulus of elasticity -")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("average spec. heat capacity 20-150 â„ƒ","average spec. heat capacity")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("melt volume-flow rate mvr at 190 °c and 10 kg","melt volume-flow rate mvr")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("heat deflection temperature 264psi","heat deflection temperature")

final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("insulation resistance 3 (90°c)","insulation resistance")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("min. service temperature (5)","min. service temperature")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("unnotched izod impact 73°f (23°c)","unnotched izod impact at 73°f")

final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("taber abrasion resistance 1000 cycles","taber abrasion resistance")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("flammability fmvss302","flammability")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("hydrolytic stability 2","hydrolytic stability")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("burning rate. thickness 1 mm","burning rate. thickness")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("strain at break 80c","strain at break")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("stress 10% deformation","stress at 10% deformation")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("insulation resistance 1 (90°c)","insulation resistance")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("min. service temperature (4)","min. service temperature")

final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("hdt 0.45mpa","hdt at 0.45mpa")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("flexural modulus of elasticity -","flexural modulus of elasticity")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("tensile modulus - chord 1","tensile modulus - chord")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("elongation at break 23℃","elongation at break")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("% crystallinity","crystallinity")

final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("heat deflection temperature: method a: 1.8 mpa (264 psi)","heat deflection temperature")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('relative volume loss during a wear test in sand/water-slurry" ; tivar®1000 = 100"','relative volume loss during a wear test in sand/water-slurry')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("compression set, 100°c, 22h, type 1, method b","compression set type 1 method b")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("dielectric constant, 60hz, 1.93 mm","dielectric constant at 60hz")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("dielectric constant, 60hz, 1.96 mm","dielectric constant at 1.96 mm")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("compression set, 23°c, 168h, type a","compression set type a")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("tear strength, method ba, perpendicular","tear strength")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("electric strength, 23°c (ac)","electric strength at 23°c (ac)")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("elongation at break elast, perpendicular","perpendicular elongation at break")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("electric strength, 23°c (dc)","electric strength at 23°c (dc)")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("flame rating, 1.1 mm","flame rating at 1.1 mm")
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace("dissipation factor 23℃、60%rh、1mhz","dissipation factor at 23℃")

In [28]:
to_remove = ["24 hr",
"charpy notced impact strength",
 "flame rating 3",
 "ti density",
 "coefficient of linear thermal expansion (23 to 100°c) (73°f to 210°f)",
 "direction",
 "load",
 "heat deflection temperature 4.6 kgf/cm²",
 "limiting pv at 0.1 / 1 m/s cylindrical sleeve bearings", "limiting pv at 0.1m/s cylindrical sleeve bearings"
 "96% h2so4 (sulphuric acid)",
 "ul94",
 "colour; black (bk)",
 "color no.",
 "flexural modulus 23℃",
 "particles > 250 um",
 "volume resistivity 23°c 50% rh",
 "dissipation factor 23℃、60%rh、1mhz",
 "flexural stress (23°c) iso 178",
 "flammability: ul 94 (3 mm (1/8 in.)) (5)",
 "density 23℃","charpy impact strength notched (double 14°) (14) - -",
 "water absorption 23 °c (69%) rh",
 "impact",
 "tensile strength (9) -",
 "density / specific gravity",
"tensile strain at yield(9) -",
"tensile strength at yield 73°f",
"tensile strain at break (9) -",
"coefficient of linear thermal expansion (-40 to 150 °c) (-40 to 300°f)",
"molding shrinkage flow - (0.126 in (3.20 mm))",
"deflection temperature at 1.8 mpa (264 psi)",
"melt volume-flow rate (mvr) (190°c/2.16 kg)",
"heat deflection temperature a",
"charpy impact strength unnotched (13) -",
"flexural modulus - chord 1",
"izod notched impact strength iso 180/a (-30 °c)",
"mold shrinkage x flow 2mm",
"tensile modulus 80°c",
"vn at 0.5% in sulfuric acid",
"tensile modulus 80°c",
"flexural stress 2",
"electric strength k20/p50",
"clte flow -",
"charpy notched impact strength (23â„ƒ)",
"colour",
"dielectric constant 23℃、60%rh、1mhz",
"arc resistance 2","particles > 300 um",
"flexural strength 23℃","insulation resistance 2 (90°c)","color","gloss",
 "flexural modulus 2","flexural modulus 1","direction)","charpy impact strength notched -",
 "tensile strength 23℃","filler","flexural modulus (160°c)","molding shrinkage 1",
 "ball pressure test 1","charpy impact strength double 14° notched -","flammability hb 3mm",
 "tensile strength 80c","compression set, 23°c, 22h, type a","compression set, 100°c, 300h, type a",
     "compression set, 23°c, 22h, type 1, method b","dielectric constant 60hz, 1.96 mm",
 "compression set, 100°c, 70h, type a","flame rating, 1.7 mm","flame rating, 1.0 mm","dielectric strength, 2.0 mm",
"compression set, 23°c, 168h, type 1, method b","dielectric constant, 60hz, 2.03 mm",
"compression set, 100°c, 168h, type 1, method b","volume resistivity, 23°c","dielectric constant, 60hz, 2.01 mm",
"dielectric constant 60hz, 1.98 mm","compression set, 100°c, 168h, type a","volume resistivity, 2.0 mm",
"dielectric constant 60hz","compression set, 100°c, 22h, type a","compression set, 100°c, 70h, type 1, method b",
"compression set, 70°c, 168h, type a","flame rating, 1.6 mm","ompression set, 70°c, 168h, type 1, method b",
"flame rating, 3.0 mm","compression set, 23°c, 70h, type a"]

for i in to_remove:
    if i in list(final_df["PROPERTY_NAME"]):
        pass
    else:
        print(i)
        
# "limiting pv at 0.1 / 1 m/s cylindrical sleeve bearings"
# "molding shrinkage flow"
        
final_df = final_df[~final_df.PROPERTY_NAME.isin(to_remove)]

direction
limiting pv at 0.1 / 1 m/s cylindrical sleeve bearings
limiting pv at 0.1m/s cylindrical sleeve bearings96% h2so4 (sulphuric acid)
dissipation factor 23℃、60%rh、1mhz
molding shrinkage flow - (0.126 in (3.20 mm))
ompression set, 70°c, 168h, type 1, method b

In [29]:
final_df

                       PROPERTY_NAME MODIFIER ALL MODIFIERS
0     apparent viscosity at 1200 1/s     pa s          pa s
1      apparent viscosity at 200 1/s     pa s          pa s
2                     arc resistance      sec  sec;s;s;sec.
3           average molecular weight    g/mol         g/mol
4              average particle size       µm         µm;um
...                              ...      ...           ...
1851         temperature performance
1852             electrical strength
1853                           stiff
1854          stiffness at high temp
1855                      melt index

[1773 rows x 3 columns]

In [30]:
unique_df = pd.read_excel("unique_values_29_05_23.xlsx")
unique_df

,Unnamed: 0,APPLICATION,BRAND,POLYMER,PROPERTY,MODIFIER,FILLER,FILLER_PERCENTAGE,FEATURE,COMPETITOR_GRADE,CERTIFICATION
0,0,automotive window lift-carrier and pulley,COOLPOLY,POM,ball indentation hardness,0.500000 %,glass fiber (short) load,9.0 %,fuel resistant,Delrin 100T,MS-AR-100 CGV
1,1,fan shroud-lamella,THERMX,tpv,"rti str, 1.5 mm",30 MPa,total load,40.0 %,hydrolysis resistant,SUPRAN PP1340,Tesla
2,2,off road switch,ecomid,lcp,glow wire ignition temperature,60 E-4/°C,glass bead load,1.5 %,wear resistant,Ultradur B 4300 G4 HiSpeed,Continental
3,3,automotive fuel filler neck-seal,celanyl,LCP,"tensile stress at 100%, perpendicular",0.22 mm,carbon fiber load,43.0 %,mineral reinforced,Siveras L304M35,CP3766
4,4,automotive vw golf-seal,ZENITE,PA*,flammability @1.6mm nom. thickn.,1.8 MPa,glass fiber (long) load,20.0 %,multi injection molding,ZYTEL HTN51G35HSL BK083,EMP 50
...,...,...,...,...,...,...,...,...,...,...,...
11770,11770,motor housings & covers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11771,11771,component for flexible printed circuit (fpc) c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11772,11772,electrical components,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11773,11773,automotive brake-assembly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11774,11774,check valve-wear disk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
property_list_new = list(set(list(unique_df["PROPERTY"])).difference(set(list(final_df["PROPERTY_NAME"].dropna()))))
property_details3 = {}
for i in property_list_new:
    property_details3[i] = []
        
diff_df = pd.DataFrame()

keys = []
modifier = []
modifiers = []
for k,v in property_details3.items():
    keys.append(k)
    if v:
        modifier.append(v[0])
    else:
        modifier.append("")
    modifiers.append(";".join(v))

diff_df["PROPERTY_NAME"] = keys
diff_df["MODIFIER"] = modifier
diff_df["ALL MODIFIERS"] = modifiers
diff_df

                                     PROPERTY_NAME MODIFIER ALL MODIFIERS
0                         volume resistivity, 23°c
1                     electric strength, 23°c (dc)
2              compression set, 100°c, 22h, type a
3              compression set, 100°c, 70h, type a
4                      dielectric strength, 2.0 mm
5               dielectric constant, 60hz, 1.96 mm
6           hot wire ignition @ 0.4mm nom. thickn.
7                             flame rating, 1.7 mm
8                             flame rating, 1.1 mm
9               compression set, 23°c, 22h, type a
10  compression set, 100°c, 168h, type 1, method b
11                      volume resistivity, 2.0 mm
12   compression set, 23°c, 168h, type 1, method b
13   compression set, 100°c, 22h, type 1, method b
14                            csa rating @ 0.84 mm
15                                          impact
16              compression set, 23°c, 70h, type a
17    compression set, 23°c, 22h, type 1, method b
18                            flame rating, 1.6 mm
19                    electric strength, 23°c (ac)
20                            flame rating, 3.0 mm
21                                             NaN
22         tear strength, method ba, perpendicular
23              dielectric constant, 60hz, 2.03 mm
24              dielectric constant, 60hz, 2.01 mm
25             compression set, 70°c, 168h, type a
26               dielectric constant 60hz, 1.98 mm
27               dielectric constant 60hz, 1.96 mm
28            compression set, 100°c, 168h, type a
29        elongation at break elast, perpendicular
30              dielectric constant, 60hz, 1.93 mm
31            compression set, 100°c, 300h, type a
32             compression set, 23°c, 168h, type a
33   compression set, 100°c, 70h, type 1, method b
34                            flame rating, 1.0 mm

In [32]:
final_df = pd.concat([final_df, diff_df], axis=0)

In [33]:
final_df.drop_duplicates(subset="PROPERTY_NAME", keep='last', inplace=True)

In [34]:
list(set(list(unique_df["PROPERTY"])).difference(set(list(final_df["PROPERTY_NAME"]))))

[]

In [35]:
# set(list(final_df["PROPERTY_NAME"])).difference(set(list(unique_df["PROPERTY"])))

In [36]:
final_df

                                    PROPERTY_NAME MODIFIER ALL MODIFIERS
0                  apparent viscosity at 1200 1/s     pa s          pa s
1                   apparent viscosity at 200 1/s     pa s          pa s
7                         brittleness temperature       °c            °c
10                                  clte above tg   e-4/°c        e-4/°c
11                                  clte below tg   e-4/°c        e-4/°c
..                                            ...      ...           ...
30             dielectric constant, 60hz, 1.93 mm
31           compression set, 100°c, 300h, type a
32            compression set, 23°c, 168h, type a
33  compression set, 100°c, 70h, type 1, method b
34                           flame rating, 1.0 mm

[1646 rows x 3 columns]

In [37]:
final_df.reset_index(drop=True, inplace=True)

In [38]:
final_df

                                      PROPERTY_NAME MODIFIER ALL MODIFIERS
0                    apparent viscosity at 1200 1/s     pa s          pa s
1                     apparent viscosity at 200 1/s     pa s          pa s
2                           brittleness temperature       °c            °c
3                                     clte above tg   e-4/°c        e-4/°c
4                                     clte below tg   e-4/°c        e-4/°c
...                                             ...      ...           ...
1641             dielectric constant, 60hz, 1.93 mm
1642           compression set, 100°c, 300h, type a
1643            compression set, 23°c, 168h, type a
1644  compression set, 100°c, 70h, type 1, method b
1645                           flame rating, 1.0 mm

[1646 rows x 3 columns]

In [39]:
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace(",", " ").str.replace("„", "").str.replace("˚", "°").str.replace("âºf", "°f").str.replace("âƒ", "°c").str.replace('（', "(").str.replace('）', ')').str.replace("âº", "").str.replace("â", "").str.replace(r'\s+', ' ', regex=True).str.strip()
final_df = final_df[final_df["PROPERTY_NAME"].notna()]
remove_feature = [set(list(final_df["PROPERTY_NAME"])).intersection(set(list(unique_df["FEATURE"])))]
print("remove_feature: ", remove_feature)
final_df = final_df[~final_df.PROPERTY_NAME.isin(remove_feature)]

final_df.drop_duplicates(subset="PROPERTY_NAME", inplace=True)
final_df.sort_values(by="PROPERTY_NAME", inplace=True)

remove_feature:  [{'injection molding'}]

In [40]:
final_df.reset_index(drop=True, inplace=True)
final_df

                   PROPERTY_NAME        MODIFIER   ALL MODIFIERS
0                     24 hr 23°c               %               %
1                  24 hr at 23°c               %               %
2     96% h2so4 (sulphuric acid)           cm3/g           cm3/g
3            abrasion resistance             mm3             mm3
4         additional information
...                          ...             ...             ...
1465   yield strain at 50 mm/min               %               %
1466                yield stress             mpa             mpa
1467      yield stress 50 mm/min             mpa             mpa
1468   yield stress at 50 mm/min             mpa             mpa
1469          youngs “e” modulus  mpa(psi x 105)  mpa(psi x 105)

[1470 rows x 3 columns]

In [41]:
final_df["MODIFIER"] = final_df["MODIFIER"].replace("--$", "", regex=True)
final_df["MODIFIER"] = final_df["MODIFIER"].replace("-$", "", regex=True)
final_df["MODIFIER"] = final_df["MODIFIER"].str.lower().str.strip()
final_df["MODIFIER"] = final_df["MODIFIER"].replace("", np.NaN)
# final_df["MODIFIER"] = final_df["MODIFIER"].str.replace("„", "").str.replace("˚", "°").str.replace("âºf", "°f").str.replace("âƒ", "°c").str.replace('（', "(").str.replace('）', ')').str.replace("âº", "").str.replace("â", "").str.replace(r'\s+', ' ', regex=True).str.strip()

In [42]:
final_df["ALL MODIFIERS"] = final_df["ALL MODIFIERS"].replace("--$", "", regex=True)
final_df["ALL MODIFIERS"] = final_df["ALL MODIFIERS"].replace("-$", "", regex=True)
final_df["ALL MODIFIERS"] = final_df["ALL MODIFIERS"].str.lower().str.strip()
final_df["ALL MODIFIERS"] = final_df["ALL MODIFIERS"].replace("", np.NaN)

In [43]:
final_df

                   PROPERTY_NAME        MODIFIER   ALL MODIFIERS
0                     24 hr 23°c               %               %
1                  24 hr at 23°c               %               %
2     96% h2so4 (sulphuric acid)           cm3/g           cm3/g
3            abrasion resistance             mm3             mm3
4         additional information             NaN             NaN
...                          ...             ...             ...
1465   yield strain at 50 mm/min               %               %
1466                yield stress             mpa             mpa
1467      yield stress 50 mm/min             mpa             mpa
1468   yield stress at 50 mm/min             mpa             mpa
1469          youngs “e” modulus  mpa(psi x 105)  mpa(psi x 105)

[1470 rows x 3 columns]

In [44]:
final_df = final_df[final_df["ALL MODIFIERS"].notna()]
final_df

                   PROPERTY_NAME        MODIFIER   ALL MODIFIERS
0                     24 hr 23°c               %               %
1                  24 hr at 23°c               %               %
2     96% h2so4 (sulphuric acid)           cm3/g           cm3/g
3            abrasion resistance             mm3             mm3
5                 aluminium (al)             ppm             ppm
...                          ...             ...             ...
1465   yield strain at 50 mm/min               %               %
1466                yield stress             mpa             mpa
1467      yield stress 50 mm/min             mpa             mpa
1468   yield stress at 50 mm/min             mpa             mpa
1469          youngs “e” modulus  mpa(psi x 105)  mpa(psi x 105)

[1173 rows x 3 columns]

In [45]:
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('charpy impact strength unnotched -',  'charpy impact strength unnotched')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('charpy notched impact strength - 40°f', 'charpy notched impact strength -40°f')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('charpy notched impact strength at - 40°f',  'charpy notched impact strength at -40°f')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('charpyimpact strength (double notched)', 'charpy impact strength (double notched)')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('impact strength (charpy) - 30°c', 'impact strength (charpy) -30°c')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('impact strength (charpy) at - 30°c', 'impact strength (charpy) at -30°c')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('mold shrinkagemachine direct on', 'mold shrinkage machine direction')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('notched charpy impact @-40c edgewise', 'notched charpy impact @ -40°c edgewise')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('notched impact strength (charpy) - 30°c', 'notched impact strength (charpy) -30°c')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('notched impact strength (charpy) at - 30°c', 'notched impact strength (charpy) at -30°c')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('tensile elongation@break', 'tensile elongation @ break')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('tensile strength@break', 'tensile strength @ break')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('ti average par cle size dp50', 'ti average particle size dp50')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('un notched charpy impact @-40c edgewise', 'un notched charpy impact @ -40c edgewise')
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('water absorption:', 'water absorption')

C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('charpy impact strength unnotched -',  'charpy impact strength unnotched')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('charpy notched impact strength - 40°f', 'charpy notched impact strength -40°f')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('charpy notched impact strength at - 40°f',  'charpy notched impact strength at -40°f')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('charpyimpact strength (double notched)', 'charpy impact strength (double notched)')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('impact strength (charpy) - 30°c', 'impact strength (charpy) -30°c')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('impact strength (charpy) at - 30°c', 'impact strength (charpy) at -30°c')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('mold shrinkagemachine direct on', 'mold shrinkage machine direction')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('notched charpy impact @-40c edgewise', 'notched charpy impact @ -40°c edgewise')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('notched impact strength (charpy) - 30°c', 'notched impact strength (charpy) -30°c')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('notched impact strength (charpy) at - 30°c', 'notched impact strength (charpy) at -30°c')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('tensile elongation@break', 'tensile elongation @ break')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('tensile strength@break', 'tensile strength @ break')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('ti average par cle size dp50', 'ti average particle size dp50')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('un notched charpy impact @-40c edgewise', 'un notched charpy impact @ -40c edgewise')
C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\1309763979.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].str.replace('water absorption:', 'water absorption')

In [46]:
to_remove = ['24 hr 23°c',
 '24 hr at 23°c',
 'bulkdensity',
 'charpy impact strength - 22°f',
 'charpy impact strength - 40°f',
 'charpy impact strength at - 22°f',
 'charpy impact strength at - 40°f',
 'charpy notched impact strength (+23 °c )',
 'charpy notched impact strength - 22°f',
 'charpy notched impact strength at - 22°f',
 'clte normal - 40-23 °c',
 'clte normal at - 40-23 °c',
 'clte parallel - 40-23 °c',
 'clte parallel at - 40-23 °c',
 'drying',
 'drying recommended',
 'heatdeflection temperature',
 'izod impact strength - 22°f',
 'izod impact strength at - 22°f',
 'izod notched impact strength - 40°f',
 'izod notched impact strength at - 40°f',
 'melting temperature (10oc/min)',
 'mold shrinkage(machine directi on)',
 'mold shrinkage(transverse dire ction)',
 'moleculer weight',
 'water absorption (23℃ 24hrs 1mmt)',
 'water absorption (23℃ at 24hrs 1mmt)',
 'water absorption (24 hr at 23℃)',
 'water absorption 23℃',
 'water absorption 23℃ at 24hrs',
  'water absorbtion']

final_df = final_df[~final_df.PROPERTY_NAME.isin(to_remove)]
final_df

                   PROPERTY_NAME        MODIFIER   ALL MODIFIERS
2     96% h2so4 (sulphuric acid)           cm3/g           cm3/g
3            abrasion resistance             mm3             mm3
5                 aluminium (al)             ppm             ppm
6               amino end groups          meq/kg          meq/kg
7          annealing temparature              °c              °c
...                          ...             ...             ...
1465   yield strain at 50 mm/min               %               %
1466                yield stress             mpa             mpa
1467      yield stress 50 mm/min             mpa             mpa
1468   yield stress at 50 mm/min             mpa             mpa
1469          youngs “e” modulus  mpa(psi x 105)  mpa(psi x 105)

[1142 rows x 3 columns]

In [47]:
final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].replace({'temparature': 'temperature'}, regex=True)

C:\Users\DSCAK2\AppData\Local\Temp\ipykernel_816\119339464.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PROPERTY_NAME"] = final_df["PROPERTY_NAME"].replace({'temparature': 'temperature'}, regex=True)

In [48]:
final_df.to_excel("property_name 6.xlsx", index=False)